### ISSUE TITLE
No response from Payout.

### ISSUE THREAD

**Issue by bdebever** [paypal/PayPal-PHP-SDK#1000]
### General information

* SDK/Library version: 1.13
* Environment: Sandbox
* Language, language version, and OS: PHP-SDK

### Issue description

Hi there, 

I am using the SDK to make a BatchPayout. I have been able to successfully make one payment, and I can see the payment, request and so in my account. However, I cannot make any other payment. 
Basically, my request is sent, I can see the API call in my Paypal Dashboard, but I don't have any info (just an orange exclamation point) - and I don't receive any response. 

Would you be able to assist? 

Please find a snippet of code below. 

Thanks; 

--
`public function createPayout($organization_name, $receiver_email, $amount)
    {

        $payout = new Payout();
        $senderBatchHeader = new PayoutSenderBatchHeader();

        $senderBatchHeader->setSenderBatchId(uniqid())
            ->setEmailSubject("You won a reward from " . $organization_name . "!");

        $senderItem = new PayoutItem();

        $senderItem->setRecipientType('EMAIL')
            ->setNote('Thanks for your feedback - we really appreciate it!')
            ->setReceiver($receiver_email)
            ->setAmount(new Currency('{
                        "value":"' . $amount . '",
                        "currency":"USD"
                    }'));

        $payout->setSenderBatchHeader($senderBatchHeader)
            ->addItem($senderItem);

        $request = clone $payout;

        $response = $this->callApi($payout);

        return [
            'type' => 'success',
            'response' => $response
        ];

    }

    /**
     * Call to the Paypal API
     *
     * @link https://github.com/paypal/PayPal-PHP-SDK
     *
     * @param $type 
     * @param array|string $data 
     * 
     * @return mixed
     */
    public function callApi($type, $data = null)
    {

        try {
            //TODO: switch on $type or [type => action]

            return $type->create(null, $this->apiContext);

        } catch (PayPalConnectionException $e) {

            $this->handleError($e);

        } catch (Exception $e) {

            return $e;

        }

    }`
`

**Comment by atnegrete** [comment]
How did you solve this, if you don't mind
