### ISSUE TITLE
Credit_card payment method must use credit_card or cardit_card_token funding instrument

### ISSUE THREAD

**Issue by wnaghuixin** [paypal/PayPal-PHP-SDK#1001]
{
    "name": "VALIDATION_ERROR",
    "details": [
        {
            "field": "payer",
            "issue": "Credit_card payment method must use credit_card or cardit_card_token funding instrument."
        }
    ],
    "message": "Invalid request. See details.",
    "information_link": "https://developer.paypal.com/docs/api/payments/#errors",
    "debug_id": "5594472299b46"
}

**Comment by pp-randy** [comment]
You need to provide the funding instrument as well.  Are you wanting to integrate direct credit card payments or PayPal Checkout?  This SDK does not support direct credit card integrations for new integrations please see in the [README.md#direct-credit-card-support](https://github.com/paypal/PayPal-PHP-SDK#direct-credit-card-support)

**Comment by wnaghuixin** [comment]
@pp-randy thk
