### ISSUE TITLE
Payout .. fail to create exception  upon user don't have the currency value

### ISSUE THREAD

**Issue by alien3d** [paypal/PayPal-PHP-SDK#1005]
Enviroment :Sandbox
OS: Mac Os
PHP : 5.6
composer version :    "paypal/rest-api-sdk-php": "^1.13",

Sample test by referring below code

https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payouts/CreateSinglePayout.php
Are it work ?

Yes  .Merchant Account have minus transaction amount and  and buyer receive the amount.

When it will not work

When the buyer don't have the currency upon the  merchant .

E.g 

Merchant have 100K USD  and buyer want to refund it using MYR.  
Merchant go into system and refund it and no respond..  
Try to send USD work. Try to send MYR don't work

Another testing since if the currency was issue .. 
So create a dummy sandbox account and default is myr
Send using MYR work.. Send via USD  don't fall any error .. 

Coder review 

The sample work fine and i think at first if it was

```
 ->setAmount(new \PayPal\Api\Currency('{
                        "value":"1.0",
                        "currency":"USD"
                    }'));
```

and it little a bit weird .So i changing to standard

```
        $currency = new Currency();
        $currency->setValue($invoiceAmount);
        $currency->setCurrency('MYR');

        $senderItem = new PayoutItem();
        $senderItem->setRecipientType('Email')
            ->setNote('Good Luck From our management ')
            ->setReceiver($payeeEmail)
            ->setSenderItemId("2014031400023")
            ->setAmount($currency);
```

Not sure are this is the main problem  

https://developer.paypal.com/docs/classic/api/currency_codes/

Malaysia Ringgit MYR
Note: This currency is supported as a payment currency and a currency balance for in-country PayPal accounts only.

I just want some exception if any failure transaction if user don't have the currency value

**Comment by xiaoleih41** [comment]
Both sender and receiver should have the specific currency open to do any transactions. If the funds was in USD, then refund should be in USD.  If the seller doesn't have MYR, he may block the payment not in the currency he is holding. So only send the currency that shows as the open balances in the receiver's account.

**Comment by pp-randy** [comment]
To add to the above answer, MYR can only be sent between two Malaysia accounts.

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been given.

**Comment by alien3d** [comment]
@xiaoleih41 @pp-randy   should be re  open the issue is not about the MYR sending  between two account, but the exception message saying the transaction rejected is required.. I have my own check if payid existed then consider as approved transaction.. no way I'm gonna check other currency if any rule involve.. We need exception

**Comment by xiaoleih41** [comment]
@alien3d If your payout account is a non-Malaysian account, it cannot receive MYR.  it's regulated by financial agreement that PayPal has with that specific country.  There's no exception can be made.

**Comment by alien3d** [comment]
@xiaoleih41  i mean error message exception not "exception so he/issue" . As developer ,we don't care much what is regulation but more care upon on how to deliver meaningfull error exception which customer can understand more like  ..  

`if (...)  Exception ($e) {   echo "this transaction cannot be proceed because of paypal with that specific country " } `

**Comment by pp-randy** [comment]
@alien3d we will look further into the error messaging for this use case.

**Comment by xiaoleih41** [comment]
@alien3d Can you please provide a debugId for us better report this issue?

**Comment by alien3d** [comment]
Sorry kinda late respond.. will try to get  debugid? later i will check out how to get it.

**Comment by xiaoleih41** [comment]
It should be in the header of the API response.

**Comment by xiaoleih41** [comment]
@alien3d  Please let us know if you can find the debugId for us further research the issue.

**Comment by xiaoleih41** [comment]
Close due to inactivity. Please resubmit when you have further information.
