### ISSUE TITLE
I get INVALID_PAYER_ID when I try to execute transaction.

### ISSUE THREAD

**Issue by lcaciobotariu** [paypal/PayPal-PHP-SDK#1008]
This is the scenario: The user come back from aproval URL at: [example.com/testpp-return.php?paymentId=PAY-4G380804961782949LITNEGA&token=EC-4B82324368158025G&PayerID=JC9KYD2P27Z78](url)

Then, I execute transaction using this payment object:

    PayPal\Api\Payment Object
    (
     [_propMap:PayPal\Common\PayPalModel:private] => Array
     (
        [id] => PAY-4G380804961782949LITNEGA
        [payer] => PayPal\Api\Payer Object
            (
                [_propMap:PayPal\Common\PayPalModel:private] => Array
                    (
                        [payment_method] => paypal
                        [payer_info] => PayPal\Api\PayerInfo Object
                            (
                                [_propMap:PayPal\Common\PayPalModel:private] => Array
                                    (
                                        [email] => test-buyer@email.com
                                        [payer_id] => JC9KYD2P27Z78
                                        [first_name] => test
                                        [last_name] => buyer
                                    )

                            )

                    )

            )

      )

    )

and I got Http response code 400 when accessing [https://api.sandbox.paypal.com/v1/payments/payment/PAY-4G380804961782949LITNEGA/execute]()

    {"name":"INVALID_PAYER_ID","message":"Payer ID is invalid","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"62fdad882ce5d"}

Why do I get this message even though I'm using the correct payer_id?

**Comment by xiaoleih41** [comment]
The ** payerId** doesn't match to the email: `test-buyer@email.com`

**Comment by lcaciobotariu** [comment]
Well, this is a public page, so here I replaced my test email address with test-buyer@email.com, but in reality I used the same email address as in the creation of the transaction.

**Comment by xiaoleih41** [comment]
Do you have a debugId?

**Comment by lcaciobotariu** [comment]
62fdad882ce5d

**Comment by xiaoleih41** [comment]
How do you pass the payerId and execute the payment.  Can you share your code on that?

**Comment by lcaciobotariu** [comment]
**testpaypal-create.php**

    <?php
    umask(0);
    require __DIR__  . '/vendor/autoload.php';
    include 'paypal-api-model.php';
    $data = array(
    'intent' => 'sale',
    'amount' => 23.89,
    'currency' => 'CAD', //optional
    'email' => 'axxxxxx-buyer@email.com',
    'first_name' => 'test', //optional
    'last_name' => 'buyer', //optional
    );
    $gateway = new PayPal_Api_Model();
    $response = $gateway->transaction($data);
    echo $response;`

The API respone is:

    Redirect user to approval_url: https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-15H956948A3164203
     { "intent": "sale", "payer": { "payment_method": "paypal", "payer_info": { "email": "axxxxxx-buyer@email.com", "first_name": "test", "last_name": "buyer" } }, "transactions": [ { "amount": { "total": "23.89", "currency": "CAD" }, "related_resources": [] } ], "redirect_urls": { "return_url": "http://example.com/testpaypal-return.php", "cancel_url": "http://example.com/testpaypal-cancel.php" }, "id": "PAY-1BT077292S426432HLIUAGGY", "state": "created", "create_time": "2017-12-06T14:47:55Z", "links": [ { "href": "https://api.sandbox.paypal.com/v1/payments/payment/PAY-1BT077292S426432HLIUAGGY", "rel": "self", "method": "GET" }, { "href": "https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-15H956948A3164203", "rel": "approval_url", "method": "REDIRECT" }, { "href": "https://api.sandbox.paypal.com/v1/payments/payment/PAY-1BT077292S426432HLIUAGGY/execute", "rel": "execute", "method": "POST" } ] }

I go to [https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-15H956948A3164203](), I confirm, then I'm redirected to [http://example.com/testpaypal-return.php?paymentId=PAY-1BT077292S426432HLIUAGGY&token=EC-15H956948A3164203&PayerID=JC9KYD2P27Z78]()

**testpaypal-return.php**

    <?php
    umask(0);
    require __DIR__  . '/vendor/autoload.php';
    include 'paypal-api-model.php';

    $paymentId = (isset($_GET['paymentId']) ? $_GET['paymentId'] : null );
    $token = (isset($_GET['token']) ? $_GET['token'] : null );
    $PayerID = (isset($_GET['PayerID']) ? $_GET['PayerID'] : null );

    if(is_null($paymentId) || is_null($token) || is_null($PayerID))
    {
        throw new Error('Missing input data');
    }

    $data = array(
    'payment_id' => $paymentId,
    'token' => $token,
    'payer_id' => $PayerID,
    'email' => 'axxxxxx-buyer@email.com',
    'first_name' => 'test',
    'last_name' => 'buyer',
    'amount' => 23.89,
    'currency' => 'CAD', //optional
    );

    // execute transaction
    $gateway = new PayPal_Api_Model();
    $response = $gateway->executeTransaction($data);
    echo $response;

The API response is:

    Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payment/PAY-1BT077292S426432HLIUAGGY/execute
    {"name":"INVALID_PAYER_ID","message":"Payer ID is invalid","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"f5a0fddaec89b"}

**paypal-api-model.php**

    <?php
    class PayPal_Api_Model
    {
    const INTENT_SALE = 'sale';
    const INTENT_REFUND = 'refund';

    protected $apiContext;

    public function __construct() {

        $this->apiContext = new \PayPal\Rest\ApiContext(
            new \PayPal\Auth\OAuthTokenCredential(
                'AYEzVFeitSV_xxxxmnVUzK2h2Fe4NQC',     // ClientID
                'EFkwJ_UaA4xxxxxxkArehW-X8ix_TFkk58Ig6rQ5'      // ClientSecret
            )
        );

    }

    function transaction($data = null)
    {
        $intent = (isset($data['intent']) ? $data['intent'] : self::INTENT_SALE);
        $response = null;

        if(is_null($data)){
            throw new Exception('No input data');
        }

        if($intent == self::INTENT_SALE)
        {
            $response = $this->_order($data);
        }
        else
        {
            $response = $this->_refund($data);
        }

        return $response;
    }

    public function executeTransaction($data)
    {
        $response = null;
        $payment = new \PayPal\Api\Payment();
        $payment->setId($data['payment_id'])
            ->setPayer($this->_getPayer($data));

        try {
            $execution = new \PayPal\Api\PaymentExecution();
            $execution->addTransaction($this->_getTransaction($data));
            $response = $payment->execute($execution, $this->apiContext);
        }
        catch (\PayPal\Exception\PayPalConnectionException $ex) {
            // This will print the detailed information on the exception.
            //REALLY HELPFUL FOR DEBUGGING
            $response = $ex->getData();
            print_r($ex->getMessage());
        }

        return $response;
    }

    private function _order($data)
    {
        $response = null;
        // After Step 2

        $payment = new \PayPal\Api\Payment();
        $payment->setIntent(self::INTENT_SALE)
            ->setPayer($this->_getPayer($data))
            ->setTransactions(array($this->_getTransaction($data)))
            ->setRedirectUrls($this->_getRedirectUrls());

        // After Step 3
        try {
            $response = $payment->create($this->apiContext);

            echo "\n\nRedirect user to approval_url: " . $payment->getApprovalLink() . "\n";
        }
        catch (\PayPal\Exception\PayPalConnectionException $ex) {
            $response = $ex->getData();
        }

        return $response;
    }


    private function _getPayer($data)
    {
        $payerInfo = new \PayPal\Api\PayerInfo();
        $payerInfo->setEmail($data['email']);
        if(isset($data['payer_id']))
        {
            $payerInfo->setPayerId($data['payer_id']);
        }
        if(isset($data['first_name']))
        {
            $payerInfo->setFirstName($data['first_name']);
        }
        if(isset($data['last_name']))
        {
            $payerInfo->setLastName($data['last_name']);
        }

        $payer = new \PayPal\Api\Payer();
        $payer->setPaymentMethod('paypal')
            ->setPayerInfo($payerInfo);

        return $payer;
    }

    private function _refund($data)
    {
        $response = null;

        $amount = new \PayPal\Api\Amount();
        $amount->setTotal(sprintf("%01.2f", $data['amount']))
            ->setCurrency((isset($data['currency']) ? $data['currency'] : 'CAD'));

        $refundRequest = new \PayPal\Api\RefundRequest();
        $refundRequest->setAmount($amount);
        if(isset($data['description']))
        {
            $refundRequest->setDescription($data['description']);
        }

        $sale = new \PayPal\Api\Sale();
        $sale->setId($data['transaction_id']);

        try {
            $response = $sale->refundSale($refundRequest, $this->apiContext);
        } catch (PayPal\Exception\PayPalConnectionException $ex) {
            $response = $ex->getData(); // Prints the detailed error message
        } catch (Exception $ex) {
            $response = $ex;
        }

        return $response;
    }

    private function _getRedirectUrls()
    {
        $redirectUrls = new \PayPal\Api\RedirectUrls();
        $redirectUrls->setReturnUrl('http://example.com/testpaypal-return.php')
            ->setCancelUrl('http://example.com/testpaypal-cancel.php');

        return $redirectUrls;
    }

    private function _getTransaction($data)
    {
        $amount = new \PayPal\Api\Amount();
        $amount->setTotal(sprintf("%01.2f", $data['amount']))
            ->setCurrency((isset($data['currency']) ? $data['currency'] : 'CAD'));

        $transaction = new \PayPal\Api\Transaction();
        $transaction->setAmount($amount);

        return $transaction;
    }
    }

**Comment by prakash-gangadharan** [comment]
Hi @lcaciobotariu , is this still an issue and do you have a recent debugIds?

**Comment by prakash-gangadharan** [comment]
It looks like this is no longer applicable, hence closing this issue out. Please feel to reopen if your still see this instances around.

Thanks!
