### ISSUE TITLE
Update Billing Plan - 400 Request Error

### ISSUE THREAD

**Issue by deep12650** [paypal/PayPal-PHP-SDK#1009]
### Issue description
I used the exact same code as defined as below in the sample but still giving 400 error. 
https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/billing/UpdatePlanPaymentDefinitions.php

It is creating connection and getting payment definitions ID and hitting following URL : 
`[Unknown Error] Uncaught PayPal\Exception\PayPalConnectionException: Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/billing-plans/P-8G9427685F322543GFDR6WXI.`

It is my code:
```
$createdPlan = Plan::get($plan->PlanId, $this->getContext());
        try {
            $patch = new Patch();
            $paymentDefinitions = $createdPlan->getPaymentDefinitions();
            $paymentDefinitionId = $paymentDefinitions[0]->getId();
            $patch->setOp('replace')
                ->setPath('/payment-definitions/' . $paymentDefinitionId)
                ->setValue(json_decode(
                    '{
                            "frequency": "'.$plan->Frequency.'",
                            "amount": {
                                "value": "'.$plan->Amount.'"
                            }
                    }'
                ));
            $patchRequest = new PatchRequest();
            $patchRequest->addPatch($patch);
            $createdPlan->update($patchRequest, $this->getContext());
        } catch (Exception $ex) {
            exit(1);
        }
        return;

```
Please do let me know how should I resolve. Even tried exact code as defined in the sample with static data. it is giving the same error.

* SDK/Library version: Latest 
* Environment: Sandbox 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: PHP MAMP macOS High Sierra /LAMP Ubuntu 16.04

**Comment by xiaoleih41** [comment]
Do you have a debug ID?

**Comment by xiaoleih41** [comment]
Close due to inactivity.
