### ISSUE TITLE
How can implement IPN ?

### ISSUE THREAD

**Issue by Martos** [paypal/PayPal-PHP-SDK#1010]
### General information

* SDK/Library version: Latest
* Environment: Sandbox
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: PHP, 7.1.3, Ubuntu Server 16.04

### Issue description
How can implement IPN with the SDK ?

**Comment by xiaoleih41** [comment]
Please follow the guide at the bottom of [this page](https://developer.paypal.com/docs/classic/products/instant-payment-notification/) to integrate IPN.

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been given
