### ISSUE TITLE
Save credential -> one payment: billing agreements / reference transactions ?

### ISSUE THREAD

**Issue by lorenzosfarra** [paypal/PayPal-PHP-SDK#1012]
Hi guys,

Hopefully you can help me with this, I seriously don't know where else to go.
I am waiting for a reply from the PayPal support since almost 2 weeks. 
I have studied a lot for this case and parsed the whole StackOverflow and PayPal docs, but still not able to understand what to do.  THAT SAID :) :

USE-CASE: I would like to save the PayPal credentials (a token, something) to let the user pay without entering the complete checkout flow. It's not something recurring (no monthly, weekly, daily plan).
For what I see, reference transactions can be a solution. Anyway, I can read from a [previous issue](https://github.com/paypal/PayPal-PHP-SDK/issues/813#issuecomment-289838262) that there is a monthly turnover of € 10.000 in order to be accepted for this solution, and as a startup that's not the case.
Anyway, it was very hard for me to understand how to perform reference transactions with billing agreement without a recurring plan. Is there any documentation about it? Most of the documentation brings me to the deprecated [Express Checkout portal](https://developer.paypal.com/docs/classic/express-checkout/) and it does not seem to me a good choice.
Additionally, I need this solution **to pay a payee**. I have already set up the express checkout to pay a payee successfully, but now I would need to create a sort of one-click checkout with it.

Is there any solution / example / documentation for this?

Thanks a lot in advance, all possible hints are very appreciated!

Lorenzo

**Comment by xiaoleih41** [comment]
Are you trying to do reference transaction for a 3rd party payee? It's kind of high risk product that is not for public application. We used to have a product called preapproval payment from adaptive payment but this product has been deprecated. The type product you were looking for is considered as high risk which requires contracts and high business credit. Most likely it won't be offered to startup level merchant if it exists.

**Comment by lorenzosfarra** [comment]
@xiaoleih41 first of all, thanks a lot for your reply.
I see.
The PayPal support contact - approx. 2 weeks ago - told us that a Marketplace solution will be available soon, and that we will be able to adopt it, that's a great news.
That's why we are now in the process to find a temporary solution to integrate PayPal (we have other options for credit cards etc..), even if we are not taking any fee at the moment for PayPal transactions.

This is why I would like to ask you to forget the Payee part, and help me to understand (documents / sample / whatever) how to satisfy the use-case described in the previous message (so the user as a normal flow pay us directly).

Thanks again!

**Comment by lorenzosfarra** [comment]
I see.
Thanks for your support.
