### ISSUE TITLE
How to get batch Id and batch item id in paypal payout api

### ISSUE THREAD

**Issue by karanmehta123** [paypal/PayPal-PHP-SDK#1013]
How to get batch Id and batch item id in paypal batch payouts?

**Comment by xiaoleih41** [comment]
You can get the `payout_batch_Id` when you make the [create payout batch call](https://developer.paypal.com/docs/api/payments.payouts-batch#payouts_create_request).  You can then get the `payout_item_Id` from the [get payout detail call](https://developer.paypal.com/docs/api/payments.payouts-batch#payouts_get).

**Comment by karanmehta123** [comment]
![payouts paypal developer](https://user-images.githubusercontent.com/22540585/33887039-7331b488-df6e-11e7-991b-17ee0bd6d325.png)
And How i Get `sender_batch_id `.I am very confused about this.

**Comment by xiaoleih41** [comment]
That should be defined by you to prevent duplicated batch from being sent. Please check[here](https://developer.paypal.com/docs/api/payments.payouts-batch#definition-sender_batch_header) for detail.

**Comment by pp-randy** [comment]
Closing as the answer has been provided.
