### ISSUE TITLE
[PHP 7.2] sizeof(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by selay** [paypal/PayPal-PHP-SDK#1014]
Throws an exception after upgrading php from 7.0.26 to php 7.2.0

 it is trying sizeof on "Sale" set with $payment->setIntent('Sale')

production.ERROR: ErrorException: sizeof(): Parameter must be an array or an object that implements Countable in /paypal/rest-api-sdk-php/lib/PayPal/Common/PayPalModel.php:179 

Note: PHP 7.2 notes: http://php.net/manual/en/migration72.incompatible.php

PHP no longer silently returns 1 if the parameter is not an array or not an object with implemented Countable interface. 

"An E_WARNING will now be emitted when attempting to count() non-countable types (this includes the sizeof() alias function)."

**Comment by xiaoleih41** [comment]
I am looking into this.

**Comment by Yard8** [comment]
I'm getting this since upgrading to PHP 7.2, is there a fix for this yet?

**Comment by selay** [comment]
It doesnt seem to be there yet, maybe just set your php requirements below 7.2 for now.

**Comment by yaofong** [comment]
changing 
`} else if (sizeof($v) <= 0 && is_array($v) ) {`
to
`} else if (is_array($v) && sizeof($v) <= 0) {`

**Comment by musamamasood** [comment]
is there any update on this issue?

**Comment by afernandez8781** [comment]
alquien seve si hay una solución para esto o lo unico que me queda es es vajar a php 7.1

**Comment by afernandez8781** [comment]
someone severe if there is a solution for this or the only thing that remains is to go to php 7.1

**Comment by shahrukh4** [comment]
Nice catch @yaofong

**Comment by mrohnstock** [comment]
hm isn't this fix not already part of 1.13.0, see https://github.com/paypal/PayPal-PHP-SDK/commit/1df6286dc95039e1e2a41cd24ddcfe492ac20544?

**Comment by nadar** [comment]
I have to admit it was a problem with a wrong version constraint in composer! i am sorry.

**Comment by axettone** [comment]
I'll switch to PHP 7.2 very soon, I can't believe this simple fix isn't available in the stable 1.* branch! C'mon guys! 👎

**Comment by nadar** [comment]
@axettone make sure to use the right composer constraint, its fixed indeed.

**Comment by nagsky1** [comment]
use php7.1 or lower , so you will don't get the issue

**Comment by prakash-gangadharan** [comment]
Hi folks, I could see this issue was fixed here as a part of  V1.14.0   https://github.com/paypal/PayPal-PHP-SDK/commit/1df6286dc95039e1e2a41cd24ddcfe492ac20544 , hence closing this. Please revert back if it is still an issue.

Thanks!
