### ISSUE TITLE
Payer setPaymentMethod atributes are not valid

### ISSUE THREAD

**Issue by zMrSnow** [paypal/PayPal-PHP-SDK#1016]
### General information
- **Payer** class, method **setPaymentMethod**  ( only "paypal" atribute works )

### Issue description
- Payer  ->  setPaymentMethod("credit_card")
- Payer  ->  setPaymentMethod("bank")
- Payer  ->  setPaymentMethod("pay_upon_invoice")
- Payer  ->  setPaymentMethod("carrier")
- Payer  ->  setPaymentMethod("alternate_payment")

**Comment by xiaoleih41** [comment]
Payer -> setPaymentMethod("credit_card") has been deprecated.  The rest are either limited release or for regional processing product only. At this time, "paypal" is the only current paymentMethod for general external developers.
