### ISSUE TITLE
Incoming JSON request does not map to API request

### ISSUE THREAD

**Issue by fird0s** [paypal/PayPal-PHP-SDK#1017]
Hi, I want to create payment with Paypal. The error is **Incoming JSON request does not map to API request** and my code is below. JSON Data is https://imgur.com/a/0tnTe

                   // Paypal API Payment
                    $payer = new Payer();
                    $payer->setPaymentMethod("paypal");

                    $itemList = new ItemList();
                    foreach ($order_detail as $item){
                         $items = new Item();
                         $items->setQuantity($item->quantity);
                         $items->setName($item->title);
                         $items->setPrice($item->total_price_item);
                         $items->setCurrency('USD');
                         $itemList->addItem(array($items));
                    }

                    $amount = new Amount();
                    $amount->setCurrency("USD")
                            ->setTotal($list_order_detail_total_price->total_price);

                    $transaction = new Transaction();
                    $transaction->setAmount($list_order_detail_total_price->total_price)
                                ->setItemList($itemList);

                    $redirect_urls = new RedirectUrls();
                    // Specify return & cancel URL
                    $redirect_urls->setReturnUrl(url('/checkcout/success'))
                      ->setCancelUrl(url('/checkcout/error'));
                  
                    $payment = new Payment();
                    $payment->setIntent('sale')
                      // ->setExperienceProfileId($profileid) // assign WebProfile
                      ->setPayer($payer)
                      ->setRedirectUrls($redirect_urls)
                      ->setTransactions([$transaction]);
                  
                    try {
                      $payment->create($this->_api_context);
                    } catch (\PayPal\Exception\PayPalConnectionException $ex) {
                      $request->session()->flash('error', $ex->getData());  
                      return redirect()->route('checkout');
                    }

Thank you.

**Comment by pp-randy** [comment]
In your loop can you try `  $itemList->addItem($items);`?
and `$transaction->setAmount($amount )`

**Comment by fird0s** [comment]
@pp-randy Thank you, your solution working very well.

**Comment by pp-randy** [comment]
Glad to hear it.  Let me know if you need any further assistance.
