### ISSUE TITLE
Credit card payment not working with live credentials

### ISSUE THREAD

**Issue by waelfcis2012** [paypal/PayPal-PHP-SDK#1018]
I'm using a form where the user enters his credit card info and submits the request to paypal payment 
the process worked fine for sandbox, but it didn't work for live account

`
    public function executePayment($creditCard, $itemList, $amount)
    {
        $fi = new FundingInstrument();
        $fi->setPaymentCard($creditCard);

        $payer = new Payer();
        $payer->setPaymentMethod("credit_card")
            ->setFundingInstruments(array($fi));

        $transaction = new Transaction();
        $transaction->setAmount($amount)
            ->setItemList($itemList)
            ->setDescription("Payment description")
            ->setInvoiceNumber(uniqid());
        // Payment
        // A Payment Resource; create one using the above types and intent set to sale 'sale'
        $payment = new Payment();
        $payment->setIntent("sale")
            ->setPayer($payer)
            ->setTransactions(array($transaction));
        // For Sample Purposes Only.
        $request = clone $payment;

        $response = array();

        try {
            $apiContext = $this->paypalConfig();
            $payment->create($apiContext);
            $response = [ // successfull response
                "payment" => $payment,
                "message" => "Subscription added successfully",
                "success" => true,
            ];
        } catch (\PayPal\Exception\PayPalConnectionException $ex) {
            $response = [
                "payment" => null,
                "message" => $ex->getMessage(),
                "success" => false,
            ];
        } catch (Exception $ex) {
            $response = [
                "payment" => null,
                "message" => $ex->getMessage(),
                "success" => false,
            ];
        }
        return $response;
    }`
it returns this response for live credentials 
` ERROR: Got Http response code 401 when accessing https://api.paypal.com/v1/payments/payment. {"name":"UNAUTHORIZED_PAYMENT","message":"Unauthorized payment.","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"f520ebddaa8e"}`
Also when i try to change the payment method to paypal it gives me this error
`ERROR: Got Http response code 500 when accessing https://api.paypal.com/v1/payments/payment. javax.validation.ValidationException: HV000028: Unexpected exception during isValid call.[java.lang.IllegalStateException]`

I'm stuck and any help is highly appreciated.

**Comment by pp-randy** [comment]
https://developer.paypal.com/docs/api/payments/
![image](https://user-images.githubusercontent.com/6819909/34047911-7499f6e0-e177-11e7-9011-1f1a714136a8.png)

Unfortunately, if you are working on a new integration the functionality to accept credit cards on live is restricted.

**Comment by waelfcis2012** [comment]
@pp-randy 
Thank you very much for your help
Will Braintree Direct send the fund to paypal?

**Comment by pp-randy** [comment]
The Braintree integration send funds to a bank account https://articles.braintreepayments.com/get-started/get-paid.

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been given
