### ISSUE TITLE
Guest Authorizations: No email in payment info until captured

### ISSUE THREAD

**Issue by adam-laraqui** [paypal/PayPal-PHP-SDK#1021]
Hi there,

I've been using PayPal's Authorization intent method to process orders on my site and only capture the funds once successful, or void if otherwise. For further convenience, I allow customers to choose the option of using their PayPal email to send them emails about their order.
Of course, PayPal Guests are also able to checkout the same way, and they are required by the Guest form to provide an email (so that PayPal can email them a receipt).

The issue I have only just found after months of occasional fatal errors, is that the API does not provide the email for Guests, except in the case once you capture the funds.

- After executing the payment, there is no 'email' field in the Payment object (so can't send confirmation email)
- After voiding the authorization, there is still no 'email' field (so can't inform customer)
- Only after capturing the funds does the 'email' field now show in the Payer Info

I have been told the email should show up someplace else like in shipping info, but it is not the case.

If I could see an obvious reason not to reveal the payer's email just because they don't have a PayPal account, I would understand, but I don't see why not, hence why I think it is a bug.

Any info would be appreciated!
Thanks

**Comment by xiaoleih41** [comment]
I am looking into this.

**Comment by adam-laraqui** [comment]
Great, thank you.
Please let me know if you are able to reproduce the problem, or if it even is one.

**Comment by xiaoleih41** [comment]
I tried the guest flow with the SDK sample.  I got the payer email address. 
```
{
    "id": "PAY-8RF669492V022702VLJJ6BOA",
    "intent": "authorize",
    "state": "approved",
    "cart": "18M64392C1631435K",
    "payer": {
        "payment_method": "paypal",
        "status": "UNVERIFIED",
        "payer_info": {
            "email": "abc@abcdefg.com",
            "first_name": "Bryan",
            "last_name": "Robinson",
            "payer_id": "53FX82M72LUUQ",
            "shipping_address": {
                "recipient_name": "Bryan Robinson",
                "line1": "4th Floor",
                "line2": "Unit #34",
                "city": "San Jose",
                "state": "CA",
                "postal_code": "95131",
                "country_code": "US"
            },
            "country_code": "US"
        }
    }
```

**Comment by adam-laraqui** [comment]
I don't understand what is the issue in that case.

After seeing your example response, I realise I had set an experience profile to not require the customer's billing address, however removing the profile still does not help with my issue. Everything is there except for the email (until captured).

I am so sure that I have followed documentation correctly, unless there are account restrictions that would cause this? Or is there anything I can provide for debugging?

```
{
    "id": "PAY-0KN77998PF7851942LJJ6VSY",
    "intent": "authorize",
    "state": "approved",
    "payer": {
        "payment_method": "paypal",
        "status": "UNVERIFIED",
        "payer_info": {            
            "first_name: "Adam",
            "last_name": "Laraqui",
            "payer_id": "4ZHNC948Q5JL4",
            "shipping_address": {
                "recipient_name": "Adam Laraqui"
            },
            "phone": "07821XXXXXX",
            "country_code": "GB"
        }
   }
```

**Comment by xiaoleih41** [comment]
If you are using the same code, does it work in sandbox environment?

**Comment by xiaoleih41** [comment]
Close this issue due to inactivity. Please resubmit when you have additional info.
