### ISSUE TITLE
UNKNOWN_ERROR

### ISSUE THREAD

**Issue by liz-in** [paypal/PayPal-PHP-SDK#1022]
Hi there,

the payment result sometime will get error, the message is like below:

`ERROR: Got Http response code 400 when accessing https://api.paypal.com/v1/payments/payment. {"name":"UNKNOWN_ERROR","message":"An unknown error occurred.","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"d644fe8060a1"}`

`at PayPalHttpConnection->execute('{"intent":"authorize","payer":{"payment_method":"credit_card","funding_instruments":[{"credit_card_token":{"credit_card_id":"CARD-1E184986W6097964WLI4GUVI"}}],"payer_info":{"email":"***","first_name":"***","last_name":"***"}},"transactions":[{"amount":{"currency":"USD","total":"8","details":{"shipping":"8","tax":"0","subtotal":"0"}},"item_list":{"items":[{"name":"Product","currency":"USD","quantity":"1","sku":"product-a","price":"0"}]},"invoice_number":"5a386a55b5f2a"}]}') in PayPalRestCall.php line 73`

The customer ask me what happened but I can't answer him. because this is an unknown error
could you help me?><

**Comment by xiaoleih41** [comment]
The error I saw is: Transaction refused because of an invalid argument. See additional error messages for details."
--
"The totals of the cart item amounts do not match order amounts." I think maybe the shipping is $8 while the product is 0 dollar. that might have thrown this error out.

**Comment by liz-in** [comment]
Hi @xiaoleih41 
I appreciate your message.

But earlier, that is fine. 
The product is a gift, customer just need to pay the shipping fee.

I tried using the following method to test:
  premise >> price is $0, shipping fee is $8

1. quantity is 1, pay by credit cart. (not work)
2. quantity is 2 or more, pay by credit cart. (not work)
3. quantity is 1, pay by paypal. (**work**)
4. quantity is 2 or more, pay by paypal. (**work**)
5. quantity is 1, buy another product(price is $15), pay by credit cart. (**work**)

So..... that is possible when the cart item amounts do not match order amounts.
It is not works when the payment is credit card.
What can I do? please help me><

**Comment by xiaoleih41** [comment]
I took a look at the account.  I found one $8.00 authorization was done successfully funded by credit card. Then you voided it. Has the issue been solved?

**Comment by liz-in** [comment]
I set the item($15) and the shipping discount(-$15).
It works!

Thank you
