### ISSUE TITLE
How to get Samples

### ISSUE THREAD

**Issue by Wector** [paypal/PayPal-PHP-SDK#1024]
Starting Using this SDK and wanna get samples
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description
I cant find how to download samples, i cant clone it on github.
Where can i get it?

**Comment by xiaoleih41** [comment]
Please follow the instruction provided [here](https://github.com/paypal/PayPal-PHP-SDK/tree/master/sample)

**Comment by Wector** [comment]
I get this in command line:
Could not open input file: vendor/paypal/rest-api-sdk-php/sample/index.php
Nothing happends

2017-12-20 23:03 GMT+01:00 Xiaolei Wheelock <notifications@github.com>:

**Comment by pp-randy** [comment]
Have you downloaded the samples?  You can download them here: https://github.com/paypal/PayPal-PHP-SDK/archive/master.zip

**Comment by Wector** [comment]
I downloaded that but no Samples in the given path for me.

2017-12-22 19:14 GMT+01:00 Randy <notifications@github.com>:

**Comment by Wector** [comment]
[image: Szövegközi kép 1]

2017-12-22 21:42 GMT+01:00 Viktor Kelemen <wector001@gmail.com>:

**Comment by sitodj** [comment]
I got this error on http://localhost:5000/payments/CreatePaymentUsingPayPal.php

Fatal error: Cannot use PayPal\Api\object as object because 'object' is a special class name in C:\Users\sito_\Desktop\platosypizarras\Platosypizarras\httpdocs\PayPal-PHP-SDK\paypal\rest-api-sdk-php\lib\PayPal\Api\Payment.php on line 8

**Comment by pp-randy** [comment]
@Wector the download should work, otherwise you can still view the files and copy the ones you need here https://github.com/paypal/PayPal-PHP-SDK/tree/master/sample.

**Comment by pp-randy** [comment]
When you downloaded the zip file from Github?  What was in it?  Can you take a screenshot of the zip file contents?

**Comment by pp-randy** [comment]
@Wector clone the repository using `git`.  I apologize I see the samples are excluded when downloading directly https://github.com/paypal/PayPal-PHP-SDK/blob/master/.gitattributes#L2.
