### ISSUE TITLE
Got Http response code 400 when accessing - startDate issue

### ISSUE THREAD

**Issue by wiloke** [paypal/PayPal-PHP-SDK#1027]
Hi,
ERROR: Got Http response code 400 when accessing https://api.paypal.com/v1/payments/billing-agreements/. {"name":"VALIDATION_ERROR","details":[{"field":"start_date","issue":"Agreement start date is required, should be valid and greater than the current date. Should be consistent with ISO 8601 Format"}]
I have a question: For example, I'm living in Vietnam and the owner of PayPal account is living in USA (He set his PayPal timezone to UTC - 5), When I purchase a subscription plan, the startDate should base on his timezone (UTC - 5) or my timezone  (UTC +7)?
Thanks

**Comment by pp-randy** [comment]
It will be based on UTC + 7, here is some additional information regarding start_date https://github.com/paypal/PayPal-Java-SDK/issues/207#issuecomment-255794267.

**Comment by wiloke** [comment]
Hi,
Thanks for your reply!
I'm talking about the Live account. 
I'm a web developer, and I'm integrating PayPal to my product. One of my customers, she set timezone to New York, but her website always gets this issue. 
Note that I already set 
date_default_timezone_set('america/new_york'); before using date function

**Comment by pp-randy** [comment]
The start date is relative to the merchant account, or account receiving the payment.  They have added additional information to the documentation as well https://developer.paypal.com/docs/api/payments.billing-agreements which should help. 

> The start date and time in the create agreement request might not match the start date and time that the API returns in the execute agreement response. When you execute an agreement, the API internally converts the start date and time to the start of the day in the time zone of the merchant account. For example, the API converts a 2017-01-02T14:36:21Z start date and time for an account in the Berlin time zone (UTC + 1) to 2017-01-02T00:00:00. When the API returns this date and time in the execute agreement response, it shows the converted date and time in the UTC time zone. So, the internal 2017-01-02T00:00:00 start date and time becomes 2017-01-01T23:00:00 externally.

**Comment by pp-randy** [comment]
If you want an initial payment to happen when the agreement is created, consider a setup_fee in your plan https://developer.paypal.com/docs/api/payments.billing-plans#definition-merchant_preferences.

**Comment by xiaoleih41** [comment]
Close the issue a solution has been given.
