### ISSUE TITLE
Call to a member function connection() on null

### ISSUE THREAD

**Issue by zMrSnow** [paypal/PayPal-PHP-SDK#1028]
Error : 

```
Symfony\Component\Debug\Exception\FatalThrowableError thrown with message "Call to a member function connection() on null"
Stacktrace:
#0 Symfony\Component\Debug\Exception\FatalThrowableError in C:\xampp\htdocs\EcSc\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:1116
```
Where is error :  config/paypal.php

When it happends : 

when i add 
```try {
    use App\Info;
    use Illuminate\Database\Eloquent\ModelNotFoundException;

    $client_id = Info::where("name", "=", "paypal_client_id")->firstOrFail();
    $client_id = $client_id->value;
    $secret = Info::where("name", "=", "paypal_secret")->firstOrFail();
    $secret = $secret->value;
} catch (ModelNotFoundException $e) {
    $client_id = "";
    $secret = "";
}

```

and array returns 

```'client_id' => $client_id,
    'secret' => $secret,```

**Comment by pp-randy** [comment]
So you are getting a `ModelNotFoundException`  in Laravel?  Does your integration work if you hard code the values?

**Comment by xiaoleih41** [comment]
Close due to inactivity. Please resubmit when you have additional information.

**Comment by zMrSnow** [comment]
yes my integration works perfect when i hard code my ID and SECRET this happends only when i want to get ID and SECRET from database so i m unable to make Change ID and Secret feature cause this problem

**Comment by pp-randy** [comment]
Does `App\Info::where('name', '=', 'paypal_client_id')->firstOrFail()` do anything different? 

https://laravel.com/docs/5.5/eloquent
> Not Found Exceptions
Sometimes you may wish to throw an exception if a model is not found. This is particularly useful in routes or controllers. The findOrFail and firstOrFail methods will retrieve the first result of the query; however, if no result is found, a Illuminate\Database\Eloquent\ModelNotFoundException will be thrown.

You can ensure you have a record in your table where it has a column `name` and value 
`paypal_client_id`?  

A query similar to this give you a row?
```
SELECT *
FROM Info
WHERE `name` = 'paypal_client_id';
```

**Comment by zMrSnow** [comment]
no and i thik i posted " use App\Info;" in my example code it should anyways works, yea i know about using  firstOrFail it throws ModelNotFound Exception ( 404 ) when it doesnt exists but this table is auto setup by seeds and this table exist also when i left it before return and hard code paypal id and secret it works  so if it would not when i load my home page it should return me to 404 error page or in Dev Console it should show me network error 404 or am i wrong ?

**Comment by pp-randy** [comment]
Unfortunately; I don't know, the error to me seems to be that the values are not being found in your table.  

If you don't have direct access to the database to look you could maybe run a `like` search possibly and see what you get. 
`App\Info::where('name', 'LIKE', 'paypal%')
