### ISSUE TITLE
How to upgrade the subscription?

### ISSUE THREAD

**Issue by landguy423** [paypal/PayPal-PHP-SDK#1030]
@pp-randy 
I tried to implement the recurring payment using PayPal-PHP-SDK and it worked well.
I got the TOKEN from PayPal return page.

But not sure how to upgrade the subscription.
How to get the executed agreement ID ?
Please help me!

**Comment by pp-randy** [comment]
What do you mean by upgrade the subscription?   

The `$agreement->getId()` function shown here would get the agreement id https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/billing/ExecuteAgreement.php#L29.

**Comment by landguy423** [comment]
@pp-randy Thanks,
`$agreement->getId()` makes me happy.
Regarding the subscription upgrade,
Please let me know how can I change the monthly amount of the executed agreement?
For instance, I am paying $10 month but need to change amount to $15  from $10 now.

**Comment by landguy423** [comment]
@pp-randy Thanks,
`$agreement->getId()` makes me happy.
Regarding the subscription upgrade,
Please let me know how can I change the monthly amount of the executed agreement?
For instance, I am paying $10 month but need to change amount to $15  from $10 now.

**Comment by pp-randy** [comment]
@landguy423  unfortunately with the REST API we don't have the feature to update the agreement price, the requests are being tracked here: 

https://github.com/paypal/PayPal-REST-API-issues/issues/24
https://github.com/paypal/PayPal-REST-API-issues/issues/25
https://github.com/paypal/PayPal-REST-API-issues/issues/26

I know its a hassle but if you do need to change the prices then you can change the price of an agreement using the Classic API as a workaround https://developer.paypal.com/docs/classic/api/merchant/UpdateRecurringPaymentsProfile_API_Operation_NVP/.  The agreement id, would match the `PROFILEID` of the Classic API, these are actually the same agreement.

**Comment by pp-randy** [comment]
Closing this issue, please let me know if you have any additional questions.

**Comment by PaperinoBello** [comment]
Hello!
but the API PayPal-PHP-SDK/sample/billing/UpdatePlanPaymentDefinitions.php is the solution about this problem?

**Comment by PenguinArts** [comment]
Any updates here?
