### ISSUE TITLE
Fatal error: Cannot use PayPal\Api\object as object

### ISSUE THREAD

**Issue by sitodj** [paypal/PayPal-PHP-SDK#1031]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description

Just downloaded SDK 14 with samples

I got this error on http://localhost:5000/payments/CreatePaymentUsingPayPal.php

Fatal error: Cannot use PayPal\Api\object as object because 'object' is a special class name in C:\Users\sito_\Desktop\platosypizarras\Platosypizarras\httpdocs\PayPal-PHP-SDK\paypal\rest-api-sdk-php\lib\PayPal\Api\Payment.php on line 8

**Comment by pp-randy** [comment]
What version of PHP are you using?

**Comment by sitodj** [comment]
PHP  version is 5.4.45 and paypal sdk is 1.13

**Comment by pp-randy** [comment]
Can you provide steps to reproduce this issue or a link to code?   Did you modify Payment.php?  https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Api/Payment.php#L8

**Comment by sitodj** [comment]
Solved this by using newest paypal sdk
