### ISSUE TITLE
Paypal not charging the customer after the trail ends

### ISSUE THREAD

**Issue by usamamashkoor** [paypal/PayPal-PHP-SDK#1032]
Hi we are offering 2 weeks free trial to over customers after that we want to charge them $5 month when the trial ends but the paypal is not charging the customer after the 2 weeks.  it is setting the next payment due date to 1 month after the 14 days free trial lets say today is 1 Jan 208 the free trail ends on 14 Jan 2018 so the paypal should charge our customer the monthly fee starting from 15 Jan 2018 but it is setting the next due date to 15 Feb 2018 .   

Here are my payment definitions.
```
$trialPaymentDefinition = new PaymentDefinition();
$trialPaymentDefinition->setName($plan)
    ->setType('TRIAL')
    ->setFrequency('week')
    ->setFrequencyInterval("2")
    ->setCycles("1")
    ->setAmount(new Currency(array('value' => 0, 'currency' => 'USD')));

$paymentDefinition = new PaymentDefinition();

$paymentDefinition->setName($plan)
    ->setType('REGULAR')
    ->setFrequency('Month')
    ->setFrequencyInterval("1")
    ->setCycles("0")
    ->setAmount(new Currency(array('value' => 5, 'currency' => 'USD'))); 
```
Kindly help me on this i have also tried the setup initial fee but is charging the customer at the start but i want to charge the customer after 14 days of free trial.

**Comment by pp-randy** [comment]
What are you providing as the `start_date` when creating the agreement?

**Comment by usamamashkoor** [comment]
@pp-randy i have changed the start_date to 14 days now the date is working fine now. 
@pp-randy i have set the payment definition according to yours provided code in issue  #643  in our paypal sandbox area in the payment details it shows this
Trial Period Section.
Total cycles : 2
Remaining cycles : 2
Cycle frequency : Weekly

is it correct. ?

@pp-randy i have one more question related to testing the paypal trial subscription let say if the user is subscribed to our free trail and after 14 days our free trail ends and he does not have balance or pay for our paypal $5/month subscription then how we will test this scenario in our application because if he failed to pay for the $5 monthly subscription after the free trail then we will have to cancel his subscription in our paypal and also in our application to kindly let me know how i can verify this and solve it.
Thanks again..

**Comment by pp-randy** [comment]
@usamamashkoor I think you need to have the `start_date` be same day or next day and adjust your trial days accordingly.  If you do a `start_date` 14 days out, then don't add the Trial period in the plan because I think that would start a 14 day trial at the `start_date` you set, so 28 days of trial. 

You can have the billing agreement automatically cancel using the `merchant_preferences` https://developer.paypal.com/docs/api/payments.billing-plans#definition-merchant_preferences.  I think `max_fail_attempts` set to 1 would work for you.

**Comment by pp-randy** [comment]
I will need to do some research but `initial_fail_amount_action` might work for you also.

**Comment by usamamashkoor** [comment]
@pp-randy i have set the trail days of two weeks using your example code.
```
"payment_definitions": [{
		"frequency_interval": 1,
		"amount": {
			"currency": "USD",
			"value": 0
		},
		"frequency": "Week",
		"cycles": 2,
		"type": "TRIAL",
		"name": "Two Weeks Free"
	}, {
		"frequency_interval": 1,
		"amount": {
			"currency": "USD",
			"value": 5.00
		},
		"frequency": "MONTH",
		"type": "REGULAR",
		"name": "Monthly Payment"
	}
]
```  
in my sandbox Recurring Payments details it shows me this details
**Total cycles : 2
Remaining cycles : 2
Cycle frequency : Weekly
Next payment due : Jan 16, 2018**
as the current date is Jan 2 2018 so if we add 14 days in it then the payment date should be Jan 16 2018 so i think Next Payment due date is correct. 

Can you please kindly confirm if this is correct or not for our 2 weeks free trail and after free trail $5/month amount subscription it will be great help. ?

Thanks again.

**Comment by pp-randy** [comment]
I think I can help by running a test for you.  So I tested with a start_date of next week and a 2 week trial and got ,"next_billing_date":"2018-01-09T10:00:00Z".  My two week free trial starts on January 9.

**Comment by usamamashkoor** [comment]
@pp-randy can you please explain more if my above approach is correct or not if it is incorrect then please share a correct one.

Thanks again.

**Comment by pp-randy** [comment]
Your payment definition looks good to me.  What start_date are you using when you create the agreement?

**Comment by pp-randy** [comment]
Can you run https://developer.paypal.com/docs/api/payments.billing-agreements#billing-agreements_get 

Then give me the JSON response minus any sensitive information?  I will look it over for you and discuss what I see.

**Comment by usamamashkoor** [comment]
Thanks @pp-randy i am adding 14 days in the current date time so if the today date is Jan 2 2018 then the my start date will be Jan16 2018.

**Comment by pp-randy** [comment]
That won't be correct if you are adding a trial for two weeks in the definition... This would mean you wanted to start a two week trial in 14 days. Does that make sense?  If you want to start a 2 week trial now, then set your start_date for today.

**Comment by usamamashkoor** [comment]
here is my billing agreement json response
```
{
  "id": "id",
  "state": "Active",
  "description": "description",
  "payer": {
    "payment_method": "paypal",
    "status": "verified",
  },
  "plan": {
    "payment_definitions": [
      {
        "type": "TRIAL",
        "frequency": "Week",
        "amount": {
          "currency": "USD",
          "value": "0.00"
        },
        "cycles": "2",
        "charge_models": [
          {
            "type": "TAX",
            "amount": {
              "currency": "USD",
              "value": "0.00"
            }
          },
          {
            "type": "SHIPPING",
            "amount": {
              "currency": "USD",
              "value": "0.00"
            }
          }
        ],
        "frequency_interval": "1"
      },
      {
        "type": "REGULAR",
        "frequency": "Day",
        "amount": {
          "currency": "USD",
          "value": "3.99"
        },
        "cycles": "0",
        "charge_models": [
          {
            "type": "TAX",
            "amount": {
              "currency": "USD",
              "value": "0.00"
            }
          },
          {
            "type": "SHIPPING",
            "amount": {
              "currency": "USD",
              "value": "0.00"
            }
          }
        ],
        "frequency_interval": "1"
      }
    ],
    "merchant_preferences": {
      "setup_fee": {
        "currency": "USD",
        "value": "0.00"
      },
      "max_fail_attempts": "1",
      "auto_bill_amount": "YES"
    }
  },
  "start_date": "2018-01-16T08:00:00Z",

  "agreement_details": {
    "outstanding_balance": {
      "currency": "USD",
      "value": "0.00"
    },
    "cycles_remaining": "2",
    "cycles_completed": "0",
    "next_billing_date": "2018-01-16T10:00:00Z",
    "final_payment_date": "1970-01-01T00:00:00Z",
    "failed_payment_count": "0"
  }
}
```

**Comment by usamamashkoor** [comment]
Thanks @pp-randy for clarifying i have set the start date for today date.
Here is my Billing agreement JSON response for start date today .
Let me know if this is correct.?

```
{
  "id": "id",
  "state": "Active",
  "description": "description",
 
  "plan": {
    "payment_definitions": [
      {
        "type": "TRIAL",
        "frequency": "Week",
        "amount": {
          "currency": "USD",
          "value": "0.00"
        },
        "cycles": "2",
        "charge_models": [
          {
            "type": "TAX",
            "amount": {
              "currency": "USD",
              "value": "0.00"
            }
          },
          {
            "type": "SHIPPING",
            "amount": {
              "currency": "USD",
              "value": "0.00"
            }
          }
        ],
        "frequency_interval": "1"
      },
      {
        "type": "REGULAR",
        "frequency": "Day",
        "amount": {
          "currency": "USD",
          "value": "3.99"
        },
        "cycles": "0",
        "charge_models": [
          {
            "type": "TAX",
            "amount": {
              "currency": "USD",
              "value": "0.00"
            }
          },
          {
            "type": "SHIPPING",
            "amount": {
              "currency": "USD",
              "value": "0.00"
            }
          }
        ],
        "frequency_interval": "1"
      }
    ],
    "merchant_preferences": {
      "setup_fee": {
        "currency": "USD",
        "value": "0.00"
      },
      "max_fail_attempts": "1",
      "auto_bill_amount": "YES"
    }
  },
  "start_date": "2018-01-02T08:00:00Z",
  "agreement_details": {
    "outstanding_balance": {
      "currency": "USD",
      "value": "0.00"
    },
    "cycles_remaining": "2",
    "cycles_completed": "0",
    "next_billing_date": "2018-01-02T10:00:00Z",
    "final_payment_date": "1970-01-01T00:00:00Z",
    "failed_payment_count": "0"
  }
} 
```

**Comment by pp-randy** [comment]
That looks better to me.  Just be aware of how start_date can behave, read more about it here: https://developer.paypal.com/docs/api/payments.billing-agreements#billing-agreements.  You might have issues trying to use today. If you are not charging an amount why use a trial period?

**Comment by usamamashkoor** [comment]
If we don't use trial period and set start date to 14 days in future as we are not charging for trial will it work like free trail for 14 days and it will charge the customer after 14 days for $5 /month...?

**Comment by usamamashkoor** [comment]
I am using trial because in stripe we don't have start date so we will have to add trial feature in it even if the trial is free.

**Comment by usamamashkoor** [comment]
So can we skip the trail and set start date to 14 days in future and it will work like free trial for 14 days.? What about this lets say if a customer unsubscribe after 1 week before the 14 days does he get charged for 7 days if we dont use trail and set the start date to 14 days in future...?

**Comment by pp-randy** [comment]
If you have 14 days in the future or `start_date` or 14 days of tree trial and you cancel at 7 days, then I don't expect the buyer to be charged at all.

**Comment by usamamashkoor** [comment]
Thanks can you please also let me know how can i test a failed payment scenario like our customer is subscribed to our service and after 14 days when paypal tires to charge him then the payment attempt ahould be failed...

**Comment by xiaoleih41** [comment]
You don't have to set it 14 days for testing. You can set it one day and have the buyer account approve the agreement, then close out the buyer account. After one day you can try to charge, the payment should fail.

**Comment by usamamashkoor** [comment]
How can i close the buyer account...?

**Comment by xiaoleih41** [comment]
As it's for testing so you should have access to both the buyer and the seller's PayPal accounts. You can log into the buyer's account and remove the card. If it's sandbox, you can log on sandbox.paypal.com. if it's production testing, you can log on www.paypal.com.

**Comment by xiaoleih41** [comment]
Close as the answer has been given. Please resubmit when you have additional questions.
