### ISSUE TITLE
403s on All Batch Payment Calls

### ISSUE THREAD

**Issue by dasfisch** [paypal/PayPal-PHP-SDK#1037]
### General information

* SDK/Library version: 1.13.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: bc508dd6ccb23
* Language, language version, and OS: PHP, PHP 7.1.13, OSX 10.13.1

### Issue description
I have suddenly started receiving 403s on all batch payment calls. All the other APIs function properly. I ran some debugging, and the same auth token works on some APIs but not on the batch payments. This same code worked not even a week ago; I made sure everything is on in my sandbox dashboard. I would be happy to provide code, if necessary.

 I tried to open an issue on [here](https://developer.paypal.com/support/), but the site seems to be down as of 1/1/18. Any help would be great. Not sure what to do at this point, given all this info.

Thanks in advance!

**Comment by xiaoleih41** [comment]
What exact was the error that you got returned.  Also, it shows that all the masspay payment sent before were denied.

**Comment by dasfisch** [comment]
Here is the full logs that are dumped out by the debugger:

https://gist.github.com/dasfisch/fc3a208bf52442e279dfaad15de32d7e

If they were made already, shouldn't I receive an error as such? I do know at one time I was seeing those errors.

**Comment by xiaoleih41** [comment]
I cannot reproduce your error from my end and it's an authorization error. You may try to create a payout app with a verified sandbox account instead as I can see all the previous ones were not sent successfully.

**Comment by dasfisch** [comment]
Thanks for that tip. I used our production level API account, and it stopped giving me those errors. I will keep an eye on it for now, and, if I see it again, try to get you better steps to reproduce.

Thanks a lot! Have a great day!
