### ISSUE TITLE
ItemList::removeItem can remove multiple Items at once

### ISSUE THREAD

**Issue by benjaminpick** [paypal/PayPal-PHP-SDK#1038]
In writing #1034, I discovered another potential bug:

Imagine adding an item twice:
```php
$item = (new Item)->setName('blue car');
$itemList->addItem( $item );
$itemList->addItem( (new Item)->setName('blue car') );
$itemList->removeItem($item);
```
How many Items are now in the $itemList? Yes, none at all. This is because `array_diff` does not compare by reference, but by JSON representation of the internal state.

Is this on purpose?
(The same issue exists with many other PaypalModels.)

**Comment by bluk** [comment]
This is known behavior in this convenience method. It should be rare that you have the same items or other objects with the same exact JSON representation in real world scenarios. If you must control the exact items, you can use the `setItems` or equivalent setter for the property.
