### ISSUE TITLE
Compatibility with Adaptive Payments w.r.t. recurring subscriptions (with Billing Plans/Agreements API)

### ISSUE THREAD

**Issue by Westie** [paypal/PayPal-PHP-SDK#1039]
Hi all,

I'm having some difficulty in working out any similarities with PayPal's now limited-release Adaptive Payments platform and the Billing Plans & Agreements REST API platform.

Previously, we were able to have a flow similar to this:

1. User creates a custom subscription, of X period
2. User agrees to this subscription, pays first fee instantly
3. Manually charge user set amount of money every month

Now, the BP&A API effectively forces to have a flow which is this:

1. User creates a custom subscription, of X period
2. User agrees to this subscription, gets charged a set up fee(!)
3. We have no control as to when funds are withdrawn; PayPal automagically does this for us

Is there any way within PayPal to have *manual* control over when recurring payments are actually executed?

**Comment by xiaoleih41** [comment]
So you don't want to use `start_date` and let the system do the monthly charge on the set date? You can try to look into Braintree direct product intead. it supports both PayPal and credit card. Its vault feature is very flexible. You can find the info [here](https://developers.braintreepayments.com/guides/paypal/vault/javascript/v3)

**Comment by xiaoleih41** [comment]
Close as the answer has been given
