### ISSUE TITLE
Payment not processing after redirecting to PayPal

### ISSUE THREAD

**Issue by jatinkumar09** [paypal/PayPal-PHP-SDK#1040]
Hi 
we are trying to implement paypal in laravel 5.5 , below is our code . It redirects to PayPal page but there when we put in credit/debit card details it shows session timeout and take us to login page . Can you please help us with the issue . There are no errors in PayPal log and issue is in live 

public function __construct()
    {
            $this->apiContext = new \PayPal\Rest\ApiContext(
                    new \PayPal\Auth\OAuthTokenCredential(
                        'ID',     // ClientID
                        'Secret'      // ClientSecret
                    )
            );

            $this->apiContext->setConfig(
                  array(
                    'mode' => 'live',
                    'log.LogEnabled' => true,
                    'log.FileName' => storage_path().'/logs/PayPal.log',
                    'log.LogLevel' => 'FINE',
                    'cache.enabled' => true
                  )
            );
    }

    public function store(Request $request)
    {   
       
        $payer = new \PayPal\Api\Payer();
        $payer->setPaymentMethod('paypal');

        $amount = new \PayPal\Api\Amount();
        $amount->setTotal($request['abc']*1);
        $amount->setCurrency('USD');

        $transaction = new \PayPal\Api\Transaction();
        $transaction->setAmount($amount)
                    ->setDescription("Amount payable for ".$request['abc']." abc.");

        $redirectUrls = new \PayPal\Api\RedirectUrls();
        $redirectUrls->setReturnUrl(URL::route('payment.status'))
            ->setCancelUrl(URL::route('payment.cancel'));

        $payment = new \PayPal\Api\Payment();
        $payment->setIntent('sale')
            ->setPayer($payer)
            ->setTransactions(array($transaction))
            ->setRedirectUrls($redirectUrls);

        try {
            $payment->create($this->apiContext);

            
            return redirect($payment->getApprovalLink().'&useraction=commit');
        }
        catch (\PayPal\Exception\PayPalConnectionException $ex) {
            // This will print the detailed information on the exception.
            //REALLY HELPFUL FOR DEBUGGING

            Session::flash('failure', 'There is some error. Please try again later.');

            return redirect(route('home'));
        }
    }

    public function status()
    {
        // print_r($_GET);
        // die();
        $paymentToBeUpdated = Payment::where('payment_id', $_GET['paymentId'])->first();
        $paymentToBeUpdated->update(['payer_id' => $_GET['PayerID']]);

        $paymentId = $_GET['paymentId'];
        $payment = \PayPal\Api\Payment::get($paymentId, $this->apiContext);

        $execution = new \PayPal\Api\PaymentExecution();
        $execution->setPayerId($_GET['PayerID']);

        $result = $payment->execute($execution, $this->apiContext);

        if ($result->getState() == 'approved') {
            if($paymentToBeUpdated->status == 'Pending')
                $paymentToBeUpdated->update(['status' => 'Success']);
        
            Session::flash('success', 'You have successfully made the payment.');
        }
        else{
            if($paymentToBeUpdated->status == 'Pending')
                $paymentToBeUpdated->update(['status' => 'Failure']);
        
            Session::flash('failure', 'Your transaction is declined.');
        }
        
        return redirect(route('home'));
    }

### General information

* SDK/Library version: 
* Environment:  Production
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 
PHP 7.1 CentOS

**Comment by jatinkumar09** [comment]
`public function __construct()
{
        $this->apiContext = new \PayPal\Rest\ApiContext(
                new \PayPal\Auth\OAuthTokenCredential(
                    'ID',     // ClientID
                    'Secret'      // ClientSecret
                )
        );


        $this->apiContext->setConfig(
              array(
                'mode' => 'live',
                'log.LogEnabled' => true,
                'log.FileName' => storage_path().'/logs/PayPal.log',
                'log.LogLevel' => 'FINE',
                'cache.enabled' => true
              )
        );
}

public function store(Request $request)
{   
   
    $payer = new \PayPal\Api\Payer();
    $payer->setPaymentMethod('paypal');

    $amount = new \PayPal\Api\Amount();
    $amount->setTotal($request['abc']*1);
    $amount->setCurrency('USD');

    $transaction = new \PayPal\Api\Transaction();
    $transaction->setAmount($amount)
                ->setDescription("Amount payable for ".$request['abc']." abc.");

    $redirectUrls = new \PayPal\Api\RedirectUrls();
    $redirectUrls->setReturnUrl(URL::route('payment.status'))
        ->setCancelUrl(URL::route('payment.cancel'));

    $payment = new \PayPal\Api\Payment();
    $payment->setIntent('sale')
        ->setPayer($payer)
        ->setTransactions(array($transaction))
        ->setRedirectUrls($redirectUrls);

    try {
        $payment->create($this->apiContext);


        
        return redirect($payment->getApprovalLink().'&useraction=commit');
    }
    catch (\PayPal\Exception\PayPalConnectionException $ex) {
        // This will print the detailed information on the exception.
        //REALLY HELPFUL FOR DEBUGGING

        Session::flash('failure', 'There is some error. Please try again later.');

        return redirect(route('home'));
    }
}

public function status()
{
    // print_r($_GET);
    // die();
    $paymentToBeUpdated = Payment::where('payment_id', $_GET['paymentId'])->first();
    $paymentToBeUpdated->update(['payer_id' => $_GET['PayerID']]);

    $paymentId = $_GET['paymentId'];
    $payment = \PayPal\Api\Payment::get($paymentId, $this->apiContext);

    $execution = new \PayPal\Api\PaymentExecution();
    $execution->setPayerId($_GET['PayerID']);

    $result = $payment->execute($execution, $this->apiContext);

    if ($result->getState() == 'approved') {
        if($paymentToBeUpdated->status == 'Pending')
            $paymentToBeUpdated->update(['status' => 'Success']);
    
        Session::flash('success', 'You have successfully made the payment.');
    }
    else{
        if($paymentToBeUpdated->status == 'Pending')
            $paymentToBeUpdated->update(['status' => 'Failure']);
    
        Session::flash('failure', 'Your transaction is declined.');
    }
    
    return redirect(route('home'));
}`

**Comment by jatinkumar09** [comment]
Hi ,
We checked with other country credit card and payment was processed but its still not accepting Indian Cards what can we do for same ?

**Comment by xiaoleih41** [comment]
This appears to be a more of account related issue. As it could be a regional policy, please contact customer service listed on your account for any possible policy updates on India cards.

**Comment by Bobyuan1015** [comment]
Hello,
I am struglling with how i can implement paypal payment in my laravel project.
Any paypal package for laravel ?
Or I should directly invoke paypal PHP APIs

**Comment by jatinkumar09** [comment]
Hi 
Above is the code to implement paypal in laravel , please follow this link https://github.com/paypal/PayPal-PHP-SDK/wiki/Installation-Composer
Regards
Jatin Kumar
