### ISSUE TITLE
Having PERMISSION_DENIED on attempt to retrieve authorization object

### ISSUE THREAD

**Issue by denisbulakh** [paypal/PayPal-PHP-SDK#1041]
### General information

* Environment: Production

### Issue description

Hi, I retrieve PERMISSION_DENIED trying to get authorization object to capture it for the transaction made to 3rd part payee. I have this issue simultaniously, for the same 3rd part accounts. Most of transactions are working well, but sometimes I have this issue. 

What kind of permission could it be and how should we request them from 3rd part account? And why it happens not for all the request, but simultaniously? 

Thanks!

**Comment by xiaoleih41** [comment]
Are you saying you only have this error occasionally with the same 3rd party account while most of the time it works fine with the same exact account on capturing funds? It sounds more like transaction specific issue. Do you have a transaction ID or a debuyID that I can look into to better understand the situation? Authorization only has 3 days guarantee period. Once it has passed 3 day period, the capture may fail.

**Comment by denisbulakh** [comment]
Yes, error appears in around 1% of transactions, with different 3rd party accounts. But most of transactions are successful. So yes, it looks like transaction specific but I can't understand what is the difference between successful transactions and not. Debug id of one of this kind of errors is 3ffd0fd6483ec

**Comment by xiaoleih41** [comment]
Have you had successful capture with the same exact 3rd party account? If so, do you have a transaction ID for that?

**Comment by denisbulakh** [comment]
Yes, for example, 47L28373EX919931Y (55W224060Y261234N) or 6C308462ES016882U (83W710695P5816734)

**Comment by xiaoleih41** [comment]
Do you have access to the merchant's transaction history? It will have something to do with what happen on the merchant's account. If the merchant has changed the transaction either captured the funds or refunded the funds, your attempt to capture will fail.  As this is an open forum, we cannot discuss account specific issue. You may have your merchant contact customer service to get more transaction specific information. I am closing this issue as it's not an API or SDK issue. It's more of transaction specific issue which customer service should be able to better assist you with.
