### ISSUE TITLE
Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment.

### ISSUE THREAD

**Issue by rohitdalal67** [paypal/PayPal-PHP-SDK#1043]
### Issue description From Logs

[20-01-2018 12:23:58] PayPal\Core\PayPalHttpConnection : ERROR: Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment. {"name":"INTERNAL_SERVICE_ERROR","details":[],"message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"f89debdea08fa"}

**Comment by rohitdalal67** [comment]
Same Error Keep Coming Multiple Times

[20-01-2018 14:18:41] PayPal\Core\PayPalHttpConnection : ERROR: Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment. {"name":"INTERNAL_SERVICE_ERROR","details":[],"message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"5e915efe16fe"}

**Comment by pp-randy** [comment]
I'm aware of an issue with credit card payments returning a 500.  Is this happening only for credit cards for you?

**Comment by xiaoleih41** [comment]
What type of payment are you trying to make?  Can you provide more detail?

**Comment by xiaoleih41** [comment]
Are you trying to do future payment? This product has been deprecated. You won't get approved for live production credential. Please consider to integration Braintree SDK. It supports both PayPal and credit card.

**Comment by rohitdalal67** [comment]
Thank you for your response. Yes, we are trying to do future payment. I am sorry to say this but Braintree do not work at client country. Can you suggest any other alternative? I would be greatly thankful of your's.

**Comment by rohitdalal67** [comment]
@pp-randy We are not not using credit cards we are using **paypal** as payment method

The Code is as follows - 
`
				$payer = new Payer();
				$payer->setPaymentMethod("paypal");

				$amount = new Amount();
				$amount->setCurrency("USD")
				    ->setTotal($request['new_amount']);

				$transaction = new Transaction();
				$transaction->setAmount($amount)
				    ->setDescription(env('APP_NAME'))
				    ->setInvoiceNumber($request['invoice_id']);

				$payment = new FuturePayment();
				$payment->setIntent("sale")
				    ->setPayer($payer)
				    ->setTransactions(array($transaction));

				$request['transaction_id'] = '';
				$request['transaction_fee'] = '0';
				$request['status'] = '0';

		try{
				$payment->updateAccessToken($qr_code->user['paypal_refresh_token'], $apiContext);
				$odata = clone $payment;
	    		$payment->create($apiContext);
}
`

**Comment by pp-randy** [comment]
Have you reviewed Express Checkout on Braintree as and option, which is suggested in both the Android or iOS README.md?
 
https://developer.paypal.com/docs/accept-payments/express-checkout/ec-braintree-sdk/get-started/

**Comment by pp-randy** [comment]
This is the list of Countries supported by my above suggestion https://developer.paypal.com/docs/accept-payments/express-checkout/ec-braintree-sdk/countries/

**Comment by rohitdalal67** [comment]
@pp-randy  I cannot follow Express Checkout, because I have two apps one for **User** and Other for **Merchant**
The payment is done on **Vendor App** and the requirement is automatic payment(User don't have to re-authenticate every time for new payment, User will only once authenticate) from the User Paypal Account.
Hence we used the future payment option.
Is there any way I can get it done?

**Comment by xiaoleih41** [comment]
@rohitdalal67  Can you client contact the regional sales team. Based on your client's detail situation, the sales team will make recommendations and assign integration resources to help provide the technical guidance you need. Billing agreement is an advanced feature that needs to be vetted by PayPal based on your client's specific business situation. I would strongly suggest your client to get whatever feature needed approved before putting in any integration effort.

**Comment by rohitdalal67** [comment]
@xiaoleih41 Thanks, will do

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been given.
