### ISSUE TITLE
ERROR: Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/billing-agreements/

### ISSUE THREAD

**Issue by windups76** [paypal/PayPal-PHP-SDK#1044]
Hello,

if i create an agreement (also with this simple example from: http://paypal.github.io/PayPal-PHP-SDK/sample/doc/billing/CreateBillingAgreementWithPayPal.html), i always get a 400 response.  
Paypal.log:

{"name":"BUSINESS_VALIDATION_ERROR","details":[{"field":"validation_error","issue":"Incorrect Template Id."}],"message":"Validation Error.","information_link":"https://developer.paypal.com/docs/api/payments.billing-agreements#errors","debug_id":"8d4bb95add617"}

E.g. Billing Plans is working, Auth.cache data is writing (correct permission). 

### General information

REST API SDK for PHP (20.01.2018)
* Environment: Sandbox 
* PayPal-Debug-ID` values: 8d4bb95add617
* Language, language version, and OS: PHP, 7.0.26, Debian 3.2.96-2

### Issue description

I write a typo3 extension. The creation of a billing plan is working with correct response. But if i have create an agreement ($agreement->create($apiContext)) the response is a 400 Error:

[20-01-2018 16:51:36] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.sandbox.paypal.com/v1/oauth2/token
[20-01-2018 16:51:36] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 200
[20-01-2018 16:51:36] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.sandbox.paypal.com/v1/payments/billing-agreements/
[20-01-2018 16:51:38] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 400
[20-01-2018 16:51:38] PayPal\Core\PayPalHttpConnection : ERROR: Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/billing-agreements/. {"name":"BUSINESS_VALIDATION_ERROR","details":[{"field":"validation_error","issue":"Incorrect Template Id."}],"message":"Validation Error.","information_link":"https://developer.paypal.com/docs/api/payments.billing-agreements#errors","debug_id":"8d4bb95add617"}
  
The auth.cache is writeable. 

Thanks in advance for the help.

**Comment by pp-randy** [comment]
Can you provide the request JSON that was generated?  It will help me with reproducing the issue.

**Comment by pp-randy** [comment]
I think your Plan ID might be incorrect.  Is it a valid and active Billing Plan? 

https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/billing/CreatePlan.php

**Comment by pp-randy** [comment]
Are you able to create an Agreement with this plan id then `P-8MC52885MW5187036D34MRK`?

**Comment by pp-randy** [comment]
Comment out this line https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/billing/CreateBillingAgreementWithPayPal.php#L12

Update this line with your Plan ID `P-8MC52885MW5187036D34MRK`:
https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/billing/CreateBillingAgreementWithPayPal.php#L47

**Comment by pp-randy** [comment]
The sample chains the API calls to make these sample calls work; however, once you get a plan active you can reuse it.   The plan looks ok, but what I need is the request JSON for the actual Create Billing Agreement call from CreateBillingAgreementWithPayPal.php.

**Comment by windups76** [comment]
Hello,

yes, this sample works fine. **This was the crucial clue (reusable).**
I have used the wrong Plan Object:
$plan = Plan::get($createdPlan->getId(), $apiContext);

**Solution:**
$createdPlan->update($patchRequest, $apiContext);
$plan = Plan::get($createdPlan->getId(), $apiContext);
{...}
$plan = new Plan();
**$plan->setId($createdPlan->getId());**
$agreement->setPlan($plan);

Special Thanx. Great support!
