### ISSUE TITLE
No /v1/customer/ integration?

### ISSUE THREAD

**Issue by pugsley** [paypal/PayPal-PHP-SDK#1046]
I've had a look around (apologies if I've missed it) and I can't find any support for `/v1/customer/*` support — specifically `/v1/customer/partner-referrals`. Is this supported or are there plans to support it?

Thanks!

**Comment by usenetCoder** [comment]
Hey Randy. Is there a time frame for release of the new API? I think developers are looking forward to it.

**Comment by sucithrashanu** [comment]
@usenetCoder 

Currently we do not have any stipulated timeline for the new SDK release, but it may be available in near future.

Please Check [PayPal Community](https://www.paypal-community.com) and  [MTS](https://paypal.com/mts) 
Thanks!

**Comment by levelfivehub** [comment]
Hi

Any updates on this issue?  I am also looking for /v1/customer integration

Thanks
