### ISSUE TITLE
Accepting claims

### ISSUE THREAD

**Issue by SeriousJ55** [paypal/PayPal-PHP-SDK#1047]
Is there an SDK function to accept claims?

The rest API has an "accept-claim" fonction that accepts a claim based on a dispute ID:
/v1/customer/disputes/{dispute_id}/accept-claim

It was in beta testing a few months ago. Now it seems to be fully available. But I don't find a corresponding function in the PHP SDK.

We used to simply refund disputed sales and the claim would automatically be closed. Since about two weeks ago, refunding a disputed sale now always returns the following error message: "Request was refused. This transaction already has a chargeback filed"

This is strange since we can see that there isn't a chargeback using the web UI. The dispute is still open and no chargeback has been issued. And we can close the claim by just refunding the disputed sale using the web UI.

For some reason, it doesn't work anymore with the rest API. So I guess we need to use "accept-claim" instead.

**Comment by pp-randy** [comment]
The API is not available in the SDK, new versions of the SDKs are in active development where new APIs will be added going forward.  Some of the limited access APIs may or may not be added however.  

I don't think the introduction of the Disputes API, especially if you don't have access to it, should impact your existing integration and I encourage you to escalate that aspect of your issue to PayPal Technical Support at https://www.paypal-techsupport.com/app/ask.

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been given.
