### ISSUE TITLE
Client side, Server side or Hybrid integration?

### ISSUE THREAD

**Issue by gety9** [paypal/PayPal-PHP-SDK#1048]
Guys hi,

It's not an issue, but more a question related to integration with checkout.js.

Paypal Express Checkout offers 3 integration options:

Client Side and Server Side - listed on paypal website.

Hybrid - for some reason not listed on the website, but listed in github examples.

I wonder how to understand what integration is right for specific case?
What are the pros and cons of each of them?

**Comment by xiaoleih41** [comment]
PayPal integration will always include client side integration. Are you getting the info from [this page](https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/set-up-a-payment/)? The client side only SDK is a simple button experience, You collect and finalize all info on clientside then click the button, all the info sent to PayPal and process and done. To add server side integration will give you more flexibility to customize the experience, modify the info and so on. There's another option is Express checkout through Braintree SDK which  gives you the opportunity to use Braintree SDK and prepare the integration if you ever want to switch  fully to Braintree completely  to add more payment methods such as credit card or apple pay etc.

**Comment by gety9** [comment]
Thank you! That's explains it!
