### ISSUE TITLE
Payment ok but no money-transfer

### ISSUE THREAD

**Issue by mfive** [paypal/PayPal-PHP-SDK#1049]
Hi!
i integrated this within my second project. On the first project it works fine since 3 years so i think i got the overall idea and it is working. On my second project we have the similar approach and the payment also is going fine but this time no money was transfered several times. I put the LIVE level to DEBUG but no file is generated i dont see any errors also the payment goes ok and PayPal sends the user back to our Thank-You-Page-URL...with the Debug IDs at Developers ID there is a green checkbox icon which indicates ok..but still no money transfer from a real account. Now one week later i tried to pay same checkout with another account which is in a negative saldo..now i received by coincidence following error message to balance out our account and there it stands:

how does that come? there must be something wrong but we can not debug this. any clue? or help? how can i reach or force debug informations?

where "object, object" is written there must be the amount of like for example we paid: 1.00 EUR....whats wrong here? at the first paywall step we see the proper amount to pay for! 

![bildschirmfoto 2018-02-02 um 15 21 48](https://user-images.githubusercontent.com/1105839/35737737-d6cdfd30-082c-11e8-881b-c42cc7bc3f31.png)

**Comment by mfive** [comment]
you see also attached the calls which where OK according to LIVE API Calls Dev Area...
![bildschirmfoto 2018-02-02 um 15 57 14](https://user-images.githubusercontent.com/1105839/35739451-ed2cad6a-0831-11e8-8b90-055c505b0ead.png)

**Comment by xiaoleih41** [comment]
Are you using PayPal plus?  Please contact customer service number on your account and check if there's any account related issue to prevent this transaction from happening as I don't see anything from the technical side from my end.

**Comment by mfive** [comment]
oh yes we have PayPal Plus Customer Account! It was really so difficult to just setup the account itself...but where to call exactly? i tried in the past and its hard to get the right person on related on those technical stuff...

**Comment by xiaoleih41** [comment]
inside your PayPal account, you should have a contact us section which will list your regional customer service number.

**Comment by xiaoleih41** [comment]
Close this issue as the contact info has been provided

**Comment by mfive** [comment]
thanx. i still try to reach someone :)

**Comment by mfive** [comment]
this works now...we were to dump to see that execution-payment must be called after receive paypal object...
