### ISSUE TITLE
{"error":"invalid_client","error_description":"Client Authentication failed"}PayPal\Exception\PayPalConnectionException: Got Http response code 401 when accessing https://api.paypal.com

### ISSUE THREAD

**Issue by hashcode512** [paypal/PayPal-PHP-SDK#1050]
After all the research I'm unable to find some kind a solution for paypal Please Help me out.In sandbox all was going well I have just change the API credentials and put setConfig mode live through code and I got this 

{"error":"invalid_client","error_description":"Client Authentication failed"}PayPal\Exception\PayPalConnectionException: Got Http response code 401 when accessing https://api.paypal.com/v1/oauth2/token. in /home/buyinsta/public_html/seo/smmexpertss.com/wp-content/plugins/firstplugin/includes/pay/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php:202
Stack trace:
#0 /home/buyinsta/public_html/seo/smmexpertss.com/wp-content/plugins/firstplugin/includes/pay/vendor/paypal/rest-api-sdk-php/lib/PayPal/Auth/OAuthTokenCredential.php(246): PayPal\Core\PayPalHttpConnection->execute('grant_type=clie...')
#1 /home/buyinsta/public_html/seo/smmexpertss.com/wp-content/plugins/firstplugin/includes/pay/vendor/paypal/rest-api-sdk-php/lib/PayPal/Auth/OAuthTokenCredential.php(271): PayPal\Auth\OAuthTokenCredential->getToken(Array, 'AaRa-XNeEQ1SzsH...', 'EJCz2p8emrL6PdN...', 'grant_type=clie...')
#2 /home/buyinsta/public_html/seo/smmexpertss.com/wp-content/plugins/firstplugin/includes/pay/vendor/paypal/rest-api-sdk-php/lib/PayPal/Auth/OAuthTokenCredential.php(210): PayPal\Auth\OAuthTokenCredential->generateAccessToken(Array, NULL)
#3 /home/buyinsta/public_html/seo/smmexpertss.com/wp-content/plugins/firstplugin/includes/pay/vendor/paypal/rest-api-sdk-php/lib/PayPal/Auth/OAuthTokenCredential.php(160): PayPal\Auth\OAuthTokenCredential->updateAccessToken(Array)
#4 /home/buyinsta/public_html/seo/smmexpertss.com/wp-content/plugins/firstplugin/includes/pay/vendor/paypal/rest-api-sdk-php/lib/PayPal/Handler/RestHandler.php(82): PayPal\Auth\OAuthTokenCredential->getAccessToken(Array)
#5 /home/buyinsta/public_html/seo/smmexpertss.com/wp-content/plugins/firstplugin/includes/pay/vendor/paypal/rest-api-sdk-php/lib/PayPal/Transport/PayPalRestCall.php(75): PayPal\Handler\RestHandler->handle(Object(PayPal\Core\PayPalHttpConfig), '{"intent":"sale...', Array)
#6 /home/buyinsta/public_html/seo/smmexpertss.com/wp-content/plugins/firstplugin/includes/pay/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PayPalResourceModel.php(104): PayPal\Transport\PayPalRestCall->execute(Array, '/v1/payments/pa...', 'POST', '{"intent":"sale...', Array)
#7 /home/buyinsta/public_html/seo/smmexpertss.com/wp-content/plugins/firstplugin/includes/pay/vendor/paypal/rest-api-sdk-php/lib/PayPal/Api/Payment.php(576): PayPal\Common\PayPalResourceModel::executeCall('/v1/payments/pa...', 'POST', '{"intent":"sale...', NULL, Object(PayPal\Rest\ApiContext), Object(PayPal\Transport\PayPalRestCall))
#8 /home/buyinsta/public_html/seo/smmexpertss.com/wp-content/plugins/firstplugin/index.php(129): PayPal\Api\Payment->create(Object(PayPal\Rest\ApiContext))
#9 /home/buyinsta/public_html/seo/smmexpertss.com/wp-includes/class-wp-hook.php(298): my_action('')
#10 /home/buyinsta/public_html/seo/smmexpertss.com/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array)
#11 /home/buyinsta/public_html/seo/smmexpertss.com/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#12 /home/buyinsta/public_html/seo/smmexpertss.com/wp-admin/admin-ajax.php(101): do_action('wp_ajax_nopriv_...')
#13 {main}

**Comment by xiaoleih41** [comment]
Close this issue as it's a duplicated issue of https://github.com/paypal/PayPal-PHP-SDK/issues/1051

**Comment by Satys** [comment]
Did you check if the environment is set to 'live'? I had set 'production'. It should be 'live'.
