### ISSUE TITLE
getting 401 error accessing Paypal API live

### ISSUE THREAD

**Issue by hashcode512** [paypal/PayPal-PHP-SDK#1051]
I have posted on GitHub and here three days ago but no one shows me a path as I'm a beginner and am stuck into PayPal API when I'm switching to live mood through the code I'm facing 401 error. I guess there is something wrong with the token I don't understand what the hack is token and how to use in my code. I have searched on GitHub and here I got some solutions and applied but all are useless still.

I have made changes to lib/PayPal/Core folder in PayPalConstants.php `const REST_SANDBOX_ENDPOINT = "https://api.paypal.com/";`

But didn't work please help me out.I'll be very thankful.

**Comment by xiaoleih41** [comment]
Did you follow [this instruction](https://github.com/paypal/PayPal-PHP-SDK/wiki/Going-Live)?

**Comment by hashcode512** [comment]
yes I did let me show you the snippet of code `$paypal->setConfig(
  array(
    		'mode' => 'live',
            'log.LogEnabled' => true,
            'log.FileName' => '../PayPal.log',
            'log.LogLevel' => 'DEBUG', // PLEASE USE `INFO` LEVEL FOR LOGGING IN LIVE ENVIRONMENTS
            'cache.enabled' => true,
  )
);`

**Comment by xiaoleih41** [comment]
If you have switched out the client ID and secret then get this error, it may have something to do with the API call you are trying to make. You may not have certain permission in mode to make certain advanced call. Please contact developer.paypal.com/support to open a ticket for your specific account. The engineer there should be able to help you with that.

**Comment by hashcode512** [comment]
Maybe you are right Bro. I'm gonna attach my error please see and let me know what should I have to do Thanks again 

`[url:PayPal\Exception\PayPalConnectionException:private] => https://api.paypal.com/v1/oauth2/token
    [data:PayPal\Exception\PayPalConnectionException:private] => {"error":"invalid_client","error_description":"Client Authentication failed"}
    [message:protected] => Got Http response code 401 when accessing https://api.paypal.com/v1/oauth2/token.
    [string:Exception:private] => 
    [code:protected] => 401
    [file:protected] => /home/buyinsta/public_html/seo/smmexpertss.com/wp-content/plugins/firstplugin/includes/pay/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php
    [line:protected] => 202
    [trace:Exception:private] => Array`

**Comment by xiaoleih41** [comment]
Please make sure your live client ID and secret are copied pasted exactly what was listed on your live developer account. Please make sure you have put in the correct live PayPal account as well. That should be the issue.

**Comment by xiaoleih41** [comment]
Close the issue as the answer has been provided

**Comment by chi11ax** [comment]
@xiaoleih41 sorry to sound silly, but where do you enter the account? In the sandbox, I just have the Client ID and Secret. When I added the api context `'mode'=>'live'`, I still get this error.

**Comment by Sebi94nbg** [comment]
@chi11ax if the sandbox works fine, live should also work out-of-the box, when you change the client ID and secret PLUS you add the move 'live'.

In sandbox AND live environment:
```
$apiContext = new \PayPal\Rest\ApiContext(
        new \PayPal\Auth\OAuthTokenCredential(
            'AYSq3RDGsmBLJE-...GfwddNXWz0uFU9ztymOhRS',     // ClientID
            'EGnHDxD_qRPdaLd...NKYQvQSBngp4PTTVWkPZRbL'      // ClientSecret
        )
);
```
_Reference:_ [Wiki: Making First Call](https://github.com/paypal/PayPal-PHP-SDK/wiki/Making-First-Call)

In sandbox environment:
```
$apiContext->setConfig(
      array(
        'log.LogEnabled' => true,
        'log.FileName' => 'PayPal.log',
        'log.LogLevel' => 'DEBUG',
        'mode' => 'sandbox'
      )
);
```
`'mode' => 'sandbox'` is the important line here. `sandbox` is the default setting, so it is not necessary, to set it for sandbox environments again.

In live environment:
```
$apiContext->setConfig(
      array(
        'log.LogEnabled' => true,
        'log.FileName' => 'PayPal.log',
        'log.LogLevel' => 'DEBUG',
        'mode' => 'live'
      )
);
```
_Reference:_ [Wiki: Adding Configurations](https://github.com/paypal/PayPal-PHP-SDK/wiki/Adding-Configurations)

**Comment by kamleshwebtech** [comment]
I got the solution, Just added paypal client_id, secret and paypal mode (sandbox or live) in dot env file then re-run php artisan serve command in command line. I was 100% sure, it will work. I did it and it worked, very happy now. thank for asking this question.

**Comment by buttflattery** [comment]
i also get the same issue when turning to live mode from sandbox i have enabled logging and i get the below 

> [21-05-2019 11:42:37] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/oauth2/token
> [21-05-2019 11:42:40] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 401
> [21-05-2019 11:42:40] PayPal\Core\PayPalHttpConnection : ERROR: Got Http response code 401 when accessing https://api.paypal.com/v1/oauth2/token. {"error":"invalid_client","error_description":"Client Authentication failed"}
> 

i have added `"mode"=>"live"` via 
```
$apiContext->setConfig(
            [
                'mode' => 'live',
                'log.LogEnabled' => true,
                'log.FileName' => 'PayPal.log',
                'log.LogLevel' => 'DEBUG'
            ]
);
```

and i used the secret and client ID for the live ?

Anybody has an idea why is it behaving like this , i i switch the mode to `sandbox` without changing the credentials that are for the live mode, it redirects to sandbox? why is that happening it should not be it should say that the clientId and secret are incorrect.
