### ISSUE TITLE
Paypal Plus - Links / samples

### ISSUE THREAD

**Issue by tuliogoiania** [paypal/PayPal-PHP-SDK#1054]
Good afternoon,

I looked at the examples, I'm sorry for the ignorance but I did not find out about Paypal Plus.
For sending credit card, and data without the need of redirection to the site of the paypal itself.
Thanks if you can send me the link with the instructions.

**Comment by xiaoleih41** [comment]
PayPal plus product can be different depending on which region you are in. Please submit a support ticket at www.developer-techsupport.com for your regional tech team to help you will your specific questions.

**Comment by tuliogoiania** [comment]
Hello,
Thanks for the interest and help, I could not enter the link.   www.developer-techsupport.com  (error)

The region that we will implement is Brazil (BRL).

**Comment by bluk** [comment]
@tuliogoiania I believe @xiaoleih41 meant https://www.paypal-techsupport.com/ for tech support. For general support, you can find more info at https://developer.paypal.com/support/

**Comment by bluk** [comment]
Closing since Tech Support is the best resource and this isn't a SDK issue.
