### ISSUE TITLE
Rounding off by one error in SDK

### ISSUE THREAD

**Issue by markwillis82** [paypal/PayPal-PHP-SDK#1055]
### General information

* SDK/Library version: 1.13
* Environment: Both
* Language, language version, and OS: PHP5.6/7 any OS

### Issue description

When adding items to the order, the totals are rounded to 2 decimal places before calculations are done to compare against the total. This results in the possibly of an off-by-one error.

Example below:

```

Array
--
  | (
  | [amount] => Array
  | (
  | [currency] => GBP
  | [total] => 253.71
  | [details] => Array
  | (
  | [shipping] => 0
  | [tax] => 42.29
  | [subtotal] => 211.43
  | )
  |  
  | )
  |  
  | [item_list] => Array
  | (
  | [items] => Array
  | (
  | [0] => Array
  | (
  | [name] => 150mm x 9mm Cover Board Golden Oak (Pack of 2)
  | [currency] => GBP
  | [quantity] => 5
  | [sku] => U150WGPACK2
  | [price] => 43.37
  | )
  |  
  | [1] => Array
  | (
  | [name] => Discount
  | [currency] => GBP
  | [quantity] => 1
  | [sku] => discount
  | [price] => -5.42
  | )
  |  
  | )
  |  
  | )
  |  
  | [description] => Gutter Supplies Order
  | [invoice_number] => 5a7af8d25b894
  | )

```

using these figures we get: ((43.37*5)-5.42) + 42.29 = 253.72, But the actual values sent to the PHP SDK are:

```
[cost] => 253.7145
  | [delivery] => 0
  | [tax] => 42.28575
  | [cart] => 211.42875
  | [discount] => 5.42125
  | [pre_discount] => 216.85
  | [subtotal] => 211.42875
  | [items] => Array
  | U150WGPACK2 =>  216.85  (Quantity: 5)
```

Removing the `formatToNumber` in `FormatConvertor` gives us the correct values in the output but then the API call fails because the numbers are not rounding to 2 decimal places.

Price calculations should be calculated on non-rounded numbers and then the resulting number should be rounded to 2 decimal places.

**Comment by xiaoleih41** [comment]
We are looking into this.

**Comment by sucithrashanu** [comment]
@markwillis82 

It is working fine.Can you check the issue is resolved?

Thanks
