### ISSUE TITLE
getting warning while parseResponseHeader

### ISSUE THREAD

**Issue by gaurangrajvir** [paypal/PayPal-PHP-SDK#1059]
Latest version of PHP paypal sdk. I am taking it via composer > "paypal/rest-api-sdk-php": "*",

I am getting error while parseResponseHeader as I am connecting paypal via proxy and in response i am getting extra header i.e. connection established and because of that getting below error. 
```
{
    "code": -1,
    "message": "Notice: Undefined offset: 1",
    "trace": [
        {
            "namespace": "",
            "short_class": "",
            "class": "",
            "type": "",
            "function": "",
            "file": "/var/www/mps/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php",
            "line": 86,
            "args": []
        },
        {
            "namespace": "PayPal\\Core",
            "short_class": "PayPalHttpConnection",
            "class": "PayPal\\Core\\PayPalHttpConnection",
            "type": "->",
            "function": "parseResponseHeaders",
            "file": null,
            "line": null,
            "args": [
```

I suggest to put some condition like below in File : PayPalHttpConnection.php 
Method : parseResponseHeaders
Line number : 85 
```php
 if (strpos($trimmedData, ":") == false) {
            return strlen($data);
}
```

Thanks,
Gaurang

**Comment by xiaoleih41** [comment]
We are looking into this.

**Comment by xiaoleih41** [comment]
Can you please submit a pull request and we are more than happy to review it.

**Comment by gaurangrajvir** [comment]
thanks for your reply. 

I already created pull request... > https://github.com/paypal/PayPal-PHP-SDK/pull/1060

Please let me know if i need to do anything else..

Thanks,
Gaurang

**Comment by gaurangrajvir** [comment]
Can you please check this ?

**Comment by gaurangrajvir** [comment]
Hello Again,

Any update on this ?

Thanks,
Gaurang

**Comment by gaurangrajvir** [comment]
any update on this ?

**Comment by prakash-gangadharan** [comment]
Hi @gaurangrajvir,  your pull request https://github.com/paypal/PayPal-PHP-SDK/pull/1060 for this issue was merged on on Apr 6, 2018. Hence closing this issue.
