### ISSUE TITLE
How to set custom company logo, while using PHP SDK?

### ISSUE THREAD

**Issue by tomazahlin** [paypal/PayPal-PHP-SDK#1064]
* SDK/Library version: 1.13.0
* Environment: Sandbox and Production

### Issue description

When creating order, as described here:

https://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/CreatePaymentUsingPayPal.html

How do I set our company's logo? There is some TemplateData class and some others, but no examples how to put that together.

**Comment by tomazahlin** [comment]
The other question, very similar to the issue above. Is there any way to disable shipping address, because we are selling software, no physical products. All I could find was again for Web Experience... what ever that is, but this rest api sdk seems to be stuck in the 90's just like somebody else wrote.

**Comment by bluk** [comment]
I would suggest [creating a Payment Experience Web Profile](https://developer.paypal.com/docs/api/payment-experience/#web-profiles_create) similar to the [sample here](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payment-experience/CreateWebProfile.php) with the options you want. It sounds like you want [noShipping](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payment-experience/CreateWebProfile.php#L40) and the [logo image](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payment-experience/CreateWebProfile.php#L25). Save the ID of the profile you created. 

Then when you are creating your payment, you can set the profile id using [`setExperienceProfileId`](https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Api/Payment.php#L406) on the Payment. You can re-use the same web profile on multiple payments.

If you have any additional questions, please leave a comment or open a new issue. Thanks.
