### ISSUE TITLE
Not find approve payment file after create payment in Rest API PHP - For CreditCard Payment 

### ISSUE THREAD

**Issue by VipulBokarvadiya** [paypal/PayPal-PHP-SDK#1065]
Hello

I want to create website where user can pay through Credit Card without leaving website. I am using Rest API.  From my point of view there must be below steps to complete successful transaction

1. Create Payment
2. Approve Payment
3. Execute Payment.

Take a look at Create Payment Sandbox link I implemented. https://www.vemgoo.com/paypal-plus/paypal/rest-api-sdk-php/sample/payments/CreatePayment.php

Now I am confused with 2nd step (Approve Payment). Which file I need to run for approval? Can you please share with me filename or some PHP curl code?

Also in first step I am not getting Payer ID that must need in 3rd step.

Please help me. Thanks in advance.

**Comment by xiaoleih41** [comment]
This is for paypal payment or paypal guest payment for new PayPal users only.  If you are looking for credit card payment function please look into Braintree SDK instead. It supports both PayPal payment and direct credit card payments.

**Comment by VipulBokarvadiya** [comment]
I only want credit card payment without leaving my website. Is this not possible with paypal REST API?

**Comment by xiaoleih41** [comment]
You can have PayPal payments without leaving website too if you are using PayPal REST API. If you are looking for direct credit card payment feature, you should look into Braintree SDK as PayPal REST APi no longer support direct credit card processing.

**Comment by VipulBokarvadiya** [comment]
I am using paypal REST api. Which file i need to run after create payment?

**Comment by bluk** [comment]
The "Approve Payment" step is for PayPal payments, and not credit card payments. However, as @xiaoleih41 noted, [Credit Card payments via the PayPal REST API is restricted](https://developer.paypal.com/docs/api/payments/) and no new credit card payment integrations are supported. [Braintree Direct](https://www.braintreepayments.com/products/braintree-direct), a PayPal service, is the recommended service to process credit cards.

**Comment by bluk** [comment]
If you still have questions or if you cannot use Braintree Direct, you can contact [PayPal Support](https://developer.paypal.com/support/) for your account to find the best integration path going forward.

**Comment by VipulBokarvadiya** [comment]
I have paypal plus account, still its not supporting?

**Comment by xiaoleih41** [comment]
It's a duplicated query.  Please refer to the other issue going forward
