### ISSUE TITLE
PayPal Plus for Germany Country - Which API I need to use to accept credit card payment?

### ISSUE THREAD

**Issue by VipulBokarvadiya** [paypal/PayPal-PHP-SDK#1066]
Hello

My client is from Germany and have PayPal Plus account. He want to accept payment through Credit Card without leaving website. Which API I need to use for this?
I used REST API. . From my point of view there must be below steps to complete successful transaction

Create Payment
Approve Payment
Execute Payment.

Take a look at Create Payment Sandbox link I implemented. https://www.vemgoo.com/paypal-plus/paypal/rest-api-sdk-php/sample/payments/CreatePayment.php

Now I am confused with 2nd step (Approve Payment). Which file I need to run for approval? Can you please share with me filename or some PHP curl code?

Also in first step I am not getting Payer ID that must need in 3rd step.

Please help me. Thanks in advance.

**Comment by xiaoleih41** [comment]
This is a direct credit card payment sample. The transaction is done instantly. for PayPal plus integration, you may look into createPaymentwithPayPal file instead as the backend is actually PayPal processing instead of direct credit card processing.

**Comment by VipulBokarvadiya** [comment]
So in direct payment with credit card there no need approval? Please run below script in your browser and see response. Is transaction completed by running this url?
https://www.vemgoo.com/paypal-plus/paypal/rest-api-sdk-php/sample/payments/CreatePayment.php

**Comment by xiaoleih41** [comment]
Yes but it doesn't support PayPal plus production. The PayPal plus product is using the CreatePaymentwithPayPal.php file instead.

**Comment by VipulBokarvadiya** [comment]
By using CreatePaymentwithPayPal.php need to redirect to paypal website? If yes then which file I need to use to do credit card payment within my website without redirecting to paypal?

**Comment by xiaoleih41** [comment]
It will be a PayPal iframe not a redirect URL. Please take a look at this [integration guide](https://www.paypalobjects.com/webstatic/downloads/PayPal-PLUS-IntegrationGuide.pdf) for the detail.

**Comment by VipulBokarvadiya** [comment]
Thank you for valuable information. So after running CreatePaymentwithPayPal.php this file, then which second file I need to run for payment approval? And after approval which third file I need to run for execute payment?

**Comment by xiaoleih41** [comment]
once it's approved,  there will be a return URL. containing the payment_token as well as the payer Id.  You then run execute payment file to process the payment.

**Comment by VipulBokarvadiya** [comment]
So all this steps done within my website without redirecting to PayPal? How I run approve url? Is there any file in api?

**Comment by xiaoleih41** [comment]
It looks like it is using an older version of PayPal checkout.js. I am checking internally to see if approvalURL is necessary or you can move on to use our new PayPal checkout.js instead.

**Comment by VipulBokarvadiya** [comment]
I am using REST api from github. Which che kout.js I need to use?

**Comment by xiaoleih41** [comment]
As it's a regional product, i am not sure if it support our newest version of checkout JS. Is it possible for you to contact developer.paypal.com/support and file a ticket. The regional team should be able to help you on that.

**Comment by VipulBokarvadiya** [comment]
Very poor service by paypal. My ticket is opened from last 10 days. Still
not resolved.

**Comment by xiaoleih41** [comment]
It looks like it doesn't use checkout.js product. it has its own payment wall and you will have to redirect the buyer to  approve the url. there's no other way around it. I hope this has answered your question.

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been given.
