### ISSUE TITLE
not able to execute payment after payment success.

### ISSUE THREAD

**Issue by rizwanmindcrew** [paypal/PayPal-PHP-SDK#1067]
### General information

stdClass Object
(
    [id] => PAY-1AJ840912E341444TLKHLRLY
    [intent] => sale
    [state] => created
    [cart] => 7PW73158NV901182K
    [payer] => stdClass Object
        (
            [payment_method] => paypal
            [status] => VERIFIED
            [payer_info] => stdClass Object
                (
                    [email] => mindcrew.test2@gmail.com
                    [first_name] => Ganesh
                    [last_name] => Gothi
                    [payer_id] => YGMUSUMQL4E46
                    [country_code] => US
                )

        )

    [transactions] => Array
        (
            [0] => stdClass Object
                (
                    [amount] => stdClass Object
                        (
                            [total] => 20.00
                            [currency] => PHP
                        )

                    [payee] => stdClass Object
                        (
                            [merchant_id] => LXBGC96EMLKG4
                            [email] => rizwan.mindcrew@yopmail.com
                        )

                    [description] => Payment description
                    [invoice_number] => 5a8eb8ae260a8
                    [item_list] => stdClass Object
                        (
                            [items] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [name] => ticket
                                            [sku] => 2482
                                            [price] => 20.00
                                            [currency] => PHP
                                            [quantity] => 1
                                        )

                                )

                        )

                    [related_resources] => Array
                        (
                        )

                )

        )

    [redirect_urls] => stdClass Object
        (
            [return_url] => http://mynila.mindcrewexample.com/my-tickets?paymentId=PAY-1AJ840912E341444TLKHLRLY
            [cancel_url] => http://mynila.mindcrewexample.com/my-tickets
        )

    [create_time] => 2018-02-22T12:33:51Z
    [update_time] => 2018-02-22T12:34:42Z
    [links] => Array
        (
            [0] => stdClass Object
                (
                    [href] => https://api.sandbox.paypal.com/v1/payments/payment/PAY-1AJ840912E341444TLKHLRLY
                    [rel] => self
                    [method] => GET
                )

            [1] => stdClass Object
                (
                    [href] => https://api.sandbox.paypal.com/v1/payments/payment/PAY-1AJ840912E341444TLKHLRLY/execute
                    [rel] => execute
                    [method] => POST
                )

            [2] => stdClass Object
                (
                    [href] => https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-7PW73158NV901182K
                    [rel] => approval_url
                    [method] => REDIRECT
                )

        )

)
* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description
I am getting this error while i am executing payment after payment success. 

400{"name":"VALIDATION_ERROR","details":[{"field":"purchase_units[0]","issue":"Item amount must add up to specified amount subtotal (or total if amount details not specified)"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"ba970b052b040"}

**Comment by xiaoleih41** [comment]
What currency are you trying to use? It can't be PHP.  Please check [here](https://developer.paypal.com/docs/integration/direct/rest/currency-codes/) for the correct currency codes.

**Comment by rizwanmindcrew** [comment]
Its allowing me to make payment on my success page i am executing this payment then its showing me this error
400{"name":"VALIDATION_ERROR","details":[{"field":"purchase_units[0]","issue":"Item amount must add up to specified amount subtotal (or total if amount details not specified)"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"3797dfa0720e3"}

PHP is Philippines Pesos 
http://prntscr.com/iipqvg

Please help me i need to show all items on paypal page that's why I am adding items in my code. If I am not adding items then its working fine.

**Comment by xiaoleih41** [comment]
Please specify [detail object](https://developer.paypal.com/docs/api/payments/#definition-details) as well to see if it works for you.

**Comment by xiaoleih41** [comment]
Close the issue as the question has been answered. Please resubmit if the issue hasn't been solved.
