### ISSUE TITLE
 exception : "PayPal\Exception\PayPalConnectionException" And  message : "Got Http response code 503 when accessing https://api.sandbox.paypal.com/v1/payments/payment."

### ISSUE THREAD

**Issue by rinkesh-prajapat** [paypal/PayPal-PHP-SDK#1069]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS:

**Comment by rinkesh-prajapat** [comment]
$itemName = "Amount Add";
  	$currency = $request->get('currency');
  	$name = $request->get('fullname');
        $countryCode = $currency;
        $payableAmount = $request->get('amount');
  	$creditCardNumber = $request->get('cardnumber');
  	$expMonth = $request->get('exp_date');
  	$expYear = $request->get('exp_year');
  	$cvv = $request->get('cvv');
  	$invnm=str_random(20);

   $card = new PaymentCard();
  $card->setType(strtolower('visa')) //visa, mastercard, amex, jcb, or discover
     ->setNumber($creditCardNumber)
     ->setExpireMonth($expMonth)
     ->setExpireYear($expYear)
     ->setCvv2($cvv)
     ->setFirstName('Joe')
     ->setLastName('Shopper')
     ->setBillingCountry('US');

  $fundingInstrument = new FundingInstrument();
  $fundingInstrument->setPaymentCard($card);
  
  $payer = new Payer();
  $payer->setPaymentMethod("credit_card")
        ->setFundingInstruments([$fundingInstrument]);

    $amount = new Amount();
    $amount->setCurrency("USD")
            ->setTotal($payableAmount);

     $item = new Item();
    $item->setName('Amount to Add')// item name 
      ->setCurrency("USD")
      ->setQuantity(1)
      ->setPrice($payableAmount); // unit price  
    // add item to list
    $item_list = new ItemList();
    $item_list->setItems([$item]);

            //->setDetails($details);
            
    $transaction = new Transaction();
        $transaction->setAmount($amount)
            ->setItemList($item_list)
            ->setDescription("Payment description");
            //->setInvoiceNumber(time());

    $payment = new Payment();
    $payment->setIntent("sale")
            ->setPayer($payer)
            ->setTransactions([$transaction]);
   print_r($payment->create($this->_api_context));die;  
   try {
     $payment->create($this->_api_context);
    } catch (\PayPal\Exception\PayPalConnectionException $ex) {
      echo $ex->getData(); die(); // Prints the detailed error message 
    }

**Comment by xiaoleih41** [comment]
Credit card funding feature for REST API has been deprecated. No more new application will be approved. Can you please look into Braintree SDK instead as it supports both PayPal and Credit card processing.

**Comment by xiaoleih41** [comment]
Close this issue as the feature is deprecated.
