### ISSUE TITLE
PayPal \ Exception \ PayPalConnectionException (28) 

### ISSUE THREAD

**Issue by Farouz** [paypal/PayPal-PHP-SDK#1071]
I used the package and it was an error caller size of array() so  i updated the package and i get this error 
PayPal \ Exception \ PayPalConnectionException (28)
Connection timed out after 10000 milliseconds
![image](https://user-images.githubusercontent.com/34202557/36781692-52fe4ee4-1c7f-11e8-9cb1-204ac3889c1e.png)
and i dont know what is the real problem where

**Comment by xiaoleih41** [comment]
Do you have a debugid? Does [this thread](https://github.com/paypal/PayPal-PHP-SDK/issues/481) help ?

**Comment by xiaoleih41** [comment]
Close this issue, please resubmit when you have additional questions.
