### ISSUE TITLE
boolean parameters for constructor

### ISSUE THREAD

**Issue by chief-kh** [paypal/PayPal-PHP-SDK#1073]
`
$webProfile = new WebProfile([
            'name' => 'test' . uniqid(),
            'input_fields' => [
                'no_shipping' => true
            ]
        ]);
        try {
            $webProfileId = $webProfile->create($apiContext)->getId();
        } catch (PayPalConnectionException $e) {
            var_dump($e->getData());die;
        }
`
Code above produces an error
but this one is fine:
`
$webProfile = new WebProfile([
            'name' => 'test' . uniqid(),
            'input_fields' => [
                'no_shipping' => 1
            ]
        ]);
        try {
            $webProfileId = $webProfile->create($apiContext)->getId();
        } catch (PayPalConnectionException $e) {
            var_dump($e->getData());die;
        }
`
why SDK does not support boolean parameter?

**Comment by xiaoleih41** [comment]
@chief-kh `no_shipping` data_type is interger. Please take a look at [this API reference](https://developer.paypal.com/docs/api/payment-experience/).
 
```
no_shipping integer
Indicates whether PayPal displays shipping address fields on the experience pages. Value is:
0. Displays the shipping address on the PayPal pages.
1. Redacts shipping address fields from the PayPal pages. For digital goods, this field is required and must be 1.
2. Gets the shipping address from the customer's account profile.
```
