### ISSUE TITLE
Paypal Rest app Error in Sandbox when i try to create account

### ISSUE THREAD

**Issue by matheusgnreis** [paypal/PayPal-PHP-SDK#1074]
Well, two years ago i have the same problem and repeat today.
When i try to create an app. Inform that i have not sandbox account. So i go went to sandbox page and all of them with error. So i create one. It was sucessfull, but seconds later become an status error.
So, i try to see if this sandbox account is working or not. So i acess at https://www.sandbox.paypal.com/ and then is working well. But a status at developer account at https://developer.paypal.com/developer/accounts/ still with error status and then i cannot create an app.
So i though maybe this account have bug. So i try to create another account and have the same problem.

**Comment by bluk** [comment]
Please contact [PayPal Technical Support](https://developer.paypal.com/support/) to get assistance for your issue.
