### ISSUE TITLE
Autoload issue due to ProductionEnvironment class being located in the file LiveEnvironment

### ISSUE THREAD

**Issue by nimlevy** [paypal/PayPal-PHP-SDK#1075]
### General information
* SDK/Library version: 2.0-beta
* Environment: Production
* `PayPal-Debug-ID` values: -
* Language, language version, and OS: PHP 5.6

### Issue description

Very simple. due to composer default settings.
When trying to load the ProductionEnvironment class I get an error because the filename is: LiveEnvironment which is different from the class name.

* Sandbox works fine.

**Comment by bluk** [comment]
Thanks for the report. I've fixed this in https://github.com/paypal/PayPal-PHP-SDK/commit/510918fd9c2451e9e9a39e5c90f105751328dcbc .
