### ISSUE TITLE
setSetupFee() function wrong format

### ISSUE THREAD

**Issue by iliyanlishkov** [paypal/PayPal-PHP-SDK#1076]
You have a mistaske in your MerchantPreferences() class in setSetupFee() http://prntscr.com/iofl8e
Here is how it should be: http://prntscr.com/iofked
Here is how it is current: http://prntscr.com/iofkp1

This leads to this error: http://prntscr.com/iofkws

You should fix it :)

**Comment by xiaoleih41** [comment]
`setup_fee` is an object of `currency`. Please check here to define `setup_fee` https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/billing/CreatePlan.php#L50

**Comment by xiaoleih41** [comment]
Close this issue as the question has been answered.
