### ISSUE TITLE
MALFORMED_REQUEST on payment execution using v2 beta

### ISSUE THREAD

**Issue by urielhdz** [paypal/PayPal-PHP-SDK#1077]
### General information

 SDK/Library version: dev-2.0-beta
Environment: Sandbox
 Language, language version, and OS: 7.2.2-1+ubuntu16.04.1

### Issue description

I know there's little documentation on v2 beta, but I'm trying to set up a little demo. After getting the approval from the user, I can't execute the payment.

```php
$this->client->execute(new PaymentExecuteRequest($paymentId));
```

But I'm getting the following error:

```json
{"name":"MALFORMED_REQUEST","message":"Incoming JSON request does not map to API request","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#MALFORMED_REQUEST","debug_id":"3d774d3346697"}
```

After searching in the documentation I notice that Im not sending the PayerID attribute, but the source code to execute the Payment does not accepts such argument. How can i set the PaymentID header to execute the payment?

Thank you.

**Comment by bluk** [comment]
You should be able to do something like:

```
$request = new PaymentExecuteRequest($createResponse->result->id);
$request->body = [
          "payer_id" => 'the-payer-id'
];
$this->client->execute($request);
```

**Comment by urielhdz** [comment]
Was coming to edit it. Thank you very much.

**Comment by xiaoleih41** [comment]
Close this issue as it has been solved.
