### ISSUE TITLE
Documentation markup issue

### ISSUE THREAD

**Issue by chief-kh** [paypal/PayPal-PHP-SDK#1080]
Can't copy code from example page. I tried to select code but description text hinder
![1](https://user-images.githubusercontent.com/1894160/37720936-09f8ac2c-2d31-11e8-9471-d42bdc8d55b8.jpg)

**Comment by xiaoleih41** [comment]
you can get the code from [here](https://github.com/paypal/PayPal-PHP-SDK/tree/master/sample).

**Comment by chief-kh** [comment]
Thank you. I already copied it line by line. Just want to let you know, that documentation has such inconvenience

**Comment by xiaoleih41** [comment]
I have noted this to the team. I will close this case.
