### ISSUE TITLE
Agreement::create() does not return id

### ISSUE THREAD

**Issue by chief-kh** [paypal/PayPal-PHP-SDK#1083]
I used this doc:
https://developer.paypal.com/docs/api/payments.billing-agreements/
It says 
 POST /v1/payments/billing-agreements 

Response 
id
string
The PayPal-generated ID for the resource.
Read only.
Maximum length: 128.

But this code returns NULL:
$agreement = $agreement->create($apiContext);
var_dump($agreement->getId());die;
I can't match IPN request to current agreement because id of an agreement is always NULL

**Comment by xiaoleih41** [comment]
The ID won't be created until you execute the billing agreement.

**Comment by xiaoleih41** [comment]
Close the issue as the answer has been given.
