### ISSUE TITLE
Best practice full-page-redirect integration

### ISSUE THREAD

**Issue by NickSdot** [paypal/PayPal-PHP-SDK#1085]
### General information

* SDK/Library version: PHP SDK 2.0 beta
* Environment: Sandbox/Production
* Language, language version, and OS: PHP 7.1

### Issue description

Hello guys,

this is more a best practice question than a issue.
I hope some one can point me to the little piece I am missing in my flow.

I try to implement the PHP SDK beta 2 and pretty much like the easy concept.

The environment is a full-page-redirect integration, so there will be no PayPal Express Button or checkout.js used.

At first I send the `"intent": "sale"` request to `/payment` to create a new payment.

This is done by init the 'SandboxEnvironment':

```
private function _createEnvironment($environment)
{
	// create new SandboxEnvironment/ProductionEnvironment object
	$environment = "\PayPal\Core\\" . $environment;
	$environment = new $environment($this->_client_id, $this->_client_secret);

	if(empty($environment))
	{
		return false;
	}

	return $environment;
}
```

As you can see I use the rest details.
So no API Access Token is use so far.

After that I create the request:

```
private function _createRequest($type, $data)
{
	if(empty($environment = $this->_environment))
	{
		return false;
	}

	// create required objects
	$client  = new PayPalHttpClient($this->_createEnvironment($environment));

	// prepare request object with body
	$request = $this->_prepareRequest($type, $data);

	// return false if no case
	if(empty($client) || empty($request))
	{
		return false;
	}

	$this->_executeRequest($client, $type, $request);
}
```

All works well and I get the response and handle it.
I also save some important response data to the user-session and to the database.
So I am able to get the Payment ID and other stuff when I need it later.

Then I send the user to the external PayPal page `approval_url` which also works.
Whether the payment is approved or not on the PayPal page the user is redirected back to the correct cancel/success urls of my website.
So, all got here as well.

**And now my question.**

I know I need to to the execute request to `/payment/execute/` now after the approval from the user.

But what I wonder and what I really not get is: can I really not do this before (!) the user is already redirected back to my website?
Of course I want to show the user a final payment result if the user arrives back on my website. 
But if I do the 'execute payment' at the same moment as the user come back to the page everything will be delayed a bit. 

Is there no way to get a callback from Paypal like the `onAuthorize` in the client version after the user finished the payment on the Paypal website to make sure that the execute payment request is already done when the user comes back to my website?

I think I nearly read everything I could find in the docs and out there, but there seems to be rare infos or maybe I am just to blind to find.

Thanks in advance for any input on this!

**Comment by xiaoleih41** [comment]
If you want the user complete the payment inside of PayPal then you should use  [PayPal website standard button](https://developer.paypal.com/docs/integration/web/).

**Comment by xiaoleih41** [comment]
Close the issue as the answer has been given.
