### ISSUE TITLE
MALFORMED_REQUEST: Incoming JSON request does not map to API request Issue When I setup payer Info

### ISSUE THREAD

**Issue by ssrgspdkt** [paypal/PayPal-PHP-SDK#1086]
It works correctly without passing payer Info. I would like to setup Payer details. Please check .

Code: 
require __DIR__ . '/../bootstrap.php';
use PayPal\Api\ChargeModel;
use PayPal\Api\Currency;
use PayPal\Api\MerchantPreferences;
use PayPal\Api\PaymentDefinition;
use PayPal\Api\Patch;
use PayPal\Api\PatchRequest;
use PayPal\Api\Plan;
use PayPal\Common\PayPalModel;
use PayPal\Api\Agreement;
use PayPal\Api\Payer;
use PayPal\Api\PayerInfo;
use PayPal\Api\Address;
$agreement = new Agreement();
$agreement->setName('Badsdse Agreement')->setDescription('Badsdsic Agreement')->setStartDate('2019-06-19T9:45:04Z');
$plan = new Plan();
$plan->setId('P-2FT67988MA247830RUO4SUMQ');
$agreement->setPlan($plan);
$payerInfo = new PayerInfo();
$payerInfo->setEmail('testdev@yahoo.com');
$payerInfo->setSalutation('Mr.');
;
$payerInfo->setFirstName('First Dev');
;
$payerInfo->setLastName('DEV Last');
$payerInfo->setPhone('9809555591');
$payerInfo->setPhoneType('WORK');
$billingAddress = new Address();
$billingAddress->setLine1('111 First Street')->setCity('Saratoga')->setState('CA')->setPostalCode('95070')->setCountryCode('US');
$payerInfo->setBillingAddress($billingAddress);
$payer = new Payer();
$payer->setPaymentMethod('paypal');
$payer->setPayerInfo($payerInfo);
$agreement->setPayer($payer);
$request = clone $agreement;
try {
    $agreement   = $agreement->create($apiContext);
    $approvalUrl = $agreement->getApprovalLink();
}
catch (Exception $ex) {
    ResultPrinter::printError("Created Billing Agreement.", "Agreement", null, $request, $ex);
    exit(1);
}
ResultPrinter::printResult("Created Billing Agreement. Please visit the URL to Approve.", "Agreement", "<a href='$approvalUrl' >$approvalUrl</a>", $request, $agreement);
return $agreement;
------

Request JSON:
{
    "name": "Badsdse Agreement",
    "description": "Badsdsic Agreement",
    "start_date": "2019-06-19T9:45:04Z",
    "plan": {
        "id": "P-2FT67988MA247830RUO4SUMQ"
    },
    "payer": {
        "payment_method": "paypal",
        "payer_info": {
            "email": "testdev@yahoo.com",
            "salutation": "Mr.",
            "first_name": "First Dev",
            "last_name": "DEV Last",
            "phone": "9809555591",
            "phone_type": "WORK",
            "billing_address": {
                "line1": "111 First Street",
                "city": "Saratoga",
                "state": "CA",
                "postal_code": "95070",
                "country_code": "US"
            }
        }
    }

**Comment by xiaoleih41** [comment]
I don't see `solution` in billing agreement [payer_info object](https://developer.paypal.com/docs/api/payments.billing-agreements#definition-payer_info).

**Comment by ssrgspdkt** [comment]
Anyway to pass any identifier Or payer details to paypal for retrieve their full details?

**Comment by xiaoleih41** [comment]
I don't' quite understand your question. I was saying that the `salutation` property is not included in the payer_info object.  Removing that should fix the issue.

**Comment by xiaoleih41** [comment]
Close this issue as it should have been solved.
