### ISSUE TITLE
how to transfer moeny to another account ?

### ISSUE THREAD

**Issue by OdaiTu** [paypal/PayPal-PHP-SDK#1087]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description

i want to transfer money to another account and send money to multiple account at the same time ?

**Comment by xiaoleih41** [comment]
Are you looking for [payout API?]( https://developer.paypal.com/docs/api/payments.payouts-batch/?mark=payout). The sample is [here](https://github.com/paypal/PayPal-PHP-SDK/tree/master/sample/payouts).

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been given.
