### ISSUE TITLE
"Return to merchant" Show this message on live

### ISSUE THREAD

**Issue by choudharysuman** [paypal/PayPal-PHP-SDK#1088]
I am getting same problem when i got to live app. On sandbox it is working fine. But on live getting below url:
https://www.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-32A91625D19611252#/checkout/genericError?code=VU5TVVBQT1JURURfUEFZRUVfQ1VSUkVOQ1k%3D

Anyone please assist to me.

**Comment by bluk** [comment]
You need to contact [PayPal Technical Support](https://www.paypal-techsupport.com/) to ensure that your live account is correct.
