### ISSUE TITLE
Internal Server Error in Vult Payments(Sandbox)

### ISSUE THREAD

**Issue by manojwegile** [paypal/PayPal-PHP-SDK#1089]
I have made a app that uses Vault api to make payments. Now the issue is whenever I try to make payment using this api, I got internal server error.
Debug ID : 855ec2bdf14f1
API used : https://api.sandbox.paypal.com/v1/payments/payment

**Comment by xiaoleih41** [comment]
Are you trying to vault a credit card? This feature has been deprecated. Please consider to integrate Braintree SDK instead as it was mentioned in README.MD.

**Comment by xiaoleih41** [comment]
Close this issue as the feature has been deprecated.
