### ISSUE TITLE
Pre-populate billing address

### ISSUE THREAD

**Issue by reefki** [paypal/PayPal-PHP-SDK#1091]
### General information

* SDK/Library version: 1.13.0
* Environment: Sandbox
* Language, language version, and OS: PHP 7.2.4 on macOS 10.13.4

### Issue description

I have two web experience profiles, one with `Login` landing page type and the other set to `Billing`. In my checkout page I provided two options for my customer to pay with PayPal or Credit Card.

If a customer select credit card I use the `Billing` profile to create the payment so the customer will be redirected to the PayPal guess checkout instead of login page.

I'm collecting user billing address on my checkout page for internal use. I'm trying to pass the customer's billing details using `PotentialPayerInfo` class so that my customer shouldn't not enter their billing details twice but I think it's doesn't work, the fields still blank.

Thank you

**Comment by xiaoleih41** [comment]
Please use [payer_info](https://developer.paypal.com/docs/api/payments/#definition-payer_info) instead.  Please note that guest checkout only works for brand new buyers who hasn't experienced PayPal before. Once they have had a PayPal account or experienced guest checkout before, this option may not be available to them and the system may force them to sign in their PayPal account.

**Comment by reefki** [comment]
@xiaoleih41 Thank you, it works but with one exception, the `country_code` (not the one in `billing_address` array). Here my request example:

```
{
  "intent": "sale",
  "payer": {
    "payment_method": "paypal",
    "payer_info": {
      "email": "email@example.com",
      "country_code": "ID",
      "billing_address": {
        "line1": "Address line 1",
        "line2": "Address line 2",
        "city": "City",
        "country_code": "ID",
        "postal_code": "xxxx",
        "state": "State",
        "phone": "xxxxxxxxxx"
      }
    }
  },
  "transactions": [
    {
      "amount": {
        "total": "100",
        "currency": "USD"
      },
      "item_list": {
        "items": [
          {
            "sku": "xxxx",
            "name": "Product",
            "description": "Description",
            "price": "100",
            "quantity": 1,
            "currency": "USD"
          }
        ]
      }
    }
  ],
  "redirect_urls": {
    "return_url": "http://example.com/paypal/callback",
    "cancel_url": "http://example.com/checkout"
  },
  "experience_profile_id": "xx-xxxx-xxxx-xxxx-xxxx"
}
```

In the docs, the `country_code` doesn't have `Read only` label which I think I can pass it on request parameters but the response give me error message.

> Incoming JSON request does not map to API request

If I removed the `country_code` parameter, it works but on the payment page it set to "United States" and the `state` and `phone` parameters are ignored.

**Comment by reefki** [comment]
After some digging in the source code of payment page I found that `state` value must be in uppercase, but I don't still have idea on why the `phone` is ignored, I uses phone number without phone country code.

**Comment by xiaoleih41** [comment]
Did you follow the [format](https://developer.paypal.com/docs/api/payments/#definitions)?

**Comment by reefki** [comment]
Yes, I do. You can see the example request I sent in my previous reply. 

1. Country code, If you see https://developer.paypal.com/docs/api/payments/#definition-payer_info there is also `country_code` attribute outside `billing_address`.

2. Phone, the docs say the phone number must in E.123 format, according to [Wikipedia](https://en.wikipedia.org/wiki/E.123#Example_formats) the example of this format is `+22 607 123 4567`. I've tried with `+22 607 123 4567`, `+226071234567`, `226071234567`, and `6071234567` but none of them worked.

Thanks

**Comment by trainerbill** [comment]
@reefki can you post the request and the response of the api call you are using?

**Comment by trainerbill** [comment]
I am guessing this is just an issue with the docs then... not sure why there would be a country code outside of the billing address.

**Comment by shigg1120** [comment]
@reefki were you able to pre populate a phone? If so, what format did you use and how did you make it work? Please let me know when you get a chance

**Comment by Androbin** [comment]
@trainerbill If the docs are wrong, then the code is, too: https://github.com/paypal/PayPal-PHP-SDK/blob/c2947ff409ba98953f9ad41ea70eec4344d1158f/lib/PayPal/Api/PayerInfo.php#L391
