### ISSUE TITLE
An internal service error occurred "debug_id": "7ed027ccd3c41"

### ISSUE THREAD

**Issue by mohammedfathi92** [paypal/PayPal-PHP-SDK#1094]
I got an internal server error

500{
"name":"INTERNAL_SERVICE_ERROR",
"message":"An internal service error occurred.",
"information_link":"https://developer.paypal.com/docs/api/payments/#errors",
"debug_id":"7ed027ccd3c41"
}

**Comment by xiaoleih41** [comment]
Are you trying to execute a direct credit card payment? This feature has been deprecated. Please consider to integrate Braintree SDK instead. For detetail please refer to README.MD.
