### ISSUE TITLE
MALFORMED_REQUEST Error, no idea how to resolve it

### ISSUE THREAD

**Issue by haroontyagi** [paypal/PayPal-PHP-SDK#1097]
Hi,

I'm using the SDK to send a payment (credit_card method). Everything seems to have the correct data but i am getting same error:
{"name":"MALFORMED_REQUEST","message":"Incoming JSON request does not map to API request","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#MALFORMED_REQUEST","debug_id":"c06742208e15"}

My file as follows(i am testing on sendbox):

`<?php
require __DIR__  . '/autoload.php';

$apiContext = new \PayPal\Rest\ApiContext(
        new \PayPal\Auth\OAuthTokenCredential(
            'client_id',     
            'client_secret'      
        )
);

$item = new \PayPal\Api\Item();
$item->setName("Domain for 1 year")
  ->setDescription("Domain for 1 year")	
  ->setCurrency("USD")
  ->setPrice("135")
  ->setQuantity("1")
  ->setSku("SKU012");

$itemList = new \PayPal\Api\ItemList();
$itemList->setItems(array($item));

$crdtCard = new \PayPal\Api\CreditCard();

$crdtCard->setCvv2("000")  
  ->setExpireMonth(3)
  ->setExpireYear(2020)
  ->setFirstName("Haroon")
  ->setLastName("Tyagi")
  ->setNumber("4032037197488386")
  ->setType("VISA");

$details = new \PayPal\Api\Details();
$details->setShipping("3");
$details->setSubtotal("135");
$details->setTax(2);

$amount = new \PayPal\Api\Amount();
$amount->setTotal('140');
$amount->setCurrency('USD');
$amount->setDetails($details);

$transaction = new \PayPal\Api\Transaction();
$transaction->setAmount($amount);
$transaction->setDescription("Description about the payment amount.");
$transaction->setItemList($itemList);
$transaction->setInvoiceNumber(uniqid());
  
$payerinfo = new \PayPal\Api\PayerInfo();
$payerinfo->setEmail("haroontyagi-buyer@yahoo.co.in");

$fundInstrument = new \PayPal\Api\FundingInstrument();
$fundInstrument->setCreditCard($crdtCard);

$payer = new \PayPal\Api\Payer();
$payer->setFundingInstruments($fundInstrument);
$payer->setPaymentMethod('credit_card');
$payer->setPayerInfo($payerinfo);
  
$payment = new \PayPal\Api\Payment();
$payment->setIntent('sale');
$payment->setPayer($payer);
$payment->setTransactions(array($transaction));

try {
   
    $payment->create($apiContext);
    echo $payment;

	if($payment->state == "approved") {
		echo $response;
	}
	else
		echo "Failure";
}
catch (\PayPal\Exception\PayPalConnectionException $ex) {
    echo $ex->getData();
}`

Any guidance would be greatly appreciated.

**Comment by xiaoleih41** [comment]
I saw a few quotation marks missing or used wrong. Can you please check into them?

**Comment by xiaoleih41** [comment]
As this feature has been deprecated. No more new application will be approved. The API reference has removed. it is very hard to troubleshoot for you.  Can you confirm that you have got the live API permission? If so, where do you get the API reference?

**Comment by xiaoleih41** [comment]
I see. I don't think you will get live permission approved any more as the product has been deprecated. However, please contact customer service number listed on your account to see if you can get any special permission to apply for it.

**Comment by xiaoleih41** [comment]
Close this issue as the issue itself has been solved by the developer.
