### ISSUE TITLE
Got Http response code 400 when using accented characters in AgreementStateDescriptor note

### ISSUE THREAD

**Issue by rsomoza** [paypal/PayPal-PHP-SDK#1098]
I am writing code to cancel an Agreement and was mystified when I continuously received a _"Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/billing-agreements"_ exception.

Eventually, when looking at the logs, I found the following error detail:
_{"name":"VALIDATION_ERROR","details":[{"field":"note","issue":"Note is missing from the request or Note length is too long"}_ This looked pretty ridiculous, as I had assigned the note (in Spanish) and it was not very long either.

On checking the Note in AgreementStateDescriptor, it all seemed all right, and I echoed it to verify it. Unfortunately, it still crashed, so I changed the Spanish text "_Cancelación por parte del usuario_" to "_Cancelado por parte del usuario_" ... and suddenly it worked! 

For some reason, the processing of the
_$existingAgreement->cancel($agreementStateDescriptor, $apiContext);_
statement is unable to handle accented characters in the Note variable.

I suppose this must be a bug on the Paypal processing side, as the SDK itself happily accepted the Note with accented characters.

**Comment by rsomoza** [comment]
This is the debug info. I simply changed the text, and suddenly it  worked:

_================================================================================================================================

[29-04-2018 23:43:09] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.sandbox.paypal.com/v1/payments/billing-agreements/I-SC1Y94L7YBMP/cancel
[29-04-2018 23:43:09] PayPal\Core\PayPalHttpConnection : DEBUG: Request Headers 	: POST /v1/payments/billing-agreements/I-SC1Y94L7YBMP/cancel HTTP/1.1, Host: api.sandbox.paypal.com, Accept: */*, Content-Type: application/json, User-Agent: PayPalSDK/PayPal-PHP-SDK 1.13.0 (platform-ver=5.4.45; bit=64; os=Linux_3.10.0-693.17.1.2.ELK.el6.x86_64; machine=x86_64; crypto-lib-ver=1.0.1e-fips; curl=7.19.7), Authorization: Bearer A21AAEuO9VRtAP2OPMAjwbE8EWAl3I88jWlK4R-kLkgtaunyGH3nkAdQOejHXjnb9DSFr4rfnHOOgh4Nn2kBnQacrdFqeS71g, Content-Length: 13, , 
[29-04-2018 23:43:09] PayPal\Core\PayPalHttpConnection : DEBUG: Request Data		: {"note":null}
--------------------------------------------------------------------------------------------------------------------------------

[29-04-2018 23:43:09] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 400
[29-04-2018 23:43:09] PayPal\Core\PayPalHttpConnection : DEBUG: Response Headers	: Date: Sun, 29 Apr 2018 21:43:09 GMT, Server: Apache, paypal-debug-id: 560fad86989cb, Content-Language: *, Connection: close, HTTP_X_PP_AZ_LOCATOR: sandbox.slc, Paypal-Debug-Id: 560fad86989cb, Set-Cookie: X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT, Vary: Authorization, Content-Length: 289, Content-Type: application/json, 
[29-04-2018 23:43:09] PayPal\Core\PayPalHttpConnection : ERROR: Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/billing-agreements/I-SC1Y94L7YBMP/cancel. {"name":"VALIDATION_ERROR","details":[{"field":"note","issue":"Note is missing from the request or Note length is too long"}],"message":"Invalid request. See details.","information_link":"https://developer.paypal.com/docs/api/payments.billing-agreements#errors","debug_id":"560fad86989cb"}
[29-04-2018 23:43:09] PayPal\Core\PayPalHttpConnection : DEBUG:_

**Comment by rsomoza** [comment]
I have changed back the text to the accented character set. An exception is again raised:
Error:
exception 'PayPal\Exception\PayPalConnectionException' with message 'Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/billing-agreements/I-40B2DG24LP68/cancel.' in /home/dragonkin/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php:202 Stack trace: #0 /home/dragonkin/vendor/paypal/rest-api-sdk-php/lib/PayPal/Transport/PayPalRestCall.php(78): PayPal\Core\PayPalHttpConnection->execute('{"note":null}') #1 /home/dragonkin/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PayPalResourceModel.php(104): PayPal\Transport\PayPalRestCall->execute(Array, '/v1/payments/bi...', 'POST', '{"note":null}', NULL) #2 /home/dragonkin/vendor/paypal/rest-api-sdk-php/lib/PayPal/Api/Agreement.php(536): PayPal\Common\PayPalResourceModel::executeCall('/v1/payments/bi...', 'POST', '{"note":null}', NULL, NULL, NULL) #3 /home/dragonkin/invocador_online/paypal_library.php(235): PayPal\Api\Agreement->cancel(Object(PayPal\Api\AgreementStateDescriptor), NULL) #4 /home/dragonkin/invocador_online/paypal_library.php(188): cancelPaypalSubscription('I-40B2DG24LP68', 'Cancelaci\xA8\xAEn po...') #5 /home/dragonkin/invocador_online/realizar_pago.php(305): changePaypalSubscriptionState('I-40B2DG24LP68', 'Cancelaci\xA8\xAEn po...', 'Cancel') #6 /home/dragonkin/invocador_online/invocaciones_a_funcion.php(207): pagos->cancel_user_subscription('alguien', 'Cancelaci\xA8\xAEn po...') #7 /home/dragonkin/public_html/PHPTOOLS/test.php(160): invoke_the_functionTest(NULL) #8 {main}

**Comment by rsomoza** [comment]
The offending code:

//------------------------------------------------------------------------------//
function cancelPaypalSubscription($code,$reason)
{
	include(__DIR__ . '/config/paypal_config.php');

	//Create an Agreement State Descriptor, explaining the reason for suspension of the subscription.
	$agreementStateDescriptor = new AgreementStateDescriptor();
	$agreementStateDescriptor->setNote($reason);
	
	// Fetch the agreement object
	/** @var Agreement $createdAgreement */
	$existingAgreement = getPaypalSubscriptionAgreement($code, $apiContext);

	try {
    		$existingAgreement->cancel($agreementStateDescriptor, $apiContext);
    		// Lets get the updated Agreement Object
    		//$agreement = Agreement::get($existingAgreement->getId(), $apiContext);
	} catch (Exception $ex) {
    		echo "Error al intentar cancelar la subscripción: <br>Acuerdo: " . $existingAgreement->getId(). "<br><br>" . "Error: <br>". $ex;
    		exit(1);
	}
	return $agreement;
}

**Comment by rsomoza** [comment]
It works perfectly if the note does not include accented characters, but fails if those are included.

**Comment by xiaoleih41** [comment]
did you pass in as UTF-8?

**Comment by rsomoza** [comment]
I did not see where in the API you can declare it as UTF-8. 
However, creation of the agreement (with accented characters) and aother API functions worked like a charm.... The error only happens when you try to cancel an eisting agreement, other functions don't seem to have that problem.

**Comment by xiaoleih41** [comment]
I have noted this issue and queued it for the team to work on.

**Comment by prakash-gangadharan** [comment]
Hi @rsomoza,  can you help us with the sample request and the example accented characters which you used in AgreementStateDescriptor note to check this.

**Comment by prakash-gangadharan** [comment]
Hi @rsomoza,

Am using **PayPal-PHP-SDK 1.14.0** with **PHP 7.3.10**. I used accented characters in AgreementStateDescriptor note and could see that the billing agreement has been suspended successfully. Even I tried with the same request via postman and I got successful response.

**Sample Code used**:
```php
<?php
// # Suspend an agreement
//
// This sample code demonstrate how you can suspend a billing agreement, as documented here at:
// https://developer.paypal.com/docs/api/payments.billing-agreements/v1/#billing-agreements_suspend
// API used: /v1/payments/billing-agreements/{agreement_id}/suspend

// Retrieving the Agreement object from Create Agreement Sample to demonstrate the List
require __DIR__ . '/../bootstrap.php';

use PayPal\Api\Agreement;
use PayPal\Api\AgreementStateDescriptor;

//Create an Agreement State Descriptor, explaining the reason to suspend.
$agreementStateDescriptor = new AgreementStateDescriptor();
$agreementStateDescriptor->setNote("Cancelación por parte del usuario");

// Fetch the agreement object
/** @var Agreement $createdAgreement */
$createdAgreement = new Agreement();
$createdAgreement->setId('I-6G8P1776VPTP');

try {
    $createdAgreement->suspend($agreementStateDescriptor, $apiContext);
    // Lets get the updated Agreement Object
    $agreement = Agreement::get($createdAgreement->getId(), $apiContext);
} catch (PayPal\Exception\PayPalConnectionException $ex) {
    echo $ex->getCode();
    echo $ex->getData();
    die($ex);
} catch (Exception $ex) {
    die($ex);
}
?>

```
Please feel free to reopen this, if this is still an issue for you.

Thanks!
