### ISSUE TITLE
No application_context object in this package

### ISSUE THREAD

**Issue by jhfyang** [paypal/PayPal-PHP-SDK#1099]
* SDK/Library version: rest-api-sdk-php 1.13.0
* Environment: Sandbox
* Language, language version, and OS: PHP on windows 10 Pro 64x

### Issue description

There is no object defining the application_context from the REST API, is it normal ? if not Is it possible to add it ?

https://developer.paypal.com/docs/api/payments/#definition-application_context

**Comment by xiaoleih41** [comment]
We are working on a newer version of SDK and will include this in the new version.

**Comment by xiaoleih41** [comment]
It is on beta right now.  Please check [here](https://github.com/paypal/PayPal-PHP-SDK/tree/dev-2.0-beta). You just need to add the object to the appropriate request.

**Comment by jhfyang** [comment]
Yeah I have started to use 2.0-dev branch thanks for the help!
