### ISSUE TITLE
PayPal Plus for Germany - Execute Payment error

### ISSUE THREAD

**Issue by profatilov** [paypal/PayPal-PHP-SDK#1101]
I'm trying to add PayPal Plus, using PDF integration guide,  and i have problem with payment execute on return page from paypal.
When i do payment on paypal side it redirects me to the final review page with get data: 
paymentId
token
PayerID

I'm tryiing to execute payment using curl PHP:

            $paymentId = $_GET['paymentId'];
            $token     = $_GET['token'];
            $PayerID   = $_GET['PayerID'];

            $curlopt_url = "https://api.paypal.com/v1/payments/payment/{$paymentId}/execute/";

            $ch = curl_init();

            $post_data    = 'payer_id:' . $PayerID;
            $curl_headers = array('Content-Type:application/json', "Authorization: Bearer {$token}");

            curl_setopt($ch, CURLOPT_URL, $curlopt_url);
            curl_setopt($ch, CURLOPT_HEADER, 0);
            curl_setopt($ch, CURLOPT_HTTPHEADER, $curl_headers);
            curl_setopt($ch, CURLOPT_POST, 1);
            curl_setopt($ch, CURLOPT_POSTFIELDS, $post_data);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

            $response = curl_exec($ch);

            curl_close($ch);

And I'm getting an ERROR = {"error":"invalid_token","error_description":"Token signature verification failed"}"

I have tried to find "examples in PHP" how to make Payment Execution for PayPal PLUS but and nothing work for me. 

Do you have an Example of PHP Code how to make Payment Execute for PayPal PLUS? Thank you!

**Comment by xiaoleih41** [comment]
I believe it should be the same as the sample here however as it's a regional product, please consider to contact developer.paypal.com/support to check if the regional techsupport team has any specific solution for this.

**Comment by xiaoleih41** [comment]
Close this issue as it's a regional product and directed the user to the regional team for support.
