### ISSUE TITLE
getting different transactionID in rest api response than the api showing in paypal sandbox account

### ISSUE THREAD

**Issue by vikramsingh86** [paypal/PayPal-PHP-SDK#1103]
Hi,

I am trying to integrate PayPal PHP rest api by following the same code as mentioned in below URL:
https://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/CreatePaymentUsingPayPal.html

When I execute the step 2 after successful redirection from PayPal(sandbox), payment processed successfully and showing in sandbox account but I am getting different transactionID for each transaction than showing in PayPal sandbox account.

Please help.

Thanks

**Comment by xiaoleih41** [comment]
Can you give me some example? The saleId should match to the transaction ID listed in the receiver's PayPal account.

**Comment by xiaoleih41** [comment]
Close this issue due to inactivity. Please resubmit if the issue has been solved and you have additional info.
