### ISSUE TITLE
rest-api-sample-app-php not found

### ISSUE THREAD

**Issue by franzholz** [paypal/PayPal-PHP-SDK#1105]
Master branch:
README.md:

    Sample App
    If you are looking for a full fledged application that uses the new RESTful APIs, check out the Pizza store sample app at https://github.com/paypal/rest-api-sample-app-php

click on 
Pizza App Using Paypal REST API] (https://github.com/paypal/rest-api-sample-app-php)

However this website does not exist. Where is this sample REST-API application?

**Comment by franzholz** [comment]
see also https://github.com/paypal/PayPal-PHP-SDK/issues/647

**Comment by xiaoleih41** [comment]
We have since pushed out newer version of the [REST PHP SDK](https://github.com/paypal/PayPal-PHP-SDK/tree/dev-2.0-beta). This sample code is no longer applicable. Can you please try out the new 2.0 version instead?

**Comment by eblair84** [comment]
After making the changes in the migration guide, I'm getting a "PHP Fatal error:  Uncaught Error: Class 'PaymentCreateRequest' not found in /var/www/html/project/first.php:24" error.

**Comment by xiaoleih41** [comment]
You can refer to the [test](https://github.com/paypal/PayPal-PHP-SDK/tree/dev-2.0-beta/tests/Test/v1) for the sample code.

**Comment by xiaoleih41** [comment]
Close due to inactivity.
