### ISSUE TITLE
Webhook verification failure

### ISSUE THREAD

**Issue by matthijsotterloo** [paypal/PayPal-PHP-SDK#1107]
Hi everyone!

I'm using the code below to validate a webhook response, the webhook is being called after the payment but for some reason the validation keeps returning a failure. Does anyone know what might be causing this?

Thanks!

`$apiContext = new \PayPal\Rest\ApiContext(
                new \PayPal\Auth\OAuthTokenCredential(
                    'myclientidhere',     // ClientID
                    'myclientsecrethere'      // ClientSecret
                )
            );

        $apiContext->setConfig(array('mode' => 'live',));
        $bodyReceived = file_get_contents('php://input');
        
        $headers = getallheaders();
        $headers = array_change_key_case($headers, CASE_UPPER);

        $signatureVerification = new VerifyWebhookSignature();
        $signatureVerification->setAuthAlgo($headers['PAYPAL-AUTH-ALGO']);
        $signatureVerification->setTransmissionId($headers['PAYPAL-TRANSMISSION-ID']);
        $signatureVerification->setCertUrl($headers['PAYPAL-CERT-URL']);
        $signatureVerification->setWebhookId("mywebhookidhere");
        $signatureVerification->setTransmissionSig($headers['PAYPAL-TRANSMISSION-SIG']);
        $signatureVerification->setTransmissionTime($headers['PAYPAL-TRANSMISSION-TIME']);

        $signatureVerification->setRequestBody($requestBody);
        $request = clone $signatureVerification;

        try {
            $output = $signatureVerification->post($apiContext);
        } catch (Exception $ex) {
            print_r($ex->getMessage());
            exit(1);
        }

        $verificationStatus = $output->getVerificationStatus();
        $responseArray = json_decode($request->toJSON(), true);

        $event = $responseArray['webhook_event']['resource']['event_type'];
        $outputArray = json_decode($output->toJSON(), true);

        if ($verificationStatus == 'SUCCESS') {`

**Comment by Ukuser36** [comment]
Is your webhook ID definitely correct? I deleted mine and forgot to update it in my code.

**Comment by trainerbill** [comment]
We have some issues currently with how SDKs handle the verification.

paypal/PayPal-node-SDK#294

Wondering if you can try to do the verification outside of the PHP SDK using straight REST api so we can narrow it down.

https://developer.paypal.com/docs/api/webhooks/#verify-webhook-signature_webhook

**Comment by matthijsotterloo** [comment]
I resolved it. Made a stupid mistake

**Comment by razorsharpshady** [comment]
> I resolved it. Made a stupid mistake

What was wrong?

**Comment by lyongdee** [comment]
@matthijsotterloo How to solved it, what was wrong?

**Comment by lzw012** [comment]
> @matthijsotterloo How to solved it, what was wrong?

$signatureVerification->setWebhookId('**your Webhook ID**');

**Comment by KingaTheWitch** [comment]
Instead:
`$bodyReceived = file_get_contents('php://input');`
Should be:
`$requestBody = file_get_contents('php://input');`
