### ISSUE TITLE
Missing Payout class(es) in the new SDK (2.0-beta)

### ISSUE THREAD

**Issue by nimlevy** [paypal/PayPal-PHP-SDK#1111]
### General information

* SDK/Library version: 2.0-beta
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: PHP

### Issue description

I'm not seeing the Payouts class in the new SDK. Is there a plan to add that functionality to the new SDK?
And if so, what is the estimated release date?

**Comment by trainerbill** [comment]
Yeah 2.0 is beta so some functionality is not there yet.  It will be there but not sure on a timeframe.
