### ISSUE TITLE
Got Http response code 401 when going Live

### ISSUE THREAD

**Issue by rsomoza** [paypal/PayPal-PHP-SDK#1113]
### General information

* SDK/Library version: PHP-SDK 1.13.0
* Environment: Live
* `PayPal-Debug-ID` values: Http response code 401 when accessing https://api.paypal.com/v1/oauth2/token
* Language, language version, and OS: PHP 5.4.45 running under Apache

### Issue description
I have checked all similar issues in the forum (and also in other forums) but have not been able to resolve the issue.

The problem I face is that I have a code that works perfectly in the sandbox, but fails when I go live.

The only thing that I have done is changed the ClientId and ClientSecret for the live ones. I have also changed the following in the sdk_config file:
log.LogLevel=INFO
mode=live

(I have also  tried to bypass the sdk_config file and set those values with code).

From the Exception information, it can be seen that in stack trace #1, the credentials are passed properly ('Af23YByTnBrnqry...', 'EIfB-LHHinorpqY...'), so I have no clue of what the problem might be. I have checked that the credentials are the correct ones.

And yes, I have also checked (amongst others) https://github.com/paypal/PayPal-PHP-SDK/wiki/Going-Live

As I am using the cache (cache.enabled=true), I also verified that the cache was cleared before going live.

What am I missing? 

### EXCEPTION INFORMATION:
**Fatal error:** Uncaught exception 'PayPal\Exception\PayPalConnectionException' with message 'Got Http response code 401 when accessing https://api.paypal.com/v1/oauth2/token.' in /home/u-2.co/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php:202 
Stack trace: 
#0 /home/u2co/vendor/paypal/rest-api-sdk-php/lib/PayPal/Auth/OAuthTokenCredential.php(246): PayPal\Core\PayPalHttpConnection->execute('grant_type=clie...') 
#1 /home/u2co/vendor/paypal/rest-api-sdk-php/lib/PayPal/Auth/OAuthTokenCredential.php(271): PayPal\Auth\OAuthTokenCredential->getToken(Array, 'Af23YByTnBrnqry...', 'EIfB-LHHinorpqY...', 'grant_type=clie...') 
#2 /home/u2co/vendor/paypal/rest-api-sdk-php/lib/PayPal/Auth/OAuthTokenCredential.php(210): PayPal\Auth\OAuthTokenCredential->generateAccessToken(Array, NULL) 
#3 /home/u2co/vendor/paypal/rest-api-sdk-php/lib/PayPal/Auth/OAuthTokenCredential.php(160): PayPal\Auth\OAuthTokenCredential->updateAccessToken(Array) 
#4 /home/u2co/vendor/paypal/rest-api-sdk-php/lib/PayPal/ in /home/u2co/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php on line 202

### LOGS:
[26-05-2018 18:36:56] PayPal\Core\PayPalHttpConnection : ERROR: Got Http response code 401 when accessing https://api.paypal.com/v1/oauth2/token. {"error":"invalid_client","error_description":"Client Authentication failed"}

**Comment by rsomoza** [comment]
Mystery solved:
The sdk_config file had a COPY of the Sandbox credentials that interfered with my own configuration file. 
This is something that nobody had pointed out so far and is a good lessons learned.

**Comment by flooo89** [comment]
I have the exact same problem as you did. 
Can you tell me where I find this sdk_config file as I am not able to find it?

**Comment by karoman0584** [comment]
@flooo89 I had the same problem. To solve this you have to make your configuration based in file (sdk_config.ini). This solved to me. First go [here](https://github.com/paypal/PayPal-PHP-SDK/wiki/Going-Live) and them go [here](https://github.com/paypal/PayPal-PHP-SDK/wiki/File-based-Configurations)

**Comment by kamleshwebtech** [comment]
I got the solution, Just added paypal client_id, secret and paypal mode (sandbox or live) in dot env file then re-run php artisan serve command in command line. I was 100% sure, it will work. I did it and it worked, very happy now. thank for asking this question.
