### ISSUE TITLE
Redirect.Urls Validation Error maybe cause of length?

### ISSUE THREAD

**Issue by aldos84** [paypal/PayPal-PHP-SDK#1118]
I want to create a redirect URL with encoded parameters to login the user automaticly on return from PayPal

The Url looks like this

`http://localhost:8088/authentication/aGhLVjVORWJuNTNDQi9FaFpvUEFoSVdkZitJU2hmb29yODd1U3JEcGNZTjI2ZHF1ek1aWmNvMERvTzlGaWxPdnJJeTdrM0p5QWJQZ2ZLNFEyVGZZaEd2RkErZCthaitCcEgyRWxmKy9YMFk9|qUKFjEMAyKcKoWpv-wenfQ==`

But if I create a Payment with this redirect Url I get an exception

> {"name":"VALIDATION_ERROR","details":[{"field":"redirect_urls.return_url","issue":"{Url}"},{"field":"redirect_urls.cancel_url","issue":"{Url}"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/docs/api/payments
/#errors","debug_id":"b4f34764b60bf"}

If I define a Url like `http://localhost:8088/client/order/paypal/callback/12345` it still works

* SDK/Library version: 1.13.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: b4f34764b60bf
* Language, language version, and OS: Php-fpm 7.0 on Ubuntu 16.04

**Comment by trainerbill** [comment]
You are probably hitting a length issue or you need to URL encode it.  Why not just use the Javascript SDK so it stays on your site?  No need for a redirect.

https://github.com/paypal/paypal-checkout

**Comment by grobmeier** [comment]
Why is this closed? I need redirect urls in my app too, for various reasons. 
The issue is not documented at all, the error message is not telling anything. There is no docs about any length limit, nor is there any notice of Redirect.Urls being deprecated. 

The same issue happens with the Java-SDK too, that's how I came here.
