### ISSUE TITLE
Exception: Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment. 

### ISSUE THREAD

**Issue by killrawr** [paypal/PayPal-PHP-SDK#112]
This is occuring on the **rest-api-sdk-php-master/sample/payments/CreatePaymentUsingSavedCard** (but it seems to occur every 3 or so, HTTP requests)

```
string '{"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"992bce711a5e0"}' (length=212)
```

The same issue, is occurring with my live code; which I have producing the same data as the **sample** (only difference is the CreditCard Token, and ApiContext; different ClientID and ClientSecret).

```
Exception: Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment. [debug_id 9d2922a5f4c09] An internal service error has occurred
```

Log File

```
PayPal\Core\PPHttpConnection: Connecting to https://api.sandbox.paypal.com/v1/oauth2/token
PayPal\Core\PPHttpConnection: Payload grant_type=client_credentials
PayPal\Core\PPHttpConnection: Adding header User-Agent: PayPalSDK/rest-sdk-php 0.6.0 (lang=PHP;v=5.4.7;bit=32;os=Windows_NT_6.1;machine=i586;openssl=0.9.8x;curl=7.24.0)
PayPal\Core\PPHttpConnection: Adding header Authorization: Basic QVZNYV9CQ0RJSl9QaXdUQUY1U1JDX3VHUXYzeFh4eTZ5N1lDLXc1TVVrVWJUX2tjNjZQYi1Ld1dwVGpfOkVBR3NGUkFVejNlVGluZ0R5bXoxQW9tcG9KY0lxLVhmR2t1cElHaThiWG9HRHpvNC03SmdDS0w4MXhFQg==
PayPal\Core\PPHttpConnection: Adding header Accept: */*
PayPal\Core\PPHttpConnection: Invalid or no certificate authority found - Retrying using bundled CA certs file
PayPal\Core\PPHttpConnection: Connecting to https://api.sandbox.paypal.com/v1/payments/payment
PayPal\Core\PPHttpConnection: Payload {"intent":"sale","payer":{"payment_method":"credit_card","funding_instruments":[{"credit_card_token":{"credit_card_id":"CARD-8Y8073040T621494HKQHIONI"}}]},"transactions":[{"amount":{"currency":"USD","total":"17.50","details":{"tax":"2.28","shipping":"0.00","subtotal":"15.22"}},"item_list":{"items":[{"name":"Granola bars","currency":"USD","quantity":5,"price":"1.74"},{"name":"Ground Coffee 40 oz","currency":"USD","quantity":1,"price":"6.52"}]},"description":"Justink - ref #1409091717360 - Client ProDev"}]}
PayPal\Core\PPHttpConnection: Adding header Content-Type: application/json
PayPal\Core\PPHttpConnection: Adding header User-Agent: PayPalSDK/rest-sdk-php 0.6.0 (lang=PHP;v=5.4.7;bit=32;os=Windows_NT_6.1;machine=i586;openssl=0.9.8x;curl=7.24.0)
PayPal\Core\PPHttpConnection: Adding header Authorization: Bearer A015yeAMx.Dy-lDXpBcjV0mD4RB9QwbuK1-qcJlTVtETH.Q
PayPal\Core\PPHttpConnection: Adding header PayPal-Request-Id: 2130706433404141023985457428
PayPal\Core\PPHttpConnection: Invalid or no certificate authority found - Retrying using bundled CA certs file
```

I'm not exactly sure; what I'm to meant to do, to fix this issue, from what I can see my **transactions** object; is calculating up to the correct _total_, and _subtotal_.

Also; using the same **transactions** object, I am able to connect to the PayPal Create Payment; Shopping Gateway, but Authorizing a Payment, with a Stored Credit Card seems to return HTTP 500.

**Comment by Youxiang11** [comment]
Did you solve this question?

**Comment by mikegrahamjones** [comment]
Yes, the issue was I was trying to access CreditCard Payment Gateway using unsupported currency (NZD).

**Comment by ramachandrann** [comment]
While POSTing a Credit Card Payment with postman to sandbox URL https://api.sandbox.paypal.com/v1/payments/payment

<br>request<br>
{
    "intent": "sale",
    "payer": {
        "payment_method": "credit_card",
        "payer_info": {
            "email": "joeshopper@yahoo.com"
        },
        "funding_instruments": [
            {
                "credit_card": {
                    "number": "4111111111111111",
                    "type": "visa",
                    "expire_month": 11,
                    "expire_year": 2018,
                    "cvv2": 874,
                    "first_name": "Joe",
                    "last_name": "Shopper",
                    "billing_address": {
                        "line1": "100 broadway",
                        "line2": "",
                        "city": "Albany",
                        "country_code": "US",
                        "postal_code": "12201",
                        "state": "NY",
                        "phone": "111-22-3333"
                    }
                }
            }
        ]
    },
    "transactions": [
        {
            "amount": {
                "total": "7.47",
                "currency": "USD",
                "details": {
                    "subtotal": "7.37",
                    "tax": "0.04",
                    "shipping": "0.06"
                }
            },
            "description": "This is the payment transaction description.",
            "item_list": {
                "shipping_address": {
                    "recipient_name": "Joe",
                        "line1": "100 broadway",
                        "line2": "",
                        "city": "Albany",
                        "country_code": "US",
                        "postal_code": "12201",
                        "state": "NY",
                        "phone": "111-22-3333"
                }
            }
        }
    ]
}
<br>response:<br>
{
  "name": "INTERNAL_SERVICE_ERROR",
  "information_link": "https://api.sandbox.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR",
  "debug_id": "12806272a054c"
}

How to figure out the root cause?

**Comment by pp-randy** [comment]
@ramachandrann your 500 is most likely due to the credit card, will you generate a new one here using step 4 and try again? https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1413

**Comment by mikegrahamjones** [comment]
@ramachandrann The problem is that your **item_list** consists of **shipping_address** and not **items**

`{
	"intent": "sale",
	"payer": {
		"payment_method": "credit_card",
		"payer_info": {
			"email": "joeshopper@yahoo.com"
		},
		"funding_instruments": [{
			"credit_card": {
				"number": "4111111111111111",
				"type": "visa",
				"expire_month": 11,
				"expire_year": 2018,
				"cvv2": 874,
				"first_name": "Joe",
				"last_name": "Shopper",
				"billing_address": {
					"line1": "100 broadway",
					"line2": "",
					"city": "Albany",
					"country_code": "US",
					"postal_code": "12201",
					"state": "NY",
					"phone": "111-22-3333"
				}
			}
		}]
	},
	"transactions": [{
		"amount": {
			"total": "7.47",
			"currency": "USD",
			"details": {
				"subtotal": "7.37",
				"tax": "0.04",
				"shipping": "0.06"
			}
		},
		"description": "This is the payment transaction description.",
		"item_list": {
			"shipping_address": {
				"recipient_name": "Joe",
				"line1": "100 broadway",
				"line2": "",
				"city": "Albany",
				"country_code": "US",
				"postal_code": "12201",
				"state": "NY",
				"phone": "111-22-3333"
			}
		}
	}]
}`

**Comment by viper-pranish** [comment]
I am also getting the same error time to time. No changes in my code but I get this error for certain time and then the error doesn't occur again. May I know what is the main reason for this error and does this error occur only in sandbox account or live account too?

**Comment by lway** [comment]
I am also getting the same error intermittently when creating billing agreements in a sandbox account.  I did not change my code between tries, so I don't have control over this problem.  If this also happens in a live account, I can't think of any way around it other than retrying.  That would make for a bad user experience as the user might have to wait through multiple retries.  Even if this only occurs in sandbox accounts, it makes it very difficult to develop and test the code that will be used for a live account.  Can someone please answer the question from @viper-pranish "May I know what is the main reason for this error and does this error occur only in sandbox account or live account too?".

**Comment by pp-randy** [comment]
@lway what is your debug-id?  If its the common test credit card issue then that is sandbox only.

**Comment by lway** [comment]
@pp-randy The problem is intermittent, and I'm not experiencing it now.  
Where would I see the debug-id?
What is the common test credit card issue?

**Comment by pp-randy** [comment]
@lway if you get an error then it is in your response JSON string as the debug_id variable, or it is always in your response headers as PayPal-Debug-ID. 

Common test cards such as 4111111111111111, will not currently work in the sandbox, and this is for any common test card number.  If you get a 500 in the sandbox then its best to try with a newly generated credit card number by using step 4 of this FAQ https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1413 which is to rule out any issue with the current card number you might be using.

500 errors might not always have the same cause, since they do tend to be PayPal system errors.  If you do encounter errors on live then the best course of action is to reach out the PayPal Technical Support at https://www.paypal-techsupport.com/app/ask

**Comment by lway** [comment]
@pp-randy Thank you for your response.

I am using the same test credit card number for each test run.  Since I encounter a problem intermittently, the problem shouldn't be related to the credit card number.  However if the problem comes back, I will try using a newly generated credit card number as you suggested.

It's good to know that this probably won't happen with a live account.

**Comment by lway** [comment]
@pp-randy I guess you didn't really say that there wouldn't be problem on a live account, just that the recourse is PayPal tech support.  Oh well ...

**Comment by pp-randy** [comment]
@lway a 500 error can have different causes, on live if your integration works in the sandbox it would most likely be a temporary system issue on the PayPal side, but worth reaching out to the PayPal Technical Support team if the errors are consistent.

**Comment by lway** [comment]
@pp-randy OK, thank you again!

**Comment by lway** [comment]
@pp-randy I got the error again.  The debug id is a7ad38c87c0f7.  Is there a way for me to look that up and determine what it means?

**Comment by pp-randy** [comment]
@lway the error appears related to the credit card being used in the sandbox.  Was it generated from the FAQ provided?

**Comment by qngODC** [comment]
400{"name":"INSTRUMENT_DECLINED","details":[],"message":"The instrument presented was either declined by the processor or bank, or it can't be used for this payment.","information_link":"https://developer.paypal.com/docs/api/#INSTRUMENT_DECLINED","debug_id":"170634cb95bd7"}

**Comment by pp-randy** [comment]
@figo8881941 and @qngODC  are you still getting an error?  Looking at some activity it appears things are working for you now.  If not please update with another debug_id and I will be happy to take a look.  Sorry for the delay in following up with you both.

**Comment by malik-umair** [comment]
I'm also getting 500 internal server error on sandbox(not tested on live) from last 3-4 hours. debug_id:"e31345fcba8c0". Below is the response I get:

`PayPal\Core\PayPalHttpConnection : INFO: POST https://api.sandbox.paypal.com/v1/oauth2/token
PayPal\Core\PayPalHttpConnection : INFO: Response Status : 200
PayPal\Core\PayPalHttpConnection : INFO: POST https://api.sandbox.paypal.com/v1/payments/payment

PayPal\Core\PayPalHttpConnection : INFO: Response Status : 500
PayPal\Core\PayPalHttpConnection : ERROR: Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment. {"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"e31345fcba8c0"}`

**Comment by malik-umair** [comment]
@pp-randy can you please check what has happened with the API and if it'll occur on Live mode too? as I'm testing it on sandbox

**Comment by pp-randy** [comment]
@malik-umair I apologize I can't find your logs for that debug_id, but that API request was for a credit card payment then this might be impacting you https://github.com/paypal/PayPal-PHP-SDK/issues/639.

If not, can you shoot me another debug_id and I will see if I am able to pull up some results?

**Comment by malik-umair** [comment]
@pp-randy Debug ID: 8c0ed6fcbd68d

Looking at ticket #639 should I've to replace:

    $payer->setPaymentMethod('credit_card');

with:

    $payer->setPaymentMethod('payment_card');

**Comment by pp-randy** [comment]
@malik-umair yes, since credit_card object is shown as deprecated.

**Comment by pp-randy** [comment]
@malik-umair however credit_card still works on live and should work in the sandbox, but that has not yet been resolved.

**Comment by malik-umair** [comment]
Got error that should use credit_card. "debug_id":"5b25504a595d2" . Below is the response:

    ERROR: Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payment. {"name":"VALIDATION_ERROR","details":[{"field":"payer","issue":"Credit_card payment method must use credit_card or cardit_card_token funding instrument."},{"field":"payer.payment_method","issue":"Payment method must be credit_card or paypal."}],"message":"Invalid request. See details.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#VALIDATION_ERROR","debug_id":"5b25504a595d2"}

**Comment by pp-randy** [comment]
@malik-umair update me here https://github.com/paypal/PayPal-PHP-SDK/issues/648

**Comment by srinivastamada** [comment]
$curl = curl_init('https://api.sandbox.paypal.com/v1/payments/payment/PAY-XXXXXXXXX');

{"name":"PERMISSION_DENIED","message":"No permission for the requested operation","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"8ab402e2b3366"}

**Comment by xiaoleih41** [comment]
I am locking this conversation as the original issue has been solved.  Please submit a new issue and explain what exact you were trying to accomplish through the API call.
