### ISSUE TITLE
PayPal Express Order Payment shows the payer's own account/address as the 'Ship To' address instead of the address they're sending it to

### ISSUE THREAD

**Issue by DingoDongBlueBalls** [paypal/PayPal-PHP-SDK#1121]
### General information

* SDK/Library version: Latest
* Environment: Production
* `PayPal-Debug-ID` values: none
* Language, language version, and OS: PHP 7.0, Laravel 5.5

### Issue description

Hi,

I've been stuck with this issue for the past 2 days and I can't find any solution to fix it.

Whenever a user decides to purchase an item on my website, they are then redirected to paypal(everything works fine up until this point).

As soon as they get to the payment part(after logging in), the shipping address shows their own account/address instead of my shipping address.

Payments are working fine, even when "Ship to" is set to their own account the payments are still sent to my account, I'd still like to solve this problem though cause it might cause alot of confusion for my clients.

I've attached a screenshot of the paypal page which gives the incorrect info.
![paypalissue](https://user-images.githubusercontent.com/7136117/40857932-fd5f6f66-65dc-11e8-846e-580a6d387ac5.png)

Code:
https://paste.laravel.io/c85e003d-a429-4b3c-b10f-5255ec36daeb#7

Maybe I've simply forgotten to add something to the code? I've already tried adding a Payee which doesnt do anything and simply shows the user as "Ship To" address.
Also tried setting a shipping address with the ShippingAddress module which kinda crashes the application and redirects to the cancelorder page..

**Comment by jhfyang** [comment]
By default the address shown in the Ship To section is the Buyers address, if you want to Override it you need to add shipping_address, as you can read it on Paypal API page https://developer.paypal.com/docs/api/payments/#payment_create
As I am using 2.0 I am not sure which object needs to be called but it is in your `itemList `object

**Comment by prakash-gangadharan** [comment]
Hi @DingoDongBlueBalls, add the desired shipping address through ShippingAddress object to reflect the same in the 'Ship To' section in the payment review page during checkout.

**Sample Code block :**
```php
$payer = new Payer();
$payer->setPaymentMethod("paypal");

// ### Itemized information
// (Optional) Lets you specify item wise
// information
$item1 = new Item();
$item1->setName('Ground Coffee 40 oz')
    ->setCurrency('USD')
    ->setQuantity(1)
    ->setSku("123123") // Similar to `item_number` in Classic API
    ->setPrice(7.5);
$item2 = new Item();
$item2->setName('Granola bars')
    ->setCurrency('USD')
    ->setQuantity(5)
    ->setSku("321321") // Similar to `item_number` in Classic API
    ->setPrice(2);

$shippingAddress = new ShippingAddress();
$shippingAddress->setRecipientName("Brian Robinson")
    ->setLine1("4th Floor")
    ->setLine2("Unit #34")
    ->setCity("San Jose")
    ->setCountryCode("US")
    ->setPostalCode("95131")
    ->setPhone("2025550110")
    ->setState("CA");

$itemList = new ItemList();
$itemList->setItems(array($item1, $item2));
$itemList->setShippingAddress($shippingAddress);
//$itemList->setShippingPhoneNumber("2025550110");

// ### Additional payment details
// Use this optional field to set additional
// payment information such as tax, shipping
// charges etc.
$details = new Details();
$details->setShipping(1.2)
    ->setTax(1.3)
    ->setSubtotal(17.50);

// ### Amount
// Lets you specify a payment amount.
// You can also specify additional details
// such as shipping, tax.
$amount = new Amount();
$amount->setCurrency("USD")
    ->setTotal(20)
    ->setDetails($details);

// ### Transaction
// A transaction defines the contract of a
// payment - what is the payment for and who
// is fulfilling it. 
$transaction = new Transaction();
$transaction->setAmount($amount)
    ->setItemList($itemList)
    ->setDescription("Payment description")
    ->setInvoiceNumber(uniqid());

// ### Redirect urls
// Set the urls that the buyer must be redirected to after 
// payment approval/ cancellation.
$baseUrl = "https://example.com";
$redirectUrls = new RedirectUrls();
$redirectUrls->setReturnUrl("$baseUrl/ExecutePayment.php?success=true")
    ->setCancelUrl("$baseUrl/ExecutePayment.php?success=false");

// ### Payment
// A Payment Resource; create one using
// the above types and intent set to 'sale'
$payment = new Payment();
$payment->setIntent("sale")
    ->setPayer($payer)
    ->setRedirectUrls($redirectUrls)
    ->setTransactions(array($transaction));
  
 // Create payment with valid API context
try {
  $payment->create($apiContext);
  
  echo $payment;
} catch (PayPal\Exception\PayPalConnectionException $ex) {
  echo $ex->getCode();
  echo $ex->getData();
  die($ex);
} catch (Exception $ex) {
  die($ex);
}
```

**Paypal Review Page** :

![image](https://user-images.githubusercontent.com/13796434/65040535-39c19d80-d972-11e9-9ce6-07a1dd6386ad.png)
