### ISSUE TITLE
Fail to add the payment of buyer to the merchant's paypal balance

### ISSUE THREAD

**Issue by pryxen12** [paypal/PayPal-PHP-SDK#1122]
I run test and do transaction b/w merchant and buyer. After payment execution, I checked the balance of my buyer account and it successfully deducted the total price of purchased products. But when I checked the merchant's balance it never add the payment to the balance of the merchants account. I checked the Sandbox API Call History in my merchants account and it successfully executed the payment execution with paypal debug ID of  `c8ce37494ca5f`, I tried to make a transaction again but unfortunately it doesn't add the payment in my merchants paypal balance

**Comment by trainerbill** [comment]
looks like there are some risk related issues on that transaction.  Do you have payment review turned on?  Probably will be quickest to generate a new sandbox account, then generate a new REST app attached to the new sandbox account and try again.
