### ISSUE TITLE
Webhook signature verification not working for PAYMENT.SALE.COMPLETED when executed from a Billing agreement

### ISSUE THREAD

**Issue by jhfyang** [paypal/PayPal-PHP-SDK#1123]
### General information

* SDK/Library version: 2.0-beta
* Environment: Sandbox
* `PayPal-Debug-ID` values: 

```
HttpResponse {#642 ▼
  +statusCode: 200
  +result: {#650 ▼
    +"verification_status": "FAILURE"
  }
  +headers: array:11 [▼
    "" => ""
    "Date" => "Tue, 05 Jun 2018 14"
    "Server" => "Apache"
    "paypal-debug-id" => "d79e7f9cb3a33"
    "HTTP_X_PP_AZ_LOCATOR" => "sandbox.slc"
    "Paypal-Debug-Id" => "d79e7f9cb3a33"
    "Set-Cookie" => "X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00"
    "Vary" => "Authorization"
    "Content-Length" => "33"
    "Connection" => "close"
    "Content-Type" => "application/json"
  ]
}
```

* Language, language version, and OS: PHP 7.1.9 Windows

### Issue description

I have been having issues with webhook signature verification for PAYMENT.SALE.COMPLETED coming from recurring payments of a Billing Agreement. 

I get ` "verification_status": "FAILURE"`

However this doesn't happen for two other webhooks one that is assigned on BILLING.SUBSCRIPTION.CREATED and an other one on all Events.

Here is the body for the  webhookVerificationRequest that I set: 

```
array:7 [▼
  "auth_algo" => "SHA256withRSA"
  "cert_url" => "https://api.sandbox.paypal.com/v1/notifications/certs/CERT-360caa42-fca2a594-aecacc47"
  "transmission_id" => "f17354b0-68ca-11e8-a6f7-0de0de4a06f7"
  "transmission_sig" => "uzvYY47zNav0ioULX6Ohyw9yxvfrZfN+sfvJrvPEaUUb1m5IRNUAoXykqpl30xDvgCu7Kcb3VXYHwx7hZ56dXFhefkZMTkQA0UMNPV7ovK8QFrupWMertC7WYyjP+Et7Qr5PwmZHhGPUntW6PWlQBFC7SWhq5eK8gmGSzkHRE60s79X3Gq8mymSYTAW278Navsfo6ege/E6n1QTQn4rSiv0OBr2RlYZaVSnI7CaxcFnt1uOfChYM6AxEFIOH/ogbu2DwZPk5ZBfrhRISK856brzspWkrcfuEH+AeM2fkp7gIj0fbUcZDxOJBZJdUoH3vCva9oJqhlHYFKyKYmbno2Q== ◀"
  "transmission_time" => "2018-06-05T14:15:47Z"
  "webhook_id" => "9SB72311F7255161U"
  "webhook_event" => array:8 [▼
    "id" => "WH-30N25719HJ584081X-10H76223CA920461U"
    "event_version" => "1.0"
    "create_time" => "2018-06-05T14:15:47.717Z"
    "resource_type" => "sale"
    "event_type" => "PAYMENT.SALE.COMPLETED"
    "summary" => "Payment completed for EUR 34.0 EUR"
    "resource" => array:11 [▼
      "id" => "72C0408900073910L"
      "state" => "completed"
      "amount" => array:3 [▼
        "total" => "34.00"
        "currency" => "EUR"
        "details" => []
      ]
      "payment_mode" => "INSTANT_TRANSFER"
      "protection_eligibility" => "ELIGIBLE"
      "protection_eligibility_type" => "ITEM_NOT_RECEIVED_ELIGIBLE,UNAUTHORIZED_PAYMENT_ELIGIBLE"
      "transaction_fee" => array:2 [▶]
      "billing_agreement_id" => "I-1DJHF1G2BY41"
      "create_time" => "2018-06-05T14:15:39Z"
      "update_time" => "2018-06-05T14:15:39Z"
      "links" => array:2 [▶]
    ]
    "links" => array:2 [▶]
  ]
]
```

as you can see these are my webhook Ids 

![image](https://user-images.githubusercontent.com/25792174/40982310-3ba9cbe2-68dd-11e8-93e0-2ce39329d3f1.png)

I have tried to delete and create a new Webhook for Payment sale completed however I still receive status `failure`

I feel that this might be an error on paypal side? where it might not handle webhook signature verification for payment sale completed for a BILLING AGREEMENT

Therefore I have tested it with an Express checkout and the webhook signature verification works.

Here are more paypal-debug-ids where it has failed: 
- 7be17d191245c
- 3290dd26e7f76
- f968d274ccc68

**Comment by trainerbill** [comment]
Duplicate

**Comment by jhfyang** [comment]
Could you please refer to the duplicate one, if you are referrring to the #1107, it has nothing to do with my issue.

**Comment by trainerbill** [comment]
Sorry it was made by you so I didn't link it

https://github.com/paypal/PayPal-REST-API-issues/issues/236
