### ISSUE TITLE
Environment production = live

### ISSUE THREAD

**Issue by miamibc** [paypal/PayPal-PHP-SDK#1124]
In javascript, `live` environment has name `production`. Just a suggestion, to add here extra line `case "production":` to make php sdk more compatible to javascript sdk https://github.com/paypal/PayPal-PHP-SDK/blob/ff2a7f9c2ddc47a22cb7bb8a5b0bb97bd16bdd6f/lib/PayPal/Handler/RestHandler.php#L112

**Comment by trainerbill** [comment]
Thanks for the suggestion.  the JS SDK is actually maintained by another team but this is a good recommendation.
