### ISSUE TITLE
Recurring Billing - Sandbox User, no Aproval for Billing Agreement

### ISSUE THREAD

**Issue by olissongs** [paypal/PayPal-PHP-SDK#1125]
### General information

* SDK/Library version: 1.13.0
* Environment: PayPal REST API, LAMP, Ubuntu 16.04, PHP 7
* `PayPal-Debug-ID` no debug info, calls are ok
* Language, language version, and OS: Ubuntu 16.04, PHP 7

### Issue description

i want to create a recurring billing, where the first rate is paid immediately, and the other in indivisual rate every moth.

my docs i used
https://developer.paypal.com/docs/integration/direct/billing-plans-and-agreements/
https://developer.paypal.com/docs/api/payments.billing-agreements
and the sdk sample code and source code

for the users order in my app
1. create a billing plan - success
2. activate billing plan - success
3. create agreement - success
4. get sandbox user approval - not possible

![grafik](https://user-images.githubusercontent.com/1310153/41159386-aa91f2b8-6b2c-11e8-91a1-fad6b74cb700.png)

so i don't understand why i get the error message, the start_date is 24h+, got no errors themes to be a paypal inside thing.

`$merchantPreferences->setReturnUrl("$successUrl?success=true")
            ->setCancelUrl("$cancelUrl?success=false")
            ->setAutoBillAmount("yes")
            ->setInitialFailAmountAction("CONTINUE")
            ->setMaxFailAttempts("0")
            ->setSetupFee(new \PayPal\Api\Currency(array(
                'value' => $order->payment_first_rate_height,
                'currency' => 'EUR'
            )))
            ;`

i added the paypal log for these steps.

[paypallog_bilplagr.txt](https://github.com/paypal/PayPal-PHP-SDK/files/2084461/paypallog_bilplagr.txt)

**Comment by olissongs** [comment]
'Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/billing-plans/`'

or asking in an other direction "**how do i get more dubug Information?**"

in my funtion calling PayPal\Api\Plan::create(PayPal\Rest\ApiContext) 

`        $createdPlan = $plan->create($apiContext)`

 in /paypal/rest-api-sdk-php/lib/PayPal/Api/Plan.php at line 362 – PayPal\Common\PayPalResourceModel::executeCall('/v1/payments/billing-plans/', 'POST', '{"name":"Test ","des...', null, ...) 

    $json = self::executeCall(
            "/v1/payments/billing-plans/",
            "POST",
            $payLoad,
            null,
            $apiContext,
**$restCall**

    );
        $this->fromJson($json);
     ...

error here

                         
        if ($httpStatus < 200 || $httpStatus >= 300) {
            $ex = new PayPalConnectionException(

**Comment by olissongs** [comment]
seems to be an unclear problem similiar to this, not solved

[https://github.com/paypal/PayPal-PHP-SDK/issues/699](https://github.com/paypal/PayPal-PHP-SDK/issues/699)

and this, but this i have checked and my code is ok
[https://github.com/paypal/PayPal-PHP-SDK/issues/1044](https://github.com/paypal/PayPal-PHP-SDK/issues/1044)

The other argument ist that it is a Count Thing, but Germany is listed, but i don't know which postal-Code is requiered (Payer, or Payee?)
[https://developer.paypal.com/docs/integration/direct/rest/country-codes/](https://developer.paypal.com/docs/integration/direct/rest/country-codes/)

Is PHP SDK REST?

**Comment by olissongs** [comment]
after opening an ticket its working in sandbox

**Comment by olissongs** [comment]
Ok this is not working for German PayPal Users which have an BankAccount and no CreditCard.

**Comment by prakash-gangadharan** [comment]
Hi @olissongs is this still an issue? How about now? if yes is there any recent debug_ids you have?

**Comment by prakash-gangadharan** [comment]
Hi @olissongs can you check again advice whether this issue is still happening or not.

**Comment by prakash-gangadharan** [comment]
It looks like this is no longer applicable, hence closing this issue out. Please feel to reopen if your still see this instances around.

Thanks!

**Comment by jcardussi** [comment]
I wish people would post their solution. I am having the same issue.

**Comment by prakash-gangadharan** [comment]
Hi @jcardussi , is this still an issue? can you give me more context on this?

**Comment by jcardussi** [comment]
I posted it as a new issue since I thought my details would get lost this far down a post. The link to all my details is here:

https://github.com/paypal/PayPal-PHP-SDK/issues/1299
