### ISSUE TITLE
500 Internal Error on payment in Sandbox

### ISSUE THREAD

**Issue by MilaserdovNikita** [paypal/PayPal-PHP-SDK#1126]
{"error":{"response":{"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"6cba98c8cb7ad","httpStatusCode":500},"httpStatusCode":500

General information
SDK/Library version: Dont know how to check
Environment: Sandbox
PayPal-Debug-ID values: 6cba98c8cb7ad
Language, language version, and OS: Java 1.8.0_172 on Windows 7 

Issue description:
Sometimes I'm having  error when trying pay product with my Sandbox Paypal account. Developers in our team says that PayPal servers doesn't work, does it right?

**Comment by dudj** [comment]
When I was testing sandbox mode, I also had a response status code of 500.The information on the Internet says that we need to log in first, so that we can successfully call it. I tried it.

**Comment by prakash-gangadharan** [comment]
Hi @MilaserdovNikita / @dudj  this issue still occurring? Please advice.

**Comment by prakash-gangadharan** [comment]
It looks like this is no longer applicable, hence closing this issue out. Please feel to reopen if your still see this instances around.

Thanks!
