### ISSUE TITLE
Getting error on Authorized transaction "Authorization in captured state cannot be voided. "

### ISSUE THREAD

**Issue by dhara15101991** [paypal/PayPal-PHP-SDK#1130]
Hello All,

I have authorized transaction with following code:

```
$payment = new Payment();
        $payment->setIntent("authorize")
                ->setPayer($payer)
                ->setRedirectUrls($redirectUrls)
                ->setTransactions(array($transaction));
```
Now i want void the transaction when i am using following code. 
```
$authTraId = <authorization id>
$authorization = Authorization::get($authTraId, $apiContext);
// Void the authorization
$voidedAuth = $authorization->void($apiContext);
```

But it gives me always "Authorization in captured state cannot be voided.". I can't understand what is wrong with this. 

Any help please.

**Comment by felixgomez** [comment]
The workflow is authorize -> capturing. If you execute the capture you can't void the authorization.

**Comment by prakash-gangadharan** [comment]
**Error Response** :
```json
{
    "name": "AUTHORIZATION_CANNOT_BE_VOIDED",
    "message": "Authorization is in captured state and hence cannot be voided.",
    "information_link": "https://developer.paypal.com/docs/api/payments/#errors",
    "debug_id": "569f078d4835a"
}
```

Hi @dhara15101991, Authorization which is in captured or expired state, cannot be voided.
Doc Link : https://developer.paypal.com/docs/api/payments/v1/#error-AUTHORIZATION_CANNOT_BE_VOIDED
