### ISSUE TITLE
What if user is not redirected?

### ISSUE THREAD

**Issue by devingDev** [paypal/PayPal-PHP-SDK#1131]
* SDK/Library version: 1.13.0
* Environment: both, i guess, tested only sandbox though

### Issue description
This might not be an issue from your eyes, I am not sure myself if it is , but I have this question, what happens if I say have a return url for success and the client pays and the payment is done, now imagine he doesnt get redirected for some weird reason.
Now lets assume I process the payment on the return url and then accordingly give the client some sort of key which I also send to his mail. The key is just a redeem code on my app.
So how would I handle that case where the redirect fails? Or say my server has an error so the site does not load for some time. I can't expect the user endlessly pressing F5 until I fix it.
 Is there anything I am missing maybe?

**Comment by devingDev** [comment]
Do I have to use the webhook thing for that?
If so which one and is there a guide / tutorial on that?
thanks!

**Comment by prakash-gangadharan** [comment]
Hi @devingDev, this is more like the question which is regarding the integration part. Please refer the below link for merchant technical support.
https://www.paypal.com/in/smarthelp/article/how-do-i-get-merchant-technical-support,-such-as-for-paypal-product-integrations,-apis-or-sandbox-testing-faq3723

Please visit [Merchant Technical Support](https://www.paypal-techsupport.com/app/) and submit your question for merchant/developer technical support, such as for PayPal product integrations/APIs

Thanks!
