### ISSUE TITLE
How to use data from website to paypal shipping with laravel

### ISSUE THREAD

**Issue by jonjie0317** [paypal/PayPal-PHP-SDK#1133]
I'm trying to implement the `API` of `paypal payment` with `laravel 5.1`. But when I login in `paypal (sandbox)`, it uses the address I used in my account, and also it uses the name from paypal account not the data from my website. That's my problem.

I want to use the data from my website because it doesn't make sense if I enter the shipping address (for example) from my website and not using it. Please see my code below for reference (Or comment down below for some details from me).

    
    
    class PaypalPaymentController extends BaseController
    {
    
        private $_api_context;
    
        public function __construct(){
            $paypal_conf = \Config::get('paypal');
    
            $this->_api_context = new ApiContext(new OAuthTokenCredential(
                $paypal_conf['client_id'],
                $paypal_conf['secret']
            ));
    
            $this->_api_context->setConfig($paypal_conf['settings']);
        }
    
        public function payWithPaypal(Request $request){
            $payer = new Payer;
            $payer->setPaymentMethod('paypal');
    
            $price = 0;
    
            switch($request->get('amount')) {
                case '10 books':
                    $price = 6200;
                    break;
                case '20 books':
                    $price = 12200;
                    break;
                case '50 books':
                    $price = 25200;
                    break;
                default:
                    return redirect()
                            ->route('bookstore.shipping')
                            ->with('danger', 'Please select the right amount of book/s.');
                    break;
            }
    
            $item1 = new Item();
            $item1->setName($request->get('amount'))
                    ->setCurrency('PHP')
                    ->setQuantity(1)
                    ->setPrice($price);
    
            $item_list = new ItemList();
            $item_list->setItems([$item1]);
    
            $amount = new Amount();
            $amount->setCurrency('PHP')
                    ->setTotal($price);
    
            $transaction = new Transaction();
            $transaction->setAmount($amount)
                        ->setItemList($item_list)
                        ->setDescription('Books transaction');
    
            $redirect_urls = new RedirectUrls();
            $redirect_urls->setReturnUrl(route('bookstore.payment-status'))
                            ->setCancelUrl(route('bookstore.payment-status'));
    
            $payment = new Payment();
            $payment->setIntent('Sale')
                    ->setPayer($payer)
                    ->setRedirectUrls($redirect_urls)
                    ->setTransactions([$transaction]);
    
            try{
                $payment->create($this->_api_context);
            } catch(\Palpal\Exception\PPConnectionException $e){
                if(\Config::get('app.debug')){
                    return redirect()
                            ->route('bookstore.shipping')
                            ->with('danger', 'Connection Timeout.');
                }
    
                return redirect()
                        ->route('bookstore.shipping')
                        ->with('danger', 'Some error occured, sorry for the inconvenience.');
            }
    
            foreach($payment->getLinks() as $link){
                if($link->getRel() == 'approval_url'){
                    $redirect_url = $link->getHref();
                    break;
                }
            }
    
            Session::put('paypal_payment_id', $payment->getId());
    
            if(isset($redirect_url)){
                return Redirect::away($redirect_url);
            }
    
            return redirect()
                    ->route('bookstore.shipping')
                    ->with('danger', 'Unknown error occured.');
        }
    
        public function getPaymentStatus(){
            $payment_id = Session::get('paypal_payment_id');
            Session::forget('paypal_payment_id');
    
            if(empty(Input::get('PayerID')) || empty(Input::get('token'))){
                return redirect()
                        ->route('bookstore.shipping')
                        ->with('danger', 'Payment failed.');
            }
    
            $payment = Payment::get($payment_id, $this->_api_context);
            $execution = new PaymentExecution();
            $execution->setPayerId(Input::get('PayerID'));
    
            $result = $payment->execute($execution, $this->_api_context);
    
            if($result->getState() == 'approved'){
                // Send Email
                $email_data = [
                    'number_of_books' => $payment->transactions[0]->item_list->items[0]->name,
                    'shipping' => [
                        'street' => $payment->payer->payer_info->shipping_address->line1,
                        'city' => $payment->payer->payer_info->shipping_address->city,
                        'state' => $payment->payer->payer_info->shipping_address->state,
                        'country' => $payment->payer->payer_info->shipping_address->country_code,
                    ]
                ];
    
                // Send email function here ...
    
                return redirect()
                        ->route('bookstore.shipping')
                        ->with('success', 'Transaction payment success!');
            }
    
            return redirect()
                    ->route('bookstore.shipping')
                    ->with('danger', 'Payment failed.');
        }
    
    }

**Stackoverflow:**

https://stackoverflow.com/questions/51130271/paypal-api-with-laravel-getting-the-data

**Comment by tomaxyn** [comment]
Greetings, 
why not using some session var?

Session::put('calculation', $this->variable); and $value = Session::get('calculation');
Session::forget('calculation');

to carry variables in the controller, that works for me.

<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use PayPal\Api\Amount;
use PayPal\Api\Details;
use PayPal\Api\Item;

/** All Paypal Details class **/
use PayPal\Api\ItemList;
use PayPal\Api\Payer;
use PayPal\Api\Payment;
use PayPal\Api\PaymentExecution;
use PayPal\Api\RedirectUrls;
use PayPal\Api\Transaction;
use PayPal\Auth\OAuthTokenCredential;
use PayPal\Rest\ApiContext;
use Redirect;
use Session;
use URL;
use Carbon\Carbon;

/** Models de la app**/
use App\ProductType;
use App\Registra;
use App\Revision;
use App\Categor_class_reg;

/** Mail facade  **/
use Illuminate\Support\Facades\Mail;


class PagoController extends Controller
{
	private $regis;	
	private $_api_context;

    public function __construct()
    {
    	/** Paypal api context*/
    	$paypal_conf = \Config::get('paypal');
    	$this->_api_context = new ApiContext(new OAuthTokenCredential(
    		$paypal_conf['client_id'],
    		$paypal_conf['secret'])

    	);
    	$this ->_api_context->setConfig($paypal_conf['settings']);
    	//$this->regis = array();
    }

    public function setRegis(Request $request)
    {
    	   $this->regis['event_id'] = 42;
            $this->regis['name'] = $request->name;
            $this->regis['lastname'] = $request->lastname;
            $this->regis['email'] = $request->email;
            $this->regis['address1'] = $request->address1;
            $this->regis['address2'] = $request->address2;
            $this->regis['city'] = $request->city;
            $this->regis['estado'] = $request->estado;
            $this->regis['country'] = $request->country;
            $this->regis['zip'] = $request->cp;
            $this->regis['phone'] = $request->phone;
            $this->regis['stacode'] = $request->stacod;
            $stac = $request->stacod;
            $this->regis['langu'] = $request->lengua;
            $matric = uniqid('LA_');
            $this->regis['matricula'] = $matric;
            //$registro->save(); 
            //$nuevoreg = Registra::where('matricula', $matric)->first();
            if(strcmp($stac, 'RA') == 0 || strcmp($stac, 'RC') == 0){
            	$fechasalva = Carbon::createFromFormat('Y-m-d', $request->fecharev);
	            $this->regis['fecha'] = $fechasalva;
	            $this->regis['lugar'] = $request->lugarev;
	            $this->regis['ciudad'] = $request->cityrev;
	            $this->regis['estado1'] = $request->estadorev;
	            $this->regis['pais'] = $request->countryrev;
	            //$this->regis['reg_id'] = $nuevoreg->id;
	            //$regis->save();
            }
          \Session::put('list', $this->regis); 
    }

    public function getRegis()
	{
		return $this->regis;
	}

    public function showmes()
    {
        return view('paypal.statuspago');
    }
   
    public function payWithpaypal(Request $request)
	{

			$payer = new Payer();
			$payer->setPaymentMethod('paypal');

		    $stac = $request->stacod;
            $cal = ProductType::where('statuscode', $stac)->first();
           	$this->setRegis($request);            
            //return dd($this->getRegis());
            
			$item_1 = new Item();

			$item_1->setName('Clase BÁSICO I') 
				->setCurrency('USD')
				->setQuantity(1)
				->setPrice($cal->price); 

			$item_list = new ItemList();
			$item_list->setItems(array($item_1));

			$amount = new Amount();
			$amount->setCurrency('USD')
				->setTotal($cal->price);

			$transaction = new Transaction();
			$transaction->setAmount($amount)
				->setItemList($item_list)
				->setDescription('AUTO I-DENTIDAD a través de HO’OPONOPONO® BÁSICO I Los Ángeles, California 6 y 7 de Octubre de 2018');
			
			$redirect_urls = new RedirectUrls();
			$redirect_urls->setReturnUrl(URL::route('statuses')) 
			->setCancelUrl(URL::route('statuses'));

			$payment = new Payment();
			$payment->setIntent('Sale')
				->setPayer($payer)
				->setRedirectUrls($redirect_urls)
				->setTransactions(array($transaction));
		
			try {

				$payment->create($this->_api_context);

			} catch (\PayPal\Exception\PPConnectionException $ex) {
			
			if (\Config::get('app.debug')) {
				Session::put('error', 'El tiempo de conexión expiro');
				return Redirect::route('inscripcion.date_complete');
			} else {
			\		Session::put('error', 'Algunos errores ocurrieron, lamentamos el inconveniente');
			return Redirect::route('inscripcion.date_complete');
			}
			}
			foreach ($payment->getLinks() as $link) {
				if ($link->getRel() == 'approval_url') {
				$redirect_url = $link->getHref();
				break;
				}
			}

			
			Session::put('paypal_payment_id', $payment->getId());
			if (isset($redirect_url)) {
			
			return Redirect::away($redirect_url);
			}
			Session::put('error', 'Se produjo un error desconocido');
			return Redirect::route('inscripcion.date_complete');
			
	}


	public function getPaymentStatus()
	{
		 /** Get the payment ID before session clear **/
        $payment_id = Session::get('paypal_payment_id');

        /** clear the session payment ID **/
        Session::forget('paypal_payment_id');
        
        if (empty(Input::get('PayerID')) || empty(Input::get('token'))) {
        	    \Session::put('error', 'El Pago no se realizó');
            	return Redirect::to('/payini');
        		}
        
        $payment = Payment::get($payment_id, $this->_api_context);
        $execution = new PaymentExecution();
        $execution->setPayerId(Input::get('PayerID'));
        /**Execute the payment **/
        $result = $payment->execute($execution, $this->_api_context);
        if ($result->getState() == 'approved') {        	
        	
        	$this->saveRegist();

            \Session::put('success', 'Se realizó el pago exitósamente.');            
            return Redirect::to('/payini');
        }
        \Session::put('error', 'El pago no se realizó.');
        return Redirect::to('/payini');
	}	

	public function saveRegist()
	{	
		//return dd($this->getRegis());	
		$value = Session::get('list');
		$registro = new Registra;
        $revis = new Revision;
        $compl = new Categor_class_reg;
            $registro->event_id = $value['event_id'];
            $registro->name = $value['name'];
            $registro->lastname = $value['lastname'];
            $registro->email = $value['email'];
            $registro->address1 = $value['address1'];
            $registro->address2 = $value['address2'];
            $registro->city = $value['city'];
            $registro->state = $value['estado'];
            $registro->country = $value['country'];
            $registro->zip = $value['zip'];
            $registro->phone = $value['phone'];
            $registro->stacode = $value['stacode'];
            $stac = $value['stacode'];
            $registro->langu = $value['langu'];
            $matric = uniqid('LA_');
            $registro->matricula = $matric;
            $registro->save(); 
            $nuevoreg = Registra::where('matricula', $matric)->first();
            if(strcmp($stac, 'RA') == 0 || strcmp($stac, 'RC') == 0){
            	//$fechasalva = Carbon::createFromFormat('Y-m-d', $this->regis['']);
	            $revis->fecha = $value['fecha'];
	            $revis->lugar = $value['lugar'];
	            $revis->ciudad = $value['ciudad'];
	            $revis->estado = $value['estado1'];
	            $revis->pais = $value['pais'];
	            $revis->reg_id = $nuevoreg->id;
	            $revis->save();
            }
            $compl->category_id = 1;
            $compl->reg_id = $nuevoreg->id;
            $compl->event_id = $nuevoreg->event_id;
            $cal = ProductType::where('statuscode', $stac)->first();
            $compl->productype_id = $cal->id;		
            $compl->save();
            Session::forget('list');
	}	
}

**Comment by prakash-gangadharan** [comment]
Hi @jonjie0317, 
Try using the $itemList->setShippingAddress($shippingAddress), set this shipping object with the shipping data obtained from your website,  to get the same reflected into the buyer's review page during approval flow.

**Sample Code**:

```php
$payer = new Payer();
$payer->setPaymentMethod("paypal");

// ### Itemized information
// (Optional) Lets you specify item wise
// information
$item1 = new Item();
$item1->setName('Ground Coffee 40 oz')
    ->setCurrency('USD')
    ->setQuantity(1)
    ->setSku("123123") // Similar to `item_number` in Classic API
    ->setPrice(7.5);
$item2 = new Item();
$item2->setName('Granola bars')
    ->setCurrency('USD')
    ->setQuantity(5)
    ->setSku("321321") // Similar to `item_number` in Classic API
    ->setPrice(2);

$shippingAddress = new ShippingAddress();
$shippingAddress->setRecipientName("Brian Robinson")
    ->setLine1("4th Floor")
    ->setLine2("Unit #34")
    ->setCity("San Jose")
    ->setCountryCode("US")
    ->setPostalCode("95131")
    ->setPhone("2025550110")
    ->setState("CA");

$itemList = new ItemList();
$itemList->setItems(array($item1, $item2));
$itemList->setShippingAddress($shippingAddress);
//$itemList->setShippingPhoneNumber("2025550110");

// ### Additional payment details
// Use this optional field to set additional
// payment information such as tax, shipping
// charges etc.
$details = new Details();
$details->setShipping(1.2)
    ->setTax(1.3)
    ->setSubtotal(17.50);

// ### Amount
// Lets you specify a payment amount.
// You can also specify additional details
// such as shipping, tax.
$amount = new Amount();
$amount->setCurrency("USD")
    ->setTotal(20)
    ->setDetails($details);

// ### Transaction
// A transaction defines the contract of a
// payment - what is the payment for and who
// is fulfilling it. 
$transaction = new Transaction();
$transaction->setAmount($amount)
    ->setItemList($itemList)
    ->setDescription("Payment description")
    ->setInvoiceNumber(uniqid());

// ### Redirect urls
// Set the urls that the buyer must be redirected to after 
// payment approval/ cancellation.
$baseUrl = "https://example.com";
$redirectUrls = new RedirectUrls();
$redirectUrls->setReturnUrl("$baseUrl/ExecutePayment.php?success=true")
    ->setCancelUrl("$baseUrl/ExecutePayment.php?success=false");

// ### Payment
// A Payment Resource; create one using
// the above types and intent set to 'sale'
$payment = new Payment();
$payment->setIntent("sale")
    ->setPayer($payer)
    ->setRedirectUrls($redirectUrls)
    ->setTransactions(array($transaction));
  
 // Create payment with valid API context
try {
  $payment->create($apiContext);
  
  echo $payment;
} catch (PayPal\Exception\PayPalConnectionException $ex) {
  echo $ex->getCode();
  echo $ex->getData();
  die($ex);
} catch (Exception $ex) {
  die($ex);
}
  
```

**Review Page**:
![image](https://user-images.githubusercontent.com/13796434/65424442-31ada600-de29-11e9-895f-b56ab86e72bc.png)
