### ISSUE TITLE
Error 500 

### ISSUE THREAD

**Issue by BluewintersL** [paypal/PayPal-PHP-SDK#1135]
Getting an error while attempting to create a billing plan: "Got Http response code 500 when accessing https://api.paypal.com/v1/payments/billing-plans/.'"
Happening on both sandbox and live.

Debug ID: 1e68b5b685bae

Code (PHP SDK): 
$plan = new Plan();
        $plan->setName('<SubscriptionName>')
             ->setDescription('<SubscriptionDescription>')
             ->setType('infinite');
        $paymentDefinition = new PaymentDefinition();
        $paymentDefinition->setName('Regular Payments')
                          ->setType('REGULAR')
                          ->setFrequency('Month')
                          ->setFrequencyInterval("1")
                          ->setCycles("0")
                          ->setAmount(new Currency(array('value' => 14.99, 'currency' => 'USD')));

        $paymentDefinition->setChargeModels(array(null));

        $merchantPreferences = new MerchantPreferences();
        $baseUrl = "<url>";

        $merchantPreferences->setReturnUrl("$baseUrl/ExecuteAgreement.php?success=true")
                            ->setCancelUrl("$baseUrl/ExecuteAgreement.php?success=false")
                            ->setAutoBillAmount("yes")
                            ->setInitialFailAmountAction("CONTINUE")
                            ->setMaxFailAttempts("2")
                            ->setSetupFee(new Currency(array('value' => 0, 'currency' => 'USD')));

        $plan->setPaymentDefinitions(array($paymentDefinition));
        $plan->setMerchantPreferences($merchantPreferences);

        $request = clone $plan;
        $output;

        try {
            $output = $plan->create($apiContext);
        } catch (Exception $ex) {
            echo 'Error: '.$ex.'.';
            die;
        }

**Comment by BluewintersL** [comment]
Update,

Just before anyone asks yes we are within the latest version of TLS 1.2 as well as HTTPS 1.1

**Comment by dudj** [comment]
This problem has not been properly answered. It responds to 500 at create. Does this need to be configured in paypal?

**Comment by BluewintersL** [comment]
@dudj  what do you mean? as in you're also having this issue or? sorry im a bit confused.

**Comment by prakash-gangadharan** [comment]
Hi @BluewintersL and @dudj , is this still an issue? How about now? if yes is there any recent debug_ids you have?

**Comment by prakash-gangadharan** [comment]
Hi @BluewintersL / @dudj can you help here with your inputs?

**Comment by prakash-gangadharan** [comment]
It looks like this is no longer applicable, hence closing this issue out. Please feel to reopen if your still see this instances around.

Thanks!
