### ISSUE TITLE
How can I update data to be used with Laravel

### ISSUE THREAD

**Issue by jonjie0317** [paypal/PayPal-PHP-SDK#1136]
I'm trying to implement the `API` of `paypal payment` with `laravel 5.1`. But when I login in `paypal (sandbox)`, it uses the address I used in my account, and also it uses the name from paypal account not the data from my website. That's my problem.

I want to use the data from my website because it doesn't make sense if I enter the shipping address (for example) from my website and not using it. Please see my code below for reference (Or comment down below for some details from me).

    
    
    class PaypalPaymentController extends BaseController
    {
    
        private $_api_context;
    
        public function __construct(){
            $paypal_conf = \Config::get('paypal');
    
            $this->_api_context = new ApiContext(new OAuthTokenCredential(
                $paypal_conf['client_id'],
                $paypal_conf['secret']
            ));
    
            $this->_api_context->setConfig($paypal_conf['settings']);
        }
    
        public function payWithPaypal(Request $request){
            $payer = new Payer;
            $payer->setPaymentMethod('paypal');
    
            $price = 0;
    
            switch($request->get('amount')) {
                case '10 books':
                    $price = 6200;
                    break;
                case '20 books':
                    $price = 12200;
                    break;
                case '50 books':
                    $price = 25200;
                    break;
                default:
                    return redirect()
                            ->route('bookstore.shipping')
                            ->with('danger', 'Please select the right amount of book/s.');
                    break;
            }
    
            $item1 = new Item();
            $item1->setName($request->get('amount'))
                    ->setCurrency('PHP')
                    ->setQuantity(1)
                    ->setPrice($price);
    
            $item_list = new ItemList();
            $item_list->setItems([$item1]);
    
            $amount = new Amount();
            $amount->setCurrency('PHP')
                    ->setTotal($price);
    
            $transaction = new Transaction();
            $transaction->setAmount($amount)
                        ->setItemList($item_list)
                        ->setDescription('Books transaction');
    
            $redirect_urls = new RedirectUrls();
            $redirect_urls->setReturnUrl(route('bookstore.payment-status'))
                            ->setCancelUrl(route('bookstore.payment-status'));
    
            $payment = new Payment();
            $payment->setIntent('Sale')
                    ->setPayer($payer)
                    ->setRedirectUrls($redirect_urls)
                    ->setTransactions([$transaction]);
    
            try{
                $payment->create($this->_api_context);
            } catch(\Palpal\Exception\PPConnectionException $e){
                if(\Config::get('app.debug')){
                    return redirect()
                            ->route('bookstore.shipping')
                            ->with('danger', 'Connection Timeout.');
                }
    
                return redirect()
                        ->route('bookstore.shipping')
                        ->with('danger', 'Some error occured, sorry for the inconvenience.');
            }
    
            foreach($payment->getLinks() as $link){
                if($link->getRel() == 'approval_url'){
                    $redirect_url = $link->getHref();
                    break;
                }
            }
    
            Session::put('paypal_payment_id', $payment->getId());
    
            if(isset($redirect_url)){
                return Redirect::away($redirect_url);
            }
    
            return redirect()
                    ->route('bookstore.shipping')
                    ->with('danger', 'Unknown error occured.');
        }
    
        public function getPaymentStatus(){
            $payment_id = Session::get('paypal_payment_id');
            Session::forget('paypal_payment_id');
    
            if(empty(Input::get('PayerID')) || empty(Input::get('token'))){
                return redirect()
                        ->route('bookstore.shipping')
                        ->with('danger', 'Payment failed.');
            }
    
            $payment = Payment::get($payment_id, $this->_api_context);
            $execution = new PaymentExecution();
            $execution->setPayerId(Input::get('PayerID'));
    
            $result = $payment->execute($execution, $this->_api_context);
    
            if($result->getState() == 'approved'){
                // Send Email
                $email_data = [
                    'number_of_books' => $payment->transactions[0]->item_list->items[0]->name,
                    'shipping' => [
                        'street' => $payment->payer->payer_info->shipping_address->line1,
                        'city' => $payment->payer->payer_info->shipping_address->city,
                        'state' => $payment->payer->payer_info->shipping_address->state,
                        'country' => $payment->payer->payer_info->shipping_address->country_code,
                    ]
                ];
    
                // Send email function here ...
    
                return redirect()
                        ->route('bookstore.shipping')
                        ->with('success', 'Transaction payment success!');
            }
    
            return redirect()
                    ->route('bookstore.shipping')
                    ->with('danger', 'Payment failed.');
        }
    
    }

**Stackoverflow:**

https://stackoverflow.com/questions/51130271/paypal-api-with-laravel-getting-the-data

**Comment by prakash-gangadharan** [comment]
Hi @jonjie0317,  you should set the shipping address while creating the payment itself, refer to the below example.

Sample code:
```php
<?php

// Autoload SDK package for composer based installations
require __DIR__ . '/../bootstrap.php';
use PayPal\Api\Amount;
use PayPal\Api\Details;
use PayPal\Api\Item;
use PayPal\Api\ItemList;
use PayPal\Api\Payer;
use PayPal\Api\PayerInfo;
use PayPal\Api\Payment;
use PayPal\Api\RedirectUrls;
use PayPal\Api\ShippingAddress;
use PayPal\Api\Transaction;

// ### Payer
// A resource representing a Payer that funds a payment
// For paypal account payments, set payment method
// to 'paypal'.

$payerInfo = new PayerInfo();

$payer = new Payer();
$payer->setPaymentMethod("paypal")
    ->setPayerInfo($payerInfo);

$item1 = new Item();
$item1->setName('Ground Coffee 40 oz')
    ->setCurrency('USD')
    ->setQuantity(1)
    ->setSku("123123")
    ->setPrice(7.5);
$item2 = new Item();
$item2->setName('Granola bars')
    ->setCurrency('USD')
    ->setQuantity(5)
    ->setSku("321321")
    ->setPrice(2);
// adding ShippingAddress
$shippingAddress = new ShippingAddress();
$shippingAddress->setRecipientName("Brian Robinson")
    ->setLine1("4th Floor")
    ->setLine2("Unit #34")
    ->setCity("San Jose")
    ->setCountryCode("US")
    ->setPostalCode("95131")
    ->setPhone("2025550110")
    ->setState("CA");

$itemList = new ItemList();
$itemList->setItems(array($item1, $item2));
$itemList->setShippingAddress($shippingAddress);
// adding shipping phone number
$itemList->setShippingPhoneNumber("2025550112");


$details = new Details();
$details->setShipping(1.2)
    ->setTax(1.3)
    ->setSubtotal(17.50);

$amount = new Amount();
$amount->setCurrency("USD")
    ->setTotal(20)
    ->setDetails($details);

$transaction = new Transaction();
$transaction->setAmount($amount)
    ->setItemList($itemList)
    ->setDescription("Payment description")
    ->setInvoiceNumber(uniqid());

$baseUrl = "https://example.com";
$redirectUrls = new RedirectUrls();
$redirectUrls->setReturnUrl("$baseUrl/ExecutePayment.php?success=true")
    ->setCancelUrl("$baseUrl/ExecutePayment.php?success=false");

$payment = new Payment();
$payment->setIntent("sale")
    ->setPayer($payer)
    ->setRedirectUrls($redirectUrls)
    ->setTransactions(array($transaction));

// Create payment with valid API context
try {
    $payment->create($apiContext);

    echo $payment;

} catch (PayPal\Exception\PayPalConnectionException $ex) {
    echo $ex->getCode();
    echo $ex->getData();
    die($ex);
} catch (Exception $ex) {
    die($ex);
}
?>

```
