### ISSUE TITLE
Problem when going live

### ISSUE THREAD

**Issue by ahmedelattar73** [paypal/PayPal-PHP-SDK#1137]
When work on sandbox everything going well But if i use **live's credentials** it returned a blank page .
After tracing my code i found that the method  
 `$payment->create($this->apiContext) ` 
returned an object when using sandbox but returned nothing  when going live .
NOTE i'm using laravel framework.

Paypal.log 
 {"error":"invalid_client","error_description":"Client Authentication failed"}

**Comment by polnetwork** [comment]
You need to set the mode to "live". 
https://github.com/paypal/PayPal-PHP-SDK/wiki/Going-Live

**Comment by ahmedelattar73** [comment]
@polnetwork
Thanks it works fine

**Comment by prakash-gangadharan** [comment]
Hi @ahmedelattar73, I can see that your query has been answered by @polnetwork, Hence closing this issue.

Thanks!
