### ISSUE TITLE
An internal server error has occurred, comes when i clicked the app. the bsteps to the app are as follows:  sandbox-> account->profile->api credentials 

### ISSUE THREAD

**Issue by todx2** [paypal/PayPal-PHP-SDK#1139]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS:

**Comment by prakash-gangadharan** [comment]
Hi @todx2, now this option has been moved under sandbox > Account setting > Account access > API access > Manage API credentials. Also am not facing any internal server error now hence closing this issue.
