### ISSUE TITLE
ValidateWebhookEvent - Fatal error

### ISSUE THREAD

**Issue by curruwilla** [paypal/PayPal-PHP-SDK#1141]
https://github.com/paypal/PayPal-PHP-SDK/blob/ff2a7f9c2ddc47a22cb7bb8a5b0bb97bd16bdd6f/sample/notifications/ValidateWebhookEvent.php#L55

This is generating an error:
`Fatal error: Uncaught InvalidArgumentException: CertUrl is not a fully qualified URL in /home/uiliacom/public_html/loja/vendor/paypal/rest-api-sdk-php/lib/PayPal/Validation/UrlValidator.php:23 Stack trace: #0 /home/uiliacom/public_html/loja/vendor/paypal/rest-api-sdk-php/lib/PayPal/Api/VerifyWebhookSignature.php(60): PayPal\Validation\UrlValidator::validate(NULL, 'CertUrl') #1 /home/uiliacom/public_html/_cdn/postbackpaypal.php(20): PayPal\Api\VerifyWebhookSignature->setCertUrl(NULL) #2 {main} thrown in /home/uiliacom/public_html/loja/vendor/paypal/rest-api-sdk-php/lib/PayPal/Validation/UrlValidator.php on line 23`

**Comment by xserrat** [comment]
@curruwilla , I'm having the same problem. When I try to get subscription information about an agreement or when I try to pay but the error is `NotifyUrl is not a fully qualified URL`.

**Comment by flopp26** [comment]
Hi, any news on this ? I got same error.
