### ISSUE TITLE
How to make it live

### ISSUE THREAD

**Issue by jonjie0317** [paypal/PayPal-PHP-SDK#1142]
Hello Devs!  After I tested it on sandbox, I have now no idea on how to make it live. Do you have any steps/links so I can follow and make it on live?  I just read some of the issues and they are getting some problems making it live.

**Comment by codeglow** [comment]
Here is the wikipage for going live:
https://github.com/paypal/PayPal-PHP-SDK/wiki/Going-Live

**Comment by prakash-gangadharan** [comment]
Hi @jonjie0317, it looks like your query has been answered by @0xhtml . Hence closing this issue out. Feel free to reopen this if you are still facing any challenges going live.
