### ISSUE TITLE
Why I can't see the Payment Details in create_active_billing_agreement

### ISSUE THREAD

**Issue by mavinothkumar** [paypal/PayPal-PHP-SDK#1145]
### General information

* SDK/Library version: master
* Environment: Sandbox

### Issue description

Am testing the recurring payment in sandbox mode.

After creating the Plan, I can able to go for Create and active billing agreement, but in that page, I can't see the Payment details for how much they are subscribing. Please find the below attachment.
Even at the bottom of the page it say "you will review your order before you complete your purchase"

<img width="789" alt="screen shot 2018-07-14 at 11 16 34 am" src="https://user-images.githubusercontent.com/1659203/42721389-d26046c2-8757-11e8-9ac2-7d53d1f1d517.png">

How do the user know the subscription amount and plan in the billing page?

**Comment by prakash-gangadharan** [comment]
@mavinothkumar , this is more like the question which is more regarding to Billing agreement Product flow. Please refer the below link for merchant technical support. 

https://www.paypal.com/in/smarthelp/article/how-do-i-get-merchant-technical-support,-such-as-for-paypal-product-integrations,-apis-or-sandbox-testing-faq3723

Please visit [Merchant Technical Support](https://www.paypal-techsupport.com/app/) and submit your question for merchant/developer technical support, such as for PayPal product integrations/APIs

Thanks!
