### ISSUE TITLE
Chiper Bug

### ISSUE THREAD

**Issue by juragandotid** [paypal/PayPal-PHP-SDK#1146]
I think this is a little bug chipper class, decrypt function got error and the encode cannot be decrypt,

i think must be like this : 

` // Set the method
    $method = 'AES-128-CBC';
	$key_size = 256; // 256 bits
	$encryption_key = openssl_random_pseudo_bytes($key_size, $strong);
	print $encryption_key . "\r\n";
    // Generet a random initialisation vector
	$iv_size = 16; // 128 bits
	$iv = openssl_random_pseudo_bytes($iv_size, $strong);
	
	print $iv . "\r\n";

    // Define the date to be encrypted
    $data = "Encrypt me, please!";

    print "Before encryption:  ${data}\r\n";

    // Encrypt the data
    $encrypted = openssl_encrypt($data, $method, $encryption_key, 0, $iv);

    print "Encrypted: ${encrypted}\r\n";

    // Append the vector at the end of the encrypted string
    $encrypteds = $encrypted . ':' . $iv;
    print $encrypteds . "\r\n";

    // Explode the string using the `:` separator.
    $parts = explode(':', $encrypteds);
    print "COUNT: " . count($parts) . "\r\n";

    // Decrypt the data
    $decrypted = openssl_decrypt($parts[0], $method, $encryption_key, 0, $parts[1]);

    print "Decrypted: ${decrypted}\r\n";`

Thank you.

**Comment by sucithrashanu** [comment]
@juragandotid 
Can you elaborate the issue or Error message  you are getting or kindly share the PayPal-Debug-Id?

Thanks,

**Comment by prakash-gangadharan** [comment]
@juragandotid, is this still an issue?
