### ISSUE TITLE
Capture request returns "completed" as state instead of "approved" (Sandbox)

### ISSUE THREAD

**Issue by SFlame** [paypal/PayPal-PHP-SDK#1148]
* SDK/Library version: 1.13
* Environment: Sandbox
* Language, language version, and OS: PHP 7.2, Centos 7

### Issue description

When checking the state of a capture request ($capture->getState()) value returned is "completed" and not "approved" as documented.

Should I accept both?

**Comment by prakash-gangadharan** [comment]
The state of the capture. The possible values are:

```pending```. The capture is pending.
```completed```. The capture has successfully completed.
```refunded```. The capture was fully refunded.
```partially_refunded```. The capture was partially refunded.
```denied```. PayPal has declined to process this transaction.

**Doc Link** : https://developer.paypal.com/docs/api/payments/v1/#authorization-capture-response

**SDK code reference** : https://github.com/paypal/PayPal-PHP-SDK/blob/ff2a7f9c2ddc47a22cb7bb8a5b0bb97bd16bdd6f/lib/PayPal/Api/Capture.php#L101
