### ISSUE TITLE
Class 'BraintreeHttp\Serializer\FormPart' not found error use PayPal-PHP-SDK DisputeProvideEvidence

### ISSUE THREAD

**Issue by sasachen** [paypal/PayPal-PHP-SDK#1149]
General information：
Environment:production
branchdev-2.0-beta （https://github.com/paypal/PayPal-PHP-SDK/tree/dev-2.0-beta）
Issue description
1.configuration us project composer.json file require pakage "paypal/rest-api-sdk-php":"dev-2.0-beta",
2.use composer update to download rest-api-sdk-php.one flolder will be create when downloading finished.
3.create one sample file to test custom dispute ProvideEvidence API,FormPart class can not be found,
pls refer blew code :
` $request = new DisputeProvideEvidenceRequest('PP-000-042-636-207');
$body = [];
$file = fopen('/data/web/paypal/public/uploads/image/png/20180521/02cfe7d7ff1c9acf618e7239663812c1.png','rb');
$body["input"] = new FormPart([
"evidence_type" => "OTHER",
"notes" => "Notes"
], [
"Content-Type" => "application/json"
]);
$body["file1"] = $file;

    $client = TestHarness::client();
    $response = $client->execute($request);`
I sincerely hope to get your help!

**Comment by xjijies** [comment]
Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.
Please Check PayPal Community (https://www.paypal-community.com )and MTS ( https://paypal.com/mts )
Thanks!
