### ISSUE TITLE
Do I need to enable live mode on Paypal site?

### ISSUE THREAD

**Issue by polnetwork** [paypal/PayPal-PHP-SDK#1150]
My app is working fine on test mode, I'v followed https://github.com/paypal/PayPal-PHP-SDK/wiki/Going-Live and I'm in Live mode now.
The App seems to work well, Paypal returns to my ok URL but I can't see on Paypal the payments I made with my personal account.
Do I need to do something on the Paypal's side to enable Live mode?
Thank's for all.

**Comment by polnetwork** [comment]
Hi, I just discovered there's an extra step to actually process the payment.
http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/ExecutePayment.html
Thank's for all.

**Comment by prakash-gangadharan** [comment]
@polnetwork , Please refer the below doc link to Process PayPal Payments.
https://developer.paypal.com/docs/api/quickstart/payments/

Thanks!
