### ISSUE TITLE
set Phone in Invoice

### ISSUE THREAD

**Issue by catthr** [paypal/PayPal-PHP-SDK#1154]
In [Samples](http://paypal.github.io/PayPal-PHP-SDK/sample/doc/invoice/CreateInvoice.html) and in [api docs](https://developer.paypal.com/docs/api/invoicing/v1/#invoices_create) `Phone` is a field on `BillingInfo`, `ShippingInfo` and `MerchantInfo` objects but when I set it up there - it is no showing on the Invoice
When I set up `Phone` on `Address` - it is working then. 

Like so:

            $clientPhone = new Phone();
            $clientPhone
                ->setCountryCode('+7 ')
                ->setNationalNumber('9999999999');

            $billing[0]->getAddress()->setPhone($clientPhone);
            $payPalInvoice->getShippingInfo()->getAddress()->setPhone($clientPhone);

The same is valid for `MerchantInfo`

Is it correct behaviour? Should it be mentioned in the docs?

**Comment by sucithrashanu** [comment]
@catthr 
Yes It's the correct Behaviour given in the documentation.  Check this [Sample](https://github.com/paypal/PayPal-PHP-SDK/sample/invoice/CreateInvoice.php)

Thanks
