### ISSUE TITLE
Verifying Successful payment execution

### ISSUE THREAD

**Issue by andrewwommack** [paypal/PayPal-PHP-SDK#1156]
The below code is from the paypal PHP example to execute a payment. When this is done, my webhook is fired and my IPN script sets the payment as complete in the database.

```
$execution = new PaymentExecution();
$execution->setPayerId($_GET['PayerID']);

    try {
        // Execute the payment
        $result = $payment->execute($execution, $apiContext);

        try {
            $payment = Payment::get($paypalPaymentID, $apiContext);
            // Successfull here?
        } catch (Exception $ex) {
            thankyou_writeToIPNLogFile($ex,"Payment Execution Exception: Payment::Get");
        }
    } catch (Exception $ex) {
        thankyou_writeToIPNLogFile($ex,"Payment Execution Exception");
    }
// Payment not yet set to complete, webhook hasn't fired yet
```

(My long-winded function here is just writing data to a file).

However, Because the webhook takes longer to fire, I need to know how to test whether the payment is successful or not from the above code. Where i've written `Successfull here?` is where I think the payment is succesful, but how can I verify that?

**Comment by jiteshtandel** [comment]
> 
> 
> `if($payment->state == "approved") `

PayPal latest documentation don't have "approved" status. 
https://developer.paypal.com/docs/api/payments.billing-agreements/v1/#billing-agreements_execute

I am also facing issue. I am getting "Active" state as per latest document.

**Comment by whYME953** [comment]
> > `if($payment->state == "approved") `
> 
> PayPal latest documentation don't have "approved" status.
> https://developer.paypal.com/docs/api/payments.billing-agreements/v1/#billing-agreements_execute
> 
> I am also facing this issue. I am getting "Active" state as per latest document.

The status "Active" that you're talking about is by billing agreements.

Status "approved" is for regular payments.

**Comment by jiteshtandel** [comment]
@whYME953 you are right. Sorry for creating misunderstanding. Initially, I thought this thread code was for the Billing Agreement execute method but I was wrong. It's for Regular Payment.

Would you please check this my issue?
#1257

**Comment by prakash-gangadharan** [comment]
Hi @andrewwommack , 
The state of the payment, authorization, or order transaction. Value is:

- `created`. The transaction was successfully created.
- `approved`. The customer approved the transaction. The state changes from `created` to `approved` on generation of the `sale_id` for sale transactions, `authorization_id` for authorization transactions, or `order_id` for order transactions.
- `failed`. The transaction request failed.

[Developer API Reference link](https://developer.paypal.com/docs/api/payments/v1/#payment-execute-response)
