### ISSUE TITLE
Keep getting a Internal 500 Error and PayPal Exceptions

### ISSUE THREAD

**Issue by akshaypitale** [paypal/PayPal-PHP-SDK#1159]
### General information

* SDK/Library version: 
* Environment: Sandbox
* `PayPal-Debug-ID` values: c5272835a25d8
* Language, language version, and OS: 

### Issue description

I am using laravel framwork to use the PayPal PHP SDK. After running several tests I suddenly get an Error 500 when trying to create a new payment:

**Comment by prakash-gangadharan** [comment]
Hi @akshaypitale, Do you have any newer occurrence of this issue? if yes can you help here with the respective paypal-debug-id?

Thanks!

**Comment by prakash-gangadharan** [comment]
It looks like this is no longer applicable, hence closing this issue out. Please feel to reopen if your still see this instances around.

Thanks!
