### ISSUE TITLE
get transaction does not work?

### ISSUE THREAD

**Issue by danielecr** [paypal/PayPal-PHP-SDK#116]
https://developer.paypal.com/webapps/developer/docs/api/#look-up-a-sale
this, GET /v1/payments/sale/<Transaction-Id>

should work, but calling
$sale = Sale::get($saleId, $apiContext);

I get 
Exception: Got Http response code 404 when accessing https://api.paypal.com/v1/payments/sale/9CN41094540342824. Retried 0 times. string(207) "{"name":"INVALID_RESOURCE_ID","message":"The requested resource ID was not found","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INVALID_RESOURCE_ID","debug_id":"c0da8fbe2e080"}"

9CN41094540342824 is a transaction id of my account, the call take an userId?? I can not find it

**Comment by festlanky** [comment]
hello, i'm having problem getting transactions using getTransactions(). It returns [{}]. i need to get the invoice number shipping address from the transaction.$result = $payment->execute($execution, $apiContext);
    if ($result->getState() == "approved") {        
        $transaction_details = $result->getTransactions();
i get payer_info etc but transaction just returns empty body.

**Comment by pp-randy** [comment]
@festlanky I ran a similar call `print_r($result->getTransactions());` and get results.  Do you have access to the API response for your execute?
