### ISSUE TITLE
Direct Download samples not availables

### ISSUE THREAD

**Issue by NewWebDeveloperHere** [paypal/PayPal-PHP-SDK#1161]
Hello,

I'm trying to use direct download installation (without composer) and I went to [](url) https://github.com/paypal/PayPal-PHP-SDK/releases, and downloaded the 1.13.0 version, however the [](url) https://github.com/paypal/PayPal-PHP-SDK/wiki/Installation-Direct-Download link shows 
![image](https://user-images.githubusercontent.com/41515252/43036585-588b29c2-8cb9-11e8-95d1-da3fc7b3b901.png)

And there is no sample nor tests directory, so I'm having hard times trying to see how the ValidateWebHook sample should work since the one even in the documentation is using composer ([](url)http://paypal.github.io/PayPal-PHP-SDK/sample/doc/notifications/ValidateWebhookEvent.html) even the one I downloaded directly from the repo here [](url)https://github.com/paypal/PayPal-PHP-SDK

Is there any place where I can get such samples without composer? or am I doing something wrong since the Installation Direct Download instructions explicit shows the sample directory.

Thanks for your support on this matter.
Jake.

**Comment by sucithrashanu** [comment]
@jackellenberger 

Try to clone the code via git in your terminal. Its coming with sample and test code. 
Link[https://github.com/paypal/PayPal-PHP-SDK.git](url)

Thanks
