### ISSUE TITLE
Paypal agreement transaction ID

### ISSUE THREAD

**Issue by michalsukiennik** [paypal/PayPal-PHP-SDK#1163]
I created an agreement, I set a 'set up fee', start date set to next year as a subscription is annual. When the agreement is executed I want to get a transaction ID of payment. When I retrieve details of the agreement I have no transactions so set up fee was not added as a new transaction. Webhook event PAYMENT.SALE.COMPLETED does not provide transaction ID of paypal payment. How can I get it?

**Comment by younkim** [comment]
As far as I know, you need to query for the agreement transactions. There will be a `transaction_id` you can use.

See https://developer.paypal.com/docs/api/payments.billing-agreements/v1/#billing-agreements_transactions.

**Comment by prakash-gangadharan** [comment]
Hi @michalsukiennik, Please refer this sample code which demonstrate how you can search all billing transactions.
https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/billing/SearchBillingTransactions.php
