### ISSUE TITLE
Payment success but no transaction or payment detected on sandbox account.

### ISSUE THREAD

**Issue by salvatore-esposito** [paypal/PayPal-PHP-SDK#1167]
### General information

I used the example about payment and everything is ok even the redirect to success page where I get all data.

### Issue description

I use a fake buyer to log in when my page redirect me to paypal payment page and can see all items and the exact amount. When I click pay the page redirect me to another one on my local website and told me in the JSON that the success field is true. ANyway when I go to Sandbox page to check buyer account, its funds are the same. I use PHP SDK on Ubuntu 14.10.

**Comment by neo35** [comment]
Auf eine Email hate ich Paypal Account und auf 2 github Email mein githubmeilgmeil hatte synsing Login mehrfach abgelehnt und so mit das felehr reproduziert finde ich auch seltsam schreibe gleich Sandbox Team an :(

**Comment by salvatore-esposito** [comment]
What? Please speak English.

**Comment by prakash-gangadharan** [comment]
Hi @salvatore-esposito you should execute the payment after buyer approves it.
**Process PayPal Payments**: To create a PayPal payment below are the steps.

- [Define payment](https://developer.paypal.com/docs/api/quickstart/payments/#define-payment)
- [Create payment](https://developer.paypal.com/docs/api/quickstart/payments/#create-payment)
- [Execute payment](https://developer.paypal.com/docs/api/quickstart/payments/#execute-payment)
