### ISSUE TITLE
FormPart not present at BraintreeHttp\Serializer\FormPart in branch 2.0-beta

### ISSUE THREAD

**Issue by devreena03** [paypal/PayPal-PHP-SDK#1168]
I cloned the branch 2.0-beta and tried provideEvidence Dispute API, which require braintreeHttp FormPart, below is sample code

$client = new PayPalHttpClient($environment);

$request = new DisputeProvideEvidenceRequest('PP-000-042-636-207');
        $body = [];
        $file = fopen(dirname(__DIR__) . '\test.jpg', 'rb');
        $body["input"] = new FormPart([
            "evidence_type" => "OTHER",
            "notes" => "Notes"
        ], [
            "Content-Type" => "application/json"
        ]);
        $body["file1"] = $file;
$request->body = $body;

try {
    $response = $client->execute($request);
    print_r($response);
	echo json_encode($response);

In composer.json, currently  version is
"require": {
    "braintree/braintreehttp": "^0.2.4"
  },
it doesn't contain FormPart class, we updated it to 
"require": {
    "braintree/braintreehttp": "0.3.0"
  },
which is having FormPart and Dispute API started working. 
please update the composer.json to appropriate braitreeHttp version.

**Comment by sasachen** [comment]
I have the same problem! I update this package manually by these link 'https://github.com/braintree/braintreehttp_php',but  others  error  appear

**Comment by sai5839448** [comment]
Thank

**Comment by sucithrashanu** [comment]
@devreena03 

Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.

Please Check [PayPal Community](https://www.paypal-community.com) and  [MTS](https://paypal.com/mts) 

Thanks!
