### ISSUE TITLE
subscribe question

### ISSUE THREAD

**Issue by yura-sutnuk** [paypal/PayPal-PHP-SDK#1169]
I need to create an application where the user will subscribe for a month, when the subscription is over, the user will automatically renew this subscription and his money will be removed from his account and transferred to another one, whether it can be done with the help of the paypal tools (like you can create buttons for subscription) and can Does my site know who paid for the subscription?

for example, I created a subscription https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=U9S7ZR4W46WQL when the user pays for it as my application can learn about it? it does not create any callback or any

**Comment by neo35** [comment]
Wie kann ich die repo sicher entfernen so das kein Schaden zu nimmt ? Ich habe schon Email geschickt widerrufen

**Comment by neo35** [comment]
Widerrufen *

**Comment by prakash-gangadharan** [comment]
Hi @yura-sutnuk,  can you give more context about this issue? its still unclear what your requirement is.

**Comment by prakash-gangadharan** [comment]
@yura-sutnuk, we looking forward for your further inputs.

**Comment by prakash-gangadharan** [comment]
Hi @yura-sutnuk, this is more like the question which is regarding the integration part. Please refer the below link for merchant technical support.
https://www.paypal.com/in/smarthelp/article/how-do-i-get-merchant-technical-support,-such-as-for-paypal-product-integrations,-apis-or-sandbox-testing-faq3723

Please visit [Merchant Technical Support](https://www.paypal-techsupport.com/app/) and submit your question for merchant/developer technical support, such as for PayPal product integrations/APIs

Thanks!
