### ISSUE TITLE
Class "String" not found error in PayPal core sdk

### ISSUE THREAD

**Issue by prparamasivam** [paypal/PayPal-PHP-SDK#117]
Hi,
I getting the following error while integrating risk SDK with core sdk. Kindly help.
Fatal error: Class 'string' not found in C:\xampp\htdocs\paypal-raas-sdk\raas-api-sdk-php\vendor\paypal\sdk-core-php\lib\PayPal\Common\PPModel.php on line 51

**Comment by nikunj1806** [comment]
i do all this mentioned things but still i get  paypal/lib/PayPal/Common/PPModel.php on line 164 this error.
and it works in local but not on server.

**Comment by ulkas** [comment]
@nikunj1806 

what did you put into the doc-comment section above the called class? it should be similar to
<code>/**
 * @return \PayPal\Api\PaymentDefinition
 */
</code>
but not always the same, of course.

**Comment by nikunj1806** [comment]
but where that portion in SDK

here is my code

<?php

// # Create Payment using PayPal as payment method
// This sample code demonstrates how you can process a 
// PayPal Account based Payment.
// API used: /v1/payments/payment

require __DIR__ . '/../bootstrap.php';
print_r($_POST);

use PayPal\Api\Amount;
use PayPal\Api\Details;
use PayPal\Api\Item;
use PayPal\Api\ItemList;
use PayPal\Api\Payer;
use PayPal\Api\Payment;
use PayPal\Api\RedirectUrls;
use PayPal\Api\Transaction;

$post_data = filter_input_array(INPUT_POST);
extract($post_data);


// ### Payer
// A resource representing a Payer that funds a payment
// For paypal account payments, set payment method
// to 'paypal'.
$payer = new Payer();
$payer->setPaymentMethod("paypal");

// ### Itemized information
// (Optional) Lets you specify item wise
// information
$item1 = new Item();
$item1->setName('subscription')
        ->setCurrency('USD')
        ->setQuantity($quantity)
        ->setPrice($value);
//$item2 = new Item();
//$item2->setName('Granola bars')
//        ->setCurrency('USD')
//        ->setQuantity(5)
//        ->setPrice(2);

$itemList = new ItemList();
$itemList->setItems(array($item1));

// ### Additional payment details
// Use this optional field to set additional
// payment information such as tax, shipping
// charges etc.
$details = new Details();
$details->setTax($tax)
        ->setSubtotal($total);

// ### Amount
// Lets you specify a payment amount.
// You can also specify additional details
// such as shipping, tax.
$amount = new Amount();
$amount->setCurrency("USD")
        ->setTotal($subtotal)
        ->setDetails($details);

// ### Transaction
// A transaction defines the contract of a
// payment - what is the payment for and who
// is fulfilling it. 
$transaction = new Transaction();
$transaction->setAmount($amount)
        ->setItemList($itemList)
        ->setDescription("Payment description")
        ->setInvoiceNumber(uniqid());

// ### Redirect urls
// Set the urls that the buyer must be redirected to after 
// payment approval/ cancellation.
$baseUrl = getBaseUrl();
$redirectUrls = new RedirectUrls();
$redirectUrls->setReturnUrl("$baseUrl/ExecutePayment.php?success=true")
        ->setCancelUrl("$baseUrl/ExecutePayment.php?success=false");

// ### Payment
// A Payment Resource; create one using
// the above types and intent set to 'sale'
$payment = new Payment();
$payment->setIntent("sale")
        ->setPayer($payer)
        ->setRedirectUrls($redirectUrls)
        ->setTransactions(array($transaction));


// For Sample Purposes Only.
$request = clone $payment;

// ### Create Payment
// Create a payment by calling the 'create' method
// passing it a valid apiContext.
// (See bootstrap.php for more on `ApiContext`)
// The return object contains the state and the
// url to which the buyer must be redirected to
// for payment approval
try {
    $payment->create($apiContext);
} catch (Exception $ex) {
    ResultPrinter::printError("Created Payment Using PayPal. Please visit the URL to Approve.", "Payment", null, $request, $ex);
    exit(1);
}

// ### Get redirect url
// The API response provides the url that you must redirect
// the buyer to. Retrieve the url from the $payment->getLinks()
// method
foreach ($payment->getLinks() as $link) {
    if ($link->getRel() == 'approval_url') {
        $approvalUrl = $link->getHref();
        break;
    }
}
header('Location:' . $approvalUrl);
ResultPrinter::printResult("Created Payment Using PayPal. Please visit the URL to Approve.", "Payment", "<a href='$approvalUrl' >$approvalUrl</a>", $request, $payment);

return $payment;

**Comment by ulkas** [comment]
@nikunj1806 
put this into the file `Common/PPReflectionUtil.php` at line 37 at the beginning of the function `getPropertyClass()`

```
var_dump($class); var_dump($propertyName);
```


and paste here the particular dump just before the error is thrown. i can than tell you which file you will have to modify

**Comment by nikunj1806** [comment]
it will generate

string(18) "PayPal\Api\Payment" string(5) "payer"

**Comment by nikunj1806** [comment]
it will generate
string(18) "PayPal\Api\Payment" for class  &
string(5) "payer" property

**Comment by nikunj1806** [comment]
above diplayed on server but on local it will be like
string 'PayPal\Api\Payment' (length=18)
string 'payer' (length=5)
string 'PayPal\Api\Payer' (length=16)
string 'payer_info' (length=10)
string 'PayPal\Api\PayerInfo' (length=20)
string 'shipping_address' (length=16)
string 'PayPal\Api\Payment' (length=18)
string 'transactions' (length=12)
string 'PayPal\Api\Transaction' (length=22)
string 'amount' (length=6)
string 'PayPal\Api\Amount' (length=17)
string 'details' (length=7)
string 'PayPal\Api\Transaction' (length=22)
string 'item_list' (length=9)
string 'PayPal\Api\ItemList' (length=19)
string 'items' (length=5)
string 'PayPal\Api\Transaction' (length=22)
string 'related_resources' (length=17)
string 'PayPal\Api\Payment' (length=18)
string 'links' (length=5)

so any setting on server side?
plz tell me

**Comment by ulkas** [comment]
it looks ok in current sdk, do you have this line of code in api/payment.php? specifically, with the `* @return \PayPal\Api\Payer` comment

```
    /**
     * Source of the funds for this payment represented by a PayPal account or a direct credit card.
     *
     * @return \PayPal\Api\Payer
     */
    public function getPayer()
    {
        return $this->payer;
    }
```

**Comment by jaypatel512** [comment]
Btw, @ulkas @nikunj1806 Would it help, if the error message somehow could print, which getter caused that issue ? That could iron out a bit more I guess. I will add a feature soon.

**Comment by ulkas** [comment]
@jaypatel512 thank you for that.

@nikunj1806 could you pls update your SDK to the newest version? there has been also this change, which will help us better to track down the issue:
https://github.com/paypal/PayPal-PHP-SDK/commit/0b43d599c442983578113650c76b0b5d42ebd159

**Comment by jaypatel512** [comment]
Hey @ulkas I actually worked with him yesterday, on this issue, and it turns out, the issue is not reproducable in his local machine. They are working fine. And even the samples are not working for him, on server for 0.16.1 release. I think the issue is with the server itself, and not the SDK.

**Comment by avogt** [comment]
Had the same Problem today. Solution for me was to set the class for "transaction_fee" to something like PayPal\Api\Amount

**Comment by jziaja** [comment]
@avogt which version of this SDK are you using?  The issue with `transaction_fee` should have been resolved in [version 1.3.0](https://github.com/paypal/PayPal-PHP-SDK/releases/tag/v1.3.0).  Also, the `transaction_fee` property should be of type `Currency`, not `Amount`.  See the current [Sale.php](https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Api/Sale.php#L331) and [Capture.php](https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Api/Capture.php#L153) objects as well as the public docs on retrieving a [sale](https://developer.paypal.com/docs/api/#look-up-a-sale) or [capture](https://developer.paypal.com/docs/api/#look-up-a-captured-payment) resource for more information.  (_Note:_ The public docs on retrieving the capture resource are missing a description for `transaction_fee` - I'll notify the docs team that this is missing.  It is included in the sample response, though.)

**Comment by avogt** [comment]
Hi, yeah, sorry copy paste error, was Capture.
The Readme says PayPal Core SDK - V2.4.0

**Comment by jziaja** [comment]
Core was integrated into this SDK in release version [0.11.1](https://github.com/paypal/PayPal-PHP-SDK/releases/tag/v0.11.1) in October of last year, removing it as a separate dependency.  Are you able to upgrade to the current version of this SDK?  @jaypatel512 has put together a [helpful page on the wiki](https://github.com/paypal/PayPal-PHP-SDK/wiki/Breaking-Changes---1.0.0) that goes over all the breaking changes that occurred with the 1.0 release.

**Comment by avogt** [comment]
Thx, will try it after the easter holidays.
