### ISSUE TITLE
Problem with GET /v1/checkout/orders/{order_id}

### ISSUE THREAD

**Issue by martacronic** [paypal/PayPal-PHP-SDK#1170]
I have the same problem in Postman and in PayPal-PHP-SDK (with my modifications).

I have transactionID from PayPal, and I need invoice details with items discounts.

What am I doing:

1. GET `/v1/checkout/orders/{order_id}` - in place of order_id I'm putting transactionID
2. From response I'm getting purchase_units and than invoice_number
3. GET `/v1/invoicing/invoices/{invoice_id}` - I'm getting invoice details.

The problem is that, for some transactions every think is ok, but for other I'm getting in `/v1/checkout/orders/{order_id}  ` response

```
{
	"name": "INVALID_RESOURCE_ID",
	"message": "INVALID_RESOURCE_ID",
	"information_link": "https://developer.paypal.com/docs/api/orders#errors",
	"debug_id": "8dec8f327aa3f"
}
```
In NVP API I don't have this problem, but I can get invoice details about discount.

Maybe is other whay to getting invoice details based on transactionID?

**Comment by ThomasAunvik** [comment]
Getting the same issue, have tried multiple transaction id's and still not working, the application does have access to my history.

`https://api.sandbox.paypal.com/v2/checkout/orders/{order_id}`
```
{  
   "name":"RESOURCE_NOT_FOUND",
   "details":[  
      {  
         "issue":"INVALID_RESOURCE_ID",
         "description":"Specified resource ID does not exist. Please check the resource ID and try again."
      }
   ],
   "message":"The specified resource does not exist.",
   "debug_id":"df2ef96896cfb",
   "links":[  
      {  
         "href":"https://developer.paypal.com/docs/api/orders/v2/#error-INVALID_RESOURCE_ID",
         "rel":"information_link",
         "method":"GET"
      }
   ]
}
```

**Comment by vienntbna** [comment]
I have the same problem. Can't get the transaction details

**Comment by morningdew830** [comment]
Exact same error.

**Comment by PaulBenabou** [comment]
I have the exact same error on NodeJS.
I guess it's coming from the sandbox API of paypal.
Any news on this ?

**Comment by prakash-gangadharan** [comment]
@martacronic can you help us with recent `paypal-debug-id`?

**Comment by prakash-gangadharan** [comment]
@martacronic , this is more like the question which is regarding to Order API . Please refer the below link for merchant technical support. 

https://www.paypal.com/in/smarthelp/article/how-do-i-get-merchant-technical-support,-such-as-for-paypal-product-integrations,-apis-or-sandbox-testing-faq3723

Please visit [Merchant Technical Support](https://www.paypal-techsupport.com/app/) and submit your question for merchant/developer technical support, such as for PayPal product integrations/APIs

Thanks!
