### ISSUE TITLE
Create billing agreement gives "Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/billing-agreements/."

### ISSUE THREAD

**Issue by minivetsystem** [paypal/PayPal-PHP-SDK#1172]
I was trying to create with the billing agreement with paypal but i have got the below error

**Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/billing-agreements/**
Below is the screenshot:
![image](https://user-images.githubusercontent.com/5833591/44097299-0d399c92-9ffb-11e8-807a-98c193f74eee.png)

First I have create the plan then active the plan. My plan id "P-2WJ001268W5205102HC6XVMY" 
https://paypal.github.io/PayPal-PHP-SDK/sample/doc/billing/CreatePlan.html

After got the plan id when i trying to create agreement i am getting error from paypal. I have use the below link code for creating the agreement.
https://paypal.github.io/PayPal-PHP-SDK/sample/doc/billing/CreateBillingAgreementWithPayPal.html

Please help me solve this issue.

**Comment by younkim** [comment]
Try checking `$e->getData()`, and it might have more information on your 400. Not 100% sure off-hand, but the exception message usually contains only a generic message.

**Comment by Gelembjuk** [comment]
Is there any more info?
I got same problem today

**Comment by karamvirs** [comment]
Any update on this one. been facing this issuse since last few days.

**Comment by GrzegorzWalewski** [comment]
same here

**Comment by jcardussi** [comment]
Anyone?

**Comment by prakash-gangadharan** [comment]
@minivetsystem and @jcardussi , can you guys help here with the paypal-debug-id to check this further?

**Comment by jcardussi** [comment]
> @minivetsystem and @jcardussi , can you guys help here with the paypal-debug-id to check this further?

Where will I find that?

**Comment by prakash-gangadharan** [comment]
Hi @jcardussi, Hope the below link help you out to get the `PayPal-Debug-ID` and to understand your errors
https://github.com/paypal/PayPal-PHP-SDK/wiki/exception-%27PayPal%5CException%5CPayPalConnectionException%27-with-message-%27Got-Http-response-code-400-when-accessing
Please let us know if you are facing any challenges.

**Comment by prakash-gangadharan** [comment]
@minivetsystem,@younkim,@Gelembjuk,@karamvirs & @GrzegorzWalewski, can you guys help here with the recent `PayPal-Debug-ID` to check this further?

**Comment by jcardussi** [comment]
I got the answer and posted it here:

https://github.com/paypal/PayPal-PHP-SDK/issues/1299#event-2701322856
