### ISSUE TITLE
INSTRUMENT_DECLINED error

### ISSUE THREAD

**Issue by yura-sutnuk** [paypal/PayPal-PHP-SDK#1178]
Hi, i try to integrate paypall service at site and in sandbox mode all work fine but in live mode i get this error for all transactions 
```
{
"name":"INSTRUMENT_DECLINED",
"details":[],
"message":"The instrument presented  was either declined by the processor or bank, or it can't be used for this payment.",
"information_link":"https://developer.paypal.com/docs/api/payments/#errors","
debug_id":"4a51a45cac9c4"
} 
```
I am using paypal/rest-api-sdk-php 1.13.0. 
How can i fix this error? 
this is debugs id that stored in my log files, hope it can help:

> 4a51a45cac9c4
> cc376d9521296
> 963e407724aa2

**Comment by prakash-gangadharan** [comment]
Hi @yura-sutnuk,  is this still an issue? do you have any recent occurrences of this decline?

**Comment by prakash-gangadharan** [comment]
It looks like this is no longer applicable, hence closing this issue out. Please feel to reopen if your still see this instances around.

Thanks!
