### ISSUE TITLE
Timeline for Version 2?

### ISSUE THREAD

**Issue by CaptainHypertext** [paypal/PayPal-PHP-SDK#1180]
I see you've got a snazzy new version 2 for this library, and it looks nice.  I'd like to use it, but it's still in beta and has very little documentation.  Is there a timeline for it to be released?  I'm starting a new project and would hate to use the old version if the new one's going to be released before the end of the year.  Plus the last commit was April 17th.

Any word?

**Comment by kristian-b** [comment]
Now it is 2019-06 and still no answer?

**Comment by Sebi94nbg** [comment]
See here: [Comment #515360686](https://github.com/paypal/PayPal-PHP-SDK/issues/1275#issuecomment-515360686)

**Comment by prakash-gangadharan** [comment]
Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.

**Comment by sucithrashanu** [comment]
@CaptainHypertext 


Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.

Please Check [PayPal Community ](https://www.paypal-community.com)and  [MTS]( https://paypal.com/mts) 

Thanks!
