### ISSUE TITLE
Billing plan - custom field

### ISSUE THREAD

**Issue by killmegerty** [paypal/PayPal-PHP-SDK#1181]
Using sandbox, 

### Issue description

Hi, currently I integrating billing plan using php sdk examples, and I have a question.
How can I relate my product id (subscription) with created billing plan (with )? 
For payments we have a custom field - merchant can pass OrderID there, and after he receive IPN - handle this OrderID and update DB.

But I don't see similar feature with Billing Plans.. How can I confirm that payment completed and update DB after ? 

Why official guide doesn't describe when and how should I update my store DB? The guides only described payment process, but how can I relate this payments with products&

**Comment by prakash-gangadharan** [comment]
PayPal-PHP-SDK internally uses our older deprecated billing plans and agreements API, which unfortunately does not support custom pass through merchant attributes.  

If it is newer integration, the recommendation is to migrate to our [NextGen Subscription](https://developer.paypal.com/docs/subscriptions/) integration to get the benefits of lot more richer functionality including support of custom pass through merchant attributes (which is currently WIP).
