### ISSUE TITLE
PatchRequest yields no change.

### ISSUE THREAD

**Issue by beeenji** [paypal/PayPal-PHP-SDK#1183]
Hi, 
Using: Live

I'm trying update the next payment due date of a billing agreement via the PHP SDK but altough the responsecode is 200 the actual agreement does not update.
Also: The payer gets notified with an email stating that the "billing agreement has changed" even though nothing was updated. 

Is it even possible to update "next_billing_date"? 

The code:
$patchContent = '{"agreement_details":{"next_billing_date":"2018-10-26T10:00:00Z"}}';
$patch = new Patch();
$patch->setOp('replace')
	->setPath('/')
	->setValue(json_decode($patchContent));

$patchRequest = new PatchRequest();
$patchRequest->addPatch($patch);

$response = $agreement->update($patchRequest, $apiContext);

**Comment by pimfeltkamp** [comment]
@beeenji Did you got this fixed? I want to know, because I am also looking for a way to change the next billing date. Is this even possible? Or is the value read-only.
