### ISSUE TITLE
Payout returns error 401 AUTHENTICATION_FAILURE

### ISSUE THREAD

**Issue by EdoGaru** [paypal/PayPal-PHP-SDK#1185]
### General information

* SDK/Library version: 1.13.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: PHP 7.2.2, Windows 7

### Issue description
Hello, so iam trying to run an example from the **Payouts** section which is called, `Create Batch Payout` it returns me this response: 
```
{
    "batch_header": {
        "payout_batch_id": "E36WHEX77HGVY",
        "batch_status": "PENDING",
        "sender_batch_header": {
            "sender_batch_id": "5b930589ece0a",
            "email_subject": "You have a payment"
        }
    },
    "links": [
        {
            "href": "https://api.sandbox.paypal.com/v1/payments/payouts/E36WHEX77HGVY",
            "rel": "self",
            "method": "GET",
            "enctype": "application/json"
        }
    ]
}
```

If you notice the `batch_status` says its `PENDING` from what i know, that meanst there is an error and when i go to this url https://api.sandbox.paypal.com/v1/payments/payouts/E36WHEX77HGVY it returns me this issue.

`{"name":"AUTHENTICATION_FAILURE","message":"Authentication failed due to invalid authentication credentials or a missing Authorization header.","links":[{"href":"https://developer.paypal.com/docs/api/overview/#error","rel":"information_link"}]}`

I tried changing the `client_id` and `client_secret` from the `bootstrap.php` file in the example codes, with an account of the U.S and it still gives me this same response, been facing this problem from several days.

**Comment by EdoGaru** [comment]
Ok, so there weren't any issues with the api, it was my fault thought, i just got confused because i was getting only that, link and i thought there was an error in my call,

**Comment by seojake** [comment]
> Ok, so there weren't any issues with the api, it was my fault thought, i just got confused because i was getting only that link and i thought there was an error in my call.

So what was actually the problem? I'm trying to do the same thing as you, and I can't seem to figure out why it's not working. 

`curl_setopt($ch, CURLOPT_HTTPHEADER, array("Content-Type: application/json","Authorization: Bearer'.$json->access_token.'"));`

However, I'm not getting the bit before the error... the batch header JSON result. Here's my full code:

`curl_setopt($ch, CURLOPT_URL, "https://api.sandbox.paypal.com/v1/oauth2/token");
/*curl_setopt($ch, CURLOPT_URL, "https://api.paypal.com/v1/oauth2/token");*/
curl_setopt($ch, CURLOPT_HEADER, false);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_USERPWD, $client.":".$secret);
curl_setopt($ch, CURLOPT_POSTFIELDS, "grant_type=client_credentials");
$result = curl_exec($ch);
if(empty($result)){
    die("Error: No response.");
} else {
    $json = json_decode($result);
    print_r($json->access_token);
}

$ch = curl_init();

$data = '{
  "sender_batch_header": {
    "email_subject": "You have a payout!",
    "email_message": "You have received a payout! Thanks for using our service!"
  },
  "items": [
    {
      "recipient_type": "EMAIL",
      "amount": {
        "value": "0.01",
        "currency": "CAD"
      },
      "note": "Thanks for your patronage!",
      "receiver": "XXX"
    }
  ]
}';

curl_setopt($ch, CURLOPT_URL, "https://api.sandbox.paypal.com/v1/payments/payouts");
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
curl_setopt($ch, CURLOPT_HTTPHEADER, array("Content-Type: application/json","Authorization: Bearer'.$json->access_token.'"));
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
$result = curl_exec($ch);
print_r($result);
curl_close($ch);`

Also, why do I need to include a batch ID, if I'm only making a payment to one user? Surely I won't know the batch ID or whatever until I've sent the money?

**Comment by EdoGaru** [comment]
There was no error everything was working correctly.

I highly recommend using the PHP REST API, i personally find it more easy for debugging and more,
You still need to provide batch id, just to prevent duplicates, and you dont need to know the batch id (unless you are storing it in a database).

(And sorry can't give you a proper answer as to what went wrong in your code,  i dont usually use cURL).

**Comment by ArtNous** [comment]
Hi guys, I'm facing the same issue, I have the correct credentials, so why is PayPal sending me that response?

**Comment by HadiNiazi** [comment]
it was because i am sending two individual HTTPHEADERS instead of one, and the result is to overwrite one another. So the correct way to do it, is to pass an array in the third arguments of HTTPHEADER like this:

`curl_setopt($ch2, CURLOPT_HTTPHEADER , array("Content-Type: application/json", "Authorization: Bearer myaccesstokenishere"));`

After that i still had the problem:
ppxo_no_token_passed_to_payment
ppxo_unhandled_error {stack: "Error: No value passed to payment↵
Uncaught Error: No value passed to payment

To fix that problem i just echo the result without json_decode it like this:

```
$result = curl_exec($ch2);

echo $result;

curl_close($ch2);
```
