### ISSUE TITLE
Using PayPal REST SDK in SANDBOX mode, why do i got an orange exclamation mark in the Dashboard of the Webhook page?

### ISSUE THREAD

**Issue by Neokyuubi** [paypal/PayPal-PHP-SDK#1186]
### General information

* SDK/Library version: 1.13.0 
* Environment: Sandbox
* `PayPal-Debug-ID` values: N/A
* Language, language version, and OS: PHP7.1 with Laravel 5.3, Windows7.

### Issue description
@jaypatel512 
@xiaoleih41 
I receive the webhook 'PAYMENT.SALE.COMPLETED' in my server side but in the "Status" column of the Dashboard i got a yellow exclamation marks instead of the green check mark !
So why is that sometime it's green and other it's orange?

![screen](https://user-images.githubusercontent.com/40678329/45254418-b38e7680-b36f-11e8-8cc0-c5e1b9381084.jpg)

And i use echo $status; at the end of the listener file/method.
Here's one of the orange webhook's result : https://pastebin.com/RrCChZCk
As you can see the status is PENDDING and also transmissions[0].status is PENDDING !!!

Please can anyone enlighten me about what's going on here ?

**Comment by daslicht** [comment]
Have you mailed the PayPal Tech Support ?
https://www.paypal-techsupport.com/

They are the best support I have found for PayPal yet

**Comment by daslicht** [comment]
Yeah , Stackoverflow is very very special, and it seams that some guys doing nothing else than waiting for downvoting other for some reason.

**Comment by Neokyuubi** [comment]
@daslicht  I just saw something interesting in my dashboard, in the first page of the webhooks there's are some green and some orange just like you. but when i checked the old pages (i had like 8 pages) starting from page 2 all the webhooks turned into green !!! So it was just a time question and maybe in this case a sandbox question too, i'm assuming this happen only in this mode. i cannot test the live mode for no to confirm.

**Comment by daslicht** [comment]
I am able to test it very soon with a live account and I also have some questions open to payPal.
For example , how ofen is an WebHook Event send ?!

IPN > multiple times
PDT ? just once
Webhook ???

related:
https://developer.paypal.com/docs/classic/ipn/integration-guide/IPNPDTAnAlternativetoIPN/#when-to-use-pdt

**Comment by Neokyuubi** [comment]
For how often they say  [here ](https://developer.paypal.com/docs/integration/direct/webhooks/rest-webhooks/#overview):
> If your webhook endpoint is unavailable or takes too long to respond, PayPal resends the notification message 25 times over the course of three days until a successful response is given.

I think that when you are in your application at : [https://developer.paypal.com/developer/applications/](https://developer.paypal.com/developer/applications/) you can see at left panel that down there's a section for LIVE API Calls and Webhooks Events.

**Comment by daslicht** [comment]
thank you!

**Comment by daslicht** [comment]
you are on gitter ?

**Comment by Neokyuubi** [comment]
@daslicht I wasn't but now yes.

**Comment by daslicht** [comment]
this : https://gitter.im/paypal/paypal-checkout ?

**Comment by Neokyuubi** [comment]
I joined.
