### ISSUE TITLE
Successfull Billing Agreement Execution not Showing in Payment::all

### ISSUE THREAD

**Issue by mavinothkumar** [paypal/PayPal-PHP-SDK#1188]
### General information

* SDK/Library version: 1.13.0
* Environment: Sandbox

### Issue description

After successful billing agreement execution, I can't get those paid details through the Payment::all() method. But I can able to get the previous one time payment and old subscription payment, not the new ones. Is am doing anywhere wrong?

Process: ( Taken from the sample code )
1. Starting from creating and active Billing Agreement 
2. Billing agreement success.

Note: I can able to get the complete Agreement details after the Billing agreement success. But not to fetch those through the Payment::all().

**Comment by jonjie0317** [comment]
Have you tried the `Payment::get()`?

**Comment by mavinothkumar** [comment]
Yes Payment::get(Agreement_ID) works correctly.

**Comment by jonjie0317** [comment]
Hi @mavinothkumar . Sorry, but I honestly don't know. I'm also facing a problem where I cannot get the phone number using this package 😆

**Comment by prakash-gangadharan** [comment]
@mavinothkumar refer the below example where Payment::all() method will get the one time payments
[ListPayments](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/ListPayments.php)
It is a wrapper for [List payments API](https://developer.paypal.com/docs/api/payments/v1/#payment_list)
