### ISSUE TITLE
getShippingAddress deprecated. Why ? Should I still use it ?

### ISSUE THREAD

**Issue by lazytanuki** [paypal/PayPal-PHP-SDK#1191]
Hello there,

I have seen in the documentation that the getShippingAddress method for the PayerInfo class is deprecated. Thus I have two questions:

- Does it mean that in the near future we'll have to make the user enter his shipping details instead of getting them from his PayPal Checkout ?
- Is there another non-deprecated mean to get this information that I haven't seen ?

Thank you for your time,

LazyTanuki

**Comment by petersephrin** [comment]
Hello,
Am also concerned about the same issue.

**Comment by sucithrashanu** [comment]
@lazytanuki 
You can make use of the **getShippingAddress** from the class ItemList.
Ref the [Link](https://github.com/paypal/PayPal-PHP-SDK/blob/ff2a7f9c2ddc47a22cb7bb8a5b0bb97bd16bdd6f/lib/PayPal/Api/ItemList.php)

Thanks
