### ISSUE TITLE
How can i save data order to database?

### ISSUE THREAD

**Issue by phamloi7710** [paypal/PayPal-PHP-SDK#1192]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description

![image](https://user-images.githubusercontent.com/36951408/45609693-29d35d00-ba83-11e8-8278-926315edd9f3.png)

**Comment by prakash-gangadharan** [comment]
Hi @phamloi7710,  can you give more context about this issue?

**Comment by prakash-gangadharan** [comment]
@phamloi7710 , closing this issue for now, please revert us back if you have any challenges still.
