### ISSUE TITLE
An exception that occurs when using an HTTP proxy

### ISSUE THREAD

**Issue by WonlyCms** [paypal/PayPal-PHP-SDK#1193]
> This issue is available in English and Simplified Chinese.

Due to my network, I need to use a proxy to secure access to PayPal. But when I set the proxy using the following method, the result of the request is wrong.

由于我的网络，我需要使用代理来保护对PayPal的访问。 但是当我使用以下方法设置代理时，请求的结果是错误的。

```php
PayPalConfigManager::getInstance()
	->addConfigs([
		'http.Proxy' => '127.0.0.1:1080'
	]);
```

这样之后，代理确实生效了，但是出现了错误在
After this, the agent does take effect, but there is an error in

- …\vendor\paypal\rest-api-sdk-php\lib\PayPal\Core\PayPalHttpConnection.php:90
>ErrorException (E_NOTICE)
Undefined offset: 1

Extract the code as follows
摘出代码如下

```php
list($key, $value) = explode(":",$trimmedData, 2);
```

Here I saw an explode method, probably because the header of the response was not loaded with `:`, which caused the failure. For example, `HTTP/1.0 200 OK` will cause an error.
When I tried to adjust the code, I got the desired result.

在这里我看到了一个 explode 方法，可能是在处理响应的 header 时因为部分header 并不带有 `:`，导致失败。比如 `HTTP/1.0 200 OK` 这时就会出现错误。
当我尝试将代码进行调整后就得到了期望的结果。

```php
$key = '';
$value = '';
strpos(':', $trimmedData) 
&& list($key, $value) = explode(":",$trimmedData, 2);
```

This may be a minor issue.

**Comment by sucithrashanu** [comment]
@WonlyCms 
Do you still see this instances of this issue? If so Please provide latest PayPal-Debug-ID. Check  in the version 1.14.0 also.

You can use function **setHttpProxy** from PayPalHttpConfig class. Ref [LINk](https://github.com/paypal/PayPal-PHP-SDK/blob/ff2a7f9c2ddc47a22cb7bb8a5b0bb97bd16bdd6f/lib/PayPal/Core/PayPalHttpConfig.php)

Thanks

**Comment by WonlyCms** [comment]
> @WonlyCms
> Do you still see this instances of this issue? If so Please provide latest PayPal-Debug-ID. Check in the version 1.14.0 also.
> 
> You can use function **setHttpProxy** from PayPalHttpConfig class. Ref [LINk](https://github.com/paypal/PayPal-PHP-SDK/blob/ff2a7f9c2ddc47a22cb7bb8a5b0bb97bd16bdd6f/lib/PayPal/Core/PayPalHttpConfig.php)
> 
> Thanks

Thanks for the guide, I used the SDK in my previous project, but now I am no longer responsible for that project.
