### ISSUE TITLE
ExecutePayment.php triggered twice, or not at all

### ISSUE THREAD

**Issue by randomd00d** [paypal/PayPal-PHP-SDK#1194]
### General information

* SDK/Library version: 1.12.0
* Environment: Production / Live
* `PayPal-Debug-ID` values: None available
* Language, language version, and OS: PHP Version 5.6.35, CentOS Linux release 7.4.1708

### Issue description

This version of SDK has been in use since late August 2017, without any issues. Type of payment used is PayPal Payment ([Part 1](http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/CreatePaymentUsingPayPal.html), [Part 2](http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/ExecutePayment.html)).

**Double triggering**
On the 5th and the 6th of September, two of the unrelated buyers / payers paid,  their payments were registered by PayPal, and on our end. However, for some reason we have registered them twice, even though there is only one block of code writing to our DB. All entries are parsed before being inserted. PAYID is available, and will post it, if necessary.

**Unregistered payment**
Another one of our buyers has paid on the 6th of September (21:02 CEST). The payment was unregistered by us, and registered by PayPal.

This is what we have inside ExecutePayment.php (unimportant bits were redacted):
```PHP
<?php

require __DIR__ . '/../bootstrap.php';
use PayPal\Api\Amount;
use PayPal\Api\Details;
use PayPal\Api\ExecutePayment;
use PayPal\Api\Payment;
use PayPal\Api\PaymentExecution;
use PayPal\Api\Transaction;

// Payment status - everything OK?
if (isset($_GET['success']) && $_GET['success'] == 'true') {

    $paymentId = $_GET['paymentId'];
    $payment = Payment::get($paymentId, $apiContext);

    $execution = new PaymentExecution();
    $execution->setPayerId($_GET['PayerID']);
	
    try {
        // Execute the payment
        $result = $payment->execute($execution, $apiContext);

        $resultInfo = json_decode($result,true);
      
        $paymentID = $resultInfo['id'];
        $parentPayment = $resultInfo['transactions'][0]['related_resources'][0]['sale']['parent_payment'];
        $total = $resultInfo['transactions'][0]['amount']['total'];
        $subtotal = $resultInfo['transactions'][0]['amount']['details']['subtotal'];
        $timePayment = date('d.m.Y. H:i:s', strtotime($resultInfo['update_time']));

        try {
            $payment = Payment::get($paymentId, $apiContext);
        } catch (Exception $ex) {
            // send email with exception details
            // redirect to a predefined location
            header('Location: '.$homeURL);
            exit(1);
        }
    } catch (Exception $ex) {
		// send email with exception details
		// redirect to a predefined location
		header('Location: '.$homeURL);
		exit(1);
    }
    // Everything OK? Insert into DB, check affected rows, then redirect
	header('Location: '.$homeURL);
    exit();

} else {
    // Buyer abandoned the purchase, redirect to a predefined location
    header('Location: '.$homeURL);
    exit;
}
?>
```

**Comment by prakash-gangadharan** [comment]
Hi @randomd00d can you help us with the recent occurrences, if this is still an issue?

**Comment by prakash-gangadharan** [comment]
@randomd00d, can you help us with the recent `PayPal-Debug-ID`  for this issue?
