### ISSUE TITLE
Missing support for application_context

### ISSUE THREAD

**Issue by pscarapicchiajun** [paypal/PayPal-PHP-SDK#1195]
Team,

Can you please add support for application_context (https://developer.paypal.com/docs/api/payments/v1/#definition-application_context) ?
It is mandatory for PayPal Plus BR.

Thanks in advance,

Pedro

**Comment by karms** [comment]
Hi,

I recently came against this issue as well. Good thing is that you can add the application_context without the use of specific classes like so:

`$objPayment = new PayPal\Api\Payment();`
`$objPayment->application_context = new PayPalModel(array("shipping_preference"  => 'SET_PROVIDED_ADDRESS'));`

I agree this should be added to the SDK. It seems other language's SDK also misses these classes.

**Comment by sucithrashanu** [comment]
@pscarapicchiajun @karms 
Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.


Please Check [PayPal Community ](https://www.paypal-community.com) and  [MTS](https://paypal.com/mts)  
Thanks!
