### ISSUE TITLE
Credential not found for default user. Please make sure your configuration/APIContext has credential information

### ISSUE THREAD

**Issue by bichitra12** [paypal/PayPal-PHP-SDK#1196]
An uncaught Exception was encountered
Type: PayPal\Exception\PayPalInvalidCredentialException

Message: Credential not found for default user. Please make sure your configuration/APIContext has credential information

Filename: C:\xampp\htdocs\thecakenew\application\libraries\PayPal-PHP-SDK\paypal\rest-api-sdk-php\lib\PayPal\Core\PayPalCredentialManager.php

Line Number: 139

Backtrace:

File: C:\xampp\htdocs\thecakenew\application\libraries\PayPal-PHP-SDK\paypal\rest-api-sdk-php\lib\PayPal\Rest\ApiContext.php
Line: 56
Function: getCredentialObject

File: C:\xampp\htdocs\thecakenew\application\libraries\PayPal-PHP-SDK\paypal\rest-api-sdk-php\lib\PayPal\Handler\RestHandler.php
Line: 50
Function: getCredential

File: C:\xampp\htdocs\thecakenew\application\libraries\PayPal-PHP-SDK\paypal\rest-api-sdk-php\lib\PayPal\Transport\PayPalRestCall.php
Line: 70
Function: handle

File: C:\xampp\htdocs\thecakenew\application\libraries\PayPal-PHP-SDK\paypal\rest-api-sdk-php\lib\PayPal\Common\PayPalResourceModel.php
Line: 102
Function: execute

File: C:\xampp\htdocs\thecakenew\application\libraries\PayPal-PHP-SDK\paypal\rest-api-sdk-php\lib\PayPal\Api\Payment.php
Line: 564
Function: executeCall

File: C:\xampp\htdocs\thecakenew\application\controllers\Shoppingcart.php
Line: 67
Function: create

File: C:\xampp\htdocs\thecakenew\index.php
Line: 316
Function: require_once

**Comment by prakash-gangadharan** [comment]
Hi @bichitra12, it looks like your question has been answered by @Sebi94nbg  through the above comment. Am closing this issue out and please reopen if you still have any concerns.

Thanks!
