### ISSUE TITLE
sometimes showing  Call to a member function getMessage() on null  in paypal sdk

### ISSUE THREAD

**Issue by bichitra12** [paypal/PayPal-PHP-SDK#1197]
An uncaught Exception was encountered
Type: Error

Message: Call to a member function getMessage() on null

Filename: C:\xampp\htdocs\thecakenew\application\libraries\PayPal-PHP-SDK\paypal\rest-api-sdk-php\sample\common.php

Line Number: 119

**Comment by kedomingo** [comment]
`getMessage()` is a method of `Exception` and the only time this would be null is if you called the `printError()` method in `common.php` manually, without passing this parameter. Can you show the entire trace?

**Comment by bichitra12** [comment]
after i commented this line it is not ging to paypal

**Comment by sucithrashanu** [comment]
@bichitra12 

The function `getMessage` for Display Error message. Check this location:`lib/PayPal/Api/Error.php`

Thanks
