### ISSUE TITLE
Got Http response code 400 when accessing https://api.paypal.com/v1/payments/payment.  in PayPalHttpConnection.php line 202

### ISSUE THREAD

**Issue by loveleopots08** [paypal/PayPal-PHP-SDK#1198]
### General information

* SDK/Library version:  paypal/rest-api-sdk-php": "^1.13" 
* Environment: Live
* Laravel 5.4 , PHP 5.6 on WIN 10

### Issue description

(1/1) PayPalConnectionExceptionGot Http response code 400 when accessing https://api.paypal.com/v1/payments/payment.
--
in PayPalHttpConnection.php line 202
at PayPalHttpConnection->execute('{"intent":"sale","payer":{"payment_method":"paypal"},"redirect_urls":{"return_url":"http://localhost/payrollapp/public/status","cancel_url":"http://localhost/payrollapp/public/status"},"transactions":[{"amount":{"currency":"PHP","total":"1"},"item_list":{"items":[{"name":"Neri Vol 3","currency":"PHP","quantity":2,"price":"1"}]},"description":"Payment description","invoice_number":"5bb437a95ca5f"}]}')in PayPalRestCall.php line 78
at PayPalRestCall->execute(array('PayPal\\Handler\\RestHandler'), '/v1/payments/payment', 'POST', '{"intent":"sale","payer":{"payment_method":"paypal"},"redirect_urls":{"return_url":"http://localhost/payrollapp/public/status","cancel_url":"http://localhost/payrollapp/public/status"},"transactions":[{"amount":{"currency":"PHP","total":"1"},"item_list":{"items":[{"name":"Neri Vol 3","currency":"PHP","quantity":2,"price":"1"}]},"description":"Payment description","invoice_number":"5bb437a95ca5f"}]}', null)in PayPalResourceModel.php line 104
at PayPalResourceModel::executeCall('/v1/payments/payment', 'POST', '{"intent":"sale","payer":{"payment_method":"paypal"},"redirect_urls":{"return_url":"http://localhost/payrollapp/public/status","cancel_url":"http://localhost/payrollapp/public/status"},"transactions":[{"amount":{"currency":"PHP","total":"1"},"item_list":{"items":[{"name":"Neri Vol 3","currency":"PHP","quantity":2,"price":"1"}]},"description":"Payment description","invoice_number":"5bb437a95ca5f"}]}', null, object(ApiContext), null)in Payment.php line 577

at Payment->create(object(ApiContext))
in PaymentController.php line 113

Here's the line in my controller: 
    $payment->create($this->_api_context);

Can someone please hep me with this. Thanks a lot in advance.

**Comment by loveleopots08** [comment]
{"name":"AUTHENTICATION_FAILURE","message":"Authentication failed due to invalid authentication credentials or a missing Authorization header.","links":[{"href":"https://developer.paypal.com/docs/api/overview/#error","rel":"information_link"}]}

**Comment by younkim** [comment]
"Authentication failed due to invalid authentication credentials or a missing Authorization header." 

How are you setting `$this->_api_context`?

**Comment by prakash-gangadharan** [comment]
Hi @loveleopots08, do you still facing this issue?

**Comment by prakash-gangadharan** [comment]
@loveleopots08, if this still an issue, can you help with the recent `PayPal-Debug-ID`
