### ISSUE TITLE
No payment after returning succces on live 

### ISSUE THREAD

**Issue by kaanzgn** [paypal/PayPal-PHP-SDK#1199]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description

I have tested the sandbox mode on my website and everything was working. But then I switched to live and even there was a success payment, no money have been sent to my paypal account. What is the main reason for that, I changed my credintials and mode sandbox->live. The live payment site does opening but no payment have been receiving. Please help!

**Comment by vivekxavie** [comment]
Same issue

**Comment by kaanzgn** [comment]
> Same issue

It looks like i didn't create the execute page which creates the billing and gets the money. You can search for PaymentExecution for paypal and create the page. But the code changed a lot by years so, search for the latest updated codes that github shared on docs.

**Comment by prakash-gangadharan** [comment]
Hi @kaanzgn, yes your are absolutely right that one should execute the payment after buyer approves it.
**Process PayPal Payments**: To create a PayPal payment below are the steps.

- [Define payment](https://developer.paypal.com/docs/api/quickstart/payments/#define-payment)
- [Create payment](https://developer.paypal.com/docs/api/quickstart/payments/#create-payment)
- [Execute payment](https://developer.paypal.com/docs/api/quickstart/payments/#execute-payment)
