### ISSUE TITLE
"PAYMENT.SALE.COMPLETED" webhook event is missing "billing_agreement_id"

### ISSUE THREAD

**Issue by kslimani** [paypal/PayPal-PHP-SDK#1201]
Since 2018-10-19 the "PAYMENT.SALE.COMPLETED" webhook events are missing the "billing_agreement_id" field.

It is an expected feature ? if yes, where can i find info about theses changes ?

**Comment by PhilSwift7** [comment]
it's certainly a bug, reported here too: https://github.com/paypal/PayPal-REST-API-issues/issues/274

**Comment by kslimani** [comment]
Thank you @PhilSwift7 i did not notice this issue repository.

**Comment by Gilbertoespino4213** [comment]
Gilberto Espinoza Velazquez
gilbertoespinozavelazquez@outlook.com
6616627701
Bakersfield CA 93307

**Comment by Gilbertoespino4213** [comment]
Gilberto Espinoza Velazquez
gilbertoespinozavelazquez@outlook.com
6616627701
Bakersfield CA 93307
