### ISSUE TITLE
Missing Instalment files

### ISSUE THREAD

**Issue by osworx** [paypal/PayPal-PHP-SDK#1204]
### General information

* SDK/Library version: 1.13.0
* Environment: Sandbox and Production

### Issue description

Regarding this PR https://github.com/paypal/PayPal-PHP-SDK/pull/732
and the fact that more and more German Customers adding (and using) Instalments, my question:

**when will this be officially added?**

In the meantime, it is a pain to search for all options to create a successful module for Webshops using PayPal and Instalments!

PayPal wants to make profit, but leave us devs alone (in the dark)!

**Comment by sucithrashanu** [comment]
@osworx  
Please check the [PayPal Community](https://www.paypal-community.com) and [MTS](https://paypal.com/mts)

Thanks
