### ISSUE TITLE
Bypass login page? Direct user straight to guest-checkout by default?

### ISSUE THREAD

**Issue by anishthecoder** [paypal/PayPal-PHP-SDK#1208]
Is there a way to configure things so the login option is skipped and the user is directed straight to the guest-checkout by default? I see from some stackoverflow responses that this is possible (https://stackoverflow.com/questions/16755125/paypal-payments-default-to-pay-with-credit-card-instead-of-loggin-in-with-a-p) but wasn't sure if this option can be configured using this library.

**Comment by sucithrashanu** [comment]
@anishthecoder 
Yes its possible to define which page to display as Landing page when user lands on the PayPal site for checkout.
Ref [Link](https://developer.paypal.com/docs/integration/direct/payment-experience/?mark=landing_page#flow-configuration)

Thanks
