### ISSUE TITLE
Executed an AgreementPayPal\Exception\PayPalConnectionException: Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/billing-agreements/EC-85R957913V990661X/agreement-execute

### ISSUE THREAD

**Issue by harshalone** [paypal/PayPal-PHP-SDK#1210]
Hi I have successfully created a billing plan and billing agreement

thats why I received the Token : EC-85R957913V990661X

But when I am running execute agreement its showing me error with code 400

What am I doing wrong? 

Stack trace:
#0 /home/SERVER/public_html/application/libraries/PayPal/vendor/paypal/rest-api-sdk-php/lib/PayPal/Transport/PayPalRestCall.php(78): PayPal\Core\PayPalHttpConnection->execute('')
#1 /home/SERVER/public_html/application/libraries/PayPal/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PayPalResourceModel.php(104): PayPal\Transport\PayPalRestCall->execute(Array, '/v1/payments/bi...', 'POST', '', Array)
#2 /home/SERVER/public_html/application/libraries/PayPal/vendor/paypal/rest-api-sdk-php/lib/PayPal/Api/Agreement.php(413): PayPal\Common\PayPalResourceModel::executeCall('/v1/payments/bi...', 'POST', '', NULL, Object(PayPal\Rest\ApiContext), Object(PayPal\Transport\PayPalRestCall))
#3 /home/SERVER/public_html/application/controllers/Paypal.php(674): PayPal\Api\Agreement->execute('EC-85R957913V99...', Object(PayPal\Rest\ApiContext))
#4 /home/SERVER/public_html/system/core/CodeIgniter.php(532): Paypal->billing_agreement_success()
#5 /home/SERVER/public_html/index.php(321): require_once('/home/SERVER/...')
#6 {main}

**Comment by harshalone** [comment]
I have added some error handling and got to know more about the error:

more error handling: 
```

try {
    $payment->create($apiContext);
} catch (PayPal\Exception\PayPalConnectionException $ex) {
    echo $ex->getCode(); // Prints the Error Code
    echo $ex->getData(); // Prints the detailed error message 
    die($ex);
} catch (Exception $ex) {
    die($ex);
}
```

Return
`
400{"name":"CANNOT_FIND_PROFILE_DESC","message":"Profile description is invalid","information_link":"https://developer.paypal.com/docs/api/payments.billing-agreements#errors","debug_id":"f447fcd42573c"}PayPal\Exception\PayPalConnectionException: Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/billing-agreements/EC-2NJ10952LT437752N/agreement-execute`

**Comment by harshalone** [comment]
if this error means the profile description of Payment Definition or Billing Plan Description

because I have both of them in my request?

**Comment by harshalone** [comment]
I looked into PayPal API here: https://developer.paypal.com/docs/api/payments.billing-agreements/v1/#billing-agreements_create

it says 👍 
CANNOT_FIND_PROFILE_DESC
The profile description is not valid. Provide a valid agreement description.

**Comment by harshalone** [comment]
Finally I resolved the issue. The documentation of PayPal SDK is bad.

Basically, CANNOT_FIND_PROFILE_DESC means Your Billing Plan Description and your Agreement description should be exactly same

**Comment by prakash-gangadharan** [comment]
Hi @harshalone,  hope you resolved your issue through Developer API Reference link, if you still facing any blocks please revert us back.
