### ISSUE TITLE
Client Authentication Error

### ISSUE THREAD

**Issue by AruldassD** [paypal/PayPal-PHP-SDK#1211]
When i used live api credentials from paypal account it seems client authentication failed error , can someone help me to solve this issue ...

{"error":"invalid_client","error_description":"Client Authentication failed"}

**Comment by jaypatel512** [comment]
I would recommend following the instructions here https://github.com/paypal/PayPal-PHP-SDK/wiki/Going-Live

This should allow you to start taking payments in live.
