### ISSUE TITLE
introduce getBusinessName fro PayerInfo

### ISSUE THREAD

**Issue by andrewtch** [paypal/PayPal-PHP-SDK#1213]
### General information

* SDK/Library version: 1.13
* Environment: both
* `PayPal-Debug-ID` values: none
* Language, language version, and OS: php 7.2

### Issue description

business_name of PayerInfo is not accessible via getter methods. There is no getBusinessName in PayerInfo, but the key is present in ->toArray() result and in the _props if payment is made from business account.

**Comment by sucithrashanu** [comment]
@andrewtch 

Do you still see this instances of this issue around? if yes please share us the recent PayPal-Debug-IDs to check further.

Thanks
