### ISSUE TITLE
Create BillingAgreementToken

### ISSUE THREAD

**Issue by msznaper** [paypal/PayPal-PHP-SDK#1215]
### General information

* SDK/Library version: 1.13
* Environment: Sandbox
* Language, language version, and OS: PHP 7.2

### Issue description
How do I generate agreement token? since in the sdk I can not find the function that calls the endpoin: /v1/billing-agreement/agreement-tokens

**Comment by younkim** [comment]
`Agreement::create` is the function you're looking for. It has a lot of dependencies you'll have to construct and set, but it's self-explanatory once you read through the code.

**Comment by msznaper** [comment]
Thanks, try using Agreements: create, but it is useful to create a billingAgreements not a billingAgreementsToken that belongs to the REFERENCE TRANSACTION: https://developer.paypal.com/docs/limited-release/reference-transactions/#create-billing-agreement -token

**Comment by sucithrashanu** [comment]
@msznaper 
[Link 
](https://developer.paypal.com/docs/limited-release/reference-transactions/#create-billing-agreement) is  a correct reference. 

Thanks

**Comment by prakash-gangadharan** [comment]
Hi @msznaper,currently PayPal-PHP-SDK does not support the end point /v1/billing-agreement/agreement-tokens which used to create REFERENCE TRANSACTION. It is not implement yet. It may be available in near future.
