### ISSUE TITLE
Sandbox was working now, every call results in a "Http response code 401"

### ISSUE THREAD

**Issue by lassade** [paypal/PayPal-PHP-SDK#1216]
### General information

* SDK/Library version: paypal/rest-api-sdk-php 1.13 with laravel 5.7
* Environment: Sandbox
* `PayPal-Debug-ID` values: d3e2276984a8d, 3575b897aae79, 81de2ff759029
* Language, language version, and OS: PHP  Ubuntu 18

### Issue description

After getting both my user experience and payment working. I was trying to remove the shipping address field and enable guest payments, but before I can do anything the paypal sandbox started to recuse all my calls, returning 401 for when I try to create a new temp profile experience, and 403 for the payments.

Not sure what is going on.

**Comment by lassade** [comment]
Well turn out I acidentatly unchecked the **Accept payments** in app features, after a few minutes all my calls get back working.

Not sure if this was the fix, so I'm going to leave the issue open in case problem turn backs.

**Comment by jaypatel512** [comment]
It is infact the fix. 401 means you are unauthorized, as you disabled Accept Payments. The solution you presented in your second comment is the right thing to do.
