### ISSUE TITLE
Webhooks - Receiving PAYMENT.SALE.COMPLETED twice for a monthly billing

### ISSUE THREAD

**Issue by razorsharpshady** [paypal/PayPal-PHP-SDK#1217]
Environment: Production
Webhook triggered **twice** for **PAYMENT.SALE.COMPLETED** event only for Monthly Payment for a subscriber,
If a **one time payment** is made the Webhook is triggered only once.
below are both webhooks responses received for the recurring payment
![both-webhooks](https://user-images.githubusercontent.com/20279966/49632475-df2b0680-fa1b-11e8-8671-69bde172eceb.png)

one has "invoice_number" key inside **resource** but in the other one it's missing.

and I've checked in the paypal account, only one webhook is registered for the **PAYMENT.SALE.COMPLETED** event.

**Comment by fatrbaby** [comment]
Hello, I have encountered the same problem. Can you solve this problem?

**Comment by razorsharpshady** [comment]
@fatrbaby
so what I did was made a table with webhook_id field. 
so whenever I recieve a webhook system checks if the webhook_id is already there or not if it's there then just ignore it otherwise complete your process and insert the webhook_id in the table. will that work for you?

**Comment by fatrbaby** [comment]
@razorsharpshady Thank you very much. I am also planning to use a similar method to deal with this problem.

**Comment by Sebi94nbg** [comment]
Identical / Related issue: #1286

**Comment by prakash-gangadharan** [comment]
Reference Comment : https://github.com/paypal/PayPal-PHP-SDK/issues/1286#issuecomment-524222300
