### ISSUE TITLE
Logging is not working

### ISSUE THREAD

**Issue by patrick-hintermayer** [paypal/PayPal-PHP-SDK#1218]
### General information

* SDK/Library version: 1.13
* Environment: Sandbox
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: PHP 7.2, Ubuntu 16.04

### Issue description
As described here https://github.com/paypal/PayPal-PHP-SDK/wiki/Logging I have a config file with log.LogEnabled which is `true`, log.FileName which I tried with several paths including absolute and relative paths and log.LogLevel which is "DEBUG".
I pass this config to ApiContext via setConfig method.

Unfortunately no log file is created when I authorize or capture a payment.

**Comment by jaypatel512** [comment]
If you can see in our sample code [setup](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/bootstrap.php#L84), we have enabled Logging.

If you can follow the instructions [here](https://github.com/paypal/PayPal-PHP-SDK/tree/master/sample) to setup sample in your local machine and try to run a sample, and see if you are seeing the log file. If so, I think you must be something you are missing on your end.
