### ISSUE TITLE
Free trial and subscription issue

### ISSUE THREAD

**Issue by AndManowar** [paypal/PayPal-PHP-SDK#1219]
Hello. I need to do such feature as free 7-days trial period and then monthly or yearly subscription.
!!!Important(first payment must be done only after the trial period)

I have such settings as:

For trial and monthly subscription:

    [_propMap:PayPal\Common\PayPalModel:private] => Array
    (
        [name] => Standard
        [description] => Monthly Plan
        [type] => INFINITE
        [payment_definitions] => Array
            (
                [0] => PayPal\Api\PaymentDefinition Object
                    (
                        [_propMap:PayPal\Common\PayPalModel:private] => Array
                            (
                                [name] => InstaSky Suscription Trial
                                [type] => TRIAL
                                [cycles] => 1
                                [frequency] => WEEK
                                [frequency_interval] => 1
                                [amount] => PayPal\Api\Currency Object
                                    (
                                        [_propMap:PayPal\Common\PayPalModel:private] => Array
                                            (
                                                [value] => 0
                                                [currency] => USD
                                            )

                                    )

                            )

                    )

                [1] => PayPal\Api\PaymentDefinition Object
                    (
                        [_propMap:PayPal\Common\PayPalModel:private] => Array
                            (
                                [name] => InstaSky Suscription
                                [type] => REGULAR
                                [frequency] => MONTH
                                [frequency_interval] => 1
                                [amount] => PayPal\Api\Currency Object
                                    (
                                        [_propMap:PayPal\Common\PayPalModel:private] => Array
                                            (
                                                [value] => 39.00
                                                [currency] => USD
                                            )
                                    )
                            )
                    )
            )

For trial and year subscription:

    [_propMap:PayPal\Common\PayPalModel:private] => Array
    (
        [name] => Standard
        [description] => Monthly Plan
        [type] => INFINITE
        [payment_definitions] => Array
            (
                [0] => PayPal\Api\PaymentDefinition Object
                    (
                        [_propMap:PayPal\Common\PayPalModel:private] => Array
                            (
                                [name] => InstaSky Suscription Trial
                                [type] => TRIAL
                                [cycles] => 1
                                [frequency] => WEEK
                                [frequency_interval] => 1
                                [amount] => PayPal\Api\Currency Object
                                    (
                                        [_propMap:PayPal\Common\PayPalModel:private] => Array
                                            (
                                                [value] => 0
                                                [currency] => USD
                                            )

                                    )

                            )

                    )

                [1] => PayPal\Api\PaymentDefinition Object
                    (
                        [_propMap:PayPal\Common\PayPalModel:private] => Array
                            (
                                [name] => InstaSky Suscription
                                [type] => REGULAR
                                [frequency] => YEAR
                                [frequency_interval] => 1
                                [amount] => PayPal\Api\Currency Object
                                    (
                                        [_propMap:PayPal\Common\PayPalModel:private] => Array
                                            (
                                                [value] => 399.00
                                                [currency] => USD
                                            )

                                    )

                            )

                    )

            )

Am I right?

**Comment by lazareff** [comment]
Hi. Did you manage to make a trial period? Do you have an example of creating a trial period and further withdrawals?

**Comment by sucithrashanu** [comment]
@AndManowar 

Yes Your JSON creation for trail and (monthly/yearly)  subscription correct one.
Check the [BillingPlansFunctionalTestJSON](https://github.com/paypal/PayPal-PHP-SDK/blob/ff2a7f9c2ddc47a22cb7bb8a5b0bb97bd16bdd6f/tests/PayPal/Test/Functional/resources/BillingPlansFunctionalTest/testCreate.json)

Thanks
