### ISSUE TITLE
Billing Plans : i'm lost in the docs...

### ISSUE THREAD

**Issue by guldil** [paypal/PayPal-PHP-SDK#1222]
Hy,

One day i read all the doc, i googe a lot, and i can't understand how it's supposed to work.

I just want to charge a paypal account of what i want after he gave me an agreement ?

Is it possible ?

I found this :

https://developer.paypal.com/docs/subscriptions/#billing-plans

> After you activate a billing plan, you can create one or more billing agreements, or actual subscriptions, that you base on the plan. A billing agreement allows a merchant to charge a buyer's PayPal account when they purchase goods from them or use their service. An example of this would be an agreement to pay seller fees for listing items on an online store.

My merchant is selling ebooks (with preorder) and i want one clic payment without asking again for paypal payment.

I check my personnal Paypal account, looks like Spotify or Blizzard doing this very well...

Please help me :)

Guldil

**Comment by prakash-gangadharan** [comment]
Hi @guldil, if you are trying to integrate with the paypal resk sdk, can you take a look at the below links

- [Process PayPal Payments ](https://developer.paypal.com/docs/api/quickstart/payments/)

Use _billing plans_ and _billing agreements_ to create an agreement for a recurring PayPal payment for goods or services.

- [Create Billing Plans ](https://developer.paypal.com/docs/api/quickstart/create-billing-plan/)
- [Create Billing Agreements](https://developer.paypal.com/docs/api/quickstart/create-billing-agreement/)
