### ISSUE TITLE
GetBillingAgreement function getId() error

### ISSUE THREAD

**Issue by miguelurtado** [paypal/PayPal-PHP-SDK#1223]
### General information

* SDK/Library version: 1.3.0
* Environment: Sandbox 
* Language, language version, and OS: PHP Version 7.2.4 Windows NT DESKTOP 10.0 build 17134 (Windows 10) i586

### Issue description

Fatal error: Uncaught Error: Call to a member function getId() on string in C:\xampp\htdocs\payrest\billing\GetBillingAgreement.php:17 Stack trace: #0 {main} thrown in C:\xampp\htdocs\payrest\billing\GetBillingAgreement.php on line 17

File error - https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/billing/GetBillingAgreement.php

**Comment by jaypatel512** [comment]
Hey @miguelurtado !

I think the comment in our sample page is confusing. What it expects is a BillingAgreementObject with Id set in it. It should be something like this:

```
/** @var Agreement $createdAgreement */
$createdAgreement = // your agreement object with Id set.
```

I will close this for now, but feel free to re-open if that does not solve the problem.
I will go ahead and update the sample.
