### ISSUE TITLE
Paypal: Invalid Plan Id

### ISSUE THREAD

**Issue by iabdullahshahid** [paypal/PayPal-PHP-SDK#1230]
I am using membership payment from paypal on Laravel 5.5 I am using the following link to integrate paypal in Laravel

> https://devdojo.com/tutorials/using-paypal-in-your-laravel-app
I am adding my function here:

`public function paypalRedirect($planID){
        $response = array();
        $this->plan_id = $planID;
        // Create new agreement
        $agreement = new Agreement();
        $agreement->setName('Vechflow Monthly Subscription Agreement')
        ->setDescription('Basic Subscription')
        ->setStartDate(\Carbon\Carbon::now()->addMinutes(5)->toIso8601String());

        // Set plan id
        $plan = new Plan();
        $plan->setId($this->plan_id);
        $agreement->setPlan($plan);
        // Add payer type
        $payer = new Payer();
        $payer->setPaymentMethod('paypal');
        $agreement->setPayer($payer);

        try {
          // Create agreement
          $agreement = $agreement->create($this->apiContext);
          // Extract approval URL to redirect user
          $approvalUrl = $agreement->getApprovalLink();
          $response['status_code'] = 200; 
          $response['url'] = $approvalUrl;
          return $response;
      } catch (PayPal\Exception\PayPalConnectionException $ex) {
          $response['status_code'] = 500; 
          $response['error'] = $ex;
          return $response;
      } catch (Exception $ex) {
          $response['status_code'] = 500; 
          $response['error'] = $ex;
          return $response;
      }
}`

Till here it works great and return agreement correctly but after this when we execute agreement it throws an exception which show the following error after debugging

`{"name":"TEMPLATE_ID_INVALID","details":[{"field":"template id is invalid","issue":"Incorrect Plan Id."}],"message":"","information_link":"https://developer.paypal.com/docs/api/payments.billing-agreements#errors","debug_id":"4afbcfb5dd18a"}`

**Comment by prakash-gangadharan** [comment]
Hi @iabdullahshahid, use **billing plans** and **billing agreements** to create an agreement for a recurring PayPal payment for goods or services.

- [Create Billing Plans  ](https://developer.paypal.com/docs/api/quickstart/create-billing-plan/#define-the-billing-plan-object)
- [Create Billing Agreements ](https://developer.paypal.com/docs/api/quickstart/create-billing-agreement/#)

Please refer the above link to create a billing plan and revert us back if you are still facing any challenges.
