### ISSUE TITLE
Setting payer_info triggers MALFORMED_REQUEST

### ISSUE THREAD

**Issue by Androbin** [paypal/PayPal-PHP-SDK#1231]
### General information

* SDK/Library version: `1.14.0`
* Environment: `sandbox`
* `PayPal-Debug-ID` values: `7ba43f88b9b45`
* Language, language version: `PHP 7.3`

### Issue description

I have tested this with the [`CreatePaymentUsingPayPal`](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/CreatePaymentUsingPayPal.php) example code and the following change:
```
$payerInfo = new PayerInfo();
$payerInfo->setCountryCode("US");

$payer = new Payer();
$payer->setPaymentMethod("paypal")
      ->setPayerInfo($payerInfo);
```
This triggers the following error:
```
{
  "name": "MALFORMED_REQUEST",
  "message": "Incoming JSON request does not map to API request",
  "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#MALFORMED_REQUEST",
  "debug_id": "7ba43f88b9b45"
}
```
Maybe it's an REST API issue, I can't really tell.

**Comment by deepakmaurya** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done

<hr>

**Worker have applied to start work.**

Below user(s) claimed they can complete the work within defined time period.

Please review their action plans below:

**1) <a href='https://sandbox.gitworkdone.com/profile/drewbuyer'>drewbuyer</a> has applied to start work. (Funders only: <a href='https://sandbox.gitworkdone.com/issue/payer-info-settings-adjustment?action=approve&worker=drewbuyer'>approve worker</a> | <a href='https://sandbox.gitworkdone.com/issue/payer-info-settings-adjustment?action=reject&worker=drewbuyer'>reject worker</a>)**
                
**Message:** I would like to start this work please!




<a href='https://sandbox.gitworkdone.com/issue/payer-info-settings-adjustment'>Click Here to view more</a> on GitWorkDone Bounty detail page.

**Comment by deepakmaurya** [comment]
Issue Status: 1. Open 2. **Started**  3. Submitted 4. Done

<hr>

**Work has been started.**

**<a href='https://sandbox.gitworkdone.com/profile/drewbuyer'>drewbuyer</a> has been approved to start work.**

<hr />

**Message:** Sure, go ahead and "git" started!  :)


<a href='https://sandbox.gitworkdone.com/issue/payer-info-settings-adjustment'>Click Here to view more</a> on GitWorkDone Bounty detail page.

**Comment by deepakmaurya** [comment]
**<a href='https://sandbox.gitworkdone.com/profile/angelleye'>https://sandbox.gitworkdone.com/profile/drewbuyer</a> Work has been approved by <a href='drewbuyer'>angelleye</a>.**
<hr />

**Message:** Thanks for doing a good job!


<a href='https://sandbox.gitworkdone.com/issue/payer-info-settings-adjustment'>Click Here to view more</a> on GitWorkDone Bounty detail page.

**Comment by sucithrashanu** [comment]
@Androbin 
Try this below code snippnet: for payment via paypal.


/ 3. Lets try to create a Payment
// https://developer.paypal.com/docs/api/payments/#payment_create
$payer = new \PayPal\Api\Payer();
$payer->setPaymentMethod('paypal');

$amount = new \PayPal\Api\Amount();
$amount->setTotal('1.00');
$amount->setCurrency('USD');

$transaction = new \PayPal\Api\Transaction();
$transaction->setAmount($amount);

$redirectUrls = new \PayPal\Api\RedirectUrls();
$redirectUrls->setReturnUrl("https://example.com/your_redirect_url.html")
    ->setCancelUrl("https://example.com/your_cancel_url.html");

$payment = new \PayPal\Api\Payment();
$payment->setIntent('sale')
    ->setPayer($payer)
    ->setTransactions(array($transaction))
    ->setRedirectUrls($redirectUrls);

// 4. Make a Create Call and print the values
try {
    $payment->create($apiContext);
    echo $payment;

    echo "\n\nRedirect user to approval_url: " . $payment->getApprovalLink() . "\n";
}
catch (\PayPal\Exception\PayPalConnectionException $ex) {
    // This will print the detailed information on the exception.
    //REALLY HELPFUL FOR DEBUGGING
    echo $ex->getData();
} 


Thanks

**Comment by Androbin** [comment]
@sucithrashanu The example code works fine and my use case is covered. I opened this ticket because the `setPayerInfo` function does not work but should. Your comment is irrelevant for this issue.

**Comment by sucithrashanu** [comment]
@Androbin 
Sorry for the inconvenience. Let me check and get back.

Thanks

**Comment by sucithrashanu** [comment]
Hi @Androbin, please refer to the Developer API Reference link for [[Create payment](https://developer.paypal.com/docs/api/payments/v1/#payment_create) ]

The [[payer_info](https://developer.paypal.com/docs/api/payments/v1/#definition-payer_info)] object does not have country_code parameter.

Hence it is throwing the below error when we set $payerInfo->setCountryCode("US");
**Error:**
{"name":"MALFORMED_REQUEST","message":"Incoming JSON request does not map to API request","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#MALFORMED_REQUEST","debug_id":"981e2689ccb05"}
PayPal\Exception\PayPalConnectionException: Got Http response code 400 when accessing [Payment API link](https://api.sandbox.paypal.com/v1/payments/payment)

Thanks

**Comment by Androbin** [comment]
@sucithrashanu Then why does the SDK have that `setCountryCode` function?

**Comment by prakash-gangadharan** [comment]
@Androbin  `country_code` is one of the [Common object definitions ](https://developer.paypal.com/docs/api/payments/v1/#definitions)
The API request payload should be in line with the Developer API Reference.

And [Create payment](https://developer.paypal.com/docs/api/payments/v1/#payment_create) API doc clearly says, the [payer_info](https://developer.paypal.com/docs/api/payments/v1/#definition-payer_info) object does not have country_code parameter.

$payerInfo->setCountryCode("**") might applicable for other use cases like PATCH payment call.
