### ISSUE TITLE
How to store credit card info or result it with Payflow?

### ISSUE THREAD

**Issue by psilvaleo** [paypal/PayPal-PHP-SDK#1232]
I am using SaleTransaction. 

So far i could test it locally and I realize that if I saved:

var resp = trans.SubmitTransaction();
resp.RequestId and resp.TransactionResponse.Pnref 
I can create another SaleTransaction without passing the credit card info. 
But I am not sure for how long my request id and pnref are good for? 

Do we have an option to use something like Vault or credit card token as we have on Paypal.api? 
but on paypal.payments?

**Comment by prakash-gangadharan** [comment]
Hi @psilvaleo, this is more like the question which is regarding the Payflow Product. Please refer the below link for merchant technical support.
https://www.paypal.com/in/smarthelp/article/how-do-i-get-merchant-technical-support,-such-as-for-paypal-product-integrations,-apis-or-sandbox-testing-faq3723

Please visit [Merchant Technical Support](https://www.paypal-techsupport.com/app/) and submit your question for merchant/developer technical support, such as for PayPal product integrations/APIs

Thanks!
