### ISSUE TITLE
Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payment

### ISSUE THREAD

**Issue by neeraj24a** [paypal/PayPal-PHP-SDK#1233]
### General information

* SDK/Library version: 1.14.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: 2d3eb639a9398
* Language, language version, and OS: PHP 7 on Ubuntu

I have added my JSON and error response below

PayPal\Api\Payment Object
(
    [_propMap:PayPal\Common\PayPalModel:private] => Array
        (
            [intent] => order
            [payer] => PayPal\Api\Payer Object
                (
                    [_propMap:PayPal\Common\PayPalModel:private] => Array
                        (
                            [payment_method] => paypal
                        )

                )

            [redirect_urls] => PayPal\Api\RedirectUrls Object
                (
                    [_propMap:PayPal\Common\PayPalModel:private] => Array
                        (
                            [return_url] => https://www.8thwonderpromos.com/test/cart/transact?success=true
                            [cancel_url] => https://www.8thwonderpromos.com/test/cart/transact?success=false
                        )

                )

            [transactions] => Array
                (
                    [0] => PayPal\Api\Transaction Object
                        (
                            [_propMap:PayPal\Common\PayPalModel:private] => Array
                                (
                                    [amount] => PayPal\Api\Amount Object
                                        (
                                            [_propMap:PayPal\Common\PayPalModel:private] => Array
                                                (
                                                    [currency] => USD
                                                    [total] => 22.50
                                                    [details] => PayPal\Api\Details Object
                                                        (
                                                            [_propMap:PayPal\Common\PayPalModel:private] => Array
                                                                (
                                                                    [shipping] => 5.00
                                                                    [subtotal] => 17.50
                                                                )

                                                        )

                                                )

                                        )

                                    [item_list] => PayPal\Api\ItemList Object
                                        (
                                            [_propMap:PayPal\Common\PayPalModel:private] => Array
                                                (
                                                    [items] => Array
                                                        (
                                                            [0] => Array
                                                                (
                                                                    [0] => PayPal\Api\Item Object
                                                                        (
                                                                            [_propMap:PayPal\Common\PayPalModel:private] => Array
                                                                                (
                                                                                    [name] => 8th Wonder Logo Tee
                                                                                    [currency] => USD
                                                                                    [quantity] => 1
                                                                                    [price] => 25.00
                                                                                )

                                                                        )

                                                                )

                                                        )

                                                    [shipping_address] => PayPal\Api\ShippingAddress Object
                                                        (
                                                            [_propMap:PayPal\Common\PayPalModel:private] => Array
                                                                (
                                                                    [city] => SCARSDALE
                                                                    [country_code] => US
                                                                    [postal_code] => 10583
                                                                    [line1] => 10 WILDWAY 
                                                                    [state] => NY
                                                                    [recipient_name] => Neeraj Kumar
                                                                )

                                                        )

                                                )

                                        )

                                    [description] => Payment description
                                    [invoice_number] => 5c463659a3786
                                )

                        )

                )

        )

)
Exception: Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payment.
Array
(
    [name] => MALFORMED_REQUEST
    [message] => Incoming JSON request does not map to API request
    [information_link] => https://developer.paypal.com/webapps/developer/docs/api/#MALFORMED_REQUEST
    [debug_id] => 9578fa5780362
)
Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payment.400{"name":"MALFORMED_REQUEST","message":"Incoming JSON request does not map to API request","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#MALFORMED_REQUEST","debug_id":"9578fa5780362"}

My Code is for creating an order below

$apiContext->setConfig(array(
			'mode' =>'sandbox',
			'service.EndPoint' => 'https://api.sandbox.paypal.com',
			'http.ConnectionTimeOut' => 30,
			'log.LogEnabled' => true,
			'log.FileName' => __DIR__ . '/../../PayPal.log',
			'log.LogLevel' => 'FINE',
		));
		
		$shipping_address = new ShippingAddress();

		$shipping_address->setCity($shipping['city']);
		$shipping_address->setCountryCode('US');
		$shipping_address->setPostalCode($shipping['zip']);
		$shipping_address->setLine1($shipping['address_line_1'].' '.$shipping['address_line_2']);
		$shipping_address->setState($shipping['state']);
		$shipping_address->setRecipientName($shipping['first_name'].' '.$shipping['last_name']);
        
		$payer = new Payer();
		$payer->setPaymentMethod("paypal");
		
		$items = [];
        if(isset($products['shop'])){
            foreach($products['shop'] as $shop){
				$item = new Item();
				$item->setName($shop->name)
					->setCurrency('USD')
					->setQuantity($shop->quantity)
					->setPrice(number_format($shop->unit_price,2));
                array_push($items, $item);
            }
        }
		$item = new Item();
		$item->setName('Discount')
			->setCurrency('USD')
			->setQuantity(1)
			->setPrice('-'.$offerAmount);
		
		array_push($items, $item);
		
		$itemList = new ItemList();
		$itemList->setItems(array($items));
        $itemList->setShippingAddress($shipping_address);
		$details = new Details();
		$details->setShipping($shipping_cost)
			->setSubtotal($totalWithOffer);
		
		$amount = new Amount();
		$amount->setCurrency("USD")
				->setTotal(number_format($sub_total,2))
				->setDetails($details);
		
		$transaction = new Transaction();
		$transaction->setAmount($amount)
					->setItemList($itemList)
					->setDescription("Payment description")
					->setInvoiceNumber(uniqid());
		
		$baseUrl = domainUrl();
		$redirectUrls = new RedirectUrls();
		$redirectUrls->setReturnUrl("$baseUrl/cart/transact?success=true")
					->setCancelUrl("$baseUrl/cart/transact?success=false");
		
		$payment = new Payment();
		$payment->setIntent("order")
				->setPayer($payer)
				->setRedirectUrls($redirectUrls)
				->setTransactions(array($transaction));
		$request = clone $payment;

Please help me out what's wrong in my code.

Thanks

**Comment by russek66** [comment]
```
$itemList->setItems($items);
```

**Comment by sucithrashanu** [comment]
@neeraj24a 
Can you share the recent PayPal-Debug-IDs to check further?

Thanks
