### ISSUE TITLE
Refund PENDING after refundCapturedPayment

### ISSUE THREAD

**Issue by claudioshiver** [paypal/PayPal-PHP-SDK#1235]
* SDK/Library version: 1.13.0
* Environment: Sandbox
* Language, language version, and OS: PHP 7.2.9-1+ubuntu18.04.1

After capture of an authorized payment I tried to make a refundCapturedPayment as described [here](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/RefundCapture.php)  and I have not received any errors but the refund remains pending as you can see on the image.

Please help me!

![schermata 2019-01-24 alle 17 57 17 min](https://user-images.githubusercontent.com/8624947/51695434-56841c00-2003-11e9-88d8-c7351a797ae6.png)

**Comment by prakash-gangadharan** [comment]
Hi @claudioshiver, do you have any recent occurrence, if yes please help us with the capture id and the refund txn id.

**Comment by prakash-gangadharan** [comment]
Hi @claudioshiver, is this still an issue?
