### ISSUE TITLE
Is direct credit card payments possible with REST API for Website Payments Pro account for UK merchants?

### ISSUE THREAD

**Issue by punramesh** [paypal/PayPal-PHP-SDK#1236]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description

> **Important:** The PayPal REST API no longer supports new direct credit card integrations. Please instead consider Braintree Direct; which is, PayPal's preferred integration solution for accepting direct credit card payments in your mobile app or website. Braintree, a PayPal service, is the easiest way to accept credit cards, PayPal, and many other payment methods.

Is the above statement still valid for Website Payments Pro business account for UK as well? If it's still valid, can I process the direct credit card by using Merchant PHP SDK https://github.com/paypal/merchant-sdk-php?

**Comment by sucithrashanu** [comment]
@punramesh 
Please refer the below link for merchant technical support. 
[https://www.paypal.com/in/smarthelp/article/how-do-i-get-merchant-technical-support,-such-as-for-paypal-product-integrations,-apis-or-sandbox-testing-faq3723](https://www.paypal.com/in/smarthelp/article/how-do-i-get-merchant-technical-support,-such-as-for-paypal-product-integrations,-apis-or-sandbox-testing-faq3723)

Please visit [Merchant Technical Support](https://www.paypal-techsupport.com/app/) and submit your question for merchant/developer technical support, such as for PayPal product integrations/APIs
Thanks!
