### ISSUE TITLE
VALIDATION_ERROR field payment

### ISSUE THREAD

**Issue by GAngZta** [paypal/PayPal-PHP-SDK#1237]
### General information

* SDK/Library version: 1.13
* Environment: Live
* `PayPal-Debug-ID` values: 80ed2a3c821c5, ce8d7ad183dbe, 66fd06f4f2d4a, ad65220d72270, 491f19f191977, 2074db44bf779
* Language, language version, and OS: PHP 7.2.8; Apache/2.4.34; Ubuntu 16.04.5

### Issue description

We get this error on several payments:

> Got Http response code 400 when accessing
> https://api.paypal.com/v1/payments/payment.
>     '{"name":"VALIDATION_ERROR","details":[{"field":"payment","issue":"Value
> is invalid."}],"message":"Invalid request.  See
> details.","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"80ed2a3c821c5"}'

Since weeks we are logging the data we are preparing for the sdk (amounts, items, shipping address) and also the data what is transferred to paypal (amounts, items, ...). But all is ok. All amounts are calculated correct and all fields are complete.

Here is the code snippet how we use it

```
$oPayer = new Payer();
$oPayer->setPaymentMethod('paypal');

$aItems = $this->createItems();

$oItemList = new ItemList();
$oItemList->setShippingAddress($this->createShippingAddress());
$oItemList->setItems($aItems);

$oDetails = new Details();
$oDetails->setShipping($this->getShipping());
$oDetails->setTax(0);
$oDetails->setSubtotal($this->getAmountSub());

$oAmount = new Amount();
$oAmount->setCurrency("EUR")
    ->setTotal($this->getAmountTotal())
    ->setDetails($oDetails);

$oTransaction = new Transaction();
$oTransaction->setAmount($oAmount)->setItemList($oItemList)->setDescription($sOrderText)->setInvoiceNumber($iOrderId);

$oRedirect = new RedirectUrls();
$oRedirect->setReturnUrl($this->getSuccessUrl())->setCancelUrl($this->getCancelUrl());

$oPayment = new Payment();
$oPayment->setIntent('sale')
    ->setPayer($oPayer)
    ->setRedirectUrls($oRedirect)
    ->setTransactions([$oTransaction]);

// log data ...
$this->aDebugData['AmountTotal']     = $this->getAmountTotal();
$this->aDebugData['TransactionDesc'] = $sOrderText;
$this->aDebugData['InvoiceNumber']   = $iOrderId;
$this->aDebugData[]                  = '======================';
$this->aDebugData['paypal-api']      = $oPayment->toArray(); // paypal sdk debug data

try {
    try {
        $this->Payment()->setDebugData($this->aDebugData);
    } catch (Exception $e) {}

    $oPayment->create($this->getApiContext());
} catch (PayPal\Exception\PayPalConnectionException $e) {
    // .....        
}
```

**Comment by russek66** [comment]
code looks good so idk, maybe do some tests under sandbox with hard coded values to find where is problem

**Comment by GAngZta** [comment]
I found the solution.
Before I passed the item title I cut the string (utf8) with substr(). 
Here is the problem. If the string is cutted on an umlaut or other multibyte char, the char was damaged and at the end of a string was a unrecognized character. 
mb_substr() solved it
