### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by liedekef** [paypal/PayPal-PHP-SDK#1239]
I have some issues with the doc and examples, so I hope this might help in improving ... and also answer some questions:
1) Based on https://github.com/paypal/PayPal-PHP-SDK/wiki/Making-First-Call , you should use autoload.php and namespaced functions (very good), but the referenced examples (http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/CreatePaymentUsingPayPal.html for exxample), don't do that. Neither the examples at https://github.com/paypal/PayPal-PHP-SDK/tree/master/sample/payments ... some consistency is needed here.
2) The logic of approving a payment (direct payment) and then executing it is nice at first, but:
- why should anyone be able to change the amount *after* someone approved the payment? Does this not void the approval? It is indicated the amount is optional, but still weird: https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/ExecutePayment.php
- When executing the payment (at https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/ExecutePayment.php or https://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/ExecutePayment.html), why is nothing being done with $result? What is in there? The doc is very lacking at that point ...
3) I used to use IPN for payment handling of bookings, but using the approval+execute: do I really need to start using webhooks? Or can I assume a payment is actually finished after the execute call?

Hoping to get some feedback :-)

**Comment by russek66** [comment]
$result contains every info about transaction, var_dump it to check it out.
for example I load it into $data array:
```
$data = [
	'txn_id' => $result->transactions[0]->related_resources[0]->sale->id,
	'total' => $result->transactions[0]->amount->total,
	'payment_status' => $result->transactions[0]->related_resources[0]->sale->state,
	'buyer_email' => $result->payer->payer_info->email,
];
```

I would go for webhooks, I guess IPN will be deprecated, not anytime soon but in few years.
I am using webhook + return URL validation to display data right after payment, it is just less messy compared to IPN for me. 

I can't tell you much more since I am struggling with it myself, oh wait
if you are going to use webhook [like here](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/notifications/ValidateWebhookEvent.php) you will be checking signature verification status:
```
$output = $signatureVerification->post($apiContext);
$status = $output->getVerificationStatus(); // 'SUCCESS' or 'FAILURE'
```
all I could find was to check if it is "success" but what I found out during tests it can return

- success
- completed
- denied
- none

I am waiting few days already to get response from PP support which one should I check.

Later on you want to check status of payment ofc. AFTER you verify signature, you can do it like that:
```
$paymentData = json_decode($requestBody);
	switch($paymentData->event_type){
		case 'PAYMENT.AUTHORIZATION.CREATED':
			// A payment authorization is created, approved, executed, or a future payment authorization is created.
		case 'PAYMENT.AUTHORIZATION.VOIDED':
			// A payment authorization is voided.
		case 'PAYMENT.SALE.PENDING':
			// The state of a sale changes to pending.
		case 'PAYMENT.SALE.DENIED':
			// The state of a sale changes from pending to denied.
		case 'PAYMENT.SALE.REFUNDED':
			// A merchant refunds a sale.
		case 'PAYMENT.SALE.REVERSED	':
			// PayPal reverses a sale.
		case 'PAYMENT.SALE.COMPLETED':
			// A sale completes.
			if(strtoupper($paymentData->resource->state) !== 'SUCCESS') {
				// log error + throw exception
			}
 			// do you stuff
		case ("RISK.DISPUTE.CREATED" || "CUSTOMER.DISPUTE.CREATED"):
			// A customer dispute is created.
		case "CUSTOMER.DISPUTE.UPDATED":
			// A customer dispute is updated.
		case "CUSTOMER.DISPUTE.RESOLVED":
			// A customer dispute is resolved.
	}
```

Regarding webhook "A webhook is fired when the payment is completed, the buyer does not need to be returned to the return URL in order for the webhook to be fired." that is what I got when asked when it is fired.

**Comment by liedekef** [comment]
Thanks for this, but based on the fact that I need to "execute" an "approved" payment: why would a webhook still be needed? Immediately after the execute, the payment is either done or not (again: only for direct payment), no?
Also the doc on webhooks is still lacking info: should I create a new webhook everytime via the api, or first check if a webhook already exists (and why should that be needed: via IPN I did exactly the same). It seems a limit of 10 webhooks are linked to an application, but I want to just be sure and specify the webhook each time (like I did for IPN and the notificationurl), but it seems the limit of 10 requires a check each time too. These webhooks seem cumbersome ...

**Comment by russek66** [comment]
1. You might need it if you wanna be fully automatic. Let's say for some reason customer will never get to your return URL > you will never execute payment > you will never notice it
2. Not always, for example PayPal can lock someone's payment for further review and so the payment will be pending.
3. You create webhook just once [here](https://developer.paypal.com), in code you never create it or check if it exists, you simply listen for incoming data and verify it.

Webhook is similar to IPN, you set it on your https://localhost/webhook.php (or whatever you address is) > PP send data to it > you do the verification and proceed with it. Main difference from user POV is that you will not get all data via webhook, but that does not me that you can not access it.

I am having hard time dealing with this SDK as well... I had to study it for days to get full understanding of it. I am writing huge webshop but still, docs are lacking so much that you have to do research and massive testing to create simple payment(if you want to make it tip top)...

This is what you get from webhook, not much but enough to get more:

```
    0: array(
        'webhook' => stdClass::__set_state(array(
             'id' => 'WH-09W625580J555943A-3E263661V9645703B',
             'event_version' => '1.0',
             'create_time' => '2019-02-11T19:59:25.762Z',
             'resource_type' => 'sale',
             'event_type' => 'PAYMENT.SALE.COMPLETED',
             'summary' => 'Payment completed for EUR 2.0 EUR',
             'resource' => stdClass::__set_state(array(
                 'id' => '38321916D2806725K',
                 'state' => 'completed',
                 'amount' => stdClass::__set_state(array(
                     'total' => '2.00',
                     'currency' => 'EUR',
                     'details' => stdClass::__set_state(array(
                         'subtotal' => '2.00',
                    )),
                )),
                 'payment_mode' => 'INSTANT_TRANSFER',
                 'protection_eligibility' => 'ELIGIBLE',
                 'protection_eligibility_type' => 'ITEM_NOT_RECEIVED_ELIGIBLE,UNAUTHORIZED_PAYMENT_ELIGIBLE',
                 'transaction_fee' => stdClass::__set_state(array(
                     'value' => '0.41',
                     'currency' => 'EUR',
                )),
                 'invoice_number' => '308',
                 'parent_payment' => 'PAYID-LRQ5HYI6LH15119US518014W',
                 'create_time' => '2019-02-11T19:59:21Z',
                 'update_time' => '2019-02-11T19:59:21Z',
                 'links' => array(
                    0 => stdClass::__set_state(array(
                         'href' => 'https://api.sandbox.paypal.com/v1/payments/sale/38321916D2806725K',
                         'rel' => 'self',
                         'method' => 'GET',
                    )),
                    1 => stdClass::__set_state(array(
                         'href' => 'https://api.sandbox.paypal.com/v1/payments/sale/38321916D2806725K/refund',
                         'rel' => 'refund',
                         'method' => 'POST',
                    )),
                    2 => stdClass::__set_state(array(
                         'href' => 'https://api.sandbox.paypal.com/v1/payments/payment/PAYID-LRQ5HYI6LH15119US518014W',
                         'rel' => 'parent_payment',
                         'method' => 'GET',
                    )),
                ),
            )),
             'links' => array(
                0 => stdClass::__set_state(array(
                     'href' => 'https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-09W625580J555943A-3E263661V9645703B',
                     'rel' => 'self',
                     'method' => 'GET',
                )),
                1 => stdClass::__set_state(array(
                     'href' => 'https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-09W625580J555943A-3E263661V9645703B/resend',
                     'rel' => 'resend',
                     'method' => 'POST',
                )),
            ),
        )),
    )
```

**Comment by russek66** [comment]
Samples are pretty clear on that matter. I did not use it but something like one time install script with:
```
$webhookList= Webhook::getAll($apiContext);
foreach ($webhookList->getWebhooks() as $webhook) { 
     $webhook->delete($apiContext); 
}
$webhook = new Webhook();
$webhook->setUrl("URL");
$webhookEventTypes[] = new WebhookEventType(
    '{
        "*"
    }'
);
$webhook->setEventTypes($webhookEventTypes);
$output = $webhook->create($apiContext);
```
should be fine for what you are doing. Then just listen for data on webhook URL.

**Comment by prakash-gangadharan** [comment]
Hi @liedekef, do you still need a help for this issue?

**Comment by liedekef** [comment]
No, I'll close this.

**Comment by prakash-gangadharan** [comment]
@liedekef Thanks!
