### ISSUE TITLE
Not possible to set business email 

### ISSUE THREAD

**Issue by tdroenner** [paypal/PayPal-PHP-SDK#124]
In the old APIs it is possible to define a business email to which the payment confirmation ist sent e.G.:
input type="hidden" name="business" value="paypal@nameyourdomain.com"

As far as I've seen this cannot be accomplished with the REST-API.

**Comment by ppmtscory** [comment]
@tdroenner this `business` value was where the payment was sent and also set the default for notifications.  However, this was only for PayPal Standard and is not the case for any API solutions (legacy or REST).  For anything API related, you'll need to configure your IPN or Webhook script to send the relevant information to whichever email address you'd like.
