### ISSUE TITLE
Passing Variable in the Payment Checkout 

### ISSUE THREAD

**Issue by blpraveen** [paypal/PayPal-PHP-SDK#1240]
### General information

* SDK/Library version: 1.x
* Environment: sandbox
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: PHP Version 7

### Issue description

How to pass variable in the create Payment and receive with the execute payment url http://forext.dev/execute-payment?paymentId=PAYID-LRJKH3Y4HD99569FH718421X&token=EC-69957307H53168746&PayerID=GQZNABYN4JYAJ

**Comment by blpraveen** [comment]
I tried with hidden input field that is not carried forward

**Comment by prakash-gangadharan** [comment]
Hi @blpraveen, you can simply add query string parameter in the return url while creating the payment. The same you can see it in the return URL to execute the payment after buyer approving it.
Refer attached screenshot:
![image](https://user-images.githubusercontent.com/13796434/66947599-cd20e800-f070-11e9-9305-0d303bfdd02a.png)

**Comment by prakash-gangadharan** [comment]
@blpraveen , you can also set custom filed  during create payment request and the same has been returned in the execute payment response.

```php
// ### Transaction
// A transaction defines the contract of a
// payment - what is the payment for and who
// is fulfilling it. 
$transaction = new Transaction();
$transaction->setAmount($amount)
    ->setItemList($itemList)
    ->setDescription("Payment description")
    ->setCustom("EBAY_EMS_90048630024435") //The free-form custom field for the client's use.
    ->setInvoiceNumber(uniqid());
```
