### ISSUE TITLE
Payments: Switch from PayPal to PayPal Plus

### ISSUE THREAD

**Issue by Sebi94nbg** [paypal/PayPal-PHP-SDK#1242]
### General information

* SDK/Library version: 1.14.0
* Environment: Both

### Issue description

My PayPal (normal, not PLUS) integration for `payments` is working fine in sandbox and production. My payments are created based on this sample: [CreatePaymentUsingPayPal.php](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/CreatePaymentUsingPayPal.php)

I've clicked on the button to apply for PayPal PLUS [here](https://www.paypal.com/webapps/mpp/paypal-plus) on Monday or so, but I did not get any email, phone call or anything else yet.

1. First of all: Which steps are required in my case to support PayPal PLUS? Do I even need to change anything, when I used the above sample code or do I only need to enable the features of "PLUS" in the REST API at [developer.paypal.com](https://developer.paypal.com/) later?

2. Where can I check the status of my application for PayPal PLUS? Or how can I see, if my application was approved or not?

**Comment by sucithrashanu** [comment]
HI @Sebi94nbg 
This is more like the question which is regarding the integration part. Please refer the below link for merchant technical support.

 [https://www.paypal.com/in/smarthelp/article/how-do-i-get-merchant-technical-support,-such-as-for-paypal-product-integrations,-apis-or-sandbox-testing-faq3723](url)

Please visit [Merchant Technical Support](https://www.paypal-techsupport.com/app/) and submit your question for merchant/developer technical support, such as for PayPal product integrations/APIs

Thanks!
