### ISSUE TITLE
Difference between this repository and Checkout-PHP-SDK?

### ISSUE THREAD

**Issue by scofield-ua** [paypal/PayPal-PHP-SDK#1243]
What is the difference between this repository and checkout sdk: https://github.com/paypal/Checkout-PHP-SDK? 

Why there are two different repositories, and which should I use?

**Comment by dshaw** [comment]
@scofield-ua If you are integrating Orders and Payments, then definitely go with the new Checkout SDK.

**Comment by scofield-ua** [comment]
@dshaw thanks, but current repository can be used for Ordres and Payments as well, at least before February update, right? I've used it before. So why there is a split into 2 repositories, confusing.

**Comment by prakash-gangadharan** [comment]
@scofield-ua, Please refer this link : https://github.com/paypal/PayPal-PHP-SDK#paypal-checkout-v2 for your questionnaire.
