### ISSUE TITLE
At each cycle How to check Billing Agreement payments detail

### ISSUE THREAD

**Issue by dnyaneshgetwebcare** [paypal/PayPal-PHP-SDK#1245]
I am mostly using the sample codes. I have created a plan, activated it, created an agreement and activated that. I have the Agreement ID from the callback token and have the agreement object.

Since this is a subscription based system, how do I check the user was billed at the next cycle and continue to provide services to them? Do I do it by the failed count, by the last payment date or other paramter? Is there a function in any of the Classses to do such a check or to get these attributes?

**Comment by nitinsonawane234** [comment]
I'm facing the same problem from last one week.

**Comment by prakash-gangadharan** [comment]
Hi @dnyaneshgetwebcare,
Refer these example code to check Billing Agreement payments details.

- [Get Billing Agreement](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/billing/GetBillingAgreement.php)
- [Search for Transactions](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/billing/SearchBillingTransactions.php)

**Comment by prakash-gangadharan** [comment]
Similar issue : https://github.com/paypal/PayPal-PHP-SDK/issues/1203
