### ISSUE TITLE
Where is the appropriate place to report bugs for PayPal.com (legitimate not stupid "I need help" issues)

### ISSUE THREAD

**Issue by s3w47m88** [paypal/PayPal-PHP-SDK#1247]
I realize this is not the appropriate place, but I can't find anywhere else to do this and would appreciate direction.

I have some bug reports for PayPal.com - they may relate to some of the repos here such as this API repo. But some are not.

For example:
- Unable to get all transactions using any of the APIs - including this one. See this StackOverflow for details: https://stackoverflow.com/questions/54973448/get-all-the-transactions-from-paypal-using-paypal-php-sdk
- Notifications icon in the upper right always expands on page reload. Blocking the users view of the site, especially on mobile.
- For accounts have have a PayPal Working Capital Loan they still get the banner on login and after login (one that expands up and down) inviting them to apply.
- "Provide Information About Your Account" alert gets stuck, never dismissing alert and never submitting and closing out properly.
![screen shot 2019-03-03 at 12 58 00 pm](https://user-images.githubusercontent.com/656776/53701648-1bb89500-3db4-11e9-9e3e-1d726078501c.png)
- For very old, "Legacy" accounts as I have been told they're called, they cannot access all PayPal Pro menu items and respective pages.
- After sign in, on the left, there are panels. Many should be dismissible but are not. Ex. "Tax documents and other reports", "Get the app designed for businesses", "PayPal Marketing Solutions", "Virtual Terminal More"
![Uploading Screen Shot 2019-03-03 at 12.55.46 PM.png…]()
![screen shot 2019-03-03 at 12 55 30 pm](https://user-images.githubusercontent.com/656776/53701619-c7adb080-3db3-11e9-948e-c141a05fc27b.png)
![screen shot 2019-03-03 at 12 55 14 pm](https://user-images.githubusercontent.com/656776/53701620-ca100a80-3db3-11e9-8569-e92e6de51439.png)
![screen shot 2019-03-03 at 12 55 46 pm](https://user-images.githubusercontent.com/656776/53701618-c54b5680-3db3-11e9-8107-16189030971e.png)

**Comment by prakash-gangadharan** [comment]
Hi @s3w47m88 , if this not an integration issue with PayPal-Java-SDK, refer the below link for merchant technical support.
https://www.paypal.com/in/smarthelp/article/how-do-i-get-merchant-technical-support,-such-as-for-paypal-product-integrations,-apis-or-sandbox-testing-faq3723

Please visit [Merchant Technical Support](https://www.paypal-techsupport.com/app/) and submit your question for merchant/developer technical support, such as for PayPal product integrations/APIs

Thanks!
