### ISSUE TITLE
Sorry, your bank wasn't able to verify your VISA x-... at this time. Please choose another way to pay.

### ISSUE THREAD

**Issue by VirendraArekar** [paypal/PayPal-PHP-SDK#1248]

**Comment by VirendraArekar** [comment]
Sorry, your bank wasn't able to verify your VISA x-.. at this time. Please choose another way to pay.

**Comment by prakash-gangadharan** [comment]
Hi @VirendraArekar, is this still an issue? Please revert us back with the recent occurrence.

**Comment by prakash-gangadharan** [comment]
@VirendraArekar, closing this issue, please revert us back if still you having this problem.

**Comment by ajaykumar97** [comment]
I am still having this issue. Getting same issue while proceeding after choosing the card for the payment. Please help!

**Comment by Krishnankk** [comment]
### Is there anybody still having the same issue,,,???

**For original PayPal payments.**

They temporarily charge your card a small amount. This is a regular fraud prevention measure, to ensure the card is valid. If your card issuer didn’t authorise the temporary charge, the card may be declined when you tried to make a payment using PayPal.


**For sandbox**

If you want to pay using your sandbox account, you can use credit card/debit card generated from [PayPal developer console](https://developer.paypal.com/developer/creditCardGenerator/) 

Note :  _You need to use VISA - INDIA for INR transactions_
