### ISSUE TITLE
Billing Agreement CANNOT_MIX_CURRENCIES

### ISSUE THREAD

**Issue by DanielnetoDotCom** [paypal/PayPal-PHP-SDK#1249]
### General information

* SDK/Library version: I dont know, I got this version, the latest on github a year ago
* Environment: Sandbox
* `PayPal-Debug-ID` values: d230dcb1e5c6d
* Language, language version, and OS: Ubuntu 16

### Issue description

I triple check many times, I am trying to do a billing agreement. everything goes right but when I tried to execute I got this error:

`PayPal\Core\PayPalHttpConnection : ERROR: Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/billing-agreements/EC-0G8393324E3855803/agreement-execute. {"name":"CANNOT_MIX_CURRENCIES","message":"Invalid currency code, all currency codes must match","information_link":"https://developer.paypal.com/docs/api/payments.billing-agreements#errors","debug_id":"d230dcb1e5c6d"}
`
I checked everywhere and the currency is correct, please help me, I am lost

**Comment by prakash-gangadharan** [comment]
Hi @DanielnetoDotCom , can you add the `PayPal-Debug-ID` for the recent instance of this issue?

**Comment by DanielnetoDotCom** [comment]
7 months later, it is too late

But anyway, it was regarding my main account that accepts only BRL and does not accept USD

**Comment by prakash-gangadharan** [comment]
@DanielnetoDotCom, it is live issue or happening in the sandbox environment? can you help with `PayPal-Debug-ID`?

**Comment by DanielnetoDotCom** [comment]
I am not 100% if I tested it in the live enviroment, but I am 100% it happen in sandbox

I have a Brazilian account (BRL) and I create items with values in USD, and this error happen if I do not change the currency to BRL

**Comment by prakash-gangadharan** [comment]
@DanielnetoDotCom , can you help me with `debug_id` to check this further?

**Comment by DanielnetoDotCom** [comment]
@prakash-gangadharan where can I find the debug_id?

**Comment by prakash-gangadharan** [comment]
@DanielnetoDotCom , refer this link to get the `Paypal-Debug-id`
https://github.com/paypal/PayPal-PHP-SDK/wiki/exception-%27PayPal%5CException%5CPayPalConnectionException%27-with-message-%27Got-Http-response-code-400-when-accessing

**Comment by prakash-gangadharan** [comment]
@DanielnetoDotCom, did you get a chance to retrieve the `Paypal-Debug-id` for the reported issue?

**Comment by DanielnetoDotCom** [comment]
I will be honest, It is working now since I change the currency.

This issue **took 7 months to get answered**, which I think is unacceptable if you have a serious project.

To be able to do it, I will need to create all test environment again, and I am engaged in something else now.

sorry, for now, I can not take a look on it. next time, when I need to update something on PayPal I may return to this issue.

**Comment by prakash-gangadharan** [comment]
@DanielnetoDotCom sorry the for the inconvenience/delay in response. Please reopen/revert us back if you find this instance of issue again.
