### ISSUE TITLE
Autoload is not working

### ISSUE THREAD

**Issue by gintares** [paypal/PayPal-PHP-SDK#1250]
Autoload is not working in PHP PayPal SDK, 

In case of PayPal SDK, statements
```
use Sample\PayPalClient; 
use PayPalCheckoutSdk\Orders\OrdersGetRequest;
```
do not find the namespaces and classes.

Instead i have to write : 
```
require_once INC_ROOT.'/vendor/paypal/paypal-checkout-sdk/samples/PayPalClient.php'; 
$PayPalClient_n = 'Sample\\PayPalClient';
$PayPalClient_o = new $PayPalClient_n(); 

require_once INC_ROOT.'/vendor/paypal/paypal-checkout-sdk/lib/PayPalCheckoutSdk/Orders/OrdersGetRequest.php'; 
$PayPalClient_n = 'PayPalCheckoutSdk\\Orders\\OrdersGetRequest';
$OrdersGetRequest_o = new $PayPalClient_n($orderId); 

$client = $PayPalClient_o::client();
$response = $client->execute( $OrdersGetRequest_o );
```

The problem that this issue propagates too loading inside OrdersGetRequest.php, and PayPalClient. php, thus i have to require and instantiate class in every included file, which also requires other vendor packages like Braintree. 

There is something clearly wrong with PayPal SDK installation.
There is no such a problem with any other package i am using:

    "require" : {
        "php": "~7.0",
        "doctrine/orm": "^2.5",
        "doctrine/data-fixtures" :  "dev-master",
        "doctrine/migrations" :  "dev-master",
        "doctrine/doctrine-bundle" :  "^1.6",
        "doctrine/doctrine-fixtures-bundle" :  "dev-master",
        "symfony/console": "~2.5",  
        "twig/twig": "^1.24",
        "abraham/twitteroauth"  :  "dev-master",
        "phpdocumentor/phpdocumentor" : "2.*",
        "firebase/php-jwt": "^4.0",
        "phpmailer/phpmailer": "^5.2",
        "swiftmailer/swiftmailer": "^6.0",
        "geocoder-php/google-maps-provider": "^4.1",
        "php-http/message": "^1.6",
        "beberlei/DoctrineExtensions": "^1.1",
        "paypal/rest-api-sdk-php": "*",
        "mongodb/mongodb": "^1.4",
        "joshtronic/php-loremipsum": "^1.0",
        "braintree/braintree_php": "^3.39",
        "paypal/paypal-checkout-sdk": "^1.0"
    },

### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS:

**Comment by sucithrashanu** [comment]
@gintares 
if this still an issue, can you help with the recent PayPal-Debug-ID

Thanks
