### ISSUE TITLE
Support for the new Subscriptions API

### ISSUE THREAD

**Issue by Mwni** [paypal/PayPal-PHP-SDK#1251]
The old subscriptions API will be deprecated in about two weeks.
The new subscriptions API [(link to docs)](https://developer.paypal.com/docs/limited-release/subscriptions/api/#subscriptions) is live, but it doesn't seem like this SDK is supporting it, yet.

Are there plans for this?

**Comment by MarGul** [comment]
I would really like to know this as well. Should we just start to integrate directly with the API or is this coming anytime soon in the SDK?

**Comment by manyeung** [comment]
Is that any update?

**Comment by viralwvmagic** [comment]
When new PHP SDK version launch with latest API support?

**Comment by davestlyon** [comment]
Even the low-level documentation on Paypal APIs is a bit confusing. For the SDK to be so far behind what Paypal themselves says we should be doing for Subscriptions. If you go find a recent how-to on PHP development for Paypal subscriptions you'll find approaches that are deprecated within Paypal. The SDK is only helpful if it's up to date.

No doubt many that will read this will be thinking "Hey! Get involved and write the new additions to the SDK!" Yes, but... Paypal is a large, well-off company that wants us to use their service. They need to be driving the development of their own SDKs. I guess I'm spoiled from working recently with Stripe and even Braintree SDKs, which in comparison are amazingly good.

**Comment by manyeung** [comment]
feedback from the PayPal: https://github.com/paypal/PayPal-PHP-SDK/issues/1275#issuecomment-515360686

**Comment by prakash-gangadharan** [comment]
Hi folks, current REST sdks still using below `Billing Plans API` which is  deprecated.
https://developer.paypal.com/docs/api/payments.billing-plans/v1/#billing-plans

**Deprecation notice**:

-  The /v1/billing-plans endpoints are deprecated. 
- Use the /v1/billing/subscriptions endpoints instead. 
- For details, see [Subscriptions Integration](https://developer.paypal.com/docs/subscriptions/integrate/).

Currently we do not have any stipulated timeline to replace the deprecated endpoints with the newer one but it may be available in near future.

**Comment by sucithrashanu** [comment]
HI folks,

Please Check [PayPal Community](https://www.paypal-community.com) and  [MTS](https://paypal.com/mts)
Thanks!
