### ISSUE TITLE
SetRecipientName Method return 400 error

### ISSUE THREAD

**Issue by junardoclarit** [paypal/PayPal-PHP-SDK#1252]
I think there is an issue when setting a shipping address specifically the recipient_name field. I created an agreement and set the Shipping Address. but it returns me this error.

`PayPal\Core\PayPalHttpConnection : ERROR: Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/billing-agreements/. {"name":"VALIDATION_ERROR","details":[{"field":"shipping_address.recipient_name","issue":"Field name is not defined for this resource type."}],"message":"Invalid request. See details.","information_link":"https://developer.paypal.com/docs/api/payments.billing-agreements#errors","debug_id":"2565dab2c3ff3"}`

Here is my code

        $shippingAddress = new ShippingAddress;
        $shippingAddress->setLine1($checkoutSession->shipping_address1);
        $shippingAddress->setLine2($checkoutSession->shipping_address2);
        $shippingAddress->setCity($checkoutSession->shipping_city);
        $shippingAddress->setState($checkoutSession->shipping_state);
        $shippingAddress->setPostalCode($checkoutSession->shipping_postal_code);
        $shippingAddress->setCountryCode($checkoutSession->shipping_country_code);
        $shippingAddress->setRecipientName($checkoutSession->shipping_first_name);

        $agreement->setShippingAddress($shippingAddress);

but if I remove this line `$shippingAddress->setRecipientName($checkoutSession->shipping_first_name);` it has no issue..

Please Help..

**Comment by prakash-gangadharan** [comment]
@junardoclarit, **recipient_name** is not supported in Create Billing Agreement API.
The documentation is not up-to-date. We have noted this and will update the documentation accordingly.
