### ISSUE TITLE
How to get the transaction number ?

### ISSUE THREAD

**Issue by MOWebCreation** [paypal/PayPal-PHP-SDK#1253]
Hello all,

I'm using the REST API Paypal ExpressCheckout with the PHP SDK, my script is able to process payment but I would like to get a essential information about the payment : the transaction number, usefull for tracking payment.

He's anybody no how to get the transaction number after a payment ?

I've tried many object and methods of the API without finding the solution.

Thankz by advance for your help,

Mickaël

**Comment by hellohasan** [comment]
i also fach this same problem, please help us anybody.

**Comment by prakash-gangadharan** [comment]
Hi @MOWebCreation, to **Process PayPal Payments** / create a PayPal payment below are the steps.

- [Define payment](https://developer.paypal.com/docs/api/quickstart/payments/#define-payment)
- [Create payment](https://developer.paypal.com/docs/api/quickstart/payments/#create-payment)
- [Execute payment](https://developer.paypal.com/docs/api/quickstart/payments/#execute-payment)

After executing the approved payment you can call [Show payment details API](https://developer.paypal.com/docs/api/payments/v1/#payment_get) via SDK. You can find the transaction_id under related_resources -> sale -> id in the response.

**Sample code**:
```php
<?php
// # GetPaymentSample
// API used: GET /v1/payments/payment/{payment_id}

$createdPayment = require __DIR__ . '/CreatePaymentUsingPayPal.php';
/** @var Payment $createdPayment */

use PayPal\Api\Payment;

// ### Retrieve payment
// Retrieve the payment object by calling the
// static `get` method
// on the Payment class by passing a valid
// Payment ID
try {
    $payment = Payment::get($createdPayment->getId(), $apiContext);
} catch (Exception $ex) {
    exit(1);
}
return $payment;

```
