### ISSUE TITLE
Will Payouts API be integrated in v2?

### ISSUE THREAD

**Issue by dkjensen** [paypal/PayPal-PHP-SDK#1256]
Are there plans for the Payouts API to be integrated in v2 at some point?

**Comment by lmarkus** [comment]
Hi, dkjensen.

I am assuming that the question relates to V2 of Payouts API - in that case, yes, we do have plans to release the V2 later in the year which will incorporate better features to make it easier for merchants to get activated, to send payouts in multiple currencies and to send payouts to Venmo. Any other feedback of things you would like to see in future versions is welcome.
