### ISSUE TITLE
How to update the payment definition for trial and regular subscriptions ? 

### ISSUE THREAD

**Issue by Majid-ali37** [paypal/PayPal-PHP-SDK#1261]
Hi I need to update my plan that is currently active and customers have subscribed to it. I created trial and regular subscription plan successfully but I now I need to update the plan for payment definitions for trial and for the regular.  I found no topic on updating the payment definition for trial and regular subscription. Please I need help !!

**Comment by sucithrashanu** [comment]
@Majid-ali37 
Check this sample [Payment Definition](https://github.com/paypal/PayPal-PHP-SDK/blob/ff2a7f9c2ddc47a22cb7bb8a5b0bb97bd16bdd6f/tests/PayPal/Test/Functional/resources/BillingPlansFunctionalTest/testCreate.json) for trail and regular subscription.

Thanks
