### ISSUE TITLE
Broken link to webhooks testing tool

### ISSUE THREAD

**Issue by surround3** [paypal/PayPal-PHP-SDK#1263]
The webhooks guide at https://paypal.github.io/PayPal-PHP-SDK/sample/doc/notifications/CreateWebhook.html recommends using requestb.in for testing.

This service was taken down last year and the link is broken. There is a new hosted version, with some additional features (including enhanced privacy) at https://requestbin.com

**Comment by sucithrashanu** [comment]
@surround3 

Currently we do not have any stipulated timeline for the next version( v2.0.0 release), but it may be available in near future.
Kindly Check [PayPal Community](https://www.paypal-community.com) and  [MTS](https://paypal.com/mts) 

Thanks!
