### ISSUE TITLE
Unauthorized payment issue : 400

### ISSUE THREAD

**Issue by Nicolas-Demailly** [paypal/PayPal-PHP-SDK#1265]
### General information

* SDK/Library version: 1.14
* Environment: Production
* `PayPal-Debug-ID` values: 9ca8b0f35042
* Language, language version, and OS: PHP 7.2 on OVH Linux

### Issue description

I'm using rest api on laravel and for the same code, I've ALWAYS got a success on SANDBOX and ALWAYS a 400 error on LIVE. So I don't know why.

**Comment by prakash-gangadharan** [comment]
Hi @Nicolas-Demailly , if it is still an issue can you help us here by providing the `PayPal-Debug-ID` for the recent occurrence?

Thanks!

**Comment by prakash-gangadharan** [comment]
Hi @Nicolas-Demailly, can you revert us back.

**Comment by prakash-gangadharan** [comment]
@Nicolas-Demailly, closing this issue for now, please revert us back if this is still an issue.
