### ISSUE TITLE
Unable to download Sample Folder

### ISSUE THREAD

**Issue by cbpatel17** [paypal/PayPal-PHP-SDK#1266]
I am not able to download Sample Folder.

I tried download zip file as well as using composer.

Note : Sample Folder downloaded when i tried to clone repository through git clone.

Thanks

**Comment by sharkbit** [comment]
I agree, Would love this to download with rest of SDK.

**Comment by sucithrashanu** [comment]
@cbpatel17 
Try this method. Navigate to this [Release](https://github.com/paypal/PayPal-PHP-SDK/releases/tag/1.14.0) and find **PayPal-PHP-SDK-1.14.0.zip**

Just Download and extract into your project folder.

Thanks
