### ISSUE TITLE
404 INVALID_RESOURCE_ID after successful return

### ISSUE THREAD

**Issue by mdeuerlein** [paypal/PayPal-PHP-SDK#1267]
### General information

* SDK/Library version: 1.14.0
* Environment: Production
* `PayPal-Debug-ID` values: cae194195dffd, 8695d1e1d84b1, 5f78c2f282b02, ....
* Language, language version, and OS: 
PHP Version 7.2.13-nmm1
Ubuntu xenial (16.04)
Linux Kernel 4.4.0-146-generic 

### Issue description

- PayPal Plus Payment is created
- PaymentID and approval is returned from Paypal
- User is directed to approval URL
- User is returned to success URL incl. paymentID, token and PayerID
- API GetPayment Request returns 404 Error:

```
{
    "name": "INVALID_RESOURCE_ID",
    "message": "The requested resource ID was not found",
    "information_link": "https://developer.paypal.com/docs/api/payments/#errors",
    "debug_id": "5f78c2f282b02"
}
```
Seems to be like:
#980 and paypal/PayPal-REST-API-issues/issues/151

**Comment by NiklasLazinbee** [comment]
I get a similar error message

>Fatal error: Uncaught BraintreeHttp\HttpException: {"name":"RESOURCE_NOT_FOUND","details":[{"issue":"INVALID_RESOURCE_ID","description":"Specified resource ID does not exist. Please check the resource ID and try again."}],"message":"The specified resource does not exist.","debug_id":"43d8214fa9514","links":[{"href":"https://developer.paypal.com/docs/api/orders/v2/#error-INVALID_RESOURCE_ID","rel":"information_link","method":"GET"}]} 

What is the resource id, where do I get the right id from? Only the orderID is passed as parameter.

**Comment by gilsonviana** [comment]
Having the same problem here using the `"paypal/rest-api-sdk-php": "^1.14"`.

```{"name":"INVALID_RESOURCE_ID","message":"Requested resource ID was not found.","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"7378f77e8a710"}```

Please, does anybody have an update on this?

**Comment by gilsonviana** [comment]
Alright. I was able to figure out the problem.

```use PayPal\Api\Payment;

**Comment by gilsonviana** [comment]
I was able to fix the problem.
The first parameter of static method **get** in the **Payment** class requires the **paymentId** instead of the PayerID. Silly mistake, but the error was untraceable through the error message provided.
```
use PayPal\Api\Payment;

/** redirect method after user logged in and submitted the payment */
public function getPaymentStatus(Request $request)
    {
        $payment_id = $request->input('paymentId');
        
        $payment = Payment::get($payment_id, $this->_api_context);
                
        $execution = new PaymentExecution();
        $execution->setPayerId($request->input('PayerID'));

        $result = $payment->execute($execution, $this->_api_context);        
        
        dd($result->getState()); // APROVED
        if ($result->getState()) {
            // insert into database
            // send message status 201
        }
        // send error message status 400
    }
```

**Comment by prakash-gangadharan** [comment]
Hi @mdeuerlein, do you still facing this issue?

**Comment by prakash-gangadharan** [comment]
Hi @mdeuerlein, am closing this issue out, please feel free to reopen if this is still an issue and help us with the recent debug ids.

**Comment by dakiesse** [comment]
I have the same issue. I am using @paypal/checkout-server-sdk

**Comment by prakash-gangadharan** [comment]
Hi @dakiesse, Please help us with the recent `PayPal-Debug-ID`

**Comment by dakiesse** [comment]
Hi @prakash-gangadharan, I solved this issue =)
