### ISSUE TITLE
Sandbox is working fine with 'Paypal Personal Account' but in Live mode, the 'Paypal Personal account' not logging in

### ISSUE THREAD

**Issue by riaxe-tanmaya** [paypal/PayPal-PHP-SDK#1268]
When I process with Test Paypal mode It works file. I used to pay by my Personal Account. But in case of Live Payment, when I am trying to login with my Personal Account, It does not log in into the paypal and payment not happening. 

Please Help.

**Comment by prakash-gangadharan** [comment]
Here is the wikipage for going live and you need to set the mode to "live".
https://github.com/paypal/PayPal-PHP-SDK/wiki/Going-Live

And below is the link to File based Configurations:
https://github.com/paypal/PayPal-PHP-SDK/wiki/File-based-Configurations

Follow the steps given above. If you still facing any challenges, Please revert us back.

Thanks!
