### ISSUE TITLE
Unable to switch to Live Mode

### ISSUE THREAD

**Issue by buttflattery** [paypal/PayPal-PHP-SDK#1269]
### General information

* SDK/Library version: 1.14.0
* Environment: Production
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: php 7.2 Ubuntu

### Issue description
I am trying to switch to the live mode and following the guide i add my live secret and the ClientID and add `"mode"=>'live'` by using code configuration like below

```
$apiContext->setConfig(
            [
                'mode'=>'live',
                'log.LogEnabled' => true,
                'log.FileName' => 'PayPal.log',
                'log.LogLevel' => 'DEBUG'
            ]
);
```
it throws the error 

> {"error":"invalid_client","error_description":"Client Authentication failed"}

Although the sandbox works fine, i am using REST API for payments. the strangest thing is that if i use the same live credentials and remove the `"mode"=>"live"` it starts redirecting me to the sandbox url to login why is that ? it should not redirecting me to the sandbox with the live credentials?

My Logs in  `Paypal.log` file

> [21-05-2019 11:42:37] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/oauth2/token
> [21-05-2019 11:42:40] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 401
> [21-05-2019 11:42:40] PayPal\Core\PayPalHttpConnection : ERROR: Got Http response code 401 when accessing https://api.paypal.com/v1/oauth2/token. {"error":"invalid_client","error_description":"Client Authentication failed"}

**Comment by prakash-gangadharan** [comment]
Hi @buttflattery,
Here is the wikipage for going live and you need to set the mode to "live".
https://github.com/paypal/PayPal-PHP-SDK/wiki/Going-Live

And below is the link to File based Configurations:
https://github.com/paypal/PayPal-PHP-SDK/wiki/File-based-Configurations

Follow the steps given above. If you still facing any challenges, Please revert us back.

Thanks!

**Comment by buttflattery** [comment]
I was just doing something stupid I had it done, thanks or the concerns @prakash-gangadharan

**Comment by BaiMaoLi** [comment]
yes. This is shit sdk.
Not working in live mode.

**Comment by buttflattery** [comment]
@BaiMaoLi  no it isnt and it works correctly if you dont pay attention, what is the problem you are having?

**Comment by BaiMaoLi** [comment]
Sorry for my rude,  I just deleted that comment.
It is working well.
I just made one mistake.
I used to use stripe, and in stripe, even though we don't capture payment, money deduct from buyer account and goes into merchant account, but just not captured.
But in paypal, only when captured, money goes into merchant account and ...
