### ISSUE TITLE
Receipt Number doesn't include leading zero

### ISSUE THREAD

**Issue by adam-laraqui** [paypal/PayPal-PHP-SDK#1270]
Hi,

Just wanted to let you know that for customers checking out as a guest, the receipt number is being provided as an integer, so any leading zero(s) are removed, therefore being incorrect data.

**Comment by prakash-gangadharan** [comment]
Hi @adam-laraqui , can you add more context about this issue? do you have code snippet or related correlation id for this issue?

**Comment by adam-laraqui** [comment]
Hi,

Well, here's an example of what I get back from pulling a sale transaction record of a guest payment:

`(
            [id] => {removed}
            [state] => completed
            [amount] => PayPal\Api\Amount Object
                (
                    [_propMap:PayPal\Common\PayPalModel:private] => Array
                        (
                            [total] => 5.25
                            [currency] => USD
                            [details] => PayPal\Api\Details Object
                                (
                                    [_propMap:PayPal\Common\PayPalModel:private] => Array
                                        (
                                            [subtotal] => 5.25
                                        )

                                )

                        )

                )

            [payment_mode] => INSTANT_TRANSFER
            [protection_eligibility] => ELIGIBLE
            [protection_eligibility_type] => ITEM_NOT_RECEIVED_ELIGIBLE,UNAUTHORIZED_PAYMENT_ELIGIBLE
            [transaction_fee] => PayPal\Api\Currency Object
                (
                    [_propMap:PayPal\Common\PayPalModel:private] => Array
                        (
                            [value] => 0.50
                            [currency] => USD
                        )

                )

            [invoice_number] => {removed}
            [receipt_id] => 963162657486943
            [parent_payment] => PAYID-LVXRA4A9WR26124B6937591J
            [create_time] => 2019-09-04T01:18:20Z
            [update_time] => 2019-09-04T01:18:20Z
            [links] => Array
                (
                    [0] => PayPal\Api\Links Object
                        (
                            [_propMap:PayPal\Common\PayPalModel:private] => Array
                                (
                                    [href] => https://api.paypal.com/v1/payments/sale/{removed}
                                    [rel] => self
                                    [method] => GET
                                )

                        )

                    [1] => PayPal\Api\Links Object
                        (
                            [_propMap:PayPal\Common\PayPalModel:private] => Array
                                (
                                    [href] => https://api.paypal.com/v1/payments/sale/{removed}/refund
                                    [rel] => refund
                                    [method] => POST
                                )

                        )

                    [2] => PayPal\Api\Links Object
                        (
                            [_propMap:PayPal\Common\PayPalModel:private] => Array
                                (
                                    [href] => https://api.paypal.com/v1/payments/payment/PAYID-LVXRA4A9WR26124B6937591J
                                    [rel] => parent_payment
                                    [method] => GET
                                )

                        )

                )

            [soft_descriptor] => PAYPAL *{removed}
        )`

The receipt ID is only 15 numbers long, rather than 16. On the PayPal email, the full receipt ID is provided, with the leading 0 included. So this issue can only be reproduced by executing guest payments until a receipt ID with a leading 0 is generated (which is quite common).

The issue I would assume is that you're parsing it as an integer before returning it to the client.

**Comment by xjijies** [comment]
Hi @adam-laraqui, 
Can you do a recent transaction and updated here with paypal-debug ID, transaction ID and mail snippet for 16 digit leading 0 receipt_id.

**Comment by prakash-gangadharan** [comment]
Hi @adam-laraqui, this is not reproducible and please reopen if it still exists.
