### ISSUE TITLE
No webhooks fired for invoices created with the SOAP API

### ISSUE THREAD

**Issue by mcance** [paypal/PayPal-PHP-SDK#1272]
### General information

* SDK/Library version: 1.14.0
* Environment: sandbox & live
* `PayPal-Debug-ID` values: none
* Language, language version: PHP 5.6.36

### Issue description

No webhooks what-so-ever are fired for an invoice created via the SOAP API in either sandbox or live mode.

The webhook and tracked events are displayed correctly in the NVP SOAP Webhooks section of our Dashboard, e.g. Webhook ID: 7WX43933U7499124G and can also be viewed using the REST API with getWebhooks().

The related hook has a listener verified by the PayPal webhooks simulator and also by triggering a simulated event via the REST API, in both cases the the expected JSON payload will POST'ed to the listener.

However, when an invoice is created using the SOAP credentials for the same account, (either live or sandbox) and paid etc, no webhook is fired, (there is no POST or other request made to the listeners URL).

The listener is roughly setup like so, (credentials and listener URL removed):

$this->token = new OAuthTokenCredential( 
	'PAYPAL_CLIENT_ID',
	'PAYPAL_CLIENT_SECRET'
);

$this->auth = new ApiContext($this->token);

$this->auth->setConfig(
	array(
		'mode' => "sandbox",
		'log.LogEnabled' => true,
		'log.FileName' => '..//paypal.log',
		'log.LogLevel' => 'DEBUG'
	)
);

$webhook = new \PayPal\Api\Webhook();
$webhook->setUrl("https://our-paypal-listener.php?" . uniqid());

$webhookEventTypes = array();
$webhookEventTypes[] = new \PayPal\Api\WebhookEventType(
	'{
		"name":"INVOICING.INVOICE.PAID"
	}'
);
$webhookEventTypes[] = new \PayPal\Api\WebhookEventType(
	'{
		"name":"INVOICING.INVOICE.UPDATED"
	}'
);
$webhookEventTypes[] = new \PayPal\Api\WebhookEventType(
	'{
		"name":"INVOICING.INVOICE.REFUNDED"
	}'
);

$webhook->setEventTypes($webhookEventTypes);

try {	
	$output = $webhook->create($this->auth);
} catch (PayPalConnectionException $ex) {
	Utils::log('Failed to create webhooks (' . $ex->getData() . ')', true);
	return false;
}

return $output;	

And simulated with the PayPal dashboard simulator and the curl post below:

curl -v -X POST https://api.sandbox.paypal.com/v1/notifications/simulate-event \
-H "Content-Type: application/json" \
-H "Authorization: Bearer TOKEN" \
-d '{"url": "https://our-paypal-listener.php","event_type": "INVOICING.INVOICE.PAID","resource_version": "1.0"}'

As mentioned once setup the details of the hook created can be got, (getAll()) and deleted, (delete()) and via the REST API, the corresponding action reflected on the NVP SOAP dashboard.

We also deployed our code and used the live mode and the scenario repeated itself exactly.

I guess that the problem lies in the link between our invoices and corresponding hook and the use of the old SOAP API, (we have an ongoing project to convert all our PayPal calls to the REST API), but the exact reason is unclear.

**Comment by prakash-gangadharan** [comment]
Hi @mcance, is this still an issue and if it is yes please revert back.

**Comment by mcance** [comment]
Yes. We never solved the problem, wehooks refused to work whatever was tried.

Currently update invoice status using a request to getInvoiceDetails() for all our outstanding. Far rather use the webhook.

Any help would be appreciated.

**Comment by prakash-gangadharan** [comment]
@mcance, are you integrated with **PayPal-PHP-SDK** or the SOAP API?

**Comment by mcance** [comment]
The old SOAP service is still used to create our invoices but we use the newer REST service via the php API to create webhooks, see code refrenced above. 

We are in the process of moving invoicing to the PHP API, but some legacy stuff is holding us back.

**Comment by mcance** [comment]
PayPal-Debug-ID? Maybe missing something, but never seen that in the response from the SOAP service.

Our hooks id is 2NG58773KX1763533. The relevant listener is registered and responding, (all in live mode, unable to switch to sandbox on our production servers).

Registered hooks;
INVOICING.INVOICE.PAID
INVOICING.INVOICE.REFUNDED
INVOICING.INVOICE.UPDATED

I just created an invoice (INV2-G5ZN-2VE4-9K74-YFHC) and payed it. No notification received, or HTTPS request made to the listener.

**Comment by prakash-gangadharan** [comment]
@mcance , let us look into it and **2NG58773KX1763533** and is this live webhook-id?

**Comment by mcance** [comment]
Yes that's the live Web Hook ID associated with our account.

**Comment by mcance** [comment]
Thanks for taking a look, let me know if you need anything further.

**Comment by mcance** [comment]
Any progress?

**Comment by prakash-gangadharan** [comment]
@mcance , 
The old SOAP service is used to create your invoices via the APP-ID (APP-***masked***544) and 
you used the newer REST service via the php API to create webhooks via the client-id (Ae00xohep..***masked***1Gob-).

To receive the `INVOICING.INVOICE.PAID`, you should create the invoices using the same client-id for which the webhook events were subscribed.

If you are using different client id/APP-id which was not subscribed to the event but trying to receive webhooks for it, is not going to work.

**Comment by mcance** [comment]
Feared that was the case. As the app and client id are derived from the same account had hoped that they would be liked. Thanks for the clarification though.

**Comment by prakash-gangadharan** [comment]
@mcance, one merchant account may have multiple client-id/APP-ids since he may own different sites/stores.

**Comment by mcance** [comment]
Yup, our bad we created a new NVP/SOAP app via the dashboard that monitored web hooks for invoices but of course it is not the legacy app creating our invoices.

Penny would have dropped quicker if the legacy app had been listed in the Dashboard offering the option to enable webhooks etc, but understand SOAP, legacy etc.

We'll take the plunge and create an entirely new app and use v2 of the PHP SDK to both create and monitor invoices. Thanks for your help all much clearer now.
