### ISSUE TITLE
how to update merchant_preferences

### ISSUE THREAD

**Issue by Meatballsl** [paypal/PayPal-PHP-SDK#1273]
1、if the plan’s state is "ACTIVE", can't update merchant_preferences's return_url?
2、if the plan’s state is "CREATED"，how to update merchant_preferences's return_url

**Comment by gbaumeister** [comment]
+1 Was also trying to update a return_url on an existing plan. Unfortunately it seems like once a plan is active the return_url/cancel_url cannot be updated.

Generally this code should work if the plan has state: 'CREATED' (untested).

        $value = new PayPalModel('{
                "return_url":"'.$returnUrl.'",
                "cancel_url":"'.$cancelUrl.'"
        }');
        $patch = new Patch();
        $patch->setOp('replace')
           ->setPath('/merchant-preferences')
           ->setValue($value);
        $patchRequest = new PatchRequest();
            $patchRequest->addPatch($patch);
            $plan = Plan::get($planId, $apiContext);
            $plan->update($patchRequest, $apiContext);

**Comment by prakash-gangadharan** [comment]
Hi @Meatballsl, to update a billing plan, it should be in `CREATED` state. If you try to patch a plan when the state is `ACTIVE` you will get the below error.

```json
{
    "name": "BUSINESS_VALIDATION_ERROR",
    "details": [
        {
            "field": "validation_error",
            "issue": "Updation of a template only allowed in CREATED state."
        }
    ],
    "message": "Validation Error.",
    "information_link": "https://developer.paypal.com/docs/api/payments.billing-plans#errors",
    "debug_id": "9f58335227d9e"
}
```

**Comment by prakash-gangadharan** [comment]
@Meatballsl, If the plan’s state is "CREATED"，below is the sample code to update **merchant-preferences**'s return_url

```php
<?php
// # Update a plan
//
// This sample code demonstrate how you can update a billing plan, as documented here at:
// https://developer.paypal.com/docs/api/payments.billing-plans/v1/#billing-plans_patch
// API used: PATCH /v1/payments/billing-plans/{plan_id}-
// ### Changing Plan Amount
// This example demonstrate how you could change the plan amount

// Retrieving the Plan object from Create Plan Sample to demonstrate the List
/** @var Plan $createdPlan */
$createdPlan = require 'CreatePlan.php';

use PayPal\Api\Patch;
use PayPal\Api\PatchRequest;
use PayPal\Api\Plan;

try {
    $patch = new Patch();

    $paymentDefinitions = $createdPlan->getPaymentDefinitions();
    $patch->setOp('replace')
        ->setPath('/merchant-preferences')
        ->setValue(json_decode(
            '{
            "return_url": "https://example.com/return_url"
            }'
        ));
    $patchRequest = new PatchRequest();
    $patchRequest->addPatch($patch);

    $createdPlan->update($patchRequest, $apiContext);
    $plan = Plan::get($createdPlan->getId(), $apiContext);
} catch (Exception $ex) {
    exit(1);
}

```
