### ISSUE TITLE
PayPalPlus: How to resolve "logged out message" on PayPal using Payment Wall?

### ISSUE THREAD

**Issue by hendrikreimers** [paypal/PayPal-PHP-SDK#1274]
Hi,

i'm using the PHP SDK 1.14.0 and want to integrate a PayPalPlus Payment selection.
First i'd created a payment like the following json to get the approvalLink.
After that i'm placing the paypalplus script including the approval url and the payment selection options will be shown. That works.

But after i'm clicking continue to get the user to paypal, i got a simple message that i'm logged out for security reasons and need to go back to start the process again. If i'm redirecting to the approvalUrl without showing the paypalplus payment selection (instant after calling getApprovalLink() in my code) it works.

How can i fix it to show the payments selection in my site (PayPalPlus) and go to paypal after clicking continue without being logged out or something?

here's my json that will be generated by the SDK.

> {
   "intent":"sale",
   "payer":{
      "payment_method":"paypal",
      "payer_info":{
         "email":"....EMAIL....",
         "billing_address":{
            "line1":"test 123 ",
            "city":"test",
            "country_code":"DE",
            "postal_code":"12345"
         },
         "shipping_address":{
            "recipient_name":" ",
            "line1":"test 123 ",
            "city":"test",
            "country_code":"DE",
            "postal_code":"12345"
         }
      }
   },
   "transactions":[
      {
         "item_list":{
            "items":[
               {
                  "name":"...PRODUCT_NAME...",
                  "currency":"EUR",
                  "quantity":1,
                  "price":"3.42",
                  "sku":"1009"
               }
            ]
         },
         "amount":{
            "total":"8.65",
            "currency":"EUR",
            "details":{
               "subtotal":"3.42",
               "tax":"0.24",
               "shipping":"4.99"
            }
         },
         "invoice_number":"2549"
      }
   ],
   "redirect_urls":{
      "return_url":"....SUCCESS_URL....",
      "cancel_url":"....CANCEL_URL...."
   }
}

thanks a lot

**Comment by sucithrashanu** [comment]
Hi @hendrikreimers , 

This is more like the question which is regarding the integration part. Please refer the below link for merchant technical support. 

[https://www.paypal.com/in/smarthelp/article/how-do-i-get-merchant-technical-support,-such-as-for-paypal-product-integrations,-apis-or-sandbox-testing-faq3723](url)

Please visit [Merchant Technical Support](https://www.paypal-techsupport.com/app/) and submit your question for merchant/developer technical support, such as for PayPal product integrations/APIs

Thanks!
