### ISSUE TITLE
The API v1 is deprecated. Will support v2?

### ISSUE THREAD

**Issue by manyeung** [paypal/PayPal-PHP-SDK#1275]
I noticed that the v1 of API is deprecated. Will the SDK support v2 in the near future? 
At this moment, should I develop my own code in order to support v2?

**Comment by Sebi94nbg** [comment]
Isn't this branch for v2? https://github.com/paypal/PayPal-PHP-SDK/tree/2.0-beta

**Comment by manyeung** [comment]
@Sebi94nbg I had a look. The endpoint is using v1.

**Comment by Sebi94nbg** [comment]
Ah, you're right. Missunderstood this migration from v1 thing. This was only about migrating from v1 of this library to v2, not the API itself.

Where did you read, that the v1 API is deprecated?

**Comment by manyeung** [comment]
here: https://developer.paypal.com/docs/api/payments/v1/

**Comment by manyeung** [comment]
and here is for the subscription: https://developer.paypal.com/docs/api/payments.billing-agreements/v1/

**Comment by Sebi94nbg** [comment]
Mhmmm, ok. I believe, we need to contact the PayPal support by phone since here is never ever anyone replying.

**Comment by kslimani** [comment]
According documentation, billing agreement is deprecated for subscriptions : https://developer.paypal.com/docs/subscriptions/

I did not find any PHP SDK or migration guide.

**Comment by manyeung** [comment]
Here is an article about paypal v2:
https://medium.com/paypal-engineering/launch-v2-paypal-checkout-apis-45435398b987

**Comment by manyeung** [comment]
Perhaps we can send a feedback to PayPal:
https://www.paypal-survey.com/survey/selfserve/229d/190203#?

**Comment by Sebi94nbg** [comment]
I just got the following feedback from the PayPal tech support by email:
- REST API v1 is deprecated, but it is currently not planned to remove it soon or to discontinue the support of it
- REST API v2 is currently only supported by the [Checkout SDK](https://github.com/paypal/Checkout-PHP-SDK), but this supports currently only `v2/checkout/orders` and `v2/payments` (Subscriptions and all other features are not supported yet)
- There is currently no known time plan, when PayPal will bring over all other missing features like subscriptions (billing plans) and so on to the Checkout SDK
- PayPal said, that you can use the Checkout SDK for `orders` and `payments` and for all other features, you have to continue using this SDK here
- The other "solution" would be to build your own SDK, which uses the v2 API

**Comment by kristian-b** [comment]
The response from the PayPal team sounds like they don't care anymore about the PHP SDK.

**Comment by JexPY** [comment]
Should we all move to braintree_php as they don't care about paypal_sdk any more?

**Comment by prakash-gangadharan** [comment]
similar question : https://github.com/paypal/PayPal-PHP-SDK/issues/1251
