### ISSUE TITLE
Paypal Cancel subscription through API not working

### ISSUE THREAD

**Issue by wsfreelanzer** [paypal/PayPal-PHP-SDK#1277]
I am trying to cancel the Paypal subscription through the api. I followed this doc. https://developer.paypal.com/docs/api/subscriptions/v1/#subscriptions_cancel

According to this document.

`curl -v -X POST https://api.sandbox.paypal.com/v1/billing/subscriptions/I-BW452GLLEP1G/cancel \ -H "Content-Type: application/json" \ -H "Authorization: Bearer Access-Token" \ -d '{ "reason": "Not satisfied with the service" }'`

As per this, i created the following CURL

	```
$ch = curl_init();
	curl_setopt($ch, CURLOPT_URL, 'https://api.sandbox.paypal.com/v1/billing/subscriptions/I-X88N77T9HN56/cancel');
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"reason\":\"Not satisfied with the service\"}");
	curl_setopt($ch, CURLOPT_POST, 1);
	
	$headers = array();
	$headers[] = 'Content-Type: application/json';
	$headers[] = 'Authorization: Bearer '.$access_token;
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	
	$result = curl_exec($ch);
	if (curl_errno($ch)) {
		echo 'Error:' . curl_error($ch);
	}
	curl_close($ch);
	
	if(empty($result))die("Error: No response.");
	else
	{
		$json = json_decode($result);
		echo "<pre>";
		print_r($json);
		echo "</pre>";
	}
```

Its not working for me, i am getting this following errors.

stdClass Object
(
    [name] => RESOURCE_NOT_FOUND
    [message] => The specified resource does not exist.
    [debug_id] => f8c1c32066dd7
    [details] => Array
        (
            [0] => stdClass Object
                (
                    [issue] => INVALID_RESOURCE_ID
                    [description] => Requested resource ID was not found.
                )

        )

    [links] => Array
        (
            [0] => stdClass Object
                (
                    [href] => https://developer.paypal.com/webapps/developer/docs/api/#INVALID_RESOURCE_ID
                    [rel] => information_link
                    [method] => GET
                )

        )

)

**Comment by prakash-gangadharan** [comment]
Similar issue : https://github.com/paypal/PayPal-PHP-SDK/issues/1251

**Comment by prakash-gangadharan** [comment]
@wsfreelanzer, https://developer.paypal.com/docs/api/subscriptions/v1/ is the new API end point. 
For rest sdks currently we do not have any stipulated timeline to replace the deprecated endpoints with the newer one but it may be available in near future.
