### ISSUE TITLE
How to validate subscription

### ISSUE THREAD

**Issue by Giacomo92** [paypal/PayPal-PHP-SDK#1279]
Hi everyone,
I am running a few subscription tests. I cannot understand how I can test a payment error (the availability is lower than price plan). 
Is this case handle by [this](https://github.com/paypal/PayPal-PHP-SDK/blob/647c8c49bc40a2a5fb7c76d2dfc5a9c6ee57c789/sample/billing/ExecuteAgreement.php#L30)  exception block?

How can I handle the order state change?

I want to be sure to switch the order state to payed only when the transaction is successful.

Than you

**Comment by prakash-gangadharan** [comment]
Hi @Giacomo92, for Exception Handling refer to the below link 
https://github.com/paypal/PayPal-PHP-SDK/wiki/exception-%27PayPal%5CException%5CPayPalConnectionException%27-with-message-%27Got-Http-response-code-400-when-accessing

Let us know if you face any challenges.
