### ISSUE TITLE
Billing agreement without a plan

### ISSUE THREAD

**Issue by W3b3r** [paypal/PayPal-PHP-SDK#1280]
Hi,

I want to create a billing agreement without plan to bill my user when place a order on the web site without do the process of the authentication through paypal payment flow.
I'm using this sdk for normal payment flow, but i think is useless for my needs.

How i can do for create a billing agreement and bill my user automatic by using agreement_id at the checkout?
Which is the flow to use to create the authorization id and then make the automatic payment when they do checkout?

In some cases my user send order through the api of web site and they visit site from browser to pay the order.
I don't even want to use paypal's express checkout button.

I hope I was clearer
Thanks in advace.

Best

**Comment by prakash-gangadharan** [comment]
Hi @W3b3r, this is more like the question which is regarding the integration part. Please refer the below link for merchant technical support.
https://www.paypal.com/in/smarthelp/article/how-do-i-get-merchant-technical-support,-such-as-for-paypal-product-integrations,-apis-or-sandbox-testing-faq3723

Please visit [Merchant Technical Support](https://www.paypal-techsupport.com/app/) and submit your question for merchant/developer technical support, such as for PayPal product integrations/APIs

Thanks!
