### ISSUE TITLE
The right flow to subscriptions with PayPal-PHP-SDK

### ISSUE THREAD

**Issue by rodrigoguariento** [paypal/PayPal-PHP-SDK#1281]
I'm using [REST API SDK for PHP](https://github.com/paypal/PayPal-PHP-SDK) to create a subscription.

Firstly, I've coded a class to [Create Billing Plan](https://paypal.github.io/PayPal-PHP-SDK/sample/#billing), [Activate Plan](https://paypal.github.io/PayPal-PHP-SDK/sample/#billing) and after [Create Billing Agreement With PayPal](https://paypal.github.io/PayPal-PHP-SDK/sample/#billing) (step 1 and 2).

After step 2 ([Execute Agreement](https://paypal.github.io/PayPal-PHP-SDK/sample/doc/billing/ExecuteAgreement.html)), the buyer is subscribed into the plan, right? (Yes/No?)

How can I [Capture amount on subscription](https://developer.paypal.com/docs/subscriptions/full-integration/subscription-management/#capture-amount-on-subscription) like described at [Full Integration](https://developer.paypal.com/docs/subscriptions/full-integration/) documentation? Am I right about this steps? Or after [execute agreement](https://paypal.github.io/PayPal-PHP-SDK/sample/doc/billing/ExecuteAgreement.html) (step 2) this capture have been made?

Is missing some step? My goal was put buyer into a subscription and capture money every month to merchant. Are these steps sufficient?

Thank you.

Note: why I'm asking it? Because haven't found a way to test this capture with myemail-**facilitator**@myserver.com (business) that I've found into [Sandbox Accounts](https://developer.paypal.com/developer/accounts).

**Comment by prakash-gangadharan** [comment]
@rodrigoguariento use _billing plans_ and _billing agreements_ to create an agreement for a recurring PayPal payment for goods or services.

> [Create Billing Plans](https://developer.paypal.com/docs/api/quickstart/create-billing-plan/#)
- [Define the billing plan object](https://developer.paypal.com/docs/api/quickstart/create-billing-plan/#define-the-billing-plan-object)
- [Create and activate billing plan](https://developer.paypal.com/docs/api/quickstart/create-billing-plan/#create-and-activate-billing-plan)

> [Create Billing Agreements](https://developer.paypal.com/docs/api/quickstart/create-billing-agreement/#)
- [Create billing agreement attribute object ](https://developer.paypal.com/docs/api/quickstart/create-billing-agreement/#create-billing-agreement-attribute-object)
- [Create billing agreement (PayPal)](https://developer.paypal.com/docs/api/quickstart/create-billing-agreement/#create-billing-agreement-paypal)
- [Execute billing agreement ](https://developer.paypal.com/docs/api/quickstart/create-billing-agreement/#execute-billing-agreement)

After buyer approves you extract the token, call the billing agreement execute method to complete the billing agreement.
