### ISSUE TITLE
Update quantity of product or service in subscription

### ISSUE THREAD

**Issue by hodela** [paypal/PayPal-PHP-SDK#1284]
We want to build a subscription feature similar to Github. 
Our customers are companies, they will buy the number of seats equal to their number of employees. Each seat is priced at $100, on July 15, customers buy 5 seats and pay $500, 15 days later (July 30), they buy another 5 seats, we do this via API and check subscription updated quantity to 10. But no payment transaction occurred (for 5 new seats).
We want customers to pay for 5 new seats from July 30 to August 15 ($250) immediately. By August 15, they will pay for 10 seats ($1000). Is it possible to do this with Paypal or what steps do I lack?

**Comment by prakash-gangadharan** [comment]
Hi @hodela, this is more like the question which is regarding the integration part. Please refer the below link for merchant technical support.
https://www.paypal.com/in/smarthelp/article/how-do-i-get-merchant-technical-support,-such-as-for-paypal-product-integrations,-apis-or-sandbox-testing-faq3723

Please visit [Merchant Technical Support](https://www.paypal-techsupport.com/app/) and submit your question for merchant/developer technical support, such as for PayPal product integrations/APIs

Thanks!
