### ISSUE TITLE
Webhook PAYMENT.CAPTURE.COMPLETED never arrives

### ISSUE THREAD

**Issue by novaknole** [paypal/PayPal-PHP-SDK#1287]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description

I am using Javascript sdk(smart payment buttons) in client-side. After user pays in paypal popup, I am expected to receive the events on my back-end listener url because I've set up webhook with the listener URL and all events. 

It turns out that the only events I can get are PAYMENT.CAPTURE.PENDING and CHECKOUT.ORDER.APPROVED.  Why don't I get PAYMENT.CAPTURE.COMPLETED or PAYMENT.CAPTURE.DENIED?

I really need those to also arrive since if my server fails when user pays through client side and me making api call never arrives to my server ,I want to have webhook so that when it's completed, it's gonna throw the event. Right now, it doesn't so i might have to tell user that he has paid, but my database hasn't been updated so you can't get the product. 

What should I do?

**Comment by prakash-gangadharan** [comment]
Hi @novaknole, if this not an integration issue with PayPal-PHP-SDK, refer the below link for merchant technical support.
https://www.paypal.com/in/smarthelp/article/how-do-i-get-merchant-technical-support,-such-as-for-paypal-product-integrations,-apis-or-sandbox-testing-faq3723

Please visit [Merchant Technical Support](https://www.paypal-techsupport.com/app/) and submit your question for merchant/developer technical support, such as for PayPal product integrations/APIs

Thanks!
