### ISSUE TITLE
PayPal Subscription (Billing Plan): Get Agreement ID

### ISSUE THREAD

**Issue by Sebi94nbg** [paypal/PayPal-PHP-SDK#1290]
### General information

* SDK/Library version: 1.14.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: -
* Language, language version, and OS: PHP 7.x on Debian 9.x

### Issue description

I want to create subscriptions, that my customers automatically pay a specific amount every month without the need to do this manually every month.

First of all: It is very confusing, when the documentation uses different names than this library. This should change with v2!

So, right now, my workflow is the following:

1. Customer creates a subscription by defining the amount and interval (eg. 20 Euro every 1 month)
2. My application creates a plan as described here: [sample/billing/CreatePlan.php](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/billing/CreatePlan.php) (and saves the ID of the plan in the applications database)
3. As soon as the plan has been created and has the state `ACTIVE`, it will create the actual subscription (here called "agreement") as described here: [sample/billing/CreateBillingAgreementWithPayPal.php](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/billing/CreateBillingAgreementWithPayPal.php) (here, I can NOT save the ID of the subscription (agreement), because it does not have or provide any ID yet until it has been approved)
4. My application redirects the user the the approval link from `$agreement->getApprovalLink()`
5. Customer approves the subscription / agreement
6. Customer gets redirected back to my application, where he can see the message, that he has successfully created the subscription

Now, the PayPal webhook (notification / event) triggers those events:

- BILLING.PLAN.CREATED
- BILLING.PLAN.UPDATED
- BILLING.SUBSCRIPTION.CREATED

The event `BILLING.SUBSCRIPTION.CREATED` contains now the ID of the subscription (agreement), but my big problem is now, that I can not see any reference to the used plan. How can I link this created subscription now with my already saved plan? I need this information in order to assign this subscription to my correct customer.

The documentation says, that the response returns "plan_id", but this does not exist: https://developer.paypal.com/docs/api/subscriptions/v1/#subscriptions_create

I'm still not sure, when I can or should charge the customer. As soon as I receive the webhook `BILLING.SUBSCRIPTION.CREATED`? Or will there be a different webhook?

And what about this? [sample/billing/ExecuteAgreement.php](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/billing/ExecuteAgreement.php)

Should this be triggered, when the user gets redirected to the application or when a specific webhook event was sent?

**Comment by rossaddison** [comment]
Can you not just try assigning a session variable as in the following code: 
                      
                       $patchRequest = new PatchRequest();
                       $patchRequest->addPatch($patch);
                       $createdPlan->update($patchRequest, $apiContext);
                       ......$SESSION variable  = $createdPlan->getId();
                       $patchedPlan = Plan::get($createdPlan->getId(), $apiContext);

And then use and capture this session variable's value in your database once the agreement has been executed and user passed back to your website in the paypal success redirect to your site.

**Comment by Sebi94nbg** [comment]
No, a SESSION variable is unfortunately no solution since the webhook does not know this variable and the user may not click on "return to merchant / shop".

**Comment by prakash-gangadharan** [comment]
@Sebi94nbg Use _billing plans_ and _billing agreements_ to create an agreement for a recurring PayPal payment for goods or services.

> [Create Billing Plans](https://developer.paypal.com/docs/api/quickstart/create-billing-plan/#)
- [Define the billing plan object](https://developer.paypal.com/docs/api/quickstart/create-billing-plan/#define-the-billing-plan-object)
- [Create and activate billing plan](https://developer.paypal.com/docs/api/quickstart/create-billing-plan/#create-and-activate-billing-plan)

> [Create Billing Agreements](https://developer.paypal.com/docs/api/quickstart/create-billing-agreement/#)
- [Create billing agreement attribute object ](https://developer.paypal.com/docs/api/quickstart/create-billing-agreement/#create-billing-agreement-attribute-object)
- [Create billing agreement (PayPal)](https://developer.paypal.com/docs/api/quickstart/create-billing-agreement/#create-billing-agreement-paypal)
- [Execute billing agreement ](https://developer.paypal.com/docs/api/quickstart/create-billing-agreement/#execute-billing-agreement)

After buyer approves you extract the token, call the billing agreement execute method to complete the billing agreement.

**Comment by prakash-gangadharan** [comment]
https://developer.paypal.com/docs/api/subscriptions/v1/#subscriptions_create is the new API end point. 
Currently we do not have any stipulated timeline to replace the deprecated endpoints with the newer one but it may be available in near future.
