### ISSUE TITLE
415 UNSUPPORTED_MEDIA_TYPE - Disputes Provide Evidence API

### ISSUE THREAD

**Issue by Arvind6353** [paypal/PayPal-PHP-SDK#1291]
### General information

* SDK/Library version: PayPal-PHP-SDK 2.0.0b1
* Environment: Production
* `PayPal-Debug-ID` values: d6872acae31

### Issue description

Getting ```
{"name":"UNSUPPORTED_MEDIA_TYPE","debug_id":"d6872acae31","message":"The server does not support the request payload’s media type","information_link":"https://developer.paypal.com/docs/api/customer-disputes/#errors"}```
when trying DisputesProvideEvidence API in live environment

UserAgent - PayPalSDK/PayPal-PHP-SDK 2.0.0b1 (platform-ver=7.1.11; bit=64; os=Linux_3.10.0-957.5.1.el7.x86_64; machine=x86_64; crypto-lib-ver=1.0.2k-fips; curl=7.29.0)

Please help with the issue . The same api is working with CURL but failing when using this SDK .

**Comment by xjijies** [comment]
Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.
Please Check PayPal Community (https://www.paypal-community.com )and MTS ( https://paypal.com/mts )
Thanks!
