### ISSUE TITLE
make a failed payment in paypal php sdk

### ISSUE THREAD

**Issue by AO-IO** [paypal/PayPal-PHP-SDK#1293]
### General information

* SDK/Library version: paypal/rest-api-sdk-php with laravel 5.8
* Environment: sandbox

### Issue description

How I can make a failed payment in the sandbox?  

I read that you put the error code in the amount but it doesn't give any error?

**Comment by prakash-gangadharan** [comment]
@AO-IO, what is the exact error code/scenario you trying to do. Can you give some context?
