### ISSUE TITLE
i am redirecting to the paypal successfully but when i pay a payment it is not deducting from my account and shows successfully paid but payment is not deducted 

### ISSUE THREAD

**Issue by jhonny112** [paypal/PayPal-PHP-SDK#1297]
i have a issue when i redirect to paypal by redirect url and try to checkout with guest payment with my credit card no payment shows there and when i fill there form to pay no payment is decucting by my account and not get payment in my paypal account here is my code . 

`<?php
// 1. Autoload the SDK Package. This will include all the files and classes to your autoloader
// Used for composer based installation
$qty=$_REQUEST['qty'];
$total=$_REQUEST['total'];
$fullname=$_REQUEST['fullname'];
$email=$_REQUEST['email'];
$contact=$_REQUEST['contact'];

$question=$_REQUEST['question'];
$ticketid=$_REQUEST['ticketid'];
$eventid=$_REQUEST['eventid'];
$uid=$_REQUEST['uid'];
$testt="http://down4events.com/makeevent1.php?view=".$eventid;

require __DIR__  . '/PayPal-PHP-SDK/autoload.php';
// Use below for direct download installation
// require __DIR__  . '/PayPal-PHP-SDK/autoload.php';

$apiContext = new \PayPal\Rest\ApiContext(
        new \PayPal\Auth\OAuthTokenCredential(
            '12345',     // ClientID
            '12345'      // ClientSecret
        )
);

$apiContext->setConfig(
      array(
         'mode' => 'live',
        'log.LogEnabled' => true,
        'log.FileName' => 'PayPal.log',
        'log.LogLevel' => 'DEBUG'
      )
);

// After Step 2
 $payer = new \PayPal\Api\Payer();
 $payer->setPaymentMethod('paypal');
//  $execution = new \PayPal\Api\PaymentExecution();
//     $execution->setPayerId($request->payerID);

$amount = new \PayPal\Api\Amount();
$total=$_REQUEST['total'];
 //$total;
 
$amount->setTotal($total);
$amount->setCurrency('USD');

$transaction = new \PayPal\Api\Transaction();
$transaction->setAmount($amount);
//   $execution->addTransaction($transaction);

 $redirectUrls = new \PayPal\Api\RedirectUrls();
$redirectUrls->setReturnUrl("http://down4events.com/index.php")
    ->setCancelUrl($testt);

 $payment = new \PayPal\Api\Payment();
 $payment->setIntent('sale')
    ->setPayer($payer)
    ->setTransactions(array($transaction))
    ->setRedirectUrls($redirectUrls);
    

    
     $_SESSION['payer']=$payer;
    $_SESSION['amount']=$total;
    try {
        

echo $payment->create($apiContext);
//   $execution->addTransaction($transaction);
//  $result = $payment->execute($execution, $apiContext);

    //echo $payment;
 $myurl= $payment->getApprovalLink();
$finurl=$myurl."&amount=".$total;
 //   echo "\n\nRedirect user to approval_url: " . $payment->getApprovalLink() . "\n";
 

 echo '	<meta http-equiv="refresh" content="0;url='.$finurl.' " />';   
}
catch (\PayPal\Exception\PayPalConnectionException $ex) {
    // This will print the detailed information on the exception.
    //REALLY HELPFUL FOR DEBUGGING
     $ex->getData();
  
}

?>`

**Comment by prakash-gangadharan** [comment]
Hi @jhonny112 ,  can you help here with the ec-token which you used for the guest checkout or paypal debug id/PAYID for the create payment?

Thanks!

**Comment by AlbertoSinigaglia** [comment]
Are you sure to have correctly implemented both first and second part of the payment iter?
the first one creates a payment, but it's the second that create the transaction 
check:  [first field of this table](http://paypal.github.io/PayPal-PHP-SDK/sample/#payments)

**Comment by prakash-gangadharan** [comment]
Hi @jhonny112, to **Process PayPal Payments** / create a PayPal payment below are the steps.

- [Define payment](https://developer.paypal.com/docs/api/quickstart/payments/#define-payment)
- [Create payment](https://developer.paypal.com/docs/api/quickstart/payments/#create-payment)
- [Execute payment](https://developer.paypal.com/docs/api/quickstart/payments/#execute-payment)

Let us know if you are facing any challenges.
