### ISSUE TITLE
Changing Landing Page Type to Billing not working on production

### ISSUE THREAD

**Issue by marcelo2605** [paypal/PayPal-PHP-SDK#1303]
I generated a web profile to both sandbox and production versions. The only two config are:

```
$inputFields = new \PayPal\Api\InputFields();
$inputFields->setNoShipping(1);

$flowConfig = new \PayPal\Api\FlowConfig();
$flowConfig->setLandingPageType('Billing');
```

I checked and that infos are stored in both profiles. Sandbox redirect to Billing landing page, but production still redirect to Login landing page.

Any idea what could causing this error?

**Comment by prakash-gangadharan** [comment]
Hi @marcelo2605,  do you have the impacted ec-token?

**Comment by marcelo2605** [comment]
Hey @prakash-gangadharan I made another test: Here is the generated URL: https://www.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-02Y234243J582373D. This is what you ask?

**Comment by marcelo2605** [comment]
I will close this issue. I changed client and secret token, generated a new profile and the problem was fixed.
