### ISSUE TITLE
Payment received confirmation email

### ISSUE THREAD

**Issue by maticb** [paypal/PayPal-PHP-SDK#1305]
### General information

* SDK/Library version:    "paypal/rest-api-sdk-php": "^1.14",
* Environment:  Prod
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description

Hello,

we have a payment implementation with this sdk, going roughly like this:
...
 $payment = new Payment();
...
 $payment->create($this->getApiContext());
...

This redirects to a confirmation page:

..
  $paymentId = $_GET['paymentId'];
  $payment = Payment::get($paymentId, $apiContext);
...
 $getCapture = $authorization->capture($capture, $apiContext)
...

The first part is using the "authorize" intent and the second is capturing the payment and confirming order paid.

Now my problem is that the seller is not receiveing emails "You have received a pyment from..." and I am not sure if this is a setting in the SDk or the paypal account, and all the googling leads me to IPN messages which is not what I need.

Can anyone point mein the right direction, thanks.

**Comment by prakash-gangadharan** [comment]
Hi @maticb 

- We do not send emails to the merchant at Authorization/capture time for EC AS1 integrations.
- The reason behind it, is to not flood the merchant's inbox with the auth & capture emails.
- Merchants are expected to rely on IPNs for getting the status of the payment, else they can rely on the API response.

**Comment by maticb** [comment]
@prakash-gangadharan , I assumed that, thank you for the explanation.
