### ISSUE TITLE
How to get customer name and email from webhook sale event?

### ISSUE THREAD

**Issue by kangarko** [paypal/PayPal-PHP-SDK#1307]
### General information
* Environment: live
* Version: 1.14.0

### Issue description
I am listening for webhook notification about a new sale. This is the data I am getting: https://pastebin.com/jfAbi2e9

I want to get the customers name and email. When I try to get the sale by the ID but I am getting just the sale data and I don't see the customer's name and email. My code:

![a](https://i.imgur.com/OZsW7Cm.png)

How can I get this + his email please?

![a](https://i.imgur.com/t4x0Tew.png)

Thank you.

**Comment by prakash-gangadharan** [comment]
@kangarko, can you add the `Paypal-debug-id` for this error?

**Comment by kangarko** [comment]
How can I get this?

**Comment by kangarko** [comment]
I changed the Payment to Sale and fixed the ID, now it returns a Sale but still there is no customer name:

![a](https://i.imgur.com/OZsW7Cm.png)

How can I get this + his email please?

![a](https://i.imgur.com/t4x0Tew.png)

**Comment by prakash-gangadharan** [comment]
@kangarko , let us take a look and is this live transaction id?

**Comment by kangarko** [comment]
Yes everything is live.

**Comment by prakash-gangadharan** [comment]
Can you try calling the Show payment details API
[Developer API Reference link](https://developer.paypal.com/docs/api/payments/v1/#payment_get)
```php
try {
    $payment = Payment::get($createdPayment->getId(), $apiContext);
} catch (Exception $ex) {    
exit(1);
}
```

**Comment by kangarko** [comment]
Yes it's done through a website where you can buy small digital goods, then it redirects to paypal.

And? How can I get the customer's name and email?

**Comment by prakash-gangadharan** [comment]
@kangarko,  checking on that

**Comment by kangarko** [comment]
@prakash-gangadharan and?

**Comment by kangarko** [comment]
@prakash-gangadharan 10 days and no answer for such a simple question?

**Comment by prakash-gangadharan** [comment]
I forwarded your query to our product team to check is there way to get  customer's name and email for the wps payments.
Since you are calling get sale method which internally uses [Show sale details](https://developer.paypal.com/docs/api/payments/v1/#sale_get)
as per docs it shows details for a sale by ID. Returns only sales that were created through the REST API.

**Comment by prakash-gangadharan** [comment]
@kangarko, below are the steps for the ideal way to **Process PayPal Payments** / create a PayPal payment using sdk.

- [Define payment](https://developer.paypal.com/docs/api/quickstart/payments/#define-payment)
- [Create payment](https://developer.paypal.com/docs/api/quickstart/payments/#create-payment)
- [Execute payment](https://developer.paypal.com/docs/api/quickstart/payments/#execute-payment) - [API reference link](https://developer.paypal.com/docs/api/payments/v1/#payment_execute)

The response contain [payer](https://developer.paypal.com/docs/api/payments/v1/#definition-payer) -> [payer_info](https://developer.paypal.com/docs/api/payments/v1/#definition-payer_info) which has the  customer's name and email.

**Comment by kangarko** [comment]
@prakash-gangadharan I absolutely have no idea how to proceed. I don't think I can create the payment. I am using webhooks to listen to existing ones.

Let me restate my question so we are clear:

How can I, using PayPal PHP SDK, get the payer name and email from the following transaction?
![a](https://i.imgur.com/LEAeCfl.png)

Thanks.

**Comment by prakash-gangadharan** [comment]
@kangarko, This is a transaction which is done via buynow paypal button (WPS payment - WEBSITE_PAYMENT_STANDARD). It is not feasible to get payer name and email for this transaction using PayPal PHP SDK.

**Comment by kangarko** [comment]
@prakash-gangadharan it is possible, I am using quaderno.io to handle my taxes and they are able to use your [API](https://i.imgur.com/eNWDNf7.png) well enough to get this information. 

So how can I get this?

**Comment by kangarko** [comment]
@prakash-gangadharan so? 

If anyone is reading this, I am very disappointed at how PayPal deals with their technical support. I contacted their email support but was directed here, which is a ghost town where no one is able to help. As you can see the person marked as Contributor does not know understand the API himself! Overall I can only recommend Stripe, I've had thousand times better experience with them and the only reason I am still dealing with PayPal is that a lot of my customers use it.

**Comment by lmarkus** [comment]
@kangarko , I looked at your integration on spigotmc.org, and you're using one of our older payment products, known as the "Buy Now" button.  These SDKs are wrappers for our more modern REST APIs, and as such don't have support for the older product types.  

You have a couple of choices:
1) For an easy fix, you'll need to use IPN (Instant Payment Notifications). This was the original webhook-like product that was meant to work in conjunction with the button that SpigotMC is using.   IPN Notifications will include the full payment details you're looking for, and won't require a follow-up call to paypal to retrieve more information. I see that the current integration is already using `notify_url`, so you may already be receiving these messages at `<input type="hidden" name="notify_url" value="https://www.spigotmc.org/bdpaygate/callback.php?p=paypalcpa">`    For more details, here's the IPN Integration guide: https://developer.paypal.com/docs/classic/ipn/integration-guide/IPNIntro/ 

2) If this is within your control, I would recommend that you use the more modern smart payment buttons ( https://www.paypal.com/buttons/smart ). These will give you a lot more flexibility in integrations choices, webbhooks, and SDK support. In addition it will allow your customers access to additional funding choices like Venmo, credit, and other alternative payment methods ). Apologies for the confusion, and hope this helps.

**Comment by kangarko** [comment]
Sorry, but SpigotMC is out of my control. It works like Google play. I am only a publisher my these products there and have 0 control over how they handle payments.

Neither of your solutions are thus applicable. I have tried IPN system before with Zapier but it failed since SpigotMC overtakes forcefully over it to listen to payments and give customers access to the products right after the purchase.

There _is_ a way to programatically get a customer's name and email from the transactions ID. How can I do so? Any way after the transaction has been made.

**Comment by lmarkus** [comment]
You can still use IPNs through your account settings. (Independent of SpigotMC). When a payment hits your account PayPal should send you an IPN, if you've enabled it through here:  https://www.paypal.com/cgi-bin/customerprofileweb?cmd=_profile-ipn-notify

**Comment by lmarkus** [comment]
All that said, this team specifically supports issues with the SDK, we're not equipped for full fledged merchant support on GitHub.  I would recommend you reach to our Merchant Tech Support specialists, ( http://paypal.com/mts ), as they will be the better team to help you find the right solution.

**Comment by kangarko** [comment]
Thanks

Anyone wondering how I solved it, I used NVP on top of the webhook. Here's how: https://stackoverflow.com/a/53408834
