### ISSUE TITLE
Test Authorize and Capture Process [response code 404]

### ISSUE THREAD

**Issue by luciano88** [paypal/PayPal-PHP-SDK#1310]
### General information

* SDK/Library version: 1.14.0
* Environment: Sandbox
* Language, language version, and OS: PHP7

### Issue description

I want to test authorize&capture process. I'm purchasing an item from a sandbox account (buyer) to another sandbox account (merchant). They belong to the same main Paypal account. And I'm getting this error when I try to capture an authorized payment:

"Got Http response code 404 when accessing https://api.sandbox.paypal.com/v1/payments/authorization/PAYID-LXA2YXY8NC48194EA8533310."

Is it possible that this error is due to the fact that both the accounts have been created in the same Paypal account? Or am I missing something in the code?

```
public function capturePayment($orderId, $ordersItemsIds) {
        $authorizationId = $myPaymentId;
        try {
            $authorization = Authorization::get($paymentId, $this->apiContext);

            $amt = new Amount();
            $amt->setCurrency("EUR")
                ->setTotal($myAmount);

            ### Capture
            $capture = new Capture();
            $capture->setAmount($amt);

            $getCapture = $authorization->capture($capture, $this->apiContext);
        } catch (Exception $ex) {
            exit(1);
        }
}
```

ps. as authorizationId I'm using the paymentId (PAYID-LXA2YXY8NC48194EA8533310).

**Comment by prakash-gangadharan** [comment]
Hi @luciano88, can you help us with the `paypal-debud-id`?
Refer the below link to Understand your exception.
https://github.com/paypal/PayPal-PHP-SDK/wiki/exception-%27PayPal%5CException%5CPayPalConnectionException%27-with-message-%27Got-Http-response-code-400-when-accessing

**Comment by luciano88** [comment]
> Hi @luciano88, can you help us with the `paypal-debud-id`?
> Refer the below link to Understand your exception.
> https://github.com/paypal/PayPal-PHP-SDK/wiki/exception-%27PayPal%5CException%5CPayPalConnectionException%27-with-message-%27Got-Http-response-code-400-when-accessing

{"name":"INVALID_RESOURCE_ID","message":"The requested resource ID was not found","information_link":"https: //developer.paypal.com/docs/api/payments/#errors","debug_id":"eb5a66eaebd9f"}

**Comment by prakash-gangadharan** [comment]
Hi @luciano88,  you should pass the authorizationId in the Get call, not the paymentId
Refer this sample : https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/GetAuthorization.php

Revert us back if you have questions.
```

try {
    // Retrieve the authorization
    $result = Authorization::get($authorizationId, $apiContext);
} catch (Exception $ex) {
    // NOTE: PLEASE DO NOT USE RESULTPRINTER CLASS IN YOUR ORIGINAL CODE. FOR SAMPLE ONLY
    ResultPrinter::printError("Get Authorization", "Authorization", null, null, $ex);
    exit(1);
}
```
