### ISSUE TITLE
Sandbox and Live account, Payment not deducting from buyer account.

### ISSUE THREAD

**Issue by Alwafaa123** [paypal/PayPal-PHP-SDK#1312]
Sandbox and a live account having the same issue, we tried payment and we are getting the payment id and payer id, token id we are getting but not deducting the amount from the personal account. Please let me know what configuration I missed on the same.

![2019-11-24 (1)](https://user-images.githubusercontent.com/58136137/69493926-b6bb4700-0ece-11ea-864e-f080f97e62ae.png)
![2019-11-24](https://user-images.githubusercontent.com/58136137/69493928-b6bb4700-0ece-11ea-845f-d1b52abac5dc.png)

**Comment by prakash-gangadharan** [comment]
Hi @Alwafaa123, to **Process PayPal Payments** / create a PayPal payment below are the steps.

- [Define payment](https://developer.paypal.com/docs/api/quickstart/payments/#define-payment)
- [Create payment](https://developer.paypal.com/docs/api/quickstart/payments/#create-payment)
- [Execute payment](https://developer.paypal.com/docs/api/quickstart/payments/#execute-payment)

Let us know if you are facing any challenges.
