### ISSUE TITLE
How to change Store Name on Checkout process?

### ISSUE THREAD

**Issue by dylanmichaelryan** [paypal/PayPal-PHP-SDK#1313]
Hey,

how do i change the store name at the checkout process? Default one seems to be "John Doe's Test Store"..

i would really appreciate it if someone could help me with this!

thanks in advance

**Comment by prakash-gangadharan** [comment]
Hi @dylanmichaelryan 
You can change the store name at the checkout process  through below steps,
- Login into Merchant account (sandbox.paypal.com)
- Select Account Setting 
- Then select Business information under BUSINESS PROFILE
- Update the business name.

Screenshot:
![image](https://user-images.githubusercontent.com/13796434/69524496-2e9b7700-0f8c-11ea-9a28-d6a925cf6287.png)
