### ISSUE TITLE
Fund Amount Transfer Issue 

### ISSUE THREAD

**Issue by upendraalwafaa** [paypal/PayPal-PHP-SDK#1316]
After payment the amount is not deducting from customer account or not transferring to integrated sandbox account.
Sir please can you help me.

![22](https://user-images.githubusercontent.com/32842147/69626658-81dff900-1062-11ea-90e5-322ec7f2684b.PNG)

**Comment by prakash-gangadharan** [comment]
Hi @upendraalwafaa, to **Process PayPal Payments** / create a PayPal payment below are the steps.

- [Define payment](https://developer.paypal.com/docs/api/quickstart/payments/#define-payment)
- [Create payment](https://developer.paypal.com/docs/api/quickstart/payments/#create-payment)
- [Execute payment](https://developer.paypal.com/docs/api/quickstart/payments/#execute-payment)

Let us know if you are facing any challenges.

**Comment by prakash-gangadharan** [comment]
Similar issue : https://github.com/paypal/PayPal-PHP-SDK/issues/1312

**Comment by upendraalwafaa** [comment]
> Hi @upendraalwafaa, to **Process PayPal Payments** / create a PayPal payment below are the steps.
> 
> * [Define payment](https://developer.paypal.com/docs/api/quickstart/payments/#define-payment)
> * [Create payment](https://developer.paypal.com/docs/api/quickstart/payments/#create-payment)
> * [Execute payment](https://developer.paypal.com/docs/api/quickstart/payments/#execute-payment)
> 
> Let us know if you are facing any challenges.

Thanks working perfect.
