### ISSUE TITLE
Instrument declined - December 2019

### ISSUE THREAD

**Issue by mdeprezzo** [paypal/PayPal-PHP-SDK#1318]
### General information

* SDK/Library version: 1.14.0
* Environment: live
* `PayPal-Debug-ID` values: 479c9d5bc73f3
* Language, language version, and OS: php 7.2 on ubuntu

### Issue description

Is a few days, that sometimes in live mode, i see that error "Instrument declined", but i don't understand if for the version of that sdk, or because the customers had a problem on their bank account or credit card. Am i missing something ?

**Comment by prakash-gangadharan** [comment]
Hi @mdeprezzo, do you have more occurrence of this issue? if yes share the same with `PayPal-Debug-ID`

**Comment by mdeprezzo** [comment]
Sure, here the other debug id:

- 4b94a3145255f
- cbfca9e9cdd5d
- a5227872dabac
- 25752debf6ca3

**Comment by prakash-gangadharan** [comment]
Hi @mdeprezzo,  I checked with internal product team and advised that these were primarily due to “INSUFFICIENT_FUNDS” response from the processor and these are valid and legit declines.

**Comment by mdeprezzo** [comment]
@prakash-gangadharan ok thanks. I'm closing the issue. For now
