### ISSUE TITLE
PayPal get all transactions

### ISSUE THREAD

**Issue by nicdnepr** [paypal/PayPal-PHP-SDK#1321]
Hi
How can I get  PayPal all transactions and get not shipped transactions?
Is any examples?

**Comment by sucithrashanu** [comment]
@nicdnepr 
Can  you give clear context about which transaction? is it for one time transaction or billing?

Thanks

**Comment by nicdnepr** [comment]
Its about business selling account
Need get selling goods transactions

**Comment by prakash-gangadharan** [comment]
Hi @nicdnepr can you help us with some sample transactions?

**Comment by prakash-gangadharan** [comment]
@nicdnepr refer the below example where Payment::all() method will get the one time payments
sample : [ListPayments](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/ListPayments.php)
It is a wrapper for [List payments API](https://developer.paypal.com/docs/api/payments/v1/#payment_list)
