### ISSUE TITLE
Disputes are not implemented

### ISSUE THREAD

**Issue by AidasK** [paypal/PayPal-PHP-SDK#1327]
I can see that paypal has some disputes rest endpoints available, but they are not implemented in this library. I saw they used to be included in v1 version, though they seem to be removed from PayPal-PHP-SDKv2. Any info why these endpoints are not supported by this library?

**Comment by sucithrashanu** [comment]
@AidasK 

Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.

Please Check [PayPal Community](https://www.paypal-community.com) and  [MTS](https://paypal.com/mts)  
Thanks!

**Comment by AidasK** [comment]
Maybe you should leave it open, because disputes api should be implemented at some point imo

**Comment by prakash-gangadharan** [comment]
similar enhancement : https://github.com/paypal/PayPal-PHP-SDK/issues/746
