### ISSUE TITLE
WHERE are the ACTUALLY USEFUL example scripts such as an “A customer bought something, send an email to the seller” script?

### ISSUE THREAD

**Issue by 01GOD** [paypal/PayPal-PHP-SDK#1329]
Seriously...this repo makes it look like Paypal's API department has its head so far up its own Paypal-speak arse that it forgot that the API is FOR CUSTOMERS!!! 

Customers don't want to study internal Paypal software jargon for a month and get an associates degree in Paypal API to make a simple PHP script that sends an email to the seller containing the buyer's name and email address after the buyer presses a "buy now" button!!! Why all the ridiculous callback handshakes and other mumbo jumbo? 

Crappy experiences for customers when a company outsources to india (and imports on h1b) are common though, so wasn't as surprised when saw some of the names involved. 

### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS:

**Comment by prakash-gangadharan** [comment]
You might have a glance at these examples : https://github.com/paypal/PayPal-PHP-SDK/tree/master/sample and also here http://paypal.github.io/PayPal-PHP-SDK/sample/
