### ISSUE TITLE
Big delay of first payment in billing agreement executed on morning CET.

### ISSUE THREAD

**Issue by KingaTheWitch** [paypal/PayPal-PHP-SDK#1331]
### General information

* SDK/Library version: 1.14.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: I-A2W67K1NURCK (sandbox)
* Language, language version, and OS: PHP

### Issue description

I have noticed that, when I create and execute an agreement in sandbox on early hours CET (Central European Time) for example on 8 o'clock CET. I have to wait a FEW HOURS for the first payment. When I made in on evening, first payment is done immediately.

I set the start date using following function in PHP date("c", time()+600). So I obtain 

something like this YYYY-MM-DDT08:10:00+01:00.

I don't set initial payment. So agreement is ACTIVE just after execute.

Could you explain what is wrong? I think the start date. But how to set it taking into account different time zones of different users from all over the world.

**Comment by prakash-gangadharan** [comment]
Hi @KingaTheWitch, Can you please check with the [MTS](https://paypal.com/mts) since this is more related to the billing flow/product.

**Comment by prakash-gangadharan** [comment]
Similar query  : Which time zone is used in start date in create billing agreement? #1332

**Comment by prakash-gangadharan** [comment]
Hi @KingaTheWitch the start date should be in ISO date time format which mandates the time zone.
You may want to refer to the dev doc  for the start date in create agreement section : https://developer.paypal.com/docs/api/payments.billing-agreements/v1/
