### ISSUE TITLE
Which time zone is used in start date in create billing agreement?

### ISSUE THREAD

**Issue by KingaTheWitch** [paypal/PayPal-PHP-SDK#1332]
### General information

* SDK/Library version: not applicable
* Environment: not applicable 
* `PayPal-Debug-ID` values: not applicable 
* Language, language version, and OS: not applicable 

### Issue description

It is required to set the start date during create billing agreement. But what kind of date/time should it be? UTC date/time, user date/time with time zone (+xx.00), user date without time zone or maybe something else? According to documentation it is time WITHOUT time zone. But which time zone will be used in such case?

**Comment by prakash-gangadharan** [comment]
similar issue : https://github.com/paypal/PayPal-PHP-SDK/issues/1331
