### ISSUE TITLE
iOS integration issues

### ISSUE THREAD

**Issue by sbiermanlytle** [paypal/PayPal-PHP-SDK#142]
Hi, I am following these instructions to implement a future payment server for an iPhone app using paypal: https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/future_payments_server.md

I can retrieve an auth_code from the iPhone console output, and I can successfully obtain an access token through my Mac console with this code

```
curl -v 'https://api.sandbox.paypal.com/v1/oauth2/token' \
    -H "Content-Type: application/x-www-form-urlencoded" \
    -u "CLIENT_ID:SECRET" \
    -d 'grant_type=authorization_code&response_type=token&redirect_uri=urn:ietf:wg:oauth:2.0:oob&code=AUTH_CODE'
```

however, when I try this same call on my PHP 5.4 server with this code:

```
$request = urldecode($_GET['p']);

$code = substr($request, strpos($request, '"code":')+9);
$code = substr($code, 0, strpos($code, '"'));

$headers = array(
    'Content-Type: application/x-www-form-urlencoded'
);

$userpwd = "CLIENT_ID:SECRET";

$ch = curl_init("https://api.paypal.com/v1/oauth2/token?grant_type=authorization_code&response_type=token&redirect_uri=urn:ietf:wg:oauth:2.0:oob&code=".$code);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HEADER, $headers);
curl_setopt($ch, CURLOPT_USERPWD, $userpwd);
$response = curl_exec($ch);
curl_close($ch);

print_r($response);
```

I get the output:

```
HTTP/1.1 505 HTTP Version Not Supported
Server: Apache-Coyote/1.1
Date: Wed, 22 Oct 2014 21:02:31 GMT
Connection: close
```

how can I obtain an access code with PHP? I am unclear of how to integrate this SDK with the iOS handshaking process.

Here is my iOS code:

```
- (void)sendFuturePaymentAuthorizationToServer:(NSDictionary *)authorization {

   NSLog(@"Here is your authorization:\n\n%@\n\nSend this to your server to complete future payment setup.", authorization);
   NSMutableString *path = [NSMutableString stringWithString:@"http://xxxxxxxx?p="];
   [path appendString:[[NSString stringWithFormat:@"%@",authorization] stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding]];

   NSError *e;
   NSString *rrr = [NSString stringWithContentsOfURL:[NSURL URLWithString:path] encoding:NSUTF8StringEncoding error:&e];
   NSLog(@"Server Response:\n\n%@\n\n", rrr);

}
```

**Comment by sbiermanlytle** [comment]
@jaypatel512 I had to go with another solution b/c of time constraints, but I am now trying to get this working again and have run into the same problem. Let me explain again with updated code:

I want to implement future payments via an iOS app and php server. I get the authorization response from the iOS SDK with this code in my iOS app:

```- (void)sendAuthorizationToServer:(NSDictionary *)authorization {
  // Send the entire authorization reponse
  NSData *consentJSONData = [NSJSONSerialization dataWithJSONObject:authorization
                                                            options:0
                                                              error:nil];
NSLog(@"JSON summary: %@", [[NSString alloc] initWithData:consentJSONData
                                                     encoding:NSUTF8StringEncoding]);```

Here's an example of the output:

```JSON summary: {"client":{"environment":"sandbox","product_name":"PayPal iOS SDK","paypal_sdk_version":"2.8.0","platform":"iOS"},"response_type":"authorization_code","response":{"code":"xxxx"}}```

If I take the `code` from that, open up a terminal, and run this command:

```curl -v 'https://api.sandbox.paypal.com/v1/oauth2/token' \
    -H "Content-Type: application/x-www-form-urlencoded" \
    -u "CLIENT_ID:SECRET" \
    -d 'grant_type=authorization_code&response_type=token&redirect_uri=urn:ietf:wg:oauth:2.0:oob&code=AUTH_CODE'```

I get a proper response with a refresh token.

However, if I try to execute that command on my server using this php code:

```$headers = array(
	    'Content-Type: application/x-www-form-urlencoded'
	);
	$fp = fopen("db.txt","w");
	$data = array(
	    "grant_type" => "authorization_code",
	    "response_type" => "token",
	    "redirect_uri" => "urn:ietf:wg:oauth:2.0:oob",
	    "code" => $json->response->code
	);
	$userpwd = "CLIENT_ID:SECRET";
	$query = http_build_query($data);
	$ch = curl_init("https://api.paypal.com/v1/oauth2/token?".$query);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
	curl_setopt($ch, CURLOPT_HEADER, $headers);
	curl_setopt($ch, CURLOPT_USERPWD, $userpwd);
	curl_setopt($ch, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_NONE);
	$response = curl_exec($ch);
	curl_close($ch);
	fwrite($fp,$response);
	fclose($fp);
	var_dump($response);```

I get this error:

```HTTP/1.1 500 Internal Server Error

Server: Apache-Coyote/1.1

PROXY_SERVER_INFO: host=slcjavapapi3035b.slc.paypal.com;threadId=141239

Paypal-Debug-Id: 833113da443fe

Pragma: No-cache

Cache-Control: no-cache

Expires: Wed, 31 Dec 1969 16:00:00 PST

SERVER_INFO: identitysecuretokenserv:v1.oauth2.token&CalThreadId=940&TopLevelTxnStartTime=14aa86a8ce8&Host=slcidensectoken3082b.slc.paypal.com&pid=17755

Content-Language: *

Date: Fri, 02 Jan 2015 02:12:42 GMT

Connection: close

Content-Type: text/xml

Content-Length: 0

Connection: close```

I know the curl extension is installed and I know that I am sending a proper code. How can I obtain a refresh token using PHP?

**Comment by jaypatel512** [comment]
Hey @sbiermanlytle !! I am not exactly sure why curl is acting weird on this. However, do you mind trying out our SDK to create a future payment. 

We also have a [sample that you could use to get what you want](http://htmlpreview.github.io/?https://raw.githubusercontent.com/paypal/PayPal-PHP-SDK/master/sample/doc/payments/CreateFuturePayment.html). You can download the SDK and make changes to the sample, to make changes to it, with your code and access token. Let me know I could help you setup samples.

**Comment by sbiermanlytle** [comment]
Ok I integrated the code but I get the error: ```Class 'ApiContext' not found```

Here is my php code: 
```
error_reporting(E_ALL);
ini_set('display_errors', '1');
require __DIR__ . '/../PayPal-PHP-SDK/autoload.php';
use PayPal\Rest\ApiContext;
use PayPal\Auth\OAuthTokenCredential;
use PayPal\Api\FuturePayment;

$clientId = 'xxx';
$clientSecret = 'xxx';

$apiContext = new ApiContext(
        new OAuthTokenCredential(
            $clientId,
            $clientSecret
        )
);
$apiContext->setConfig(
        array( 'mode' => 'sandbox')
);
$refreshToken = FuturePayment::getRefreshToken($json->response->code, $apiContext);
echo $refreshToken;
```

**Comment by jaypatel512** [comment]
Hey @sbiermanlytle I am assuming, this is how your directory locations look like:

```
LM-AUN-00876403:Test japatel$ tree -L 2
.
├── PayPal-PHP-SDK
│   ├── autoload.php
│   ├── composer
│   └── paypal
└── web
    └── index.php
```
If your index.php is in the same location as PayPal-PHP-SDK, you might want to change your require line to 
```
require __DIR__ . '/PayPal-PHP-SDK/autoload.php';
```

Let me know if this helps. If not, I can help you setup your machine, and get started. Its just PHP that is not loading SDK properly I guess.

**Comment by sbiermanlytle** [comment]
Yes that is my directory structure. I also tried putting the SDK in the same folder as the index, but it output the same error.

**Comment by jaypatel512** [comment]
Would you mind jumping onto this hangout ? https://plus.google.com/hangouts/_/gsudstesfm5gvv5fgns54dbt3qa?authuser=0&hl=en

**Comment by sbiermanlytle** [comment]
Ok, turns out that issue was because the `use` statements weren't included in the file where I was calling the functions - php needs them in the same file, even if that file is included in another file with `include`...

Have one more problem though. I am trying to wrap up the payments and copied this code from the link you posted:

```
$apiContext = new ApiContext(
        new OAuthTokenCredential(
            $GLOBALS['PPCLIENTID'],
            $GLOBALS['PPCLIENTSECRET']
        )
    );
    $apiContext->setConfig(
        array( 'mode' => 'sandbox')
    );

	$payer = new Payer();
	$payer->setPaymentMethod("paypal");
	$amount = new Amount();
	$amount->setCurrency("USD")->setTotal($data[3]);
	$transaction = new Transaction();
	$transaction->setAmount($amount)
	    ->setDescription($data[2]." ".$data[3]);

	$baseUrl = "http://fetchit.iluj.in";
	$redirectUrls = new RedirectUrls();
	$redirectUrls->setReturnUrl("$baseUrl/ExecutePayment.php?success=true")
	    ->setCancelUrl("$baseUrl/ExecutePayment.php?success=false");

	$payment = new FuturePayment();
	$payment->setIntent("authorize")
	    ->setPayer($payer)
	    ->setRedirectUrls($redirectUrls)
	    ->setTransactions(array($transaction));
	try{
		$refreshToken = FuturePayment::getRefreshToken($authorizationCode, $apiContext);
		$payment->updateAccessToken($refreshToken, $data[6]);
		$request = clone $payment;
		$payment->create($apiContext, $correlationId);
	} catch (Exception $ex) {
		echo $ex;
	    //ResultPrinter::printError("Future Payment", "Payment", null, $request, $ex);
	    exit(1);
	}
```

This gives me the following error:

```
exception 'PayPal\Exception\PPConnectionException' with message 'Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/oauth2/token.' in /home/iljn/master/fetchit/PayPal-PHP-SDK/paypal/rest-api-sdk-php/lib/PayPal/Core/PPHttpConnection.php:159
Stack trace:
#0 /home/iljn/master/fetchit/PayPal-PHP-SDK/paypal/rest-api-sdk-php/lib/PayPal/Auth/OAuthTokenCredential.php(221): PayPal\Core\PPHttpConnection->execute('grant_type=auth...')
#1 /home/iljn/master/fetchit/PayPal-PHP-SDK/paypal/rest-api-sdk-php/lib/PayPal/Auth/OAuthTokenCredential.php(174): PayPal\Auth\OAuthTokenCredential->getToken(Array, 'AcXy_hArGkFMyC1...', 'EKpezxBF1ILxCYS...', 'grant_type=auth...')
#2 /home/iljn/master/fetchit/PayPal-PHP-SDK/paypal/rest-api-sdk-php/lib/PayPal/Api/FuturePayment.php(61): PayPal\Auth\OAuthTokenCredential->getRefreshToken(Array, '1tnIFnNLBrUFgJq...')
#3 /home/iljn/master/fetchit/controller.php(320): PayPal\Api\FuturePayment::getRefreshToken('1tnIFnNLBrUFgJq...', Object(PayPal\Rest\ApiContext))
#4 /home/iljn/master/fetchit/root/index.php(68): ctr_buy_item(Object(mysqli), Array)
#5 {main}
```

If I print out `authorizationCode`, I get the same code that I successfully received in the other script.

If I print out `data[6]` (the correlationId), I get the same value that I receive from the iOS SDK.

If I print out `refreshToken` it tells me that the variable doesn't exist.

So it seems the problem occurs at `FuturePayment::getRefreshToken($authorizationCode, $apiContext);`

What could the issue be with this function? Could the problem be related to sandbox mode, or the fact that I am accessing the iOS SDK on an emulator?

**Comment by jaypatel512** [comment]
Hey @sbiermanlytle ! 

Can you please make sure you have Future Payments Enabled in your Developer Account. That may be the reason of you not getting the proper scope for getting authrorization. 

In your developer portal, inside the app you are using, you would see an option Accept payments at the bottom of the page. Click on Advanced Options, and confirm that you have Future Payments enabled.

![screen shot 2015-01-04 at 1 06 27 pm](https://cloud.githubusercontent.com/assets/1309895/5607127/b8fea3b8-9412-11e4-943d-e7a5a79264bd.png)

Can you please try with that and see if it works. Also make sure you are using the same clientId and secret that you are using for generating that Authorization Code in your Mobile SDK. They need to match, as the code is bound with the clientId and Secret who created it, and only that app could use that code to complete that payment.

Let me know if that fixes it, and if not, we can dig little deeper. I tried it on my machine, and it works.

**Comment by sbiermanlytle** [comment]
Future Payments was already checked, but Payouts wasn't, I don't think that's what I'm using but I tried again on a different computer after checking it and there was no difference in the error.

I also checked the client ID, its the same Sandbox id in both the iOS code and the php code. The secret isn't used in the iOS code but has worked in the php script before. I set the iOS environment to ```PayPalEnvironmentSandbox```

**Comment by jaypatel512** [comment]
Do you mind replacing your catch block to something like this:

```php
catch (\PayPal\Exception\PPConnectionException $ex) {
    echo $ex->getData();
    exit(1);
}
```

This should print the business reason why it is failing. Probably will give you a better error message than just 400. 

Also, if you have your logging enabled, you should be able to see the logs with a proper error message too.

**Comment by sbiermanlytle** [comment]
Ok I tried that and now get this output:

```{"error":"invalid_request","error_description":"Internal error"}```

I looked at my logs but couldn't find the error message there.

**Comment by jaypatel512** [comment]
Strangely, when I tried to send a string to $apiContext object, it threw me a proper fatal errror. Not sure what SDK version you are using, but worth upgrading I guess.

Oh wait, probably your metadataId is null, and thats why it worked. You might want to make sure you get a proper clientMetadata Id, as it is optional. It will make the payment with null values, but you wont get the protection from fraud. 

![screen shot 2015-01-11 at 1 35 04 pm](https://cloud.githubusercontent.com/assets/1309895/5696428/befb026e-9996-11e4-87c3-a57a762cb085.png)

**Comment by sbiermanlytle** [comment]
Hopefully this is the last problem. Payments are successful in Sandbox mode, but when I switch to production mode, I get the following error message:

```
exception 'PayPal\Exception\PPConnectionException' with message 'Got Http response code 401 when accessing https://api.paypal.com/v1/payments/payment.' in /home/iljn/master/fetchit/PayPal-PHP-SDK/paypal/rest-api-sdk-php/lib/PayPal/Core/PPHttpConnection.php:159
Stack trace:
#0 /home/iljn/master/fetchit/PayPal-PHP-SDK/paypal/rest-api-sdk-php/lib/PayPal/Transport/PPRestCall.php(74): PayPal\Core\PPHttpConnection->execute('{"intent":"auth...')
#1 /home/iljn/master/fetchit/PayPal-PHP-SDK/paypal/rest-api-sdk-php/lib/PayPal/Api/FuturePayment.php(43): PayPal\Transport\PPRestCall->execute(Array, '/v1/payments/pa...', 'POST', '{"intent":"auth...', Array)
#2 /home/iljn/master/fetchit/controller.php(322): PayPal\Api\FuturePayment->create(Object(PayPal\Rest\ApiContext), '1b1fe57ade874c2...')
#3 /home/iljn/master/fetchit/root/index.php(74): ctr_buy_item(Object(mysqli), Array)
#4 {main}
```

I changed my ClientID and Secret to the live credentials, changed all api contexts to `live` mode, and set the environment to `PayPalEnvironmentProduction` in the iOS app. Did I miss a step for switching to live payments? Why would I be receiving this error?

**Comment by jaypatel512** [comment]
Just to make sure, the refresh token that we get when we convert that authorization code to refresh token, are you sure, you updated your database to not use the sandbox refresh token ?

**Comment by sbiermanlytle** [comment]
Yes, I reverted to sandbox model, got a new refresh token, and the payments worked.

When I switch to live mode, I can login to paypal and generate a refresh token, but no payments go through. The error message is the same each time.

**Comment by jaypatel512** [comment]
Hey @sbiermanlytle ! Can you provide me with the debug_id. It should generally be in the log file. I will forward this to technical team inside here, and get it resolved sooner.

**Comment by sbiermanlytle** [comment]
I have a PayPal.log file in my root folder, but it does not contain any entries from today.

The text of `Exception $ex` is the error message that I posted above

Where else would I find the debug_id?

**Comment by jaypatel512** [comment]
In that case, can you replace the catch exception with this, and run the code again:

```php
catch( \PayPal\Exception\PayPalConnectionException $ex) {
    $data = $ex->getData();
    echo $data;
}
```

This exception helps you get the internal message that will have additional data.

**Comment by sbiermanlytle** [comment]
Ok here it is:

```
{"name":"UNAUTHORIZED_PAYMENT","message":"Unauthorized payment","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#UNAUTHORIZED_PAYMENT","debug_id":"50ee7235c01b9"}
```

**Comment by jaypatel512** [comment]
Awesome. We are looking into this now. I will let you know as soon as possible.

**Comment by jaypatel512** [comment]
We were able to look into the debug_id. It seems like you are passing all the correct scopes and everything. It could be that you have not enabled live credentials in your developer account. 

Can you please open this, and confirm if your have Future Payments  enabled for live. This is how the page would look like:

![screen shot 2015-02-22 at 7 28 27 pm](https://cloud.githubusercontent.com/assets/1309895/6321679/033927e6-bac9-11e4-9016-312e19b6a784.png)

**Comment by saji-rainconcert** [comment]
Hello,

I am also facing the same issue when I use PayPal-PHP-SDK for future payment process in server side. Following is the error I am getting when I try to generate token using the "authorizationCode" and "clientMetadataId" which is passing from iOS mobile SDK. 

Same ClientID and ClientSecret are used in server side and mobile sdk. 
I have Future Payments Enabled in my Developer Account. 

Question: Do you suggest that the referral url (currently the site in development mode and its hosted in a demo server which has no SSL installed) should be in HTTPS?

Error: 

Type: PayPal\Exception\PayPalConnectionException

Message: Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/oauth2/token.

Kindly let me know if you have fixed this issue. 

Thanks.
