### ISSUE TITLE
Billing REST API Question

### ISSUE THREAD

**Issue by juliocoliveira** [paypal/PayPal-PHP-SDK#151]
Hi there, I'm using the REST API to create a Billing Plan.

But the question is: How I update a Billing Plan price because I searched on the http://developers.paypal.com but the only way that i found is to update each Billing Agreement and on the Classic API it says that i can only update 20% in some period.

So there is some way to update a Billing Plan (Amount) Price and all Billing agreement be updated as well?

**Comment by projectzerotohero** [comment]
@jaypatel512 
 Hi there Jay! 

I'm pretty new to the paypal rest api.

I just created a billing plan and I am able to update the billing plan details (e.g. name,type,description) and payment_definitions by having patch request and calling plan.Update(apiContext, patchRequest) for each object.

Is there a way to update merchant_preferences and charge_models in the billing plan?
 Btw, the plan's state is still "CREATED" and still not connected to any billing agreement.

I hope to hear soon from you.
Thanks.

**Comment by jaypatel512** [comment]
About the merchant_preferences and charge_models. There are few ways you might be able to accomplish this. The easiest way to do so would be to use `override_charge_model` and `override_merchant_preferences` when creating an agreement using an existing plan, as shown [here](https://developer.paypal.com/webapps/developer/docs/api/#create-an-agreement). 

However, you could still update `merchant_preferences` on plan itself by creating a patch request with body below:

```json
[
            {
                "op": "replace",
                "path": "/merchant-preferences",
                "value": {
                    "cancel_url": "http://www.cancel.com",
                    "setup_fee": {
                        "value": "5",
                        "currency": "USD"
                    }
                }
            }
        ]
```

You could follow the sample provided [here](http://paypal.github.io/PayPal-PHP-SDK/sample/doc/billing/UpdatePlanPaymentDefinitions.html) of updating plan payment preferences, and make changes accordingly to it to achieve above result. 

Btw, I am not sure if you know about this, but we have a lot of [documents](http://paypal.github.io/PayPal-PHP-SDK/) to get your through the SDKs, including [running samples on your local machine](https://github.com/paypal/PayPal-PHP-SDK/wiki/Samples)

**Comment by projectzerotohero** [comment]
Thanks for the references.

What I want to do is be able to update billing plans before using them in the billing agreement.

So what I'll use are patch requests. I'll try to update the merchant_preferences based on your example.

With the charge models, may I know the path to be used? I can't find any in the documentation.

Thanks.

**Comment by jaypatel512** [comment]
Hey @projectzerotohero ! 

I will get back to you on this. I am not entirely sure about the answer. Let me ask the API team on how to do that. In the meantime, you could always use `overrid_charge_model` attribute to update the charge model when creating the agreement using that plan.

**Comment by projectzerotohero** [comment]
Ok. Thanks.

**Comment by projectzerotohero** [comment]
I think it would be better if I can just update the billing plan alone compared to creating a billing agreement first and override.

**Comment by projectzerotohero** [comment]
Hi @jaypatel512 . I already got it!

I am now able to update charge models.

I just set the path to "/payment-definitions/" + {paymentDefinitionIdGoesHere} + "/charge-models/" + {chargeModelIdGoesHere}"

Ex. 
 var patchRequest = new PatchRequest()
{
                new Patch()
                {
                    op = "replace",
                    path = "/payment-definitions/" + editedPlan.BillingPlan.StandardPlan.Id + "/charge-models/" + editedPlan.BillingPlan.StandardPlan.Shipping.Id,
                    value = newStandardPlanShippingChargeDefinition
                }
};

**Comment by Meatballsl** [comment]
> About the merchant_preferences and charge_models. There are few ways you might be able to accomplish this. The easiest way to do so would be to use `override_charge_model` and `override_merchant_preferences` when creating an agreement using an existing plan, as shown [here](https://developer.paypal.com/webapps/developer/docs/api/#create-an-agreement).
> 
> However, you could still update `merchant_preferences` on plan itself by creating a patch request with body below:
> 
> ```json
> [
>             {
>                 "op": "replace",
>                 "path": "/merchant-preferences",
>                 "value": {
>                     "cancel_url": "http://www.cancel.com",
>                     "setup_fee": {
>                         "value": "5",
>                         "currency": "USD"
>                     }
>                 }
>             }
>         ]
> ```
> 
> You could follow the sample provided [here](http://paypal.github.io/PayPal-PHP-SDK/sample/doc/billing/UpdatePlanPaymentDefinitions.html) of updating plan payment preferences, and make changes accordingly to it to achieve above result.
> 
> Btw, I am not sure if you know about this, but we have a lot of [documents](http://paypal.github.io/PayPal-PHP-SDK/) to get your through the SDKs, including [running samples on your local machine](https://github.com/paypal/PayPal-PHP-SDK/wiki/Samples)

it does not work
