### ISSUE TITLE
When using saved card id, I cannot do payment->create repeatedly.

### ISSUE THREAD

**Issue by kenjohnson** [paypal/PayPal-PHP-SDK#157]
I am using PayPal-PHP-SDK Master Branch Tag v0.13.1

PROBLEM:
Problem calling payment->create  two times or more
in the same file; an exception will be thrown. 
For this case, I am using Saved Credit card id.  
REPRODUCE BY:
 go to samples/payments/CreatePaymentUsingSavedCard.php
 and modify as follows.

 case #1
 Add another call to payment->create at the bottom,
 like this. 

``` php
 try {
      $payment->create($apiContext);
 } catch (PayPal\Exception\PPConnectionException $ex) {
      echo "Exception: " . $ex->getMessage() . PHP_EOL;
      var_dump($ex->getData());
      exit(1);
 }
 // ADD ANOTHER CALL HERE

 try {
      $payment->create($apiContext);
 } catch (PayPal\Exception\PPConnectionException $ex) {
       echo "Exception: " . $ex->getMessage() . PHP_EOL;
       var_dump($ex->getData());
        exit(1);
 }
```

It will throw an exception
 [ken@ds1 payments]$ php CreatePaymentUsingSavedCard.big.php
Exception: Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payment.
string(229) "{"name":"DUPLICATE_REQUEST_ID","message":"The value of PayPal-Request-Id header has already been used","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#DUPLICATE_REQUEST_ID","debug_id":"cf7f97ad64e0d"}"

 case #2
 Okay, make it just like above except add a new 
 payment object. 

``` php
try {
     $payment->create($apiContext);
} catch (PayPal\Exception\PPConnectionException $ex) {
   echo "Exception: " . $ex->getMessage() . PHP_EOL;
   var_dump($ex->getData());
    exit(1);
 }
// START ADDING HERE
 $payment = new Payment();
$payment->setIntent("sale")
         ->setPayer($payer)
      ->setTransactions(array($transaction));

 try {
      $payment->create($apiContext);
 } catch (PayPal\Exception\PPConnectionException $ex) {
     echo "Exception: " . $ex->getMessage() . PHP_EOL;
    var_dump($ex->getData());
    exit(1);
 }
```

 It will throw an exception like this. 

 [ken@ds1 payments]$ php CreatePaymentUsingSavedCard.big.php
Exception: Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment.
string(212) "{"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"d5fbe0144bcce"}"
[ken@ds1 payments]$

Now, sometimes it will throw DUPLICATE_REQUEST_ID even when I
make a new payment object. 

It seems I get one of these two exceptions every time I try to 
do this. I can run one, just fine.  

The reason I want to do this is for 
membership. Every day we want to run
a script and if a membership has expired,
we want to do payment->create to renew. 
So, we loop through our members and call
payment->create if the membership is due. 
Of course this means we may call
payment->create twice or more.  

Any ideas what is going on.

**Comment by amitpanwar86** [comment]
HI Jay,

I am facing a problem in marking invoice as MARKED_AS_PAID.
Here is my code : 

      $invoice=new Invoice();
      $invoice->setId($invoiceId);
      $invoice->setStatus("MARKED_AS_PAID");
      $updateStatus=$invoice->update($this->_apiContext);
      echo updateLocalInvoices;die;
      return true;

But i am getting an error  Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/invoicing/invoices/*************.  I am stuck in this issue.
Can you please tell whats wrong with this???

Many Thanks in Advance,
