### ISSUE TITLE
Prefill email for 'new acccount'

### ISSUE THREAD

**Issue by 123marcel** [paypal/PayPal-PHP-SDK#161]
I have a question about prefilling some data. When I have chosen to use PayPal for doing the payment, it give me two options, first option is to login with an existing account, the second option is to create an account. When the second option is chosen, the information about billing address and shipping address are prefilled (I send the data with the request), also the phone number, but I cannot find the way to prefill the email address. How can I arrange to prefill the email address?

Thanks in advance!

**Comment by Hajneej** [comment]
@123marcel Can you please post some sample how you successfully pre-filled billing address/shipping address/phone? I supposed, that pre-filled is currently not supported (see  [#302](https://github.com/paypal/PayPal-PHP-SDK/issues/302#issuecomment-99302986)).

Thanks
