### ISSUE TITLE
Permissions in rest API?

### ISSUE THREAD

**Issue by agrandin** [paypal/PayPal-PHP-SDK#165]
Hi, is it possible to use the Permissions from Classic API in combination with the Rest API? 
Would like to us the Rest API as much as possible, but right now it looks like I have to go back to the classic one. To bad.

**Comment by nathanwelch** [comment]
Hey @jaypatel512  I wanted to get some clarification on this: Is it possible to make REST API requests on behalf of a merchant whose account is connected with my app (e.g. in the same way that the Permissions Service API from the Classic APIs allowed you to use ExpressCheckout on another merchant's behalf)? The original question above seemed to be asking if/when support for Permissions API access tokens would be included in the new REST API or replaced by some new REST API calls to get account permissions for creating payments. 

I realize I can use both the new and classic SDKs together now with 1.x but I wanted to see if I could begin development on a feature like this without using the deprecated classic SDK.

Thanks!

**Comment by jaypatel512** [comment]
Hey @nathanwelch ! Unfortunately, the permissions support is not yet available in REST API. The PayPal REST Team is trying to move all the features from Classic APIs to REST. However, this is something that is still under progress. We unfortunately do not have a fixed timeline for this. I think your best bet would be to use both Classic and REST for now. Once the REST Feature is available, I will definitely update the thread, and let everyone know. However, I dont see that happening anytime really soon.

**Comment by nathanwelch** [comment]
Alright, I won't hold my breath then. Thanks @jaypatel512!

**Comment by blakeloverain** [comment]
Is there any update to this? I just spent a few days implementing the REST API in my application because the customer can also choose Stripe, and I wanted as similar flow as possible for transactions. I provide a web service where the customer can receive donations, and they can authorize me via Stripe's OAuth to allow me to process payments for them. I have all the pieces for Paypal using the REST API, except I only have my internal client_id and secret. Is there a way to query the customer to provide THEIR OWN client_id and secret? Would that REQUIRE they create an APP as well? Is there any way I can use both the classic Permissions API and the new REST API simultaneously? Or am I forced to give up on the REST API altogether? It would seem my alternative is to just revert to basic HTML forms that submit directly onto PayPal's servers (instead of the credit card vault storage), and redirect back to my site afterward - which would only really need their paypal email, I believe.

**Comment by gildo** [comment]
@jaypatel512 any update on this?

**Comment by shaunc869** [comment]
Any updates? Thanks!

**Comment by Programadores-iOS** [comment]
Seems that this issue has been closed, but I believe the ability to use the token generated from the paypalpermissions as described here (https://developer.paypal.com/docs/classic/permissions-service/integration-guide/PermissionsUsing/) hasn't been ported to the Rest SDK.

Any update will be appreciated.

Basically we want to be able to use the rest sdk and the token from the Paypal permissions (classic api)

Please advise.

**Comment by ppmtscory** [comment]
Unfortunately we still don't have any concrete timelines for when/if the Permissions Service functionality would be available via REST API.  There are various feature/product priorities still being ironed out as well as service dependencies being looked at.

**Comment by maniJoe** [comment]
I am unable to do payment transaction in Live.But the sandbox works perfectly.
Please clarify me on this.I think the API permission may be the problem.

**Comment by xiaoleih41** [comment]
@maniJoe, Please submit a ticket at https://www.paypal-techsupport.com/ and provide the debug id associated with the error message. The engineer over the technical support will help you pinpoint the exact cause. Thanks, Xiaolei

**Comment by perrytew** [comment]
Ping.  
Here we are a year later.  Do anyone know of any official communication on when, if ever, the REST API will support permissions and multiple merchants?

**Comment by pp-randy** [comment]
@perrytew what API calls are you trying to make?  Third Party PayPal payments are now supported in REST.

**Comment by perrytew** [comment]
Hmmm, perhaps I've missed something.   My apologies for any ignorance on my part, and thank you for your help.

I see the CreateThirdPartyPayment.php example.  But what I'm looking for is the ability to act on behalf of merchants using the full spectrum of the REST API.  Using OAuth, have the merchants authorize my application to do everything, including the BillingPlan API, etc.  

The API still seems geared to one client id, one secret.  Would you please point me to an example where I pass in a merchant's access token and proceed to manage their account, create billing plans, agreements, and the like?

For example, on the Getting Started example:
https://github.com/paypal/PayPal-PHP-SDK/wiki/Making-First-Call

How do I alter Step 2 and replace my application's client id and secret with an access token from a merchant?  And how might I get that access token using REST?  I see some NVP examples.  Do those same examples for obtaining access tokens apply here?

**Comment by pp-randy** [comment]
When this thread was created third party payments were not yet supported with the REST API, so I wanted to check your use case.  The REST API does not support your use case at this time.

**Comment by perrytew** [comment]
Randy,
Thank you for confirming that.   I appreciate your time.
