### ISSUE TITLE
PPUserAgent array problem?

### ISSUE THREAD

**Issue by shinesoftware** [paypal/PayPal-PHP-SDK#167]
Hi guys,

I have found a problem in the PayPal\Common\ResourceModel::executeCall( ). This is my code:

        $apiContext = new ApiContext ( new OAuthTokenCredential ( 'Aah3BxCbxxk4vOcpwQ2ssscECW16b0R_l6-lL_yyo_dasdasdadaweqw', 'EKp-tBBHbtwpMDUG44pSGkFOe3MswNqgiW4adasd3r3rd212cfbulHjbc5JX' ) );
        
        $apiContext->setConfig ( array ('mode' => 'sandbox', 'http.ConnectionTimeOut' => 30, 'log.LogEnabled' => true, 'log.FileName' => LOG_PATH . 'PayPal.log', 'log.LogLevel' => 'FINE', 'validation.level' => 'log' ) );
        
        $payer = new Payer ();
        $payer->setPaymentMethod ( "paypal" );
        
        $item1 = new Item ();
        $item1->setName ( 'Milonga a Trieste' )->setDescription ( 'Biglietto per una persona con consumazione inclusa.' )->setCurrency ( 'USD' )->setQuantity ( 1 )->setTax ( 0 )->setPrice ( 7.50 );
        
        $itemList = new ItemList ();
        $itemList->setItems ( array ($item1 ) );
        
        $details = new Details ();
        $details->setShipping ( 0 )->setTax ( 0 )->setSubtotal ( 7.5 );
        
        $amount = new Amount ();
        $amount->setCurrency ( "USD" )->setTotal ( 7.5 )->setDetails ( $details );
        
        $transaction = new Transaction ();
        $transaction->setAmount ( $amount )->setItemList ( $itemList )->setDescription ( "Payment description" )->setInvoiceNumber ( uniqid () );
        
        $baseUrl = "http://www.itango.com";
        $redirectUrls = new RedirectUrls ();
        $redirectUrls->setReturnUrl ( "$baseUrl/response/success" )->setCancelUrl ( "$baseUrl/response/failure" );
        
        $payment = new Payment ();
        
        $payment->setIntent ( "sale" )->setPayer ( $payer )->setRedirectUrls ( $redirectUrls )->setTransactions ( array ($transaction ) );
        
        $request = clone $payment;
        
        try {
            $payment->create ( $apiContext );
        } catch ( Exception $ex ) {
            var_dump ( 'Create Payment Using Credit Card', 'Payment', null, $request, $ex );
            exit ( 1 );
        }
        
        foreach ( $payment->getLinks () as $link ) {
            if ($link->getRel () == 'approval_url') {
                $approvalUrl = $link->getHref ();
                break;
            }
        }
        
        echo printf ( "Created Payment Using PayPal. Please visit the %s to Approve.", "<a href='$approvalUrl' >URL</a>" );
        die ();

this is the error:

        ( ! ) Catchable fatal error: Object of class PayPal\Rest\ApiContext could not be converted to string in /var/www/myproject/vendor/paypal/sdk-core-php/lib/PayPal/Common/PPUserAgent.php on line 28

thanks

**Comment by jaypatel512** [comment]
Hey @shinesoftware @ulkas ! I am closing this issue based on its inactivity. However, I will keep you updated on 1.0 release, that should fix this. 

Please feel to try out the instructions mentioned above, and I would be more than happy to re-open if issue still exists.

**Comment by shinesoftware** [comment]
Hi @jaypatel512 and happy new year!
I am testing it in my website right now and I have not found any difficulty. I have to admit that the issue is not shown also in the master branch now. Something has changed.

    $ php composer.phar update
    Loading composer repositories with package information
    Updating dependencies (including require-dev)             
      - Removing paypal/rest-api-sdk-php (v0.16.1)
      - Installing paypal/rest-api-sdk-php (dev-1.0.0-beta 9e7cb95)
        Cloning 9e7cb951a6d79bf1208b870a6cfc47aeca2d8c40

This is my code: 

    <?php
    /**
    * Copyright (c) 2014 Shine Software.
    * All rights reserved.
    *
    * Redistribution and use in source and binary forms, with or without
    * modification, are permitted provided that the following conditions
    * are met:
    *
    * * Redistributions of source code must retain the above copyright
    * notice, this list of conditions and the following disclaimer.
    *
    * * Redistributions in binary form must reproduce the above copyright
    * notice, this list of conditions and the following disclaimer in
    * the documentation and/or other materials provided with the
    * distribution.
    *
    * * Neither the names of the copyright holders nor the names of the
    * contributors may be used to endorse or promote products derived
    * from this software without specific prior written permission.
    *
    * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
    * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
    * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
    * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
    * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
    * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
    * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
    * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
    * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    * POSSIBILITY OF SUCH DAMAGE.
    *
    * @package Events
    * @subpackage Service
    * @author Michelangelo Turillo <mturillo@shinesoftware.com>
    * @copyright 2014 Michelangelo Turillo.
    * @license http://www.opensource.org/licenses/bsd-license.php BSD License
    * @link http://shinesoftware.com
    * @version @@PACKAGE_VERSION@@
    */

    namespace Paypal\Service;

    use Zend\EventManager\EventManager;
    use Zend\Db\TableGateway\TableGateway;
    use Zend\Stdlib\Hydrator\ClassMethods;
    use Zend\EventManager\EventManagerAwareInterface;
    use Zend\EventManager\EventManagerInterface;

    class PaypalService implements PaypalServiceInterface, EventManagerAwareInterface
    {
        protected $eventManager;
        protected $settings;
        protected $translator;
    
        public function __construct(\Base\Service\SettingsService $settings, \Zend\Mvc\I18n\Translator $translator ){
            $this->settings = $settings;
            $this->translator = $translator;
        }
    
        /**
         * Create the Pay key code to redirect the user to the Paypal website
         * 
         * @param string email $receiver
         * @param float $amount
         * @throws \Exception
         * @return string
         */
        public function getPayKey($receiver, $amount)
        {
            $link = null;
            $username = $this->settings->getValueByParameter('paypal', 'username');
            $password = $this->settings->getValueByParameter('paypal', 'password');
            $signature = $this->settings->getValueByParameter('paypal', 'signature');
            $appid = $this->settings->getValueByParameter('paypal', 'appid');
            $mode = $this->settings->getValueByParameter('paypal', 'mode');
            $log = $this->settings->getValueByParameter('paypal', 'log');
            $currency = $this->settings->getValueByParameter('paypal', 'currency');
            $baseUrl = $this->settings->getValueByParameter('paypal', 'baseurl');
            $paypal_receiver = $this->settings->getValueByParameter('paypal', 'receiver');
            $fee = $this->settings->getValueByParameter('paypal', 'fee');
            $success = "$baseUrl/paypal/success";
            $cancel = "$baseUrl/paypal/failure";
            $ipn = "$baseUrl/response/ipn";
        
            if(empty($username) || empty($password) || empty($signature) || empty($appid) || empty($currency) || empty($baseUrl))
                throw new \Exception('Paypal is not set yet! Go to the administration page and then Settings > Paypal');
        
            $config = array('acct1.UserName' => $username,
                    'acct1.Password' => $password,
                    'acct1.Signature' => $signature,
                    'acct1.AppId' => $appid,
                    'mode' => !empty($mode) ? $mode : "sandbox",
                    'http.ConnectionTimeOut' => 30,
                    'log.LogEnabled' => (bool)$log,
                    'log.FileName' => LOG_PATH . 'PayPal.log',
                    'log.LogLevel' => 'FINE',
                    'validation.level' => 'log');
        
            $service = new \PayPal\Service\AdaptivePaymentsService($config);
         
            $payer = new \PayPal\Api\Payer();
            $payer->setPaymentMethod("paypal");
        
            $requestEnvelope = new \PayPal\Types\Common\RequestEnvelope("en_US");
            $receivers = array();
        
            $receivers[0] = new \PayPal\Types\AP\Receiver();
            $receivers[0]->email = $receiver; // A receiver's email address
            $receivers[0]->amount = $amount;  // Amount to be credited to the receiver's account
            $receivers[0]->primary = true;
         
        
            $receivers[1] = new \PayPal\Types\AP\Receiver();
            $receivers[1]->email = $paypal_receiver; // A receiver's email address
            $receivers[1]->amount = $fee;  // Amount to be credited to the receiver's account
        
            $receiverList = new \PayPal\Types\AP\ReceiverList($receivers);
        
            $payRequest = new \PayPal\Types\AP\PayRequest($requestEnvelope, "PAY", $cancel, $currency, $receiverList, $success);
            $payRequest->ipnNotificationUrl = $ipn;
        
            try {
                $response = $service->Pay($payRequest);
            } catch(\Exception $ex) {
                var_dump($ex->getMessage());
                die;
            }
        
            if ($response->responseEnvelope->ack == "Success"){
                return $response->payKey;
            }else{
                throw new \Exception($response->error[0]->message);
            }
        }
    
    
        /* (non-PHPdoc)
         * @see \Zend\EventManager\EventManagerAwareInterface::setEventManager()
        */
        public function setEventManager (EventManagerInterface $eventManager){
            $eventManager->addIdentifiers(get_called_class());
            $this->eventManager = $eventManager;
        }
    
        /* (non-PHPdoc)
         * @see \Zend\EventManager\EventsCapableInterface::getEventManager()
        */
        public function getEventManager (){
            if (null === $this->eventManager) {
                $this->setEventManager(new EventManager());
            }
    
            return $this->eventManager;
        }
    
    }

This code works with both branches!

**Comment by jaypatel512** [comment]
Hmmm !! Interesting !! I wonder what fixed it in master. :) 

But anyway, Good to know the issue is fixed. However, to not have any future namespacing issues, we made changes to similar named classes from Classic SDK from PP* to PayPal* prefixes. This should keep troubles away.

**Comment by shinesoftware** [comment]
Perfect! thanks!
