### ISSUE TITLE
CodeIgniter Create Payment Using Credit Card not working - UNKNOWN_ERROR

### ISSUE THREAD

**Issue by achintverma** [paypal/PayPal-PHP-SDK#173]
I setup the SDK on my CodeIgniter Project http://365housecleaning.com/paypal. I am running sample code from the file CreatePayment.php which is constantly throwing exception. Other payment method like "paypal" works just fine. I am leaving the page as it is so you can see the issue details. This is for sure a bug in the API. I believe Paypal should not encourage people to use REST API till its fully tested and has stable release. Its very frustrating to debug hundred files of SDK for a simple payment integration.

**Comment by jaypatel512** [comment]
Closing the task based on inactivity. Please feel free to re-open the issue if not yet resolved. 

Thank you.

**Comment by rybulka** [comment]
I get this error by setting the value of the currency as "RUB", when permitted currencies: USD, EUR - no error occurs :)

**Comment by sachinvrg** [comment]
everything was working fine but suddenly getting this issue - 
{"name":"UNKNOWN_ERROR","message":"An unknown error has occurred","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR","debug_id":"a84962f32bfc4"}
please help me.

**Comment by Zartexx** [comment]
so was there a solution here?
I am attempting implemention of the REST API.
but can't get past the line: 
Payment ZeroChargedPayment = pymnt.Create(PAC)
all it tells me is UNKNOWN_ERROR
![paypalerror2](https://cloud.githubusercontent.com/assets/12850728/8117144/f25ef4b0-103a-11e5-8092-2f4724721a4b.png)

**Comment by jaypatel512** [comment]
This doesnt look PHP to me. I think you are looking at wrong place. 

However, there was a bug that was found recently, that was causing Credit card payments to fail. They have been resolved yesterday. Can you please make sure you are seeing the issues today ?

**Comment by Zartexx** [comment]
Just tried again, still no
![paypalerror3](https://cloud.githubusercontent.com/assets/12850728/8117378/82b9e9ec-103c-11e5-9e89-c0a6451c9bc5.png)

**Comment by Zartexx** [comment]
i'm on the sandbox, heres the json
{"intent":"sale","payer":{"payment_method":"credit_card","funding_instruments":[{"credit_card_token":{"credit_card_id":"CARD-9X649077V3345220FKV4L7FY","expire_month":11,"expire_year":2018}}]},"transactions":[{"amount":{"currency":"USD","total":"1.00","details":{"subtotal":"1.00"}},"description":"Validating a Credit Card","item_list":{"items":[{"quantity":"1","name":"Validation","price":"1.00","currency":"USD","sku":"bbdc6a4a-6dd4-4424-b507-609d41f3dced"}]}}]}

**Comment by Zartexx** [comment]
I also tried removing the Details() from the Amount() and removing the ItemList() from the Transaction()

**Comment by jaypatel512** [comment]
Hey @Zartexx !

Can you please open https://developer.paypal.com/developer/accountStatus and see if you have "Direct credit cards" enabled in your account ? 

It should look something like this: 

![screen shot 2015-06-11 at 3 35 27 pm](https://cloud.githubusercontent.com/assets/1309895/8117666/85cc083c-104f-11e5-9fbc-5df5ce82462c.png)

**Comment by Zartexx** [comment]
![paypalerror4](https://cloud.githubusercontent.com/assets/12850728/8117698/226e4206-103f-11e5-939d-860a09c3a4cc.png)

**Comment by Zartexx** [comment]
This should work on the sandbox right?  my understanding is, if I enable the live one, my boss starts paying monthly, so I wanted to wait and get your API implemented first.  correct me if I am wrong please.

**Comment by jaypatel512** [comment]
Yes. Having that enabled in Sandbox should be enough. This seems to be an issue with your account, or your merchant's account. Can you please refer to https://ppmts.custhelp.com/ and see if you could get your account checked by merchant technical service. 

Please see if you could open an issue in https://github.com/paypal/PayPal-NET-SDK for correct issue tracking. Thanks again.
