### ISSUE TITLE
custom form field for billing plans

### ISSUE THREAD

**Issue by ulkas** [paypal/PayPal-PHP-SDK#175]
is there any way how to add any custom string to a billing plan / billing agreement similar to https://developer.paypal.com/docs/api/#transaction-object ->custom field? 

i would like to pass some customer info in order to see that info in the paypal billing report  export which is done manually on the paypal site.

currently i can only send custom string within the simple payments transaction object. this information is than being send together everywhere, including IPN and manuall exports on paypal site.

**Comment by jaypatel512** [comment]
CC https://github.com/paypal/PayPal-Python-SDK/issues/68
