### ISSUE TITLE
If payment_method is paypal, payer->status of UNVERIFIED is ambiguous

### ISSUE THREAD

**Issue by kenjohnson** [paypal/PayPal-PHP-SDK#178]
create a payment
use payment_method: paypal
  
 If you always pay by paypal, then the payment->payer->status
 results are very meaningful, they tell if that
 user is VERIFIED or UNVERIFIED. 
  
 Now suppose in web profile you set the
 landing page to billing; the user now 
 has a choice to 
 pay by paypal or credit card. If he chooses
 credit card, the result is always UNVERIFIED.
  
 Now a result of UNVERIFIED is ambiguous, you
 don't know if he paid by paypal and was truly
 UNVERIFIED, or if he paid by  Credit card and 
 got that result.  
  
  ADDITIONAL INFO
  
   I am using PayPal-PHP-SDK v0.14.2
   
  FROM THE Rest Api on line documentation and then my comment on it.
  
  Payer object   status 	  
  
  Status of the payer’s PayPal account. 
  Currently supported with paypal payment_method only,
  but available for credit_card payment_method at a 
  later date. Allowed values: VERIFIED or UNVERIFIED.
  
  COMMENT 
    How the documentation applies to my problem may be
	a bit tricky. They say it will be available for 
	credit_card payment method; that is fine. They also
	need to implement this for the case when you specify
	a payment_method of "paypal", and you choose to
	enter your credit card to pay.

**Comment by jaypatel512** [comment]
Hey @kenjohnson ! 

I have forwarded your comments to doc teams, and Payments team. They will definitely look over it and see what improvements could be done to improve this based on your suggestions.

**Comment by super-iterator** [comment]
it's always shows UNVERIFIED with me, yet everything goes fin; actually I don't understand the meaning of verification here, can anybody explain it to me?

**Comment by kenjohnson** [comment]
@super-iterator
The docs say the user needs to be verified to make
payments of over $500.  If you are like a lot of 
us, you probably don't have customers coming in spending
more that $500 at a time, so this might be why
everything is working fine for you.     

This might help
[https://www.paypal.com/c2/cgi-bin/webscr?cmd=xpt/Marketing/securitycenter/buy/VerificationFAQ-outside]

**Comment by super-iterator** [comment]
@kenjohnson Thanks a lot!
