### ISSUE TITLE
How do I pass custom data to Paypal (for IPN / webhooks)?

### ISSUE THREAD

**Issue by MikeHopley** [paypal/PayPal-PHP-SDK#185]
When Paypal sends me an IPN or webhook, it must contain the user ID from my database, so that I know which customer it's for.

I am using subscriptions (billing agreements). Using the REST API, how do I pass this information to Paypal during the signup process?

In the classic APIs, you could use parameters like `invoice`, although that was a bit hacky. Hopefully Paypal will come up with something better for the REST API. [Stripe uses a `metadata` parameter](https://stripe.com/blog/adding-context-with-metadata), which can contain whatever values you want and can even be "nested" -- for example:

```JSON
"metadata": {
	"user": {
		"id": "27",
		"affection": "negotiable"
	},
	"product": {
		"category": "personal toy",
		"size": "too large"
	}
}
```

**Comment by jaypatel512** [comment]
Hey @ulkas ! The previous issue is not closed entirely without output. Because there are multiple SDKs for each languages, and this issue is not specific to an SDK, we keep only one issue open, which is in mentioned at : https://github.com/paypal/PayPal-Python-SDK/issues/68

**Comment by diptigajjar** [comment]
Hi, 
I'm new to the Laravel framework and facing the same issue. I want to send some custom data to paypal and on success response i want to store that in my database but I'm not able to send the custom data. Can anyone please help me?

**Comment by xiaoleih41** [comment]
@diptigajjar Can you please open a new issue and explain what type of error have you received and which parameter you have been used to pass on the custom data?
