### ISSUE TITLE
No SDK for Payments/Payouts

### ISSUE THREAD

**Issue by gregv** [paypal/PayPal-PHP-SDK#189]
Ref: https://developer.paypal.com/docs/integration/direct/create-single-payout/

I don't see an SDK for Payouts, can you pretty please add it?

**Comment by jaypatel512** [comment]
Hey @gregv Just an update,  I have created a branch with the Payout APIs. I will be releasing these soon. https://github.com/paypal/PayPal-PHP-SDK/tree/Payouts

**Comment by jaypatel512** [comment]
Glad to close this as we have an official release with [ Payouts Support ](https://github.com/paypal/PayPal-PHP-SDK/releases/tag/v1.0.0)

**Comment by gregv** [comment]
Thanks a bunch!
