### ISSUE TITLE
Configurable authentication headers required

### ISSUE THREAD

**Issue by druteika** [paypal/PayPal-PHP-SDK#193]
As defined in https://developer.paypal.com/webapps/developer/docs/api/#authentication--headers, there might be needed additional headers, like partner BN code (key "PayPal-Partner-Attribution-Id").

Unfortunately in \PayPal\Auth\OAuthTokenCredential::getToken method, where the header is built, there is no parameter to add custom header values.

It would be even better if there would be a config section for those custom header values!

**Comment by jahir3819** [comment]
Hi @jaypatel512 @druteika where do i get right Partner attribution id for Sandbox testing?

**Comment by xiaoleih41** [comment]
@jahir3819 If you are currently working with PayPal partner sale team, they will assign you the Id. Please contact customer service number listed on your account to get in touch with the sales team.

**Comment by jahir3819** [comment]
Thank you @xiaoleih41 . Will do that now
