### ISSUE TITLE
1.0.0-beta

### ISSUE THREAD

**Issue by jaypatel512** [paypal/PayPal-PHP-SDK#194]
There have been issues with backward compatibility with classic SDKs with the newer Rest SDKs, which did not allow them to work together nicely. There were naming conflicts that was mostly the reason behind it.

However, We are making [1.0.0-beta](https://github.com/paypal/PayPal-PHP-SDK/tree/1.0.0-beta) branch that would allow us to remove such issues. But, that would require us to make some breaking changes in the code, specially around Class Naming Convention and Namespaces.

I have created a branch here, and started to work on this, with few more features into it, before making an official release, and I would really appreciate if you guys could check it out and see if it works fine with you. I understand that there might be few bugs in there, but giving first hand access to this would reduce issues when you move to release version. This is the time when we could make breaking changes to the SDK and make it better than previous versions. 

You can download the 1.0.0-beta version by updating your composer.json to :

```json
{
        "require": {
                "paypal/rest-api-sdk-php":"dev-1.0.0-beta"
        }
}
```

Please let me know if you run into any issues, or if there are any features you would like to see in this release. I am committed to improve this SDK, and make sure it is desirable for developers to use it as the default SDK for PayPal APIs.

**Comment by jaypatel512** [comment]
Closing the issue on behalf of completing 1.0.0-beta cycle. The 1.0.0 will be released soon.

**Comment by MikeHopley** [comment]
Hi Jay,

Thanks for inviting me to be part of this.

Unfortunately with Christmas & new year & now being pretty busy, it looks
like I may not get a chance to try out the beta in time for your 1.0
release. Sorry!

Regardless, when I get time I will check out the latest version and provide
feedback.

Thanks,
Mike

On 21 December 2014 at 00:26, Jay <notifications@github.com> wrote:

> Adding few active members to the list, for them to try out 1.0.0-beta and
> be a part of making it better.
>
> @MikeHopley <https://github.com/MikeHopley> @shinesoftware
> <https://github.com/shinesoftware> @laravelian
> <https://github.com/laravelian> @ulkas <https://github.com/ulkas>
> @kenjohnson <https://github.com/kenjohnson>
>
> Hey Guys,
>
> I would really appreciate, if you can give some inputs on any issues,
> features, or enhancements you would want to see in 1.0-beta, and I would be
> more than happy to get them in the list.
>
> You guys have created many issues, that has helped us make our SDK better,
> and getting more suggestions from you is always desired. We would add each
> feature in my backlog, and get to them, either in 1.0.0 release, or its
> next releases.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/paypal/PayPal-PHP-SDK/issues/194#issuecomment-67755387>
> .
>



-- 
Mike Hopley
07917 136277

**Comment by jaypatel512** [comment]
Sounds good ! No worries. It was something that I wanted to get more traction before making a release, and cover as many bugs as I could. However, I tested the PHP SDK for most parts, and it should go along nicely. Wost case, 2.0.0-beta it is ! :)
