### ISSUE TITLE
Using paypal SDK without composer

### ISSUE THREAD

**Issue by sbiermanlytle** [paypal/PayPal-PHP-SDK#200]
I am trying to follow the instructions here: https://github.com/paypal/PayPal-PHP-SDK#--direct-download-without-using-composer

I put the `PayPal-PHP-SDK` folder into my root, then added `include 'PayPal-PHP-SDK/autoload.php';` to my index file. That seems to work. But I cannot utilize any of the components.

When I try to follow these instructions: https://devtools-paypal.com/guide/openid/php?interactive=OFF&env=sandbox

I get a 500 Internal Server Error after adding the first line of code: `$apicontext = new PPApiContext(array('mode' => 'sandbox'));`

What am I doing wrong? Why do the integration docs mention a 'vender' folder if there is no vender folder included in the direct download? All the sample applications use composer, so I can't get any demos working. I'm using PHP 5.5

**Comment by velryphon** [comment]
Hi,

I've been struggling with integrating the Paypal Checkout SDK (without composer) for days, and I've finally make it work.

I have coded a loader that construct dependencies needed for the SDK to work, here it is :

`<?php

function autoload($classes, $deps_file)
{
		$deps	=array();	//Stores the classes that have been scanned
		$stack	=array();	//Stores the classes about to be scanned, needed to avoid scanning twice the same class

	foreach($classes as $class)
				load_class_file($class, $deps, $stack);

		$stream	="<?php".PHP_EOL;

	foreach($deps as $dep)
	{
		$stream	.=str_replace("\\", "/", "require(\"".$dep.".php\");".PHP_EOL);
		$stream	.="use ".$dep.";".PHP_EOL;
	}

		$stream	.="?>".PHP_EOL;

				file_put_contents($deps_file, $stream);
}

//==================================================

function load_class_file($class_path, &$deps, &$stack)
{
	if(!in_array($class_path, $stack))
	{
						$stack[]	=$class_path;
						$file		=$class_path.".php";

		if(file_exists($file))
		{
						$content	=file_get_contents($file);
						$lines		=explode("\n", $content);
						$namespace;
						$uses		=array();

			foreach($lines as $line)
			{
				if(substr($line, 0, strlen("namespace ")) == "namespace ")
				{
						$namespace	=str_replace(";", "", str_replace("namespace ", "", $line));
				}
				if(substr($line, 0, strlen("use ")) == "use ")
				{
						$uses[]		=substr($line, strlen("use "), strlen($line) - strlen("use ") - 1);

									load_class_file(end($uses), $deps, $stack);
				}
				else if(strpos($line, "extends") > 0)
				{
						$line		=str_replace("class ", "", $line);
						$line		=str_replace(" extends ", ";", $line);
						$fields		=explode(";", $line);
						
						$child		=$fields[0];
						$mother		=$fields[1];

						$found		=false;

					if(file_exists($namespace."\\".$mother.".php"))
								load_class_file($namespace."\\".$mother, $deps, $stack);
				}
				else if(strpos($line, "new ") > 0)
				{
						$data		=explode("new ", $line)[1];
						$class		=trim(explode("(", $data)[0]);

						$found		=false;

					foreach($uses as $use)
					if(strpos($use, $class))
					{
						$found		=true;
									break;
					}

					if(!$found)
					if(file_exists($namespace."\\".$class.".php"))
									load_class_file($namespace."\\".$class, $deps, $stack);
				}
				else if(strpos($line, "::") > 0)
				{
						$data		=explode("::", $line)[0];
						$data		=explode(" ", $data);
						$class		=trim(end($data));

						$found		=false;

					foreach($uses as $use)
					if(strpos($use, $class))
					{
						$found		=true;
									break;
					}

					if(!$found)
					if(file_exists($namespace."\\".$class.".php"))
									load_class_file($namespace."\\".$class, $deps, $stack);
				}
			}

						$deps[]		=$class_path;
		}
	}
}

?>`

Then simply execute once the main function to build dependencies :

```
include("autoload.php");

$classes	=array();
$classes[]	="BraintreeHttp\Encoder";
$classes[]	="PayPalCheckoutSdk\Core\PayPalHttpClient";
$classes[]	="PayPalCheckoutSdk\Core\SandboxEnvironment";
$classes[]	="PayPalCheckoutSdk\Orders\OrdersGetRequest";

			autoload($classes, "deps.php");
```
This code scans for the 4 main classes (Encoded, PaypalHttpClient, SandboxEnvironment and OrdersGetRequest) called by the sample code from SDK (PaypalClient class) :+1: 

```
class PayPalClient
{
    public static function client()
    {
        return new PayPalHttpClient(self::environment());
    }

    public static function environment()
    {
        $clientId = YOUR_SB_CLIENT_ID;
        $clientSecret = YOUR_SB_CLIENT_SECRET;
        return new SandboxEnvironment($clientId, $clientSecret);
    }
}

class PaypalOrder
{
  public static function getOrder($orderId)
  {
    $client = PayPalClient::client();
    $response = $client->execute(new OrdersGetRequest($orderId));
    print "Status Code: {$response->statusCode}\n";
    print "Status: {$response->result->status}\n";
    print "Order ID: {$response->result->id}\n";
    print "Intent: {$response->result->intent}\n";
    print "Links:\n";
    foreach($response->result->links as $link)
    {
      print "\t{$link->rel}: {$link->href}\tCall Type: {$link->method}\n";
    }
    print "Gross Amount: {$response->result->purchase_units[0]->amount->currency_code} {$response->result->purchase_units[0]->amount->value}\n";
  }
}
if (!count(debug_backtrace()))
{
  PaypalOrder::getOrder($_POST["orderID"], true);
}
```

Here are the depencencies generated from this autoloader, needed for the PayPalClient to work : 

```
require("BraintreeHttp/HttpRequest.php");
use BraintreeHttp\HttpRequest;
require("BraintreeHttp/Serializer.php");
use BraintreeHttp\Serializer;
require("BraintreeHttp/Serializer/Form.php");
use BraintreeHttp\Serializer\Form;
require("BraintreeHttp/Serializer/Json.php");
use BraintreeHttp\Serializer\Json;
require("BraintreeHttp/Serializer/FormPart.php");
use BraintreeHttp\Serializer\FormPart;
require("BraintreeHttp/Serializer/Multipart.php");
use BraintreeHttp\Serializer\Multipart;
require("BraintreeHttp/Serializer/Text.php");
use BraintreeHttp\Serializer\Text;
require("BraintreeHttp/Encoder.php");
use BraintreeHttp\Encoder;
require("BraintreeHttp/Curl.php");
use BraintreeHttp\Curl;
require("BraintreeHttp/IOException.php");
use BraintreeHttp\IOException;
require("BraintreeHttp/HttpResponse.php");
use BraintreeHttp\HttpResponse;
require("BraintreeHttp/HttpException.php");
use BraintreeHttp\HttpException;
require("BraintreeHttp/HttpClient.php");
use BraintreeHttp\HttpClient;
require("BraintreeHttp/Injector.php");
use BraintreeHttp\Injector;
require("PayPalCheckoutSdk/Core/AccessTokenRequest.php");
use PayPalCheckoutSdk\Core\AccessTokenRequest;
require("PayPalCheckoutSdk/Core/AccessToken.php");
use PayPalCheckoutSdk\Core\AccessToken;
require("PayPalCheckoutSdk/Core/AuthorizationInjector.php");
use PayPalCheckoutSdk\Core\AuthorizationInjector;
require("PayPalCheckoutSdk/Core/GzipInjector.php");
use PayPalCheckoutSdk\Core\GzipInjector;
require("PayPalCheckoutSdk/Core/FPTIInstrumentationInjector.php");
use PayPalCheckoutSdk\Core\FPTIInstrumentationInjector;
require("PayPalCheckoutSdk/Core/Version.php");
use PayPalCheckoutSdk\Core\Version;
require("PayPalCheckoutSdk/Core/UserAgent.php");
use PayPalCheckoutSdk\Core\UserAgent;
require("PayPalCheckoutSdk/Core/PayPalHttpClient.php");
use PayPalCheckoutSdk\Core\PayPalHttpClient;
require("BraintreeHttp/Environment.php");
use BraintreeHttp\Environment;
require("PayPalCheckoutSdk/Core/PayPalEnvironment.php");
use PayPalCheckoutSdk\Core\PayPalEnvironment;
require("PayPalCheckoutSdk/Core/SandboxEnvironment.php");
use PayPalCheckoutSdk\Core\SandboxEnvironment;
require("PayPalCheckoutSdk/Orders/OrdersGetRequest.php");
use PayPalCheckoutSdk\Orders\OrdersGetRequest;
```

I'm not a PHP expert to I did'nt want to use composer which I didn't know. Moreover, I did'nt know how to use it on my host server.

I'm still in testing mode, so the ProductionEnvironment class has not yet been scanned to build its dependencies.

I hope it will be usefull for anyone wanting to integrate simple paypal transaction to simple website, without using Composer or any CMS that could already includes Paypal Checkout System.
