### ISSUE TITLE
class 'string' not found in paypal intigration at line no 164

### ISSUE THREAD

**Issue by nikunj1806** [paypal/PayPal-PHP-SDK#201]
Fatal error: Class 'string' not found in /home/kanhawhp/public_html/rms/paypal/lib/PayPal/Common/PPModel.php on line 164

**Comment by nikunj1806** [comment]
i just show this error
 Class 'string' not found in paypal/lib/PayPal/Common/PPModel.php on line 164 when i tried to make paypal transfer on my server with fix value of that field.

**Comment by nikunj1806** [comment]
i send this data
$value = $_POST['value'];
$quantity = $_POST['quantity'];
$tax = $_POST['tax'];
$total = $_POST['total'];
$subtotal = $_POST['subtotal'];
in file CreatePaymentUsingPayPal.php
and the error will arise as above

**Comment by jaypatel512** [comment]
Hey @nikunj1806 ! Let me know what time CST you would be available online. We could do a chat, and try to iron out the issue.

**Comment by nikunj1806** [comment]
from 10am to 8pm

**Comment by nikunj1806** [comment]
even the static value the same error occurred can i miss anything when putting my code on site, or configuration settings which needed

**Comment by jaypatel512** [comment]
Hey @nikunj1806 ! I will be available online on [this hangout](https://plus.google.com/hangouts/_/gsudstesfm5gvv5fgns54dbt3qa). Can you please see if you could join the meeting, and we could solve the issue.

**Comment by jaypatel512** [comment]
Hey @nikunj1806 ! Could you please send me an email at jaypatel512@gmail.com when you would be free, if I am not available on hangout. We will setup the time, and get it done.

**Comment by jaypatel512** [comment]
Hey @nikunj1806 Please re-open this ticket if you are still facing this issue. I will be more than happy to help debug the issue.

**Comment by ulkas** [comment]
fyi, reference https://github.com/paypal/PayPal-PHP-SDK/issues/117#issuecomment-69150111

**Comment by nikunj1806** [comment]
hey @jaypatel512 and @ulkas  
it's just path set at server side to resolve this error
thanx for helping me and suggest me
