### ISSUE TITLE
Responsive frontend

### ISSUE THREAD

**Issue by shinesoftware** [paypal/PayPal-PHP-SDK#204]
Hi guys, I am trying to understand how to redirect all users to a responsive version of the Paypal. Which is the parameter that have I to send?

I am using the latest master version.

Any idea?

**Comment by jaypatel512** [comment]
Hey @shinesoftware ! It is an internal automatic decision that is causing the responsive/non-responsive mix coming to users. There is currently no way to fixate on one. However, it should be made as only frontend soon. nothing but being patient would be a solution. Sorry
