### ISSUE TITLE
Adaptive Payments using a different currency

### ISSUE THREAD

**Issue by shinesoftware** [paypal/PayPal-PHP-SDK#207]
Is there a way to play with the adaptive payments using a different currency between the primary receiver and the secondary receiver? If yes, how have I to do? thanks

**Comment by jaypatel512** [comment]
If you are mentioning about Classic APIs, we have a separate [github repository for classic APIs](https://github.com/paypal/adaptivepayments-sdk-php). However, if you are still using REST API for making this call, can you please let me know exact url or method you are calling.

**Comment by shinesoftware** [comment]
I am using the adaptivepayments-sdk-php module for zf2

In my composer I have set this:

    "paypal/adaptivepayments-sdk-php":"*",

and this is my custom method:

    /**
     * Create the Pay key code to redirect the user to the Paypal website
     * 
     * @param string email $receiver
     * @param float $amount
     * @param string $currency
     * @throws \Exception
     * @return string
     */
    public function getPayKey($receiver, $amount, $currency="EUR")
    {
        $link = null;
        $username = $this->settings->getValueByParameter('paypal', 'username');
        $password = $this->settings->getValueByParameter('paypal', 'password');
        $signature = $this->settings->getValueByParameter('paypal', 'signature');
        $appid = $this->settings->getValueByParameter('paypal', 'appid');
        $mode = $this->settings->getValueByParameter('paypal', 'mode');
        $log = $this->settings->getValueByParameter('paypal', 'log');
        $currency_fallback = $this->settings->getValueByParameter('paypal', 'currency');
        $baseUrl = $this->settings->getValueByParameter('paypal', 'baseurl');
        $paypal_receiver = $this->settings->getValueByParameter('paypal', 'receiver');
        $fee = $this->settings->getValueByParameter('paypal', 'fee');
        $success = "$baseUrl/paypal/success";
        $cancel = "$baseUrl/paypal/failure";
        $ipn = "$baseUrl/response/ipn";
        
        if(empty($username) || empty($password) || empty($signature) || empty($appid) || empty($currency) || empty($baseUrl))
            throw new \Exception('Paypal is not set yet! Go to the administration page and then Settings > Paypal');
        
        $config = array('acct1.UserName' => $username,
                'acct1.Password' => $password,
                'acct1.Signature' => $signature,
                'acct1.AppId' => $appid,
                'mode' => !empty($mode) ? $mode : "sandbox",
                'http.ConnectionTimeOut' => 30,
                'log.LogEnabled' => (bool)$log,
                'log.FileName' => LOG_PATH . 'PayPal.log',
                'log.LogLevel' => 'FINE',
                'validation.level' => 'log');
        
        $service = new \PayPal\Service\AdaptivePaymentsService($config);
         
        $payer = new \PayPal\Api\Payer();
        $payer->setPaymentMethod("paypal");
        
        $requestEnvelope = new \PayPal\Types\Common\RequestEnvelope("en_US");
        $receivers = array();
        
        $receivers[0] = new \PayPal\Types\AP\Receiver();
        $receivers[0]->email = $receiver; // A receiver's email address
        $receivers[0]->amount = $amount;  // Amount to be credited to the receiver's account
        $receivers[0]->primary = true;
         
        
        $receivers[1] = new \PayPal\Types\AP\Receiver();
        $receivers[1]->email = $paypal_receiver; // A receiver's email address
        $receivers[1]->amount = $fee;  // Amount to be credited to the receiver's account
        
        $receiverList = new \PayPal\Types\AP\ReceiverList($receivers);
        
        $payRequest = new \PayPal\Types\AP\PayRequest($requestEnvelope, "PAY", $cancel, $currency, $receiverList, $success);
        $payRequest->ipnNotificationUrl = $ipn;
        
        try {
            $response = $service->Pay($payRequest);
        } catch(\Exception $ex) {
            var_dump($ex->getMessage());
            die;
        }
        
        if ($response->responseEnvelope->ack == "Success"){
            return $response->payKey;
        }else{
            throw new \Exception($response->error[0]->message);
        }
    }

**Comment by jaypatel512** [comment]
As you can see here in `currencyCode` in https://developer.paypal.com/webapps/developer/docs/classic/api/adaptive-payments/Pay_API_Operation/, 

>The code for the currency in which the payment is made; you can specify only one currency, regardless of the number of receivers
