### ISSUE TITLE
Subtotal 0 throwing 400 Bad Request

### ISSUE THREAD

**Issue by jaypatel512** [paypal/PayPal-PHP-SDK#208]
Issue Mentioned in https://github.com/paypal/PayPal-PHP-SDK/issues/55#issuecomment-69012679

If you submit a negative amount item such as 'Discount' at '-3.50', if it brings your subtotal to 0 you get a 400 response:

The remote server returned an error: (400) Bad Request.

The only way I can get around this is by making by delivery charge my subtotal and vice versa, so:

ERRORS ON:
Shop Item: 3.50
Discount: -3.50
Delivery: 2.00
Subtotal: 0.00

WORKAROUND:

Shop Item: 3.50
Discount: -3.50
Delivery: 0.00
Subtotal: 2.00

Workaround works fine but isn't ideal because the delivery isn't what it is in real life.

**Comment by jaypatel512** [comment]
Just updating the internal ticket reference for future tracking: PPTIPS-2227

**Comment by jaypatel512** [comment]
Just as an update. The issue is getting fixed, and should be released soon.

**Comment by ppmtscory** [comment]
According to the internal ticket, and my testing, this issue seems resolved so I am going to close this ticket.  If there's any further issue, please feel free to let us know.
