### ISSUE TITLE
PrintError keep showing No Data on response

### ISSUE THREAD

**Issue by maesa** [paypal/PayPal-PHP-SDK#212]
Maybe you should use PPConnectionException instead of PayPalConnectionException on sample/common.php
```
if ($exception instanceof \PayPal\Exception\PPConnectionException ) {
    $data = $exception->getData();
}
```

*sorry for my English

**Comment by jaypatel512** [comment]
Hey @maesa ! I am not sure if you are using the latest release, but if I try to run the sample with invalid data, I am getting a proper error message. We made some [breaking changes](https://github.com/paypal/PayPal-PHP-SDK/wiki/Breaking-Changes---1.0.0) that involved making changes to names of our Exception, for [v1.0.0 release](https://github.com/paypal/PayPal-PHP-SDK/releases/tag/v1.0.0). Can you please make sure you have updated your code accordingly.

![screen shot 2015-01-11 at 12 06 07 pm](https://cloud.githubusercontent.com/assets/1309895/5696193/5fd6c18a-998a-11e4-930f-fa90663638c3.png)

**Comment by maesa** [comment]
Hmm, it's weird, maybe I have an issue with composer or something else. I install this paypal SDK  (v0.16.1) about 2 days ago using composer. Since then, I neither touch composer or make any changes manually. But somehow, I got "Exception/PPConnectionException.php" file and PayPalConnectionException in printError().

Now, I have updated it to v1.0.0 and see no problem.

Thank you for your quick response and you may close this issue.

Regards.

**Comment by jaypatel512** [comment]
Cool. Not sure exactly what happened there. But good news is, you have a nicely working latest SDK :) Enjoy. ! Btw, let me know if you run into any other issues, or think of any improvement to the SDK.
