### ISSUE TITLE
Cannot communicate securely with peer: no common encryption algorithm(s). 

### ISSUE THREAD

**Issue by chiragnirmal** [paypal/PayPal-PHP-SDK#214]
Hello,

As of 6:37AM EST on 1/12/2015 we started getting the following error from the paypal rest api client:
Cannot communicate securely with peer: no common encryption algorithm(s). 

I tried upgrading to the latest version 1.0.0 of the rest api client but that did not help. Can you please help?

Following information can was logged:
PayPal\Core\PPHttpConnection: Adding header Accept: */*
PayPal\Core\PPHttpConnection: Connecting to https://api.paypal.com/v1/oauth2/token
PayPal\Core\PPHttpConnection: Payload grant_type=client_credentials
PayPal\Core\PPHttpConnection: Adding header User-Agent: PayPalSDK/rest-sdk-php 0.6.0 (lang=PHP;v=5.5.20;bit=64;os=Linux_3.14.26-24.46.amzn1.x86_64;machine=x86_64;openssl=1.0.1j-fips;curl=7.38.0)
PayPal\Core\PPHttpConnection: Adding header Authorization: Basic {%removed our key from here%}
PayPal\Core\PPHttpConnection: Adding header Accept: */*

**Comment by jaypatel512** [comment]
Hey @chiragnirmal ! 

The issue you are facing is because of recent vulnerability found on SSLv3 called POODLE. We did make changes both on SDK and PayPal to disable accepting SSLv3. The way we are doing it is by enforcing the encryption algorithms that a client could use to make communications to your server. If you are using an old system, you might want to update your OS, to have latest encryption algorithms.

However, still if you are facing this issue, feel free to re-open this issue, and I could help you debug the issue. Also, I would recommend updating curl libraries, as it may not have the recent [SSL Fix](http://curl.haxx.se/docs/releases.html).

**Comment by chiragnirmal** [comment]
@jaypatel512 I have all the latest versions of openssl and curl available on amazon's repo. i.e.
openssl-1.0.1j-1.80.amzn1.x86_64
curl-7.38.0-1.48.amzn1.x86_64 
I can try to manually install the versions of these libraries from their websites, but would rather not do that because I would image a lot of people using paypal api would be using amazon linux servers.

**Comment by chiragnirmal** [comment]
@jaypatel512 OpenSSL 3 bug was fixed in amazon's repo in Oct 2014 itself and I have that same version openssl-1.0.1j-1.80.amzn1.x86_64 . Please see https://alas.aws.amazon.com/ALAS-2014-427.html

**Comment by jaypatel512** [comment]
Can you make sure you have done `yum clean all` first.

**Comment by chiragnirmal** [comment]
@jaypatel512 thanks for the quick reply! I ran ```yum clean all``` and also restarted the web server to be safe. Still getting the same error. Below a dump of the exception.

```
[url:PayPal\Exception\PPConnectionException:private] => https://api.paypal.com/v1/oauth2/token
    [data:PayPal\Exception\PPConnectionException:private] => 
    [message:protected] => Cannot communicate securely with peer: no common encryption algorithm(s).
    [string:Exception:private] => 
    [code:protected] => 35
    [file:protected] => /src/zoora/lib/composer/vendor/paypal/sdk-core-php/lib/PayPal/Core/PPHttpConnection.php
    [line:protected] => 91
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /src/zoora/lib/composer/vendor/paypal/rest-api-sdk-php/lib/PayPal/Auth/OAuthTokenCredential.php
                    [line] => 130
                    [function] => execute
                    [class] => PayPal\Core\PPHttpConnection
                    [type] => ->
                    [args] => Array
                        (
                            [0] => grant_type=client_credentials
                        )

                )

            [1] => Array
                (
                    [file] => /src/zoora/lib/composer/vendor/paypal/rest-api-sdk-php/lib/PayPal/Auth/OAuthTokenCredential.php
                    [line] => 104
                    [function] => _generateAccessToken
                    [class] => PayPal\Auth\OAuthTokenCredential
                    [type] => ->
                    [args] => Array
```

**Comment by chiragnirmal** [comment]
I think I found the issue, its my mistake I update the wrong composer library :disappointed_relieved:

**Comment by jaypatel512** [comment]
Oops !! :P 

Hope it works nicely now :)
