### ISSUE TITLE
Logs should never record full set of CC credentials during Live sessions

### ISSUE THREAD

**Issue by rgeddes** [paypal/PayPal-PHP-SDK#215]
I'm using the following config for logging Paypal transactions:

$apiContext->setConfig(
        array(
            'mode' => 'live',
            'http.ConnectionTimeOut' => 30,
            'log.LogEnabled' => true,
            'log.FileName' => '/xxx/xxx/xxx/PayPal.log',
            'log.LogLevel' => 'FINE',
            'validation.level' => 'log'
        )
    );

and in the request portion, I see full CC Credentials in the logs.  This is a security issue, and should probably never happen.

Can you advise how to config logging to provide detail, but avoid logging cc credentials.

Thanks,
Richard

**Comment by jaypatel512** [comment]
FINE Logging level is provided to give you entire message , and all the request response. However, it is not a good idea to keep FINE level logging for live. 

But you are right, there should be something more organized on how the logs are treated. The issue is, for some getting the request response and headers are useful for debugging, but not for live. However, it is definitely a security issue. 

How about this, we have a log level as `DEBUG`, which would print everything you send. But, if you make your mode as live, it wont log `request` and `response` headers. That should prevent people from logging crucial data, but will not be able to read that information on live ever.

Thoughts ?

**Comment by rgeddes** [comment]
Considering a wide range of people behavior, some people just copy and paste( probably most common ), others read the entire documentation before writing code( rare ), I would consider the FINE logging feature, as it currently stands, an accident waiting to happen.

My suggestions are:
If you do want to maintain this feature ( of logging everything for live ), then make it so the user has to actively select it (ie, it shouldn't be the default) and with many security warnings in the documentation. 
If you have a legal team,  I recommend you consult with them on how to phrase the caveats and warnings, to make sure you cover your 6.

OR

I think this was your suggestion, but I'm wording it in my own way:
Some additional code that only allows logging full cc credentials  during sandbox, but when switching to live, the same setting, logs only a partial set, enough to useful but not dangerous.   Live situations would never be allowed to log full cc credentials.

**Comment by jaypatel512** [comment]
Agreed @rgeddes ! We will discuss this with SDK team, as it would potentially affect every SDK. However, I do agree that logging request and response on live is very dangerous, and we should not be allowing that. 

However, having the ability to check request and response during sandbox development is quite crucial, as it helps developer understand what is happening. From what I think, having debug only available for sandbox, that prints all the information, and reducing (with PHP warning) to FINE, that prints only URL on live, as shown below:

![screen shot 2015-01-13 at 12 42 01 pm](https://cloud.githubusercontent.com/assets/1309895/5726528/9e2d27f6-9b21-11e4-87b0-da0c47894d9f.png)

Later if any developer asks for a specific feature to read entire logs on live, we could have a specific setting to override this restriction, somehow. But in general, everyone should get this message, if they try to use DEBUG on live environment.

**Comment by rgeddes** [comment]
In the meanwhile, can you point me to the documentation for the logging, so I can select a more appropriate logging level for the live environemnt.

Thanks.

**Comment by jaypatel512** [comment]
Sure. Here you go : https://github.com/paypal/PayPal-PHP-SDK/wiki/Logging
