### ISSUE TITLE
Get billing agreements

### ISSUE THREAD

**Issue by rise94** [paypal/PayPal-PHP-SDK#216]
Hi there!

The title says it all. 

Is there a way to get all the billing agreements, or at least a list of their IDs, because currently, correct me if I'm wrong, but, if you create, and execute a billing agreement, and don't save the returned ID there's no way to find the agreement in the future, since the only way to get an agreement is the 'get' method, but it requires an ID. 

I've seen some people struggling with this on SO, without getting any answers. 

So it would be great to have a method, to list all the Agreements, or to have a method in Plan like $plan->getAgreements() or something.

**Comment by jziaja** [comment]
Unfortunately, this is not currently possible.  We're following up with the API team to check the status of this feature and will provide an update when we have more information to share.

Duplicate issue: https://github.com/paypal/PayPal-Python-SDK/issues/70
(We'll provide updated information in that issue as it becomes available)

**Comment by anthonykozak** [comment]
Hi!
was the issue fulfilled or just closed ? this feature would still be useful !

**Comment by pp-randy** [comment]
The feature request is being tracked here https://github.com/paypal/PayPal-REST-API-issues/issues/5.
