### ISSUE TITLE
Address::setPostal_code() undefined...

### ISSUE THREAD

**Issue by Seth-Duncan** [paypal/PayPal-PHP-SDK#217]
Setup with composer within a Wordpress plugin directory(The plugin took advantage of the old SDK, this is in response to the SSLv3 deprecation). And what looks to be a successful creation with composer has led to this:

Call to undefined method PayPal\Api\Address::setPostal_code() in F:\Xampp\htdocs\wp-mcore\wp-content\plugins\ph-event-scheduler\ph-event-scheduler.php</b> on line 1533

ABSOLUTELY POSITIVE THAT ADDRESS IS THERE (As an address object is created and city and state are assigned fine) but it looks like it can't or won't access the base BaseAddress class. 

Was hoping this would be simple replace as the previous SDK version I am using has worked flawlessly for 2+ years, but have tried manual switchout (same error) and Composer switchout and stuck on this...

**Comment by Seth-Duncan** [comment]
Just a heads up, this is the first few lines of my Plugin code:

```
if(!file_exists(__DIR__ .'/vendor/autoload.php')) {
	echo "The 'vendor' folder is missing. You must run 'composer update' to resolve application dependencies.\nPlease see the README for more information.\n";

		$loader = require dirname(__DIR__) . '/vendor/autoload.php';
		$loader->add('PayPal\\Test', __DIR__);
		if (!defined("PP_CONFIG_PATH")) {
			define("PP_CONFIG_PATH", __DIR__);
		}
	
	
	
	//call references to Paypal API
	use PayPal\Rest\ApiContext;
	use PayPal\Auth\OAuthTokenCredential;
	use PayPal\Api\Address;
	use PayPal\Api\Amount;
	use PayPal\Api\CreditCard;
	use PayPal\Api\Payer;
	use PayPal\Api\Payment;
	use PayPal\Api\FundingInstrument;
	use PayPal\Api\Transaction;
	use PayPal\Api\Refund;
	use PayPal\Api\Sale;

}
```

**Comment by Seth-Duncan** [comment]
Offending code

```
// ### Address
				$addr = new Address();
				$addr->setLine1($txtAddress1);
				if (empty($txtAddress2)){
					$addr->setLine2("N/A");
				}else{
					$addr->setLine2($txtAddress2);
				}						
				$addr->setCity($txtCity);
				$addr->setState($txtState);
				$addr->setPostal_code($txtZipcode);
				$addr->setCountry_code("US");
				$addr->setPhone($txtPhone);
```

**Comment by Seth-Duncan** [comment]
Well it would appear that the SDK changed numerous method signatures for the different Objects. We went ahead and changed those in our application and got it working. Thanks.

**Comment by jaypatel512** [comment]
Yes, The 1.0.0 release have removed deprecated methods, which includes the one you mentioned.

**Comment by gegere** [comment]
@jaypatel512 these docs need to be update 

Calling [setCountry_code](https://developer.paypal.com/docs/api/#create-a-payment) in the documentation should be **setCountryCode**. I understand the newest release is not using these functions but it would be so sorry amazing if PayPal was able to communicate across the board.

Here are other functions which should updated:
- setPostal_code
- setExpire_month
- etc

The list goes on...

**Comment by jaypatel512** [comment]
Hey @gegere !

Thanks for pointing this out. I will let the documentation team be aware of that, and updated soon. However, we are revamping our developer docs soon, and are working on a new layout. For PHP based documentation, you can directly reach out to http://paypal.github.io/PayPal-PHP-SDK/. You should be able to find samples, wiki specifically designed for PHP SDK.

**Comment by gegere** [comment]
I have to say the documentation is pretty terrible. I really hope the documentation team are developers also.
