### ISSUE TITLE
Suddenly Sandbox connection throws "Problem with the SSL CA cert (path? access rights?)"

### ISSUE THREAD

**Issue by evk02** [paypal/PayPal-PHP-SDK#218]
Hi,
I have created my code to connect to the Sandbox a week ago, tested it and worked fine. I showed it to a few people and worked fine and now today suddenly it throws connection error:
exception 'PayPal\\Exception\\PPConnectionException' with message "Problem with the SSL CA cert (path? access rights?)"

I know this must mean something is wrong with the ca_certificate, I just don't see how this could "suddenly" be wrong. Isn't something (like the SSL) changed in PayPal sandbox?

**Comment by evk02** [comment]
Figured it out. The issue was caused by a recent nss-softoken package update on our CentOS server (see http://kiteplans.info/2015/01/15/solved-bug-centos-yum-rpm-broken-by-nss-softokn-3-14-3-19-el6_6-update-error-rpmts_hdrfromfdno-error-rpmdbnextiterator-header-v3-rsasha1-signature-key-id-bad/comment-page-1/#comment-112183), which was referring to another package nss-softoken-freebl, but they forgot to add it as a package dependency, so as soon as you installed this update nss-softoken got broken, so no RPMs, no YUM and no SSL.

**Comment by jaypatel512** [comment]
Oh !! Thats great to know you got it figured out. :) Let me know if you run into another issues in our SDK, or you think of any great new feature that we could have in our SDK to make your integration easier.

**Comment by evk02** [comment]
Thanks Jay!Yes, this issue was a little scary at first (how something can stop working suddenly without us changing anything in the code), but as it turned out it was caused by this faulty Red Hat package upgrade (https://bugzilla.redhat.com/show_bug.cgi?id=1182337) and luckily there already was a workaround available.
Thank, I will let you know if we can think of any new features. 

     On Monday, January 19, 2015 11:56 AM, Jay <notifications@github.com> wrote:
   

 Oh !! Thats great to know you got it figured out. :) Let me know if you run into another issues in our SDK, or you think of any great new feature that we could have in our SDK to make your integration easier.—

**Comment by udokmeci** [comment]
Off topic however is there any projection to mark billing agreement transactions? Something we customly add to discriminate?

> 
> Ugur Dokmeci 
> Tel: +90-532-383 39 44 


19 Oca 2015 tarihinde 18:56 saatinde, Jay <notifications@github.com> şunları yazdı:

**Comment by jaypatel512** [comment]
When you say mark, as in having a unique Id to every individual transaction that is done based on agreement, then I think it should be there if it is not already ! I am not sure if anyone has pointed this out before, but either way, let me ask the billing team about this !

**Comment by udokmeci** [comment]
Yeah it can be anything one field maybe json maybe text or string. Even a enum would be helpful. Thank you for trying anyway.

**Comment by jaypatel512** [comment]
From the search transactions, the return response will have a unique transactionId that will point to a specific transaction. Correct me if I am wrong there.
