### ISSUE TITLE
PayPal\Api\Agreement only accepts ShippingAddress

### ISSUE THREAD

**Issue by udokmeci** [paypal/PayPal-PHP-SDK#222]
Hi,
I don't know how to put it here but in our case I was setting ShippingAddress for our system and it works fine. Yet, we are not actually shipping anything, plans are for premium membership to our website. I have seen there is another option InvoiceAddress. So I decided to use it but its setter is not defined in Agreement. 

``` php
Call to undefined method PayPal\Api\Agreement::setInvoiceAddress()
```
Both extends address. Here is the question. Is code missing or does the system accept only ShippingAddress?

Thank you.

**Comment by jaypatel512** [comment]
According to [developer docs](https://developer.paypal.com/webapps/developer/docs/api/#create-an-agreement) creating an agreement has only shipping_address as a part of the request. As far as I am aware, there is no such field as invoice_address. However, let me know where you saw that, and I could possibly get more details about it.

Please re-open the issue, if you feel agreement accepts invoice_address.
