### ISSUE TITLE
If set shipping to null in Details, will get malformed JSON when creating a payment

### ISSUE THREAD

**Issue by cullylarson** [paypal/PayPal-PHP-SDK#223]
Set shipping to null, and don't set any other values in the Details object:

```
$ppDetails = new PayPal\Api\Details();
$ppDetails->setShipping(null);

$ppAmount = new PayPal\Api\Amount();
$ppAmount
    ->setTotal('10')
    ->setCurrency('USD')
    ->setDetails($ppDetails);
```

Then create the payment, and you'll get a JSON request payload like this:

```
{
...
    "transactions": [
        {
            "amount": {
                "total": "10",
                "currency": "USD",
                "details": []
            }
        }
    ]
}
```

See how the "details" element is set to "[]"?  It's supposed to be an object.  In any case, this will result in the following response from the API:

```
PayPal\Core\PayPalHttpConnection: FINE: Response : {"name":"MALFORMED_REQUEST","message":"Incoming JSON request does not map to API request","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#MALFORMED_REQUEST","debug_id":"..."}
```

If you just set shipping to 0, this won't happen.  Not sure if this is a bug (i.e. people shouldn't be setting shipping to null), but it's was SUPER confusing to track down what was cauing the malformed error.

**Comment by jaypatel512** [comment]
Hey @cullylarson ! I agree. The object conversion seem to be doing something crazy here. I will definitely look into this, and allow it to create an empty object.
