### ISSUE TITLE
An invalid link in an error response

### ISSUE THREAD

**Issue by MartyIX** [paypal/PayPal-PHP-SDK#228]
Hello,

I've received the error message below (PayPal sandbox):

    [28-01-2015 12:06:33] PayPal\Core\PayPalHttpConnection: FINE: Response : {"name":"ADDRESS_INVALID","message":"Provided user address is invalid.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#ADDRESS_INVALID","debug_id":"c363764ba1b24"}

and the information link is not working: https://developer.paypal.com/webapps/developer/docs/api/#ADDRESS_INVALID

It is a minor issue.

Have a nice day!

**Comment by jaypatel512** [comment]
Thank you so much for informing us. Let me forward this to documentation team.

**Comment by jaypatel512** [comment]
Btw, @MartyIX Can you please tell me when was this error thrown to you ? Making Payment calls ? 

This will help me find the right team to add that documentation for us.

**Comment by MartyIX** [comment]
It was thrown when I attempted to create a new billing agreement with a wrong shipping address (an invalid country code was used).

**Comment by jaypatel512** [comment]
Awesome @MartyIX ! thanks.
