### ISSUE TITLE
Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/oauth2/token.

### ISSUE THREAD

**Issue by kalpitpandit** [paypal/PayPal-PHP-SDK#229]
I suddenly started getting this error in payout API, Prior it was working fine.

"Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/oauth2/token."

**Comment by jaypatel512** [comment]
Yes !! Actually, we were just being notified, the sandbox authorization server has brought down for maintenance/upgrade, and will be back very very soon. Sorry about that.

**Comment by jaypatel512** [comment]
You should be able to track the status [here](https://www.paypal-notify.com/eventnotification/search?eventSearchType=PayPalSiteStatus)

**Comment by kalpitpandit** [comment]
Thanks for quick update :+1:

**Comment by lfwebdev** [comment]
I am having the same issue. Is the server still down?

**Comment by jaypatel512** [comment]
Hey @lfwebdev ! I am able to get proper Oauth calls from the sandbox environment just fine. Let me know if you are facing that intermittently, or continuously.

**Comment by lfwebdev** [comment]
It is actually continusly: Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment.

But it was working fine a couple of weeks ago.

**Comment by jaypatel512** [comment]
I am sorry if I got that wrong. If possible, can you please run the samples, other than payment if possible, from our SDK. I just want to confirm if the issue is the one where entire sandbox is down, or the API is down. Thanks @lfwebdev for giving more information.

**Comment by kalpitpandit** [comment]
I am also facing same issue @jaypatel512

**Comment by jaypatel512** [comment]
It must be true. From PayPal Notifications, I was able to realize that few sections are facing 500 Exceptions, as mentioned [here](https://www.paypal-notify.com/eventnotification/event_details?eventId=6057)

I will keep you updated on this. Apologies for that.

**Comment by lfwebdev** [comment]
I am sorry, I can't get to run the Tests. I don't know how to do it. I got this error: Fatal error:  Class 'PHPUnit_Framework_TestCase'. I don't know if @kalpitpandit was able to do it.

**Comment by kalpitpandit** [comment]
@ifwebdev Testcase and API is working fine for me, Only disappointing thing is sandbox/API going down frequently. i would recommend you to use update your SDK.

**Comment by lfwebdev** [comment]
Ok will do. Thank you.

**Comment by jaypatel512** [comment]
What I meant by this is, you could run samples on our SDK to test out each APIs. In future too, this would help you reproduce the scenario that you are trying to accomplish, by making some minor changes to sample, and test it out. 

Here is the link on how to run samples: https://github.com/paypal/PayPal-PHP-SDK/wiki/Samples

It is just one command that you need to run, if you are running PHP 5.4 or higher.

**Comment by mukeshra** [comment]
Hi, i am also getting the same issue.

Exception: Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment/v1/oauth2/token. 

can anyone help me out?
