### ISSUE TITLE
Property assigment "secretKey" typo

### ISSUE THREAD

**Issue by antosdaniel** [paypal/PayPal-PHP-SDK#230]
I belive you have a typo here: https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Security/Cipher.php#L23

(secretKey instead of $secretKey?)

**Comment by jaypatel512** [comment]
Yes, you are right. I will make a fix on this as soon as possible.

Thanks for pointing this out.

**Comment by jaypatel512** [comment]
I will make a patch release soon with this, as this affects the security aspect of cipher. Thank you so much for pointing this out. Please update your SDK to latest version when it is ready. I should be able to make patch release by EOD today.
