### ISSUE TITLE
SDK resets time zone if no ini file is used

### ISSUE THREAD

**Issue by druteika** [paypal/PayPal-PHP-SDK#231]
In file lib/PayPal/Core/PayPalLoggingManager.php on line 75 there is a setter for timezone, which always resets the timezone if there's no ini value.

In my case I am not using ini files, but using dynamic configuration inside a framework.
Now problem is, that SDK resets the timezone of the framework.

Is it possible to make date.timezone also accepted by ApiContext setConfig as one of settings? And then in PayPalLoggingManager.php:74 check it as setting, not just ini value.

**Comment by jaypatel512** [comment]
Hey @druteika ! I would be glad to make a fix for this. However, it would be nice if we could test the changes in your machine, before I make a push. Would you mind helping me out with that.

There is an alternative where I could let PHP decide what the date is. The code would look like this:

```php
// Suppress DateTime warnings
date_default_timezone_set(@date_default_timezone_get());
```

Can you please replace the below code with the one above:

```php
if (!ini_get('date.timezone')) {
      date_default_timezone_set('GMT');
}
```

What the one above does is, set the timezone that PHP thinks is right, and suppresses any warning if present. This would help people not get those weird warning all over the place, and let you keep the default time zone.

Let me know if this fix would work for you, and I could make the changes, and run additional tests, and get it going. :) 

Thanks

**Comment by jaypatel512** [comment]
Hey @druteika ! Did you got the time to try out the issue, and see if it fixes the issue. Let me know, and I would be more than happy to make a commit and release soon.

**Comment by druteika** [comment]
Hello @jaypatel512 ,

I am sorry, I have no time capacity to do much fixes at the moment.

My quick solution was to use `ini_set('date.timezone', date_default_timezone_get())` since I always have timezone in the framework.

**Comment by jaypatel512** [comment]
Makes sense. Actually, very similar to what I proposed. I will still go ahead and try to test it on different machines. If in the meantime, if you get some time to make this tiny change, and test it out, I would really appreciate your help.
