### ISSUE TITLE
Update a stored credit card

### ISSUE THREAD

**Issue by engrsandeep** [paypal/PayPal-PHP-SDK#233]
I am wondering if possible to update stored credit card by rest api. I have tried to use it like below code.  Can you please help.

Error :
{"name":"MALFORMED_REQUEST","message":"Incoming JSON request does not map to API request"}

Sample code:
$card = new CreditCard();
    	$card->setId($creditCardID);
    	$card->setFirstName($params['first_name']);
    	$card->setLastName($params['last_name']);
    	$card->setExpireMonth($params['expire_month']);
    	$card->setExpireYear($params['expire_year']);
    	$card->setNumber($params['number']);
    	$card->setType($params['type']);
    	$card->setCvv2($params['cvv']);
    	
    	
    	try
    	{
    		$card->update($this->context);
    		
    		$card = CreditCard::get($card->getId(), $this->context);
    		
    		return $card->getId();
    	}
    	catch(Exception $e)
    	{
    		var_dump($e);
    		return FALSE;
    	}

Many Thanks.

**Comment by jaypatel512** [comment]
Hey @engrsandeep !! I will make the release soon, with few other fixes lined up. Feel free to use `dev-master` as your version to download latest master version, if you are using composer.

**Comment by engrsandeep** [comment]
Thanks for quick help @jaypatel512

**Comment by engrsandeep** [comment]
There is one more thing in this. 

Paypal rest api document says below url for update a stored credit card
PATCH /v1/vault/credit-card**s**/Credit-Card-Id

Rest Api Calling:
PATCH /v1/vault/credit-card/Credit-Card-Id

Which one is correct?

**Comment by engrsandeep** [comment]
I have taken dev-master and now getting error
{"name":"INVALID_PATCH","message":"Invalid PATCH request"}

I m using below code to update credit card.
$patch = new Patch();
    	$patch->setOp('replace')
		    	->setPath('/')
		    	->setValue(json_decode('{
		            "type": "'.$params['type'].'",
		    		"number":"'.$params['number'].'",
		    		"first_name":"'.$params['first_name'].'",
		    		"last_name":"'.$params['last_name'].'",
		    		"cvv2":"'.$params['cvv'].'",
		    		"expire_month":"'.$params['expire_month'].'",
		    		"expire_year":"'.$params['expire_year'].'"
		        }'));
    	
    	$patchRequest = new PatchRequest();
    	$patchRequest->addPatch($patch);
    	
    	try
    	{
    		$card = CreditCard::get($creditCardId, $this->context);
    		
    		$card->update($patchRequest,$this->context);
    		
    		$card = CreditCard::get($card->getId(), $this->context);
    		
    		return $card->getId();
    	}
    	catch(Exception $e)
    	{
    		var_dump($e);
    		return FALSE;
    	}

**Comment by jaypatel512** [comment]
Hey @engrsandeep ! 

Both credit-card and cards are fine. However, I will update it to credit-cards, as the credit-card will be deprecated soon. Good thing is, you dont need to worry about it, as SDK will automatically update it moving further.

And regarding your invalid patch request. Not entire object could be updated. Please have a look at the [sample code](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/vault/UpdateCreditCard.php#L20) showing hot to change a specific field. Also, please note that not all fields are updatable. For e.g. Type, CVV2, couldn't be updated. Ideally, if the card identity is incorrect, you would want to create a new instance of credit card object.

**Comment by engrsandeep** [comment]
Ok, but it not mentioned anywhere that which fields of object can be update. So may I ask, can we update credit card token and plan id in existing agreement?

**Comment by jaypatel512** [comment]
No. you cannot change the planId. Sorry about that. You need to create a new agreement if you wish to change the plan Id in future.

**Comment by engrsandeep** [comment]
Ok, so there is no way to upgrade user package like we have some packages for user. We wants to allow upgrade and degrade existing package. if user wants to upgrade. we can not provide new plan id to that agreement simply? 

If we create new agreement for user than how outstandings will be charged if any? Is api provide an option to force user to pay outstandings so like we can put link to pay outstandings simply?

Any help?

**Comment by jaypatel512** [comment]
Hey @engrsandeep ! Just to update you, we have made a [release](https://github.com/paypal/PayPal-PHP-SDK/releases/tag/v1.2.0) and updated [composer](https://packagist.org/packages/paypal/rest-api-sdk-php), that includes the fix for that Vault API Update in Credit Card. You could not use 1.* version of code, without any issue. 

I am trying to get answer on the question about billing plan and agreement. I will get back to you as soon as I have the answer to that.

**Comment by engrsandeep** [comment]
Thanks @jaypatel512 . Your help is much appreciated.

**Comment by renielDev** [comment]
Hi @jaypatel512 

I am trying to update one of the stored cards but It's giving me 400 response. 
It is working well if I only patch expire_month and expire_year but when trying to add
the other 3, it doesn't work. What I'm missing? Thanks.

Here is my code : 

$pathOperation = new Patch();
        $pathOperation->setOp('replace')
            ->setPath('/expire_month')
            ->setValue('12');

        $pathOperation2 = new Patch();
        $pathOperation2->setOp('replace')
            ->setPath('/expire_year')
            ->setValue('2020');

        $pathOperation3 = new Patch();
        $pathOperation3->setOp('replace')
            ->setPath('/number')
            ->setValue('4417119669820331');

        $pathOperation4 = new Patch();
        $pathOperation4->setOp('replace')
            ->setPath('/cvv2')
            ->setValue('122');

        $pathOperation5 = new Patch();
        $pathOperation5->setOp('replace')
            ->setPath('/type')
            ->setValue('visa');

        $pathRequest = new \PayPal\Api\PatchRequest();
        $pathRequest
            ->addPatch($pathOperation)
            ->addPatch($pathOperation2)
            ->addPatch($pathOperation3)
            ->addPatch($pathOperation4)
            ->addPatch($pathOperation5);

        try {
            $card = CreditCard::get('CARD-2R457877BM548793VLGKYRYQ', $this->paypalContext);
            $card->update($pathRequest, $this->paypalContext);
            // dd($card);

            // $card = $card->update($pathRequest, $this->paypalContext);
        } catch (Exception $ex) {
            return $this->response('error', $e->getMessage());
        }

**Comment by xiaoleih41** [comment]
@renielDev Is this a non-UK new integration? As you can see in the updates of this SDK, credit card processing has been removed. Briantreepayment.com integration is recommended going forward as it supports not only credit card, paypal but other popular form of payment methods.
