### ISSUE TITLE
Stored credit card do not return back correct first and last name.

### ISSUE THREAD

**Issue by engrsandeep** [paypal/PayPal-PHP-SDK#235]
When retrieving stored credit card by credit card id, it returns last name as first name and actual first name never returned.

So if i have credit card with **First Name**: **Sandeep** and **Last Name**: **Kumar**, it return back **First Name** as **Kumar** and **Last Name** empty.

Can you please help?

**Comment by jaypatel512** [comment]
Hey @engrsandeep ! I am not sure why you are facing this issue. When I ran the sample given on the SDK, I got this response. Can you please try the samples, and see if you are seeing the same or not.

![screen shot 2015-02-04 at 1 14 03 am](https://cloud.githubusercontent.com/assets/1309895/6036489/3cc1d070-ac0b-11e4-8ecf-6936377e4d7e.png)


Thanks

**Comment by engrsandeep** [comment]
I got response like below when I tried to retrieve stored credit card, you can see last name is completely missing but i have supplied both first name and last name when stored credit card

    ["id"]=>
    string(29) "CARD-XXXXXXXXX"
    ["state"]=>
    string(2) "ok"
    ["external_customer_id"]=>
    string(2) "38"
    ["type"]=>
    string(4) "visa"
    ["number"]=>
    string(16) "xxxxxxxxxxxx0123"
    ["expire_month"]=>
    string(2) "12"
    ["expire_year"]=>
    string(4) "2019"
    ["first_name"]=>
    string(5) "Kumar"
    ["valid_until"]=>
    string(20) "2018-02-03T00:00:00Z"
    ["create_time"]=>
    string(20) "2015-02-04T07:16:26Z"
    ["update_time"]=>
    string(20) "2015-02-04T07:16:26Z"

**Comment by jaypatel512** [comment]
Can you send me the logs, preferably in FINE level, so that I could see what was sent and received. Feel free to obscure the credit card number, or any other sensitive data.

**Comment by jaypatel512** [comment]
Also, it would really help, if you could run the samples and test this out. It helps figuring out any issues in SDK very easily.

**Comment by jaypatel512** [comment]
Here is the [documentation](https://github.com/paypal/PayPal-PHP-SDK/wiki/Samples) that explains how to run the samples, from your local machine. They are very easy to setup, and run.

**Comment by engrsandeep** [comment]
I ran the samples and all worked fine. 

I got my fault. now its working fine.

Thanks for looking into this.
