### ISSUE TITLE
Order API

### ISSUE THREAD

**Issue by cabrilo** [paypal/PayPal-PHP-SDK#237]
Hello,

As it looks like now, PayPal\Api\Order class extends PayPalModel and is just a class to encapsulate order object. (https://developer.paypal.com/docs/api/#order-object)

However, orders are resources which have several operations, including authorize, capture and void. Would it make sense to implement those and have Order extends PayPalResourcesModel?

Is it just not implemented yet, or am I missing the bigger picture?
Would you implement this (or accept a pull request which implements these things)? 

Thanks for all the hard work :)
Dejan

**Comment by jaypatel512** [comment]
Hey @cabrilo, I realized that 2 days back about it. Generally, all these API objects are automatically created by schema's of those APIs, and it seems like generator didnt understood the order API schema, that led them to not create those options. 

I will definitely go ahead and start working on this, and keep you updated on this thread. However, we do accept pull request for any issue you think you could help the sdk with.

**Comment by jaypatel512** [comment]
Hey @cabrilo ! I have added the code for order APIs. I will make a release soon.

I have also added the [samples](https://github.com/paypal/PayPal-PHP-SDK/wiki/Samples) for making order calls. Feel free to create another issue if you face any issue.

**Comment by cabrilo** [comment]
@jaypatel512 wow, impressive! Thanks. I think I'll test & deploy it soon. If you don't hear from me - it works great :) Thanks again, that was impressive speed.

**Comment by jaypatel512** [comment]
I am glad :) 

We, as PayPal are dedicating ourselves to serve external developers better than ever. Helping them resolve these issues, faster than ever.

**Comment by jaypatel512** [comment]
Both [Composer](https://packagist.org/packages/paypal/rest-api-sdk-php), and [Direct Download](https://github.com/paypal/PayPal-PHP-SDK/releases/tag/v1.2.0) have been updated with the release containing Order API Fix.
