### ISSUE TITLE
Stored credit card token is not working

### ISSUE THREAD

**Issue by engrsandeep** [paypal/PayPal-PHP-SDK#238]
I have stored credit card and added token to agreement then I got below error.

**Funding Instrument Details are missing or Funding instrument not supported. Only credit-card is supported.**

````php
$payer = new Payer();
$payer->setPaymentMethod("credit_card");    	

$credit_card_token = new CreditCardToken();
$credit_card_token->setCreditCardId($credit_card_id);
$credit_card_token->setPayerId($user_id);

$fundingInstrument = new FundingInstrument();
$fundingInstrument->setCreditCardToken($credit_card_token);
    		
$payer->setFundingInstruments(array($fundingInstrument));

$agreement->setPayer($payer);
````

Can you please help?

**Comment by jziaja** [comment]
Unfortunately, using a credit card token as the funding instrument isn't currently supported when creating billing agreements.  I'm following up with the subscription team to check the current status of supporting this feature.  If anything, the error message should be changed to indicate that credit card tokens aren't currently supported.

**Comment by engrsandeep** [comment]
Ok, then what is benefit to store a credit card with paypal?

**Comment by jziaja** [comment]
> Ok, then what is benefit to store a credit card with paypal?

Using a credit card token is supported for making [one time payments](https://developer.paypal.com/docs/integration/direct/accept-credit-cards/).  

In context of billing agreements, using a credit card token is currently not supported as a funding instrument.

**Comment by jaypatel512** [comment]
Closing this issue to be tracked on https://github.com/paypal/PayPal-Python-SDK/issues/60
