### ISSUE TITLE
How to set the taxes and shipping manually by customer instead of hardcoding?

### ISSUE THREAD

**Issue by dineshi2it** [paypal/PayPal-PHP-SDK#240]
I have set up taxes and shipping in Paypal by referring this link http://westwoodva.com/blog/set-taxes-shipping/
Customers in Texas will need 8.25% sales tax. 
So How should I change it in CreatePaymentUsingPayPal.html instead of setting the default tax & shipping in $details.
When I used paypal buttons it works good as below.
![shipping_and_tax](https://cloud.githubusercontent.com/assets/5243459/6074307/89043144-ade1-11e4-9dd3-4ad550cabb2e.png)

**Comment by jaypatel512** [comment]
Hey @dineshi2it ! This github is for PayPal-PHP-SDK. The link you have mentioned is not related to this SDK. Please reach out to [PayPal Technical Support](https://www.paypal.com/us/webapps/helpcenter/helphub/home/)

**Comment by dineshi2it** [comment]
I understand, but is there any way not to hardcode the taxes?
Can't we set depending on the zipcode?
