### ISSUE TITLE
Billing Agreements - Override Merchant Preferences

### ISSUE THREAD

**Issue by cre8tiveweb** [paypal/PayPal-PHP-SDK#245]
This feature doesn't seem to be working:

Example:

I have an "Active" Billing Plan that has a Setup Fee of $4.99,

````php
$merchantPreferences->setReturnUrl($baseUrl."subscriptions/?call=subscription&payment_type=paypal&success=true")
->setCancelUrl($baseUrl."subscriptions/?call=subscription&payment_type=paypal&success=false")
->setAutoBillAmount("no")
->setMaxFailAttempts("1")
->setSetupFee(new Currency(array('value' => 4.99, 'currency' => 'USD')))
````

Now there are cases that we need to use the same Billing Plan but with "Zero" setup fee.

When creating an Agreement with `override_merchant_preferences` to remove the setupFee, it still charges the User the same amount as the original Billing Plan.:

````php
$merchantPreferences->setReturnUrl($baseUrl."subscriptions/?call=subscription&payment_type=paypal&success=true")
->setCancelUrl($baseUrl."subscriptions/?call=subscription&payment_type=paypal&success=false")
->setAutoBillAmount("no")
->setMaxFailAttempts("1")
->setSetupFee(0)

$agreement->setOverrideMerchantPreferences( $merchantPreferences);
````

Also note that the `setReturnUrl` and `setReturnCancel` works... but can't seem to override SetupFee settings - is this supported? if not please add support asap...

Let me know, thanks!

**Comment by jaypatel512** [comment]
Hey @cre8tiveweb !

SetupFee is a Currency object, and not an integer. Because of PHP's default behavior to take any value, it worked. However, what you might be doing is something like this:

```php
$merchantPreferences->setSetupFee(new Currency(array('value' => 0, 'currency' => 'USD')));
```

The same way you pass on 4.99, you have to pass 0 there. But you still have to pass a currency object.

**Comment by cre8tiveweb** [comment]
thanks Jay for the response, will give it a try real quick..

**Comment by cre8tiveweb** [comment]
it worked! thank you!
