### ISSUE TITLE
ExpressCheckout

### ISSUE THREAD

**Issue by caBBAlainB** [paypal/PayPal-PHP-SDK#247]
merchant-sdk is deprecated but I cannot find the ExpressCheckout Feature in this one. What to do?

**Comment by jziaja** [comment]
Hi @caBBAlainB, please refer to the [PayPal Developer documentation](https://developer.paypal.com/docs/integration/direct/rest-payments-overview/) on making payments with the PayPal REST API, which this SDK is built on.  There's also some great [samples](https://github.com/paypal/PayPal-PHP-SDK/tree/master/sample) included with this SDK that show exactly how to create and execute a payment.
