### ISSUE TITLE
Unknown SSL protocol error in connection to api-s.sandbox.paypal.com:443 

### ISSUE THREAD

**Issue by aqeelrepoowner** [paypal/PayPal-PHP-SDK#250]
I am getting this error after running Paypal/PHP/SDK samples for authorize payment.

Please let me know solution for this

**Comment by avidas** [comment]
Hey @aqeelrepoowner try changing to api.sandbox.paypal.com to see if you are still having the issue

**Comment by aqeelrepoowner** [comment]
Yes even tried it but same error .  Unknown SSL protocol error in connection to api.sandbox.paypal.com:443

**Comment by aqeelrepoowner** [comment]
I am running it from localhost server. I think this would not create any problem as paypal uses CURL.

**Comment by jaypatel512** [comment]
Can you run `curl --version` in your command line, and provide me with the output. Also, can you please try the [latest release](https://github.com/paypal/PayPal-PHP-SDK/tree/v1.2.0) and try this. We reverted URLs back to api.sandbox.com.

**Comment by jaypatel512** [comment]
Closing this issue based on highly unlikeliness of it happening now. The commit that added api-s.sanbox.paypal.com has been reverted in the future commits, and should not be present anymore.

**Comment by shinijaQB** [comment]
Am getting error 'Unknown SSL protocol error in connection to api.sandbox.paypal.com:443 when making first call as per the doc (https://github.com/paypal/PayPal-PHP-SDK/wiki/Making-First-Call)

**Comment by pp-randy** [comment]
@shinijaQB ensure you are on the most recent release of this SDK.  Also review https://github.com/paypal/tls-update.   

If you are unable to correct after reviewing the above please file a new issue and we will take a look.

**Comment by pp-randy** [comment]
Locking the thread due to age, please file a new issue if you encounter this error if one is not already open.
