### ISSUE TITLE
parent_payment is missing on Webhook notification

### ISSUE THREAD

**Issue by jethdeguzman** [paypal/PayPal-PHP-SDK#251]
My webhook notification url receives webhook events properly. One thing i wonder about is the inconsistency of the json object posted. 

When i use paypal rest payment sale refund the oject posted is like this

````json
{
	"id": "WH-5AJ94700JE919132V-5SS03462WU8938309",
	"create_time": "2015-02-24T10:31:19Z",
	"resource_type": "sale",
	"event_type": "PAYMENT.SALE.REFUNDED",
	"summary": "A $ 10.0 USD sale payment was refunded",
	"resource": {
		"id": "86P867858D9634917",
		"create_time": "2015-02-24T10:30:14Z",
		"update_time": "2015-02-24T10:30:14Z",
		"state": "completed",
		"amount": {
			"total": "-10.00",
			"currency": "USD"
		},
		"sale_id": "6RL269607X164743P",
		"parent_payment": "PAY-7B9392223W8965434KTWFERY",
		"links": [{
			"href": "https://10.72.108.213:11881/v1/payments/refund/86P867858D9634917",
			"rel": "self",
			"method": "GET"
		},
		{
			"href": "https://10.72.108.213:11881/v1/payments/payment/PAY-7B9392223W8965434KTWFERY",
			"rel": "parent_payment",
			"method": "GET"
		},
		{
			"href": "https://10.72.108.213:11881/v1/payments/sale/6RL269607X164743P",
			"rel": "sale",
			"method": "GET"
		}]
	},
	"links": [{
		"href": "https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-5AJ94700JE919132V-5SS03462WU8938309",
		"rel": "self",
		"method": "GET"
	},
	{
		"href": "https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-5AJ94700JE919132V-5SS03462WU8938309/resend",
		"rel": "resend",
		"method": "POST"
	}]
}
````

But when i refund a payment sale on the merchant dashboard i got something like this . The parent_payment  is missing. 

````json
{
	"id": "WH-3FP42695GJ186162S-2AH978653H323444S",
	"create_time": "2015-02-24T03:22:18Z",
	"resource_type": "sale",
	"event_type": "PAYMENT.SALE.REFUNDED",
	"summary": "A $ 10.0 USD sale payment was refunded",
	"resource": {
		"id": "0FN301188F222022V",
		"create_time": "2015-02-24T03:21:27Z",
		"state": "completed",
		"amount": {
			"total": "-10.00",
			"currency": "USD",
			"details": {
				"subtotal": "-10.00"
			}
		},
		"links": [{
			"href": "https://10.72.108.213:11881/v1/payments/refund/0FN301188F222022V",
			"rel": "self",
			"method": "GET"
		}]
	},
	"links": [{
		"href": "https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-3FP42695GJ186162S-2AH978653H323444S",
		"rel": "self",
		"method": "GET"
	},
	{
		"href": "https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-3FP42695GJ186162S-2AH978653H323444S/resend",
		"rel": "resend",
		"method": "POST"
	}]
} 
````

Would there be a way where i can get the parent_payment when a payment is refunded on the merchant dashboard?

**Comment by jaypatel512** [comment]
Oh ! This definitely seems to be a an inconsistent behavior. Let me get with the Payments Team, and get back to you on this. Apologies for the inconvenience.

**Comment by jaypatel512** [comment]
Just an update. The bug has been accepted, and would be resolved shortly. The deadline is unavailable.

**Comment by jaypatel512** [comment]
More Update. The issue has been realized by the API team, and they are going to make a fix on the major release. However, it wont be an immediate fix, but it would be a part of major fix.

**Comment by dstotijn** [comment]
Hi @jaypatel512, do you have an estimate when the fix for this issue will be released?

**Comment by jaypatel512** [comment]
SDK Engineering Team does not have access to those information unfortunately. However, you could directly get in contact with [Merchant Technical Support](https://www.paypal-techsupport.com/app/ask), for detailed information and estimates.

**Comment by horch004** [comment]
6 month later and still no ETA for the fix. With a great looking rich featured API, such a basic notification issue should be fixed before everything else (in my opinion).
We just implemented Paypal as a payment gateway at request of our customers and have to warn them right away that the system can be inconsistent because of a long time bug in the Paypal API. That is a bit sad.

**Comment by ppmtscory** [comment]
Closing as this has since been resolved.
