### ISSUE TITLE
Cookie error - Paypal payment

### ISSUE THREAD

**Issue by cchacholiades** [paypal/PayPal-PHP-SDK#252]
I have Paypal integrated in a Laravel project and everything was working just fine until today.  I get this error which says "Please turn on cookies to check out". 

- I cleared the cookies and made sure that are enabled on my browser.
- I tried to test it on other browsers and even going incognito.

But the problems persists.

![screen shot 2015-02-25 at 14 14 19](https://cloud.githubusercontent.com/assets/2761712/6372608/21509bbe-bd0e-11e4-926e-dd27f266dd98.png)

**Comment by jaypatel512** [comment]
Hey @cchacholiades ! It seems like an issue from PayPal checkout and not the SDK. However, I will let you know once I have an input for you.

**Comment by jaypatel512** [comment]
Hey @cchacholiades ! The issue has been recognized by [PayPal Notification](https://www.paypal-notify.com/eventnotification/event_details?eventId=6109) and they are currently working on this. Please monitor this notification. 

Thank you.

**Comment by cchacholiades** [comment]
Hi @jaypatel512 ! Thank you for replying. Many thanks for that notification. I guess we should wait until its fixed.
