### ISSUE TITLE
CURLINFO_HEADER_SIZE not supported for curl < 7.30.0

### ISSUE THREAD

**Issue by platformoperations** [paypal/PayPal-PHP-SDK#258]
Hi,

After upgrade to newest version we started seeing this error:

```
PayPal\Exception\PayPalConnectionException: Could not generate new Access token. Invalid response from server
```

After short investigation we found php curl library needs to be upgraded as to at least version **>=7.30.0** in order to properly handle **CURLINFO_HEADER_SIZE** used by **1.2.1**.

As a result, in client we are getting incorrect chunk of data which can not get json decoded:

Example of chunk received:

"plication/json
Content-Length: 318

{"scope":"https://api.paypal.com/v1/developer/.* https://api.paypal.com/v1/payments/.* https://api.paypal.com/v1/vault/credit-card https://api.paypal.com/v1/vault/credit-card/.*","access_token":"A015o4pwMqQ7ZfEYJtBC5Jr.cr8u2Kq3f459nSyyYLeyJlU","token_type":"Bearer","app_id":"APP-80W284485P519543T","expires_in":28800}"

Now, in the meantime, before we look into possibility to upgrade to proper curl version, we found a workaround and manually applied a patch inside SDK, we changed

    $responseHeaderSize = curl_getinfo($ch, CURLINFO_HEADER_SIZE);
to

    $responseHeaderSize = strlen($result) - curl_getinfo($ch, CURLINFO_SIZE_DOWNLOAD);

Looking into composer dependencies, there is no explicitly defined curl version required to use SDK.

On enterprise level, it's impossible to upgrade to newest curl as the version supported. We are using curl version **7.19.7** and can not upgrade any hire at this stage.

Therefore, can you guys make a compatible fix for curl version **<7.30.0** please?

Thanks,
B.

**Comment by jaypatel512** [comment]
Hey @platformoperations ! 

I will definitely add this bug fix, and review the code. as per your suggestion. I intend to do this immediately after the Payment API release, as it is blocking few people too. I should add this fix as soon as tomorrow. Sorry for the inconvenience.

**Comment by jaypatel512** [comment]
Hey @platformoperations ! 

I was trying to reproduce this issue on a VM with curl version 7.19.7, and was not able to see this bug. 
Can you please confirm if you are using any kind of proxy between the two. I will try to reproduce this issue, so that I could test it properly. 

 curl --version
```sh
curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.14.0.0 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
Protocols: tftp ftp telnet dict ldap ldaps http file https ftps scp sftp 
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz 
```

 php --version
```sh
PHP 5.4.37 (cli) (built: Jan 23 2015 09:13:35) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
```

**Comment by jaypatel512** [comment]
Hey @platformoperations ! 

I would really appreciate if you could help me reproduce this bug. I am trying to create the issue, and I am not able to do so. I am close to making a release with new Payment APIs, and I wish to include this fix too, however, I cannot do so unless I have a reproducible bug. Really Appreciated your help :) 

Thank you so much.

**Comment by platformoperations** [comment]
Hey @jaypatel512 

Please look at our setup below:

php --version

>PHP 5.5.21 (cli) (built: Jan 21 2015 15:35:14) 
>Copyright (c) 1997-2014 The PHP Group
>Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
>    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies
>    with Xdebug v2.2.7, Copyright (c) 2002-2015, by Derick Rethans


curl --version
>curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 >libssh2/1.4.2
>Protocols: tftp ftp telnet dict ldap ldaps http file https ftps scp sftp 
>Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz

Looking into origin curl patch (http://sourceforge.net/p/curl/bugs/1204/) it is required to set up a proxy to reproduce this bug.

Also, sharing example how to make curl backwards compatible in PHP: https://github.com/kriswallsmith/Buzz/issues/181

Hope it helps,
B.

**Comment by jaypatel512** [comment]
This really helps. I think the proxy setup is the one causing this bug. I will definitely reproduce it, and get back with the fix. Thank you so much for helping me debug.

**Comment by jaypatel512** [comment]
You are right. I am able to reproduce this issue now. I should be able to make a fix merged, and released soon.
