### ISSUE TITLE
404 on GET Payment for Payment that exists -- "PayPal-API" branch?

### ISSUE THREAD

**Issue by justiniso** [paypal/PayPal-PHP-SDK#259]
We are playing with the latest (unstable) version of the SDK (PayPal-API branch). Note this is our sandbox environment. So we reverted back to stable 1.2.1 and are getting the same error. The strange thing is that the payment ID we are using to retrieve the payment was provided directly from the API just seconds before. Looking at our historical logs, this is a new error for us:

    [27-02-2015 04:46:32] PayPal\Core\PayPalHttpConnection: INFO    : GET https://api.sandbox.paypal.com/v1/payments/payment/PAY-2FN61130H0076380LKTYIFOY
    [27-02-2015 04:46:32] PayPal\Core\PayPalHttpConnection: INFO    : Response Status     : 404
    [27-02-2015 04:46:32] PayPal\Core\PayPalHttpConnection: ERROR    : Got Http response code 404 when accessing https://api.sandbox.paypal.com/v1/payments/payment/PAY-2FN61130H0076380LKTYIFOY. {"name":"INVALID_RESOURCE_ID","message":"The requested resource ID was not found","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INVALID_RESOURCE_ID","debug_id":"0d66ca764eaa1"}

Specifically, we're making a call immediately after capture:

      /**
       * Loads the last information about a paypal payment and updates the order payment entity.
       * @param OrderPaymentEntity $orderPayment
       * @param \PayPal\Api\Payment $paypalPayment
       * @return bool
       */
      private function updatePaypalPaymentInformation(OrderPaymentEntity $orderPayment, \PayPal\Api\Payment $paypalPayment){
        $businessEntity = $orderPayment->getBusinessEntity();
        $apiContext = (isset($this->paypalApiContexts[$businessEntity])) ? $this->paypalApiContexts[$businessEntity] : FALSE;
        if(!$apiContext){
          return FALSE;
        }
        try {
          $paypalPayment = $paypalPayment->get($paypalPayment->getId(), $apiContext);
          // ^ the GET is the line that's failing

Is this related to the recent issues?

**Comment by jaypatel512** [comment]
So, basically, you first capture a payment, and do a get on the payment after that ? Am I correct ? 

Let me try it in my local machine and get back to you. I think the issue is not related to the major Payment API release, however, lets dig into this, and resolve it.

P.S. This is not the resolution to the bug, however, I noticed that you are using `get` method as an instance method. It is actually a static method. It would work both ways in PHP, however, In future, you might want to try something like this:

```php
 $paypalPayment = Payment::get($paypalPayment->getId(), $apiContext);
```

**Comment by justiniso** [comment]
> So, basically, you first capture a payment, and do a get on the payment after that ? Am I correct ?

Correct, and the capture is succeeding. 

It's actually only an issue on the unstable branch. 1.2.1 does not have this issue. I've edited the name of the issue to reflect that. 

re: your PS, thanks for the tip, we'll do some cleanup and address after the crisis. It's not my code, just trying to make it work!

p.s. get any sleep last night? ;)

**Comment by jaypatel512** [comment]
Hey @justiniso ! Would it make sense if we could do a quick hangout chat or something, where we could possibly look over the code. This would save me a heap of time, and allow us to easily fix this issue. Let me know and I could setup a quick hangout session.

**Comment by justiniso** [comment]
Sure, let me quickly figure out a way to make code accessible to you.

**Comment by justiniso** [comment]
This was an error on our end. We were looking for transaction ID's across sandbox environments due to a shared database.

**Comment by jaypatel512** [comment]
Thanks for the clarification. This should help other devs to not hesitate to use Payment-API branch for testing.
