### ISSUE TITLE
address update on execute payment does not work anymore

### ISSUE THREAD

**Issue by jbieneck** [paypal/PayPal-PHP-SDK#262]
I just updated to sdk 1.3.0 from 0.11.1.
With the old sdk I have a function like:
```
use PayPal\Api\ShippingAddress;
use PayPal\Api\Transaction;
use PayPal\Auth\OAuthTokenCredential;
use PayPal\Rest\ApiContext;
use PayPal\Api\Payment;
use PayPal\Api\PaymentExecution;

function PP_executePayment($clientId, $secret, $paymentId, $payerId) {

    $oauthCredential = new OAuthTokenCredential($clientId, $secret);
    $apiContext = new ApiContext($oauthCredential);

    $payment = Payment::get($paymentId, $apiContext);
    $transactions = $payment->getTransactions();

    $paymentExecution = new PaymentExecution();
    $paymentExecution->setPayerId($payerId);

    if (cfg("allowPatchPaymentThroughExecution") === "yes") {

        $shippingAddress = $_SESSION["shippingAddress"];

        $address = new ShippingAddress();
        $address
            ->setRecipientName($shippingAddress["recipient"])
            ->setLine1($shippingAddress["street"])
            ->setCity($shippingAddress["city"])
            ->setCountryCode($shippingAddress["country"])
            ->setPostalCode($shippingAddress["postal"])
            ->setState($shippingAddress["state"]);

        foreach ($transactions as $transaction) {
            /* @var $transaction Transaction */
            $itemList = $transaction->getItemList();
            $itemList->setShippingAddress($address);

            $amount = $transaction->getAmount();
            $amountDetails = $amount->getDetails();

            $shippingOptions = $_SESSION['shippingOptions'];

            if (isset($shippingOptions['expressShipping']) && $shippingOptions['expressShipping'] === "on") {
                $shippingCost = "5";
                $amountDetails->setShipping($shippingCost);
                $total = bcadd($amount->getDetails()->getSubtotal(), $shippingCost);
                $amount->setTotal($total);
            }
        }

        $paymentExecution->setTransactions($transactions);
    }

    return $payment->execute($paymentExecution, $apiContext)
```
where ```$transactions``` is an ```array``` with ```PayPal\Api\Transaction``` objects. *The important thing is I could update the buyer's shipping address through the execute call. This is an important* **legal** *requirement for Germany!!!*

With the new sdk I can still update the amount through the execute call but it seems to me I cannot update the shipping address anymore.

Is that statement correct? Why is that so? Is that a bug or a feature?

**Comment by jaypatel512** [comment]
Hey @jbieneck ! 

I understand your question. Let me look into that. just to confirm, you are trying to update the buyer's shipping address just before executing the payment. This is the line of code, that you are interested, from the above code.

```php
 $itemList->setShippingAddress($address);
```

Let me try to reproduce this on my local machine and get back to you. Overall, the SDK should not have eliminated any methods/features from older versions. The only thing we did during 1.0.0 release which were resolving namespaces, and removing deprecated getter setters. You can read more about it [here](https://github.com/paypal/PayPal-PHP-SDK/wiki/Breaking-Changes---1.0.0). 

I will get back to you as soon as possible.

**Comment by jbieneck** [comment]
No, I want to update the shipping address by/via/through the execute payment call, not short before. As far as I remember this is a use case that had been implemented in the payment API extra for one of our PPPlus merchants (can't remember if that was a single merchant or a partner shop)

**Comment by jaypatel512** [comment]
Sending you an internal Email. Closing this issue.
