### ISSUE TITLE
Add a constructor to Item class

### ISSUE THREAD

**Issue by rgeddes** [paypal/PayPal-PHP-SDK#263]
Instead of:

<pre>$item1 = new Item();
$item1->setName('Ground Coffee 40 oz')
    ->setDescription('Ground Coffee 40 oz')
    ->setCurrency('USD')
    ->setQuantity(1)
    ->setTax(0.3)
    ->setPrice(7.50);

item2 ...
</pre>
can you add a constructor to the Item class so I can do this:

<pre>$item1 = new Item( 'Ground Coffee 40 oz', 'USD', 1, 0.3, 7.50 );
</pre>

That way I can create and insert Item objects directly into the an array:

<pre>
$myItems = $_REQUEST[ 'array_of_arrays_with_item_data' ];
$itemArray = array();

foreach ( $myItems as $myItem ) {
    $itemArray[] =  new Item( $myItem[ 'name' ], $myItem[ 'description' ], ..., ... );
}
$itemList = new ItemList();
$itemList->setItems( $itemArray );
</pre>

**Comment by jaypatel512** [comment]
Hey @rgeddes !

The way you are presenting makes perfect sense for objects like `Item`. However, complicated objects that have multiple objects, and almost 15-20 attributes to set, it starts looking pretty bad, and hard to debug, as in your case, you are using the index of the array to determine the value corresponding to the field. If for some reason, a new field is added in the middle, this would break compatibility very easily.

However, good news is there is a better way than :
```php
$item1 = new Item();
$item1->setName('Ground Coffee 40 oz')
    ->setDescription('Ground Coffee 40 oz')
    ->setCurrency('USD')
    ->setQuantity(1)
    ->setTax(0.3)
    ->setPrice(7.50);

item2 ...
```

There are actually [2 more ways](https://github.com/paypal/PayPal-PHP-SDK/wiki/Passing-Data) you could pass data to constructor. Now, this may not serve your need exactly, but I think it could take you one step further. Let me know your thoughts on this.

I will still keep your suggestion in mind, and see if it would make sense in future. 

## JSON String

You could directly pass the JSON string as PayPalModel constructor parameter, and PayPal SDK will fill the information accordingly. You could use `get*` methods to retrieve specific information about the object immediately after that. Here is the example.

```php
$creditCard = new \PayPal\Api\CreditCard(
    '{
    "type": "visa",
    "number": "4417119669820331",
    "expire_month": "11",
    "expire_year": "2019",
    "cvv2": "012",
    "first_name": "Joe",
    "last_name": "Shopper"
    }'
);
// This will print the number
echo $creditCard->getNumber();

```

## Array Object
Similarly, array could be passed too as a constructor parameter to PayPalModel Object, as shown below:

```php
$creditCard = new \PayPal\Api\CreditCard(
    array(
        "type" => "visa",
        "number"=> "4417119669820331",
        "expire_month"=> "11",
        "expire_year"=> "2019",
        "cvv2"=> "012",
        "first_name"=> "Joe",
        "last_name"=> "Shopper"
    )
);
// This will print the number
echo $creditCard->getNumber();
```

This ability to accept multiple data formats allow developers to create instance of PayPalModels with minimal interference.

**Comment by rgeddes** [comment]
Thanks that makes sense.

I was an early adopter of the PHP REST API back in 12/2014 with version 0.3x and had to recently upgrade my code when some variable names were recently changed in the API.... I think it was from names like "payment_total" to camel case (paymentTotal).

Anyway, I understand there's a new account interface that makes more sense when using the REST API.  My client is still using the old account interface for viewing the their transactions, and that Paypal clients are being randomly allowed to try the new account interface.

Is there any way to get the Paypal clients, already using the REST API, to get the option to use the new account interface?
