### ISSUE TITLE
Retrieve 'Note to the merchant' field in Payments API

### ISSUE THREAD

**Issue by Jako** [paypal/PayPal-PHP-SDK#265]
Is that field available in REST API? It seems not to be retreived with `Payment::get($paymentId, $apiContext)` during a CreatePaymentUsingPayPal/ExecutePayment process.

It is available with NVP API in `PAYMENTREQUEST_n_NOTETEXT`

**Comment by jaypatel512** [comment]
From my initial knowledge, the `note` is not retrievable yet. I will however, get a confirmed answer from you on Monday.

**Comment by jziaja** [comment]
[Related issue](https://github.com/paypal/PayPal-NET-SDK/issues/63#issuecomment-69623871) from .NET SDK.

**Comment by jaypatel512** [comment]
Closing this issue as this being a new feature request for API operations. It has been reported to the internal team responsible for the development, and would be released based on priority.

Please reach out to [Merchant Technical Support](https://www.paypal-techsupport.com/app/ask), if this is a blocking issue for you, to help them prioritize better.
