### ISSUE TITLE
Problem Using PayPal-PHP-SDK

### ISSUE THREAD

**Issue by Obsdark** [paypal/PayPal-PHP-SDK#266]
I'm following a tutorial about how to use PayPal-PHP-SDK and i got stuck in somewhere with this error in the console:

[Sun Mar 08 16:11:21.729977 2015] [:error] [pid 4484:tid 1760] [client ::1:4308] PHP Fatal error:  
Uncaught exception 'PayPal\\Exception\\PayPalConnectionException' with message 
'Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payment.' 
in C:\\UniServerZ\\www\\PayPal\\vendor\\paypal\\rest-api-sdk-php\\lib\\PayPal\\Core\\PayPalHttpConnection.php:176\nStack trace:\n#0 
C:\\UniServerZ\\www\\PayPal\\vendor\\paypal\\rest-api-sdk-php\\lib\\PayPal\\Transport\\PayPalRestCall.php(74): 
PayPal\\Core\\PayPalHttpConnection->execute('{"intent":"sale...')\n#1 
C:\\UniServerZ\\www\\PayPal\\vendor\\paypal\\rest-api-sdk-php\\lib\\PayPal\\Common\\PayPalResourceModel.php(103): 
PayPal\\Transport\\PayPalRestCall->execute(Array, '/v1/payments/pa...', 'POST', '{"intent":"sale...', NULL)\n#2 
C:\\UniServerZ\\www\\PayPal\\vendor\\paypal\\rest-api-sdk-php\\lib\\PayPal\\Api\\Payment.php(424): 
PayPal\\Common\\PayPalResourceModel::executeCall('/v1/payments/pa...', 'POST', '{"intent":"sale...', NULL, Object(PayPal\\Rest\\ApiContext), NULL)\n#3 
C:\\UniServerZ\\www\\PayPal\\member\\payment.php(48): PayPal\\Api\\Payment->create(Object(PayPal\\Rest\\ApiContext))\n#4 {mai in 
C:\\UniServerZ\\www\\PayPal\\vendor\\paypal\\rest-api-sdk-php\\lib\\PayPal\\Core\\PayPalHttpConnection.php on line 176, referer: http://localhost:1313/PayPal/

This is the code:

<?php

use PayPal\Api\Payer;
use PayPal\Api\Details;
use PayPal\Api\Amount;
use PayPal\Api\Transaction;
use PayPal\Api\Payment;
use PayPal\Api\RedirectUrls;

require '../scr/start.php';

$payer = new Payer();
$details = new Details();
$amount = new Amount();
$transaction = new Transaction();
$payment = new Payment();
$redirectUrls = new RedirectUrls();

// Payer
$payer->setPaymentMethod('paypal');

// Details
$details->setShipping('2.00')
	->setTax('0.00')
	->setSubtotal('20.00'); //feed for membership
	
// Amount
$amount->setCurrency('CLP')
	->setTotal('22.00') // Shipping + Tax + Subtotal + Everything else you need to charge
	->setDetails($details);

// Transaction
$transaction->setAmount($amount)
	->setDescription('Membership');
	
$payment->setIntent('sale')
	->setPayer($payer)
	->setTransactions([$transaction]);

// Redirect URLs
$redirectUrls->setReturnUrl('http://localhost:1313/PayPal/PayPall/Pay.php?approved=true')
	->setCancelUrl('http://localhost:1313/PayPal/PayPall/Pay.php?approved=false');

$payment->setRedirectUrls($redirectUrls);

try {
	
	$payment->create($api);
	
	// Generate and store hash
	// Prepare and execute transaction storage
	
	
	
} catch (PPConnectionException $e) {
	// Perhaps log an error
	header('Location: ../PayPall/error.php');
	
}

var_dump($payment->getLinks());

?>

**Comment by Obsdark** [comment]
Any orientation, question for improve this same question, comment, advice or request of clarification/more info about it, etc[...] than help to reach the solution of the problem would be much apreciated.

Thanks a lot in advance

**Comment by jaypatel512** [comment]
Hey @Obsdark ! 

Can you please point me which tutorial are you trying to follow ? 

Btw, I was able to reproduce the issue you were facing. There is one things done wrong. 
*  `PPConnectionException` was  renamed to `PayPalConnectionException` on 1.0.0 release. You are catching an exception with `PPConnectionException` which is not getting caught, and so, is throwing uncaught exception.

Now, to read a proper exception, you could do something like this:
```php
<?php

require '../scr/start.php';

use PayPal\Api\Payer;
use PayPal\Api\Details;
use PayPal\Api\Amount;
use PayPal\Api\Transaction;
use PayPal\Api\Payment;
use PayPal\Api\RedirectUrls;


$payer = new Payer();
$details = new Details();
$amount = new Amount();
$transaction = new Transaction();
$payment = new Payment();
$redirectUrls = new RedirectUrls();

// Payer
$payer->setPaymentMethod('paypal');

// Details
$details->setShipping('2.00')
    ->setTax('0.00')
    ->setSubtotal('20.00'); //feed for membership

// Amount
$amount->setCurrency('CLP')
    ->setTotal('22.00') // Shipping + Tax + Subtotal + Everything else you need to charge
    ->setDetails($details);

// Transaction
$transaction->setAmount($amount)
    ->setDescription('Membership');

$payment->setIntent('sale')
    ->setPayer($payer)
    ->setTransactions([$transaction]);

// Redirect URLs
$redirectUrls->setReturnUrl('http://localhost:1313/PayPal/PayPall/Pay.php?approved=true')
    ->setCancelUrl('http://localhost:1313/PayPal/PayPall/Pay.php?approved=false');

$payment->setRedirectUrls($redirectUrls);

try {

    $payment->create($apiContext);

// Generate and store hash
// Prepare and execute transaction storage
} catch (\PayPal\Exception\PayPalConnectionException $e) {
    echo $e->getData();
    exit(1);
} catch(Exception $e) {
    echo $e->getMessage();
    exit(1);
}

var_dump($payment->getLinks());

```

As you can see, the only change I have made is to exception handling. I have added two exception catch. One for PayPalConnectionException, and other for generic Exception.

[`PayPalConnectionException`](http://paypal.github.io/PayPal-PHP-SDK/docs/class-PayPal.Exception.PayPalConnectionException.html) has a `getData` method that could be used to retrieve a more detailed exception message, that will tell you what is causing the 400 exception. This is especially helpful when developing in sandbox.

As you can see now, if you try to run this code, you will see this printed on the screen. 
```
{
    "name": "CURRENCY_NOT_ALLOWED",
    "message": "Currency is not supported",
    "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#CURRENCY_NOT_ALLOWED",
    "debug_id": "e8a64ccaef9fe"
}
```
In your case CLP seems to be not allowed.

Let me know if you were able to get past this issue.

**Comment by Obsdark** [comment]
Yes indeed, i just solve it it's true and was the currency, thanks for all
