### ISSUE TITLE
Expire paypal session if its inactive for certain period 

### ISSUE THREAD

**Issue by cchacholiades** [paypal/PayPal-PHP-SDK#267]
The situation is that the store should have products available in stock before any user tries to purchase them.

Each time the user goes for checkout I have two functions:

```
1. postPayment(){} // This is one is responsible for collecting all necessary data and sends them to paypal
2. getPaymentStatus() // This is one is to get a transaction response
```

Let's say that there is only one item in stock and that there are more than one users simultaneously trying to purchase that item.

To prevent this, I wrote a function that removes the quantity for the items that are in checkout from the stock. But I need to do that temporarily, for example to expire in 20 mins. If the transaction is not successful during the 20 mins and the result's state is not approved then the items should be added back in stock.

I've tried to use session cookies in the ```postPayment()```:
```
$_SESSION['timeout'] = time();

  if ($_SESSION['timeout'] + 20 * 60 < time()) {
     // session timed out
  } else {
     // session ok proceed with paypal 
  }
```
But this won't work as expected. What could be a solution to go with in such context? Is there a way to do this with the sdk?

**Comment by jziaja** [comment]
How are you defining the payment?  This use case is one that is recommended for [creating and processing an order](https://developer.paypal.com/docs/integration/direct/create-process-order/).

> This technique is often used by merchants who accept orders for varying items, some of which may not be available for shipment at the time the order is placed. For example, when a merchant ships items from multiple distribution centers and needs separate authorizations for each shipment. Another example would be delayed shipping on items that are not in stock.

**Comment by cchacholiades** [comment]
I have a similar structure to [this tutorial](http://jslim.net/blog/2014/09/19/integrate-paypal-sdk-into-laravel-4/)

**Comment by jziaja** [comment]
Yeah, that's using a `sale` payment setup, which works great for simple, one-time payment setups.  However, for a system where the payments are linked to inventory, an order/authorization/capture setup makes much more sense.

@jaypatel512 has put together some great examples [here](http://paypal.github.io/PayPal-PHP-SDK/sample/#order) that show the steps involved for PHP.

**Comment by cchacholiades** [comment]
Great @jziaja , thanks for the guidance.

**Comment by cchacholiades** [comment]
I've tried the order payment setup. 

But it would be much easier and practical if there was a way to specify a paypal timeout and send the user back to the site where he came from. Is there maybe another solution to get this problem sorted?

**Comment by jaypatel512** [comment]
Hey @cchacholiades ! The SDK does not provide such support you are seeking. You could definitely implement your own logic. Something that you could get more help from us, as well as our general PHP community to develop such use case, by creating a question in StackOverflow.

However, using order payment setup would be your best bet, that comes pre-packaged in our SDK.
