### ISSUE TITLE
Subscriptions 

### ISSUE THREAD

**Issue by robertmylne** [paypal/PayPal-PHP-SDK#270]
I have this working using a one off payment. Though there are no examples for subscriptions of a fixed amount for a term indefinite. Where can I find docs on this? I don't think a billing agreement is what I want.

**Comment by jaypatel512** [comment]
Hey @robertmylne 

You could find a lot of documentation around Billing Plans and Agreements here at : 

- [Billing Plans and Agreement](https://developer.paypal.com/webapps/developer/docs/integration/direct/create-billing-plan/)
- [REST API Specifications](https://developer.paypal.com/webapps/developer/docs/api/#billing-plans-and-agreements)
- [SDK Sample Codes](http://paypal.github.io/PayPal-PHP-SDK/sample/#billing)

You should be able to find all the possible combinations that you could use to cover your scenario.
