### ISSUE TITLE
getAgreementDetails() returning the wrong object

### ISSUE THREAD

**Issue by sdrichins** [paypal/PayPal-PHP-SDK#271]
When calling getAgreementDetails() it is returning NULL even though they are set within the agreement object. In looking at the Agreement.php

    public function getAgreementDetails()
        {
            return $this->{"agreement-details"};
        }

The object being returned is `[agreement_details] => PayPal\Api\AgreementDetails Object`

When I modify Agreement.php to be `return $this->{"agreement_details"};` it works as expected

**Comment by jaypatel512** [comment]
This is definitely a bug. Let me test it a bit, and get the change out as soon as possible. 

Thanks for bringing this to notice.

**Comment by jaypatel512** [comment]
Thanks @sdrichins for pointing this out. I will make a patch release soon

**Comment by sdrichins** [comment]
Thanks for the quick turn around
