### ISSUE TITLE
Should we hide the cache file?

### ISSUE THREAD

**Issue by ecabuk** [paypal/PayPal-PHP-SDK#273]
I am developing a wordpress plugin that uses paypal sdk. 

- Cache file has sensitive data? Should I try hide the cache file?
- Or is it better to don't use cache for my situation?

Thanks!

**Comment by jaypatel512** [comment]
Cache File has `clientId` and `encrypted access token` information. The encryption is done using `clientSecret` as the key, however `clientSecret` is not stored in the cache file. This is how a sample cache file would contain:

```json
{
    "AYSq3RDGsmBLJE-otTkBtM-jBRd1TCQwFf9RGfwddNXWz0uFU9ztymylOhRS": {
        "clientId": "AYSq3RDGsmBLJE-otTkBtM-jBRd1TCQwFf9RGfwddNXWz0uFU9ztymylOhRS",
        "accessTokenEncrypted": "NTUxMDQ1YTE2YWVhNzkuNEUxcmNlS1hWa3h6dFpLK1UzVkdZY1Y1Q084c21icFEvU3NzK1N0VWhFZFcrQUROUWNoeFZHVHprQUtOR05NODI=",
        "tokenCreateTime": 1427129761,
        "tokenExpiresIn": 28800
    }
}
```

Generally, providing a cache path that is outside of web access is desirable. Someone should not just open the URL on a browser and be able to read it. However, merely having the cache file information in hand would not expose any security risk, however, that doesn't mean you should neglect the security standard.

The final decision of, if you wish to use caching is your call, however, I would love to give you any more details you may need to make an informed decision.

**Comment by ecabuk** [comment]
Thanks for the help.
