### ISSUE TITLE
Going live sdk_config.ini with mode=sandbox?

### ISSUE THREAD

**Issue by y2josei** [paypal/PayPal-PHP-SDK#274]
As I can see in the following doc page I understand that using sdk_config.ini I need to add the mode=sandbox when going live. Is this correct? Is it not the mode=live instead?

https://github.com/paypal/PayPal-PHP-SDK/wiki/Going-Live

**Comment by jziaja** [comment]
Thanks for pointing that out @y2josei!  I've updated the page so it says `mode=live` and provides a sample of how the config section looks.

https://github.com/paypal/PayPal-PHP-SDK/wiki/Going-Live#2-set-your-configurations

**Comment by y2josei** [comment]
I wasn't sure to submit pull request, gald to help.
Thanks @jziaja
