### ISSUE TITLE
what do paypal agreement transaction states mean?

### ISSUE THREAD

**Issue by HLong** [paypal/PayPal-PHP-SDK#275]
I am using paypal rest api recurring payment. About Agreement Transaction, it has many state eg: Completed, Expired, Pending .. I want to ask what they meant and when they appeared. Thank all.

**Comment by RedLikeTheColor** [comment]
https://developer.paypal.com/webapps/developer/docs/api/#agreement-object
"Possible values are Active, Pending, Expired, Suspend, Reactivate, and Cancel."

My understanding of these states, in terms of the SDK:
Pending: initial state after Agreement->create()
Active: state after Agreement->execute($token) following user approval.
Expired: state after the the Payment Agreement has run the number of cycles defined in the Payment Plan's payment definition [ PaymentDefinition->setCycles()->setFrequency()->setFrequencyInterval(), Plan->addPaymentDefinition(), Agreement->setPlan() ], if not indefinite.
Suspend: state after Agreement->suspend(), or if the agreement is suspended from the merchant's web interface.
Reactivate: state after Agreement->reActivate() or manual reactivation from the merchant's web interface, if previously suspended.
Cancel: state after Agreement->cancel(), or after manual cancellation from the customer or merchant's web interface.

If you mean the AgreementTransaction object and not the general Agreement:
https://developer.paypal.com/webapps/developer/docs/api/#agreementtransactions-object
"State of the subscription at this time."
That is, one of the states listed above, whichever was the state of the Agreement at the time of the transaction.

**Comment by HLong** [comment]
Thank @RedLikeTheColor ,
How is about "Completed" state? In my transactions, there are this state when it comes to due date.

**Comment by RedLikeTheColor** [comment]
The API and SDK documentation do leave much to be desired sometimes. The "Completed" status doesn't appear to be documented for this object, but looking at https://developer.paypal.com/webapps/developer/docs/api/#search-for-transactions, in the response example, it appears to be a status that will only show on Agreement Transactions which are the payments themselves. It would indicate that that transaction is a payment under the agreement which has successfully completed.

I suspect there are other states which can also apply to payment agreement transactions. My own project with the SDK is recently launched so I don't have a lot of hands on experience with these values. Looking at some of the other objects on the REST API documentation, I see the "completed" state applies to a Sale object as well (https://developer.paypal.com/webapps/developer/docs/api/#sale-object), so I imagine you might also see pending, refunded, and partially_refunded as appropriate.

**Comment by jaypatel512** [comment]
Thanks @RedLikeTheColor for your help answering the question. @HLong ! he is right. The transactions inside an agreement are under the covers the same transactions that you see in the payments. Each transaction is an individual payment taken from the buyer, who subscribed to the agreement.

I will ask the developer docs team to update the docs to include possible state values.

**Comment by jaypatel512** [comment]
These are the possible values for it.

```json
"status":{
         "type":"string",
         "readonly":true,
         "enums":[
            "Created",
            "Suspended",
            "Reactivated",
            "Canceled",
            "Completed"
         ],
         "description":"State of the subscription at this time."
      },
```

Almost all of those are as the name suggest, and @RedLikeTheColor explained. We have created a ticket to update the docs, and should be up for future devs. 

Thanks for pointing it out.

**Comment by HLong** [comment]
What is transaction's state if my paypal account has not enough money to pay? And what 's continue if I fill up money?

**Comment by jaypatel512** [comment]
Hey @HLong ! Let me confirm those two, because even I am not aware of that answer at top of my head.
