### ISSUE TITLE
cURL Error

### ISSUE THREAD

**Issue by engrsandeep** [paypal/PayPal-PHP-SDK#276]
Recently started to receive following error. it was working fine before last couple of days
cURL error: [60] SSL certificate problem: unable to get local issuer certificate.

Can you please help?

**Comment by jaypatel512** [comment]
Hey @engrsandeep ! 

Can you please let me know what version you are using ? And how did you download the SDK ? Via Composer or direct download.

**Comment by jaypatel512** [comment]
Also, can you please confirm if you have cacert.pem file located in the given location: https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Core/cacert.pem

**Comment by engrsandeep** [comment]
Hi, 

i have direct downloaded. I think issue was with IPN Notification not with Rest sdk. I  have updated cacert.pem. I will check if error come again.

Thank you.

**Comment by jaypatel512** [comment]
That sounds about right. The Cert should not generally fail as it was not something we have changed in a while. I wlil close the issue. Feel free to open in issue found in PHP SDK.
