### ISSUE TITLE
Billing plan and agreement for variable monthly payments

### ISSUE THREAD

**Issue by RedLikeTheColor** [paypal/PayPal-PHP-SDK#277]
And if so, how? Also, how can I salvage our current implementation? The SDK and REST API documentation has been sparse and occasionally misleading.

Our use case is a subscription service where users pay monthly for content updates that happened during the month to content types they've selected. One user might pledge $1 per main content update (up to 9 per month), and another might pledge $3 per main content and secondary content (up to 9 + 5 per month).

Our current implementation is to create a billing plan and billing agreement for each subscriber, setting the monthly value in the payment details to their pledge value times the total potential updates in a month. The plan was to then, at the end of the month, lower their monthly total according to the number of updates that actually occurred, before billing them the appropriate amount.

However, I've just realized in testing this process that Agreement->setBalance() is intended to affect delinquent / unpaid balances (and then only to lower / forgive that balance), and Agreement->billBalance() is for billing that same unpaid amount. Unfortunately, our implementation is already live with a number of subscribers set to be billed on April 1, at which point there will only be 4 updates worth of content since our March 22 launch.

I've notice the merchant web interface has the ability to modify a subscriber's monthly total, but I've been unable to find a way to do so through the API, and I've gotten into some rather esoteric PatchRequest attempts at this point, all of which seem to consider any non "/" path invalid, and any partial JSON object a mismatch.

Incidentally, I was only able to figure out my misunderstanding when my googling turned up the Classic API documentation here: https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECRecurringPayments . The REST API documentation is severely lacking in this level of terminology explanation.

**Comment by jaypatel512** [comment]
Hey @RedLikeTheColor ! From your use case standpoint, I think it is very unlikely that the REST API supports variable monthly payments. Ideally, the way agreement works is the user will be agreeing to pay n dollars to a seller for a particular frequency, till the end date. Any changes to agreement once it is accepted by user, is not allowed.

However, there could be a way we could do a partial refund on executed agreement, and remove the difference. However, I have asked the subscription API team to reply back to us with their suggestions.

**Comment by RedLikeTheColor** [comment]
Thanks @jaypatel512 . I'll try to test some refund transactions and see if I can make that work. I really need to figure something out today or we're manually editing over 200 payment profiles and then I'm having to learn Classic API.

You might be interested that I've cross-posted this question to Stack Exchange: http://stackoverflow.com/questions/29349096/can-i-set-variable-monthly-payment-amounts-through-paypal-rest-apis-billing-pla

**Comment by RedLikeTheColor** [comment]
@jaypatel512 : It looks like the Classic API operation I'd want is [Reference Transactions][1]. This is a part of Express Checkout and integrates with Billing Agreements much like we're already using. I also see that the [Transaction][2] class recently added a `setPurchaseUnitReferenceId()` method, which sounds like it's intended for transaction references. I tried shoehorning a transaction through there with a billing agreement ID set through that method with no luck. Is there any way to use this as is, or with some sort of account approval?

Failing that, do you have any short term advice on how to handle our billing tomorrow? Right now our only fall back seems to be manually editing over 200 subscriber profiles to set their amount to the pledges they've accrued this month, which will generate an email alerting them to the change before they receive another email that their payment has processed.

[1]:https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECReferenceTxns/
[2]http://paypal.github.io/PayPal-PHP-SDK/docs/class-PayPal.Api.Transaction.html

**Comment by RedLikeTheColor** [comment]
To keep @jaypatel512 and any interested parties aware of our specific issue, we've finally determined that we're completely out of luck with the Rest API and we're moving to implement Classic API and reference transactions using the [Merchant-SDK-PHP][1]. It looks like that's still your department Jay, so I'll probably run into you there!

[1]:https://github.com/paypal/merchant-sdk-php

**Comment by jaypatel512** [comment]
Closing the issue accordingly. I will update the SDK as well as this issue when we have this support.
