### ISSUE TITLE
Ability to Cache Token to MongoDB or MySql

### ISSUE THREAD

**Issue by matiasperrone** [paypal/PayPal-PHP-SDK#278]
Hi,

I would like to save to a database (could be MongoDB, MySQL or Redis is not important right now) the token received and update the OAuthTokenCredential class with the cached one or retrive a new one if is necessary.

How can this be done?

**Comment by jaypatel512** [comment]
I think this is an excellent idea. I would love to add such a feature. That actually also allows you to secure the data better, than just a file. I will look into this, and try to come up an easy way to allow to do so. 

I think we could provide an adapter that anyone could implement, and access that information. Btw, if you feel excited to implement something for us, feel free to give it a try and send us a pull request. 

Thanks for your suggestion @matiasperrone !

**Comment by jaypatel512** [comment]
We will not be implementing this issue, as we have not gained enough traction. If the request is made in future, with more people looking for it, we will re-consider. In the mean time, we would love to accept a pull request that could make this happen.
