### ISSUE TITLE
UrlValidator does not allow "-" in URL

### ISSUE THREAD

**Issue by jungidee** [paypal/PayPal-PHP-SDK#279]
When using the SDK from a website with a "-" in the URL e.g. my-website.com an error occurs in 
\library\paypal\integration\vendor\paypal\rest-api-sdk-php\lib\PayPal\Api\RedirectUrls.php
when calling
UrlValidator::validate($cancel_url, "CancelUrl"); or 
UrlValidator::validate($return_url, "ReturnUrl");

**Comment by jaypatel512** [comment]
Hey @jungidee ! I wrote a quick test to verify if the UrlValidator accepts `-` in urls. I am not able to reproduce this issue. Can you please make sure you are passing a fully qualified URL ? 

For e.g. : `https://www.my-website.com` as the value. Don't forget the `https://` in the front.

**Comment by jaypatel512** [comment]
Just added few more tests to verify if the method works properly, in the latest commit https://github.com/paypal/PayPal-PHP-SDK/commit/c181af361d9daa48d7b8c717cf48cf3550da2a2a

**Comment by jungidee** [comment]
Hi,

Here is an example from an URL when I get an error.
http://pre-mium.staging.qrd.by

Trace below,
Peter

[cid:image002.jpg@01D06D5D.B58BAB80]

Fatal error: Uncaught exception 'InvalidArgumentException' with message 'ReturnUrl is not a fully qualified URL' in /var/staging.qrd.by/public/library/paypal/integration/vendor/paypal/rest-api-sdk-php/lib/PayPal/Validation/UrlValidator.php:23 Stack trace: #0 /var/staging.qrd.by/public/library/paypal/integration/vendor/paypal/rest-api-sdk-php/lib/PayPal/Api/RedirectUrls.php(29): PayPal\Validation\UrlValidator::validate('http://pre-mium...', 'ReturnUrl') #1 /var/qr1.whitelabel.staging/white/public/premium/paypal/index.php(104): PayPal\Api\RedirectUrls->setReturnUrl('http://pre-mium...') #2 {main} thrown in /var/staging.qrd.by/public/library/paypal/integration/vendor/paypal/rest-api-sdk-php/lib/PayPal/Validation/UrlValidator.php on line 23

Von: Jay [mailto:notifications@github.com]
Gesendet: Donnerstag, 2. April 2015 15:46
An: paypal/PayPal-PHP-SDK
Cc: jungidee
Betreff: Re: [PayPal-PHP-SDK] UrlValidator does not allow "-" in URL (#279)


Hey @jungidee<https://github.com/jungidee> ! I wrote a quick test to verify if the UrlValidator accepts - in urls. I am not able to reproduce this issue. Can you please make sure you are passing a fully qualified URL ?

For e.g. : https://www.my-website.com as the value. Don't forget the https:// in the front.

**Comment by jungidee** [comment]
I guess ist a PHP issue, since the URL Validator uses
http://php.net/manual/en/function.filter-var.php
to validate the url….

Von: Peter Hlavac
Gesendet: Donnerstag, 2. April 2015 15:57
An: 'paypal/PayPal-PHP-SDK'
Betreff: AW: [PayPal-PHP-SDK] UrlValidator does not allow "-" in URL (#279)

Hi,

Here is an example from an URL when I get an error.
http://pre-mium.staging.qrd.by

Trace below,
Peter

[cid:image001.jpg@01D06D5E.1EA752E0]

Fatal error: Uncaught exception 'InvalidArgumentException' with message 'ReturnUrl is not a fully qualified URL' in /var/staging.qrd.by/public/library/paypal/integration/vendor/paypal/rest-api-sdk-php/lib/PayPal/Validation/UrlValidator.php:23 Stack trace: #0 /var/staging.qrd.by/public/library/paypal/integration/vendor/paypal/rest-api-sdk-php/lib/PayPal/Api/RedirectUrls.php(29): PayPal\Validation\UrlValidator::validate('http://pre-mium...', 'ReturnUrl') #1 /var/qr1.whitelabel.staging/white/public/premium/paypal/index.php(104): PayPal\Api\RedirectUrls->setReturnUrl('http://pre-mium...') #2 {main} thrown in /var/staging.qrd.by/public/library/paypal/integration/vendor/paypal/rest-api-sdk-php/lib/PayPal/Validation/UrlValidator.php on line 23

Von: Jay [mailto:notifications@github.com]
Gesendet: Donnerstag, 2. April 2015 15:46
An: paypal/PayPal-PHP-SDK
Cc: jungidee
Betreff: Re: [PayPal-PHP-SDK] UrlValidator does not allow "-" in URL (#279)


Hey @jungidee<https://github.com/jungidee> ! I wrote a quick test to verify if the UrlValidator accepts - in urls. I am not able to reproduce this issue. Can you please make sure you are passing a fully qualified URL ?

For e.g. : https://www.my-website.com as the value. Don't forget the https:// in the front.

**Comment by jaypatel512** [comment]
Can you create a file called `test.php` at the same location where your vendor directory is, and add this to the file

```php
<?php

include 'vendor/autoload.php';
try {
    \PayPal\Validation\UrlValidator::validate('http://pre-mium.staging.qrd.by');
    echo "Validated\n";
} catch (InvalidArgumentException $ex) {
    echo $ex->getMessage() . "\n";
}
```

And just run the file, using `php -f test.php` and confirm if it goes through fine ? 
In my guess, you might be adding some space or special character by accident.

**Comment by jungidee** [comment]
Hello Jay,

http://pre-mium.staging.qrd.by/test.php

<?php


include __DIR__.'/library/paypal/integration/vendor/autoload.php';

$url = "http://pre-mium.staging.qrd.by";
try {
    \PayPal\Validation\UrlValidator::validate($url);
    echo "Validated\n";
} catch (InvalidArgumentException $ex) {
    echo "<code>$url</code>".$ex->getMessage() . "\n";
}

==>http://pre-mium.staging.qrd.by is not a fully qualified URL

Strange…

Von: Jay [mailto:notifications@github.com]
Gesendet: Donnerstag, 2. April 2015 17:07
An: paypal/PayPal-PHP-SDK
Cc: jungidee
Betreff: Re: [PayPal-PHP-SDK] UrlValidator does not allow "-" in URL (#279)


Can you create a file called test.php at the same location where your vendor directory is, and add this to the file

<?php



include 'vendor/autoload.php';

try {

    \PayPal\Validation\UrlValidator::validate('http://pre-mium.staging.qrd.by');

    echo "Validated\n";

} catch (InvalidArgumentException $ex) {

    echo $ex->getMessage() . "\n";

}

And just run the file, using php -f test.php and confirm if it goes through fine ?
In my guess, you might be adding some space or special character by accident.

**Comment by jaypatel512** [comment]
Wow ! Thats weird. 

Here is my snapshot: 
![screen shot 2015-04-02 at 10 18 18 am](https://cloud.githubusercontent.com/assets/1309895/6966898/a9071c0c-d921-11e4-9009-f78327d35552.png)

Can you confirm the php version ? Mine is PHP 5.3.

**Comment by jungidee** [comment]
PHP 5.3.2-1ubuntu4.27 with Suhosin-Patch (cli) (built: Sep  4 2014 06:54:47)
Copyright (c) 1997-2009 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies

I guess I need to upgrade

Von: Jay [mailto:notifications@github.com]
Gesendet: Donnerstag, 2. April 2015 17:19
An: paypal/PayPal-PHP-SDK
Cc: jungidee
Betreff: Re: [PayPal-PHP-SDK] UrlValidator does not allow "-" in URL (#279)


Wow ! Thats weird.

Here is my snapshot:
[screen shot 2015-04-02 at 10 18 18 am]<https://cloud.githubusercontent.com/assets/1309895/6966898/a9071c0c-d921-11e4-9009-f78327d35552.png>

Can you confirm the php version ? Mine is PHP 5.3.

**Comment by jaypatel512** [comment]
That explains that: https://bugs.php.net/bug.php?id=51632

Awesome. Now we know the root cause. Please re-open the issue if you still see the issue after upgrading. Happy Coding !

**Comment by jungidee** [comment]
Thx, I will
