### ISSUE TITLE
Problem Using the app "invalid or no certificate authority found - Retrying using bundled CA certs file" 

### ISSUE THREAD

**Issue by Obsdark** [paypal/PayPal-PHP-SDK#281]
```
[04-04-2015 10:46:45] PayPal\Core\PayPalHttpConnection: INFO	: POST https://api.sandbox.paypal.com/v1/oauth2/token
[04-04-2015 10:46:48] PayPal\Core\PayPalHttpConnection: INFO	: Invalid or no certificate authority found - Retrying using bundled CA certs file
[04-04-2015 10:46:49] PayPal\Core\PayPalHttpConnection: INFO	: Response Status 	: 200
[04-04-2015 10:46:49] PayPal\Core\PayPalHttpConnection: INFO	: POST https://api.sandbox.paypal.com/v1/payments/payment
[04-04-2015 10:46:49] PayPal\Core\PayPalHttpConnection: INFO	: Invalid or no certificate authority found - Retrying using bundled CA certs file
[04-04-2015 10:46:50] PayPal\Core\PayPalHttpConnection: INFO	: Response Status 	: 201`
```
No Apache, nor Mysql return me any error message, but the logPayPal.txt (the log i assign for paypal) show me this.

I was trying to following a tutorial to make a simple app for a page who add Paypal-SDK to receive payments in the pages, i still can't finish it because of this problem.

The problem is; that is not inserting the data on the database, for be more specificly, is in this video, 

https://www.youtube.com/watch?v=NTL3w_qROkU

The part where it shows than insert the data on a transaction register, is not working.

The tutorial i was following is:
https://www.youtube.com/playlist?list=PLfdtiltiRHWE_c8jjW5OeweL1c_8uqcnW

Feel free to suggest improvements to the questions, ask for more information or anything

Thanks in advance for everything
I'm suscribing to this one

-Obsdark-

PS: The code: start.php & payment.php

```<?php

use PayPal\Rest\ApiContext;
use PayPal\Auth\OAuthTokenCredential;

session_start();

$_SESSION['User_id'] = 1;

require __DIR__ . '/../vendor/autoload.php';

// API
$api = new ApiContext(
	new OAuthTokenCredential(
		'Abxr4WOfNsBDlEvCmDdpNnUNdTuRx2PcAALwF1IBh978K42B2q5z8VZJaURCpJtNXO0H3XefO1q-zoSt', // Client Id
		'EM81APj_87_BVyLsltZLqW5ZOhsE9H57mTG13sbrlmGhXPu2DLtuYOGHhDMzZir1rsLY2RgUhiwsyTz_' // Secret
		)
	);

$api->setConfig(['mode' => 'sandbox',
				 'http.ConnectionTimeOut' => 30,
				 'log.LogEnabled' => true,
				 'log.FileName' => 'logPaypal.txt',
				 'log.LogLevel' => 'FINE',
				 'validation.level' => 'log'
				]);
	
$db = new PDO('mysql:host=localhost;dbname=paypal', 'root', 'SomePass');

$user = $db->prepare("
	SELECT * FROM user
	WHERE id = :User_id
");

$user->execute(['User_id' => $_SESSION['User_id']]);

$user = $user->fetchObject();
?>



<?php

use PayPal\Api\Payer;
use PayPal\Api\Details;
use PayPal\Api\Amount;
use PayPal\Api\Transaction;
use PayPal\Api\Payment;
use PayPal\Api\RedirectUrls;

require '../scr/start.php';

$payer = new Payer();
$details = new Details();
$amount = new Amount();
$transaction = new Transaction();
$payment = new Payment();
$redirectUrls = new RedirectUrls();

// Payer
$payer->setPaymentMethod('paypal');

// Details
$details->setShipping('1.00')
	->setTax('0.00')
	->setSubtotal('1.00'); //feed for membership
	
// Amount
$amount->setCurrency('USD')
	->setTotal('2.00') // Shipping + Tax + Subtotal + Everything else you need to charge
	->setDetails($details);

// Transaction
$transaction->setAmount($amount)
	->setDescription('Membership');
	
$payment->setIntent('sale')
	->setPayer($payer)
	->setTransactions([$transaction]);

// Redirect URLs
$redirectUrls->setReturnUrl('http://localhost:1313/PayPal/PayPall/Pay.php?approved=true')
	->setCancelUrl('http://localhost:1313/PayPal/PayPall/Pay.php?approved=false');

$payment->setRedirectUrls($redirectUrls);

try {
	
	$payment->create($api);
	
	// Generate and store hash
	$hash = md5($payment->getId());
	$_SESSION['paypal_hash'] = $hash;
	
	// Prepare and execute transaction storage
	$store= $db->prepare("
		INSERT INTO transanctions_paypal (User_id, Payment_id, hash, Complete)
		VALUES (:user_id, :payment_id, :hash, 0)
	");
	
	$store->execute([
		'user_id' => $_SESSION['User_id'],
		'payment_id' => $payment->getId(),
		'hash' => $hash
	]);
	

} catch (PayPalConnectionException $e) {
        echo $e->getData();
        // Perhaps log an error
        header('Location: ../PayPall/error.php');

    }



    foreach($payment->getLinks() as $link) {
    	if($link->getRel() == 'approval_url') {
		    $redirectUrl = $link->getHref();
	    }
    }



    header('Location: '. $redirectUrl);

    ?>```

**Comment by jaypatel512** [comment]
First,

As you can see, the Invalid Certificate issue is not exactly an error. What our SDK tries is, to make a REST call without using a certificate attached to the request, and adds only if it fails to authenticate himself, and tries again. As you can see, the response was received with 200 or 201, means that the request was accepted gracefully. So, don't worry if you see that message. You would see that it is in INFO level log, and not as ERROR or WARN.

And for the reason why they are not inserted in the database, you could use something like this to verify if data is received.

```php
try {

    $payment->create($api);
    
    // Print some stuffs for debugging
    echo "Payment Id is " . $payment->getId();

    ...


}
```

Try adding such similar echo statement or log message, and check if the PaymentId is received or not. If it is not received, than we have an issue in SDK. But if it prints fine, I think we need to dig further into your database and mysql setup.

**Comment by jaypatel512** [comment]
No no ! It is throwing 400 exception because you are not passing all the data that paypal needs. PayPal wont create a payment if you don't provide the return URL. 

Put back those redirect URLs, and just add an exit command after echo statement as shown below:

```php
try {

    $payment->create($api);
    
    // Print some stuffs for debugging
    echo "Payment Id is " . $payment->getId();
    exit;
    ...


}
```

**Comment by Obsdark** [comment]
Is returning the Payment id

Payment Id is PAY-...(and a mix between numbers and letters here)

**Comment by jaypatel512** [comment]
That means, that you were successfully able to create a payment using PayPal SDK. I would recommend digging further into your call to database. That seems to be the culprit.

**Comment by jaypatel512** [comment]
Btw, if I am not wrong, In your insert query, you have key User_id, and Payment_id, and Complete with first character in upper case. make it lower case as suggested in the video.
```
INSERT INTO transanctions_paypal (user_id, payment_id, hash, complete)
        VALUES (:user_id, :payment_id, :hash, 0)

```

**Comment by Obsdark** [comment]
i try it, even remake the entire db from scratch and still doesn't work

the intresting thing is it is actualy connected, because its making the $user object with all the data from the database, i fix the capital letter stuff too, in both, start.php and payment.php, but still doesn't work

 i undestand what you say about the connection to the database, but then, where's the problem, is exactly like it is in the videos, and by my knowledgment of PDO Mysql is nothing wrong in my sintax, the insert must work right?

**Comment by jaypatel512** [comment]
Interesting. 

Can I ask you one more favor. Can you just execute your query with some random fixed data ? E.g.

```php
$store->execute([
        'user_id' => '123123123',
        'payment_id' => '111111111',
        'hash' => '321321'
    ]);
```

Also, you may want to catch a Exception around it.

Something like this:

```php
try {

    $payment->create($api);

    // Generate and store hash
    $hash = md5($payment->getId());
    $_SESSION['paypal_hash'] = $hash;

    // Prepare and execute transaction storage
    $store= $db->prepare("
        INSERT INTO transanctions_paypal (User_id, Payment_id, hash, Complete)
        VALUES (:user_id, :payment_id, :hash, 0)
    ");

    $store->execute([
        'user_id' => $_SESSION['User_id'],
        'payment_id' => $payment->getId(),
        'hash' => $hash
    ]);


} catch (PayPalConnectionException $e) {
        echo $e->getData();
        // Perhaps log an error
        header('Location: ../PayPall/error.php');

} catch (Exception $e) {
        echo $e->getMessage();
        exit(1);

}
```

**Comment by Obsdark** [comment]
Done

Not the apache log, not the mysql log and not the paypal log return any kind of new information

is just not registering the data in the db

Any other idea?

**Comment by jaypatel512** [comment]
I would try adding some echo statements after `$store->execute()` method, to make sure it actually moves further after execute. 

Something like this:

```php
try {

    $payment->create($api);

    // Generate and store hash
    $hash = md5($payment->getId());
    $_SESSION['paypal_hash'] = $hash;

    // Prepare and execute transaction storage
    $store= $db->prepare("
        INSERT INTO transanctions_paypal (User_id, Payment_id, hash, Complete)
        VALUES (:user_id, :payment_id, :hash, 0)
    ");

    $store->execute([
        'user_id' => $_SESSION['User_id'],
        'payment_id' => $payment->getId(),
        'hash' => $hash
    ]);
    
    echo "Payment Create Completed Successfully";


} catch (PayPalConnectionException $e) {
        echo $e->getData();
        // Perhaps log an error
        header('Location: ../PayPall/error.php');

} catch (Exception $e) {
        echo $e->getMessage();
        exit(1);

}
```

**Comment by Obsdark** [comment]
...Done

When i avoid the redirection, the web browser (in payment.php) is returning me the echo:
"Payment Create Completed Successfully"

i just add the echo just like you suggest, must say.

**Comment by jaypatel512** [comment]
That is so weird. One good thing is its not SDK then. But, btw, are you available for a quick hangout session, and we could look over the code you have (if you don't mind). Send me an email at jaypatel512@gmail.com

Also, you could possibly ask the author of the video series too. He is a very helpful developer too.

**Comment by Obsdark** [comment]
Ok, how about weekend?, tell me an hour and your timezone and we coordinate, I'll send you an email Thanks a lot for everything

**Comment by KinanSharif** [comment]
I'm facing the similar problem, have you found the solution ?
