### ISSUE TITLE
Trying to use "agreement_details" on creation of billing agreement

### ISSUE THREAD

**Issue by sml-kejo** [paypal/PayPal-PHP-SDK#283]
Request: 
```json
{
  "name": "Upgrade from Personal to Recurring Premium",
  "description": "test",
  "start_date": "2015-07-29T19:58:05+00:00",
  "override_merchant_preferences": {
    "cancel_url": "https://test.com",
    "return_url": "https://test.com",
    "auto_bill_amount": "NO",
    "max_fail_attempts": 3,
    "setup_fee": {
      "value": "3.15",
      "currency": "USD"
    },
    "initial_fail_amount_action": "CANCEL"
  },
  "agreement_details": {
    "outstanding_balance": {
      "value": "123.00",
      "currency": "USD"
    },
    "cycles_remaining": "0",
    "cycles_completed": "0",
    "next_billing_date": "2015-07-29T19:58:05+00:00",
    "last_payment_date": "2015-04-08T12:33:08+00:00",
    "last_payment_amount": {
      "value": "123.00",
      "currency": "USD"
    },
    "final_payment_date": "0",
    "failed_payment_count": "0"
  },
  "plan": {
    "id": "P-53M12771RU934515TS7RI5HA"
  },
  "payer": {
    "payment_method": "paypal"
  }
}
```
Response:
Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/billing-agreements.

{"name":"VALIDATION_ERROR","details":[{"field":"agreement_details","issue":"Not valid to specify this field in a request"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#VALIDATION_ERROR","debug_id":"84d6af76875f7"}

**Comment by jaypatel512** [comment]
The `agreement_details` is read-only. It is the details that is returned by PayPal with details about the agreement you created. 

Please remove that from the request, and you should be able to make the call appropriately.
