### ISSUE TITLE
Possible bug with json integer value equal to 0

### ISSUE THREAD

**Issue by josecelano** [paypal/PayPal-PHP-SDK#285]
It seems conversion from json to object does not work if there is an integer property with value 0, for example (no_shipping property):

````
{"allow_note":true,"no_shipping":0,"address_override":123}
````

I think the problem could be this line:

https://github.com/paypal/PayPal-PHP-SDK/blob/fd6a38d0efa82053ecc4e08c396b2650656afe24/lib/PayPal/Common/PayPalModel.php#L109

With this patch it seems to work:

````php
    public function __set($key, $value)
    {
        ModelAccessorValidator::validate($this, $this->convertToCamelCase($key));
        // NOTICE === instead of ==
        if (!is_array($value) && $value === null) {
            $this->__unset($key);
        } else {
            $this->_propMap[$key] = $value;
        }
    }
````
Notice === instead of ==

**Comment by jaypatel512** [comment]
I was able to reproduce the issue. You are right. I will however, have to consider the scenario where you pass in an empty string ? What to consider then ? I will add some more test around this, and commit it soon. 

Thanks so much @josecelano for your detailed explanation.

**Comment by josecelano** [comment]
You're welcome.
