### ISSUE TITLE
Problem with Config file sdk_config.ini not found

### ISSUE THREAD

**Issue by appshop** [paypal/PayPal-PHP-SDK#286]
Hello to everybody. I'm learning about this API Paypal. I'm include this API in my personal framework and I followed all instructions in github about "making first call". So after the last step the PHP parser give me this error:

>Config file C:\xampp\htdocs\framework\vendor\paypal\sdk-core-php\lib\..\config\sdk_config.ini not found

I'm looking for this file, but I can't find it. Can any body help me with this problem? If is necessary I can offer code as well as captures of my framework or more code.

(sorry for my English, it's not my native language)

**Comment by jaypatel512** [comment]
There are two things : 

1. From the look of it, it is having sdk-core-php which we removed as a dependency long back. Can you please make sure you are using the latest version of SDK ?

2. Are you having classic SDKs in the system too ? 

3. In your path, `lib..\config\sdk_config.ini` see `lib..\conf...` . It is missing a tiny backslash. Probably you need your sdk_config.ini  set properly, as shown here : https://github.com/paypal/PayPal-PHP-SDK/wiki/File-based-Configurations

```php
// 2. Define PP_CONFIG_PATH directory
if(!defined("PP_CONFIG_PATH")) {
    define("PP_CONFIG_PATH", __DIR__);
}
```

Let me know if this fixes the issue. If not, I would be happy to help.

**Comment by appshop** [comment]
Thank you jaypatel512. Recently cheking the manual of this API I can saw that is possible install Paypal of 2 ways: with Composer or manual. The code installed with composer (using a composer.json with require directive and writing "composer install" or using the words in comand line 'composer require "..." ' dont download the Api folder in the vendor/paypal/sdk-core-php/lib/Paypal tree filesystem folders) but when I downloaded the .zip directly (version 1.3.2) the Api folder is located. So the error is in Paypal mantener/authors. If you know where is possible notice of this issue.... Thank you again and sorry for my English, is not my native language.

**Comment by jaypatel512** [comment]
Aah ! Thanks for your message. 

If you download our SDK using composer, the location should be `vendor/paypal/rest-api-sdk-php` and not `vendor/paypal/sdk-core-php`. Thats where I think it is getting confused. 

so, from the look of it, it feels like you were able to resolve the issue. I will hovewer confirm if there is any issue with composer separately.

Please re-open this issue if you are still facing this issue with download.

**Comment by klowan** [comment]
Hello,

This error still occurs. How can I solve it? 
I don't want to edit your core files. My SDK is updated.

All best,
Maciej

**Comment by jaypatel512** [comment]
The only addition you need to do is, to locate the directory location where the sdk_config.ini file is. 

Adding this line in your bootstrap should locate the file properly.
```php
// 2. Define PP_CONFIG_PATH directory
if(!defined("PP_CONFIG_PATH")) {
    define("PP_CONFIG_PATH", __DIR__);
}
```

Also, you could print __DIR__ just to make sure that the location the __DIR__ is pointing, is the one you want. Sometimes, that is generally the cause of issue, where we get the directory location wrong. 

If nothing, provide me with some more context, and I could help you with that. I personally tested it right now, and it still works fine for me.

**Comment by klowan** [comment]
Hey,

I've seen only two sdk_config.ini in my vendor/rest-api-sdk-php they are in my test and sample folders.
My lib doesn't include any sdk_config.ini.

Please take a look on my stucture:
<img width="432" alt="screen shot 2015-08-19 at 20 23 58" src="https://cloud.githubusercontent.com/assets/13873716/9365158/4b88df0a-46b0-11e5-977f-d711ffaba87d.png">

**Comment by jaypatel512** [comment]
Yes. sdk_config.ini is something you create, and add to your project root location, not in the location where you sdk is installed. However, you could potentially copy the one in the sample, and modify it to your desire, to reach achieved result.

**Comment by jaypatel512** [comment]
Probably [this documentation](https://github.com/paypal/PayPal-PHP-SDK/wiki/File-based-Configurations) could help you understand how this works better I suppose.

**Comment by klowan** [comment]
Brillant ! 

Thanks for your professional support.

**Comment by jaypatel512** [comment]
@klowan ! We recently added these wiki pages to help developers figure how SDK works. Please let me know if there are any improvements that we could do to make it better. 

From your issue, I think creating an sdk_config.ini file that people could copy which has some basic default settings, would be a great addition to the sdk. I will think about it, and see if I could make something like that happen.

**Comment by klowan** [comment]
In my opinion it will be really cool to provide your users things like this. It will save a lot of time for others  Is there any other's features which I can add to my sdk_config.ini? Other then this from sample?

**Comment by jaypatel512** [comment]
All the available options that you may use would be in the sample. Also, if you are new to the SDK, I would highly recommend you checking out the samples provided in this SDK. They are self-deployable, on your local machine, and will give you running sample of almost all basic use cases that you wish to cover. You can then modify the sample files to your choice to obtain what you wish to achieve, and then simply write the code in your platform. 

here is the link on how to setup the samples: https://github.com/paypal/PayPal-PHP-SDK/wiki/Samples
