### ISSUE TITLE
Typo in method name ApiContext::getrequestId

### ISSUE THREAD

**Issue by josecelano** [paypal/PayPal-PHP-SDK#287]
I suppose there is a typo in that method name.

https://github.com/paypal/PayPal-PHP-SDK/search?utf8=%E2%9C%93&q=getrequestId%28

In fact, it seems to be used with the name getRequestId:

https://github.com/paypal/PayPal-PHP-SDK/blob/46f7e668cd61e465e56382196331e924c584d065/lib/PayPal/Handler/RestHandler.php#L84

**Comment by jaypatel512** [comment]
Good Catch !! Thanks @josecelano ! 

Will be fixed ASAP.

**Comment by jaypatel512** [comment]
As per the specifications, php function names are case-insensitive, so good thing is, we don't have to worry about deprecating. We could just rename it without any major issue.
