### ISSUE TITLE
Error, while processing the payment request

### ISSUE THREAD

**Issue by slave2anubis** [paypal/PayPal-PHP-SDK#293]
Hi, i have a laravel app, and i am using the paypal sdk, but after a few months of using it, now i get this error "Getter function for 'payer' in 'PayPal\Api\Payment' class should have a proper return type.", i have moved the app to a different server, can that be the problem?

**Comment by jaypatel512** [comment]
Hey @slave2anubis ! 

Can you please confirm if you have `getPayer` method in your payment.php class, in PayPal-PHP-SDK, and you have proper comments there as shown here: https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Api/Payment.php#L96-105

```php
/**
     * Source of the funds for this payment represented by a PayPal account or a direct credit card.
     *
     * @return \PayPal\Api\Payer
     */
    public function getPayer()
    {
        return $this->payer;
    }
```

**Comment by slave2anubis** [comment]
Yes, i have that method. I have installed via Composer, so it should have all the files and methods.

**Comment by jaypatel512** [comment]
Oh ! That's weird. Can you please quickly try running samples that came packaged. You could easily host it on local by following instructions [here](https://github.com/paypal/PayPal-PHP-SDK/wiki/Samples). We also have a way to run those in [command line (limited)](https://github.com/paypal/PayPal-PHP-SDK/wiki/Samples#alternatives-running-on-console). 

Let me know if you are having similar error there too ? If not, then we could dig further into your code.

**Comment by jaypatel512** [comment]
Hey @slave2anubis ! Just curious, were you able to resolve the issue ? Let me know if I could be of any help ?

**Comment by slave2anubis** [comment]
Sorry for the late reply, no i was not able to resolve this.

**Comment by jaypatel512** [comment]
Were you able to run our samples ? Generally, if samples act fine, you should be able to make it work. Also, make sure you are using the latest version of PayPal-PHP-SDK. You could use * in composer.json for version to obtain latest version.

**Comment by ChrisDeightonSerato** [comment]
Hey @slave2anubis.

I had a similar issue here https://github.com/paypal/PayPal-PHP-SDK/issues/309 which I resolved.

Maybe it's the same problem that you've encountered.

**Comment by slave2anubis** [comment]
Thank you alot, i did not have time to resolve this issue. But the suggestion from your post was spot on. When i moved the webapp to the new server i activated opcache, so probably there was the problem!

**Comment by jaypatel512** [comment]
Aah ! Would not have figured that out easily myself. Thanks @ChrisDeightonSerato for that. What I think would be helpful, to add a more detailed message in our error, that may point to a more detailed page, pointing to similar issue like this.

**Comment by jaypatel512** [comment]
There you go. Added the wiki page for this: https://github.com/paypal/PayPal-PHP-SDK/wiki/class-should-have-a-proper-return-type 

I will continue to add more of these as we find other probably issues. 

I am closing this issue for now. But dont hesitate to re-open if this didnt help.
