### ISSUE TITLE
Are there currency restrictions to the Payment API

### ISSUE THREAD

**Issue by ahoekie** [paypal/PayPal-PHP-SDK#294]
I want to know if there are currency restrictions to the paypal payout api. I am trying to do a payout on the sandbox and I used to have it working with US dollar but now I changed to EUR it fails. What I want to do:
1. Account used for developer API has EUR account with enough balance
2. Wants to do a payout to a an US account (Dollar)
3. Everytime I get a denied back

Payouts checkbox is set on the App level

**Comment by jaypatel512** [comment]
Payouts API requires you to have a balance of particular currency you wish to have. 

From the description provided at [developer docs](https://developer.paypal.com/docs/integration/direct/payouts-overview/)


> The sending PayPal account must hold the total amount of funds being sent, in the currency being sent, plus any sending fees in PayPal balance at the time the Payouts are submitted. There is no limit on the total amount of the payout. In the U.S., each individual payment can be no more than $10,000.00 USD. For accounts in other countries, the maximum individual payment varies according to the payments standard sending limit.
