### ISSUE TITLE
Error while creating payment call -- Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment

### ISSUE THREAD

**Issue by asrivastavcog** [paypal/PayPal-PHP-SDK#295]
Hi,
I am getting errors , using credit card payment method --
function is as below -- please help me what I am missing ?

function directpayusingcard($customerpostdata = array() ,$sdkConfig ){
	// blank for now
	$cred = new PayPal\Auth\OAuthTokenCredential(CLIENT_ID,SECRET, $sdkConfig);

	$apiContext = new PayPal\Rest\ApiContext($cred, 'Request' . time());
	$apiContext->setConfig($sdkConfig);
	$card = new PayPal\Api\CreditCard();
	
	#echo '<pre>';
	#pr($card);
	#die('Abhishek');
	/*
	$card->setType($customerpostdata['cardtype']);
	$card->setNumber($customerpostdata['cardno']);
	$card->setExpireMonth($customerpostdata['expiry_month']);
	$card->setExpireYear($customerpostdata['expiry_year']);
	$card->setCvv2($customerpostdata['cvv']);
	*/
	$card->setType('discover');
	$card->setNumber("6011111111111117");
	$card->setExpireMonth("04");
	$card->setExpireYear("2017");
	$card->setCvv2("222");

	$fundingInstrument = new \PayPal\Api\FundingInstrument();
	$fundingInstrument->setCreditCard($card);

	$payer = new \PayPal\Api\Payer();
	$payer->setPaymentMethod("credit_card");
	$payer->setFundingInstruments(array($fundingInstrument));
	
	#pr($payer) ;
	
	$amount = new \PayPal\Api\Amount();
	/*
	$amount->setCurrency($customerpostdata['currency']);
	$amount->setTotal($customerpostdata['total']);
	*/
	$amount->setCurrency("USD");
	$amount->setTotal(10);
	#pr($amount) ;
	#die;
	$transaction = new \PayPal\Api\Transaction();
	$transaction->setAmount($amount);
	$transaction->setDescription("creating a direct payment with credit card");
	#pr($transaction) ;

	$payment = new PayPal\Api\Payment();
	$payment->setIntent("sale");
	$payment->setPayer($payer);
	$payment->setTransactions(array($transaction));
	try{
		$payment->create($apiContext);
    	#pr($payment);
		if($payment->getState() == 'approved'){
			$payResponse =  array(
								'payment_method'=>'paypal',
								'payment_id'=>$payment->getId(),
								'pay_status'=>$payment->getState()
								) ;
		}else{
			$payResponse =  array(
								'payment_method'=>'paypal',
								'pay_status'=>$payment->getState()
								) ;
		}
	} catch (Exception $ex){
		pr($ex);
	}
	

	return json_encode($payResponse) ;
}

O/P -- Exception that --
PayPal\Exception\PayPalConnectionException Object
(
    [url:PayPal\Exception\PayPalConnectionException:private] => https://api.sandbox.paypal.com/v1/payments/payment
    [data:PayPal\Exception\PayPalConnectionException:private] => {"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"3565045a4a76b"}
    [message:protected] => Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment.
    [string:Exception:private] => 
    [code:protected] => 500
    [file:protected] => /var/www/payments/paypal-php-sdk/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php
    [line:protected] => 177
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /var/www/payments/paypal-php-sdk/paypal/rest-api-sdk-php/lib/PayPal/Transport/PayPalRestCall.php
                    [line] => 74
                    [function] => execute
                    [class] => PayPal\Core\PayPalHttpConnection
                    [type] => ->
                    [args] => Array
                        (
                            [0] => {"intent":"sale","payer":{"payment_method":"credit_card","funding_instruments":[{"credit_card":{"type":"visa","number":"4012888888881881","expire_month":"04","expire_year":"2017","cvv2":"211"}}]},"transactions":[{"amount":{"currency":"USD","total":"10"},"description":"creating a direct payment with credit card"}]}
                        )

                )

            [1] => Array
                (
                    [file] => /var/www/payments/paypal-php-sdk/paypal/rest-api-sdk-php/lib/PayPal/Common/PayPalResourceModel.php
                    [line] => 103
                    [function] => execute
                    [class] => PayPal\Transport\PayPalRestCall
                    [type] => ->
                    [args] => Array
                        (
                            [0] => Array
                                (
                                    [0] => PayPal\Handler\RestHandler
                                )

                            [1] => /v1/payments/payment
                            [2] => POST
                            [3] => {"intent":"sale","payer":{"payment_method":"credit_card","funding_instruments":[{"credit_card":{"type":"visa","number":"4012888888881881","expire_month":"04","expire_year":"2017","cvv2":"211"}}]},"transactions":[{"amount":{"currency":"USD","total":"10"},"description":"creating a direct payment with credit card"}]}
                            [4] => 
                        )

                )

            [2] => Array
                (
                    [file] => /var/www/payments/paypal-php-sdk/paypal/rest-api-sdk-php/lib/PayPal/Api/Payment.php
                    [line] => 424
                    [function] => executeCall
                    [class] => PayPal\Common\PayPalResourceModel
                    [type] => ::
                    [args] => Array
                        (
                            [0] => /v1/payments/payment
                            [1] => POST
                            [2] => {"intent":"sale","payer":{"payment_method":"credit_card","funding_instruments":[{"credit_card":{"type":"visa","number":"4012888888881881","expire_month":"04","expire_year":"2017","cvv2":"211"}}]},"transactions":[{"amount":{"currency":"USD","total":"10"},"description":"creating a direct payment with credit card"}]}
                            [3] => 
                            [4] => PayPal\Rest\ApiContext Object
                                (
                                    [requestId:PayPal\Rest\ApiContext:private] => Request1430119101
                                    [credential:PayPal\Rest\ApiContext:private] => PayPal\Auth\OAuthTokenCredential Object
                                        (
                                            [logger:PayPal\Auth\OAuthTokenCredential:private] => PayPal\Core\PayPalLoggingManager Object
                                                (
                                                    [loggerName:PayPal\Core\PayPalLoggingManager:private] => PayPal\Auth\OAuthTokenCredential
                                                    [isLoggingEnabled:PayPal\Core\PayPalLoggingManager:private] => 
                                                    [loggingLevel:PayPal\Core\PayPalLoggingManager:private] => 
                                                    [loggerFile:PayPal\Core\PayPalLoggingManager:private] => 
                                                )

                                            [clientId:PayPal\Auth\OAuthTokenCredential:private] => AQkquBDf1zctJOWGKWUEtKXm6qVhueUEMvXO_-MCI4DQQ4-LWvkDLIN2fGsd
                                            [clientSecret:PayPal\Auth\OAuthTokenCredential:private] => EL1tVxAjhT7cJimnz5-Nsx9k2reTKSVfErNQF-CmrwJgxRtylkGTKlU4RvrX
                                            [accessToken:PayPal\Auth\OAuthTokenCredential:private] => A015fOmUMmRTFiXcttpVkvp8awxI4r7yBQuhFRg9SWTp6Ts
                                            [tokenExpiresIn:PayPal\Auth\OAuthTokenCredential:private] => 28800
                                            [tokenCreateTime:PayPal\Auth\OAuthTokenCredential:private] => 1430119103
                                            [cipher:PayPal\Auth\OAuthTokenCredential:private] => PayPal\Security\Cipher Object
                                                (
                                                    [secretKey:PayPal\Security\Cipher:private] => EL1tVxAjhT7cJimnz5-Nsx9k2reTKSVfErNQF-CmrwJgxRtylkGTKlU4RvrX
                                                )

                                            [_propMap:PayPal\Common\PayPalModel:private] => Array
                                                (
                                                )

                                        )

                                )

                            [5] => 
                        )

                )

            [3] => Array
                (
                    [file] => /var/www/payments/paypalpaynew.php
                    [line] => 66
                    [function] => create
                    [class] => PayPal\Api\Payment
                    [type] => ->
                    [args] => Array
                        (
                            [0] => PayPal\Rest\ApiContext Object
                                (
                                    [requestId:PayPal\Rest\ApiContext:private] => Request1430119101
                                    [credential:PayPal\Rest\ApiContext:private] => PayPal\Auth\OAuthTokenCredential Object
                                        (
                                            [logger:PayPal\Auth\OAuthTokenCredential:private] => PayPal\Core\PayPalLoggingManager Object
                                                (
                                                    [loggerName:PayPal\Core\PayPalLoggingManager:private] => PayPal\Auth\OAuthTokenCredential
                                                    [isLoggingEnabled:PayPal\Core\PayPalLoggingManager:private] => 
                                                    [loggingLevel:PayPal\Core\PayPalLoggingManager:private] => 
                                                    [loggerFile:PayPal\Core\PayPalLoggingManager:private] => 
                                                )

                                            [clientId:PayPal\Auth\OAuthTokenCredential:private] => AQkquBDf1zctJOWGKWUEtKXm6qVhueUEMvXO_-MCI4DQQ4-LWvkDLIN2fGsd
                                            [clientSecret:PayPal\Auth\OAuthTokenCredential:private] => EL1tVxAjhT7cJimnz5-Nsx9k2reTKSVfErNQF-CmrwJgxRtylkGTKlU4RvrX
                                            [accessToken:PayPal\Auth\OAuthTokenCredential:private] => A015fOmUMmRTFiXcttpVkvp8awxI4r7yBQuhFRg9SWTp6Ts
                                            [tokenExpiresIn:PayPal\Auth\OAuthTokenCredential:private] => 28800
                                            [tokenCreateTime:PayPal\Auth\OAuthTokenCredential:private] => 1430119103
                                            [cipher:PayPal\Auth\OAuthTokenCredential:private] => PayPal\Security\Cipher Object
                                                (
                                                    [secretKey:PayPal\Security\Cipher:private] => EL1tVxAjhT7cJimnz5-Nsx9k2reTKSVfErNQF-CmrwJgxRtylkGTKlU4RvrX
                                                )

                                            [_propMap:PayPal\Common\PayPalModel:private] => Array
                                                (
                                                )

                                        )

                                )

                        )

                )

            [4] => Array
                (
                    [file] => /var/www/payments/paypalpaynew.php
                    [line] => 103
                    [function] => directpayusingcard
                    [args] => Array
                        (
                            [0] => Array
                                (
                                    [cardtype] => visa
                                    [cardno] => 4012888888881881
                                    [expiry_month] => 04
                                    [cvv] => 211
                                    [expiry_year] => 2017
                                    [currency] => USD
                                    [total] => 10
                                )

                            [1] => Array
                                (
                                    [mode] => sandbox
                                )

                        )

                )

        )

    [previous:Exception:private] => 
)

**Comment by jaypatel512** [comment]
Hey @asrivastavcog ! I think I know the issue. PayPal Sandbox has a known issue where if a "Credit Card" that is used excessively in sandbox by a lot of people throws 500 Exception.

From the previous Github Issue created, https://github.com/paypal/PayPal-NET-SDK/issues/61#issuecomment-68570042 

> I was able to get it to work by **changing the credit card number** (I tried it with `4446283280247004`, and the payment was successfully created).  Can you try that out and see if it works for you?  You can also generate a new test credit card to use against sandbox by creating a new sandbox test account from your [PayPal Developer Dashboard](https://developer.paypal.com/webapps/developer/applications/accounts/create).

Duplicate : #112
