### ISSUE TITLE
Copy/Paste error in message "The Created Web Profile was not found in the get list"

### ISSUE THREAD

**Issue by josecelano** [paypal/PayPal-PHP-SDK#297]
https://github.com/paypal/PayPal-PHP-SDK/blob/46f7e668cd61e465e56382196331e924c584d065/tests/PayPal/Test/Functional/Api/WebhookFunctionalTest.php#L140

I suppose the message should be:

"The Created Webhook was not found in the get list"

;-)

**Comment by jziaja** [comment]
Good catch! :+1: 

By the way, @josecelano, have you considered submitting pull requests?  You've been doing a great job uncovering bits of code like this that need to be updated/fixed. :)

**Comment by josecelano** [comment]
Thanks. Most of them are minor bugs/typos. I will do it the next time ;-)
