### ISSUE TITLE
how to attach item_number in rest api ?

### ISSUE THREAD

**Issue by adrianmak** [paypal/PayPal-PHP-SDK#299]
In paypal classic api, i could put a hidden form value named 'item_number', which is stored the product id.

The item_number will be returned back for a payment is made, and I could using this value to update the product sales count.

**Comment by jaypatel512** [comment]
From trying out manually in our samples, I realized that the `item_number` you are looking for is `sku` in REST API. As shown in the image below, to set the item number, you could use `setSku` method in the item object as shown below:

```php
$item1 = new Item();
$item1->setName('Ground Coffee 40 oz')
    ->setCurrency('USD')
    ->setQuantity(1)
    ->setSku("123123")   // This is what you set for Item Number
    ->setPrice(7.5);
$item2 = new Item();
$item2->setName('Granola bars')
    ->setCurrency('USD')
    ->setQuantity(5)
    ->setSku("321321")  // This is what you set for Item Number
    ->setPrice(2);
```

![screen shot 2015-05-03 at 8 56 52 pm](https://cloud.githubusercontent.com/assets/1309895/7448131/25b7ddf4-f1d7-11e4-958a-a581bd9dede9.png)
