### ISSUE TITLE
Add Customer Information when Creating Payment

### ISSUE THREAD

**Issue by jabrego** [paypal/PayPal-PHP-SDK#302]
I have just completed a regular payment creation similar to express checkout. All the steps are completed correctly. The user is redirected to paypal and the cart items have the correct amount. 

Is there any way that I can transfer the user's information from my site to the paypal site, when being redirected to paypal. So there is no need for the customer to  enter his personal information, if 
he decides to pay with a credit card. I already capture his personal information on my site. However, I do not capture credit card information.

At this point autofill in
![autofillin](https://cloud.githubusercontent.com/assets/12174723/7484631/0abb5892-f348-11e4-860d-7f6fd4fbe390.png)

I have tried using setPayerInfo() but the information does not appear when selecting creditcard in the paypal site.

Thanks for your help

Jorge

**Comment by jaypatel512** [comment]
Similar issue https://github.com/paypal/PayPal-PHP-SDK/issues/161 

Pre-filling is not currently supported, however, I think that is one step closer to making users to have a better checkout experience.
