### ISSUE TITLE
PayPalModel::getList allows arrays of mixed json objects

### ISSUE THREAD

**Issue by josecelano** [paypal/PayPal-PHP-SDK#303]
I have added a new case to PayPalModelTest::getProvider. In this case I create a json array with two different objects. PayPalModel::getList returns two PayPalModel objects with differents properties.

````php
    public function getProvider()
    {
        return array(
            array('[[]]', 1, array(array())),
            array('[{}]', 1, array(new PayPalModel())),
            array('[{"id":"123"}]', 1, array(new PayPalModel(array('id' => '123')))),
            array('{"id":"123"}', 1, array(new PayPalModel(array('id' => '123')))),
            array('[]', 0, array()),
            array('{}', 1, array(new PayPalModel())),
            array(array(), 0, array()),
            array(array("id" => "123"), 1, array(new PayPalModel(array('id' =>'123')))),
            array(null, 0, null),
            array('',0, array()),
            array('[[], {"id":"123"}]', 2, array(array(), new PayPalModel(array("id"=> "123")))),
            array('[{"id":"123"}, {"id":"321"}]', 2,
                    array(
                        new PayPalModel(array("id" => "123")),
                        new PayPalModel(array("id" => "321"))
                    )
            ),
            array(array(array("id" => "123"), array("id" => "321")), 2,
                array(
                    new PayPalModel(array("id" => "123")),
                    new PayPalModel(array("id" => "321"))
                )),
            array(new PayPalModel('{"id": "123"}'), 1, array(new PayPalModel(array("id" => "123")))),
            // Array of json object with one wrong object
            array('[{"id":"123"}, {"error":"error message"}]', 2,
                array(
                    new PayPalModel(array("id" => "123")),
                    new PayPalModel(array("error" => "error message"))
                )
            ),
        );
    }
````

Should not the method getList check that all objects in the array have the same properties?

Sample json array of event types with wrong value:

````json
[    
	{
      "name": "PAYMENT.AUTHORIZATION.CREATED",
      "description": "A payment authorization was created"
    },
    {
      "error": "error",
    },	

]
````

If validation is disabled running this:

````php
        $obj = WebhookEventType::getList('[{"name":"TestSample","description":"TestSample"},{"error":"error"}]');
        var_dump($obj);
````

will show:

````sh
array(2) {
  [0] =>
  class PayPal\Api\WebhookEventType#204 (1) {
    private $_propMap =>
    array(2) {
      'name' =>
      string(10) "TestSample"
      'description' =>
      string(10) "TestSample"
    }
  }
  [1] =>
  class PayPal\Api\WebhookEventType#203 (1) {
    private $_propMap =>
    array(1) {
      'error' =>
      string(5) "error"
    }
  }
}
````

It means that it return an invalid empty WebhookEventType, may be it should return null instead of WebhookEventType, what do you think?

Something like:

````sh
array(2) {
  [0] =>
  class PayPal\Api\WebhookEventType#204 (1) {
    private $_propMap =>
    array(2) {
      'name' =>
      string(10) "TestSample"
      'description' =>
      string(10) "TestSample"
    }
  }
  [1] => null
}
````

or throw an exception

**Comment by jaypatel512** [comment]
Hey @josecelano !

SDK is designed to be flexible for future additions/removals of properties in data models. E.g. error is currently not in the WebhookEventType, but it could be. We have Validators that validate if the getter setter exists for any property or not. However, SDK should not break, if in future a new property has been added, and still you are using an older SDK. For that same reason, we do not strictly throw an exception, or do anything unusual, when an unknown property inside the class is set. E.g. "error" in our case. 

Does that make sense ? That's the reason why we still create an instance of the class specified by user, without complaining (it will warn if using [Validation](https://github.com/paypal/PayPal-PHP-SDK/wiki/Validation)). 

Let me know if that does not make sense to you ? we can talk more about it.

Btw, a real case that happened few months back. Payment API introduced a new object, in their latest API update, that allows the payment to have more information about the payer. Now, for anyone who were using our SDK previously, would not have any getter setter for those objects, as they didnt exist when the SDK were released. Now, if we have something strict about throwing an exception if an unknown property is seen, it would break their integration, which is not good at all. At all times, SDK should try to be compatible not only with older versions, but also with future versions of APIs, and so, we could not be strict in data mapping.

**Comment by josecelano** [comment]
OK. I know that but what I mean is that: at the same time (the same API request) if an array is returned all object in that array should contains the same properties. If you add a new property that property should be present on all objects. GetList method is soppused to get an array of objects of the same type (in json) and return and array of objects of the same type (as PHP object). I think that method should return something like invalid json.

I suppose the API never returns and array of the same object with different properties (in the same request).

In case the API returns an array and one of the items has totally different properties, how the user can validate each item. In my previous sample the second WebhookEventType does not contain valid properties. User can expect all entities in the array to contain name and description properties. I suppose that API will never return such json but user can generate an invalid one and pass it to GetList method.

**Comment by jaypatel512** [comment]
Hey @josecelano ! 

> I suppose the API never returns and array of the same object with different properties (in the same request).

We don't know that, and that is the flexibility we wish to provide in SDK. Because, it is absolutely necessary to have a forward compatibility with APIs. 

And regarding the different properties, that could be the case, for e.g. payment done with Credit Card vs PayPal. The Payer object properties are different in each, and are set accordingly. I agree that there is a very good chance that it will always be of the same type, which could mean, it would always have the required field too. And for some reason, you are missing a required field in one of the API object, it is an API bug, and definitely it is something we could get it fixed in API end.

**Comment by jaypatel512** [comment]
Also, you could always turn on the validation to determine such inconsistency. If for any reason, the object is not as expected, if the validation is on, it will thrown an exception or throw a warning log.

**Comment by josecelano** [comment]
OK, thanks.
