### ISSUE TITLE
ReflectionException: Method PayPal\Api\Sale::getTransactionFee() does not exist in ReflectionMethod->__construct()  after Upgrade to 1.3.2

### ISSUE THREAD

**Issue by Chris8080** [paypal/PayPal-PHP-SDK#304]
Hello,

I just upgraded to 1.3.2:

```bash
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing paypal/rest-api-sdk-php (v1.3.1)
  - Installing paypal/rest-api-sdk-php (v1.3.2)
    Loading from cache
Writing lock file
Generating autoload files
```

and my composer.lock agrees with that:
            "name": "paypal/rest-api-sdk-php",
            "version": "v1.3.2",

But I still receive this error message - with sandbox and live systems both.
In the live system, the payments are being processed.

Is this possible?
Do I have to catch the error somehow or what do I need to do here?

**Comment by jaypatel512** [comment]
Can you please try running the samples, and see if they work fine in your local machine ?

You could do so by following instructions here : https://github.com/paypal/PayPal-PHP-SDK/wiki/Samples

**Comment by jaypatel512** [comment]
Any updates on this ?

**Comment by jaypatel512** [comment]
Hey @Chris8080 ! I am closing this issue for now, please re-open if the issue still exists.
