### ISSUE TITLE
"First call" example doesn't work out of the box

### ISSUE THREAD

**Issue by jdwx** [paypal/PayPal-PHP-SDK#306]
Attempting to do anything with the PHP API, even run the very first simplest example provided exactly as provided, results in an exception about a missing config file:

Fatal error: Uncaught exception 'PPConfigurationException' with message 'Config file /opt/local/lib/php/vendor/paypal/sdk-core-php/lib/../config/sdk_config.ini not found' in /opt/local/lib/php/vendor/paypal/sdk-core-php/lib/PPConfigManager.php:40
Stack trace:
#0 /opt/local/lib/php/vendor/paypal/sdk-core-php/lib/PPConfigManager.php(23): PPConfigManager->load('/opt/local/lib/php/v...')
#1 /opt/local/lib/php/vendor/paypal/sdk-core-php/lib/PPConfigManager.php(30): PPConfigManager->__construct()
#2 /opt/local/lib/php/vendor/paypal/sdk-core-php/lib/PPLoggingManager.php(43): PPConfigManager::getInstance()
#3 /opt/local/lib/php/vendor/paypal/rest-api-sdk-php/lib/PayPal/Auth/OAuthTokenCredential.php(49): PPLoggingManager->__construct('PayPal\\Auth\\OAu...')
#4 /opt/local/sbin/paypal-first.php(12): PayPal\Auth\OAuthTokenCredential->__construct('AYSq3RDGsmBLJE-...', 'EGnHDxD_qRPdaLd...')
#5 {main}
  thrown in /opt/local/lib/php/vendor/paypal/sdk-core-php/lib/PPConfigManager.php on line 40

There is no reference to this config file in the Installation instructions or in the description of "how to make your first call."  Later in the documentation, using a config file is presented as an alternative to configuring the API context from PHP, not as a requirement.  But this hasn't even gotten as far as instantiating an ApiContext object, much less configuring one.

The expected behavior is that it should be possible to run the examples as-written by following the directions provided.

**Comment by jaypatel512** [comment]
Please use the latest version of PayPal-PHP-SDK. From the look of it, it shows that you are using sdk-core-php, which was deprecated on 1.* version of this SDK. Please re-open if the issue still exists.

**Comment by jdwx** [comment]
In that case, it is this page that is incorrect:

https://developer.paypal.com/docs/api/

As following the example provided forces the SDK version to 0.5.

**Comment by jaypatel512** [comment]
You could update the instructions provided to install from here: https://github.com/paypal/PayPal-PHP-SDK/wiki/Installation

I will update the developer docs as soon as possible.
