### ISSUE TITLE
Webhooks and IPN, questions about the raw data returned

### ISSUE THREAD

**Issue by kenjohnson** [paypal/PayPal-PHP-SDK#307]
I have some questions and comments concerning 
IPN raw data and webhooks raw_data.

I am using PayPal REST (PHP-SDK 1.3.1)
and doing memberships. 

I had IPN working just fine for PayPal x.com
Since webhooks for subscription is not quite
implemented yet, I am using IPN instead,
and I use the classic (x.com) library for IPN.

In IPN, I notice all the raw data I get back from 
IPN for membership is the same data I got 
back when using x.com. It has variables
like recurring_payment_id, and things like that.
By the way, I do see that 
recurring_payment_id is the
same as agreement_id, so you do have a link to
some of your REST information.

Is everyone else getting this same kind of 
raw_data with IPN?

Consider the case where I just buy
a shopping cart item using the paypal method. 
Both webhooks and IPN work for this,
and I have set up both of them. 
In this case the raw data from IPN is 
different than the raw data from webhooks.
Will this be the same with subscriptions?

At some point will the raw_data returned 
from IPN change to be the same as the raw
date returned by webhooks?  My guess is the
answer is no, because PayPal would want to 
allow some people to continue using 
paypal classic.

**Comment by jaypatel512** [comment]
Ideally the data returned from IPN and x.com should be the same. 
Webhook is based on JSON standards, and would have different data structure. There are some important security changes that are taking place in webhooks. We will be implementing the webhook handler soon that would help expedite the integration between webhooks and PHP frameworks.
