### ISSUE TITLE
Is there going to be a sample webhooks handler?

### ISSUE THREAD

**Issue by kenjohnson** [paypal/PayPal-PHP-SDK#308]
I am using PHP-SDK 1.3.1

I have webhooks working for shopping
cart items when you pay by method paypal.
I use requestbin, but
I would like to implement a webhooks
handler.  

What files would I include?

How is the information passed to my 
webhooks handler? by GET, REQUEST, POST?

How do I get all the raw data that is 
passed to my webhooks hander?

Are there some webhooks classes that 
have some methods that allow me to get
the webhooks data?

**Comment by jaypatel512** [comment]
Hey @kenjohnson ! 

We are working on implementing webhook handler/receiver, who will have validation methods to validate the webhook data, and present to you in a nicer fashion. The code is still under progress.

**Comment by jaypatel512** [comment]
Hey @kenjohnson  !

We have released the new version that includes Webhook Validation Support. Here are the interesting links for you:

- **Release Version** : [v1.4.0](https://github.com/paypal/PayPal-PHP-SDK/releases/tag/v1.4.0)
- **Documentation** : [Webhook Validation Docs](https://github.com/paypal/PayPal-PHP-SDK/wiki/Webhook-Validation)

> Please note that the SDK wont work with webhook simulator provided in PayPal Developer Page. You need to run sandbox samples to retreive those webhooks. Please read the documentation for more explanation.

**Comment by kenjohnson** [comment]
Thank you Jay,

I have installed PHP-SDK 1.4.0 

In the samples, I can get ValidateWebhookEvent.php working with your
clientId and secretId, but not with my own clientId and secretId.

Here is the error message 

Response Object

Got Http response code 401 when accessing https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-36G56432PK518391U-9HW18392D95289106.

{"name":"UNAUTHORIZED","details":[],"message":"Not authorized for this operation"}


By the way,  in the samples, my clientId and secretId work fine for
payments.
