### ISSUE TITLE
Error: Getter function for 'payer' in 'PayPal\Api\Payment' class should have a proper return type

### ISSUE THREAD

**Issue by ChrisDeightonSerato** [paypal/PayPal-PHP-SDK#309]
I'm trying to use the SDK to make a payment of type 'paypal'.

When I run the sample script CreatePaymentUsingPayPal.php it executes correctly from a command line but I receive the following error when executing it via a web server:

Getter function for 'payer' in 'PayPal\Api\Payment' class should have a proper return type

I'm running the code on a VM running CentOS 6.5 with PHP 5.5.24 and version 1.3.2 of the PayPal SDK.

I've tried using the built in PHP web server and Nginx + php-fpm. I can successfully run the script via CLI on the same VM using the exact same code base.

The generated Request JSON object in both usages (ie. CLI and web server) appears identical.

When using a web server, the debug output of the Response suggests that the API call was successful: I can see the redirect URL (amongst other things) in the Response data. But the SDK is throwing an exception.

I saw this issue, https://github.com/paypal/PayPal-PHP-SDK/issues/293, which mentions the same error but no resolution to the problem.

**Comment by ChrisDeightonSerato** [comment]
OK, I solved my own problem :-)

The PayPal\Common\ReflectionUtil class used throughout the SDK relies on reading PHP code annotations via the \ReflectionMethod class.

The annotations are declared within PHP code comments.

I use the built-in PHP opcache but had the opcache.save_comments and opcache.load_comments config directives set to 0.

This meant that the opcache was discarding code comments which in turn could not be read via the \ReflectionMethod class.

The PHP CLI implementation doesn't use the opcache which explains why that was working OK.

So the fix for me was to ensure that I have the following directives specified in my php.ini file:

[opcache]
opcache.save_comments=1
opcache.load_comments=1

May I suggest that some additional documentation be added to mention something to this affect.

**Comment by jaypatel512** [comment]
Aah !! I can see that happening. Thats a really impressive debugging you did there. I didnt realize that someone could optimize the filesize in opcache to minimize cache data, eventually causing the SDK code to break. 

I will definitely add this scenario in one of the wiki page. I will probably try to pick the most common issues that we have seen in SDKs, and point those issues in one wiki page. Would be helpful.

**Comment by ChrisDeightonSerato** [comment]
Sounds good @jaypatel512.

**Comment by geodeveloper** [comment]
I faced this problem too, thanks @chris-die for pointing this out.

**Comment by dolito** [comment]
3 years later I could resolve this in 5 minutes! Thx to you @chris-die

**Comment by LinQianWei** [comment]
why i tyied ,it desen't work

**Comment by LinQianWei** [comment]
why i tried,it doesn't work?@chris-die

**Comment by psaikali** [comment]
Thanks @chris-die, 4 years later and still an issue.

Just mentioning Kinsta and WooCommerce here, so people can find out this thread. 
Just ask support enable `opcache.save_comments=1` and no more fatal errors.
