### ISSUE TITLE
HTTP DELETE method with body not supported

### ISSUE THREAD

**Issue by josecelano** [paypal/PayPal-PHP-SDK#311]
Hi, in this line:
https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Core/PayPalHttpConnection.php#L97
you can add DELETE this way:

````php
...
        //Determine Curl Options based on Method
        switch ($this->httpConfig->getMethod()) {
            case 'POST':
                curl_setopt($ch, CURLOPT_POST, true);
            case 'PUT':
            case 'PATCH':
            case 'DELETE':
                curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
                break;
        }
...
````
if you want to support DELETE with body content in the future. I suppose you do not have that case for the time being.

**Comment by jaypatel512** [comment]
From the semantics specifications : http://tools.ietf.org/html/draft-ietf-httpbis-p2-semantics-14#section-7.7 they do say that DELETE body has no semantics to it, but I agree, I think having that feature in it should be helpful. I will go ahead and make the change. 

Thanks again for your wonderful help. Really appreciated.

**Comment by josecelano** [comment]
Hey @jaypatel512 I asked Leonard Richardson on Twiiter and he told me he would not use body for DELETEs.

https://twitter.com/leonardr/status/601061556835745792

but anyway I suppose it is a HTTP user decision.

**Comment by jaypatel512** [comment]
Exactly. We will still add the feature as body is allowed on DELETE, but will not advertise on upper layers. Generally wouldnt matter, as none of the PayPal APIs use DELETE bodies, but either case, closer to specs.
