### ISSUE TITLE
ipn notifications not working with rest api

### ISSUE THREAD

**Issue by engrsandeep** [paypal/PayPal-PHP-SDK#313]
Hi,

We are having issue in receiving ipn notifications from paypal from starting may, 2015. 
We got below email from paypal saying. When i tried our ipn url in browser it opening well.  Can you please guide what paypal have changed recently so we can amend accordingly.

"When sent, we receive a message in return advising the IPN has failed. This means that the URL does not have a listener set up or is not ready to 'hear' the messages."

Tried sandbox IPN Simulator and got below message.
We're sorry, we could not connect to this URL. Please make sure it was entered correctly.

It was working fine till April, 2015. suddenly stopped working but not sure what paypal have changed.

Can you please help me out.

Many many thanks.

**Comment by jaypatel512** [comment]
Can you please try using an external tool like: http://requestb.in/, by creating a one requestbin, and using that url to point sandbox IPN simulator ? 

I was not able to reproduce the issue you are seeing. I was able to send the message appropriately.

**Comment by jaypatel512** [comment]
Hey @engrsandeep ! Were you able to resolve the issue ?

**Comment by jaypatel512** [comment]
Closing this issue based on inactivity. Please re-open if issue exists.
