### ISSUE TITLE
Plan ID retrieval from Agreement ID?!

### ISSUE THREAD

**Issue by nekhbet** [paypal/PayPal-PHP-SDK#314]
Asking for information about a billing agreement /v1/payments/billing-agreements/<Agreement-Id> returns details about the plan itself but not its ID. How can someone, given an agreement ID get a plan ID?!

**Comment by jaypatel512** [comment]
Hey @nekhbet ! 

I got an initial answer from the API team that, currently, the support for getting a plan Id from agreement is not supported, as it was considered first for Plan to be just as a template for agreement creation.

**Comment by jaypatel512** [comment]
Similar issue https://github.com/paypal/PayPal-Java-SDK/issues/53
