### ISSUE TITLE
Recurrent 400 Error with the last API update

### ISSUE THREAD

**Issue by eqrxjz** [paypal/PayPal-PHP-SDK#315]
Hello! I have this site since last september (hurom.mx), it was running with no mayor problem until the release of last API update to 1.3.1 where i needed to update cause the "getTransactionFee() does not exist" issue. Apparently that resolve the problem, but since last update i got some fatal error, but the weird thing is that only 1 of each 5 or 6 transactions receive this problem, and the other ones going thru. This is the fatal error the user received.

Fatal error:
Uncaught exception 'PayPal\Exception\PayPalConnectionException' with message 'Got Http response code 400 when accessing https://api.paypal.com/v1/payments/payment/PAY-1CC07416ND0889035KVS7S7A/execute.' in /home/huromex/public_html/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php:177 Stack trace: #0 /home/huromex/public_html/vendor/paypal/rest-api-sdk-php/lib/PayPal/Transport/PayPalRestCall.php(74): PayPal\Core\PayPalHttpConnection->execute('{"payer_id":"P3...') #1 /home/huromex/public_html/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PayPalResourceModel.php(103): PayPal\Transport\PayPalRestCall->execute(Array, '/v1/payments/pa...', 'POST', '{"payer_id":"P3...', NULL) #2 /home/huromex/public_html/vendor/paypal/rest-api-sdk-php/lib/PayPal/Api/Payment.php(498): PayPal\Common\PayPalResourceModel::executeCall('/v1/payments/pa...', 'POST', '{"payer_id":"P3...', NULL, Object(PayPal\Rest\ApiContext), NULL) #3 /home/huromex/public_html/PPExecutePayment.php(16): PayPal\Api\Payment->execute(Ob in /home/huromex/public_html/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php on line 177

This is the response registry in the LOG:

ERROR	: Got Http response code 400 when accessing https://api.paypal.com/v1/payments/payment/PAY-1CC07416ND0889035KVS7S7A/execute. {"name":"INSTRUMENT_DECLINED","message":"The instrument presented  was either declined by the processor or bank, or it can't be used for this payment.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INSTRUMENT_DECLINED","debug_id":"427309faf4871"}

Could you help me to know what can i do to avoid this error?

Thanks!!

**Comment by jaypatel512** [comment]
I think the issue you are seeing is because of :+1: 
```
{"name":"INSTRUMENT_DECLINED","message":"The instrument presented was either declined by the processor or bank, or it can't be used for this payment.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INSTRUMENT_DECLINED","debug_id":"427309faf4871"}
```

I think the credit card/payment source used for the above transaction is invalid. I will try to see if I could get more details based on `debug_id`. However, one thing I can assure is, that there are not SDK issues in your setup. This has to do something directly with Payment APIs, which we will figure out soon :)

**Comment by jaypatel512** [comment]
Could be related to https://github.com/paypal/PayPal-NET-SDK/issues/104

**Comment by jaypatel512** [comment]
Hey @eqrxjz !

Can you please retry this ? We recently found a bug in Payments API that was not allowing PayPAl Payments using credit cards. The issue has been resolved now. 

Please re-open the ticket if the issue still exists.

**Comment by eqrxjz** [comment]
Hello Jay! i search on my log and it seems no longer 400 Error apear on it, i try to recreate the error calling the API and i don’t have this error anymore, i’m glad it was just a bug, i really appreciate your help! Thanks!

Enrique

**Comment by jaypatel512** [comment]
I am glad it worked :) Let us know if our SDK does something bad again  :)

**Comment by Fever905** [comment]
Checking into this myself. From what I can gather, the 400 error is the code they send you when there is a problem with the transaction and it is declined.   There should also be an explanation as to what happened along with it, in my case it was missing SKU.
