### ISSUE TITLE
IPN Simulator documentation on notifications.

### ISSUE THREAD

**Issue by kenjohnson** [paypal/PayPal-PHP-SDK#317]
I notice the IPN Simulator does not send notification to your account.
I believe it is designed to work this way, but PayPal might want to say
so more explicitly in the documentation.  

The documentation talks about this here

https://developer.paypal.com/webapps/developer/docs/classic/ipn/integration-guide/IPNSimulator/

It says "the notification URL does not have to be set up in your PayPal account profile"
This infers that you won't see notifications in your account, but it might
be nice to more explicitly say this.
Perhaps add something like the following.
"The IPN Simulator does not send out any notifications to your 
accounts, so do not expect to see any notifications on any of
your account pages."

Here is bigger snippet of the documentation

>IPN listener requirements

>There are two basic requirements when using the IPN Simulator to send IPN messages from the >PayPal Sandbox:

>    You have to change the code in your listener to post your response to the Sandbox URL at >https://www.sandbox.paypal.com/cgi-bin/webscr, instead of the live URL https://www.paypal.com/cgi-bin/webscr. This URL cannot be localhost. Unlike the enabling the IPN service in the Live IPN >environment, the notification URL does not have to be set up in your PayPal account profile.

**Comment by jaypatel512** [comment]
The IPN Simulator is built to just simulate an even that resembles to a proper event. It will not be sending any notification to your account. This is a universal understanding about simulators. They just fake the operation you are trying to make, and to prevent accidental issues, they never store these requests anywhere. Simulators are to be used just for testing purposes only. 

The same stands for Webhook Simulator too.
