### ISSUE TITLE
PHP-SDK

### ISSUE THREAD

**Issue by alien3d** [paypal/PayPal-PHP-SDK#318]
The Source Code Seem Over Engineer..  

Do Please Clean the code..

To create an agreement  
1. require update
2. require create

To delete 
same as above..

It totally weird  to delete must create a plan. It's to show a flow which can be see but need to create more simplifier API like 

Agreement->delete($agreement)

OR Update
Agreement->update($agreement,$amount);

I also don't see how invoices related to agreement or plan ?  Are 1 plan 1 agreement How  about multiple item invoice in 1 invoices in the term of plan and agreement ?
E.g

I invoice 2 item recurring 6 month
If the in 6 month the person wanted to add new item 
1 invoices 3 item recurring 6 month

I don't see how any of it i can update in agreement or plan the amount and description.. This is normal transaction .

**Comment by jaypatel512** [comment]
Hey @alien3d ! 

I agree with you on few points you mentioned above, about over engineering of API operations. Update Agreement is definitely something that could be simplified. However, you need to keep in mind that the APIs are different than the SDKs. We, as SDK team generates SDK for PayPal API. However, we have strongly asked Subscription Team (responsible for Plan and Agreement API), to redesign, or optimize few of such optimization. I will definitely go ahead and share your concern.

About your question on updating an existing agreement, you cannot currently update the amount once the agreement has been executed. This was done this way to not allow merchants to modify an agreement that has already been made. However, we have realized this as a big blocker for many use cases, and the team is working on allowing this change. However, for now, this is not currently supported.

I will definitely send your concerns to the right team, and make sure it gets executed as soon as we could. I will close the story for now, but feel free to re-open if you run into any other issues.
