### ISSUE TITLE
Partial Refunds : response code 400

### ISSUE THREAD

**Issue by guillermog** [paypal/PayPal-PHP-SDK#319]
Hi, is anyone else having problems with partial refunds? I keep getting: 

<pre>PayPalConnectionException in PayPalHttpConnection.php line 177: Got Http response code 400 when accessing https://api.paypal.com/v1/payments/sale/[tx-id]/refund.</pre>

When I do full refunds (using full amount) it goes through fine, only when the amount is less than the total transaction amount it gives me this error. I believe it was working fine a couple of days ago, it is only recently that I started experiencing this issue.

This is the code Im using to refund:

<pre>$reference = $order->fetchOrderMeta('payment_transaction_id', true);
			$reason = $request->input('refund_reason');
			$amount = new Amount();
			$amount->setCurrency("GBP");
			$amount->setTotal($request->input('refund_amount'));
			
			$refund = new Refund();
			$refund->setAmount($amount);
			$refund->setReason($reason);
			
			$capture = Capture::get($reference, $apiContext);
				
			try {
				//dd($reason);
		        $capture->refund($refund, $apiContext);
		        
		        //dd($captureRefund);
		    } catch (\PayPal\Exception\PPConnectionException $ex) {
		        if (\Config::get('app.debug')) {
		            echo "Exception: " . $ex->getMessage() . PHP_EOL;
		            $err_data = json_decode($ex->getData(), true);
		            exit;
		        } else {
		            die('Some error occur, sorry for inconvenient');
		        }
		    }</pre>

Any help would be greatly appreciated. Bellow is some more debuging info I get from laravel:

<pre>in PayPalHttpConnection.php line 177
at PayPalHttpConnection->execute('{"amount":{"currency":"GBP","total":"0.14"}}') in PayPalRestCall.php line 74
at PayPalRestCall->execute(array('PayPal\Handler\RestHandler'), '/v1/payments/sale/0UB26548H26568121/refund', 'POST', '{"amount":{"currency":"GBP","total":"0.14"}}', null) in PayPalResourceModel.php line 103
at PayPalResourceModel::executeCall('/v1/payments/sale/0UB26548H26568121/refund', 'POST', '{"amount":{"currency":"GBP","total":"0.14"}}', null, object(ApiContext), null) in Sale.php line 553
at Sale->refund(object(Refund), object(ApiContext)) in PaymentController.php line 358
at PaymentController->refundPayment(object(Request), object(Order))
at call_user_func_array(array(object(PaymentController), 'refundPayment'), array(object(Request), 'order' => object(Order))) in Controller.php line 246
at Controller->callAction('refundPayment', array(object(Request), 'order' => object(Order))) in ControllerDispatcher.php line 162
at ControllerDispatcher->call(object(PaymentController), object(Route), 'refundPayment') in ControllerDispatcher.php line 107
at ControllerDispatcher->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 141
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 101
at Pipeline->then(object(Closure)) in ControllerDispatcher.php line 108
at ControllerDispatcher->callWithinStack(object(PaymentController), object(Route), object(Request), 'refundPayment') in ControllerDispatcher.php line 67
at ControllerDispatcher->dispatch(object(Route), object(Request), 'App\Http\Controllers\PaymentController', 'refundPayment') in Route.php line 204</pre>

**Comment by jaypatel512** [comment]
Can you please catch the exception as shown below, and see what the data is. You need to rename the Exception `PPConnectionException` to `PayPalConnectionException`
```php
} catch (\PayPal\Exception\PayPalConnectionException $ex) {
                if (\Config::get('app.debug')) {
                    echo "Exception: " . $ex->getMessage() . PHP_EOL;
                    $err_data = json_decode($ex->getData(), true);
                    exit;
                } else {
                    die('Some error occur, sorry for inconvenient');
                }
            }
```
https://github.com/paypal/PayPal-PHP-SDK/wiki/exception-%27PayPal%5CException%5CPayPalConnectionException%27-with-message-%27Got-Http-response-code-400-when-accessing

**Comment by guillermog** [comment]
Thanks for the suggestion. This is what I get now transaction:

<pre>Exception: Got Http response code 400 when accessing https://api.paypal.com/v1/payments/sale/0UB26548H26568121
/refund.
Array
(
    [name] => TRANSACTION_REFUSED
    [message] => The request was refused.{0}
    [information_link] => https://developer.paypal.com/webapps/developer/docs/api/#TRANSACTION_REFUSED

    [debug_id] => e6947b4f806cc
)</pre>

or this too

<pre>Exception: Got Http response code 400 when accessing https://api.paypal.com/v1/payments/capture/9KV63860KB715761P
/refund.
Array
(
    [name] => TRANSACTION_REFUSED
    [message] => The request was refused.The partial refund amount is not valid
    [information_link] => https://developer.paypal.com/webapps/developer/docs/api/#TRANSACTION_REFUSED

    [debug_id] => cc662f160d0b5
)</pre>

Why do you suppose its being refused?

**Comment by ppmtscory** [comment]
@guillermog for the first error, it's showing a timestamp of after it's already been refunded so that's why it's being refused.  For the second error, it's stating that there was an invalid amount passed through.  However, if that's for the same sale ID, then it won't go through either because of already being refunded in full.

**Comment by guillermog** [comment]
But what qualifies as an invalid amount? below is the refund and capture object Im using to perform the refund, everything looks good to me, maybe Im missing something:

Refund:
<pre>
Refund {#243
  -_propMap: array:2 [
    "amount" => Amount {#246
      -_propMap: array:2 [
        "currency" => "GBP"
        "total" => "15"
      ]
    }
    "reason" => "test"
  ]
}
</pre>

Capture:
<pre>
Capture {#244
  -_propMap: array:7 [
    "id" => "9KV63860KB715761P"
    "create_time" => "2015-06-02T21:18:25Z"
    "amount" => Amount {#252
      -_propMap: array:2 [
        "total" => "35.00"
        "currency" => "GBP"
      ]
    }
    "state" => "completed"
    "invoice_number" => "7700632"
    "transaction_fee" => Currency {#247
      -_propMap: array:2 [
        "value" => "0.59"
        "currency" => "GBP"
      ]
    }
    "links" => array:2 [
      0 => Links {#249
        -_propMap: array:3 [
          "href" => "https://api.paypal.com/v1/payments/capture/9KV63860KB715761P"
          "rel" => "self"
          "method" => "GET"
        ]
      }
      1 => Links {#250
        -_propMap: array:3 [
          "href" => "https://api.paypal.com/v1/payments/capture/9KV63860KB715761P/refund"
          "rel" => "refund"
          "method" => "POST"
        ]
      }
    ]
  ]
}
</pre>

**Comment by ppmtscory** [comment]
@guillermog After some further testing, I'm also having some issues when doing a partial refund on a Capture.  Let me do some more testing/research and then I will get back to you here.

**Comment by ppmtscory** [comment]
@guillermog We expect this issue with partial refunds to be resolved later this evening.

**Comment by ppmtscory** [comment]
@guillermog This issue should be resolved now.  I was just able to successfully do a partial refund on an eligible transaction.  If you experience any other issues, please feel free to let us know.

**Comment by guillermog** [comment]
@ppmtscory was it resolved on PayPal's end? on the SDK? do I need to update any files?

Thanks.

**Comment by ppmtscory** [comment]
It was resolved on PayPal's end.  You don't need to do anything on your side.

**Comment by jaypatel512** [comment]
Thanks @ppmtscory for helping us solving this issue.

**Comment by guillermog** [comment]
Awesome! thank you guys a lot for your help.
