### ISSUE TITLE
1.3.2 - Item::setCategory() -> This field name is not defined for this resource type

### ISSUE THREAD

**Issue by Xety** [paypal/PayPal-PHP-SDK#321]
Hello,

I'm trying to use your awesome SDK and it work well.
But when i want to set the category to the Item with the method `setCategory()`, i have an error.

Code used :
```php
$payer = new Payer();
$payer->setPaymentMethod("paypal");

$item = new Item();
$item->setName($application->title)
        ->setCurrency($application->currency_code)
        ->setQuantity(1)
        ->setCategory("DIGITAL") 
        ->setSku($application->id)
        ->setPrice($application->price);

$itemList = new ItemList();
$itemList->setItems([$item]);

$tax = $application->price * $application->tax / 100;

$details = new Details();
$details->setTax($tax)
        ->setSubtotal($application->price);

$amount = new Amount();
$amount->setCurrency($application->currency_code)
        ->setTotal($application->price + $tax)
        ->setDetails($details);

$transaction = new Transaction();
$transaction->setAmount($amount)
        ->setItemList($itemList)
        ->setDescription("Payment description")
        ->setInvoiceNumber(uniqid());
```

```php
stdClass Object
(
    [name] => VALIDATION_ERROR
    [details] => Array
        (
            [0] => stdClass Object
                (
                    [field] => transactions[0].item_list.items[0].category
                    [issue] => This field name is not defined for this resource type
                )

        )

    [message] => Invalid request - see details
    [information_link] => https://developer.paypal.com/webapps/developer/docs/api/#VALIDATION_ERROR
    [debug_id] => 7e65ccc813d9b
)
```

I don't understand why it don't work.
Related function : https://github.com/paypal/PayPal-PHP-SDK/blob/2c90b77c5ab779a7ed19a7dc61d73074d1eb32b7/lib/PayPal/Api/Item.php#L224-L236

I have also the **same** bug for the function `Item::setUrl()`.

I have also another question :
How can i set a discount/reduction (percentage or the amount of the discount) to the Item ?
Because i saw that i can set a Tax (With the method `Details::setTax(15)`) but nothing about a discount/reduction.

Your SDK is very awesome. Great work !

**Comment by jaypatel512** [comment]
Hey @Xety !

As per the developer documentation, only these fields are allowed in Item: https://developer.paypal.com/webapps/developer/docs/api/#item-object

| Property	| Type |	Description |
| ---- | ---- | ---- |
| quantity	| string	| Number of a particular item. 10 characters max. Required. |
| name	| string	| Item name. 127 characters max. Required. | 
| price	| string	| Item cost. 10 characters max. Required. |
| currency	 | string	| 3-letter currency code. Required. |
| sku	 | string	|Stock keeping unit corresponding (SKU) to item. 50 characters max. |
| description	| string	| Description of the item. Only supported when the payment_method is set to paypal. 127 characters max. |
| tax	| string	| Tax of the item. Only supported when the payment_method is set to paypal. |

There are no current field that allows us to set category, url, etc. Keep in mind that sometimes, we have these getter setters that are not supported externally to public, but are available to very limited set of merchants, e.g. eBay, etc. category, and url seems to be one of those. In these cases, we generally keep it deprecated for external users. They may become available in future, however, it is not supported yet. 

Appreciated your kind words about SDK. Let us know of any feedback you have on improvising our SDK.

**Comment by Xety** [comment]
Hello @jaypatel512 !

Ahhh okay, now i understand why it doesn't work. :stuck_out_tongue: I can close the issue then.

I have another question :
How can i set a discount/reduction (percentage or the amount of the discount) to the Item or to the total of the transaction please ? 
I see nothing about that in the doc or in the API itself. With the classic API it was `discount_rate`.

**Comment by Xety** [comment]
No answer for my question ? :( I really need to know, because i have a reduction system with codes etc.
