### ISSUE TITLE
Requested experience ID not found : error 400

### ISSUE THREAD

**Issue by korentins** [paypal/PayPal-PHP-SDK#322]
Hello,
I'm using the PHP SDK to create Payments.
I recently created a "web experience profile" through the samples files of the SDK.
Everything seems good, but when I try to use this web experience in a request I get the "Requested experience ID not found" error message. I tried this in Sandbox mode but my web experience profile was also generated in sandbox mode.
My request format is exactly the same as it is described in the doc:
```
"experience_profile_id":"XP-MYRC-3M7H-N8LM-DKH9"
```
Some help would be welcome.

**Comment by jaypatel512** [comment]
Just to make sure, can you please make sure that the clientId and secret used for sample were yours. We ship a sample clientId and secret, and if you just created a "web profile experience" directly from sample, it would not have used your client Id and secret, unless you change it in [bootstrap.php](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/bootstrap.php#L29-30)

Once you have done that, try using that in your payment call (making sure the clientID is same), and see if it works. 

For any reason if it still fails, let me know, and i should be able to help.

**Comment by jaypatel512** [comment]
Any update on this @korentins ?

Let me know if you were able to resolve this issue ?

**Comment by korentins** [comment]
Well, it was that.
I changed my credentials in the "sdk_config.ini" file but I didn't notice I had to change also in the bootstrap.php.
I should have understand before because I saw a lot of Web Experience Profiles I didn't created in the list.

**Comment by jaypatel512** [comment]
Oh yes. There are two ways to feed the configs into the SDK.

Btw, for more SDK specific information, you could read out the wiki here: https://github.com/paypal/PayPal-PHP-SDK/wiki

And almost all the interesting information is provided here: http://paypal.github.io/PayPal-PHP-SDK/
