### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by bkhaderbashashaikh** [paypal/PayPal-PHP-SDK#323]
Dearest
Need Support Response Cooperation
As Automatically on ur greatest humanitarian interesty

**Comment by jaypatel512** [comment]
Please follow your support issues in Paypal at https://ppmts.custhelp.com/. If you have any specific issue with PHP SDK, feel free to create an issue, that has specific information about the issue.

**Comment by bkhaderbashashaikh** [comment]
PayPal payment processing
