### ISSUE TITLE
Is it good practice ?

### ISSUE THREAD

**Issue by Tetdoss** [paypal/PayPal-PHP-SDK#324]
I have a question about my practice about API REST. I want to sell Points to a user, this is how i do that : 

		$paymentId = $request->query->get('paymentId');
		$execution = new PaymentExecution();
		$execution->setPayerId($request->query->get('PayerID'));
		try {
			$payment = Payment::get($paymentId, $apiContext);
			$result = $payment->execute($execution, $apiContext);

			// Payment completed ! Is it good to give bought points to the user here ?

		} catch (\Exception $ex) {
			$this->get('session')->getFlashBag()->set('danger', "Erreur : ".$ex->getMessage());
			return $this->redirect($this->generateUrl('wc_payment_acheter_wp'));
		}

Thanks !

**Comment by jaypatel512** [comment]
Hey @Tetdoss !

I think you got it right. However, I would recommend one more check just to confirm. When you `execute` a payment, you will get a payment resource back with `state` as `approved`. I think this could be a better check, where you can make sure that the payment went completely fine. There could be other states when executing in future, which makes this code future proof.

```php
    $paymentId = $request->query->get('paymentId');
    $execution = new PaymentExecution();
    $execution->setPayerId($request->query->get('PayerID'));
    try {
        $payment = Payment::get($paymentId, $apiContext);
        $result = $payment->execute($execution, $apiContext);
        if ($result->getState() == "approved") {
            // Payment completed ! Is it good to give bought points to the user here ?
        }
    } catch (\Exception $ex) {
        $this->get('session')->getFlashBag()->set('danger', "Erreur : ".$ex->getMessage());
        return $this->redirect($this->generateUrl('wc_payment_acheter_wp'));
    }

```

**Comment by Tetdoss** [comment]
Thank you ! That's what I thought !
