### ISSUE TITLE
Getting 400 error on creating call--

### ISSUE THREAD

**Issue by asrivastavcog** [paypal/PayPal-PHP-SDK#325]
Hi,

Any help is appreciated, I am getting the issues here using credit card payments --

Below is details that I got in response  from api --

PayPal\Exception\PayPalConnectionException Object
(
    [url:PayPal\Exception\PayPalConnectionException:private] => https://api.sandbox.paypal.com/v1/payments/payment
    [data:PayPal\Exception\PayPalConnectionException:private] => {"name":"UNKNOWN_ERROR","message":"An unknown error has occurred","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR","debug_id":"bc5f68a42abee"}
    [message:protected] => Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payment.
    [string:Exception:private] => 
    [code:protected] => 400
    [file:protected] => /var/www/html/payments/paypal-php-sdk/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php
    [line:protected] => 177
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /var/www/html/payments/paypal-php-sdk/paypal/rest-api-sdk-php/lib/PayPal/Transport/PayPalRestCall.php
                    [line] => 74
                    [function] => execute
                    [class] => PayPal\Core\PayPalHttpConnection
                    [type] => ->
                    [args] => Array
                        (
                            [0] => {"intent":"sale","payer":{"payment_method":"credit_card","funding_instruments":[{"credit_card":{"type":"visa","number":"4148529247832259","expire_month":"04","expire_year":"2017","cvv2":"211"}}]},"transactions":[{"amount":{"currency":"USD","total":"10"},"description":"creating a direct payment with credit card"}]}
                        )

                )

            [1] => Array
                (
                    [file] => /var/www/html/payments/paypal-php-sdk/paypal/rest-api-sdk-php/lib/PayPal/Common/PayPalResourceModel.php
                    [line] => 103
                    [function] => execute
                    [class] => PayPal\Transport\PayPalRestCall
                    [type] => ->
                    [args] => Array
                        (
                            [0] => Array
                                (
                                    [0] => PayPal\Handler\RestHandler
                                )

                            [1] => /v1/payments/payment
                            [2] => POST
                            [3] => {"intent":"sale","payer":{"payment_method":"credit_card","funding_instruments":[{"credit_card":{"type":"visa","number":"4148529247832259","expire_month":"04","expire_year":"2017","cvv2":"211"}}]},"transactions":[{"amount":{"currency":"USD","total":"10"},"description":"creating a direct payment with credit card"}]}
                            [4] => 
                        )

                )

            [2] => Array
                (
                    [file] => /var/www/html/payments/paypal-php-sdk/paypal/rest-api-sdk-php/lib/PayPal/Api/Payment.php
                    [line] => 424
                    [function] => executeCall
                    [class] => PayPal\Common\PayPalResourceModel
                    [type] => ::
                    [args] => Array
                        (
                            [0] => /v1/payments/payment
                            [1] => POST
                            [2] => {"intent":"sale","payer":{"payment_method":"credit_card","funding_instruments":[{"credit_card":{"type":"visa","number":"4148529247832259","expire_month":"04","expire_year":"2017","cvv2":"211"}}]},"transactions":[{"amount":{"currency":"USD","total":"10"},"description":"creating a direct payment with credit card"}]}
                            [3] => 
                            [4] => PayPal\Rest\ApiContext Object
                                (
                                    [requestId:PayPal\Rest\ApiContext:private] => Request1433744961
                                    [credential:PayPal\Rest\ApiContext:private] => PayPal\Auth\OAuthTokenCredential Object
                                        (
                                            [logger:PayPal\Auth\OAuthTokenCredential:private] => PayPal\Core\PayPalLoggingManager Object
                                                (
                                                    [loggerName:PayPal\Core\PayPalLoggingManager:private] => PayPal\Auth\OAuthTokenCredential
                                                    [isLoggingEnabled:PayPal\Core\PayPalLoggingManager:private] => 
                                                    [loggingLevel:PayPal\Core\PayPalLoggingManager:private] => 
                                                    [loggerFile:PayPal\Core\PayPalLoggingManager:private] => 
                                                )

                                            [clientId:PayPal\Auth\OAuthTokenCredential:private] => AQkquBDf1zctJOWGKWUEtKXm6qVhueUEMvXO_-MCI4DQQ4-LWvkDLIN2fGsd
                                            [clientSecret:PayPal\Auth\OAuthTokenCredential:private] => EL1tVxAjhT7cJimnz5-Nsx9k2reTKSVfErNQF-CmrwJgxRtylkGTKlU4RvrX
                                            [accessToken:PayPal\Auth\OAuthTokenCredential:private] => A015sjzBp1m9AH2WYb51IPRdkAcO1wfpoWFJDdtiv0KbyDI
                                            [tokenExpiresIn:PayPal\Auth\OAuthTokenCredential:private] => 28800
                                            [tokenCreateTime:PayPal\Auth\OAuthTokenCredential:private] => 1433744963
                                            [cipher:PayPal\Auth\OAuthTokenCredential:private] => PayPal\Security\Cipher Object
                                                (
                                                    [secretKey:PayPal\Security\Cipher:private] => EL1tVxAjhT7cJimnz5-Nsx9k2reTKSVfErNQF-CmrwJgxRtylkGTKlU4RvrX
                                                )

                                            [_propMap:PayPal\Common\PayPalModel:private] => Array
                                                (
                                                )

                                        )

                                )

                            [5] => 
                        )

                )

            [3] => Array
                (
                    [file] => /var/www/html/payments/paypalpaynew.php
                    [line] => 62
                    [function] => create
                    [class] => PayPal\Api\Payment
                    [type] => ->
                    [args] => Array
                        (
                            [0] => PayPal\Rest\ApiContext Object
                                (
                                    [requestId:PayPal\Rest\ApiContext:private] => Request1433744961
                                    [credential:PayPal\Rest\ApiContext:private] => PayPal\Auth\OAuthTokenCredential Object
                                        (
                                            [logger:PayPal\Auth\OAuthTokenCredential:private] => PayPal\Core\PayPalLoggingManager Object
                                                (
                                                    [loggerName:PayPal\Core\PayPalLoggingManager:private] => PayPal\Auth\OAuthTokenCredential
                                                    [isLoggingEnabled:PayPal\Core\PayPalLoggingManager:private] => 
                                                    [loggingLevel:PayPal\Core\PayPalLoggingManager:private] => 
                                                    [loggerFile:PayPal\Core\PayPalLoggingManager:private] => 
                                                )

                                            [clientId:PayPal\Auth\OAuthTokenCredential:private] => AQkquBDf1zctJOWGKWUEtKXm6qVhueUEMvXO_-MCI4DQQ4-LWvkDLIN2fGsd
                                            [clientSecret:PayPal\Auth\OAuthTokenCredential:private] => EL1tVxAjhT7cJimnz5-Nsx9k2reTKSVfErNQF-CmrwJgxRtylkGTKlU4RvrX
                                            [accessToken:PayPal\Auth\OAuthTokenCredential:private] => A015sjzBp1m9AH2WYb51IPRdkAcO1wfpoWFJDdtiv0KbyDI
                                            [tokenExpiresIn:PayPal\Auth\OAuthTokenCredential:private] => 28800
                                            [tokenCreateTime:PayPal\Auth\OAuthTokenCredential:private] => 1433744963
                                            [cipher:PayPal\Auth\OAuthTokenCredential:private] => PayPal\Security\Cipher Object
                                                (
                                                    [secretKey:PayPal\Security\Cipher:private] => EL1tVxAjhT7cJimnz5-Nsx9k2reTKSVfErNQF-CmrwJgxRtylkGTKlU4RvrX
                                                )

                                            [_propMap:PayPal\Common\PayPalModel:private] => Array
                                                (
                                                )

                                        )

                                )

                        )

                )

            [4] => Array
                (
                    [file] => /var/www/html/payments/paypalpaynew.php
                    [line] => 252
                    [function] => directpayusingcard
                    [args] => Array
                        (
                            [0] => Array
                                (
                                    [cardtype] => visa
                                    [cardno] => 4148529247832259
                                    [expiry_month] => 04
                                    [cvv] => 211
                                    [expiry_year] => 2017
                                    [currency] => USD
                                    [total] => 10
                                    [first_name] => Abhishek
                                    [last_name] => Srivastav
                                )

                            [1] => Array
                                (
                                    [mode] => sandbox
                                )

                        )

                )

        )

    [previous:Exception:private] => 
)

**Comment by sanjeev1991** [comment]
Same issue founded recently on my app
Error : Got Http response code 400 when accessing

**Comment by jziaja** [comment]
There appears to be an issue with the Payments API on sandbox with respect to processing credit cards.  We're tracking this issue over on the .NET SDK repo: **[PayPal-NET-SDK Issue#104](https://github.com/paypal/PayPal-NET-SDK/issues/104)**.
