### ISSUE TITLE
Merchant Return URL and sample cancel billing.

### ISSUE THREAD

**Issue by alien3d** [paypal/PayPal-PHP-SDK#327]
Merchant return url work fine upon return one single variable  but will not work upon mutiple value. If seem decoding the extra  variable

E.g
x.com?success= true work
x.com?success=true&message=hai&securityToken=xyz not work 
it would output like
x.com?success=true=message%3dhai%26securityToken%3dxyz&token=true

I cannot see some sample upon cancelling billing. Which much better ? cancel or suspend the account ?

**Comment by jaypatel512** [comment]
Hey @alien3d !

I am not able to reproduce this issue. I updated the sample in my machine of ["CreatePlan.php"](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/billing/CreatePlan.php#L50) to have multiple such variables, and ran ["Create Billing Agreement Using PayPal"](http://paypal.github.io/PayPal-PHP-SDK/sample/#billing), it seem to work just fine. As shown in the URL image below, I got the "jay=patel" back with "success=true".

![screen shot 2015-06-09 at 12 03 55 pm](https://cloud.githubusercontent.com/assets/1309895/8064360/d0813dcc-0e9f-11e5-838a-eab522f1550e.png)

**Comment by alien3d** [comment]
I try back i'm unsure what happening.. It's work fine..  Sometimes my line is slow or disconnect some of the object i have to check is_object(). Need to test more on this problem myself.
