### ISSUE TITLE
What is the equivalent of discount_rate in this API ?

### ISSUE THREAD

**Issue by Xety** [paypal/PayPal-PHP-SDK#329]
Hello,

How can i set a discount/reduction (percentage or the amount of the discount) to the Item or to the total of the transaction please ?

I didn't see anything about that in the doc or in the API itself. With the classic API it was `discount_rate`.

**Comment by jaypatel512** [comment]
Hey @Xety !

There is no direct equivalent of discount_rate right now, however, your request makes sense. I will ask Payments API team to see if they have something similar in plan, and if not create a feature request for this.

However for now, you could create a new item in the item_list with negative value to provide the amount of discount, and you should be able to show that. 

Here are few snapshots to demonstrate that:

![screen shot 2015-06-15 at 11 51 44 am](https://cloud.githubusercontent.com/assets/1309895/8165300/f49d967e-1354-11e5-8242-4454eca05eee.png)
![screen shot 2015-06-15 at 11 51 33 am](https://cloud.githubusercontent.com/assets/1309895/8165301/f70fc83c-1354-11e5-85a9-f08861f37e19.png)


And here is the sample code: 

```php
...
// ### Itemized information
// (Optional) Lets you specify item wise
// information
$item1 = new Item();
$item1->setName('Ground Coffee 40 oz')
    ->setCurrency('USD')
    ->setQuantity(1)
    ->setSku("123123") // Similar to `item_number` in Classic API
    ->setPrice(7.5);
$item2 = new Item();
$item2->setName('Granola bars')
    ->setCurrency('USD')
    ->setQuantity(5)
    ->setSku("321321") // Similar to `item_number` in Classic API
    ->setPrice(2);

$item3 = new Item();
$item3->setName('Discounts')
    ->setCurrency('USD')
    ->setQuantity(1)
    ->setPrice(-2);

$itemList = new ItemList();
$itemList->setItems(array($item1, $item2, $item3));
...
```

**Comment by Xety** [comment]
Thanks for your reply !

That would be awesome if it can be implemented in the API !

Also, that's a nice hack, i will use this hack until the function will be implemented, thanks you !

**Comment by jaypatel512** [comment]
Great to know. Closing the issue for now.
