### ISSUE TITLE
Missing support for express checkout SOLUTIONTYPE option

### ISSUE THREAD

**Issue by lifeisfoo** [paypal/PayPal-PHP-SDK#331]
Without this option isn't possible to emulate the classic api's express checkout: the payment without paypal account, using a credit card directly, isn't available for the user.

Get as example:
http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/CreatePaymentUsingPayPal.html

Note that I'm in a country (Italy) where direct credit card processing using api isn't available, so this is the only way that we have to accept credit card without paypal account. See https://developer.paypal.com/docs/integration/direct/rest_api_payment_country_currency_support/#direct-credit-card-payments

**Comment by jaypatel512** [comment]
I am not sure if I completely understood your question. 

However, you could do a direct credit card payment using the example shown here: http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/CreatePayment.html

**Comment by lifeisfoo** [comment]
Direct credit card payment isn't available in my country (see the link above). 

The the only way to allow credit card payment (without paypal account) is to use express checkout with the 'SOLUTIONTYPE=Sole' option.

Using rest api isn't possible to send this option.

**Comment by ppmtscory** [comment]
@lifeisfoo If the guest checkout option is available in your country, then it should be enabled by default.  You can also adjust the landing page, similar to classic express checkout, via the [flow_config](https://developer.paypal.com/webapps/developer/docs/api/#flowconfig-object) object of the [Payment Experience](https://developer.paypal.com/webapps/developer/docs/api/#payment-experience) profiles.  Do you have an example of where it's not showing the option to pay with just credit/debit card without a PayPal account?

**Comment by lifeisfoo** [comment]
You're right: switching from the sandbox to the live environment fix the problem (the option was disabled in my sandbox account).

Thank you
