### ISSUE TITLE
Is there a way to change the Plan for Agreement?

### ISSUE THREAD

**Issue by dyenair** [paypal/PayPal-PHP-SDK#334]
Hi!

I was trying to change the plan amount and interval if possible, in short UPGRADES.
e.g: I have 3 plans. Monthly, Quarterly and Yearly. And the user realized that he wants to upgrade his subscription of yearly basis. 

Would it be possible using this SDK? I was thinking of recreating the agreement but I'm sure there is much better solution. 

Thank you!

**Comment by jaypatel512** [comment]
Currently, the only solution is to recreate an agreement. We are trying to implement a way to do that without re-creating, but currently, agreement only supports one plan during creation, and cannot be changed.
