### ISSUE TITLE
Make future payments without mobile SDK

### ISSUE THREAD

**Issue by msvrtan** [paypal/PayPal-PHP-SDK#335]
Hi,

Is it possible to do future payments without using mobile SDK? I'we found http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/CreateFuturePayment.html but it expects permanent refresh token and meta data ID to come from mobile SDK. 

Can this be done without mobile app? I'm looking into identity OAuth2.0 but not sure if that is correct way to grab that info?

**Comment by jaypatel512** [comment]
No. The idea of future payments include mobile to create a consent, that allows the server to generate refresh token, and make future payments.

So, basically, it requires you to have a mobile SDK for generating future payments.
