### ISSUE TITLE
PlanList - Approved Plans

### ISSUE THREAD

**Issue by harshalpatel** [paypal/PayPal-PHP-SDK#338]
Plan list works fine for showing plans in CREATED state; it does not return plans in ACTIVE state.

I have confirmed the active plan exists by creating a billing agreement against it.

**Comment by harshalpatel** [comment]
Looks like by default it only shows plans in CREATED state; you have to pass in ACTIVE as a param if you want to see active plans.

By default it should show all.

**Comment by jaypatel512** [comment]
Hey @harshalpatel ! 

According to developer docs, https://developer.paypal.com/webapps/developer/docs/api/#list-plans the default value is set to created. I agree however, that it would be more sensible to make it to show all. 

I will send the request to internal api team anyway.
