### ISSUE TITLE
Question: Agreements

### ISSUE THREAD

**Issue by harshalpatel** [paypal/PayPal-PHP-SDK#340]
For a certain plan, I cannot find a way to show all agreements referencing that plan. Is this possible?

Don't see any functions that would work in the class definition.

One possible way to accomplish this is to show all agreements; the agreement class can then return the plan it's attached to.

Show all agreements could works similar to list plans.

**Comment by jaypatel512** [comment]
Hey @harshalpatel !

Currently there is no filtering available to retrieve agreements created by a single plan. The feature is already in pipeline, but is not getting released anytime soon. I think show all agreements would be a viable solution here. 

Also, for similar questions, I think you would get a much faster and detailed response from "stackoverflow" where many of our PayPal developers are helping each other out. However, if you run into a specific bug inside the SDK, feel free to create an issue here. 

Thanks.
