### ISSUE TITLE
 SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by Newbie012** [paypal/PayPal-PHP-SDK#342]
When I try to create a payment, I receive the error "SSL certificate problem: unable to get local issuer certificate"

**Comment by jaypatel512** [comment]
Can you please share more information about this error. What version you are using ? What machine is it on ? And what SSL version you have in your machine. 

I am not able to reproduce this setup currently in my machine.

**Comment by jaypatel512** [comment]
Any updates @Newbie012 ?

**Comment by Newbie012** [comment]
Well Apparently, the cause of  the problem was my ISP. it turns out my ISP is blocking inappropriate sites. and to check on SSL sites, their programmers probably don't know how to program so it caused "MITM Attack". I called them to turn off the protection on SSL Sites and it worked.

**Comment by jaypatel512** [comment]
Oh great. Good to know it got resolved :)
