### ISSUE TITLE
not receive any fees when paying via credit card

### ISSUE THREAD

**Issue by googlle** [paypal/PayPal-PHP-SDK#344]
I'm testing accepting payments using the php sdk in the sandbox. Do not receive any fees when paying via credit card.

Is this a known bug?

**Comment by googlle** [comment]
When I use type paypal, I get this info
```php
[related_resources] => Array
(
	[0] => PayPal\Api\RelatedResources Object
	(
		[_propMap:PayPal\Common\PayPalModel:private] => Array
		(
			[sale] => PayPal\Api\Sale Object
			(
				[_propMap:PayPal\Common\PayPalModel:private] => Array
				(
					[id] => xxxxxxxxxxxxxxxxx
					[create_time] => 2015-06-29T07:47:44Z
					[update_time] => 2015-06-29T07:48:47Z
					[amount] => PayPal\Api\Amount Object
					(
						[_propMap:PayPal\Common\PayPalModel:private] => Array
						(
							[total] => 100.00
							[currency] => USD
						)
					)

					[payment_mode] => INSTANT_TRANSFER
					[state] => pending
					[reason_code] => PAYMENT_REVIEW
					[protection_eligibility] => INELIGIBLE
					[parent_payment] => PAY-xxxxxxxxxxxxxxxxxxxxxxx
					[transaction_fee] => PayPal\Api\Currency Object
					(
						[_propMap:PayPal\Common\PayPalModel:private] => Array
						(
							[value] => 4.20
							[currency] => USD
						)

					)
				)
			)
		)
	)
)
```

**Comment by googlle** [comment]
In sandbox mode when paying with a credit card, not charging money off my account

**Comment by jaypatel512** [comment]
Hey @googlle !

In sandbox mode, the amount is not really charged from the account, but you will be able to see the transaction that happened. It is done to keep the balance on these credit cards all the time. 

About your previous question, I have asked the internal team, and I should have an answer for that real soon.

**Comment by jaypatel512** [comment]
Ticket ID for Internal Tracking: PPTIPS-2139

**Comment by googlle** [comment]
hi @jaypatel512!
Hi. When will I get the answer?
Already 20 days have passed

**Comment by jaypatel512** [comment]
Hey @googlle !

I am trying to push the API team to respond on this immediately. However, please do understand that it may take some time for internal team to push this fix. However, I will definitely try to expedite this request.

**Comment by jaypatel512** [comment]
Hey @googlle ! 

I have received the confirmation from the internal team, and they are going to add this new feature based on their team priority. I do not have much say in that, however, you could reach out to [Merchant Technical Support](https://www.paypal-techsupport.com/app/ask) to expedite this request. 

We will make a release as soon as this feature has been added to the API.
