### ISSUE TITLE
Can't pay using sandbox

### ISSUE THREAD

**Issue by waiylgeek** [paypal/PayPal-PHP-SDK#350]
Hello,

Why can't I testing payment with my developer account using the sandbox? Is it mandatory to have a real activated Paypal account?

**Comment by jaypatel512** [comment]
No, it is not mandatory to have paypal account verified, however, you need  a working developer account at https://developer.paypal.com/developer/applications

Once you have that, you could follow instructions provided at : https://github.com/paypal/PayPal-PHP-SDK/wiki
