### ISSUE TITLE
Keep On Getting Internal Service Error When Trying to Get Payment Url

### ISSUE THREAD

**Issue by yosus** [paypal/PayPal-PHP-SDK#351]
Hi guys,

I keep on getting this internal_service_error. I am using the PHP-SDK and making a Payment->create() call.

object(PayPal\Exception\PayPalConnectionException) {
	[protected] message => 'Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment.'
	[protected] code => (int) 500
	[protected] file => '/xxx/Core/PayPalHttpConnection.php'
	[protected] line => (int) 178
	[private] url => 'https://api.sandbox.paypal.com/v1/payments/payment'
	[private] data => '{"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"9c1f62ddf136d"}'
}

**Comment by yosus** [comment]
Nvm . I found the issue. It was because the payment method was set to 'credit_card' without any credit card info. It should be set to 'paypal'. Hope this will help in creating a better error-message.


Thanks

**Comment by jaypatel512** [comment]
I definitely agree with you. It should have sent you a proper error response for this. I will test it out myself, and ask the API team to add a new error message soon.
