### ISSUE TITLE
Change Auto billing amount

### ISSUE THREAD

**Issue by dyenair** [paypal/PayPal-PHP-SDK#352]
Hi! 

I would like to ask using this SDK, For the executed agreement - I would like to update the Auto billing to "Yes" if somehow the client would like to update it's subscription to auto. Here is the flow of my code.

1. Create Plan
2. Activate Plan
3. Create Agreement
4. Execute agreement
(after a some time client wants to make it automatic)
5. Update agreement from auto billing amount "NO" to "YES"

I tried to use the update agreement passing this request data

[{"op":"replace","path":"/","value":{"override_merchant_preferences":{"auto_bill_amount":"no"}}}]

unfortunately, this is the response

[{"field":"override_merchant_preferences","issue":"patch is not supported for this field."}]

Thank you for your help!

**Comment by jaypatel512** [comment]
I got a response from the subscription API team. currently, there is no support to update the field via patch request. 

The only best option we have currently is to re-create a new agreement.
