### ISSUE TITLE
Shipping discount

### ISSUE THREAD

**Issue by jcerrada** [paypal/PayPal-PHP-SDK#353]
Hi,

I was checking out one of the examples of your website regarding "Payment capabilities" (https://developer.paypal.com/webapps/developer/docs/integration/direct/explore-payment-capabilities/) and I realized that the payment details don't add up the total amount:
subtotal  + tax + shipping + handling_fee - shipping_discount + insurance = 30 + 0.07 + 1 + 1 -1 + 1 = 32.07
total = 34.07
They don't match or maybe I miss something, because in my local environment  I can't get it to work, even thou both quantities match (in my local environment). It only works when I don't have any shipping discount.

Here it is an example of my problem:

```json
curl -v https://api.sandbox.paypal.com/v1/payments/payment \
-H "Content-Type:application/json" \
-H "Authorization: Bearer <Access-Token>" \
-d '{
    "intent": "sale",
    "redirect_urls": {
        "return_url": "http://www.return.com",
        "cancel_url": "http://www.cancel.com"
    },
    "payer": {
        "payment_method": "paypal",
        "payer_info": {
            "tax_id_type": "BR_CPF",
            "tax_id": "Fh618775690"
        }
    },
    "transactions": [
        {
            "amount": {
                "total": "30.07",
                "currency": "USD",
                "details": {
                    "subtotal": "30.00",
                    "tax": "0.07",
                    "shipping": "1.00",
                    "shipping_discount": "1.00"
                }
            },
            "description": "This is the payment transaction description.",
            "custom": "EBAY_EMS_90048630024435",
            "invoice_number": "48787589677",
            "payment_options": {
                "allowed_payment_method": "INSTANT_FUNDING_SOURCE"
            },
            "soft_descriptor": "ECHI5786786",
            "item_list": {
                "items": [
                    {
                        "name": "bowling",
                        "description": "Bowling Team Shirt",
                        "quantity": "5",
                        "price": "3",
                        "tax": "0.01",
                        "sku": "1",
                        "currency": "USD"
                    },
                    {
                        "name": "mesh",
                        "description": "80s Mesh Sleeveless Shirt",
                        "quantity": "1",
                        "price": "15",
                        "tax": "0.02",
                        "sku": "product34",
                        "currency": "USD"
                    }
                ],
                "shipping_address": {
                    "recipient_name": "Betsy Buyer",
                    "line1": "111 First Street",
                    "city": "Saratoga",
                    "country_code": "US",
                    "postal_code": "95070",
                    "state": "CA"
                }
            }
        }
    ]
}'```

**Comment by jaypatel512** [comment]
In the above example, the shipping_discount is not accounted directly as negative. You have to explicitly mention "-1" for it to take effect. 

I will actually go ahead and ask the documentation team to update their sample to reflect it. however, still technically the sample stands correct. 

You could easily figure out the specific details by following the approval url, and viewing the information as shown below.
![screen shot 2015-07-10 at 12 31 07 pm](https://cloud.githubusercontent.com/assets/1309895/8624702/949cdf50-26ff-11e5-88b3-8af36994a8fb.png)

**Comment by jcerrada** [comment]
Thank you, you were right. Now I've made it all work. I just thought that since it is a discount, it'd be automatically subtracted from the shipping cost. Thanks again.

**Comment by jaypatel512** [comment]
I agree with you on that. I have forwarded that suggestion to Payments team, to see if that could be taken into consideration in future revisions of this API.
