### ISSUE TITLE
Negative testing

### ISSUE THREAD

**Issue by msvrtan** [paypal/PayPal-PHP-SDK#354]
Is it possible to do negative testing with PHP SDK?

https://developer.paypal.com/docs/classic/lifecycle/sb_error-conditions/ 

I'we enabled it for merchant acc, set Amount to 10001 or 100.01, tested with both merchant and customer acc and couldnt get any kind of error back.

**Comment by jaypatel512** [comment]
Hey  @msvrtan !

I have asked the internal team to confirm if rest API has a similar feature to classic API for negative testing. And if not, what is the solution.

**Comment by jaypatel512** [comment]
Hey @msvrtan !

I got a response from the internal REST API team. They mentioned that the negative testing framework is not yet completely developed for REST API. I have asked the team to help it expedite it. I will update you when I have more details.

Thanks,

**Comment by msvrtan** [comment]
Tnx for the info!

**Comment by tomwhipple** [comment]
It can also us help make the case for these features if developers request them directly with a [merchant support ticket](https://www.paypal-techsupport.com/app/ask). ;)

**Comment by jaypatel512** [comment]
Closing this issue, as this is an API technology improvement, and not SDK specific.
