### ISSUE TITLE
Error responses

### ISSUE THREAD

**Issue by rzfarrell** [paypal/PayPal-PHP-SDK#355]
I'm trying to develop a capture script and tried testing a larger than authorized amount. I just get this:

Got Http response code 400

Does the API not response with any kind of error messages so we might know what is wrong?  It seems that if there is any error it just provides a 400 response code.

**Comment by jaypatel512** [comment]
Yes you can my friend @rzfarrell ! 

We have a specific exception class that holds more information about what went wrong. You can follow the wiki page talking about the [PayPalConnectionException](https://github.com/paypal/PayPal-PHP-SDK/wiki/exception-%27PayPal%5CException%5CPayPalConnectionException%27-with-message-%27Got-Http-response-code-400-when-accessing)

**Comment by jaypatel512** [comment]
Please re-open the issue if the error message is something that you didnt expect.
