### ISSUE TITLE
Capture a PayPal Payment Authorization

### ISSUE THREAD

**Issue by claudio-dalicandro** [paypal/PayPal-PHP-SDK#356]
How can I capture a paypal authorization subsequently if the  payment object has no references to authorization itself?

I followed your documentation [here](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/AuthorizePaymentUsingPayPal.php), but on the way back from the paypal site the only id I have is the payment id, and no way to get the authorization.

In addition I am forced to wait for paypal redirection because even having recorded a webhook for the authorization I still don't get any post from paypal...

**Comment by jaypatel512** [comment]
I would recommend you setting up the samples provided in the SDK by following instructions [here](https://github.com/paypal/PayPal-PHP-SDK/wiki/Samples). 

As per the sample you would see that once you get a PaymentId back from the URL, you will be able to execute on the Payment similar to a normal sale payment, as shown [here](http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/ExecutePayment.html)

And about the webhook Issue, are you able to receive any webhook ? Were you able to follow the instructions provided [here](https://github.com/paypal/PayPal-PHP-SDK/wiki/Webhook-Validation)

**Comment by jaypatel512** [comment]
Please re-open if that doesnt answer your question.
