### ISSUE TITLE
Updating PAYPAL API issues

### ISSUE THREAD

**Issue by 123bbuingbbuing** [paypal/PayPal-PHP-SDK#357]
hi! i updated my paypal API because i used an outdated API with my project, sending payments to paypal works perfectly fine but when i have to do the payment execution where the paypal deducts the amount, it always give me a "getTransactionFee() does exist" response. So i updated my API with the newest release. But it still not work. it gives me null response so itried testing it with chrome's app Advance Rest Client. But it only give me this response and headers

Status
500 Internal Server Error Show explanation Loading time: 6641
Request headers 
CSP: active
Origin: chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36
Content-Type: application/x-www-form-urlencoded 
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8,fil;q=0.6
Response headers 
Date: Tue, 21 Jul 2015 05:42:44 GMT 
Server: Apache/2.4.7 (Ubuntu) 
X-Powered-By: PHP/5.5.9-1ubuntu4.11
Content-Length: 0 
Connection: close
Content-Type: text/html; charset=UTF-8 

response: Response does not contain any data.

i hope you could help me with this. it's my first time integrating Paypal's API with my website

**UPDATE:** i am having problem with this part:

```$paymentExecution = new PaymentExecution();
$paymentExecution->setPayer_id( unserialize(  $_POST['PayerID'])  );```

**Comment by jaypatel512** [comment]
As shown in the sample here: http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/ExecutePayment.html

You need to use `setPayerId` method for any SDK release after 1.*, as the `_` convention was deprecated and removed in 1.* versions.

You could also run the above sample using the instructions here: https://github.com/paypal/PayPal-PHP-SDK/wiki/Samples

More information: http://paypal.github.io/PayPal-PHP-SDK/

**Comment by 123bbuingbbuing** [comment]
hahaha OMG XD i kept on looking at the sample from the link you gave me. and i really don't get it. then I realized what is wrong with my code HAHAHAH I should use **setPayerId** instead of **setPayer_id** thank you so much for this response it really helped a lot!
