### ISSUE TITLE
Payment using Saved Credit Card doesn't work

### ISSUE THREAD

**Issue by laurentiustroia** [paypal/PayPal-PHP-SDK#358]
I follow example example from this link http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/CreatePaymentUsingSavedCard.html and i don't see in sandbox to take mony from my credit card, and receive this

`    ["id"]=>
    string(28) "PAY-2R983675G4870683PKWXGNXI"
    ["create_time"]=>
    string(20) "2015-07-21T15:35:57Z"
    ["update_time"]=>
    string(20) "2015-07-21T15:35:58Z"
    ["state"]=>
    string(8) "approved"
    ["links"]=>
    array(1) {
      [0]=>
      object(PayPal\Api\Links)#1490 (1) {
        ["_propMap":"PayPal\Common\PayPalModel":private]=>
        array(3) {
          ["href"]=>
          string(79) "https://api.sandbox.paypal.com/v1/payments/payment/PAY-2R983675G4870683PKWXGNXI"
          ["rel"]=>
          string(4) "self"
          ["method"]=>
          string(3) "GET"
        }
      }
    }`

Have state approved and info token from credid card seam to be ok but he don't do transaction why ?

**Comment by jaypatel512** [comment]
I would recommend running the [sample](https://github.com/paypal/PayPal-PHP-SDK/wiki/Samples) that you have provided for it. Setting it up is fairly easy. Once you have the localhost working, just click on "Payments using saved credit card" run button, and it would be able to show how the entire flow would look like. 

Let me know if that doesnt solve the issue you are seeing.
