### ISSUE TITLE
Verifying a Card Without Purchase

### ISSUE THREAD

**Issue by re1naldo** [paypal/PayPal-PHP-SDK#360]
Is it possible to verify a credit card without purchase ($0 Auths) using REST API (like [DoDirectPayment API](https://developer.paypal.com/docs/classic/paypal-payments-pro/integration-guide/WPWebsitePaymentsPro/) does)? Is there any example for this operation?

**Comment by jaypatel512** [comment]
Currently no such feature is available in REST API. However, I will pass along the feature request to API team.
