### ISSUE TITLE
Unknown error when trying to authorize a credit card payment

### ISSUE THREAD

**Issue by adamclayd** [paypal/PayPal-PHP-SDK#361]
I tried to create a payment to authorize a credit card in sandbox. When creating the payment I get an exception with a message that says "An unknown error has occurred". It occurs when payment->create is called. The debug id is 241be24071816. The code is almost exactly like the example file https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/AuthorizePayment.php.

Can someone tell me what I can do to fix it?

**Comment by jziaja** [comment]
@adamclayd, can you try the call again using a different credit card number?  You can quickly generate a new card number by creating a new test sandbox account or by going [here](https://www.paypal-techsupport.com/app/answers/detail/a_id/750).

**Comment by jaypatel512** [comment]
Also, could you try running the sample code that already exists, by running it on your local machine. The instructions are extremely simple, and provided [here](https://github.com/paypal/PayPal-PHP-SDK/wiki/Samples)

Let me know if that also fails for you. I just tested it, and it works great.

**Comment by adamclayd** [comment]
I tried a different card and it appeared to work. I found a list of test numbers to use at https://www.paypalobjects.com/en_US/vhelp/paypalmanager_help/credit_card_numbers.htm and I was trying to use 4111111111111111 and it was throwing that exception work but 4012888888881881 seemed to work

**Comment by jaypatel512** [comment]
Generally this happens because if one credit card that is used extremely gets flagged via RISK teams, and throttling, causing these errors. Closing the issue.
