### ISSUE TITLE
Too Many Requests error

### ISSUE THREAD

**Issue by steelbrain** [paypal/PayPal-PHP-SDK#363]
I was looking through the Paypal API docs and couldn't find anything for the code `RATE_LIMIT_REACHED`. You guys work at Paypal so I figured you would know. I have spinned up a new Vultr Server like a few hours ago, and Paypal API isn't working at all for me, this is the exception that I see
```
{"message":"Too many requests. Blocked due to rate limiting.","informationLink":"https://developer.paypal.com/docs/api/#RATE_LIMIT_REACHED","name":"RATE_LIMIT_REACHED","debugId":"c02f80d9c7e60"}
```
How do I fix that?

**Comment by jaypatel512** [comment]
Seems like for some reason, you may have called far too many calls. This may also happen if for some reason the security analysis trigger a flag or something. No worries, Just contact [Paypal Technical Support Team](https://www.paypal-techsupport.com/app/ask/session/L3RpbWUvMTQzNzcwODYyMy9zaWQvZllOa083c20%3D) and they would be able to help you out.

**Comment by steelbrain** [comment]
Will try there, Thanks!

**Comment by jaypatel512** [comment]
Also, I am not sure if that helps, but try creating a new app and see if you are seeing the same result.
