### ISSUE TITLE
SSL connect error

### ISSUE THREAD

**Issue by emandtf** [paypal/PayPal-PHP-SDK#364]
From 12 hours I'm not able to connect to PayPal Server via REST API on PHP.
I know PayPal has changed many SSL certificates.
My website is hosted on a Server but I have not access to Apache configuration.
I suppose my Hoster still using old certificates.

How can I solve this issue?
Is there a CURL option to choose the right certificate in runtime?
Which certificare should I need to use/add for REST API - Instant Payments (Live and Sandbox)?

**Comment by jaypatel512** [comment]
Generally updating the SDK to latest version should solve the problem. Let me know if you could try downloading the newest release of our SDK, and see if that resolves the issue.

**Comment by emandtf** [comment]
Hello.
Thank you for the answer but I'm already using latest 1.5.0 version. The problem has started to occurs the day after PayPal communication in which they said to have changed/disabled old SSL certificates, so it's not a coincidence.

**Comment by jaypatel512** [comment]
I am trying to reproduce this issue on my end, and I am failing to do so. I tried [running the samples](https://github.com/paypal/PayPal-PHP-SDK/wiki/Samples) provided in the SDK, and I am able to run them successfully. 

I am trying to figure out internally exactly which all certificates were changed, but in the mean time, can you please try and see if the samples are working fine locally in your machine ? That will help us eliminate any issues we may have directly with hosting server.

**Comment by tomwhipple** [comment]
In some cases OS provided SSL libraries are used. (I believe that's true for PHP) You'll want to make sure that those libraries are up to date as well. 

There are some curl options to specify SSL/TLS protocol versions, but it is generally a bad idea to hardcode them since the default is generally secure and kept up to date.

Here's what I see:
```
$ curl -v https://api.paypal.com
* Rebuilt URL to: https://api.paypal.com/
* Hostname was NOT found in DNS cache
*   Trying 173.0.84.98...
* Connected to api.paypal.com (173.0.84.98) port 443 (#0)
* TLS 1.2 connection using TLS_RSA_WITH_AES_256_CBC_SHA256
* Server certificate: api.paypal.com
* Server certificate: VeriSign Class 3 Secure Server CA - G3
* Server certificate: VeriSign Class 3 Public Primary Certification Authority - G5
> GET / HTTP/1.1
> User-Agent: curl/7.37.1
> Host: api.paypal.com
> Accept: */*
```

The important bit is: `TLS 1.2 connection using TLS_RSA_WITH_AES_256_CBC_SHA256`

Also important is to see that the root certificate is the Verisign Class 3 G5.

**Comment by emandtf** [comment]
Could the problem be the old CURL 7.19.x version of my Hosting Server?

**Comment by emandtf** [comment]
CURL executed on my local PC gives this result:
$ curl -v https://api.paypal.com
* Rebuilt URL to: https://api.paypal.com/
*   Trying 173.0.84.98...
* Connected to api.paypal.com (173.0.84.98) port 443 (#0)
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* TLSv1.2 (OUT), TLS Unknown, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, Server hello (2):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

**Comment by emandtf** [comment]
Finally I've solved main issue using "CURLOPT_SSLVERSION => 4" instead of "CURLOPT_SSLVERSION => 1" as suggested in the Paypal's ReadMe file.
When I use "CURLOPT_SSLVERSION => 0" is there a way to check if the PHP's CURL Connection is done using TLS? Because if I set it to "0" or "4" it works, but if I set to "1" it doesn't work...so I would like to be sure to avoid an unsecure connection when I use "CURLOPT_SSLVERSION => 0".

For CURL command-line issue: I should added "--cacert /home/.../ca-bundle.crt" at each call or I cannot connect to any HTTPS websites.

**Comment by tomwhipple** [comment]
I'm not certain, but it I think your curl may not be finding the local certificate trust store. Somewhere on your machine, there's a list of CA certificates. These are the root certs that are known to belong to the certificate authority. Usually they are distributed with the OS, and are kept up to date with the normal security patch process.

If, for instance, you're running Windows and install a separate curl package, it might not be as straightforward. (And as a Mac/Linux user, I know much less about that platform)

**Comment by jaypatel512** [comment]
I think the issue seem to be related to the installed curl version on your operating system. Updating that to latest version should rectify this issue without manual changes to SDK itself. 

As you mentioned at the end, you had to add cacert location for all curl request manually, which seems to be the cause of this issue. You may have to configure curl accordingly, such that it picks that location automatically.
