### ISSUE TITLE
Payment creation doesn't work on production - empty response

### ISSUE THREAD

**Issue by CodeBrauer** [paypal/PayPal-PHP-SDK#365]
I'm just facing that problem for hours. This complete app works locally (`OSX/MAMP/modphp/PHP 5.5.18`) but for some reason on the production server the payment creation fails: White/Empty response. No Exception, no max_execution time limit reached also HTTP 200. PHP, Paypal SDK and Apache logs are just fine and also there are no errors on the screen. - Pay

Everything before $payment->create($this->apiContext); gets executed - after that line the result is blank page.

The production server runs `Ubuntu 14.04 / Apache 2.4.7 / modphp / PHP 5.5.9`

That is my config:
```php
$this->apiContext->setConfig([
            // 'mode'           => 'live',
            'mode'           => 'sandbox',
            'log.LogEnabled' => true,
            'log.FileName'   => 'PayPal.log',
            'log.LogLevel'   => 'FINE'
        ]);
```
Here is the code:
```php
public function create($data)
{
    $payer = new Payer();
    $payer->setPaymentMethod("paypal");

    $total    = 0.0;
    $shipping = 0.0;
    foreach ($data as $key => $value) {
        $item = new Item();
        $item->setName($value->name)
            ->setDescription($value->type)
            ->setCurrency(Option::get('general-settings', 'currency'))
            ->setQuantity($value->amount)
            ->setPrice($value->price);

        $items[] = $item;
        $total += $value->price * $value->amount;
    }

    if ($total < 100) {
        $shipping += 10;
    }

    $itemList = new ItemList();
    $itemList->setItems($items);

    $details = new Details();
    $details->setShipping($shipping)
    ->setSubtotal($total);

    $amount = new Amount();
    $amount->setCurrency(Option::get('general-settings', 'currency'))
        ->setTotal($total+$shipping)
        ->setDetails($details);

    $transaction = new Transaction();
    $transaction->setAmount($amount)
        ->setItemList($itemList)
        ->setDescription("JustinRein Auftag")
        ->setInvoiceNumber(uniqid());

    $baseUrl = "http://example.ch";
    $redirectUrls = new RedirectUrls();
    $redirectUrls->setReturnUrl("$baseUrl/payment?success=true")
        ->setCancelUrl("$baseUrl/payment?success=false");

    $payment = new Payment();
    $payment->setIntent("sale")
        ->setPayer($payer)
        ->setRedirectUrls($redirectUrls)
        ->setTransactions(array($transaction));

    try {
        $payment->create($this->apiContext);

    } catch (Exception $ex) {
        td($ex);
        exit(1);
    }

    return $payment;
}
```
x-post: http://stackoverflow.com/questions/31704901/paypal-php-sdk-payment-creation-doesnt-work-on-production-empty-response

**Comment by jaypatel512** [comment]
Generally for the cases like this, it is the error that is specifically not shown based on server settings. Generally PHP does not print errors unless explicitly specified. This prevents from leaking any code. 

Anyway, the best way to figure out the issue for you would be to add these two lines at the top, and you should be able to see any specific error you may be having.

```php
error_reporting(E_ALL);
ini_set('display_errors', '1');
```

Also, you might want to look at catching a better exception [PayPalConnectionException](https://github.com/paypal/PayPal-PHP-SDK/wiki/exception-%27PayPal%5CException%5CPayPalConnectionException%27-with-message-%27Got-Http-response-code-400-when-accessing)

**Comment by CodeBrauer** [comment]
I will try to get it with PayPalConnectionException - display_errors is already on and by default I log every error. Will get back tommorow to this.

**Comment by jaypatel512** [comment]
Just a stupid question. From just the code you have provided. There is no printing of data when the $payment->create() happens. Do you wish to print the payment object ? or something else if the code successfully executes ? not sure if you have something in place that prints something on success.

**Comment by CodeBrauer** [comment]
I'm returning $payment to another method that provides me a JSON response for angular. (So I have the link for the redirect)

**Comment by CodeBrauer** [comment]
So, my errors reporting works.
- `throw new Exception("Error Processing Request", 1);` » script stops, exception printed.
- `die('debug exit');` **before** `$payment->create($apiContext);` » script stops, die printed.
- `die('debug exit');` **after** `$payment->create($apiContext);` » script stops, empty response. No errors on screen or logfiles.
- PayPalConnectionException also didn't catch anything.

**Comment by jaypatel512** [comment]
Can you please echo `$payment->toJSON()` before doing a create, and post the output. I am trying to see if I could replicate what payment object looks like.

**Comment by CodeBrauer** [comment]
Here is the [output](https://gist.githubusercontent.com/CodeBrauer/dab4de1c6466356db7cd/raw/7f2d7c7a5799d651526f8b741b7476ec11980d1d/toJSON_JustinRein.json)

**Comment by CodeBrauer** [comment]
Just solved the issue. It was an with "@" suppressed error from a third party library. Sometimes... I hate those PHP developers.

**Comment by jaypatel512** [comment]
Aah !! I understand your frustration. I am glad your issue is resolved though. Thanks for trying our SDK. Let me know if you have any further issues using the SDK, or any improvement you could think of.

**Comment by CodeBrauer** [comment]
Thanks for that great support and also for the fast responses!
