### ISSUE TITLE
Recurring payment with Initial Amount / charges

### ISSUE THREAD

**Issue by dyenair** [paypal/PayPal-PHP-SDK#366]
Hi! 

Just want to ask if SDK supports initial payment when creating Agreement? Because paypal have delay charging the paypal account most of the time more than 5hrs before it charge to their paypal user. 

If this is possible how am I going to do it? Should I include it on creating Plan? how?

Thank you!

**Comment by jaypatel512** [comment]
DUPLICATE: https://github.com/paypal/PayPal-PHP-SDK/issues/180
