### ISSUE TITLE
Payout 500 Internal service error

### ISSUE THREAD

**Issue by sanjeev1991** [paypal/PayPal-PHP-SDK#367]
I am facing issue with payout getting  "Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payouts?.". Unable to rectify this issue.  Please give a solutions for this.

My Script for payout
$payouts = new \PayPal\Api\Payout();
			
			$senderBatchHeader = new \PayPal\Api\PayoutSenderBatchHeader();
			$senderBatchHeader->setSenderBatchId($commonVar['unique_id'])->setEmailSubject('Contest Payout to writers'); 
			
			$payouts->setSenderBatchHeader($senderBatchHeader);
			foreach($postDatas as $postData){
				 
				$senderItem = new \PayPal\Api\PayoutItem();
				$senderItem->setRecipientType('Email')
				    ->setNote($postData['notes'])
				    ->setReceiver($postData['pay_email'])
				    ->setSenderItemId($postData['item_id'])
				    ->setAmount(new \PayPal\Api\Currency('{
				                        "value":"'.$postData['amount'].'",
				                        "currency":"USD"
				                    }'));
				$payouts->addItem($senderItem);
			} 
			$request = clone $payouts;
			try {
			    $response = $payouts->createSynchronous($this->apiContext); 
				//$response = $payouts->create(null, $this->apiContext); 
				$returnData['response'] = json_decode($response);
				$returnData['run'] = true;  
			} catch (Exception $ex) {
				echo "<pre>";
				print_r($ex); 
				$returnData['response'] = $ex->getMessage();
				$returnData['run'] = false;
			}
--------------------------------------------------------------------------------------------

See below Response from payout

PayPal\Exception\PayPalConnectionException Object
(
    [url:PayPal\Exception\PayPalConnectionException:private] => https://api.sandbox.paypal.com/v1/payments/payouts?sync_mode=true
    [data:PayPal\Exception\PayPalConnectionException:private] => {"name":"INTERNAL_ERROR","message":"An internal service error has occurred.","debug_id":"12523d3cbb7e","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_ERROR"}
    [message:protected] => Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payouts?sync_mode=true.
    [string:Exception:private] => 
    [code:protected] => 500
    [file:protected] => /home/beta/writemates/application/third_party/PayPal-PHP-SDK/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php
    [line:protected] => 177
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /home/beta/writemates/application/third_party/PayPal-PHP-SDK/paypal/rest-api-sdk-php/lib/PayPal/Transport/PayPalRestCall.php
                    [line] => 74
                    [function] => execute
                    [class] => PayPal\Core\PayPalHttpConnection
                    [type] => ->
                    [args] => Array
                        (
                            [0] => {"sender_batch_header":{"sender_batch_id":"00055b9dcae62a25","email_subject":"Contest payment"},"items":[{"recipient_type":"Email","note":"Paying for participation in contest. sdfdsf","receiver":"paypal-buyer@writemates.com","sender_item_id":"500013","amount":{"value":"45.00","currency":"USD"}}]}
                        )

                )

            [1] => Array
                (
                    [file] => /home/beta/writemates/application/third_party/PayPal-PHP-SDK/paypal/rest-api-sdk-php/lib/PayPal/Common/PayPalResourceModel.php
                    [line] => 103
                    [function] => execute
                    [class] => PayPal\Transport\PayPalRestCall
                    [type] => ->
                    [args] => Array
                        (
                            [0] => Array
                                (
                                    [0] => PayPal\Handler\RestHandler
                                )

                            [1] => /v1/payments/payouts?sync_mode=true
                            [2] => POST
                            [3] => {"sender_batch_header":{"sender_batch_id":"00055b9dcae62a25","email_subject":"Contest payment"},"items":[{"recipient_type":"Email","note":"Paying for participation in contest. sdfdsf","receiver":"paypal-buyer@writemates.com","sender_item_id":"500013","amount":{"value":"45.00","currency":"USD"}}]}
                            [4] => 
                        )

                )

            [2] => Array
                (
                    [file] => /home/beta/writemates/application/third_party/PayPal-PHP-SDK/paypal/rest-api-sdk-php/lib/PayPal/Api/Payout.php
                    [line] => 122
                    [function] => executeCall
                    [class] => PayPal\Common\PayPalResourceModel
                    [type] => ::
                    [args] => Array
                        (
                            [0] => /v1/payments/payouts?sync_mode=true
                            [1] => POST
                            [2] => {"sender_batch_header":{"sender_batch_id":"00055b9dcae62a25","email_subject":"Contest payment"},"items":[{"recipient_type":"Email","note":"Paying for participation in contest. sdfdsf","receiver":"paypal-buyer@writemates.com","sender_item_id":"500013","amount":{"value":"45.00","currency":"USD"}}]}
                            [3] => 
                            [4] => PayPal\Rest\ApiContext Object
                                (
                                    [requestId:PayPal\Rest\ApiContext:private] => Request1438244014
                                    [credential:PayPal\Rest\ApiContext:private] => PayPal\Auth\OAuthTokenCredential Object
                                        (
                                            [logger:PayPal\Auth\OAuthTokenCredential:private] => PayPal\Core\PayPalLoggingManager Object
                                                (
                                                    [loggerName:PayPal\Core\PayPalLoggingManager:private] => PayPal\Auth\OAuthTokenCredential
                                                    [isLoggingEnabled:PayPal\Core\PayPalLoggingManager:private] => 
                                                    [loggingLevel:PayPal\Core\PayPalLoggingManager:private] => 
                                                    [loggerFile:PayPal\Core\PayPalLoggingManager:private] => 
                                                )

                                            [clientId:PayPal\Auth\OAuthTokenCredential:private] => ARNio2OamLueaqzUyed3T-k5yw3zAcyuLou6NusoQDeLB-JnoBhc6es0ua66ZJqv3rVXl4RMtT5ATiWq
                                            [clientSecret:PayPal\Auth\OAuthTokenCredential:private] => EFCPhrFDvy4DJvi8NwgGleZfwIjj2WQdsUAyJ37pq77Di6GExTOOmXZy54EQbBwn2DiyiziiNZ_ai4If
                                            [accessToken:PayPal\Auth\OAuthTokenCredential:private] => A015EmbzjmB5Pwe.ojEmkpjUGOdHFGlTs7W58.MtPseAE6s
                                            [tokenExpiresIn:PayPal\Auth\OAuthTokenCredential:private] => 28800
                                            [tokenCreateTime:PayPal\Auth\OAuthTokenCredential:private] => 1438244015
                                            [cipher:PayPal\Auth\OAuthTokenCredential:private] => PayPal\Security\Cipher Object
                                                (
                                                    [secretKey:PayPal\Security\Cipher:private] => EFCPhrFDvy4DJvi8NwgGleZfwIjj2WQdsUAyJ37pq77Di6GExTOOmXZy54EQbBwn2DiyiziiNZ_ai4If
                                                )

                                            [_propMap:PayPal\Common\PayPalModel:private] => Array
                                                (
                                                )

                                        )

                                )

                            [5] => 
                        )

                )

            [3] => Array
                (
                    [file] => /home/beta/writemates/application/third_party/PayPal-PHP-SDK/paypal/rest-api-sdk-php/lib/PayPal/Api/Payout.php
                    [line] => 138
                    [function] => create
                    [class] => PayPal\Api\Payout
                    [type] => ->
                    [args] => Array

**Comment by jaypatel512** [comment]
DUPLICATE: https://github.com/paypal/PayPal-node-SDK/issues/102

**Comment by 1Pauletto** [comment]
I have the same issue

**Comment by juwlee** [comment]
@1Pauletto @sanjeev1991 Please try again and let us know if it still throws internal service error.

**Comment by sanjeev1991** [comment]
@jaypatel512  thanks for the time. 
Can you please let me what was the issue? was api issue or other things? 
btw thnks...

**Comment by juwlee** [comment]
@sanjeev1991 the issue was on API side, not on client side.
