### ISSUE TITLE
FormatConverter not working correctly

### ISSUE THREAD

**Issue by do-web** [paypal/PayPal-PHP-SDK#368]
If i set the current locale in php to de_DE the number is for example float(4,5) instead of float(4.2).
The FormatConverter::formatToPrice do not handle this correctly.
The values will be rounded.

**Comment by jaypatel512** [comment]
Hey @do-web ! I am trying to setup my machine to replicate what you are seeing. Can you please add a little bit more details to this issue ? 

I set the current locale by setting `setlocale(LC_ALL, 'de_DE');` Once done, I am trying to add the currency as EUR, and price as `1.23`, it is able to set that correctly. Am I missing something here ?

**Comment by do-web** [comment]
‘
   $item = new Item();
                        $item->setName("test")
                            ->setCurrency('EUR')
                            ->setQuantity(1)
                            ->setSku($ean)
                            ->setPrice(1.4);
                 

                    $itemList = new ItemList();
                    $itemList->setItems($items);

                    $details = new Details();
                    $details->setShipping(4.9)
                        ->setTax(0)
                        ->setSubtotal(1.4);

                    $amount = new Amount();
                    $amount->setCurrency("EUR")
                        ->setTotal(6.3)
                        ->setDetails($details);

‘

All values are rounded up in the paypal cart

**Comment by jaypatel512** [comment]
I think I was able to find the root cause of the issue. I would appreciate if you could do me a favor helping me fix this. Can you please make the below addition to our SDK code, and test if that fixes your problem. If it does, I would add more tests around it, and get the fix ready to be released sooner. Ability to verify with you would save me a lot of time.  
Please add these 3 lines in [FormatConverter.php Line 48 ](https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Converter/FormatConverter.php#L48)

```php
// Specific Locale Settings to change Decimal Points syntax
$LocaleInfo = localeconv();
$value = str_replace($LocaleInfo["mon_decimal_point"] , ".", $value);
```
This is how the method `formatToPrice` would look like after the addition:
```php

    public static function formatToPrice($value, $currency = null)
    {
        // Specific Locale Settings to change Decimal Points syntax
        $LocaleInfo = localeconv();
        $value = str_replace($LocaleInfo["mon_decimal_point"] , ".", $value);
        $decimals = 2;
        $currencyDecimals = array('JPY' => 0, 'TWD' => 0);
        if ($currency && array_key_exists($currency, $currencyDecimals)) {
            if (strpos($value, ".") !== false && (floor($value) != $value)) {
                //throw exception if it has decimal values for JPY and TWD which does not ends with .00
                throw new \InvalidArgumentException("value cannot have decimals for $currency currency");
            }
            $decimals = $currencyDecimals[$currency];
        } else if (strpos($value, ".") === false) {
            // Check if value has decimal values. If not no need to assign 2 decimals with .00 at the end
            $decimals = 0;
        }
        return self::formatToNumber($value, $decimals);
    }
```

**Comment by do-web** [comment]
This works

**Comment by jaypatel512** [comment]
:+1: !! Great !! 

I will go ahead and make some changes, and pass this on. Btw, Just out of curiosity, this should apply for  all numbers in our SDKs right ?

**Comment by jaypatel512** [comment]
Hey @do-web ! 

Just an update, we are visiting on this locale issue on all SDKs, and trying to come up with a plan to implement such feature in all our SDKs. I will not be making that addition just yet, but will do so as soon as we have a confirmation from the team. :)

**Comment by jaypatel512** [comment]
Hey @do-web ! 

After reviewing the option to add the way to automatically convert the price value, we decided that it would be beneficial if developers could do that on their integrations. This keeps both the incoming and outgoing format similar.

We may reconsider this if there are more requests for this in future.
