### ISSUE TITLE
Seller Protection disabled

### ISSUE THREAD

**Issue by Newbie012** [paypal/PayPal-PHP-SDK#370]
When I use the package, I don't have seller protection for the transactions. when I use a simple html form, I do have. What do I need to do to make Express Checkout with a Seller Protection?

**Comment by tomwhipple** [comment]
@Newbie012 unfortunately seller protection is more of a policy question rather than a feature of the PHP SDK. The [merchant support site](https://www.paypal-techsupport.com/) is probably a better forum to ask this question.
