### ISSUE TITLE
How to get transaction ID from Payment ID

### ISSUE THREAD

**Issue by steelbrain** [paypal/PayPal-PHP-SDK#375]
I tried digging through the docs, but couldn't find it :(
Payment ID: `PAY-9AT86720FS191832WKXELL3A`
How do I exchange it with the transaction ID?

**Comment by jaypatel512** [comment]
Here is a sample code snippet that could retrieve a sale (transaction) from a payment object. Do a GET payment before using this code:

```php
// ### Get Sale From Created Payment
// You can retrieve the sale Id from Related Resources for each transactions.
$transactions = $payment->getTransactions();
$relatedResources = $transactions[0]->getRelatedResources();
$sale = $relatedResources[0]->getSale();
$saleId = $sale->getId();
```

**Comment by steelbrain** [comment]
@jaypatel512 Sorry man, it didn't work, I have `8UB592132H977442K` in the `saleId` but `9CW939507K700494H` in Unique Express Checkout Transaction ID.

**Comment by jaypatel512** [comment]
Yes, that would be the sale Id. By transactionId you mean the Id that you see on the PayPal UI page right ? 

Here is what I saw.

![screen shot 2015-08-12 at 2 29 29 pm](https://cloud.githubusercontent.com/assets/1309895/9234576/42b4936c-40ff-11e5-8636-33d74d4d1167.png)


![screen shot 2015-08-12 at 2 29 42 pm](https://cloud.githubusercontent.com/assets/1309895/9234578/44fbf76e-40ff-11e5-9c6d-7bfb7fd9ed5f.png)

**Comment by steelbrain** [comment]
Thanks, I'll try that and report back!

**Comment by steelbrain** [comment]
I can confirm what you provided is correct.

**Comment by jaypatel512** [comment]
Great. :+1:

**Comment by shahankitb997** [comment]
How to get Payment ID from Transaction ID?

**Comment by maniJoe** [comment]
How to get Payment id from Transaction Id

**Comment by pp-randy** [comment]
@maniJoe I think you are looking for getParentPayment(), if you look up a Sale. 
https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Api/Sale.php#L463

**Comment by maniJoe** [comment]
@jaypatel512 
Is it possible to search transaction using **Item_number** or **Invoice_number**(not Invoice_ID) using SDK in java

**Comment by maniJoe** [comment]
@pp-randy
I got the parentPayment from Payment object .

**Comment by maniJoe** [comment]
@shahankitb997
In which technology are you working?
If java i can help you.

**Comment by maniJoe** [comment]
@pp-randy 
Is it possible to search transaction using Item_number or Invoice_number(not Invoice_ID) using SDK in java

**Comment by shahankitb997** [comment]
HI @maniJoe I already solve the Issue. Thanks for your concern. Using PHP

**Comment by maniJoe** [comment]
You are welcome @shahankitb997.

Is it possible to search transaction using Item_number or Invoice_number(not Invoice_ID)
