### ISSUE TITLE
Verifying Mobile Payment and Saving it in Database Server Approach

### ISSUE THREAD

**Issue by ashishsakarkar2020** [paypal/PayPal-PHP-SDK#379]
Hi,

I want to verify the mobile payment in my php web server. For this I have followed the steps from https://github.com/paypal/PayPal-PHP-SDK/wiki/Making-First-Call...

After making the necessary changes for my client id and secret key in bootstrap.php i am  trying to get the required details from http://mywebsite.com/PayPal-PHP-SDK/paypal/rest-api-sdk-php/sample/payments/GetPayment.php.I have tried this by hardcoding payment id of mobile payment. It works fine..

Should i call this link "http://mywebsite.com/PayPal-PHP-SDK/paypal/rest-api-sdk-php/sample/payments/GetPayment.php" from my mobile app and pass payment id to this url.

Then after verifying the details of app and web in GetPayment.php i will save the details in database in the same page. Is this approach correct?

**Comment by jaypatel512** [comment]
Anything under samples directory is just for understanding purpose, and should not be used directly on live. They have no security aspect to it, e.g. server side scripting hacks, escaping data, etc. 

You could however almost copy paste the same code to get it working fine. You could use the script of "Making First call", and add the code to do a getPayment.php. 

To summarize, you can almost copy 90% of the code from samples, but not directly. You would have to stitch things together to make it work nicely. I would recommend following the steps after "making first call" like https://github.com/paypal/PayPal-PHP-SDK/wiki/Adding-Configurations, etc. Once you are finished with those, you should have almost everything you need to set this up.
