### ISSUE TITLE
new client Id and secret not working

### ISSUE THREAD

**Issue by vishnuc** [paypal/PayPal-PHP-SDK#380]
I have created many apps , But client ID and Secret not working.Whereas Default client Id and secret present in PHP SDK is working fine.What is wrong with my developer accounts ?

When I run CreatePaymentUsingPayPal.php I just blank error **unknown error** .Nothing stored in log too.

**Comment by jaypatel512** [comment]
Generally, you need to enable few settings in Developer Dashboards, to get it to work properly. The most obvious ones are "redirect urls", enable payment in Sandbox, etc. 

However, for any reason your clientId and secret are not working, this seems to be an issue with your account, and not the SDK. Please reach out to https://www.paypal-techsupport.com/app/ask for getting your account fixed.
