### ISSUE TITLE
 Got Http response code 400 when accessing 

### ISSUE THREAD

**Issue by code-freakz** [paypal/PayPal-PHP-SDK#381]
Hi,

I have been trying  Create Payment Using Credit Card using your sdk. But I am always getting a response as shown:

<div class="row hidden-xs hidden-sm hidden-md"><div class="col-md-6"><h4>Request Object</h4><pre class="prettyprint ">{
    <span class="key">"intent":</span> <span class="string">"sale"</span>,
    <span class="key">"payer":</span> {
        <span class="key">"payment_method":</span> <span class="string">"credit_card"</span>,
        <span class="key">"funding_instruments":</span> [
            {
                <span class="key">"credit_card":</span> {
                    <span class="key">"type":</span> <span class="string">"visa"</span>,
                    <span class="key">"number":</span> <span class="string">"4311196134878802"</span>,
                    <span class="key">"expire_month":</span> <span class="string">"09"</span>,
                    <span class="key">"expire_year":</span> <span class="string">"2020"</span>,
                    <span class="key">"cvv2":</span> <span class="string">"012"</span>,
                    <span class="key">"first_name":</span> <span class="string">"Sarath"</span>,
                    <span class="key">"last_name":</span> <span class="string">"KS"</span>
                }
            }
        ]
    },
    <span class="key">"transactions":</span> [
        {
            <span class="key">"amount":</span> {
                <span class="key">"currency":</span> <span class="string">"USD"</span>,
                <span class="key">"total":</span> <span class="string">"20"</span>,
                <span class="key">"details":</span> {
                    <span class="key">"shipping":</span> <span class="string">"1.20"</span>,
                    <span class="key">"tax":</span> <span class="string">"1.30"</span>,
                    <span class="key">"subtotal":</span> <span class="string">"17.50"</span>
                }
            },
            <span class="key">"item_list":</span> {
                <span class="key">"items":</span> [
                    {
                        <span class="key">"name":</span> <span class="string">"Ground Coffee 40 oz"</span>,
                        <span class="key">"description":</span> <span class="string">"Ground Coffee 40 oz"</span>,
                        <span class="key">"currency":</span> <span class="string">"USD"</span>,
                        <span class="key">"quantity":</span> <span class="number">1</span>,
                        <span class="key">"tax":</span> <span class="string">"0.30"</span>,
                        <span class="key">"price":</span> <span class="string">"7.50"</span>
                    },
                    {
                        <span class="key">"name":</span> <span class="string">"Granola bars"</span>,
                        <span class="key">"description":</span> <span class="string">"Granola Bars with Peanuts"</span>,
                        <span class="key">"currency":</span> <span class="string">"USD"</span>,
                        <span class="key">"quantity":</span> <span class="number">5</span>,
                        <span class="key">"tax":</span> <span class="string">"0.20"</span>,
                        <span class="key">"price":</span> <span class="string">"2"</span>
                    }
                ]
            },
            <span class="key">"description":</span> <span class="string">"Payment description"</span>,
            <span class="key">"invoice_number":</span> <span class="string">"55d44b38827ba"</span>
        }
    ]
}</pre></div><div class="col-md-6"><h4 class="error">Response Object</h4><p class="error"><i class="fa fa-exclamation-triangle"></i> Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payment.</p><pre class="prettyprint error">{
    <span class="key">"name":</span> <span class="string">"UNKNOWN_ERROR"</span>,
    <span class="key">"message":</span> <span class="string">"An unknown error has occurred"</span>,
    <span class="key">"information_link":</span> <span class="string">"https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR"</span>,
    <span class="key">"debug_id":</span> <span class="string">"817fefb0cb878"</span>
}</pre></div></div>

I have tried things like creating new account and changing email addredd. But I couldn't resolve it myself. Please help me

Thanks in advance,
Sarath

**Comment by jaypatel512** [comment]
Hey @code-freakz !

I was not able to reproduce the issue. I used your request object and made a call in sandbox, and it worked. I have attached the snapshot. It seems like the issue is still somehow your account related. 

Can you please reach out to [Merchant Technical Support](https://www.paypal-techsupport.com/app/ask) with the above information, and they can quickly lookup your account if there is something there. 

<img width="1376" alt="screen shot 2015-08-19 at 10 39 07 am" src="https://cloud.githubusercontent.com/assets/1309895/9360938/bff7e9f0-465e-11e5-9e38-01dd5d046e3b.png">

**Comment by code-freakz** [comment]
OK . Thank you very much for the support.
