### ISSUE TITLE
Some clarification about billing agreement and execute

### ISSUE THREAD

**Issue by SirCameron** [paypal/PayPal-PHP-SDK#385]
Hey

Thanks for the help so far.
I am a little confused about the step between creating a billing agreement, the customer agreeing and then executing the agreement.
I redirect the  customer to the agreement link after creating the agreement, so, in order to execute the agreement, is the user then redirected back to a page on my site with the token in the query? Or is that a call that happens in the background IPN style?
If it is the IPN style, where do I set that URL?

Also, I get an error when trying to use a sandbox user to agree to a billing agreement.. Simply says an error occurred and redirects me back to my site.

**Comment by jaypatel512** [comment]
It would be a redirect to the URL that you have set in the plan that is used in the given agreement. 

You can actually try the samples locally by installing the SDK in your machine and following instructions [here](https://github.com/paypal/PayPal-PHP-SDK/wiki/Samples). Alternatively, just to checkout the flow, you can view that here at http://paypal-php-sdk.herokuapp.com/#6de667ee2194454f3298064cbf2a2290

**Comment by SirCameron** [comment]
Hey Jay

Thanks, but even testing your sample code, I get the same problem I'm experiencing with mine: the sandbox accounts are not allowing me to continue and execute an agreement... I get an error stating that it could not be processed.

So from here, I cannot see how payments are processed, etc..

**Comment by jaypatel512** [comment]
Can you please make sure you are using the provided sample in the SDK as is, and not making any changes to it ? If it still fails, you should have a PayPal.log file that should have more information on why it is failing. 

If nothing, can you please share the screenshot of what kind of error you are seeing, that could help me debug ?

**Comment by SirCameron** [comment]
Hi Jay.

I am using your sample code as is.. I have changed nothing.
When going to the execution link provided in your samples after creating the agreement, etc, I get this error:

http://snag.gy/4bTCg.jpg
