### ISSUE TITLE
Paypal REST API for Bank Direct Debit

### ISSUE THREAD

**Issue by manishkrag** [paypal/PayPal-PHP-SDK#388]
Hello,

My requirement is using Paypal RSET API allow user to pay using their bank account without leaving my website. Very similar to direct credit card payment.

I have checked that in API we have a class `BankAccount` using which we can save bank account to PP for future use for payment. But wonder how we can use this Bank Profile ID for payment deduction.

I have discussed with PP techsupport team and asked me to add a ticket here.

Thanks in advance.

Regards,
Manish

**Comment by jaypatel512** [comment]
Currently, the Vault APIs, only supports [Credit Cards](https://developer.paypal.com/webapps/developer/docs/api/#vault) only. Bank account is currently not supported for external developers.
