### ISSUE TITLE
CreatePaymentUsingPayPal.php

### ISSUE THREAD

**Issue by stijnwuyts** [paypal/PayPal-PHP-SDK#392]
Dear All, 

I hope you can help me with this. I noticed the most strange behaviour with the sample file in CreatePaymentUsingPayPal.php . If I leave the script and amounts untouched, it workes. Every other change I do in the amounts will through me the error: The totals of the cart item amounts do not match sale amounts.

It's very frustrating... i can do basic math 
```php
$item1 = new Item();
$item1->setName('Ground Coffee 40 oz')
    ->setCurrency('USD')
    ->setQuantity(1)
    ->setSku("123123") // Similar to `item_number` in Classic API
    ->setPrice(7.5);
$item2 = new Item();
$item2->setName('Granola bars')
    ->setCurrency('USD')
    ->setQuantity(6)
    ->setSku("321321") // Similar to `item_number` in Classic API
    ->setPrice(2);
$itemList = new ItemList();
$itemList->setItems(array($item1, $item2));
// ### Additional payment details
// Use this optional field to set additional
// payment information such as tax, shipping
// charges etc.
$details = new Details();
$details->setShipping(1.2)
    ->setTax(1.3)
    ->setSubtotal(19.50);
// ### Amount
// Lets you specify a payment amount.
// You can also specify additional details
// such as shipping, tax.
$amount = new Amount();
$amount->setCurrency("USD")
    ->setTotal(22)
    ->setDetails($details);
```

For example, i just updated the Granola bars quantity with 1 and added 2 USD both in setSubtotal and setTotal. 

It's really frustrating...

Thanks for helping out.

**Comment by jaypatel512** [comment]
As you can see in the [ExecutePayment.php](http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/ExecutePayment.html) which is the second part of Express checkout flow, where the user is redirected back when he/she approves the payment. 

In there, the sample currently has the code to make optional changes to the amount. This allows you to make adjustments to the shipping or taxes based on his shipping address provided in PayPal. In your example, you need to make the appropriate changes there too, or remove that optional block.

**Comment by JCarlosR** [comment]
@jaypatel512 I am not using the ```setDetails``` method. But the shipping address is still appearing.
How I can hide/remove that in the payment process?

Thanks in advance.

**Comment by ppmtscory** [comment]
@JCarlosR as this is not an issue with the SDK specifically, please be sure to file a ticket with our [Merchant Tech Support](https://www.paypal-techsupport.com/app/ask) team with these types of questions.  To answer you, you'll need to create an experience profile and utilize the [no_shipping](https://developer.paypal.com/docs/api/payment-experience/#definition-input_fields) option.
