### ISSUE TITLE
response code 401 when retrieve payment details 

### ISSUE THREAD

**Issue by momopaper** [paypal/PayPal-PHP-SDK#394]
i wastrying to retrieve a payment details by payment id received from a created transaction but i got the following response:
Got Http response code 401 when accessing https://api.sandbox.paypal.com/v1/payments/payment/PAY-xxxxxxxxxxxxxxxxxxxxxxxxxxx.

Here are my code: 

        $this->apiContext = new \PayPal\Rest\ApiContext(
                new \PayPal\Auth\OAuthTokenCredential(
                'xxxxxxxx', // ClientID
                'xxxxxxxx'      // ClientSecret
                )
        );
        $tokenInfo = new OpenIdTokeninfo();
        $tokenInfo = $tokenInfo->createFromRefreshToken(array('refresh_token' => $refreshToken), $this->apiContext);
        $cred = "Bearer " . $tokenInfo->getAccessToken();
        $this->apiContext->addRequestHeader("Authorization", $cred);
        $payment = Payment::get($paymentId, $this->apiContext);

is there anything wrong with my codes?

**Comment by jaypatel512** [comment]
Hey @momopaper !

Unless you are trying to create a future payment, you do not need a refreshtoken etc. We have [samples attached](https://github.com/paypal/PayPal-PHP-SDK/wiki/Samples) that could be used to get you started. The [Get Payment Detail](http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/GetPayment.html) is one you wish to run. Here would be the code to do it:

```php
<?php
// 1. Autoload the SDK Package. This will include all the files and classes to your autoloader
require __DIR__  . '/vendor/autoload.php';
// 2. Provide your Secret Key. Replace the given one with your app clientId, and Secret
// https://developer.paypal.com/webapps/developer/applications/myapps
$apiContext = new \PayPal\Rest\ApiContext(
    new \PayPal\Auth\OAuthTokenCredential(
        'AYSq3RDGsmBLJE-otTkBtM-jBRd1TCQwFf9RGfwddNXWz0uFU9ztymylOhRS',     // ClientID
        'EGnHDxD_qRPdaLdZz8iCr8N7_MzF-YHPTkjs6NKYQvQSBngp4PTTVWkPZRbL'      // ClientSecret
    )
);
// Step 2.1 : Between Step 2 and Step 3
$apiContext->setConfig(
  array(
    'log.LogEnabled' => true,
    'log.FileName' => 'PayPal.log',
    'log.LogLevel' => 'FINE'
  )
);
try {
    $payment = Payment::get(<Enter your PaymentId>, $apiContext);
} catch (\PayPal\Exception\PayPalConnectionException $ex) {
    // This will print the detailed information on the exception. 
    //REALLY HELPFUL FOR DEBUGGING
    echo $ex->getData();
} catch (Exception $ex) {
    echo $ex->getMessage();
}
```

**Comment by momopaper** [comment]
Yes, im doing future payment

**Comment by jaypatel512** [comment]
So, if you are just trying to retrieve the payment after completing the future payment, you can still do the same way as I mentioned above. Irrespective of the flow on how Payment was created, retrieving it would still be the same for all.

However, if you trying to complete the future payment flow, where you receive a "code" from mobileSDK to your server, and you create a payment, you should be looking at the code shown at http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/CreateFuturePayment.html

Let me know if that helps.

**Comment by momopaper** [comment]
thanks for your help, it works now :)

**Comment by jaypatel512** [comment]
Yay !! :+1: Happy Coding.

**Comment by acedesigns** [comment]
Hi @jaypatel512 

I came across this error and this helped me so much.
But How can I tell the message back to the user `return redirect()->back()->with(['flash_message_danger' => $ex->getData() ]);`

```
{
    name: "VALIDATION_ERROR",
    details: [
        {
            field: "payer.funding_instruments[0].credit_card",
            issue: "Credit card number is invalid for the credit card type."
        }
    ],
    message: "Invalid request. See details.",
    information_link: "https://developer.paypal.com/docs/api/payments/#errors",
    debug_id: "xxxxxxxxxxx"
}
```
#### I want to show the user the reason

I tried to do `$ex->getData()->details`
```
Trying to get property of non-object
````

**Comment by jaypatel512** [comment]
Hey @acedesigns ! 

The `$ex->getData()` is a string in our exception log, and not a JSON object. You can decode this string using [json_decode](http://php.net/manual/en/function.json-decode.php), and fetch the details from there.

Note that the issue details may change in future.
