### ISSUE TITLE
Repeat Billing Failing

### ISSUE THREAD

**Issue by paultarr** [paypal/PayPal-PHP-SDK#395]
This morning our repeats failed with the following error on one of our attempted payments.

Method PayPal\Api\Sale::getFmfDetails() does not exist

**Comment by jaypatel512** [comment]
I am still seeing the method [`PayPal\Api\Sale::getFmfDetails()`](https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Api/Sale.php#L401) in the SDK. 

Can you please make sure you are using the latest version of SDK ?

**Comment by paultarr** [comment]
We were using an older version of the SDK. Everything was working fine up until this morning (0.16 I believe) when it appears PayPal made a breaking change server side that prevented it from working.

Upgraded to the latest version and now all is processing as expected.

**Comment by jaypatel512** [comment]
It seems like you had "SDK Validation" enabled that throws an error when the SDK is not having given methods that server provides. You can read more about it [here](https://github.com/paypal/PayPal-PHP-SDK/wiki/Validation). You could disable that if you wish to not update to the latest version. However, I would strongly recommend updating it to latest :+1:
