### ISSUE TITLE
"Method PayPal\Api\Sale::getFmfDetails() does not exist"

### ISSUE THREAD

**Issue by LeRouxJonathan** [paypal/PayPal-PHP-SDK#396]
After a long, successful period of using the PayPal API that is integrated on our website, the following error has begun to appear as of this morning on 9/15/2015:

"Method PayPal\Api\Sale::getFmfDetails() does not exist"

Our server is compliant with the new SHA2 enforcement; however, this seems to be an API issue, not a server issue.

I very much appreciate your prompt assistance with this matter. This issue is impacting thousands of dollars of nonprofit donations.

**Comment by jaypatel512** [comment]
Duplicate Issue: https://github.com/paypal/PayPal-PHP-SDK/issues/395

If you could please update the SDK to latest version, you should be able to resolve the issue. Or else, you must have [enabled SDK validation](https://github.com/paypal/PayPal-PHP-SDK/wiki/Validation). Please disable it, and you should be able to resolve the issue :+1:

**Comment by radiantjuan** [comment]
Hi I have the same problem

**Comment by LeRouxJonathan** [comment]
Radiant, 

If you haven't already, upgrade to the latest version of the PayPal API. Upon upgrading around the time of this ticket -- about 5 to 6 months ago -- the issue was resolved for me. It's likely that you're using an out of date installation of the PayPal API.

**Comment by radiantjuan** [comment]
yes It's already working thank you
