### ISSUE TITLE
PayPal service upgrades

### ISSUE THREAD

**Issue by engrsandeep** [paypal/PayPal-PHP-SDK#398]
Hi,

We got below email from paypal sometime ago. Do we need update to use REST api? We dont have secure server(https).  Can you please guide if we need to update?

Paypal Mail
As we have previously communicated to you, PayPal is upgrading the certificate for www.paypal.com to SHA-256. This endpoint is also used by merchants using the Instant Payment Notification (IPN) product. 

This upgrade is scheduled for 30/9/2015; however, we may need to change this date on short notice to you to align to the industry security standard.

You’re receiving this notification because you’ve been identified as a merchant who has used IPN endpoints within the past year. If you have not made the necessary changes, we urge you to do so right away to avoid a disruption of your service!
Because these changes are technical in nature, we advise that you consult with your individuals responsible for your PayPal integration. They will be able to identify what, if any, changes are needed. Please share this email and the hyperlinks below with your technical contact for evaluation. 
Testing in the Sandbox is one of the best ways to make sure your integrations work. Sandbox endpoints have been upgraded to accept secure connections by the SHA-256 Certificates. 
Full technical details can be found in our Merchant Security System Upgrade Guide. In addition, our 2015-2016 SSL Certificate Change microsite contains a schedule of our service upgrade plan. 
Thanks for your patience as we continue to improve our services. 

Regards,
Sandeep

**Comment by pp-randy** [comment]
Are you receiving IPNs at all?  https://developer.paypal.com/docs/classic/products/instant-payment-notification/

 Have you tested your integration against the sandbox?

**Comment by engrsandeep** [comment]
Yes, We are using IPN.

It working till now but we got paypal email. Dont know if we need to upgrade anyhing.

**Comment by jaypatel512** [comment]
If you don't mean webhooks, IPN is supported in Classic SDKs, not in REST SDK.

**Comment by engrsandeep** [comment]
We are using IPN because weekhooks dont support all things related to subscriptions. so if we use ipn will it affect? this is a general question not regarding SDK.

**Comment by tomwhipple** [comment]
If your server is capable of communicating with sites that have a SHA-256 certificate, then you are OK. If not you will need to update your crypto libraries and/or web environment. If you have stayed current with security patches, you are most likely fine. But, it is best to test on sandbox just to be safe.

Alternately you can use the [tools at SSLLabs.com](https://www.ssllabs.com/ssltest/) to examine other endpoints your application communicates with. If you are already connecting to sites with a SHA-256 cert, then you are in good shape.

**Comment by ppmtscory** [comment]
Lastly - more information on these upgrades can be found on our [microsite](https://www.paypal-knowledge.com/infocenter/index?page=content&id=FAQ1766&expand=true&locale=en_US).  There's a lot of information/resources on there and if you feel you need additional assistance or have further questions, please don't hesitate to reach out to our [Merchant Tech Support](https://www.paypal-techsupport.com/app/ask/) team.
