### ISSUE TITLE
[21-09-2015 01:47:49] PayPal\Validation\ModelAccessorValidator: DEBUG	: Missing Accessor: PayPal\Api\Sale:setProcessorResponse.

### ISSUE THREAD

**Issue by reykats** [paypal/PayPal-PHP-SDK#399]
I am getting this log after purchasing using credit card ( sandbox ). Please advise what this error is all about. I am using the latest repo.

Thanks

**Comment by jaypatel512** [comment]
Hey @reykats ! 

You are receiving this log because it is a new field returned from APIs that is not yet available in our PHP SDK. I have created a task for this, and will add those objects in our SDK and make a release as soon as possible.

**Comment by j2gl** [comment]
I had the same issue too, with version 1.3.2, and updated to 1.5.1
```
$ composer update paypal/rest-api-sdk-php
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing paypal/rest-api-sdk-php (v1.3.2)
  - Installing paypal/rest-api-sdk-php (v1.5.1)
    Downloading: 100%

Writing lock file
Generating autoload files
```

Log file with version 1.5.1 :
```
[20-09-2015 04:43:24] PayPal\Validation\ModelAccessorValidator: DEBUG   : Missing Accessor: PayPal\Api\Sale:setProcessorResponse. You might be using older version of SDK. If not, create an issue at https://github.com/paypal/PayPal-PHP-SDK/issues
```

**Comment by reykats** [comment]
Hello @jaypatel512 

Will this affect the payment processing? Can I just leave this as is for now? In a few days my site will about to go live. Please advise.

Thanks

**Comment by jaypatel512** [comment]
Hey @reykats !

This should absolutely not affect your code. This is just a log message to notify you that more fields are available for the latest API releases. I think renaming the log message to a bit more calming format would be better. However, you dont need to worry about it. 

You can push your existing code to live :+1: !

**Comment by jaypatel512** [comment]
Hey all !

The new release has been made with the new fields for Payments API. Please update to the latest version, and you should not see those errors anymore. :+1: 

Release: https://github.com/paypal/PayPal-PHP-SDK/releases/tag/v1.6.0

Happy Coding !

**Comment by j2gl** [comment]
Awesome! thanks @jaypatel512
