### ISSUE TITLE
Paypal REST API INSTRUMENT_DECLINED

### ISSUE THREAD

**Issue by mickolechou** [paypal/PayPal-PHP-SDK#400]
recently,when execute payment.execute() ,throw the exception:
Error code : 400 with response : {\"name\":\"INSTRUMENT_DECLINED\",\"message\":\"The instrument presented was either declined by the processor or bank, or it can't be used for this payment.\",\"information_link\":\"https://developer.paypal.com/webapps/developer/docs/api/#INSTRUMENT_DECLINED\",\"debug_id\":\"8c6dca762c1a2\"}
someone can help me?

**Comment by pp-randy** [comment]
The funding source of the payer was declined. Is this happening to all of your payments?

**Comment by ppmtscory** [comment]
Closing this as it's not related to an issue with the SDK itself.  For future reference, please reference [this page](https://developer.paypal.com/docs/api/#errors) to get an initial explanation of the payment error.  Also, if you need further explanation of an API error, then please reach out to our [Merchant Tech Support](https://www.paypal-techsupport.com/app/ask/) team.
