### ISSUE TITLE
PayPal SDK changes the timezone of our app

### ISSUE THREAD

**Issue by dobrev** [paypal/PayPal-PHP-SDK#401]
In our app we don't set the timezone in php.ini but rather in the code using [date_default_timezone_set()](http://php.net/manual/en/function.date-default-timezone-set.php). [This](https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Core/PayPalLoggingManager.php#L73-L76) changes the timezone globally and breaks some of our functionality. I'd much rather see a warning in the logs than having the timezone overridden by an external service.

**Comment by jaypatel512** [comment]
Hey @dobrev !

I completely agree with you. I will go ahead and remove that code, to make it generic and not mess with environments settings. 

It should be available in the next release very soon.

**Comment by jaypatel512** [comment]
Hey @dobrev ! 

We have added the fix for this. Should be in the latest release soon.

**Comment by dobrev** [comment]
Thanks @jaypatel512!
