### ISSUE TITLE
Log File persision problem

### ISSUE THREAD

**Issue by laurentiustroia** [paypal/PayPal-PHP-SDK#403]
I use symfony2 and i integrate paypal sdk, the problem is if I access from browser this create file to log, but if i run command php say no permission, can make log have to have permission for editing all , 775 mod i think is enough. or is some option what need to configurate ?

here is my configuration:

```
'log.LogEnabled' => true,
'log.FileName' => $this->container->get('kernel')->getRootDir() .'/logs/PayPal.log',
'log.LogLevel' => 'INFO'
```

**Comment by jaypatel512** [comment]
The reason for that could be both php and browser would be two different users. You need to set proper users to it.
