### ISSUE TITLE
About paypal credit card payment api

### ISSUE THREAD

**Issue by Vivacityjaipur** [paypal/PayPal-PHP-SDK#404]
I've have made a form including credit card detail fields, like Name, Address, Currency Code, country code etc. i wanted to show the json format of credit card details field after successful payment. As i followed the instructions from paypal credit card api from paypal developers documentation. The error i've got as follow: 

```
Catchable fatal error: Argument 1 passed to PayPal\Transport\PayPalRestCall::__construct() must be an instance of PayPal\Rest\ApiContext, instance of PayPal\Auth\OAuthTokenCredential given, called in /opt/lampp/htdocs/work/credit_card/PayPal-PHP-SDK/paypal/rest-api-sdk-php/lib/PayPal/Common/PayPalResourceModel.php on line 99 and defined in /opt/lampp/htdocs/work/credit_card/PayPal-PHP-SDK/paypal/rest-api-sdk-php/lib/PayPal/Transport/PayPalRestCall.php on line 38
```

I've PayPal-PHP-SDK folder with my index.php in my directory. I've include it properly at the top of the index.php page (require __DIR__  . '/PayPal-PHP-SDK/autoload.php;) and used all the required classes, also used proper client key and secret client key. 

Please provide me executable solution.

Thank you!

**Comment by jaypatel512** [comment]
Can you make sure when you are making a call to create payment, you are passing `apiContext` object and not `OauthTokenCredential` Object ? 

If not sure, can you paste your code here, so that I may be able to refer to the code a bit more. 

Also, there is a sample code that shows exactly what you are trying to achieve here at https://github.com/paypal/PayPal-PHP-SDK/wiki/Making-First-Call

**Comment by jaypatel512** [comment]
Any updates @Vivacityjaipur ?

**Comment by jaypatel512** [comment]
Closing this issue based on inactivity. Please re-open if still facing this issue.

**Comment by fijisoo** [comment]
I have the same issue. 
My code: 

<?php

use PayPal\Api\Payer;
use PayPal\Api\Item;
use PayPal\Api\ItemList;
use PayPal\Api\Details;
use PayPal\Api\Amount;
use PayPal\Api\Transaction;
use PayPal\Api\RedirectUrls;
use PayPal\Api\Payment;

require 'start.php';

if(!isset($_POST['produkt'],$_POST['cena'])){
    die();
}

$product = $_POST['produkt'];
$price = $_POST['cena'];
$shipping = 0;

$total = $price + $shipping;

$payer = new Payer();
$payer->setPaymentMethod('paypal');

$item = new Item();
$item->setName($product)
      ->setCurrency('PLN')
      ->setQuantity(1)
      ->setPrice($price);

$itemList = new ItemList();
$itemList->setItems([$item]);

$details = new Details();
$details->setShipping($shipping)
        ->setSubtotal($total);

$amount = new Amount();
$amount->setCurrency('PLN')
        ->setTotal($total)
        ->setDetails($details);

$transaction = new Transaction();
$transaction->setAmount($price)
        ->setItemList($itemList)
        ->setDescription('Zapłać za bilety')
        ->setInvoiceNumber(uniqid());

$redirectUrl = new RedirectUrls();
$redirectUrl ->setReturnUrl(SITE_URL . '/zaplac.php?success=true')
             ->setCancelUrl(SITE_URL . '/zaplac.php?success=false');

$payment = new Payment();
$payment->setIntent('sale')
        ->setPayer($payer)
        ->setRedirectUrls($redirectUrls)
        ->setTransactions([$transaction]);

try {
    $payment->create($paypal);
} catch (Exception $ex) {
    die($ex);
}

echo $approvalUrl = $payment->getApprovalLink();

**Comment by fijisoo** [comment]
ok again. 
i trying to do paypal payment on my webside and i working with this video: https://www.youtube.com/watch?v=BD1dOWIABe0

at the begining when i want to run I got this error "Fatal error: Class 'PayPay\Auth\OAuthTokenCredential' not found in line 8"

LINE 8:  new \PayPay\Auth\OAuthTokenCredential( '****U KNOW*****','*****U KNOW*****');

and then i found solution on stackoverflow :
"<?php
require_once('vendor/autoload.php');
use PayPal\Auth\OAuthTokenCredential;
define('SITE_URL', '**MY_URL.pl***');
$paypal = new OAuthTokenCredential('*****MHM***', '**THATS RIGHT***');
"
after this i got this one: 
"Catchable fatal error: Argument 1 passed to PayPal\Transport\PayPalRestCall::__construct() must be an instance of PayPal\Rest\ApiContext, instance of PayPal\Auth\OAuthTokenCredential given, called in /home/bendomin/public_html/*********.pl/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PayPalResourceModel.php on line 99 and defined in /home/bendomin/public_html/*********.pl/vendor/paypal/rest-api-sdk-php/lib/PayPal/Transport/PayPalRestCall.php on line 38"


THIS IS MY PHP:
<?php

use PayPal\Api\Payer;
use PayPal\Api\Item;
use PayPal\Api\ItemList;
use PayPal\Api\Details;
use PayPal\Api\Amount;
use PayPal\Api\Transaction;
use PayPal\Api\RedirectUrls;
use PayPal\Api\Payment;

require 'start.php';

if(!isset($_POST['produkt'],$_POST['cena'])){
    die();
}

$product = $_POST['produkt'];
$price = $_POST['cena'];
$shipping = 2.00;

$total = $price + $shipping;

$payer = new Payer();
$payer->setPaymentMethod('paypal');

$item = new Item();
$item->setName($product)
      ->setCurrency('PLN')
      ->setQuantity(1)
      ->setPrice($price);

$itemList = new ItemList();
$itemList->setItems([$item]);

$details = new Details();
$details->setShipping($shipping)
        ->setSubtotal($total);

$amount = new Amount();
$amount->setCurrency('PLN')
        ->setTotal($total)
        ->setDetails($details);

$transaction = new Transaction();
$transaction->setAmount($amount)
        ->setItemList($itemList)
        ->setDescription('Zapłać za bilety')
        ->setInvoiceNumber(uniqid());

$redirectUrls = new RedirectUrls();
$redirectUrls ->setReturnUrl(SITE_URL . '/zaplac.php?success=true')
             ->setCancelUrl(SITE_URL . '/zaplac.php?success=false');

$payment = new Payment();
$payment->setIntent('sale')
        ->setPayer($payer)
        ->setRedirectUrls($redirectUrls)
        ->setTransactions([$transaction]);

try {
    $payment->create($paypal);
} catch (Exception $ex) {
    die($ex);
}

echo $approvalUrl = $payment->getApprovalLink();

**Comment by fijisoo** [comment]
hmm, i think I solved my problem. don't know really how but i knew it was something wrong with this PayPay\Auth\OAuthTokenCredential. Anyway it works by now.
