### ISSUE TITLE
WARNING: Missing Accessor: PayPal\Api\Transaction:setCoupledGroup

### ISSUE THREAD

**Issue by AnjaGoldmann** [paypal/PayPal-PHP-SDK#405]
Hello,

in our OXID PayPal Plus modul we get a warning:

PayPal\Validation\ModelAccessorValidator: WARNING	: Missing Accessor: PayPal\Api\Transaction:setCoupledGroup.

Please help.

Regards

**Comment by jaypatel512** [comment]
Duplicate of https://github.com/paypal/PayPal-PHP-SDK/issues/399
