### ISSUE TITLE
$oAuth->getAccessToken allways calling to sandbox :S

### ISSUE THREAD

**Issue by MGDSoft** [paypal/PayPal-PHP-SDK#407]
In api rest docs
https://developer.paypal.com/docs/api/#oauth-request--response

Says

```php
            $oAuth =  new \PayPal\Auth\OAuthTokenCredential(self::API_CLIENT_ID_LIVE, self::API_SECRET_LIVE);
            $oAuth->getAccessToken(['mode' => 'live']);
```

But allways send to sandbox

**Comment by pp-randy** [comment]
Does it go to live if you make the change to the config file?  Here is an example from the Sample https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/sdk_config.ini

**Comment by MGDSoft** [comment]
Then the example from https://developer.paypal.com/docs/api/#oauth-request--response (PHP) is wrong, that parameter have not sense

**Comment by jaypatel512** [comment]
Hey @MGDSoft ! 

The developer docs samples for PHP are out of date. Infact, we have a whole set of SDK specific documentation available at : http://paypal.github.io/PayPal-PHP-SDK/
