### ISSUE TITLE
Function to set "no_shipping"

### ISSUE THREAD

**Issue by Skaronator** [paypal/PayPal-PHP-SDK#415]
I saw the Note.js SDK have a option to set the "no_shipping" statement but I didn't found any way to do this in the PHP SDK. 

https://github.com/paypal/PayPal-node-SDK/issues/6#issuecomment-63317852

**Comment by jaypatel512** [comment]
Hey @Skaronator !

We do have an option to do no_shipping using Payment-Experience. The same way Nodejs has.

Here is the link to the sample: https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payment-experience/CreateWebProfile.php#L32

Steps to implement:

1. Create a web-profile with noShipping set to true. (as shown in the sample).
2. Use the web-profile-id returned on step 1, and add it inside the payment object :[setExperienceProfileId()](https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Api/Payment.php#L310)
3. Proceed with the normal checkout flow.
4. Execute the payment as usual.

**Comment by Skaronator** [comment]
Hey @jaypatel512

Damn you fast! Just found the same file and implementing this right now.

Thanks for the quick response!

**Comment by jaypatel512** [comment]
Great to know !! Happy Coding !! :+1:
