### ISSUE TITLE
GetBillingAgreemen error, please correction of my steps.

### ISSUE THREAD

**Issue by adnan-adiatman** [paypal/PayPal-PHP-SDK#416]
sorry if my English was bad

it is right agreementId?
![Image](http://i.imgur.com/awwEb5s.png)

I tried to follow this flow. but errors before completion.
http://paypal-php-sdk.herokuapp.com/billing/GetBillingAgreement.php

I will explain my steps, please be corrected if there are errors or omissions
step 1
after the subscription completed from page paypal, i got tx = 1GD58065H2561505G

step 2
i get detail tx code and convert to object
```
 public function getTxDetail($tx) {

        try{
        $url = 'https://www.sandbox.paypal.com/cgi-bin/webscr';

        $data = http_build_query(array('cmd' => '_notify-synch', 'tx' => $tx, 'at' => $this->getIdentityToken()));

        $options = array(
            'http' => array(
                'header' => "Content-type: application/x-www-form-urlencoded",
                'method' => 'POST',
                'content' => $data,
            ),
        );
        
        }  catch (Exception $e){
            
        }

        $context = stream_context_create($options);

        $result = file_get_contents($url, false, $context);

        $data = explode('\n', urldecode(str_replace('"', '', json_encode($result))));
        $list=new \stdClass();
        foreach ($data as $value) {
            $value = explode('=', $value);
            if (count($value) == 2) {
                $list->$value[0] = $value[1];
            } else if (trim($value[0]) != '') {
                $list->$value[0] = $value[0];
            }
        }
        
        return $list;
    }
```
return
![Image](http://i.imgur.com/QLCZkZD.png)

step 3
i use `subscr_id` to get `billing-agreements`
```
    public function getBillingAgreement($agreementId) {
        $apiContext = $this->getApiContext();
        $agreement = Agreement::get($agreementId, $apiContext);
        return $agreement;
    }
```
and i get error
`Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/billing-agreements/I-4GTNKX546820.`

please correction of the wrong parts or less?
Thank you.

**Comment by jaypatel512** [comment]
Hey @adnan-adiatman !

The steps provided in the https://github.com/paypal/PayPal-PHP-SDK/tree/master/sample/billing would able to help you get through the setup. 

For better understanding I would recommend you installing `samples` in your local machine, and make changes to it to replicate your scenario. Here is the link to setup samples. It is fairly quick and will help you understand better.

https://github.com/paypal/PayPal-PHP-SDK/wiki/Samples

**Comment by jaypatel512** [comment]
Also, there should be more detailed error in 400 HTTP. Can you catch the exception as shown here, to print the detailed message on why exactly it is failing ? 

Here are the instruction to do so : https://github.com/paypal/PayPal-PHP-SDK/wiki/exception-%27PayPal%5CException%5CPayPalConnectionException%27-with-message-%27Got-Http-response-code-400-when-accessing

Example Code:
```php
public function getBillingAgreement($agreementId) {
        try {
             $apiContext = $this->getApiContext();
             $agreement = Agreement::get($agreementId, $apiContext);
             return $agreement;
        } catch (PayPal\Exception\PayPalConnectionException $ex) {
             echo $ex->getCode(); // Prints the Error Code
             echo $ex->getData(); // Prints the detailed error message 
             die($ex);
         } catch (Exception $ex) {
             die($ex);
         }
    }
```

**Comment by adnan-adiatman** [comment]
return error
```
{
    "name": "SUBSCRIPTION_UNMAPPED_ERROR",
    "message": "Subscription Profiles not supported by Recurring Payment APIs.",
    "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#SUBSCRIPTION_UNMAPPED_ERROR",
    "debug_id": "32486574739cf"
}
```

Thank you.
i found my problem. my problem is that I use a basic subscription button profile. so that the agreement  profile could not be retrieved.

**Comment by jaypatel512** [comment]
In that case, I will go ahead and close this issue. You would only be able to retrieve the Ids that are generated using APIs.
