### ISSUE TITLE
Billing Agreement State is wrong

### ISSUE THREAD

**Issue by rmatil** [paypal/PayPal-PHP-SDK#418]
Hi

I just checked the documentation at https://developer.paypal.com/webapps/developer/docs/api/#agreement-object and found that the states returned can be one of the following:

* Active
* Pending
* Expired
* Suspend
* Reactivate
* Cancel

However, when i now suspend a billing agreement as described in the examples (http://paypal.github.io/PayPal-PHP-SDK/sample/doc/billing/SuspendBillingAgreement.html), the status returned is now `Suspended`. Note the additional `ed`. Same is happening for `Cancel`, i.e. request returns `Cancelled` and `Reactivated`.

Could you please state the correct values or update the documentation?

-----  EDIT -----
Btw, when requesting transactions from a billing agreement (e.g. https://api.sandbox.paypal.com/v1/payments/billing-agreements/I-K4UYV9H650CH/transactions?start_date=2015-10-06&end_date=2015-10-15) the cancel state is called `Canceled`. Note here only one `l`. Could be nice if the state of the billing agreement and the transaction would be equally called (`Cancelled` or `Canceled`)

**Comment by ppmtscory** [comment]
Closing as it appears that the documentation has been updated.

**Comment by benkr94** [comment]
I still see the same list as rmatil above, and experienced an error relying upon the returned state to be 'Cancel' when in fact it is 'Cancelled'.

**Comment by ppmtscory** [comment]
Thank you for reporting, @benkr94.  I'm fairly certain these were updated when I last closed this issue, however, I've filed an internal ticket accordingly.

For internal bookkeeping: DEVDOC-426

**Comment by theyuv** [comment]
Can you please point me to the documentation that details all possible Billing Agreement states?

I can't find it in the link above.

Thanks.

**Comment by xiaoleih41** [comment]
@theyuv  The list is not there for some reason. I have followed up with internal team on this. 
For internal bookkeeping: DEVDOC-426

**Comment by xiaoleih41** [comment]
Please refer to https://github.com/paypal/PayPal-REST-API-issues/issues/72 for the status of this issue.
