### ISSUE TITLE
Agreement object is missing Plan details

### ISSUE THREAD

**Issue by Binternet** [paypal/PayPal-PHP-SDK#421]
When querying for an agreement, I cannot get the full `Plan` details (For example, `id` is missing)...
![Screenshot]
(http://s11.postimg.org/6x7e5ts03/2015_10_18_170718.png)

I noticed there is a bug that the `Payer` object is not returned as well, so I guess this is quite similar...

**Comment by jaypatel512** [comment]
Duplicate: https://github.com/paypal/PayPal-PHP-SDK/issues/155
