### ISSUE TITLE
Objects getId() does not work

### ISSUE THREAD

**Issue by garzettone** [paypal/PayPal-PHP-SDK#424]
I need to apply a patch to a paymentdefinition stored yesterday but crashed against a bug.

I have some simple php code to retrieve a PaymentDefinition Id that doesn't work:
// ... here some code to rertieve $apiContextand not included

$billing_agreement_id='I-X3AR1DCKHEUS'; // valued stored in my database

$agreement = Agreement::get($billing_agreement_id, $apiContext);
//agreement is ok
$plan = $agreement->getPlan();
//$plan is ok
$plan_id = $plan->getId(); //// this doesn't work

/////// $plan_id is empty //WRONG//

$payments = $plan->getPaymentDefinitions();
// $payments = is an array ok
$frequency=$payments[0]->getFrequency();  //this work correctly
//$frequency has a correct value
$first_payment_id = $payments[0]->getId(); //// this doesn't work

/////// $first_payment_id is empty //WRONG AGAIN//

Why getId() call returns empy values ?
Is it a bug ?

thanks

**Comment by jaypatel512** [comment]
Hey @garzettone !

I was able to reproduce the issue you are facing. I noticed, that when you create a new Plan, it returns the array of `payment_definitions` with `id` parameter in the response. However, once the agreement is completed/executed, the `GET` request on agreement returns `payment_definitions` array without the `id`s. This seems to be the issue with the APIs itself, and not the SDK. 

We will go ahead and inform the rest api team responsible for this.

**Comment by jaypatel512** [comment]
Hey @garzettone !

From our support team, we got to know that the `payment_definitons` Ids that you are trying to access from the agreement is not returned for a reason. Once the agreement is executed, the plan is simply copied over to the agreement and gets disconnected. It is currently not possible to link plan and agreement with each other, and so the `Id`s of these `payment_definitions` are not returned.

However, from the look of the code, it seems like you are trying to achieve something else. Do you intend to get all the payments taken on that agreement ?
