### ISSUE TITLE
Question about the billing agreement flow

### ISSUE THREAD

**Issue by siegerhansma** [paypal/PayPal-PHP-SDK#426]
So, I'm starting a subscription box website. I have 3 plans with different amounts of money. I would like to collect the money on the first day of every month. 

- I create 3 billing plans, one for every subscription plan.
- For every user I make a billing agreement using the billing plan as a "template". 
- I set the start date on the first of the next month so the billing executes on the first of every month (I think?)
- Customer needs to approve the agreement

After approval it needs to be executed, what does that mean? Do you essentially set the agreement to active or something? What does the start date do and can I use that to control the day Paypal collects the money?

**Comment by ppmtscory** [comment]
The overview of the order of operations can be found [here](https://developer.paypal.com/docs/integration/direct/create-billing-agreement/).  The `start_date`, along with the frequency that's set in the Plan, will determine when it's going to bill on a recurring basis.  For any further integration questions, not specific to SDK functionality, please reach out to our [Merchant Tech Support](https://www.paypal-techsupport.com/app/ask/) team for assistance.
