### ISSUE TITLE
Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment

### ISSUE THREAD

**Issue by pradoshcubet** [paypal/PayPal-PHP-SDK#427]
Hi

I am using  PayPal-PHP-SDK with laravel 5.1.
i have used this package " https://github.com/net-shell/laravel-paypal".

while trying a payment method ( redirecting to paypal  ) with sandbox account, i am getting the following error : 

Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment. {"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"a000649d71eec"}

I have tried using the following sample code (Please see the link) : 
https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/CreatePaymentUsingPayPal.php

"debug_id":"a000649d71eec"

**Comment by nicomollet** [comment]
Same problem.

Even the demo shows the issue:
http://paypal-php-sdk.herokuapp.com/payments/CreatePaymentUsingPayPal.php

**Comment by SorawitZongkun** [comment]
how to solve this problem

**Comment by matteoannibali** [comment]
<img width="1280" alt="schermata 2015-10-30 alle 12 08 29" src="https://cloud.githubusercontent.com/assets/252208/10844331/fa1c7172-7efe-11e5-9fec-69e3c491432c.png">

**Comment by nicomollet** [comment]
Problem seems to be solved. Sandbox is OK again.

**Comment by pradoshcubet** [comment]
:+1:

**Comment by tomwhipple** [comment]
There was an issue with sandbox earlier which has now been resolved: https://github.com/paypal/PayPal-iOS-SDK/issues/355

Thanks!
