### ISSUE TITLE
Choose "Payments Pro Hosted" solution

### ISSUE THREAD

**Issue by nicomollet** [paypal/PayPal-PHP-SDK#430]
Hello

I have Prestashop eshops working with Paypal, and configured with "Paypal Payments Pro Hosted" solution, they use the old "Classic" API. The payments are received in the paypal backoffice and tagged as "Payments Pro Hosted" and have a small paypal fee, fee as agreed in our Paypal pro contract.

Now I am writing a custom PHP application using REST API and the PHP SDK. I am calling a simple Payment method.

$payer->setPaymentMethod("paypal");
$payment->setIntent("sale");

And then redirects the user to the approval_url.

Under Sandbox mode, the payment was successful so I tested under Live mode.
The payment was tagged as "Express checkout", not "Payments Pro Hosted", and I believe the paypal fees are higher.

My question is, how can I force Paypal to use the "Payments Pro Hosted" solution, not "Express checkout", with the REST API?

I wouldn't want to be forced to use the old classic API to do this, as it is close to be obsolete.

Thanks for your help.
Kind regards

**Comment by ppmtscory** [comment]
@nicomollet there's a couple parts to your question that I'll answer for you.

1. Pro Hosted is not available via REST APIs as they still operate on their own API subset

2. The fees for Pro Hosted depend on who your processor is.  If you are using PayPal as the processor, then your transaction fees for that and the fees for using REST APIs will be the same.  If you are not using PayPal as a processor for Hosted Solution, then your fees may be different than what the standard PayPal fees are with REST transactions.

**Comment by nicomollet** [comment]
Thanks a lot @ppmtscory 

I am not sure what processor is used. I just call the payment method, then redirects the browser to the approval_url. 

It's unfortunate the REST API is not compatible with all Paypal solutions. The Classic API PHP SDK (https://github.com/paypal/merchant-sdk-php/) is said to be obsolete.

**Comment by ppmtscory** [comment]
@nicomollet to clarify - with the REST API SDKs - there's no way to specify your own processor so PayPal is processing everything and you'd get the transaction fee that's set up within your PayPal account (default is 2.9% + 0.30).  The Classic API SDKs are not deprecated yet - it's just recommended to use REST when/where it's possible.  Therefore if somebody was doing a new integration, we'd recommend REST API (if their features are available) as that is the direction we're going.

Secondly, the merchant-sdk-php you reference doesn't have any Pro Hosted functionality within it as it's not used for that.  That SDK is for Classic products such as EC and DoDirectPayment among other Classic APIs.  The Hosted Solution you are referring to would use Payflow credentials and can be found [here](https://developer.paypal.com/docs/classic/payflow/gs_ppa_hosted_pages/).

For any further information on which SDK or API set to use for the product you'd like to integrate, please reach out to our [Merchant Tech Support](https://www.paypal-techsupport.com/app/ask) team as they'll be able to get you up and running efficiently in no time!
