### ISSUE TITLE
execute payment sample

### ISSUE THREAD

**Issue by shangsunset** [paypal/PayPal-PHP-SDK#433]
Hi Im very new to using paypal api and i was just wondering when should we do 'execute payment' the second part of express check out? when the users sign in to paypal and approve the payment, they will be directed to a page says success. should i make a ajax call and execute the payment when they are directed to that page?

Thanks.

**Comment by jaypatel512** [comment]
You might want to look at this documentation: http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/ExecutePayment.html

Also, there is a [whole bunch of documentation](https://github.com/paypal/PayPal-PHP-SDK/wiki) that would help you get started PHP SDK quickly.

I would recommend at least going through this: https://github.com/paypal/PayPal-PHP-SDK/wiki/Samples

**Comment by shangsunset** [comment]
Hi thanks for your reply. I looked through the sample code for execute payment before but I still don't know when or where to use the code...I already have the code to ask user to approve PayPal. Could you briefly walk me through what happens after users are redirected to the redirectUrl. Thanks!

**Comment by jaypatel512** [comment]
Basically, here are the steps involved:

1. Create a payment with all your items, total, etc. Add redirect_url, that should point to a url specific to your application. (This will be used in later steps.)
2. On success, use the `approval_url` and redirect the user to the page.
3. This will show paypal login/checkout flow.
4. User will approve the payment. (Or Cancel and return) 
5. Once the user has approved the payment, paypal will redirect the user to the above `redirect_url` with `PayerID` information.
6. Use that payerId to execute the payment. (This will be like a new request in laravel PHP framework). See above mentioned sample.
7. Payment is successfully executed, and completed.

5b. In the case of cancel, paypal will redirect the user to `cancel_url`. This is the place where you take appropriate steps to handle cases where user cancels the payment.
