### ISSUE TITLE
Issue going live - Client Authentication failed

### ISSUE THREAD

**Issue by viion** [paypal/PayPal-PHP-SDK#435]
I am trying to get the API to work in "Live" mode, I have had no issues with integrating the SDK through Sandbox, but once I switch to live I get: 

```
{"error":"invalid_client","error_description":"Client Authentication failed"}
```

And here starts my rabbit hole ....

- I read [Going Live!](https://github.com/paypal/PayPal-PHP-SDK/wiki/Going-Live) and noticed it has different screenshots to the [Dashboard](https://developer.paypal.com/developer/applications/) I've been using, never the less it has a link to it, so lets click that...
- I click the link on that page which takes me to [Dashboard on /webapps/](https://developer.paypal.com/webapps/developer/applications/myapps) ? No idea what the difference is, it doesn't list my application and the site looks the same as the one in the screenshots, so maybe it will work!?
- I try create an application there instead, Error: `We’re sorry, but something went wrong while creating the application. Please try again.` Had this for **a week** so I'm assuming, it's broken.
- I click "My Apps" or any link on [Dashboard on /webapps/](https://developer.paypal.com/webapps/developer/applications/myapps) and it takes me to the other, blue dashboard... so Now I'm thinking, is it just an old legacy thing?
- I read [Going Live 2](https://developer.paypal.com/docs/classic/lifecycle/goingLive/) and it says I have to do all this stuff, the Wiki doesn't say that...
- I go through the steps, most link me to things that do not exist... *"Click the Create and manage Classic API apps link at the bottom of the page."* ... that doesn't exist on the new Dashboard, only on that "legacy" looking one...
- I submit an application using the (old) dashboard and finding the link on there, but no idea if it will do anything... 

So now I'm at a loss, I don't know why I am getting this error and all documentation doesn't line up with what the dashboard is, links don't match up to instructions, screenshots don't match up to links....

The correct **LIVE API CREDENTIALS** have been copied (Client ID/Secret) and the mode set to `live`.

How do you go live?

*The documentation on this has just been utter frustrating, so sorry for the pre-tone.*

**Comment by tomwhipple** [comment]
@viion Thank you for your feedback on the docs. We will review the content.

In the mean time your best bet will be to [contact merchant support](https://www.paypal-techsupport.com/app/ask) to look in to what is happening for your account.

**Comment by ppmtscory** [comment]
@viion unfortunately there are some issue with the developer portal that are being worked through currently.  If you are able to login, and see your app that contains the Live credentials, those are what you need for your config file.  This [Dashboard](https://developer.paypal.com/developer/applications/) you were going to is the correct place to see your Apps.  If you click the [My Account](https://developer.paypal.com/developer/accountStatus/) link on the left, you'll see what your live credentials have been enabled for.  If you see anything there that isn't enabled, but you need it to be, simply click the enable link accordingly.

After checking your Live eligibility on the 'My Account' link I provided above, if you are seeing everything is enabled and are still getting the error, please let me know the debug ID of the error so that I can look up our logs to see what's happening.

The link you used for [Going Live 2](https://developer.paypal.com/docs/classic/lifecycle/goingLive/) is for our Classic Adaptive Payments applications and is not what you need.

**Comment by viion** [comment]
Hi @ppmtscory 

Thank you for the confirmation of the right Dashboard. Looking on that in **My Account** I have all I need  set to `enabled`, this would be: `Subscriptions` and `PayPal payments`. So everything in there is correct.

The items not enabled are: `Direct credit cards`, `Future Payments` and `Payouts`, but i should not need these for a single API `Payment` request?

I can't get the debug id right at the moment because it seems the API has just flat out gone down??

```
Array
(
    [0] => [PAYMENT] {"name":"INTERNAL_SERVICE_ERROR","information_link":"https://api.sandbox.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"7d500379a322a"}
)
```

That URL doesn't work...

**Comment by ppmtscory** [comment]
@viion Yes, it seems that's another side effect of the issues that are happening right now for sandbox.  Are you able to use your Live credentials (per your initial problem report)?

**Comment by ppmtscory** [comment]
@viion just FYI, the Sandbox issues should be resolved currently.

**Comment by viion** [comment]
This looks to be working now. 

I ended up deleting the app and remaking it this morning, the sandbox was working, the credentials used are working. 

Thank you!

**Comment by atulshrma91** [comment]
Iam  getting the error   {"error":"invalid_client","error_description":"Client Authentication failed"} . I have configured the paypal sdk REST API and  successfully generated the live app id . but in the my account page  in account eligibiltity for debit credit card and rest of  two option when i click enable it show me "Note: Live credentials are disabled for direct credit card processing in your app. At the moment, we can't enable this based on the information provided. You will be able to try again in 90 days. For more information, please visit the PayPal Help Center". Is this the problem. what can i do to figure it out . please help me as soon as possible .THANKS 

[paypal.docx](https://github.com/paypal/PayPal-PHP-SDK/files/269940/paypal.docx)

**Comment by viion** [comment]
@atulshrma91 Your docx file contains sensitive information, I'd suggest removing it.

Also, in your `$apiContext->setConfig()` array, you need to set: `mode => 'live'`

```php
$apiContext->setConfig(
            array(
                'log.LogEnabled' => true,
                'log.FileName' => 'PayPal.log',
                'log.LogLevel' => 'FINE',
                'mode' => 'live',
            )
    );
```

I believe by default it goes to Sandbox, I have had that issue in the past.

**Comment by atulshrma91** [comment]
i did exactly as per your instructions now it gave me error {"name":"UNAUTHORIZED_PAYMENT","message":"Unauthorized payment","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#UNAUTHORIZED_PAYMENT","debug_id":"e9b910795061e"}
and i configured the settings in the sdk_config. I am facing issues while going live,paypal is working fine in sandbox mode. Please help me out of this . Thankyou
[sdk_config.docx](https://github.com/paypal/PayPal-PHP-SDK/files/270078/sdk_config.docx)

**Comment by viion** [comment]
You should create a new issue as that is a different issue than the one for this thread. This will give you more visibility to hopefully figure it out.

My first guess would be the issue you have on your account, you mentioned you have direct credit cards are disabled, this could be the issue? Have you tried using a payment with money already in your balance rather than taking it from a source? If this works, then your issue is with payment providers. This is a more higher level issue than the API and you would need to contact the PayPal team to solve it.

**Comment by atulshrma91** [comment]
and i thought i might have written something bad in the code. Thanks for your help and i will talk to the paypal regarding this .and one  more thing do that direct debit card option is enabled in your account by default  and do i have to put the live app id somewhere in code or they will recognize it with client secret and id  as they are doing  it in  the sandbox  mode. Thank you Viion.

**Comment by nikkwong** [comment]
I'm also experiencing this, and can not get any response from technical support, can someone help? Thank you.

**Comment by chi11ax** [comment]
I'm also experiencing this. Created a new app with new ID and new Secret and they also don't work.

**Comment by akhiltanveer** [comment]
please refer
https://developer.paypal.com/docs/api/overview/#api-requests

when using live credentials
 the url should be  https://api.paypal.com
instead 
https://api.**sandbox**.paypal.com
