### ISSUE TITLE
when hit back button in the browser, the page goes to returnUrl instead of cancelUrl

### ISSUE THREAD

**Issue by shangsunset** [paypal/PayPal-PHP-SDK#436]
im testing in sandbox and i noticed that when the user proceeds to paypal sign in page to approve payment, if users want to go back to the site with back button,  they will be directed to returnUrl with paymentId and PayerID showing from last payment. how to direct them back the cancelUrl when users hit back button in browser? thanks.

```php
        $redirectUrls = new RedirectUrls();
        $redirectUrls->setReturnUrl(URL::to('/subscription/result'))
            ->setCancelUrl(URL::to('/subscription/plans'));

        $payment->setIntent("sale")
            ->setPayer($payer)
            ->setRedirectUrls($redirectUrls)
            ->setTransactions(array($transaction));
```

**Comment by jaypatel512** [comment]
Hey @shangsunset !

I am not able to reproduce this issue. I am logging into the paypal account, and clicking back on the browser, it takes me back to the login screen. Can you please provide bit more details on this ? 

1. Which browser are you facing this issue ? 
2. Is it on Mac or Windows ?
3. At what exact part of the flow, you click back ?

Here is the gif demonstrating the behavior. Please re-open the issue if you are not seeing as expected.
![vcsq7k6flz](https://cloud.githubusercontent.com/assets/1309895/11154936/db704776-8a07-11e5-9836-feaab4dc895d.gif)

**Comment by shangsunset** [comment]
Hey @jaypatel512 !

this happens before logging into paypal on paypal login page. i can produce this problem by clicking back button before logging into paypal account.
I tried in chrome and firefox on mac and got the same results.

there are two different situations: 
say i have urls like `/'`, `/subscription/plans`, and `/subscription/result`. the `returnUrl` is to `/subscription/result` and the `cancelUrl` is to `/subscription/plans`.

1. when the browser is opened fresh, if i hit back button on login in page on paypal, i get directed back to `/` instead of `/subscription/plans`.  
2. when i have paid with paypal successfully and want to pay again, if i hit back button, instead of returning to `/subscription/plans`, i will get redirected back from paypal login page to `/subscripton/result?paymentid=...` where `paymentId` and `payID` are from the last payment.

bwt, how can i get the new UI for paypal payment like your gif. thanks for your time.
