### ISSUE TITLE
set landing_page?

### ISSUE THREAD

**Issue by SnguonTheara** [paypal/PayPal-PHP-SDK#437]
I don know how to set landing_page using this package. Anyone please help me. Thank you very much.

**Comment by jaypatel512** [comment]
You need to create a payment-experience, and add its `id` to the regular payment flow during creation.

Here are the steps:

1. Create a payment experience : [Sample](http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payment-experience/CreateWebProfile.html)
2. Store the Id returned somewhere, if you intend to use the same experience for all your payment flows.
3. Everytime, you create a payment, add above `id` to payment: [Source](http://paypal.github.io/PayPal-PHP-SDK/docs/class-PayPal.Api.Payment.html#_setExperienceProfileId)
4. Thats it.

**Comment by SnguonTheara** [comment]
[image: Inline image 1]



Please Help me i want my checkout default with this landing page. How can
do by using you the package?
