### ISSUE TITLE
For checkout alternative

### ISSUE THREAD

**Issue by SnguonTheara** [paypal/PayPal-PHP-SDK#438]
I want default credit card page not paypal account when checkout. Please help me thank you very much. 
<img width="1121" alt="screen shot 2015-11-14 at 12 54 07 pm" src="https://cloud.githubusercontent.com/assets/9159944/11162817/0387d822-8ae5-11e5-8f09-8faa0ddcd769.png">

**Comment by ppmtscory** [comment]
@SnguonTheara you first need to create an [Experience Profile](https://developer.paypal.com/docs/api/#payment-experience) with the appropriate `landing_page_type` set.  Then you'll pass in that experience profile with your [payment creation](https://developer.paypal.com/docs/api/#payment-object).
