### ISSUE TITLE
Where can i set the access token?? Payments going into wrong account.

### ISSUE THREAD

**Issue by jamstarter** [paypal/PayPal-PHP-SDK#441]
I understand that there is a cache in the PHP SDK. I'm trying to allow a user to setup paypal as an available gateway in my application. I'm currently in sandbox mode. No matter how I try to run a charge, it always ends up in the account I set my app up with and doesn't go into the connected account for which I received the access token. I've tried manually setting it a number of ways. Not sure what I'm doing wrong.

	/**
	 * Authenticate user
	 * @param  object $params Params from setup
	 */
	public function auth($params){
		//set params
		$this->_params = $params;

		$this->_endpoint = Config::get('app.paypal.endpoint');
		$this->_consent_endpoint = Config::get('app.paypal.consent_endpoint');
		
	
		$this->_client_id = Config::get('app.paypal.client_id');    // ClientID
		
		$this->_client_secret =  Config::get('app.paypal.client_secret');
		 
		$this->_scope = array('openid','https://api.paypal.com/v1/payments/.*', 
			'https://api.paypal.com/v1/vault/credit-card/.*',

		 );

		if(isset($this->_params->access_token)){
			$sdkConfig = array(
				"mode" => Config::get('app.paypal.mode'),
		//		"access_token" => $this->_params->access_token
			);
		} else {
			$sdkConfig = array("mode" => Config::get('app.paypal.mode'));
		}
		//create api context
		$this->_apiContext = new \PayPal\Rest\ApiContext(
		    new \PayPal\Auth\OAuthTokenCredential($this->_client_id,$this->_client_secret,$sdkConfig)
		);

	//	if(isset($this->_params->access_token)){
	//		$this->_apiContext->access_token = $this->_params->access_token;
	//	}

		$this->_apiContext->setConfig(array(
			'http.ConnectionTimeOut' => 30,
			'http.Retry' => 1,
			'mode' => 'sandbox',
			'log.LogEnabled' => true,
			'log.FileName' => '/PayPal.log',
			'log.LogLevel' => 'INFO'		
		));

		return json_encode(['status'=>'success']); 
	}

	public function processOAuth(){
		$this->auth(array());
		$data = Input::all();
		if(!isset($data['error'])){

	
				$code = $data['code'];

    		try {

        		$accessToken = OpenIdTokeninfo::createFromAuthorizationCode(array('code' => $code), null, null, $this->_apiContext);
        		$metadata = array();
        
				$metadata['token_type'] = $accessToken->token_type;
				$metadata['expires_in'] = $accessToken->expires_in;
				$metadata['refresh_token'] = $accessToken->refresh_token;
				$metadata['id_token'] = $accessToken->id_token;
				$metadata['access_token'] = $accessToken->access_token;

        		        $gateway = new Gateway;
				$gateway->type = 'PayPal';
				$gateway->name = 'PayPal';
				$gateway->params = json_encode($metadata);

				$gateway->expires = strtotime('now') + $metadata['expires_in'];
				$gateway->user_id = Auth::user()->get()->id;

				$gateway->save();

				return Redirect::to("/gateways");

			    } catch (PayPalConnectionException $ex) {

			 		ResultPrinter::printError("Obtained Access Token", "Access Token", null, $_GET['code'], $ex);
			        exit(1);
			    }

		} else {
			return Redirect::to("/gateways")->with('error',urldecode($data['error_description']));
		}

		
	}

	public function addCardToCustomer($customer,$cardData){
	
		$card = new CreditCard();
		$card->setType(strtolower($cardData['brand']))->setNumber($cardData['number'])
	    ->setExpireMonth($cardData['exp_month'])
	    ->setExpireYear(date('Y',strtotime($cardData['exp_year'].'-01-01')))
	    ->setCvv2($cardData['cvc'])
	    ->setFirstName($cardData['first_name'])
	    ->setLastName($cardData['last_name']);

		$card->setMerchantId($customer->user_id);
		$card->setExternalCardId("PayPalCard" . uniqid());
		$card->setExternalCustomerId($customer->email);

		$request = clone $card;

		$card->create($this->_apiContext);

		//add card and store in gateway

		$return = array(
			'gateway_reference' => $card->id,
			'brand' => $card->type,
			'funding' => 'Credit',
			'country' => $cardData['country'],
			'last4' => substr($cardData['number'], -4),
			'customer_id' => $customer->id
			);
		//return data
		return $return;
	}

			/**
	 * Create a charge from a customer object
	 * @param  object $customer      PW Customer Object
	 * @param  array $chargeDetails Charge details
	 * @return array  Charge Details
	 */
	public function createChargeByCustomer($customer,$chargeDetails){

		//run charge
		//get default card
		$defaultCard = Card::where('id','=',$customer->default_card)->first();

		$creditCardToken = new CreditCardToken();
		$creditCardToken->setCreditCardId($defaultCard->gateway_reference);

		$fi = new FundingInstrument();
		$fi->setCreditCardToken($creditCardToken);

		$payer = new Payer();
		$payer->setPaymentMethod("credit_card")
		    ->setFundingInstruments(array($fi));

	// Specify the payment amount.
		$amount = new Amount();
		$amount->setCurrency($chargeDetails['currency']);
		$amount->setTotal($chargeDetails['amount']);
		// ###Transaction
		// A transaction defines the contract of a
		// payment - what is the payment for and who
		// is fulfilling it. Transaction is created with
		// a `Payee` and `Amount` types
		$transaction = new Transaction();
		$transaction->setAmount($amount);
		$transaction->setDescription($chargeDetails['description']);
		
		$payment = new Payment();
		$payment->setIntent("sale");
		$payment->setPayer($payer);
		$payment->setTransactions(array($transaction));

		$request = clone $payment;

		$payment->create($this->_apiContext);

      //build repsonse
		$return = array(
			'gateway_reference' => $payment->transactions[0]->related_resources[0]->sale->id,
			'amount' => $chargeDetails['amount'],
			'currency' => $chargeDetails['currency'],
			'customer_id' => $customer->id,
			'description' => $chargeDetails['description'],
			);
		//print_r($return); die();
		//return data
		return $return;

		
	}

**Comment by ppmtscory** [comment]
@jamstarter it appears that you're storing the `access_token` that you get from the `processOAuth()` function first in the `$metadata` array and then in `$gateway->params`.  However, when you are storing the card and/or processing the payment, you reference `$this->_apiContext`, which doesn't seem to be ever getting the customer's access token that's still stored in `$gateway->params`.  As far as I can tell, your `apiContext` is still using your client credentials that it's set up with initially.

**Comment by jamstarter** [comment]
@ppmtscory Yes I believe thats whats happening. My question is - how can I pass the access token into the apiContext? I can't seem to find any docs that reference how to set the access_token in apiContext manually... :(

**Comment by ppmtscory** [comment]
[OAuthTokenCredential.php](https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Auth/OAuthTokenCredential.php) has a function to `updateAccessToken` based on a `refresh_token` that you've stored for the customer.  The access token generated from this should be specific to that merchant as it was generated from their authorization code.

**Comment by jamstarter** [comment]
Do I call updateAccessToken on $apiContext? can you point me to an example in a doc somewhere? I'm not sure where I need to add this. I have a refresh_token stored.

               //create api context
		$this->_apiContext = new \PayPal\Rest\ApiContext(
		    new \PayPal\Auth\OAuthTokenCredential($this->_client_id,$this->_client_secret,$sdkConfig)
		);

can I call it directly on $this->_apiContext like this?

           $this->_apiContext->updateAccessToken($sdkConfig,$this->_params->refresh_token);

**Comment by jamstarter** [comment]
Doesn't seem to work...

**Comment by ppmtscory** [comment]
There's an example in the [CreateFuturePayment](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/CreateFuturePayment.php) sample.  Line 70 is where it gets the refresh token from auth code and then line 73 is where it calls updateAccessToken.

**Comment by jamstarter** [comment]
Thanks, but that looks like it is called on $payment. So the first step i have is vaulting the card. When I do this, I get an error - Call to undefined method PayPal\Api\CreditCard::updateAccessToken(). Since I'm trying to act on behalf of a user, I need to add the card first before I make the payment, so I can't test calling it on $payment yet..... Am I just totally off base here?

             $card = new CreditCard();
		$card->setType(strtolower($cardData['brand']))->setNumber($cardData['number'])
	    ->setExpireMonth($cardData['exp_month'])
	    ->setExpireYear(date('Y',strtotime($cardData['exp_year'].'-01-01')))
	    ->setCvv2($cardData['cvc'])
	    ->setFirstName($cardData['first_name'])
	    ->setLastName($cardData['last_name']);

		$card->setMerchantId($customer->user_id);
		$card->setExternalCardId("PayPalCard" . uniqid());
		$card->setExternalCustomerId($customer->email);

		$request = clone $card;

		// Update the access token in apiContext
   		 $card->updateAccessToken($this->_params->refresh_token, $this->_apiContext);


		$card->create($this->_apiContext);

**Comment by jamstarter** [comment]
Maybe it will help to spell out the steps I'm going through....

1. Merchant signs up on my website and connects their PayPal account using oauth.
2. Merchant comes back the next day and adds a customer to their account on my site
3. Merchant stores a credit card for that customer in PayPal vault
4. Merchant schedules a payment to be made in 2 weeks.
5. Two weeks later, my application charges the stored card for the payment amount specified by the merchant

**Comment by tomwhipple** [comment]
You should not be using Future Payment or refresh tokens for this case. Just get a new access token prior to each session. An access token is valid for only 15 min.

**Comment by jamstarter** [comment]
Right I know. I'm not using future payments. That was just what was in the example that you sent me.

I have everything working EXCEPT being able to act on behalf of a user. The entire problem is that when I store a card or process a payment it goes into MY paypal account.

I just need to know how to set the access token so I can store a card and run a payment on behalf of a user so that the card and payment are associated with their account and not the account connected to my client id and secret.

**Comment by jamstarter** [comment]
Is this possible with the REST API? I've been searching for days to find any docs with an example of how to do this.....

**Comment by jamstarter** [comment]
Anyone?

**Comment by tomwhipple** [comment]
From poking around a bit, it looks like maybe you're trying to offer the ability to essentially proxy for a 3rd party merchant? In some of the product descriptions, that business model is referred to as a "partner". I'd recommend looking at the [Braintree Partner API](https://developers.braintreepayments.com/guides/partner-api/overview) and perhaps chatting with the sales team to help select the right product.

The primary design of the SDKs & APIs they depend upon assumes that they have access to the `client_id` and, for back-end cases, the `client_secret`. Refresh tokens aren't currently implemented for the proxy model you describe, rather they're typically used to enable consumers to delegate a more limited set of permissions to a merchant.

**Comment by jamstarter** [comment]
I've already integrated braintree, stripe and authorize.net. PayPal is a must. Is there really no way for me to accomplish this with PayPal? It seems that sites like Shopify and Recurly us PayPal on behalf of their users. I guess I could ask the merchant to supply their client_id and client_secret, but that seems a little intrusive, doesn't it?

**Comment by ppmtscory** [comment]
Processing on behalf of others can be done with certain products with PayPal, but CC Vaulting is not one of them.  You'd definitely want to reach out to our [Merchant Tech Support](https://www.paypal-techsupport.com/app/ask) folks regarding third party processing with our Classic APIs.

**Comment by sessionstart** [comment]
https://www.youtube.com/watch?v=BD1dOWIABe0

I followed this tutorial and made it. Have a try.

**Comment by ppmtscory** [comment]
@sessionstart that's a great video for first party payments (receiving payments into your own merchant account).  

Closing this as the feature requested is unavailable at this time and so you'd need to contact the [Merchant Tech Support](https://www.paypal-techsupport.com/app/ask) team to consult on the best solution available for third party processing.
