### ISSUE TITLE
How can I change the payment page layout to the new layout?

### ISSUE THREAD

**Issue by Newbie012** [paypal/PayPal-PHP-SDK#443]
I've already asked in stackoverflow (http://stackoverflow.com/questions/33735153/a-little-issue-with-paypal-express-checkout-with-paypal-in-context) and I haven't received an answer.

Does anyone knows how can I do this?

**Comment by jaypatel512** [comment]
Hey @Newbie012 !

The selection on who gets the new layout is randomly based on the client. We are pushing all the major traffic eventually to the new layout, however, this is done in steps, and may change your account later. 

However, you could try creating a new app in developer dashboard to test your luck :)
