### ISSUE TITLE
Billing Agreements not getting cancelled on initial payment fail 

### ISSUE THREAD

**Issue by JayBhatt** [paypal/PayPal-PHP-SDK#445]
Hi,

While processing recurring payments, I am charging users initial amount using merchant preference -> setup_fees. 

When this initial amount or setup_fee fails I want the whole transaction to fail. To achieve this I am setting **"initial_fail_amount_action"** to **"CANCEL"** in merchant preference. But its not behaving as expected. Even when the initial amount fails the recurring payment profile is created and approved without any errors. 

Am I doing anything wrong here? or Is this a bug? Below is my code for crating a billing plan.

    $description = 'Sample Billing Plan';
    $billingPlan = new Plan();
    $billingPlan->setName('Payment plan for '.$description);
    $billingPlan->setDescription($description);
    $billingPlan->setType("FIXED");

    $paymentDefinition = new PaymentDefinition();
    $paymentDefinition->setName('Charge for '.$description);
    $paymentDefinition->setType('REGULAR');
    $paymentDefinition->setFrequencyInterval("1");
    $paymentDefinition->setFrequency("MONTH");
    $paymentDefinition->setCycles("2");

    $amount = new Currency();
    $amount->setCurrency("GBP");
    $amount->setValue(49.99);

    $paymentDefinition->setAmount($amount);

    $shippingAmount = new Currency();
    $shippingAmount->setCurrency("GBP");
    $shippingAmount->setValue(0);

    $chargeModelShipping = new ChargeModel();
    $chargeModelShipping->setType('SHIPPING');
    $chargeModelShipping->setAmount($shippingAmount);

    $taxAmount = new Currency();
    $taxAmount->setCurrency($this->getCurrency());
    $taxAmount->setValue(0);

    $chargeModelTax = new ChargeModel();
    $chargeModelTax->setType('TAX');
    $chargeModelTax->setAmount($taxAmount);

    $paymentDefinition->setChargeModels(array($chargeModelShipping, $chargeModelTax));

    $billingPlan->setPaymentDefinitions(array($paymentDefinition));

    $merchantPreferences = new MerchantPreferences();

    $setupFeesAmount = new Currency();
    $setupFeesAmount->setCurrency($this->getCurrency());
    $setupFeesAmount->setValue($cartSummary->firstInstallmentCost);

    $merchantPreferences->setSetupFee($setupFeesAmount);
    $merchantPreferences->setMaxFailAttempts("0");
    $merchantPreferences->setAutoBillAmount("YES");
    $merchantPreferences->setInitialFailAmountAction("CANCEL");
    $billingPlan->setMerchantPreferences($merchantPreferences);

    return $billingPlan->create($apiContext);

Below is the PayPal IPN notification which I got after the initial amount failed.

`Payment Cycle = Monthly
Txn Type = recurring_payment_profile_created
Initial Payment Status = Failed
Initial Payment Amount = 57.94
Profile Status = Active
Amount = 49.99
Outstanding Balance = 57.94`

Thanks in advance. 

Jay

**Comment by ppmtscory** [comment]
@JayBhatt is this for Live or Sandbox?

**Comment by JayBhatt** [comment]
@ppmtscory this is live.

**Comment by JayBhatt** [comment]
@ppmtscory this is when I used credit/debit card payments.

**Comment by ppmtscory** [comment]
@JayBhatt thank you for the update.  Since this is Live, and I don't want you to put Live account information in this public forum, can you please file a ticket with our [Merchant Tech Support](https://www.paypal-techsupport.com/app/ask) team?  In the message, please include the email address of your account, the profile ID of the agreement in question, and also the date/time stamp (with timezone) of when this was created and initial payment failed.  They will be able to look it up based on that information and let you know what's going on.  Please post your ticket number back here so that I can keep tabs on it and mark this issue as resolved once we figure everything out.
