### ISSUE TITLE
unlimited cycles for recurring payments

### ISSUE THREAD

**Issue by sarathvs123git** [paypal/PayPal-PHP-SDK#446]
Hi,
      I need to set unlimited cycles for my recurring payments .
    I added the below values in paymentDefinition

  $paymentDefinition->setName('Recurring Payments')
    ->setType('INFINITE')
    ->setFrequency('Month')
    ->setFrequencyInterval("1")
    ->setCycles(0)

But I got   
Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/billing-plans

  "details": [
        {
            "field": "payment_definitions[0].type",
            "issue": "Payment Definition type passed is either null/invalid. Valid values are TRIAL or REGULAR."
        }
    ],

**Comment by jaypatel512** [comment]
As you can see in the [developer docs](https://developer.paypal.com/webapps/developer/docs/api/#paymentdefinition-object), you need to either set the type to `TRIAL` or `REGULAR`. The way to set the cycles to infinite, is to set it to 0, and it should do it. Please set the type to `REGULAR` and you should be fine.

**Comment by chief-kh** [comment]
You should add such information in method description.
 /**
     * Number of cycles in this payment definition.
     * use 0 for infinite payments
     *
     * @param string $cycles
     * 
     * @return $this
     */
public function setCycles($cycles)
...

**Comment by jesusvazquez90** [comment]
@chief-kh I set 0 cycles and I get the same error 400, only the plan is created if I define a value greater than 0
```

$paymentDefinition = new PaymentDefinition();
        $paymentDefinition->setName('Regular Payments')
            ->setType('REGULAR')
            ->setFrequency('Month')
            ->setFrequencyInterval("1")
            ->setCycles('0')
            ->setAmount(new Currency(array('value' => '9.99', 'currency' => 'USD')));
        
```
