### ISSUE TITLE
Will be possible to use the Paypal RestFul API to process a payment with a Maestro credit card

### ISSUE THREAD

**Issue by sudar77** [paypal/PayPal-PHP-SDK#447]
Im using the PayPal-PHP-SDK to create a payment - my code is meant to be designed for only maestro card payments.

Does anyone know of any sample code as all samples I can find are for Credit Cards such as Visa or Mastercard etc?

My code that im trying to debug looks a little like the  following (using sample card details):

$card = new PaymentCard();
$card->setType("Maestro")
    ->setNumber("6331101999990016")
    ->setExpireMonth("11")
    ->setExpireYear("2019")
    ->setStartMonth("11")
    ->setStartYear("2015")
    ->setCvv2("012")
    ->setFirstName("Joe 1231")
    ->setLastName("Shopper")
    ->setBillingCountry("UK");

$fi = new FundingInstrument();
$fi->setPaymentCard($card);

$payer = new Payer();
$payer->setPaymentMethod("credit_card")
    ->setFundingInstruments(array($fi));

etc.
but this produces an error:

exception 'PayPal\Exception\PayPalConnectionException' with message 'Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payment.'

**Comment by ppmtscory** [comment]
@sudar77 it may be possible in the future, but at this time, only `visa`, `mastercard`, `discover`, and `amex` are supported for [credit card types](https://developer.paypal.com/docs/api/#creditcard-object)
