### ISSUE TITLE
Message parsing failure on http 100 continue responses

### ISSUE THREAD

**Issue by bhoehl** [paypal/PayPal-PHP-SDK#452]
When creating an instant payment and setting items to be paid, it happens to us that the request being transferred to PayPal is around 11000 bytes. 
This causes the, at the moment sandbox system, to respond with additional HTTP 100 continue messages, which are prepended to the server response.
Your parser is unable to extract the correct json and we are no longer getting any approval url.
see PayPalHttpConnection::execute($data)
I have tried to add the header 'Expect:', so it does no longer return it, but the parsing of the HTTP response still fails.
Another solution might, be switching to Guzzle, which I have done after adding 'Expect:', to at least parse the message correctly:
$response = \Guzzle\Http\Message\Response::fromMessage($result);
$result = (string)($response->getBody());
$responseHeaders = $response->getRawHeaders();

Example response:
HTTP/1.1 100 Continue

HTTP/1.1 201 Created
Date: Wed, 02 Dec 2015 15:05:03 GMT
Server: Apache
PROXY_SERVER_INFO: host=slcsbplatformapiserv3002.slc.paypal.com;threadId=368
Paypal-Debug-Id: b5bdd931a79c1
CORRELATION-ID: b5bdd931a79c1
Content-Language: *
Paypal-Debug-Id: b5bdd931a79c1
Vary: Authorization
Content-Type: application/json
Set-Cookie: X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D880%26app%3Dplatformapiserv%26TIME%3D2668126038; domain=.paypal.com; path=/; Secure; HttpOnly
Set-Cookie: X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT
Connection: close
Transfer-Encoding: chunked

**Comment by jaypatel512** [comment]
The release has been made with the fix : https://github.com/paypal/PayPal-PHP-SDK/releases/tag/v1.6.3

Please let me know if that resolves the issue for you.
