### ISSUE TITLE
Billing Agreement Description

### ISSUE THREAD

**Issue by sarathvs123git** [paypal/PayPal-PHP-SDK#454]
Hi,
    I am creating billing agreement with the sdk and it works. When I add billing description , It doesn't allow line breaks in the description .
 
 $description = "Membership payment for 10 per month ";
 $description.= "\n  Initial amount : 10 ";
  $agreement ->setDescription($description);

   I had used '<br>','\n 'etc for line break but it doesn't work . 
   How can I add  line break in description

**Comment by jaypatel512** [comment]
From the looks of it, it looks like this is not possible, as we suppress any special characters. This is done for better UI control. I will however, send this request to the UI team to see if this could be enabled.
