### ISSUE TITLE
Can't view my Webhook Dashboard

### ISSUE THREAD

**Issue by moiroca** [paypal/PayPal-PHP-SDK#456]
err: "Internal server error" statusCode: 500 sys: {,…} links: {jsBaseUrl: "https://www.paypalobjects.com/web/res/f8a/fc7e6bb2a10c36f82e70d27419e10/js",…} locality: {timezone: {determiner: "viaUserProfile", value: "Asia/Manila"}, country: "PH", locale: "en_US",…} pageInfo: {date: "Dec 8, 2015 19:37:53 -08:00",…} tracking: {fpti: {name: "pta", jsURL: "//www.paypalobjects.com", serverURL: "https://t.paypal.com/ts",…},…} url: "/dashboard/webhooks/filter-events?client_id=AXTbdKLy-W7oR7FO-881FlflBsIRutbuZBet0TpQj39-lB8FWAGrqhY_AIXHRNniKuSfEEzD37XPEO18&start_time=2015-11-10T00:00:00+08:00&end_time=2015-12-09T11:37:53+08:00&isSandbox=true" Name Path

**Comment by jaypatel512** [comment]
This issue seems to be related to the developer dashboard. Please contact [MTS](https://www.paypal-techsupport.com/app/ask) for this issue. This issue tracker is limited to PHP SDK issues only.
