### ISSUE TITLE
can't checkout in live mode

### ISSUE THREAD

**Issue by inuvalogic** [paypal/PayPal-PHP-SDK#459]
thanks for this amazing php sdk library, it save my work

I'm using REST API from example code in pizza web for my ecommerce site, so the user can checkout using his/her credit card directly, in sandbox mode the transaction is success, but it can't checkout in live mode, it's always throw 400 error

having tried several credit card for this test, but still no luck

**Comment by jaypatel512** [comment]
You need to get more details on what exactly it is failing with. To do so, follow the instructions [shown here](https://github.com/paypal/PayPal-PHP-SDK/wiki/exception-%27PayPal%5CException%5CPayPalConnectionException%27-with-message-%27Got-Http-response-code-400-when-accessing). 

Once done, you should be able to get the detailed message of the issue.

**Comment by jaypatel512** [comment]
I am closing this issue as it requires more information for now. Please re-open this issue if the above comment does not help fix the issue.
