### ISSUE TITLE
Change Field Name Tax To Vat.

### ISSUE THREAD

**Issue by ankitvadariya** [paypal/PayPal-PHP-SDK#460]
Hi
I am using PHP paypal Restfull SDK.
When user will redirect to paypal site for payment. as we know display items list & amount information.
but i need to display VAT in replacement of Tax Label.

How can i change label of Tax ?
Please let me know .

Thanks :-)
Ankit Vadariya

**Comment by jaypatel512** [comment]
Updating the Labels on the UI is not available in PayPal. However, developers generally add vat tax as a `tax` itself.

**Comment by ankitvadariya** [comment]
![vat](https://cloud.githubusercontent.com/assets/7002111/12071725/15789c2a-b0e1-11e5-8ea6-4a01b4c205b2.png)

Here is the one of example. I had already used. its already done in NVP .
But i need it with RestFull API.

**Comment by KylaZhen** [comment]
@ankitvadariya ,
I also want to change 'VAT' to 'TAX'. I would like to how you change the label with NVP?

**Comment by ankitvadariya** [comment]
@KylaZhen  I for the NVP you can change it from merchant account there is some settings for design & labels but i am not sure... 

Thanks 
Ankit
