### ISSUE TITLE
Documentation and sample differences

### ISSUE THREAD

**Issue by Newbas** [paypal/PayPal-PHP-SDK#462]
Hi thank you for SDK and samples. 
I checked samples and docomentation, and found little difference.
[Here](https://developer.paypal.com/docs/integration/web/accept-paypal-payment/) 
return url is `http://<return_url>?paymentId=PAY-6RV70583SB702805EKEYSZ6Y&token=EC-60U79048BN7719609&PayerID=7E7MGXCWTTKK2`, and when testing i see it. 

[In this sample](http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/ExecutePayment.html) 
```
if (isset($_GET['success']) && $_GET['success'] == 'true') 
```
status parameter is expected, and seems that it does not appear in response. 

Thanks.

**Comment by jaypatel512** [comment]
Hey @Newbas !

Actually, the success variable is something that we pass [when setting the url](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/CreatePaymentUsingPayPal.php#L77-L78). The reason we did it this way is to demonstrate that you can actually pass parameters to the urls, that will be passed on to the return url once the user has completed the flow and is returned back to you. 

You necessarily do not have to add the success parameter, however, this is one way to differentiate between a cancel url and redirect url.
