### ISSUE TITLE
Variable value, pre-authorised, repeat payments on PayPal accounts

### ISSUE THREAD

**Issue by paultarr** [paypal/PayPal-PHP-SDK#464]
I've had a look through everything currently available in the REST API and at present it doesn't appear possible to make repeat, variable value payments against a PayPal account in a similar way as Vaulted Cards or Reference transactions in the classic API.

Is there a timeline to implement repeat payments on PayPal accounts (with varying amounts) via the REST API?

**Comment by jaypatel512** [comment]
If you are looking for vault apis, and creating payments using vault credit cards, there you go:

### Vault API 
- Samples: http://paypal.github.io/PayPal-PHP-SDK/sample/#vault
- Docs: https://developer.paypal.com/webapps/developer/docs/api/#vault

### Creating Payment using Saved Credit Card (Vaulted Credit Card)
- Samples :  http://paypal.github.io/PayPal-PHP-SDK/sample/#0d537fdbf8793ccfb1c851174f4607e6
- Docs : https://developer.paypal.com/webapps/developer/docs/api/#create-a-payment

**Comment by paultarr** [comment]
Hi Jay,

We already have vaulted card payments, I'm referring specifically to the ability to transact against a user's PayPal account (not credit card) and the ability to perform future payments of varying value without obtaining additional authorisation.
