### ISSUE TITLE
How to get invoice numbers after payment approved

### ISSUE THREAD

**Issue by conmen80** [paypal/PayPal-PHP-SDK#465]
After an execution of payment, I want to have payment's info such as invoice number and buyer's info for further process,  I have call `$info = $payment->getTransactions()` to view payment's details after payment approved, print as `print_r($info)`:

`Array ( [0] => PayPal\Api\Transaction Object ( [_propMap:PayPal\Common\PayPalModel:private] => Array ( [amount] => PayPal\Api\Amount Object ( [_propMap:PayPal\Common\PayPalModel:private] => Array ( [total] => 56.00 [currency] => GBP [details] => PayPal\Api\Details Object ( [_propMap:PayPal\Common\PayPalModel:private] => Array ( [subtotal] => 46.00 [shipping] => 10.00 ) ) ) ) [payee] => PayPal\Api\Payee Object ( [_propMap:PayPal\Common\PayPalModel:private] => Array ( [email] => myshop@example.com ) ) [description] => Payment description [invoice_number] => 0AGIRVBYCOLK [item_list] => PayPal\Api\ItemList Object ( [_propMap:PayPal\Common\PayPalModel:private] => Array ( [items] => Array ( [0] => PayPal\Api\Item Object ( [_propMap:PayPal\Common\PayPalModel:private] => Array ( [name] => Blossom Cherry [price] => 20.00 [currency] => GBP [quantity] => 1 [description] => Tanks / Womens - M ) ) [1] => PayPal\Api\Item Object ( [_propMap:PayPal\Common\PayPalModel:private] => Array ( [name] => Space Sheep [price] => 26.00 [currency] => GBP [quantity] => 1 [description] => Roundnecks / Mens - L ) ) ) [shipping_address] => PayPal\Api\ShippingAddress Object ( [_propMap:PayPal\Common\PayPalModel:private] => Array ( [recipient_name] => test buyer [line1] => Level 01, Wall Street [city] => ABC City [state] => Manchester [postal_code] => 12345 [country_code] => UK ) ) ) ) [related_resources] => Array ( ) [notify_url] => http://example.com/paypal/pp-ipn.php ) ) )`

How about if i want to pass `[invoice_number]` to SQL query? How do I get each array's data?

**Comment by jaypatel512** [comment]
Currently, getting a payment response based on invoice number is not directly supported in REST API. However, this feature is something that we have in our backlog.

For now, the way, you would want it would be to store the invoiceId and paymentId in your database, and use that to query the REST API that way.

**Comment by marcelo2605** [comment]
Hey guys. I need getting invoice_number from payment info. This is possible now?
