### ISSUE TITLE
Error 400 MALFORMED_REQUEST using setPurchaseUnitReferenceId()

### ISSUE THREAD

**Issue by KonstantinKolodnitsky** [paypal/PayPal-PHP-SDK#468]
Hi. I'm getting the same issue when trying to setPurchaseUnitReferenceId

Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payment

    $transaction = PayPal::Transaction();
    $transaction->setAmount(123);
    $transaction->setDescription($description);
    $transaction->setPurchaseUnitReferenceId($trans->id);

Also tried wrapping

    $transaction->setPurchaseUnitReferenceId("$trans->id");

Here is the error
"{"name":"MALFORMED_REQUEST","message":"Incoming JSON request does not map to API request","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#MALFORMED_REQUEST","debug_id":"3c6127fadc5a"}"

Here is the request json example

    '{"intent":"sale","payer":{"payment_method":"paypal"},"redirect_urls":{"return_url":"http://localhost:8082/checkout-done","cancel_url":"http://localhost:8082/checkout-cancel"},"transactions":[{"amount":{"currency":"AUD","total":"5"},"description":"Website Access","purchase_unit_reference_id":"13"}]}'

What I'm doing wrong?
Thanks

**Comment by pp-randy** [comment]
I tested your JSON and its returning an error because purchase_unit_reference_id is not part of the transaction object https://developer.paypal.com/docs/api/#transaction-object. When I see it, it is only in responses mainly for Orders.  

What are you attempting to track with this?  If it is for tracking a transaction you could look over invoice_number.

**Comment by KonstantinKolodnitsky** [comment]
Thanks. I will have a look to invoice number.
I'm using php sdk.
So why the lass Transactions has such a method?
http://paypal.github.io/PayPal-PHP-SDK/docs/class-PayPal.Api.Transaction.html#_setPurchaseUnitReferenceId

**Comment by pp-randy** [comment]
@KonstantinKolodnitsky I'm not entirely sure, looking at the error class I would reason purchase_unit_reference_id was deprecated. 

Did invoice number work out for you?

**Comment by KonstantinKolodnitsky** [comment]
@pp-randy Yes, I'm now using invoice number instead of purchase_unit_reference_id and it works just fine. Thanks for advise.
Just interested why the method setPurchaseUnitReferenceId() is for.
