### ISSUE TITLE
Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment/PAY-...../execute

### ISSUE THREAD

**Issue by KonstantinKolodnitsky** [paypal/PayPal-PHP-SDK#469]
Hi, couldn't find an issue for payment execution 500 error so I created new one. Sorry if it duplicates.

SOMETIMES!!! this error happens when I'm trying to execute payment.
For now I'm doing it on localhost.

There is the response:
{
	"status": 500,
	"duration_time": 14040,
	"body": {
		"message": "An internal service error has occurred",
		"debug_id": "28c6319d99207",
		"information_link": "https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR",
		"name": "INTERNAL_SERVICE_ERROR"
	},
	"additional_properties": {},
	"header": {
		"Content-Length": "212",
		"Content-Language": "*",
		"CORRELATION-ID": "28c6319d99207",
		"Date": "Sat, 16 Jan 2016 12:15:23 GMT",
		"Connection": "close",
		"Paypal-Debug-Id": "28c6319d99207",
		"PROXY_SERVER_INFO": "hostu003dslcsbplatformapiserv3002.slc.paypal.com;threadIdu003d272",
		"Content-Type": "application/json"
	}
}

And request:
{
	"body": {
		"payer_id": "23QQMFXRE23RN"
	},
	"header": {
		"x-pp-ads-performed": "false",
		"content-length": "28",
		"pp_remote_addr": "91.244.27.73",
		"x-pp-silover": "name%3DSANDBOX3.API.1%26silo_version%3D880%26app%3Dplatformapiserv%26TIME%3D1295293014",
		"paypal-request-id": "16777268728727145294650665230",
		"accept": "*/*",
		"client-auth": "No cert",
		"host": "api.sandbox.paypal.com",
		"x-pp-slingshot-targetapp": "platformapiserv",
		"x-pp-corrid": "28c6319d99207",
		"user-agent": "PayPalSDK/PayPal-PHP-SDK 1.3.2 (langu003dPHP;vu003d5.6.17-1+deb.sury.org~trusty+2;bitu003d64;osu003dLinux_3.13.0-74-generic;machineu003dx86_64;opensslu003d1.0.2e;curlu003d7.35.0)",
		"content-type": "application/json",
		"authorization": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx7YDm"
	},
	"additional_properties": {},
	"method": "POST"
}

my php code is the same as in example.

Can you help me please.

**Comment by danielberg1** [comment]
Hi. I am now developing the payment system with Stripe.I have no experience of doing with paypal_php_sdk.So I have nothing to help you. 😔
If i have anything to help you, I will.Hope to solve the problem.Bye
Date: Sat, 16 Jan 2016 04:39:31 -0800

**Comment by hakimny** [comment]
I have the same error : Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment
it started happening to me just today. not sure if it is related to all TLS changes

Please  shed some lights on this. We are stuck and not able to work.

Thx

**Comment by KonstantinKolodnitsky** [comment]
@hakimny there is a separate issue for your error
https://github.com/paypal/PayPal-PHP-SDK/issues/427

**Comment by pp-randy** [comment]
@KonstantinKolodnitsky Are you getting errors currently?  I saw a sandbox notification it was a day after your example; however, not sure if it resolved the underlying issue.

**Comment by KonstantinKolodnitsky** [comment]
@pp-randy Checked right now - no error. Will test more.

**Comment by roykho** [comment]
I am also getting this error recently with this endpoint `https://api.sandbox.paypal.com/v1/payments/payouts`

Full error here: `Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payouts?.`

**Comment by ppmtscory** [comment]
@roykho in order for us to help you out here, we'll need some debug IDs from your examples.  You should see this in the response headers with your 500 errors.

**Comment by jaypatel512** [comment]
Closing this issue based on inactivity. Please re-open if this issue still exists.

**Comment by mukeshra** [comment]
i getting error while using 

$payer->setPaymentMethod('paypalExpress');

Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment

**Comment by pp-randy** [comment]
@mukeshra please see this sample https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/CreatePaymentUsingPayPal.php#L23

$payer->setPaymentMethod("paypal");

**Comment by NikitaMelikhov** [comment]
Suddenly I began to get an error when I applied to payouts api, although I already did several such requests and they worked fine, and there were no changes in the code.

`object(PayPal\Exception\PayPalConnectionException)#24 (9) {
  ["url":"PayPal\Exception\PayPalConnectionException":private]=>
  string(51) "https://api.sandbox.paypal.com/v1/payments/payouts?"
  ["data":"PayPal\Exception\PayPalConnectionException":private]=>
  string(193) "{"name":"INTERNAL_ERROR","message":"An internal service error has occurred.","debug_id":"491368446dce","information_link":"https://developer.paypal.com/docs/api/payments.payouts-batch/#errors"}"
  ["message":protected]=>
  string(94) "Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payouts?."
  ["string":"Exception":private]=>
  string(0) ""
  ["code":protected]=>
  int(500)`

**Comment by pp-randy** [comment]
@NikitaMelikhov  please see https://github.com/paypal/PayPal-REST-API-issues/issues/130 to track the payouts issue further.

**Comment by pp-randy** [comment]
Locking the conversation. Please create a new issue for any 500 errors if you do not find an open one already in our API issue tracking repository [paypal/PayPal-REST-API-issues]( https://github.com/paypal/PayPal-REST-API-issues/).
