### ISSUE TITLE
Perform API requests on behalf of a user

### ISSUE THREAD

**Issue by blazerunner44** [paypal/PayPal-PHP-SDK#470]
I am wondering if it is possible to perform API requests on behalf of a third party user. For example, I would like to be able to do the following:
* **Process payments for my clients.** For example, one of my client's customers would need to make a payment to my client through my software. How do I send that payment into my clients paypal account rather than mine?
* **Process refunds from my client's paypal to their customers** so they never have to leave and go to paypal to process a refund.

Those are the two main things I need to do. I have read about the Permissions service here: https://developer.paypal.com/docs/classic/permissions-service/integration-guide/PermissionsAbout/ and I think that is what I need. Is there a way to do all of this with the SDK? If so, could someone point me in the right direction?

**Comment by pp-randy** [comment]
@blazerunner44 Unfortunately, at this time to do something similar with this SDK, your clients would need a REST application and share with you the client id and secret.  

Permissions service would be the right direction for now, you would use this with Classic SDKs though such as the Merchant SDK and also the Adaptive SDK. 

https://github.com/paypal/merchant-sdk-php#authentication
https://github.com/paypal/adaptivepayments-sdk-php#authentication

This is the line for permissions service for the two SDKs above
$cred->setThirdPartyAuthorization(new PPTokenAuthorization("accessToken", "tokenSecret"));

I am closing this issue, but let me know if you have further questions.
