### ISSUE TITLE
Transaction is being placed but without any deduction of money.

### ISSUE THREAD

**Issue by umarmughal824** [paypal/PayPal-PHP-SDK#471]
I have been using with laravel 4.2. I tried to get its solution from this website.
http://learninglaravel.net/integrate-paypal-sdk-into-laravel-4-laravel-5/link
I wrote the code as it is. 
But I got shocked its showing transaction but without any charging or deduction. After transaction my balance remains same even though by any way of paying.

By the way, I'm using 'paypal' as payment method. When I go to pay for it. It charges nothing even though have some positive values in cart.
In my developer account or sandbox in transaction. I see that fields only. No transactions are being processed in live version.

HTTP Status	URL	PayPal Debug ID	Transaction Date

No transaction amount included in it.

Please help me in this sort.
thanks

**Comment by umarmughal824** [comment]
here is my code
        $payer = new Payer();
        $payer->setPaymentMethod('paypal');

        $item_1 = new Item();
        $item_1->setName('Item 1') // item name
        ->setCurrency('USD')
            ->setQuantity(1)
            ->setPrice('1'); // unit price
        $item_list = new ItemList();
        $item_list->setItems(array($item_1/*, $item_2, $item_3*/));

        $amount = new Amount();
        $amount->setCurrency('USD')
            ->setTotal(1);

        $transaction = new Transaction();
        $transaction->setAmount($amount)
            ->setItemList($item_list)
            ->setDescription('Your transaction description')
            ->setInvoiceNumber(uniqid());

        $redirect_urls = new RedirectUrls();
        $redirect_urls->setReturnUrl(URL::route('store.confirmation'))
            ->setCancelUrl(URL::route('store.cancel'));

        $payment = new Payment();
        $payment->setIntent('Sale')
            ->setPayer($payer)
            ->setRedirectUrls($redirect_urls)
            ->setTransactions(array($transaction));

        try {
            $payment->create($this->_api_context);
        } catch (\PayPal\Exception\PPConnectionException $ex) {
            if (\Config::get('app.debug')) {
                echo "Exception: " . $ex->getMessage() . PHP_EOL;
                $err_data = json_decode($ex->getData(), true);
                exit;
            } else {
                die('Some error occur, sorry for inconvenient');
            }
        }

        foreach($payment->getLinks() as $link) {

            if($link->getRel() == 'approval_url') {
                $redirect_url = $link->getHref();
                break;
            }
        }

Its redirecting the page for both successful return and cancel return. but the only issue is its deducting the money from paypal.

**Comment by viion** [comment]
I am getting this issue, I do a purchase and API returns successful. No money is moved, nothing deducted from my account, nothing added to the recipients account.

The weird thing is, Paypal returns "Success" and even querying a Payment ID returns information of a payment, that never happened!?

**Comment by viion** [comment]
I found my issue, and it was related to execution being called much after a payment was done (likely a different issue). I tested a execution immediately after payment and this worked. Likely payments only last within PayPal system for a day or so.

**Comment by umarmughal824** [comment]
thanks I also fixed by executing the payment. thanks @viion 
i want to add you in my professional network.
my skype: umarscientist

**Comment by umarmughal824** [comment]
https://github.com/paypal/PayPal-PHP-SDK/issues/472
this is also my issue. I got the solution here.

**Comment by pp-randy** [comment]
@viion my guess is that you would need to execute a PayPal payment within three hours. It should be following Express Checkout rules https://developer.paypal.com/docs/classic/api/merchant/SetExpressCheckout_API_Operation_NVP/, reviewing token in the response it says 3 hour duration in the classic API documentation.

**Comment by umarmughal824** [comment]
I mean by setting paypal as payment method, will I be able to pay through any way (master card, debit card, credit card and paypal account).
