### ISSUE TITLE
Got Http response code 404 when accessing https://api.sandbox.paypal.com/v1/payments/payment.

### ISSUE THREAD

**Issue by muddy-28** [paypal/PayPal-PHP-SDK#473]
Using sample code i got error above

Got Http response code 404 when accessing https://api.sandbox.paypal.com/v1/payments/payment.

**Comment by jaypatel512** [comment]
We would need more information on this. What operation you were trying to use ? Were you able to follow the wiki setup instructions provided here: https://github.com/paypal/PayPal-PHP-SDK/wiki

**Comment by muddy-28** [comment]
i was tranfering funds from the test creditcards to test merchant acount
using sample website of pizza shop

**Comment by jaypatel512** [comment]
Are you still seeing this issue. We were in process of updating sandbox services recently with new fixes/updates. Please try again and see if you are still facing this issue. 

Also, any screenshots, or more details would be helpful.

**Comment by ppmtscory** [comment]
Closing for now.  Please reopen with the extra details as @jaypatel512 requested if you are still seeing issues.
