### ISSUE TITLE
https://developer.paypal.com/developer/applications/ doesn't load

### ISSUE THREAD

**Issue by omarkilani** [paypal/PayPal-PHP-SDK#475]
Hi PayPal,

I don't know where to put this. I can't load:

https://developer.paypal.com/developer/applications/

While logged in. It just hangs forever, and Chrome gives me a SPDY_PROTOCOL_ERROR.

I've tried Safari and Firefox as well.

**Comment by pp-randy** [comment]
Hi @omarkilani ,

I tested the page and it is working for me at this time.

If you are still having an issue with the applications page, can you please contact PayPal Merchant Technical Support at https://www.paypal-techsupport.com/app/ask/ ?
