### ISSUE TITLE
Unsupported SSL protocol version 

### ISSUE THREAD

**Issue by srokatonie** [paypal/PayPal-PHP-SDK#478]
http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/CreatePaymentUsingPayPal.html
This used to work few months ago but now I'm getting "Unsupported SSL protocol version" in sandbox environment..

**Comment by bluk** [comment]
Please see issue #474 if that helps fix your issue.

**Comment by srokatonie** [comment]
This doesn't solve the issue. I upgraded to 1.6.4 and still getting the same error...

**Comment by Caffe1neAdd1ct** [comment]
What PHP version are you running, i've found PHP 5.4 and under won't
connect using TLS 1.2 even if available in your Curl  or openssl.

**Comment by srokatonie** [comment]
Turned I was running different CLI PHP and different on Apache. It's seems to be fine now.

**Comment by Allerion** [comment]
I'm using v1.6.4 and still have this issue.

- Linux CentOS 6.32
- Apache 2.4.18
- PHP 5.6.18
- CURL 7.38.0
- OpenSSL 1.0.1e-fips

- CURL tls_version  = TLS 1.2
- CURL ssl_version = OpenSSL/1.0.0
- PHP OPENSSL_VERSION_TEXT = OpenSSL 1.0.1e-fips 11 Feb 2013

Any thoughts on a solution?

**Comment by jeroendesloovere** [comment]
Having the same issue.
Is there a solution yet?

**Comment by bluk** [comment]
@jeroendesloovere Please open a new issue with more details about your environment (which version of CURL, OpenSSL, PHP, etc. that your web server is using, which may not necessarily be the same as what is available on the command line). You can find more information on the [TLS update site](https://github.com/paypal/TLS-update#php).
