### ISSUE TITLE
Guest checkout not displayed on mobile

### ISSUE THREAD

**Issue by rairlie** [paypal/PayPal-PHP-SDK#480]
I am trying to perform a guest checkout (prompt for card rather than Paypal login) on a mobile device.

I successfully created a web-profile with the following details:
```
{
    "name": "My Business Name",
    "flow_config": {
        "landing_page_type": "billing"
    }
}
```
When I pass the ID of this web-profile to the Payment object (via setExperienceProfileId) I have no errors, but when visiting the approval URL the 'pay with card' option does not appear on mobile, only on desktop. Also the problem only happens on live; on the sandbox it shows the old UI and allows card checkout.

Live - no card option:
![screenshot from 2016-01-21 22 47 23](https://cloud.githubusercontent.com/assets/14072280/12497108/b133b342-c091-11e5-9156-3040bb5fdfec.png)

---

Sandbox - landing page is card:
![screenshot from 2016-01-21 22 48 53](https://cloud.githubusercontent.com/assets/14072280/12497014/29deba36-c091-11e5-8eb5-17ae2b368c1d.png)

**Comment by pp-randy** [comment]
Hi @rairlie can you submit this issue to Merchant Technical Support here? https://www.paypal-techsupport.com/app/ask/

From what I can tell this doesn't not appear an SDK issue since its working in sandbox.
