### ISSUE TITLE
 PayPal \ Exception \ PayPalConnectionException (28)  Connection timed out after 10425 milliseconds 

### ISSUE THREAD

**Issue by Ral15** [paypal/PayPal-PHP-SDK#481]
Hi, I get this problem when I'm trying to  access the express checkout form from paypal.

**Comment by pp-randy** [comment]
@Ral15 Is this issue happening against Production or Sandbox?

**Comment by Ral15** [comment]
Hi @pp-randy this issue is happening in both production and sandbox, I tried to use the api again today and got this message:

PayPal \ Exception \ PayPalConnectionException (7)

Failed connect to api.paypal.com:443; Operation now in progress 


I believe that this has something to do with the configuration of the firewall of my current hotspot, I just changed to an office and I start getting this issues, I could work without problems before.

**Comment by pp-randy** [comment]
@Ral15 I think you might be correct, it was hard to find anything solid researching this but it appears to be an underlying firewall issue which is causing this cURL error. 

Some of the error examples I see indicate you might need to connect through a proxy server.  Does your new office use a proxy server?

**Comment by jaypatel512** [comment]
Any updates on this @Ral15 ?

**Comment by Ral15** [comment]
@jaypatel512 @pp-randy Sorry for not updating.

The next day my problem was resolved, as if nothing had happened. It all worked normally.

**Comment by pp-randy** [comment]
@Ral15 Thank you for the update.

**Comment by danielberg1** [comment]
@Ral15  Hi, dear.
I am a user a paypal-php-sdk.
first, I want to thank you for uploading good source.
Your sdk is essential for me.
I have a question.
Can i transfer money to other's credit card using this sdk?

**Comment by pp-randy** [comment]
@danielberg1 
Not to a credit card directly, but you can send money to another PayPal account. 
https://github.com/paypal/PayPal-PHP-SDK/tree/master/sample/payouts

Documentation:
https://developer.paypal.com/docs/rest/api/payments.payouts-batch/

**Comment by danielberg1** [comment]
Thank you. randy.
Can i get issue from PayPalConnectionException?

**Comment by pp-randy** [comment]
@danielberg1 Are you getting a PayPalConnectionException currently?

**Comment by danielberg1** [comment]
yes. I got it.
I want to extract the issue sentence from paypalconnectionException.
And ps: Have you ever used this sdk to send money to credit card?

**Comment by jaypatel512** [comment]
There is [a wiki page](https://github.com/paypal/PayPal-PHP-SDK/wiki/exception-%27PayPal%5CException%5CPayPalConnectionException%27-with-message-%27Got-Http-response-code-400-when-accessing) documenting how to catch PayPalConnectionException.

**Comment by danielberg1** [comment]
Thank you.
And is there ability that you can update this sdk to send from credit to credit?
If it is possible, then your sdk will be more famous.

**Comment by Waleedaimviz** [comment]
hey Randy how are you my br0o 
i still facing that issue 

Response Object

 Connection timed out after 31001 milliseconds

No Data

please help to resolve it

**Comment by Waleedaimviz** [comment]
it is perfect working in localhost on sandbox but not working proper in live server and Production or Sandbox both not working

**Comment by dfguns89** [comment]
I have the same error in localhost: Resolving timed out after 10520 milliseconds!! I dont know what happened . It was working fine in the past. Please help

**Comment by pp-randy** [comment]
@dfguns89 sorry I missed your comment. Can you file a new issue if this is still happening?  I know a DNS provider was impacted around that time which could have cased this.

**Comment by YoleyTeichman** [comment]
Having a Connection Time out error after 36000ms.

Tests I initiated.
localhost: sandbox and live were ok,
production: sandbox ok, live throwing a connection time out error after 36000ms sometimes

can some one help me with that?

**Comment by pp-randy** [comment]
@YoleyTeichman this might be helpful PayPal Technical Support [FAQ1403](https://www.paypal-knowledge.com/infocenter/index?page=content&id=FAQ1403&expand=true&locale=en_US).

**Comment by YoleyTeichman** [comment]
@pp-randy I have done all the tests and solutions but still same problem, the live api responds with a timeout error sometimes, for instance a few minutes ago the api responded perfectly, now it doesn't it returns a timeout error.

What else could be the issue?

**Comment by pp-randy** [comment]
Please reach out to PayPal Technical Support here: https://www.paypal-techsupport.com/app/ask.  They should be able to better assist since it does not appear to be an SDK issue at this time.

**Comment by YoleyTeichman** [comment]
@pp-randy Thank you very much for your help.
