### ISSUE TITLE
Notice: Missing Accessor: PayPal\Api\Transaction:setSupplementaryDataMap. You might be using older version of SDK. If not, create an issue at https://github.com/paypal/PayPal-PHP-SDK/issues in ......modules/oxps/paypalplus/vendor/paypal/rest-api-sdk-php/lib/PayPal/Validation/ModelAccessorValidator.php on line 44

### ISSUE THREAD

**Issue by sodeo** [paypal/PayPal-PHP-SDK#482]
Hi,
this message appears from today in our shop!
Before, PayPal Plus worked without problems.
(I just made a test-order - it worked - although this notice apears)
Do you have any temporary technical disorder?
Best regards!

**Comment by sid606** [comment]
Same here is there an solution without update the sdk?

**Comment by jaypatel512** [comment]
The recommended solution is to update the SDK to latest version. However, in case you cannot update to latest version, there is a configuration setting to disable the validation for missing accessor. 

Just add the following configuration in ApiContext object :
```
// Step 2.1 : Between Step 2 and Step 3
$apiContext->setConfig(
  array(
    ...
    'validation.level' => 'disable',
    ...
  )
);
```

Know more about adding configurations here: https://github.com/paypal/PayPal-PHP-SDK/wiki/Adding-Configurations

**Comment by sid606** [comment]
this was like that..

I update to the new version of the sdk and now it give me this error 

Response Object

 Unsupported SSL protocol version

**Comment by jaypatel512** [comment]
Hey @sid606 !

This is expected. You need to update your openssl version for your PHP WEB installation. Please refer to the documentation provided here: https://github.com/paypal/tls-update#php

Related issues if you run into issues using MAMP: https://github.com/paypal/PayPal-PHP-SDK/issues/484
