### ISSUE TITLE
Still having SSL connect error in 1.6.4 sdk

### ISSUE THREAD

**Issue by funnykiat** [paypal/PayPal-PHP-SDK#485]
I'm still having this ssl connect error for 1.6.4 release. However when I use postman to manually post the request, it works. but when posting normally through my code using the api it doesn't work. Please help

**Comment by juwlee** [comment]
@funnykiat have you looked at #484 and [readme doc regardint `TLS 1.2`](https://github.com/paypal/PayPal-PHP-SDK#please-note)? What kind of error(s) do you see? And what `openssl` and/or `curl`versions is your PHP environment using?

**Comment by funnykiat** [comment]
Thanks for the quick reply, It works now after I've updated my libcurl from 7.19 to 7.46. restart of the web server is required after the update.

**Comment by juwlee** [comment]
Glad the problem has been resolved. Closing this issue.
