### ISSUE TITLE
Merchant SDK Adaptation for Capture Payment

### ISSUE THREAD

**Issue by fiatux** [paypal/PayPal-PHP-SDK#486]
Can I capture an authorized payment created by paypal/merchant-sdk-php, using the new paypal/rest-api-sdk-php SDK? IDs are all different, is there any adaptations or a way to query old transaction IDs?

**Comment by ppmtscory** [comment]
@fiatux unfortunately you won't be able to capture the transaction using REST from the older merchant sdk.  You'd need to use the Classic APIs to close any loops on those transactions.

**Comment by fiatux** [comment]
@ppmtscory  loading both new and old sdks would cause namespace conflicts i presume. so it leaving using curl to capture old transactions as the only way.

**Comment by ppmtscory** [comment]
Correct - if needed, you can just utilize whichever [API call](https://developer.paypal.com/docs/classic/api/) you need directly.
