### ISSUE TITLE
REST API Samples > Check if your system supports TLSv1.2 > Read More! link is broken

### ISSUE THREAD

**Issue by rojoangel** [paypal/PayPal-PHP-SDK#487]
In the ```// REST API Samples``` page (available at http://paypal.github.io/PayPal-PHP-SDK/sample/#fdd062bb702057b0466b4a2766a35a8e) the "Read More!" link for "Check if your system supports TLSv1.2" section is broken (it currently is pointing to https://github.paypal.com/SDK-R/tls-update/blob/master/readme.md which redirects to a not available web page)

**Comment by jaypatel512** [comment]
Thanks for the heads up. Let me fix that right away !!

**Comment by jaypatel512** [comment]
Commit fixing this : https://github.com/paypal/PayPal-PHP-SDK/commit/c465caf01aa8e2cb807182366c6a528375ef5376
