### ISSUE TITLE
Why payments doesn't appear on my account?

### ISSUE THREAD

**Issue by geolyth** [paypal/PayPal-PHP-SDK#488]
I follow all the instruction to integrate PayPal SDK in my website but also I receive a HTTP Status 200 in my account I can't see nothing...

**Comment by jaypatel512** [comment]
We might need some additional information to help you debug. Can you please be more specific on which environment you were generating payments ? 

Also, if you could provide us with debug_ids, we could make sure that everything is fine from paypal service end or not.

**Comment by geolyth** [comment]
This is my code:
    
    public function payment($userId, $price)  {      
        $sdkConfig = array(
            "mode" => "live"
        );

        $apiContext = new \PayPal\Rest\ApiContext(new \PayPal\Auth\OAuthTokenCredential(
            'XXX',     // ClientID Live
            'YYY'      // ClientSecret Live
        ), 'Request' . time());

        $apiContext->setConfig($sdkConfig);

        $payer = new \PayPal\Api\Payer();
        $payer->setPaymentMethod('paypal');

        $item = new \PayPal\Api\Item();
        $item->setName('Name')
            ->setCurrency('EUR')
            ->setQuantity(1)
            ->setSku(uniqid())
            ->setPrice(intval($price));

        $itemList = new \PayPal\Api\ItemList();
        $itemList->setItems(array($item));

        $amount = new \PayPal\Api\Amount();
        $amount->setCurrency('EUR')
            ->setTotal($price);

        $transaction = new \PayPal\Api\Transaction();
        $transaction->setAmount($amount)
            ->setItemList($itemList)
            ->setDescription('Credits')
            ->setInvoiceNumber(uniqid());

        $redirectUrls = new \PayPal\Api\RedirectUrls();
        $redirectUrls->setReturnUrl(site_url("home/paypal_success?price=".$price))
            ->setCancelUrl(site_url("home/paypal_denied?price=".$price));

        $payment = new \PayPal\Api\Payment();
        $payment->setIntent('sale')
            ->setPayer($payer)
            ->setRedirectUrls($redirectUrls)
            ->setTransactions(array($transaction));

        try {
            $payment->create($apiContext);
        } catch (PayPal\Exception\PayPalConnectionException $ex) {
            echo '<pre>';
            print_r(json_decode($ex->getCode()));; // Prints the Error Code
            echo '<pre>';
            print_r(json_decode($ex->getData())); // Prints the detailed error message
            die($ex);
        } catch (Exception $ex) {
            die($ex);
        }

        $this->transaction_model->create_paypal_transaction($payment->getId(), $userId, $price);

        echo $approvalUrl = $payment->getApprovalLink();

        return $payment;
    }

How could you give debug_ids? Where can i found it?

Thanks in advance for your help :)

**Comment by jaypatel512** [comment]
I am not sure if you have completed the second step of this integration. Once the approvallink is provided, you would redirect the user to that, which would allow paypal to get the user logged in, and get the consent for your payment. Once done, they will redirect you to back to the URL you have set in `returnUrl`.

You are expected to execute the payment once you receive that return url. You can experience that flow by running samples as [shown here](https://github.com/paypal/PayPal-PHP-SDK/wiki/Samples#instructions)

Or you could directly look at the source code for the [second part of the flow](http://paypal.github.io/PayPal-PHP-SDK/sample/#fdd062bb702057b0466b4a2766a35a8e)

**Comment by geolyth** [comment]
I follow this path...with Sandbox mode I am able to complete this process in right way...

I take the sample directly from the source code.

**Comment by ppmtscory** [comment]
@geolyth after following the links that @jaypatel512 provided, were you able to perform the redirect, login to approve the payment, and then follow through with the Execute call?  If you are getting errors on the Execute call, then that's what we would need to know about.  If you are seeing an error or have issue, please provide us with all 3 of your steps to complete the payment (create, approve, execute).

**Comment by geolyth** [comment]
Hi @ppmtscory,
first thank you for your help!
Steps that I do in my code are:

1. Click on a button in a form (it has $userId and $price data value that I need);
2. Execute function payment (listed before);
3. Redirect to approval link so I am now in PayPal website;
4. Complete or reject the transaction;
5. Return to my website with redirect url.

With sandbox mode all worked well so I decided to switch to live mode. The issue is the payment seems to go well but not worked too.

I followed already that links...

What can I do to know If transaction on PayPal goes well or not?

**Comment by ppmtscory** [comment]
If you see the transaction in the receiver account, then you know it completed.  However, you're still missing the last crucial step which is to [Execute](https://developer.paypal.com/docs/api/#execute-an-approved-paypal-payment) the payment *after* your Step 5 that you listed.  You can find an example of this in the SDK, [here](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/ExecutePayment.php).

**Comment by geolyth** [comment]
Now I have a transaction id (with method execute) in sandbox and live mode.
Maybe I resolved with your precious help :)

Thanks a lot!
