### ISSUE TITLE
I am trying to run $result = $payment->execute($execution, $apiContext); but i'm always getting error on execute, please help

### ISSUE THREAD

**Issue by B1ll1** [paypal/PayPal-PHP-SDK#490]
400{"name":"VALIDATION_ERROR","details":[{"field":"transactions[0].item_list.shipping_address.normalization_status","issue":"This field name is not defined for this resource type"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#VALIDATION_ERROR","debug_id":"7fa8dd8687106"}exception 'PayPal\Exception\PayPalConnectionException' with message 'Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payment/PAY-7K118016T11050001K2YK5JA/execute.'

**Comment by pp-randy** [comment]
Hi @B1ll1 

When reviewing execute documentation in REST Here: https://developer.paypal.com/docs/api/#execute-an-approved-paypal-payment
Transactional details if updating a payment. **Note that this instance of the transactions object accepts only the amount object.**

Looking at the Classic API documentation, it appears the normalization_status is provided in responses from PayPal and is a reflection of the Address stored at PayPal.  
https://developer.paypal.com/docs/classic/api/merchant/GetExpressCheckoutDetails_API_Operation_NVP/
PAYMENTREQUEST_n_ADDRESSNORMALIZATIONSTATUS: The PayPal address normalization status for Brazilian addresses

**Comment by jaypatel512** [comment]
If there is no change to the amount, you could just execute the payment by setting just its ID, something like shown below:

```php
$execution = new PaymentExecution();
$execution->setPayerId($_GET['PayerID']);
$result = $payment->execute($execution, $apiContext);
```

**Comment by B1ll1** [comment]
Thank you, I've managed to fix it :)
 Universidade Federal de Itajubá Rodolfo Lima Zahn 

    Em Terça-feira, 2 de Fevereiro de 2016 13:33, Randy <notifications@github.com> escreveu:
 

 Hi @B1ll1 When reviewing execute documentation in REST Here: https://developer.paypal.com/docs/api/#execute-an-approved-paypal-payment
Transactional details if updating a payment. Note that this instance of the transactions object accepts only the amount object.Looking at the Classic API documentation, it appears the normalization_status is provided in responses from PayPal and is a reflection of the Address stored at PayPal.

https://developer.paypal.com/docs/classic/api/merchant/GetExpressCheckoutDetails_API_Operation_NVP/
PAYMENTREQUEST_n_ADDRESSNORMALIZATIONSTATUS: The PayPal address normalization status for Brazilian addresses—
