### ISSUE TITLE
Make logging more flexible.

### ISSUE THREAD

**Issue by lectrotext** [paypal/PayPal-PHP-SDK#491]
Monolog would be a great alternative to using the basic file logging offered.

**Comment by jaypatel512** [comment]
The only reason we have not included monolog directly is to not have any additional dependency on the SDK. It causes a lot of complexity to support different monolog versions.

**Comment by lectrotext** [comment]
How about a PSR Logger

**Comment by dopesong** [comment]
This issue was closed way too fast and it should be reopened. With PSR-3 we would be able to use whatever we want. For example my whole application using monolog and I could implement it with paypal SDK also. :)

**Comment by jaypatel512** [comment]
Thats my bad on closing this issue. I think adding PSR logger interface definitely makes sense. We have another open issue #520  that talks about this.

I spent some time today and create a pull request to get this thing going. This is a first pass. However, I would really encourage you guys to contribute to the PR. Lets take the discussion to the PR.
