### ISSUE TITLE
Complete transfer setPaymentMethod(“credit_card”)

### ISSUE THREAD

**Issue by keygenqt** [paypal/PayPal-PHP-SDK#492]
Tell me how to complete the transfer of money from credit card (previously saved). Follow all documentation approved status and the money remain in place. It is not clear what step you need to perform the following.

http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/CreatePaymentUsingSavedCard.html

answer:
....
["state"]=> string(8) "approved"
....

**Comment by ppmtscory** [comment]
Please let me know the full response of the API call itself so that I can look up the debug ID, sale ID, or payment resource to see why there is no money movement.  Also let me know whether this is in Production or Sandbox.

**Comment by keygenqt** [comment]
Thank you already understood everything. Paypal works on the site.

12.02.16 7:42, Cory пишет:

**Comment by ppmtscory** [comment]
Thank you for the update, @keygenqt, I'm glad that you were able to get it working.  Cheers!
