### ISSUE TITLE
cakephp

### ISSUE THREAD

**Issue by elarion83** [paypal/PayPal-PHP-SDK#494]
I'm, I'm using cakephp v3 to run my website and I'd like to know if your SDK is usable with this framework ?

**Comment by jaypatel512** [comment]
The SDK is designed to work with any new PHP frameworks following basic programming standards. There might be few additional steps that may be required to integrate with CakePHP.

However, you could reach out to public forums in Cake PHP or here at github issue tracker if you run into any specific SDK issues.
