### ISSUE TITLE
https://developer.paypal.com/docs/api/#payouts issue

### ISSUE THREAD

**Issue by borracciaBlu** [paypal/PayPal-PHP-SDK#497]
I'm sorry, I'm not sure this is the right place to point out this but on https://developer.paypal.com/docs/api/#payouts when you click on PHP there is this screen:  

![screenshot from 2016-02-11 12 33 04](https://cloud.githubusercontent.com/assets/2061731/12967555/f7cb8c32-d0bb-11e5-8da3-6953d6b00fcd.png)

In particular notice this:  
    
    "require": {
        "php": ">=5.3.0",
        "ext-curl": "*",
        "ext-json": "*",
        "paypal/rest-api-sdk-php" : "0.5.*"
    }

As you can see the version of the sdk is old, I think it could be misleading.

Thanks

**Comment by pp-randy** [comment]
@borracciaBlu Thank you for letting us know about this.  I do not see this going on in the beta version of the documentation https://developer.paypal.com/docs/rest/api/. I will follow up internally on the options if end of life is near on the current docs this might not be an issue much longer.
