### ISSUE TITLE
Create Authorization returns HTTP Status 500

### ISSUE THREAD

**Issue by lectrotext** [paypal/PayPal-PHP-SDK#498]
When client makes a mistake and the "payment_method":"credit_card" parameter is missing, the create authorization POST returns a 500.  API should return a 400 and give guidance on the problem.

Error was discovered with help from kmaiya@paypal.com.

**Comment by pp-randy** [comment]
Thank you for reporting this issue. I will follow up on this to get a more reasonable error to be thrown. 

For internal tracking purposes: PPPLPAYPT-6503

**Comment by ppmtscory** [comment]
@lectrotext this has been resolved so I will be closing this out.  Below is the error that I receive now...
```
400 Bad Request
{
  "name": "VALIDATION_ERROR",
  "details": [
    {
      "field": "payer.payment_method",
      "issue": "Value is invalid (must be credit_card or paypal)"
    },
    {
      "field": "payer",
      "issue": "For credit_card payment method, the supported funding instrument is credit_card or cardit_card_token "
    }
  ],
  "message": "Invalid request - see details",
  "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#VALIDATION_ERROR",
  "debug_id": "99d7d7f16834b"
}
```
