### ISSUE TITLE
Add recurring payments example

### ISSUE THREAD

**Issue by iadj** [paypal/PayPal-PHP-SDK#500]
The sample (pizza) app does not include recurring payments, and the sample code snippets also fail to explain how to integrate it. Please add it to the example app (getting something working properly with the Paypal PHP SDK is hard enough as it is).

**Comment by ppmtscory** [comment]
@iadj please file issues with that sample app in it's own [repo](https://github.com/paypal/rest-api-sample-app-php) as the samples in this repo do contain [billing plan/agreement samples](https://github.com/paypal/PayPal-PHP-SDK/tree/master/sample/billing).
