### ISSUE TITLE
Is EWP supoprted by the PHP SDK?

### ISSUE THREAD

**Issue by prionkor** [paypal/PayPal-PHP-SDK#502]
I am trying to locate any **Encrypted Website Payments** code in this sdk searched by the string *Encrypted Website Payments* and *EWP* but it didn't get me any result.

Does the sdk supports EWP for encrypting payment buttons?

**Comment by pp-randy** [comment]
Closing as duplicate of https://github.com/paypal/buttonmanager-sdk-php/issues/14
