### ISSUE TITLE
Exception: Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment

### ISSUE THREAD

**Issue by brtsos** [paypal/PayPal-PHP-SDK#503]
![pp](https://cloud.githubusercontent.com/assets/729906/13355271/d3466afe-dc9f-11e5-9e2d-c55607530d45.PNG)

I tested:
vendor/paypal/rest-api-sdk-php/sample/payments/ExecutePayment.php?

Error 500 is here again :(

**Comment by ppmtscory** [comment]
@brtsos unfortunately there were some system issues in the sandbox this morning that seem to be the cause of your issue.  I just tested with the samples in the SDK and the ExecutePayment.php processed with success.  Can you please try and update here?

**Comment by brtsos** [comment]
@ppmtscory you are right :) Now is ok.

Thanks for reply!

**Comment by devnedra** [comment]
Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payouts?.

**Comment by devnedra** [comment]
I am geting this error after paypal sandbox success return page
Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payouts?.

**Comment by xiaoleih41** [comment]
This issue should have been solved now. Please check again.
