### ISSUE TITLE
Billing Agreement with setup_fee can be created even for accounts that can't be charged

### ISSUE THREAD

**Issue by iadj** [paypal/PayPal-PHP-SDK#505]
If a user can't be charged with the setup fee, the user shouldn't be able to authorize the billing agreement on Paypal's authorization page.
This is currently not the case and users that can't be charged (because there are no funds on their bank account for instance) can create billing agreements and go to the 'success' return URL.

**Comment by iadj** [comment]
@jziaja I think this goes in combination with https://github.com/paypal/PayPal-PHP-SDK/issues/149
The NVP API requires the merchant to invoke the Check-Out for Digital Goods product and add a billing agreement to it. That way if the user doesn't have sufficient funds, Paypal will ask the user to add a payment method to their account.

I don't see how this is possible with the REST API, but either way this shouldn't be the required course of action in order to make recurring payments work properly. Paypal needs to treat the setup fee as a digital product, display in the check-out summary (not just the agreement description), and fail if the user can't be charged immediately just like checking out a (digital) product.

**Comment by ppmtscory** [comment]
@iadj this is where the `initial_fail_amount_action` parameter comes into play.  Yes, with a PayPal agreement, the customer is simply authorizing the agreement and saying they are cool with setting it up.  The fee/amount is not actually attempted until the Execute call so there isn't anything that checks funding prior to that (during the 'ok' of the agreement).  For this use case, you'll want to set `initial_fail_amount_action` to `CANCEL` if you don't wish to continue with the agreement when the setup fee fails.

**Comment by iadj** [comment]
I haven't tried it in production. In the sandbox at least, the `setup_fee` appears to always return 0.00 in the JSON response. I remember reading that it takes a few minutes for it to update properly in the sandbox. Might be a sandbox bug. I'll check back and let you know exactly what happens.

**Comment by iadj** [comment]
@ppmtscory I just tested an amount of payments in the sandbox, and only one payment was received (30 minutes later). The `setup_fee` also appears to always display as `0.00`, regardless of what I configure it as. Is this an issue with the sandbox?

**Comment by iadj** [comment]
@ppmtscory I just checked the sandbox account itself rather than the sandbox development dashboard, and it does show received payments. They just don't show in 'Notifications' in the dashboard.

**Comment by ppmtscory** [comment]
@iadj this could be the way that your sandbox account is set up as well.  Did your agreement eventually change to Active or is it still in a Pending state?  Can you let me know the agreement ID so that I can take a look?  Also, i will run some tests in the sandbox as this latency of `setup_fee` very well may be just an issue with Sandbox.  The agreement will be pending until that fee is either charged or failed.  Lastly, since your issue #504 is still open, let's move this conversation over to that one.

**Comment by daerimin** [comment]
@ppmtscory  I'm experiencing exactly the same thing as @iadj .  Is there any update on this problem?  I, too, cannot get a successful test in the sandbox.  It took my test customer over an hour for the billing agreement to switch from "pending" to "active", with a setup fee applied to the transaction.

**Comment by ppmtscory** [comment]
@daerimin this issue is being tracked via #504.  There is currently no update, unfortunately.
