### ISSUE TITLE
Should you create a new payment plan for every billing agreement?

### ISSUE THREAD

**Issue by iadj** [paypal/PayPal-PHP-SDK#506]
I don't see this explained in the documentation: should you create a payment plan for every billing agreement? Or if you have (for instance) 2 plans, one monthly and one yearly, do you just create those 2 plans, save the IDs, and then use either of the 2 plan IDs for every new billing agreement?

Are there any pros/cons to using one or the other method?

**Comment by ppmtscory** [comment]
@iadj it's way more convenient for you to re-use Plan IDs if you have similar payment definitions.  If you have multiple agreements that all have the same options, you can definitely use the same Plan for them all.  The only reason you'd need to create a different Plan is if you have a different option for the next agreement.
