### ISSUE TITLE
Another SSL Connect Error

### ISSUE THREAD

**Issue by mvalent23** [paypal/PayPal-PHP-SDK#507]
I'm receiveing an SSL Connect Error when I try to connect to the Pay Pal Sandbox.  Everything works fine when I connect using 'live' as the mode.   Any ideas why this might occur?

I've updated to the latest SDK API.

I've made 10000% sure I switched the mode flag to 'sandbox', and triple checked I'm using the right API keys.

**Comment by pp-randy** [comment]
Have you reviewed the PHP section here? 
https://github.com/paypal/tls-update#php

**Comment by mvalent23** [comment]
I have reviewed similar, but this at least gave me some more info.  

`php -r '$ch = curl_init(); curl_setopt($ch, CURLOPT_URL, "https://tlstest.paypal.com/"); var_dump(curl_exec($ch)); var_dump(curl_error($ch));'
bool(false)
string(17) "SSL connect error"`

Then, I checked CURL and OpenSSL settings on the host

`curl -V:
curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.15.3 zlib/1.2.3 libidn/1.18 libssh2/1.4.2`

`openssl version:
OpenSSL 1.0.1e-fips 11 Feb 2013`

These release notes indicate that the OpenSSL version 1.0.1c or higher is needed, which it appears is the case.  What else am I missing here?

**Comment by pp-randy** [comment]
If you run a php file with phpinfo() what version of OpenSSL does it show to be using?

**Comment by mvalent23** [comment]
That revealed the culprit!  The version of PHP on my host is using openssl-1.0.0.  This is unfortunate - I don't have control over this host to update things like PHP and/or other packages.  

I may have to upgrade the service on that host in order to get this working.  On a related note, is this expected to migrate and impact live settings anytime soon?  I just need to determine how long I have before the live feature breaks.

**Comment by bluk** [comment]
@mvalent23 The [PayPal 2016 Merchant Security Roadmap Microsite](https://www.paypal-knowledge.com/infocenter/index?page=content&id=FAQ1913&expand=true&locale=en_US) has the current official dates and some other related links you may find useful.

**Comment by pp-randy** [comment]
Closing this issue for now. @mvalent23 please let us know if you run into any issues once you get this figured out with your host.
