### ISSUE TITLE
UNAUTHORIZED_PAYMENT error

### ISSUE THREAD

**Issue by scufa** [paypal/PayPal-PHP-SDK#508]
What does it mean? Documentation is missing - https://developer.paypal.com/webapps/developer/docs/api/#UNAUTHORIZED_PAYMENT

```
        "status": 401,
	"duration_time": 178,
	"body": {
		"message": "Unauthorized payment",
		"information_link": "https://developer.paypal.com/webapps/developer/docs/api/#UNAUTHORIZED_PAYMENT",
		"name": "UNAUTHORIZED_PAYMENT",
		"debug_id": "5d09d5628856d"
	},
```

I have tested my code on two different paypal accounts. App settings are same, no CC Payment limit notes in dashboard.

**First account**
sandbox - works
live - works

**Second account**
sandbox - works
live - getting "Unauthorized payment" error

Is it API problem? Who should I contact to regarding this issue?

**Comment by pp-randy** [comment]
I see you have two REST Applications on the same account, the first one is working fine for you? Or are you is the first account you mention a completely separate account?

**Comment by scufa** [comment]
I made two applications for testing. Both not working in live mode. First account is separate, it has one application.

**Comment by pp-randy** [comment]
When you log into here https://developer.paypal.com/developer/accountStatus/ with the account

What do you see for Direct credit cards under the Live column?

**Comment by scufa** [comment]
I see now. It's not enabled. I was referring to the Live mode settings:

> Accept one-time and subscription payments from PayPal members using PayPal and direct credit card processing.

Thanks.
