### ISSUE TITLE
Paypal REST API INSTRUMENT_DECLINED

### ISSUE THREAD

**Issue by silencechow** [paypal/PayPal-PHP-SDK#509]
When I execute the payment it always shown "{"name":"INSTRUMENT_DECLINED","details":[],"message":"The instrument presented  was either declined by the processor or bank, or it can't be used for this payment.","information_link":"https://developer.paypal.com/docs/api/#INSTRUMENT_DECLINED","debug_id":"ba818e96bcff5"}"
But It will be fine after refresh once.

**Comment by pp-randy** [comment]
From what I can tell a different funding source is most likely being used.  Is this happening for all your buyers or just this one?

**Comment by jaypatel512** [comment]
Closing this issue as resolved based on inactivity. Please re-open if issue not solved.
