### ISSUE TITLE
Can't use sandbox.

### ISSUE THREAD

**Issue by ealvizouri** [paypal/PayPal-PHP-SDK#510]
[I know PayPal changed the certificates](http://stackoverflow.com/questions/34926940/php-paypal-error-14077410ssl-routinesssl23-get-server-hellosslv3-alert-hands)

I made an update with composer. But I still get this error when I try to use sanbox:

paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php:139string(94) "[generate_url]error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure"

Is there gonna be updates for this to get it work? What can I do temporarily?

**Comment by pp-randy** [comment]
Can you see if you find something helpful in this thead? https://github.com/paypal/PayPal-PHP-SDK/issues/507

**Comment by pp-randy** [comment]
@ealvizouri was the previous thread helpful and were you able to resolve this?

**Comment by jaypatel512** [comment]
Closing this issue as resolved based on inactivity. Please re-open if issue not solved.
