### ISSUE TITLE
Misleading errors in TLS check

### ISSUE THREAD

**Issue by troywray** [paypal/PayPal-PHP-SDK#512]
I spent ages chasing the wrong thing and googling, found others that might have the same problem.

If function push in AuthorizationCache.php can't mkdir the $cachePath (e.g. because of permissions), the TLS check reports that TLS1.2 is not working - as well as lots of warnings about not being able to log.

**Comment by jaypatel512** [comment]
Hey @troywray !

Thanks for creating the issue here pointing this out. I have explicitly disabled caching for TlsCheck.php as it is not required.

It should be available in next release. Thanks.

**Comment by pp-randy** [comment]
I wanted to add a link from the wiki in regards to the caching: https://github.com/paypal/PayPal-PHP-SDK/wiki/Caching
