### ISSUE TITLE
Company logo on payment page

### ISSUE THREAD

**Issue by oranze** [paypal/PayPal-PHP-SDK#516]
Good day, how to set custom company logo to payment page?

**Comment by bluk** [comment]
You may want to checkout the [Web Experience Profiles](https://developer.paypal.com/docs/rest/api/payment-experience/?mark=experience%20profile) with the presentation data. There are some [samples for creating web profiles here](https://github.com/paypal/PayPal-PHP-SDK/tree/master/sample/payment-experience).
