### ISSUE TITLE
PayerInfo throws status 400

### ISSUE THREAD

**Issue by cornex** [paypal/PayPal-PHP-SDK#517]
Hello, I try to add payer info to my payer object, but for some reason it just returns 400.
This do not works:
```php
$payerInfo = new PayerInfo();
$payerInfo->setFirstName('Kristoffer')
          ->setLastName('Eklund')
          ->setEmail('kristoffer@gmail.com');

$payer = new Payer();
$payer->setPaymentMethod('paypal')->setPayerInfo($payerInfo);
```

This DO work:
```php
$payer = new Payer();
$payer->setPaymentMethod('paypal');
```

Thanks in advance for any help

**Comment by pp-randy** [comment]
PayPal should provide that to you according to the documentation. It should be returned in the response. 

https://developer.paypal.com/docs/api/#payerinfo-object
This object is pre-filled by PayPal when the payment_method is paypal.

**Comment by ppmtscory** [comment]
Closing out.  If you encounter any further issues, please reopen or open a new issue.
