### ISSUE TITLE
400 error Paypal\Api\Amount on paymentDefinitions

### ISSUE THREAD

**Issue by Karl456** [paypal/PayPal-PHP-SDK#518]
When creating a new plan there's a requirement to set the amount, but there seems to be a inconsistency between the API and the PHP SDK, on the API the Amount needs to conform to the following, the API requires `currency` and `value`.

Whereas, in \Paypal\API\Amount, there's a setCurrency method and a setTotal method. Because of this, when creating a plan you receive a 400 error:

`"name":"MALFORMED_REQUEST","message":"Incoming JSON request does not map to API request"`

In order to fix this you need to change the methods in \Paypal\Api\Amount:

    /**
     * Total amount charged as part of this payment.
     *
     *
     * @param string|double $value
     *
     * @return $this
     */
    public function setValue($value)
    {
        NumericValidator::validate($value, "Value");
        $value = FormatConverter::formatToPrice($value, $this->getCurrency());
        $this->value = $value;
        return $this;
    }

    /**
     * Total amount charged as part of this payment.
     *
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

**Comment by Karl456** [comment]
One thing that I've noticed with the change that I suggested above, is that the API returns the correct response, but when going through the checkout there's no indication of amount, etc. So this stops a preapproved payment being setup. This needs looking at immediately.

**Comment by jaypatel512** [comment]
Hey @Karl456 !

I would recommend you to follow the sample code shown here: http://paypal.github.io/PayPal-PHP-SDK/sample/doc/billing/CreatePlan.html

This sample creates a Plan using PHP SDK. The amount in the payment Definition object takes instance of "Currency" object as shown below:

```
->setAmount(new Currency(array('value' => 100, 'currency' => 'USD')));
```

Also, for future reference, you can easily figure out what type of object the method accepts by following the annotations provided at [class level](https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Api/PaymentDefinition.php#L20) or at [method level](https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Api/PaymentDefinition.php#L166)

For more samples/docs, please refer to http://paypal.github.io/PayPal-PHP-SDK/

**Comment by Karl456** [comment]
Thanks @jaypatel512, you're absolutely right, it uses the Currency class not the Amount class. Apologies for missing that!

If I could, would you be able to help me an issue with the API?

I'm now getting a response from the API with an approval URL, however, when I go to this URL in order to agree to the plan, there's no price/amount ever shown. I've set it up so that it's £50/month and has an initial setup fee of £50, so that we can get an immediate payment. So shouldn't this show on the checkout? I'm also logged in to the test account and there are no pre-approved payments in the list. Any ideas why?

**Comment by jaypatel512** [comment]
Hey @Karl456 !

We are aware of the issue where the plan summary is not showing up in PayPal UI that user interacts with. We have an issue currently opened to track this: https://github.com/paypal/PayPal-PHP-SDK/issues/149

We will update the thread as soon as the summary is available in UI.

**Comment by Karl456** [comment]
Ahh okay, thanks a lot @jaypatel512! 

Although that doesn't explain why the agreement never actually enters the pre-approved payments list, or why the setup fee is never taken. Any ideas?
