### ISSUE TITLE
Custom Logging

### ISSUE THREAD

**Issue by cullylarson** [paypal/PayPal-PHP-SDK#520]
It's pretty common to send log messages to a database or service, instead of logging to a file.  It seems odd that the SDK only allows logging to a file (or syslog, apparently).  Any thoughts on enabling the ability to add a custom log handler?  I imagine this could look like a simple callback function, set in the config, or the option to pass a custom `PayPalLoggingManager ` instance.

**Comment by jaypatel512** [comment]
I think you are absolutely right ! We could possibly extend PayPalLoggingManager to enable custom logging. 

We will definitely add this as an enhancement, and consider it in next major release. Btw, you are always encouraged to help us out with a PR if you are planning to work on that.

**Comment by cullylarson** [comment]
I'll definitely consider submitting a pull request.  Does the project have any documentation concerning contributions?

I have a few thoughts on a possible solution, and would love to hear feedback:

It seems like the current logging method values simplicity for the user, and the ability to configure logging using values from a configuration file.  I imagine this is something you want to keep, while also allowing people to override it with custom logging.

Currently, instances of `PayPalLoggingManager` are retrieved through a static factory method.  What if, instead of returning an instance of `PayPalLoggingManager`, the factory method returned a "`Logger`" interface?  The `PayPalLoggingManager` would still be responsible for creating the logger, so it could create the default logger if no other was provided.  But it could also return a custom implementation, if provided.

That leaves the question of how to make the `PayPalLoggingManager` aware of a custom logger.  `PayPalLoggingManager` is already dependent on `PayPalConfigManager`, so it would be simple to set the custom logger in `PayPalConfigManager`, and then have `PayPalLoggingManager` check if that config value exists when an instance is requested.  If it doesn't exist, it could just create the default instance (i.e. essentially what the logger does now). `PayPalLoggingManager` would still honor the `LogEnabled` config value, even if a custom logger is provided, and could even return a "`NullLogger`" (e.g. implements the logger interface, but doesn't do anything with log messages), if logging is disabled.

I imagine many people would want the ability to log to multiple destinations (e.g. file, database, etc.).  But since they could provide a custom logger, they could just handle all of their log destinations in that one custom logger (i.e. it would delegate to whatever logging mechanisms they have).

Another possible request might be the ability to pass configuration values to the custom logger, from the config file.  However, once again, since they can provide a custom logger, they could just handle reading their own config in the custom logger, and basically proxy for any other loggers they have that require configuration beyond what the PayPal SDK provides.

As for the logger interface, PHP-FIG has an approved standard logging interface that might work well:

https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md

**Comment by jaypatel512** [comment]
I agree with you on the first proposal. Providing a configuration to provide the `classname` of the class implementing PayPalLoggerInterface. If that is a valid class and is found, PayPalLoggingManager could use that instance. If not, we can provide them with the default class that works as expected today. 

I would love if you can start working on a branch and send a pull request. The [contribution documentation](https://github.com/paypal/PayPal-PHP-SDK/wiki/Contributing) is pretty straight forward. Feel free to create a PR with work in progress, and add that to the heading. I can start contributing as soon as you have a wip PR in place. 

We will allow the external developers implement dbloggers/redisloggers/fileloggers/etc.

Also, you can review https://github.com/paypal/PayPal-PHP-SDK/pull/372 PR as it has a similar mechanism for extending caching. I would recommend having a similar approach to it.
