### ISSUE TITLE
Where is the REAL Documentation?

### ISSUE THREAD

**Issue by chaos234** [paypal/PayPal-PHP-SDK#521]
I can't accept that you think that http://paypal.github.io/PayPal-PHP-SDK/sample/#payments should be your Documentation ... it's a joke, isn't it?

So please give me the correct URL to our Documentation with detailed informations about EACH FILE and ablout EACH Methode and there requirements and returns and so far.

Also there should be a simple sample file which should containt the following:

Required API files to do any kind of payment with paypal which means that paypal will get the invoice name, the amount and the customer details. Then the customer can choose if he pais over credit card or over his paypal account.

I only need then a success/failure return to handle the state of the invoice (pending/paid/payment failed).

But not this bullshit on the above side ... it's horrible!

Ok, I am done here and waiting for response hoping to get the answere because I don't need all of those stupied and not well documented stuff.

Look at this: http://ts3admin.info/manual/classts3admin.html#a80224d2fe9596e6e5aadb8ddcaad3eef

This is a real and good Documentation but not your ones!

**Comment by pp-randy** [comment]
Does this look more like what you are expecting in regards to method documentation? http://paypal.github.io/PayPal-PHP-SDK/docs/class-PayPal.Api.Payment.html

**Comment by pp-randy** [comment]
@chaos234 Do you need more documentation than the link provided above?  I want to get you what you need.

**Comment by chaos234** [comment]
A few simple lines how to call this API should be written for each supportet language in an html code-tag on the first page.

**Comment by pp-randy** [comment]
Thank you for the feedback.  If you are still needing some assistance on how to pull everything together I find the actual sample code is helpful: https://github.com/paypal/PayPal-PHP-SDK/tree/master/sample/

To create a PayPal Payment https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/CreatePaymentUsingPayPal.php

Which also refers to https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/bootstrap.php

Also this is a good resource, but not PHP SDK specific https://developer.paypal.com/docs/integration/direct/make-your-first-call/

**Comment by pp-randy** [comment]
Closing the issue out, please let me know if you need further assistance after reviewing the materials provided.
