### ISSUE TITLE
Ability to refund agreement transactions?

### ISSUE THREAD

**Issue by omarkilani** [paypal/PayPal-PHP-SDK#522]
Hey PayPal,

I might have missed the thing that lets me do this, but given an agreement transaction_id (https://developer.paypal.com/webapps/developer/docs/api/#agreementtransaction-object) it doesn't seem I'm able to programmatically refund these transactions.

Is that correct?

If so, can we get the ability to do this?

Thanks!

**Comment by ppmtscory** [comment]
Hey @omarkilani, you didn't miss anything.  Currently you would need to use the Classic API to refund using the transaction/sale ID.  However, this is far from ideal and we're trying to rectify it.  This is being tracked via [this issue](https://github.com/paypal/PayPal-Python-SDK/issues/115) currently.  For the ease of bookkeeping, I'm going to close this issue out and have you follow the previously mentioned issue for any updates on this.

**Comment by omarkilani** [comment]
Thank you Cory. Sorry, I didn't see the other issue as I don't use the Python API.

BTW, why don't you guys create a new project on GitHub specifically for issues so we don't need to track all the different language APIs for PayPal API requests/bugs/etc?

**Comment by ppmtscory** [comment]
Thanks for the feedback @omarkilani.  I'll bring this up to the team and see what we can do on that front.

**Comment by daffodilsunil** [comment]
hi
