### ISSUE TITLE
Sample => User Consent Error

### ISSUE THREAD

**Issue by aquachroma** [paypal/PayPal-PHP-SDK#524]
Thank you for providing an open source SDK for us developers.

I'm attempting sample UserConsentRedirect assuming it redirects a user to grant permissions for the application to make calls on their behalf. I've modified the bootstrap.php with my applications client_id and secret_key and I've updated the application sandbox dashboard with the redirect_uri to mysite.com/rest-api-sdk-php/sample/lipp/UserConsentRedirect.php.

I'm thinking maybe I'm missing a dependency since I didn't install from composer but I doubted that was the root issue.

Here is the response error I'm getting.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/identity/openidconnect/tokenservice.

{
    "error_description": "authorization code is null",
    "error": "unauthorized_client",
    "correlation_id": "ce2d109b50e96",
    "information_link": "https://developer.paypal.com/docs/api/#errors"
}
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

I also get these PHP errors.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Notice: Undefined index: code in /var/www/html/vendor/paypal/rest-api-sdk-php/sample/lipp/UserConsentRedirect.php on line 15

Warning: error_log(../PayPal.log): failed to open stream: Permission denied in /var/www/html/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalLoggingManager.php on line 111

Warning: error_log(../PayPal.log): failed to open stream: Permission denied in /var/www/html/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalLoggingManager.php on line 111

Warning: error_log(../PayPal.log): failed to open stream: Permission denied in /var/www/html/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalLoggingManager.php on line 111

Warning: error_log(../PayPal.log): failed to open stream: Permission denied in /var/www/html/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalLoggingManager.php on line 111

Warning: error_log(../PayPal.log): failed to open stream: Permission denied in /var/www/html/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalLoggingManager.php on line 111

Warning: error_log(../PayPal.log): failed to open stream: Permission denied in /var/www/html/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalLoggingManager.php on line 111

Warning: error_log(../PayPal.log): failed to open stream: Permission denied in /var/www/html/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalLoggingManager.php on line 111

Notice: Undefined index: code in /var/www/html/vendor/paypal/rest-api-sdk-php/sample/lipp/UserConsentRedirect.php on line 22
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Thanks for taking a look.

**Comment by jaypatel512** [comment]
First thing first. As you can see, the sdk is not able to create a log file at the given location. Can you please provide write permissions to make that happen ? That should let your see the right error message.

Secondly, as you can see, the `code` is a value that is required, which is passed as a parameter to the return url. 

To better understand this, please refer to this sample: http://paypal.github.io/PayPal-PHP-SDK/sample/doc/lipp/UserConsentRedirect.html

The `UserConsentRedirect` shows how to handle a successful redirect and create an access token once the redirect has happened. You can fetch the `code` value using `$_GET['code']`.

Also, I would highly recommend, running samples in your local machine as shown here: https://github.com/paypal/PayPal-PHP-SDK/wiki/Samples#instructions

You will see that you should be able to actually run the sample with success. Command line sample execution does not support redirect handling.

**Comment by jaypatel512** [comment]
Please reopen if this doesnt solve the issue.

**Comment by aquachroma** [comment]
I went ahead and enabled logging, this is being ran from a live server so redirects shouldn't be an issue. I still receive this error:
~~~~~~~~~~~~~~~~~~
Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/identity/openidconnect/tokenservice.

{
    "error_description": "authorization code is null",
    "error": "unauthorized_client",
    "correlation_id": "a0c23a1ff3fc5",
    "information_link": "https://developer.paypal.com/docs/api/#errors"
}
~~~~~~~~~~~~~~~~~

I'm hoping to obtain user consent... So when it asks for an authorization code I'd think that that would be generated after obtaining user consent. Am I misunderstanding the intent of this part of the samples?

Thanks for your time and patience.

**Comment by yogeshkhasturi** [comment]
i am having same issue , also i have given 777 permission Or 755 permission to LOG files and directory , but its not working , 

can anyone please help

**Comment by pp-randy** [comment]
@yogeshkhasturi  What exact error are you getting?  It might be worth testing the path you gave permissions to as the absolute path for the logger FileName.

https://github.com/paypal/PayPal-PHP-SDK/wiki/Logging

**Comment by jaypatel512** [comment]
@aquachroma, I think you are missing one step there.

To obtain a user consent, you are first required to generate a URL with scopes that you need, and the redirect URL where you wish to redirect when the user approves/cancels your consent request.

Step 1: http://paypal.github.io/PayPal-PHP-SDK/sample/doc/lipp/ObtainUserConsent.html
Step 2: http://paypal.github.io/PayPal-PHP-SDK/sample/doc/lipp/UserConsentRedirect.html

As you can see in Step 1, we are setting the baseUrl as the Step 2's url. This way, when the user accepts the consent, PayPal will redirect the page to that link, along with `code`, which you will use to Generate AccessToken. 

Hope this helped.
