### ISSUE TITLE
PayPal Auth with webview

### ISSUE THREAD

**Issue by antons81** [paypal/PayPal-PHP-SDK#525]
I am building an app with PalPal integration. What I need is Authentication through WebView with PayPal login screen. So user will enter his credentials, I will get a token and get his email account to save in my app. Something like Instagram.

What's wrong there, because I cannot understand anything from PayPal off docs

webView = UIWebView(frame: self.view.bounds)
        webView.autoresizingMask = [UIViewAutoresizing.FlexibleHeight,  UIViewAutoresizing.FlexibleHeight]

        let url = "https://api.sandbox.paypal.com/v1/oauth2/token/?client_id=\(client_id)&secret=\(secret)&grant_type=client_credentials&response_type=token"

        webView.delegate = self
        //webView.scalesPageToFit = true
        webView.loadRequest(NSURLRequest(URL: NSURL(string: url)!))
        self.view.addSubview(webView)
But givin an error:

    {
"error" : "invalid client", 
"error description" : "client credentials are missing"
}

In other words I need to show to user username and password fields from paypal, than get token and take his verified paypal email to save in my app.

**Comment by juwlee** [comment]
Hi @antons81 it looks like an iOS issue rather than a PHP one. Can you open one in [PayPal iOS SDK](https://github.com/paypal/PayPal-iOS-SDK/issues)?
