### ISSUE TITLE
where is IPN?

### ISSUE THREAD

**Issue by rmeden** [paypal/PayPal-PHP-SDK#526]
I'm trying to update my website to support the IPN changes.

I found "merchant-sdk-php" which says it's depreciated and I should use "PayPal-PHP-SDK"

I'm looking for an IPN sample.  Does this API support IPN?  I don't see it anywhere.  Is it supported?

**Comment by ppmtscory** [comment]
@rmeden when you are using these REST API SDK's, you'll want to look into [webhooks](https://developer.paypal.com/docs/rest/api/notifications/).  You can still use our Classic APIs (merchant-sdk-php) but it's recommended to use the newer SDKs with REST API.  With this SDK, there isn't a spot to pass through an IPN URL, so if you want to use IPN, you'd have to specify it in your account profile.  I'd recommend the use of Webhooks, however.
