### ISSUE TITLE
Creating a payment - Operation timed out

### ISSUE THREAD

**Issue by UnlimitedSRB** [paypal/PayPal-PHP-SDK#527]
From tonight I am getting sometimes this error when my app is creating a Payment.

For Sandbox everything is working fine but if I set to live, it works just sometimes. 

![serrndf](https://cloud.githubusercontent.com/assets/18101642/14065984/a175561e-f43e-11e5-87ba-1b2057ab944f.png)

**Comment by ahfeel** [comment]
+1 :/

**Comment by UnlimitedSRB** [comment]
@ahfeel So you had the same problem as me? Did you find any solution yet?

I already Checked PHP, CURL , OpenSSL , also checked the SDK version which is also up2date. 
I am also not getting this error every time which is pretty suspect because sometimes its working and I am getting redirected to PayPal and sometimes I am getting this error. And when I am testing on Sandbox everything is running perfectly.

**Comment by ppmtscory** [comment]
@UnlimitedSRB can you please file a ticket with our [Merchant Tech Support](https://www.paypal-techsupport.com/app/ask) team please?  They will need to look at your account as well as pull attempt specific logs so I don't want you to list out your Live account details in this public forum.  Please provide your account number, client ID you are using, date/time stamp (with timezone) of when a timeout occurred, and lastly any relevant debug logs to include any debug IDs and/or requests/responses.
