### ISSUE TITLE
Change localization of Paypal Payment page ?

### ISSUE THREAD

**Issue by guldil** [paypal/PayPal-PHP-SDK#529]
Hi,

How is defined the language used on paypal payment page ?
How can i set it ? I tried PayerInfo() class with only Country Code & Email but i got a 400 Error.

Thanks

Guldil

**Comment by bluk** [comment]
You may want to look at the [Payment Experience Web Profile resource](https://developer.paypal.com/docs/rest/api/payment-experience/#web-profile) and create one with the `presentation`'s `locale_code` set. You can create the web profile once, and then reference it when creating the payment as the `experience_profile_id`.

There are some [PHP samples for creating the Payment Experience](https://github.com/paypal/PayPal-PHP-SDK/tree/master/sample/payment-experience).

Note that after a customer logs in, the experience may switch the language to the customer's country where they registered.

If you need any other help, please open a new issue or leave a comment. Thanks.

**Comment by guldil** [comment]
It's working !

Thanks a lot.
