### ISSUE TITLE
How to set locale/language to be unsed on PayPal checkout page

### ISSUE THREAD

**Issue by SDPrio** [paypal/PayPal-PHP-SDK#532]
Hi,

after creating a new payment using the SDK the user is redirected to the approval page. How can I set the language of this page? My webpage is running in multiple different languages and the each user can store his country and preferred language his user account. Thus passing this information to PayPal would be no problem. But what is the correct parameter for this?

On Google I found, that one could set the shipping address within the item list. The country value inside the address would than be used to set the language. There are two problems with this solution:

1. I do not collect any address information from the users since I do not need them. Thus passing a complete address is not possible. I tried to set only the country property, but this leads to an VALIDATION_ERROR, saying that state, city and zip code are incorrect. It seems, that not only the syntax of the values is checked, but also if the address is real. Thus passing "1245 Fake City" does not work. 

2. The solution does not work. Even if I pass a real address (just searched for a Hotel address in the US), the PayPal page is still displayed in my local language (German). 

Another hint from Google was to add a payer_info object to the payer inside the created payment. This leads to an MALFORMED_REQUEST error:
```
[30-03-2016 11:44:55] PayPal\Core\PayPalHttpConnection: INFO	: Response Status 	: 400
[30-03-2016 11:44:55] PayPal\Core\PayPalHttpConnection: DEBUG	: Response Headers	: HTTP/1.1 400 Bad Request, Date: Wed, 30 Mar 2016 11:44:55 GMT, Server: Apache, PROXY_SERVER_INFO: host=slcsbplatformapiserv3001.slc.paypal.com;threadId=2920, Paypal-Debug-Id: 35249adf24081, CORRELATION-ID: 35249adf24081, Content-Language: *, Connection: close, Connection: close, Paypal-Debug-Id: 35249adf24081, Set-Cookie: X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Dplatformapiserv%26TIME%3D935131990; domain=.paypal.com; path=/; Secure; HttpOnly, Set-Cookie: X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT, Vary: Authorization, Content-Length: 213, Content-Type: application/json, , 
[30-03-2016 11:44:55] PayPal\Core\PayPalHttpConnection: ERROR	: Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payment. {"name":"MALFORMED_REQUEST","message":"Incoming JSON request does not map to API request","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#MALFORMED_REQUEST","debug_id":"35249adf24081"}
[30-03-2016 11:44:55] PayPal\Core\PayPalHttpConnection: DEBUG	: 
```

So, what else can I do to set the page language?

**Comment by bluk** [comment]
@SDPrio : You may want to check out issue #529 which can help change the locale via a web profile experience.

**Comment by bluk** [comment]
Please leave a comment if this isn't what you're looking for, and we'll reopen if needed. Thanks.

**Comment by SDPrio** [comment]
Hi,

I finally found the time to test this solution and it works fine. However I am not sure how to use a WebProfile Experience. 

Do I have to create a new WebProfile for every payment I create? Or can I re-use the same Profile for different Payments?

My shop asks the user for this address including the country. The country is than used to set up the profile:

```
    $profileId = null;	    	
    try {
        $presentation = (new \PayPal\Api\Presentation())
            ->setLocaleCode($order->getCountry())
            ->setBrandName('My Brand');
		    	
        $webProfile = (new \PayPal\Api\WebProfile())
            ->setName(uniqid())
            ->setPresentation($presentation);
		    	
        $createProfileResponse = $webProfile->create($this->getApiContext());
        $profileId = $createProfileResponse->getId();
    } catch (\Exception $ex) { ... }	

    $payer = (new \PayPal\Api\Payer())
        ->setPaymentMethod('paypal');

    $redirect_urls = (new \PayPal\Api\RedirectUrls())
        ->setReturnUrl(...)
        ->setCancelUrl(...);

    $payment = (new \PayPal\Api\Payment())
        ->setIntent('sale')
        ->setPayer($payer)
        ->setRedirectUrls($redirect_urls)
        ->setTransactions(...);

    if (profileId != null)
        $payment->setExperienceProfileId($profileId);
        	
    $payment->create($this->getApiContext());
```

Creating the profile shows the following log:

```
Response Status 	: 201
Response Headers	: HTTP/1.1 201 Created, Date: Tue, 26 Apr 2016 09:31:48 GMT, Server: Apache, PROXY_SERVER_INFO: host=slcsbplatformapiserv3002.slc.paypal.com;threadId=761, Paypal-Debug-Id: 658192502f644, CORRELATION-ID: 658192502f644, Paypal-Debug-Id: 658192502f644, Set-Cookie: X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Dplatformapiserv%26TIME%3D2218073943%26HTTP_X_PP_AZ_LOCATOR%3D; Expires=Tue, 26 Apr 2016 10:01:48 GMT; domain=.paypal.com; path=/; Secure; HttpOnly, Set-Cookie: X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT, Vary: Authorization, Content-Length: 108, Connection: close, Content-Type: application/json, , 
Response Data 		: {"id":"XP-9WL9-VG77-5EFU-R796","name":"571f35838a02d","temporary":false,"presentation":{"locale_code":"US"}}
```
What does `"temporary":false` mean in the response data? Does thes mean, that the profile is stored and can/should be re-used? How would a temporary profile be created?

Re-creating a new profile for all payments seems quite redundant, since the values do not change. One could store the profile ID for each country and re-use it instead. However this would be cumbersome as well. So, what is the correct workflow here?

**Comment by bluk** [comment]
`Do I have to create a new WebProfile for every payment I create? Or can I re-use the same Profile for different Payments?`

You can re-use the same profile for different payments. Normally, you only need to create one per locale per "store" and keep a reference to it and re-use it whenever you create a payment.

The temporary false JSON data is extra data. I don't believe you can create a temporary one at this time.

**Comment by SDPrio** [comment]
Thank you! Are there any downsides on creating a new profile for every payment (except the extra traffic)? 

Creating a store to buffer profile for any locale to re-use them later would be quite cumbersome at them moment.

**Comment by bluk** [comment]
I would encourage you to re-use the same profile as soon as possible, but I don't believe there are any current limitations/restrictions for creating a web profile per payment.

**Comment by jaypatel512** [comment]
You could potentially hard code those Ids once you have created per language. It shouldn't be any more than a KeyValue lookup.

**Comment by SDPrio** [comment]
Ok, one last question: Is the API the only way to create and list the profiles? Or is it somehow possible to use an UI within my PayPal account or the Dev center?

**Comment by bluk** [comment]
@SDPrio There isn't a UI to do this, but you can use `curl`, Postman, Paw, or any other HTTP client/tool to create the profiles manually.
