### ISSUE TITLE
Got Http response code 500

### ISSUE THREAD

**Issue by vitorbarros** [paypal/PayPal-PHP-SDK#533]
Hi, 
Yesterday I implemented PayPal Payment based on this sdk sample "http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/CreatePaymentUsingPayPal.html". 

So, everything was working really well, but today when I did some tests I got the exception:
"Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment."

I tried a lot of solutions, such do API call using Postman, but I got the same error.

So, what you suggest me to do?

**Comment by ppmtscory** [comment]
@vitorbarros please watch issue #531 for updates to this.
