### ISSUE TITLE
How to get Payment transaction_fee? Not included in data. 

### ISSUE THREAD

**Issue by SDPrio** [paypal/PayPal-PHP-SDK#536]
Hi,

I am testing the PHP SDK using the Sandbox. The API docu says, that the Sale Object should contain information about the transaction_fee. The Sale class offers the necessary getter and setter, but neither the JSON data received when calling the ReturnUrl, nor the JSON data reveived on PAYMENT.SALE.COMPLETED and PAYMENT.SALE.PENDING webhook events contain the transaction_fee.

```
"sale"": {
    "id":"9NH012373F480761D",
    "state":"completed",
    "amount": {
        "total":"9.00",
        "currency":"EUR",
        "details":{
            "subtotal":"9.00"
        }
    },
    "payment_mode":"INSTANT_TRANSFER",
    "protection_eligibility":"ELIGIBLE",
    "protection_eligibility_type":"ITEM_NOT_RECEIVED_ELIGIBLE,UNAUTHORIZED_PAYMENT_ELIGIBLE",
    "parent_payment":"PAY-33R937871K3118932K37EVBI",
    "create_time":"2016-04-01T10:16:53Z",
    "update_time":"2016-04-01T10:16:53Z",
    "links":[
        {
            "href":"https://api.sandbox.paypal.com/v1/payments/sale/9NH012373F480761D",
            "rel":"self",
            "method":"GET"
        },
        {
            "href":"https://api.sandbox.paypal.com/v1/payments/sale/9NH012373F480761D/refund",
            "rel":"refund",
            "method":"POST"
        },
        {
            "href":"https://api.sandbox.paypal.com/v1/payments/payment/PAY-33R937871K3118932K37EVBI",
            "rel":"parent_payment",
            "method":"GET"
        }
    ]
}

```

So, how to get this information? Is this a Sandbox problem?

**Comment by ppmtscory** [comment]
@SDPrio what call is that you are doing there?  I'm seeing the `transaction_fee` just fine when I do a lookup of a Sale....
```

**Comment by ppmtscory** [comment]
Upon further testing, I see that the documentation shows that `transaction_fee` should be returned in the Sale object of an Execute response, and it's not being returned.  I will file a bug accordingly.

For internal bookkeeping - PPPLMER-12538

**Comment by SDPrio** [comment]
Thank you very much. Is there any estimate on how long it will take to fix the error? I just what to know if I need to build some kind of workaround (e.g. re-fetching the sales object?) before my webpages goes live.

**Comment by ppmtscory** [comment]
Unfortunately I don't have any ETA that I can provide confidently.  My recommendation would be to do a quick lookup of the Sale so that you have the information you need.  Even if you implement it and it's fixed prior to your go Live date, there's no real harm in having that extra call there, until you want to remove it with a later update.

**Comment by ppmtscory** [comment]
@SDPrio sorry for the delay in getting back to this, but this issue has been resolved.  I now see the `transaction_fee` in the Sale object of the Execute response.
