### ISSUE TITLE
Sample => Obtain User Consent

### ISSUE THREAD

**Issue by aquachroma** [paypal/PayPal-PHP-SDK#538]
Hello,

This is to continue #524 since we aren't given a way to re-open an issue unless we ourselves close it.

I'm hoping the sample: Obtain User Consent is designed to provide an individual a window to link their PayPal account to our application. When I click Obtain User Consent I'm receiving this error:

~~~~~~~~~~~~
Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/identity/openidconnect/tokenservice.

{
    "error_description": "authorization code is null",
    "error": "unauthorized_client",
    "correlation_id": "a0c23a1ff3fc5",
    "information_link": "https://developer.paypal.com/docs/api/#errors"
}
~~~~~~~~~~~~

To me this sounds like somehow I already need authorization to their account which seams counter intuitive since I'm attempting to "Obtain Users Consent".

Am I misunderstanding the intent of this sample? If so, what should I be using to initialize obtaining users consent?

**Comment by ppmtscory** [comment]
@aquachroma the authorization code is returned to you after the consumer has selected to provide authorization on the PayPal pages.  You redirect to PayPal where the user consents.  As part of that redirect, you specified a return url to bring them back to.  After they consent to whatever it is you want, then the authorization code is then returned to your return URL via a GET parameter.  This is the code that you then send to the `/tokenservice` endpoint that you listed above in your question.

**Comment by aquachroma** [comment]
@ppmtscory, I've found the documentation from PayPal API on how to achieve third party permissions from their website:
https://developer.paypal.com/docs/classic/permissions-service/ht_permissions-invoice/

I'm struggling to find the portion of this PHP SDK that was made to handle that API request. I really thought Obtain User Consent was designed for that but I must have been mistaken...I can create my own method to do this but I'm trying to not reinvent the wheel.

**Comment by ppmtscory** [comment]
Ah, yes, this SDK is for the REST API so you'd need to use Login with PayPal sections to obtain the permissions that are available with that service.  The link you provided is for the Classic API (Permissions Service) and is not included in this SDK.
