### ISSUE TITLE
Internal Service Error 

### ISSUE THREAD

**Issue by kmohsin** [paypal/PayPal-PHP-SDK#542]
Didnt encounter this yesterday , but I woke up to this error for all transactions : Its bizarre , it was working when I left but I got this error suddenly , please help asap.

[url:PayPal\Exception\PayPalConnectionException:private] => https://api.sandbox.paypal.com/v1/payments/payment/PAY-2LL60113FU183324LK4CUEQQ/execute
[data:PayPal\Exception\PayPalConnectionException:private] => {"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"6e0c3adf048a"}
... 
...
Furthermore , I noticed the UI screen changed overnight  and it was prompting twice for username / pwd.

**Comment by juwlee** [comment]
It might be related to [an outage posted on paypal-notify](paypal/PayPal-PHP-SDK/issues/534). Do you still see this issue?

**Comment by kmohsin** [comment]
The error disappeared in few hours after I reported, thank you
