### ISSUE TITLE
I have a problem with AMEX card

### ISSUE THREAD

**Issue by krasho** [paypal/PayPal-PHP-SDK#546]
Hello my name is Jose Luis. I am using PayPal-PHP-SDK to register payments. I am getting this error "An unknown error has occurred" when I try to pay with AMEX card.

What is the reason?? What Can I Do to resolve the problem?

Thanks

**Comment by ppmtscory** [comment]
Can you let us know a debug ID for the error?  It may be that you are using an usupported currency for AMEX or that your account isn't set up to process AMEX cards.

**Comment by krasho** [comment]
Hello, Cory thanks.

The debug ID is : 38e49362e71fc.

How can I check if my account have to set up process AMEX cards?

Thanks

2016-04-07 12:32 GMT-05:00 Cory <notifications@github.com>:

**Comment by ppmtscory** [comment]
@krasho your merchant (receiving) account is set to block payments that fail address validation via CC payments and that is what's happening with your test.  Can you provide the full response you get from the SDK so that I can double-check the error mapping for this particular scenario?

**Comment by krasho** [comment]
Hello Cory.

the full response is:

{"name":"UNKNOWN_ERROR","message":"An unknown error has
occurred","information_link":"
https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR
","debug_id":"38e49362e71fc"}

It is all.

what is the problem with address validation?

I am sending you a screenshot with the data.




Thanks.





2016-04-07 13:05 GMT-05:00 Cory <notifications@github.com>:

**Comment by ppmtscory** [comment]
Thank you for that.  Screen shot is not needed.  When you submit your payment, the address that you sent along, is coming back as a 'no match' from your card issuer.  If you're not sending an address at all, then you'll need to modify the fraud filters on your merchant account to not check for address validation.  I'm going to close this issue now, but I'll look into the error mapping for that specific scenario.
