### ISSUE TITLE
Modify InvoiceNumber after payment success ?

### ISSUE THREAD

**Issue by guldil** [paypal/PayPal-PHP-SDK#549]
Hi,

After a successfull payment can i change invoice number to set another value ?

The main goal is to have invoice IN the Paypal Dashboard to help our team tracking payment but we only have the invoice number after payment...

Thanks

Guldil

**Comment by ppmtscory** [comment]
No, you won't be able to add the invoice number after the fact.  For your use case, it'd probably be beneficial to map your invoice number to the PayPal transaction ID.  That way when you look up your invoice number internally, you can cross reference that with the transaction ID from the PayPal side.
