### ISSUE TITLE
Discounts are not calculated

### ISSUE THREAD

**Issue by mwhawkins** [paypal/PayPal-PHP-SDK#55]
The PayPal validation rules require that:
1. The total items cost must add up to the subtotal and,
2. The subtotal + shipping + tax add up to the total.

When using discounts, there is no place to set the discount so the transaction is rejected as the subtotal + shipping + tax does not equal the total order amount AND/OR the total of item costs will not equal the subtotal (depending on how/when the discount is factored).

We need a way to set discounts on transactions. This is a core feature I would have thought to have been included amongst the first implemented in the ReST API (common sense), but apparently not, therefore I seek another solution to it in the interim.  I have scoured the internet and found no less than a half dozen other reports/complaints of this issue on StackOverflow and other sites.

**Comment by c4ss** [comment]
Found another bug relating to this.

If you submit a negative amount item such as 'Discount' at '-3.50', if it brings your subtotal to 0 you get a 400 response:

The remote server returned an error: (400) Bad Request.

The only way I can get around this is by making by delivery charge my subtotal and vice versa, so:

ERRORS ON:
Shop Item: 3.50
Discount: -3.50
Delivery: 2.00
Subtotal: 0.00 

WORKAROUND:

Shop Item: 3.50
Discount: -3.50
Delivery: 0.00
Subtotal: 2.00 

Workaround works fine but isn't ideal because the delivery isn't what it is in real life.

**Comment by jaypatel512** [comment]
Hey @c4ss ! I was able to reproduce the issue. I have already sent an email to Payments team who develops these APIs. I will keep you updated on this.

**Comment by DannyZB** [comment]
What is the solution for recurring payments discounts?
Recurring payments don't support multiple items.

**Comment by littlewhitedragonIN** [comment]
Now,the restfulAPI is available for negative value. Either 5 or 5.00, both is okay.

**Comment by razie** [comment]
I just got this again, using the checkout.js via paypal.rest.payment.create(...) followed by actions.payment.execute()

```
Error: Payment Api response error:

{
    "name": "VALIDATION_ERROR",
    "details": [
        {
            "field": "transactions.item_list.items",
            "issue": "Currency amount must be non-negative number, may optionally contain exactly 2 decimal places separated by '.', optional thousands separator ',', limited to 7 digits before the decimal point and currency which is a valid ISO Currency Code"
        }
    ],
    "message": "Invalid request - see details",
    "information_link": "https://developer.paypal.com/docs/api/#VALIDATION_ERROR",
    "debug_id": "5f5aa1bec5bc"
```

The item in question has a negative price (it is a credit applied to the total:

```
 {
                    name : 'CREDIT/DEBIT applied',
                    description : 'Account balance before the checkout',
                    quantity : '1',
                    price : '-35.0',
                    currency : 'CAD'
                  },

```
