### ISSUE TITLE
MALFORMED_REQUEST Error, no idea how to resolve it

### ISSUE THREAD

**Issue by Smileysoftware** [paypal/PayPal-PHP-SDK#551]
Hi,

I'm using the SDK to send a payment. Everything seems to have the correct data however I am seeing the following error no matter what I send.
`object(stdClass)#18 (4) {
  ["name"]=>
  string(17) "MALFORMED_REQUEST"
  ["message"]=>
  string(49) "Incoming JSON request does not map to API request"
  ["information_link"]=>
  string(74) "https://developer.paypal.com/webapps/developer/docs/api/#MALFORMED_REQUEST"
  ["debug_id"]=>
  string(12) "126d95d7c108"
}`

My class is as follows
`<?php
/*
* Configure the vendor package and create a new context.
*/
require_once('../../../vendor/autoload.php');

use PayPal\Api\Amount;
use PayPal\Api\CreditCard;
use PayPal\Api\Details;
use PayPal\Api\FundingInstrument;
use PayPal\Api\Item;
use PayPal\Api\ItemList;
use PayPal\Api\Payer;
use PayPal\Api\Payment;
use PayPal\Api\Transaction;

class PPP
{

    /**
     * @var pdo
     */
    public $db;

    /**
     * @var
     */
    public $clientID;
    /**
     * @var
     */
    public $clientSecret;

    /**
     * @var string
     */
    protected $paymentMethod = 'credit_card';

    /**
     * @var
     */
    private $items;
    /**
     * @var
     */
    private $itemList;

    /**
     * @var
     */
    private $detail;
    /**
     * @var
     */
    private $payer;
    /**
     * @var
     */
    private $currency;

    /**
     * @var
     */
    public $payment;

    /**
     * @var
     */
    private $apiContext;

    /**
     * @var
     */
    private $tax;

    /**
     * PPP constructor.
     *
     * @param $dbhost
     * @param $dbusername
     * @param $dbpassword
     * @param $dbname
     */
    function __construct ($dbhost, $dbusername, $dbpassword, $dbname)
    {

        /*
         * Connect tut dinklebase
         */
        try {
            $this->db = new pdo('mysql:host=' . $dbhost . ';dbname=' . $dbname . ';charset=utf8mb4', $dbusername, $dbpassword);

            $stmt = $this->db->query("SELECT * FROM ecomms_paypal_pro_settings WHERE id='1'");

            $data = $stmt->fetch(PDO::FETCH_ASSOC);

            $this->client_id = $data['client_id'];
            $this->client_secret = $data['client_secret'];

        } catch (PDOException $ex) {
            die(json_encode([
                'outcome' => false,
                'message' => 'Unable to connect'
            ]));
        }

    }

    /**
     * @return \PayPal\Rest\ApiContext
     */
    public function createContext ()
    {
        $apiContext = new \PayPal\Rest\ApiContext(
            new \PayPal\Auth\OAuthTokenCredential(
                $this->client_id,     // ClientID
                $this->client_secret      // ClientSecret
            )
        );

        $this->apiContext = $apiContext;
    }

    /**
     * @param $cardData
     */
    public function newCard ($cardData)
    {
        $card = new CreditCard();
        $card->setType($cardData['type'])
            ->setNumber($cardData['number'])
            ->setExpireMonth($cardData['expireMonth'])
            ->setExpireYear($cardData['expireYear'])
            ->setCvv2($cardData['cv3'])
            ->setFirstName($cardData['firstname'])
            ->setLastName($cardData['surname']);

        $this->currency = $cardData['currency'];

        $fi = new FundingInstrument();
        $fi->setCreditCard($card);

        $this->payer = new Payer();
        $this->payer->setPaymentMethod($this->paymentMethod)
            ->setFundingInstruments([$fi]);
        
    }

    /**
     * @param $basket
     */
    public function addItems ($basket)
    {
        $counter = 0;
        $list = array();

        foreach ($basket as $basketItem) {

            //Create an individual item
            $list[$counter] = self::createItem([
                'name'        => $basketItem['product_name'],
                'description' => $basketItem['product_name'], //Fudged in because there isn't a description in the basket array
                'currency'    => $this->currency,
                'quantity'    => $basketItem['qty'],
                'tax'         => $basketItem['price_vat'],
                'price'       => $basketItem['price_gross']
            ]);

            $counter++;

        }

        /*
         * Create the item list
         */
        $itemList = new ItemList();
        $this->itemList = $itemList->setItems($list);

    }

    /**
     * @param $itemData
     *
     * @return Item
     */
    public function createItem ($itemData)
    {
        $item = new Item();
        $item->setName($itemData['name'])
            ->setDescription($itemData['name'])
            ->setCurrency($itemData['currency'])
            ->setQuantity($itemData['quantity'])
            ->setTax(floatval($itemData['tax']))
            ->setPrice(floatval($itemData['price']));

        $this->generateTotalTax(floatval($itemData['tax']));

        return $item;
    }

    /**
     * @param $shipping_cost
     * @param $shipping_vat
     * @param $order_amount
     */
    public function addDetail ($shipping_cost, $shipping_vat, $order_amount)
    {
        $details = new Details();

        //Make sure either the shipping is returned or a 0
        $total_shipping = $shipping_cost + $shipping_vat;
        if($total_shipping < 1){
            $total_shipping = 0;
        }

        $details->setShipping($total_shipping)//The total value of shipping. cost + vat
            ->setTax($this->tax)//This is the vat for the whole order.
            ->setSubtotal($order_amount); //Ths subtotal for the whole order. i.e. ex VAT

        $this->detail = $details;
        
    }

    /**
     * @param $total
     */
    public function setupPayment ($total)
    {

        $amount = new Amount();
        $amount->setCurrency($this->currency)
            ->setTotal($total + $this->tax)
            ->setDetails($this->detail);

        $transaction = new Transaction();
        $transaction->setAmount($total + $this->tax)
            ->setItemList($this->itemList)
            ->setDescription(urlencode("Purchase from " . $_SESSION['company_name']))
            ->setInvoiceNumber(uniqid());

        $payment = new Payment();
        $payment->setIntent("sale")
            ->setPayer($this->payer)
            ->setTransactions(array($transaction));

        $this->payment = clone $payment;

    }

    /**
     * @return mixed
     */
    public function createPayment ()
    {

        $state = $this->payment->create($this->apiContext);

        return $state;
    }

    /**
     * @param $itemTax
     */
    private function generateTotalTax ($itemTax)
    {
        $this->tax = $this->tax + $itemTax;
    }

}

`

I am seeing the following response in the sandbox console.

`{
 "body": {
  "intent": "sale",
  "payer": {
   "payment_method": "credit_card",
   "funding_instruments": [
    {
     "credit_card": {
      "first_name": "Mariam",
      "last_name": "Sanford",
      "expire_month": "11",
      "number": "xxxxxxxxx5678",
      "expire_year": "2018",
      "type": "visa"
     }
    }
   ]
  },
  "transactions": [
   {
    "item_list": {
     "items": [
      {
       "name": "70cm x 72cm Back Panel",
       "price": "88.99",
       "description": "70cm x 72cm Back Panel",
       "tax": "14.83",
       "currency": "GBP",
       "quantity": "5"
      },
      {
       "name": "Microwave Oven 900W, 25L",
       "price": "260.06",
       "description": "Microwave Oven 900W, 25L",
       "tax": "43.34",
       "currency": "GBP",
       "quantity": "1"
      }
     ]
    },
    "amount": 811.18,
    "description": "Purchase+from+Shop",
    "invoice_number": "570cd87b9532a"
   }
  ]
 },
 "header": {
  "x-pp-ads-performed": "false",
  "content-length": "655",
  "paypal-request-id": "32599295965966146045964321737",
  "x-pp-silover": "name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Dplatformapiserv%26TIME%3D2111310935",
  "accept": "*/*",
  "client-auth": "No cert",
  "authorization": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxq29G",
  "host": "api.sandbox.paypal.com",
  "user-agent": "PayPalSDK/PayPal-PHP-SDK 1.6.4 (platform-ver\\u003d5.6.16; bit\\u003d64; os\\u003dLinux_2.6.32-573.8.1.el6.x86_64; machine\\u003dx86_64; crypto-lib-ver\\u003d1.0.1e-fips; curl\\u003d7.19.7)",
  "x-slr-orig-script_uri": "https://api.sandbox.paypal.com/v1/payments/payment",
  "x-pp-corrid": "126d95d7c108",
  "pp_remote_addr": "194.78.147.252",
  "content-type": "application/json",
  "x-pp-slingshot-targetapp": "platformapiserv"
 },
 "additional_properties": {},
 "method": "POST"
}
Close`

The data is total junk and I would expect an error.
There is clearly something wrong with the payload I am sending however I have no idea what that might be.
Any guidance would be greatly appreciated.

Thanks

**Comment by Smileysoftware** [comment]
Resolved the issue myself in the end. It turns out I was adding tax in the wrong place.

It would be nice if there was some docs that explained that each method should expect but thanks for all the help...

**Comment by jaypatel512** [comment]
Hey @Smileysoftware !

Its great to know that you were able to resolve the issue. However, we have a lot of documentation focused just on PHP SDK. You can find all the resources at http://paypal.github.io/PayPal-PHP-SDK/.

Wiki Pages: https://github.com/paypal/PayPal-PHP-SDK/wiki
Sample Code: http://paypal.github.io/PayPal-PHP-SDK/sample/
Source documentation : http://paypal.github.io/PayPal-PHP-SDK/docs/
