### ISSUE TITLE
Send payments to a different paypal account/recipient dynamically

### ISSUE THREAD

**Issue by kmohsin** [paypal/PayPal-PHP-SDK#555]
A Basic question : Would this be possible in this API: I am looking to send payments to a selected recipient which has a different paypal email other than what its present in the bootstrap ( identified by clients) that pretty much ties me upto only send payment to that client id. Would this be possible in doing it in createpaymetusingpaypal.php ? If not what is the correct API to use ?

thanks

**Comment by bluk** [comment]
You probably should look at the [SOAP/NVP API - Mass Payment in particular](https://developer.paypal.com/docs/classic/api/#mp). The REST API does not support the scenario you described unless you have a client ID for the recipient.

**Comment by kmohsin** [comment]
ok thanks , I realize that  question is precisely the same as : 
https://github.com/paypal/PayPal-PHP-SDK/issues/107
is this still in the works ?

**Comment by bluk** [comment]
@kmohsin I suggest trying the SOAP/NVP APIs and their [respective SDKs](https://developer.paypal.com/docs/classic/lifecycle/sdks/) for now.

Enabling multiple adaptive payments and other features in the REST API have long been in the planning/working on state. Unfortunately, I don't have any news at this time.
