### ISSUE TITLE
Payment "Client Authentication failed" 401 error

### ISSUE THREAD

**Issue by pythonw** [paypal/PayPal-PHP-SDK#558]
Hello, I must premise that works all sandboxed, but in live mode the last process in the check payment, it gives me this error.

when performing this method:
` $payment = Payment::get($paymentId, $apiContext);`

> 401{"error":"invalid_client","error_description":"Client Authentication failed"}exception 'PayPal\Exception\PayPalConnectionException' with message 'Got Http response code 401 when accessing https://api.sandbox.paypal.com/v1/oauth2/token.' in /var/www/html/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php:174 Stack trace: #0 /var/www/html/vendor/paypal/rest-api-sdk-php/lib/PayPal/Auth/OAuthTokenCredential.php(249): PayPal\Core\PayPalHttpConnection->execute('grant_type=clie...') #1 /var/www/html/vendor/paypal/rest-api-sdk-php/lib/PayPal/Auth/OAuthTokenCredential.php(274): PayPal\Auth\OAuthTokenCredential->getToken(Array, 'AcPbmCdlU6kfqz-...', 'EOGBs10xmWCFCkr...', 'grant_type=clie...') #2 /var/www/html/vendor/paypal/rest-api-sdk-php/lib/PayPal/Auth/OAuthTokenCredential.php(218): PayPal\Auth\OAuthTokenCredential->generateAccessToken(Array, NULL) #3 /var/www/html/vendor/paypal/rest-api-sdk-php/lib/PayPal/Auth/OAuthTokenCredential.php(168): PayPal\Auth\OAuthTokenCredential->updateAccessToken(Array) #4 /var/www/html/vendor/paypal/rest-api-sdk-php/lib/PayPal/Handler/RestHandler.php(83): PayPal\Auth\OAuthTokenCredential->getAccessToken(Array) #5 /var/www/html/vendor/paypal/rest-api-sdk-php/lib/PayPal/Transport/PayPalRestCall.php(71): PayPal\Handler\RestHandler->handle(Object(PayPal\Core\PayPalHttpConfig), '', Array) #6 /var/www/html/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PayPalResourceModel.php(102): PayPal\Transport\PayPalRestCall->execute(Array, '/v1/payments/pa...', 'GET', '', NULL) #7 /var/www/html/vendor/paypal/rest-api-sdk-php/lib/PayPal/Api/Payment.php(603): PayPal\Common\PayPalResourceModel::executeCall('/v1/payments/pa...', 'GET', '', NULL, Object(PayPal\Rest\ApiContext), NULL) #8 /var/www/html/vendor/check_payment.php(24): PayPal\Api\Payment::get('PAY-4GD65721T43...', Object(PayPal\Rest\ApiContext)) #9 {main}

It could be a oauth problem? I can not understand what it is.

**Comment by pp-randy** [comment]
The exception is indicating your request went to the sandbox  https://api.sandbox.paypal.com/v1/oauth2/token

Can you check your configuration and make sure your environment is for live?

**Comment by pythonw** [comment]
I have been following [this guide ](http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/ExecutePayment.html
)
the ClientID and ClientSecret are taken from the live box.

how can I change https://api.sandbox.paypal.com/v1/oauth2/token to another?

**Comment by pythonw** [comment]
My configuration is here
`<?php

use PayPal\Api\Amount;
use PayPal\Api\Payment;
use PayPal\Api\PaymentExecution;
use PayPal\Api\Transaction;

session_start();
require __DIR__ . '/start.php';


if (isset($_GET['approved']) && $_GET['approved'] == 'true') {


    try {
        $payerId = $_GET['PayerID'];


        try {
            $paymentId = $_GET['paymentId'];
            $payment = Payment::get($paymentId, $apiContext);
        } catch (Exception $ex) {
            echo $ex->getCode(); // Prints the Error Code


            echo $ex->getData(); // Prints the detailed error message

            die($ex);
        }




        $execution = new PaymentExecution();
        $execution->setPayerId($_GET['PayerID']);


        $execution = new PaymentExecution();
        $execution->setPayerId($payerId);


        $transaction = new Transaction();
        $amount = new Amount();



        $amount->setCurrency('USD');
        $amount->setTotal(0.05);
        $transaction->setAmount($amount);

        $execution->addTransaction($transaction);


        try {
            $payment->execute($execution, $apiContext);
        } catch (PayPalConnectionException $ex) {
            echo $ex;
        }



        }

        return $payment;

        header('Location: /dashboard.php?true');
    } catch (PayPalConnectionException $e) {
        echo $e->getData();
        // Perhaps log an error


    }




} else {
    echo 'No working';
    exit;
}`

**Comment by pp-randy** [comment]
These samples might help depending on your configuration.  

Using a config file?
https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/bootstrap.php#L58
https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/sdk_config.ini#L24

Or Coding your configuration?
https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/bootstrap.php#L86

**Comment by pythonw** [comment]
I added the bootstrap files and now works, thanks. done

**Comment by jaypatel512** [comment]
There is a documentation wiki page explaining how to [switch to live](https://github.com/paypal/PayPal-PHP-SDK/wiki/Going-Live).
