### ISSUE TITLE
How to capture and authorize the payment with new amount after creating it and executing ?

### ISSUE THREAD

**Issue by safaa-alnablsi** [paypal/PayPal-PHP-SDK#560]
Hello, I have already Pending payments with `intent = order`.
And I want to authorize a new amount (or maybe the same amount) for the payment and then capture the authorized amount (or new amount). Is that possible ? 

I didn't find function "authorize ", in this library. it's like we can only do this when we create a new payment with `intent = authorize`.
But in my case I already have the payment and the order stored in db, I can retrieve them like I did when I cancelled the order  :

```
  $order = PayPalOrder::get($orderId, $apiContext);
  $result = $order->void($apiContext);
```

so how can I do authorize payment without defining a new payment with all the parameters, since only the amount may change ! 

` $payment = PaypalPayment::get($paymentId, $apiContext);`

Thanks for help !

**Comment by pp-randy** [comment]
I see the issue was closed. Did you find an answer @safaa-alnablsi?

**Comment by safaa-alnablsi** [comment]
Yes, actually. I found example called "OrderAuthorize.php" and "OrderCapture.php"
so what I found is that:
1- I can authorize a payment with new amount. 
2- also capture with new amount but not over 15% more than the basic amount! 
3- also the authorize doesn't effect the capture! 
4- you can do multi captures until you reach (amount + 15% of amount) then it will be completed. and you can't send more capture requests.
5- the state you get during these captures is always 'completed' for these partial captures.

Thanks!
