### ISSUE TITLE
Class not found when executing payment

### ISSUE THREAD

**Issue by Scilly-guy** [paypal/PayPal-PHP-SDK#562]
I have this source (based off the example):
````
<?php
require 'bootstrap.php';
use PayPal\Api\Payment; 
use Paypal\Api\PaymentExecution;
use PayPal\Api\ExecutePayment;

if(isset($_GET['success'])&&$_GET['success']=='true')
{
	$paymentId=$_GET['paymentId'];
	$payment= Payment::get($paymentId,$apiContext);
	
	$execution=new PaymentExecution();
	$execution->setPayerId($_GET['PayerID']);
	
	try{
		$result=$payment->execute($execution,$apiContext);
	}catch (Exception $ex)
	{
		die($ex);
	}
	var_dump($payment);
}
else {
		echo "Sorry";
}
?>
````
But I get: "Fatal error: Class 'Paypal\Api\PaymentExecution' not found in /var/sites/2/28miles.co.uk/public_html/pay.php on line 12". Any ideas?

**Comment by jaypatel512** [comment]
Do you infact have a bootstrap.php file similar to what is shown in the [sample](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/bootstrap.php)

I would highly recommend going through [PayPal PHP SDK tutorial](https://github.com/paypal/PayPal-PHP-SDK/wiki/Installation), as provided in the wiki to get started pretty quickly.

Let me know if that helps. Make sure, if you are using composer, you are doing `require 'vendor/autoload.php'` in your bootstrap file. Dont forget to do `composer update` to get the latest version.

**Comment by Scilly-guy** [comment]
Yes the bootstrap file is there and works fine, I complete the first stage of getting authorisation and that requires the bootstrap file, these two files (checkout.php and pay.php) are in the same directory, with the bootstrap.php. Checkout works Pay does not.

**Comment by jaypatel512** [comment]
Can you confirm what version of SDK are you using ?

**Comment by Scilly-guy** [comment]
1.6.4

**Comment by jaypatel512** [comment]
Are you able to find the file at `/vendor/paypal/rest-api-sdk-php/lib/PayPal/Api/PaymentExecution.php` ?

If not an issue, would you mind sharing your code over github, or just pasted here. Feel free to omit sensitive code/information. The issue seems to be specific to your case, so it may be because of the setup. Sharing the code should help.

**Comment by Scilly-guy** [comment]
Yes I have that file and it contains the PaymentExecution class which the line in question calls. I have double checked the spelling of every word, I have copied and pasted the sample code, I have retyped it, I have copied and pasted the class name. Its a really weird error, especially as sometimes I can get the same error but from the Payment::get() line (10). The weird thing being that step1 (checkout - getting authorisation) uses the payment class too and that is working fine. I can share my code if you like but to be honest I don't possibly see how it will help, the only line that I can think that is relevant is the return URL from the checkout:
`
	$baseUrl="http://www.28miles.co.uk";
	$redirectUrls=new RedirectUrls();
	$redirectUrls->setReturnUrl("$baseUrl/pay.php?success=true")
`
Hmm, perhaps it has something to do with the domain: www.28miles.co.uk - I am developing the new site and have configured my hosts file to use the new server. Could it have anything to do with that, because to me it looks like something funny going on with php rather than paypal specifically.

**Comment by Scilly-guy** [comment]
hmm, well I have tried using the address accessible by the public but that didn't fix it. For reference that is: 28miles.co.uk.gridhosted.co.uk

**Comment by jaypatel512** [comment]
Do you have a temporary paymentId that I can use to test it ?

**Comment by jaypatel512** [comment]
If you look at the samples hosted in your code, you should be able to complete the sample as shown here: http://28miles.co.uk.gridhosted.co.uk/PayPal-PHP-SDK/paypal/rest-api-sdk-php/sample/index.php

Please refer to the sample files, and see if you can match the code. I think the issue is not related to the SDK but to the environment.

**Comment by Scilly-guy** [comment]
So previously I have tried copying and pasting the sample code, if you compare them you will notice they are almost identical, although I do not follow the optional step, I definitely copied the use lines. However I have done it again and this time it is working, I am now able to complete purchases. Thank you very much for getting me to try it again. all I changed were the first few lines:
`
require 'bootstrap.php';
use PayPal\Api\Amount;
use PayPal\Api\Details;
use PayPal\Api\ExecutePayment;
use PayPal\Api\Payment;
use PayPal\Api\PaymentExecution;
use PayPal\Api\Transaction;
`
I assumed that as I wasn't using details and transaction classes and so could leave them out. It just seems so odd that php was giving the error with the classes I HAD included. Anyway, thanks, completely my fault.

**Comment by jaypatel512** [comment]
No worries. I think the issue was really weird to me too. Something was not making sense. But anyway, glad that you have it working. Sometimes, the php opcache could cause these issues where the files you are looking at is not the same as the one they compile. 

Glad it got fixed.

**Comment by kafuwale** [comment]
@Scilly-guy : Even though the problem is solved, just want to hilight the prblem 

First time you were using 
use Paypal\Api\PaymentExecution : Wrong
use PayPal\Api\ExecutePayment;  : Correct 

Notice the difference <Paypal> and <PayPal>
:)

**Comment by fredattack** [comment]
hello, I have the same problem, can't find a solution! 
`namespace App\Http\Controllers;
use App\Http\Requests;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Input;
/** All Paypal Details class **/
use PayPal\Rest\ApiContext;
use PayPal\Auth\OAuthTokenCredential;
use PayPal\Api\Amount;
use PayPal\Api\Details;
use PayPal\Api\Item;
use PayPal\Api\ItemList;
use PayPal\Api\Payer;
use PayPal\Api\ExecutePayment;
use PayPal\Api\Payment;
use PayPal\Api\RedirectUrls;
use PayPal\Api\PaymentExecution;
use PayPal\Api\Transaction;`
I have an error "Undefined class ExecutePayement."
How can I solved this issue?

**Comment by xiaoleih41** [comment]
@fredattack It should be **ExecutePayment** not **ExecutePayement**.

**Comment by fredattack** [comment]
thx xiaoleih41 but I use PayPal\Api\ExecutePayment;

**Comment by xiaoleih41** [comment]
ah. the error message you showed me is different. Can you give me a debrugId?

**Comment by Puni89** [comment]
I do have the same error but in my case am not able to find setup:di: compile

/vendor/paypal/rest-api-sdk-php/lib/PayPal/Api/PaymentExecution.php
