### ISSUE TITLE
Billing agreements never become 'Active'

### ISSUE THREAD

**Issue by omarkilani** [paypal/PayPal-PHP-SDK#564]
Hi PayPal,

We're seeing some strange stuff with billing agreements on both the sandbox and live where the agreement never leaves Pending state.

You can have a look at I-AKY5076AS6YH in the sandbox as an example. This has been stuck for 2+ hours.

I don't know what I can do about this since I can't let people try to sign up again if the state is still Pending. This is causing some serious issues for our support team.

Any known issues here?

**Comment by bluk** [comment]
Can you try contacting [PayPal Merchant Technical Support](https://www.paypal-techsupport.com) with the details you posted in this issue? That is the fastest way to get a response for your issue.

**Comment by omarkilani** [comment]
Sure, but since it's happening in the sandbox, I thought I'd post it here as well. :)

**Comment by bluk** [comment]
@omarkilani Thanks! Sorry for the brevity of my last response. Most of the people monitoring the SDK issues don't have access to account information (even sandbox), so we can't do lookups of other people's payment data. Merchant Technical Support should have access and be able to help you.

**Comment by ppmtscory** [comment]
@omarkilani there were some changes internally that were put through to clean up some inactive billing agreements that were causing the delay.  Can you test again and let us know if you're still seeing them stuck in a Pending state in the sandbox?

**Comment by omarkilani** [comment]
@ppmtscory I'll see if we hit this again. The merchant support people claimed the agreements were active even though the API kept returning Pending and I wasn't seeing the initial payment (setup fee).

Haven't had a report about it for a while so maybe it was fixed.

**Comment by ppmtscory** [comment]
Closing this as this particular sandbox issue should be resolved.
