### ISSUE TITLE
Getting ERROR: Got Http response code 503 when accessing https://api.sandbox.paypal.com/v1/payments/payment. Retried 0 times.{"name":"INTERNAL_SERVICE_ERROR","information_link":"https://api.sandbox.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"7a3b9f846f7f9"} 

### ISSUE THREAD

**Issue by malik-umair** [paypal/PayPal-PHP-SDK#566]
I'm using paypal rest-api-sdk-php and receiving this error and don't know about it's reason as it says it's internal server error. I've following code:
(Note: everything used below like credit card number cvv2 etc are not original and i got them from google as I'm in development mode. I'm using sandbox.
        $addr = new Address();
        $addr->setLine1('52 N Main ST');
        $addr->setCity('Johnstown');
        $addr->setCountryCode('US');
        $addr->setPostalCode('43210');
        $addr->setState('OH');

        $card = new CreditCard();
        $card->setNumber('4417119669820331');
        $card->setType('visa');
        $card->setExpireMonth('11');
        $card->setExpireYear('2018');
        $card->setCvv2('874');
        $card->setFirstName('Joe');
        $card->setLastName('Shopper');
        $card->setBillingAddress($addr);

        $fi = new FundingInstrument();
        $fi->setCreditCard($card);

        $payer = new Payer();
        $payer->setPaymentMethod('credit_card');
        $payer->setFundingInstruments(array($fi));

        $amount = new Amount();
        $amount->setCurrency('USD');
        $amount->setTotal('7.47');
        //$amount->setDetails($amountDetails);

        $transaction = new Transaction();
        $transaction->setAmount($amount);
        $transaction->setDescription('This is the payment transaction description.');

        $payment = new Payment();
        $payment->setIntent('sale');
        $payment->setPayer($payer);
        $payment->setTransactions(array($transaction));

        try {
            $payment->create($this->_api_context);
            echo "Payment Id is " . $payment->getId();
        } catch (\PayPal\Exception\PPConnectionException $ex) {
            if (\Config::get('app.debug')) {
                echo "Exception: " . $ex->getMessage() . PHP_EOL;
                $err_data = json_decode($ex->getData(), true);
                exit;
            } else {
                die('Some error occur, sorry for inconvenient');
            }
        }

**Comment by pp-randy** [comment]
The credit card number is overly used and causes an issue in sandbox.  Can you try a generated test card using step 4 from here? https://www.paypal-knowledge.com/infocenter/index?page=content&id=FAQ1413&expand=true&locale=en_US

**Comment by pp-randy** [comment]
Closing this issue as a new card number should resolve it.  Please let me know if that isn't the case. 

Internal Tracking: PPPLPAYPT-7022

**Comment by malik-umair** [comment]
yes it's fixed thanks!
