### ISSUE TITLE
How to set "custom"?

### ISSUE THREAD

**Issue by techpulse** [paypal/PayPal-PHP-SDK#568]
Hey.

From what I know, each time someone opens a dispute - or we refund the money - the "custom" query gets sent back to my server.

I want, to add "custom" when checking out. So i can generate a unique id, to assosicate the purchase with.

How can I do this?

This is my setup: http://i.imgur.com/3IPe100.png

How would I add custom, to it? Not sure what it's called, but a "custom" so i can assosicate the purchase, each time i refund or someone disputes with the web hook.

**Comment by pp-randy** [comment]
@techpulse  Are you trying to use this for PayPal funded Payments or another API / funding source? 

I am providing how to set these values for a PayPal payment; however, in my testing **I did not** get a Webhook for a buyer dispute, but I did get an IPN. 

You can set either invoice id or custom like this sample: 
https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/CreatePaymentUsingPayPal.php#L70

This is the method for setCustom: 
https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Api/CartBase.php#L153

**Comment by techpulse** [comment]
@pp-randy i used setCustom, however it didnt seem to work

invoice id seems to work

my mission is to track sales, so when i generate a license key - i can suspend the license once a dispute is open.

any ideas to how i could perform this?

**Comment by pp-randy** [comment]
Are you using Billing Agreements then and want to suspend it?  I only tested custom with a regular PayPal payment.  Did the SDK error out when setCustom was called or another issue occur?  

At this time I would point you more towards Instant Payment Notification until Webhooks are fully 1 to 1 match of functionality. https://developer.paypal.com/docs/classic/products/instant-payment-notification/

You can create a payment in sandbox, log into the buyer and dispute it, and this will generate an IPN. With a reason_code of buyer_complaint.

**Comment by techpulse** [comment]
Oh, i didn't know that I could even sign into the buyers account. Thanks for the information.

There is no billing agreement, it's one time purchase for a serial license. Then we of course have users wanting to dispute, to get the product for free - that way I want to suspend their license automatically instead of having them wasting my time searching up licenses manually :)

I've tested custom, and it does not return any error - as well as no custom sent back. I've tested it by waiting for users to dispute, which eh - takes some time.

But your way will speed it up, not sure what else I can do different?

http://i.imgur.com/5UJUIh6.png

**Comment by pp-randy** [comment]
Custom is showing up for me for both a PayPal and Credit Card payment.  The value of your variable $uniqid is not null correct?  What version of this SDK are you using?  

You should see custom returned in your response, but if invoice is working for you then you could use it instead.

**Comment by techpulse** [comment]
@pp-randy 
i am using latest, and i do not see invoice or custom in the webhook response on dispute created.. or refunds.

Btw, to test I do this..

I use my developer token instead, etc.
I sign into the account that bought the product (sandbox) then dispute.

However nothing returns to my webhook.

**Comment by techpulse** [comment]
http://pastebin.com/Fdp9LArN

here is my webhook code.

**Comment by techpulse** [comment]
I see data that it sent, and i confirm it's sending custom. Just need to get my webhook solved.

**Comment by pp-randy** [comment]
@techpulse to be clear you are not getting a webhook at all for the dispute?

In my testing I wasn't getting a webhook and following up internally.  This is when I suggested that you might want to look into Instant Payment Notification as a alternative for now. 

Internal tracking: PPBLRAC-9891

**Comment by nkavian** [comment]
The dispute and refund resource have a saleId, transactionId, or the paymentId.  You can fetch the Sale or Payment object using that ID and it should contain your custom and invoice number value.

**Comment by techpulse** [comment]
^ Yes. But what one, of those are used in all sales? So I can identify that sale, when refunding or disputing easily.

**Comment by pp-randy** [comment]
Hi @techpulse the dispute webhooks should be working in the sandbox now.

**Comment by ppmtscory** [comment]
Closing per @pp-randy confirmation.
