### ISSUE TITLE
Transaction State Pending ?

### ISSUE THREAD

**Issue by LD-Phillips** [paypal/PayPal-PHP-SDK#569]
Hello guys,

I'm trying to desperately include the RestAPI SDK 1.7 of PayPal in my online shop system. I have created a payment with intent “sale” and passing all required information. Everything works so far (I am redirected to the PayPal Login Page and see my shopping cart). After executing my “execute payment” script the transaction status is set to “pending”. I guess that’s what it should supposed to look like, even there’s an “completed” status in the documentation?! This is my response object of the execution script (Sandbox Mode):
```
{
    "id": "PAY-2RY714294E424933SK4UNGII",
    "intent": "sale",
    "state": "approved",
    "cart": "9RM32455718592154",
    "payer": {
    [.......]
    },
    "transactions": [
        {
            "amount": {
                "total": "86.95",
                "currency": "EUR",
                "details": {}
            },
            "payee": {
                "merchant_id": [xxxxxxx]
            },
            "description": [xxx],
            "item_list": {
                "items": [
                    {
                        "name": "Artikel 2.1.3 (Gelb, S)",
                        "price": "80.00",
                        "currency": "EUR",
                        "quantity": 1
                    },
                    {
                        "name": "Versandkosten",
                        "price": "6.95",
                        "currency": "EUR",
                        "quantity": 1
                    }
                ],
                "shipping_address": {
                 [.....]
                }
            },
            "related_resources": [
                {
                    "sale": {
                        "id": "02523480B6175490K",
                        "state": "pending",
                        "amount": {
                            "total": "86.95",
                            "currency": "EUR",
                            "details": {}
                        },
                        "payment_mode": "INSTANT_TRANSFER",
                        "reason_code": "RECEIVING_PREFERENCE_MANDATES_MANUAL_ACTION",
                        "protection_eligibility": "INELIGIBLE",
                        "parent_payment": "PAY-2RY714294E424933SK4UNGII",
                        "create_time": "2016-05-03T16:35:44Z",
                        "update_time": "2016-05-03T16:35:44Z",
                        "links": [
                            {
                                "href": "https://api.sandbox.paypal.com/v1/payments/sale/02523480B6175490K",
                                "rel": "self",
                                "method": "GET"
                            },
                            {
                                "href": "https://api.sandbox.paypal.com/v1/payments/sale/02523480B6175490K/refund",
                                "rel": "refund",
                                "method": "POST"
                            },
                            {
                                "href": "https://api.sandbox.paypal.com/v1/payments/payment/PAY-2RY714294E424933SK4UNGII",
                                "rel": "parent_payment",
                                "method": "GET"
                            }
                        ]
                    }
                }
            ]
        }
    ],
    "redirect_urls": {
        "return_url": "http://127.0.0.1/ld/source_code/paypal/EvalExpressCheckout.php?success=1&paymentId=PAY-2RY714294E424933SK4UNGII",
        "cancel_url": "http://127.0.0.1/ld/source_code/paypal/EvalExpressCheckout.php?success=0"
    },
    "create_time": "2016-05-03T16:35:46Z",
    "update_time": "2016-05-03T16:35:43Z",
    "links": [
        {
            "href": "https://api.sandbox.paypal.com/v1/payments/payment/PAY-2RY714294E424933SK4UNGII",
            "rel": "self",
            "method": "GET"
        }
    ]
}
```

When I’m going live and trying to process a test-order (with my private PayPal account) no transaction is being made. I don’t receive a confirmation order of my buyer’s account and there are no transactions listed in my business account. What am I doing wrong?
I have entered my Live CLIENT-ID and Secret and set the APIs configuration to “live”. My PayPal logs only show the following messages:
```
[03-05-2016 05:11:21] PayPal\Core\PayPalHttpConnection : INFO: GET https://api.paypal.com/v1/payments/payment/PAY-xxxxxxxxxx
[03-05-2016 05:11:22] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 200
```
I have followed all steps on the documentation and still can’t find my error. I have checked my “currency”-settings in my profile and set “Euro” to default.
Hope someone could help me and thank you for your time.
Best regards from Germany.

F. Phillips

**Comment by jaypatel512** [comment]
Are you executing the payment after the user is redirected to login and has accepted the payment ? 

As per your live logs, you should see another log about execute: 
```
[03-05-2016 05:11:21] PayPal\Core\PayPalHttpConnection : INFO: GET https://api.paypal.com/v1/payments/payment/PAY-xxxxxxxxxx
[03-05-2016 05:11:22] PayPal\Core\PayPalHttpConnection : INFO: Response Status  : 200
[03-05-2016 05:11:21] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payments/payment/PAY-xxxxxxxxxx/execute
[03-05-2016 05:11:22] PayPal\Core\PayPalHttpConnection : INFO: Response Status  : 200
```

**Comment by LD-Phillips** [comment]
Hello jaypatel512,

Thank you for your reply. Somehow the execute line does not appear in my log. Yes, I first create the payment (intent sale), then redirect the customer to the provided approval url. After confirming the cart, the customer is redirected correctly to my website. Then he has to confirm the order and the payment will be executed by my script (plus a confirmation email will be sent from my server). My source code of the execution process (my receivedPayment ID and PayerID are stored in sessions):

` $payment = Payment::get($_SESSION["paypal"]["paymentId"], $apiContext);
 $execution = new PaymentExecution();
 $execution->setPayerId($_SESSION["paypal"]["payerId"]); 
 try {
  $result = $payment->execute($execution, $apiContext);
  try { 
   $payment = Payment::get($_SESSION["paypal"]["paymentId"], $apiContext); 
  } catch(Exception $ex){ 
  $exit = true; }
 } 
 catch(Exception $ex){  $exit = true; }
`

The funniest thing I have just found out: In my buyers sandbox account every transaction is beeing listed as successfully charged. I can also see every live transaction in the "live transaction" page of the developers dashboard. Every transaction is marked with an green "http Status" check icon. Somehow the transactions are not listed in my business account and do not show up on my private buyers account!? 

Any suggestions? Thank you for your help.

Best regards


F. Phillips

**Comment by jaypatel512** [comment]
I would recommend you double check the execute part of the script. Make sure the apiContext object used when doing execute has the proper settings set to live, with live credentials, and logging enabled. You should be getting the logs similar to payment call. If for any reason it is not showing up, there is a good chance it is not getting executed properly. 

If none of this works, I think the issue may be not related to SDK, but to the API itself. We can sort that out once we have confirmed that the execute is getting successful.

**Comment by LD-Phillips** [comment]
After hours of work, trying to contact technical support and studying the API documentation, I have decided to use the NVP / SOAP API instead. 
I have followed all the steps provided by the documentation and now everything works perfectly (even in Live-Mode). It seems, that a lot of people are having trouble using the REST-API and there are a lot missing information in the log files and documentation (regarding to Stackoverflow and several other programmer boards).
Nevertheless, thank you jaypatel512 for your support. You were the only one helping out so far in this matter. I really appreciate your effort.

Best regards from Germany

**Comment by majid4466** [comment]
It's a pity the OP closed this issue without it being really resolved. I am having a similar issue. My execute call does go through, but the transaction stays pending. When I log in as the buyer I see it has been as "Pending". When I login as "unclaimed" and I have the option to "accept" it.

It kept puzzling me and I checked everything multiple times, until I noticed this token: `RECEIVING_PREFERENCE_MANDATES_MANUAL_ACTION`, now, isn't this interesting. Looking closely at the properties of the payment it does tell a lot. With some line reordering it says:

`
"payment_mode": "INSTANT_TRANSFER",
"state": "pending",
"reason_code": "RECEIVING_PREFERENCE_MANDATES_MANUAL_ACTION",
`

I read that as saying _although the payment was meant to be instant, it is pending because receiving preference mandates manual action_. I wonder where that preference is set and how should it be changed. Perhaps someone could provide a pointer?

**Comment by majid4466** [comment]
I did some more searching and found this Q&A where the same `RECEIVING_PREFERENCE_MANDATES_MANUAL_ACTION` token is mentioned. The reason given in the answer is this: 

> You cannot refund this payment, as it was sent in EUR, but the receiving account only has a balance in USD and therefore the payment is currently in an "unclaimed" status.

And I too, having mostly copy pasted sample code to piece together my script was having the same situation: the facilitator (sandbox seller) only had GBP balance and the cart had items with prices in USD. I changed the prices to GBP in the cart and the payment are now completed.

So, I would say the `reson_code` here could be more helpful as it is **not** a _receiving preference_ that mandates manual action, but a currency mismatch.

**Comment by xiaoleih41** [comment]
In the seller's account, there's a receiving preference they can change to decide if they are open to accept the currency they don't hold on their account. This error message is originated from that perspective.

**Comment by MOWebCreation** [comment]
Hello,

I'm working on the same problem since 1 month and I can't solve it !

https://github.com/paypal/PayPal-PHP-SDK/issues/1147

I've tried to use the REST API without the PHP SDK (I'm calling URL's with Curl), but I've the same problem !

I'm using the same currency of the default user currency and the manual approbation is well disabled for the user.

Is anybody have an another sugestion ?

Mickaël

**Comment by benaadams** [comment]
Seller/Merchant account needs to accept the currency or accept conversion to a preferred currency. You can set it up in your account https://stackoverflow.com/questions/43019376/paypal-pending-payments-with-express-checkout

Either hold the relevant currency (as you can have multiple currencies in your PayPal account) or choose " Allow payments sent to me in a currency I do not hold "
