### ISSUE TITLE
TLS-update PHP CURL ERROR:SSL connect error

### ISSUE THREAD

**Issue by LeeZa** [paypal/PayPal-PHP-SDK#571]
Test for 
https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1914&viewlocale=en_US

and see the link:
https://github.com/paypal/TLS-update#php

test on the server,show the info:

[root@server apache]# php -r '$ch = curl_init(); curl_setopt($ch, CURLOPT_URL, "https://tlstest.paypal.com/"); var_dump(curl_exec($ch)); var_dump(curl_error($ch));'
bool(false)
string(17) "SSL connect error"

and I see if I add **curl_setopt($ch, CURLOPT_SSLVERSION, 6); **
It will OK, and show:
[root@server apache]# php -r '$ch = curl_init(); curl_setopt($ch, CURLOPT_URL, "https://tlstest.paypal.com/"); curl_setopt($ch, CURLOPT_SSLVERSION, 6);var_dump(curl_exec($ch)); var_dump(curl_error($ch));'
PayPal_Connection_OKbool(true)
string(0) ""

As https://curl.haxx.se/docs/ssl-compared.html said. The curl and openssl version is enough for TLS v1.2 
Why is that? Anyone please help. Thank you!

PHP Version 5.3.29
System	Linux server 2.6.32-042stab111.12 #1 SMP Thu Sep 17 11:38:20 MSK 2015 i686

curl

cURL support	enabled
cURL Information	7.19.7
Age	3
Features
AsynchDNS	No
Debug	No
GSS-Negotiate	Yes
IDN	Yes
IPv6	Yes
Largefile	Yes
NTLM	Yes
SPNEGO	No
SSL	Yes
SSPI	No
krb4	No
libz	Yes
CharConv	No
Protocols	tftp, ftp, telnet, dict, ldap, ldaps, http, file, https, ftps, scp, sftp
Host	i386-redhat-linux-gnu
SSL Version	NSS/3.19.1 Basic ECC
ZLib Version	1.2.3
libSSH Version	libssh2/1.4.2

openssl

OpenSSL support	enabled
OpenSSL Library Version	OpenSSL 1.0.1e-fips 11 Feb 2013
OpenSSL Header Version	OpenSSL 1.0.1e-fips 11 Feb 2013

**Comment by LeeZa** [comment]
The phpinfo:
`
PHP Logo
PHP Version 5.3.29


System	Linux server 2.6.32-042stab111.12 #1 SMP Thu Sep 17 11:38:20 MSK 2015 i686
Build Date	Jan 22 2016 17:16:36
Configure Command	'./configure' '--prefix=/usr/local/php' '--with-config-file-path=/usr/local/php/etc' '--with-apxs2=/usr/local/apache/bin/apxs' '--with-mysql=mysqlnd' '--with-mysqli=mysqlnd' '--with-pdo-mysql=mysqlnd' '--with-iconv-dir' '--with-freetype-dir=/usr/local/freetype' '--with-jpeg-dir' '--with-png-dir' '--with-zlib' '--with-libxml-dir=/usr' '--enable-xml' '--disable-rpath' '--enable-magic-quotes' '--enable-safe-mode' '--enable-bcmath' '--enable-shmop' '--enable-sysvsem' '--enable-inline-optimization' '--with-curl' '--enable-mbregex' '--enable-mbstring' '--with-mcrypt' '--enable-ftp' '--with-gd' '--enable-gd-native-ttf' '--with-openssl' '--with-mhash' '--enable-pcntl' '--enable-sockets' '--with-xmlrpc' '--enable-zip' '--enable-soap' '--with-gettext' '--disable-fileinfo'
Server API	Apache 2.0 Handler
Virtual Directory Support	disabled
Configuration File (php.ini) Path	/usr/local/php/etc
Loaded Configuration File	/usr/local/php/etc/php.ini
Scan this dir for additional .ini files	(none)
Additional .ini files parsed	(none)
PHP API	20090626
PHP Extension	20090626
Zend Extension	220090626
Zend Extension Build	API220090626,NTS
PHP Extension Build	API20090626,NTS
Debug Build	no
Thread Safety	disabled
Zend Memory Manager	enabled
Zend Multibyte Support	disabled
IPv6 Support	enabled
Registered PHP Streams	https, ftps, compress.zlib, php, file, glob, data, http, ftp, phar, zip
Registered Stream Socket Transports	tcp, udp, unix, udg, ssl, sslv3, sslv2, tls
Registered Stream Filters	zlib.*, convert.iconv.*, mcrypt.*, mdecrypt.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk

Zend logo This program makes use of the Zend Scripting Language Engine:
Zend Engine v2.3.0, Copyright (c) 1998-2014 Zend Technologies
    with eAccelerator v0.9.6.1, Copyright (c) 2004-2010 eAccelerator, by eAccelerator
    with Zend Guard Loader v3.3, Copyright (c) 1998-2010, by Zend Technologies

PHP Credits

Configuration

apache2handler

Apache Version	Apache
Apache API Version	20051115
Server Administrator	lizipan99@qq.com
Hostname:Port	www.lnmp.org:0
User/Group	www(501)/501
Max Requests	Per Child: 0 - Keep Alive: off - Max Per Connection: 1000
Timeouts	Connection: 300 - Keep-Alive: 15
Virtual Server	Yes
Server Root	/usr/local/apache
Loaded Modules	core prefork http_core mod_so mod_authn_file mod_authn_dbm mod_authn_anon mod_authn_dbd mod_authn_default mod_authz_host mod_authz_groupfile mod_authz_user mod_authz_dbm mod_authz_owner mod_authz_default mod_auth_basic mod_auth_digest mod_dbd mod_dumpio mod_reqtimeout mod_ext_filter mod_include mod_filter mod_substitute mod_deflate mod_log_config mod_logio mod_env mod_mime_magic mod_expires mod_headers mod_ident mod_setenvif mod_version mod_proxy mod_proxy_connect mod_proxy_ftp mod_proxy_http mod_proxy_scgi mod_proxy_ajp mod_proxy_balancer mod_ssl mod_mime mod_dav mod_status mod_autoindex mod_asis mod_info mod_suexec mod_cgi mod_dav_fs mod_vhost_alias mod_negotiation mod_dir mod_imagemap mod_actions mod_speling mod_userdir mod_alias mod_rewrite mod_php5 mod_remoteip

Directive	Local Value	Master Value
engine	1	1
last_modified	0	0
xbithack	0	0

Apache Environment

Variable	Value
HTTP_HOST	84.200.230.171
HTTP_X_REAL_IP	120.36.190.230
HTTP_CONNECTION	close
HTTP_ACCEPT	text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
HTTP_UPGRADE_INSECURE_REQUESTS	1
HTTP_USER_AGENT	Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
HTTP_ACCEPT_LANGUAGE	zh-CN,zh;q=0.8,en;q=0.6,id;q=0.4
PATH	/sbin:/usr/sbin:/bin:/usr/bin
SERVER_SIGNATURE	<address>Apache Server at 84.200.230.171 Port 80</address>
SERVER_SOFTWARE	Apache
SERVER_NAME	84.200.230.171
SERVER_ADDR	127.0.0.1
SERVER_PORT	80
REMOTE_ADDR	120.36.190.230
DOCUMENT_ROOT	/home/wwwroot/default
SERVER_ADMIN	lizipan99@qq.com
SCRIPT_FILENAME	/home/wwwroot/default/phpinfo.php
REMOTE_PORT	35333
GATEWAY_INTERFACE	CGI/1.1
SERVER_PROTOCOL	HTTP/1.0
REQUEST_METHOD	GET
QUERY_STRING	no value
REQUEST_URI	/phpinfo.php
SCRIPT_NAME	/phpinfo.php

HTTP Headers Information

HTTP Request Headers
HTTP Request	GET /phpinfo.php HTTP/1.0
Host	84.200.230.171
X-Real-IP	120.36.190.230
Connection	close
Accept	text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Upgrade-Insecure-Requests	1
User-Agent	Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
Accept-Language	zh-CN,zh;q=0.8,en;q=0.6,id;q=0.4
HTTP Response Headers
X-Powered-By	PHP/5.3.29
Vary	Accept-Encoding
Connection	close
Content-Type	text/html

bcmath

BCMath support	enabled

Directive	Local Value	Master Value
bcmath.scale	0	0

Core

PHP Version	5.3.29

Directive	Local Value	Master Value
allow_call_time_pass_reference	Off	Off
allow_url_fopen	On	On
allow_url_include	Off	Off
always_populate_raw_post_data	Off	Off
arg_separator.input	&	&
arg_separator.output	&	&
asp_tags	Off	Off
auto_append_file	no value	no value
auto_globals_jit	On	On
auto_prepend_file	no value	no value
browscap	no value	no value
default_charset	no value	no value
default_mimetype	text/html	text/html
define_syslog_variables	Off	Off
disable_classes	no value	no value
disable_functions	passthru,exec,system,chroot,scandir,chgrp,chown,shell_exec,proc_open,proc_get_status,popen,ini_alter,ini_restore,dl,openlog,syslog,readlink,symlink,popepassthru,stream_socket_server	passthru,exec,system,chroot,scandir,chgrp,chown,shell_exec,proc_open,proc_get_status,popen,ini_alter,ini_restore,dl,openlog,syslog,readlink,symlink,popepassthru,stream_socket_server
display_errors	Off	Off
display_startup_errors	Off	Off
doc_root	no value	no value
docref_ext	no value	no value
docref_root	no value	no value
enable_dl	Off	Off
error_append_string	no value	no value
error_log	no value	no value
error_prepend_string	no value	no value
error_reporting	22527	22527
exit_on_timeout	Off	Off
expose_php	On	On
extension_dir	/usr/local/php/lib/php/extensions/no-debug-non-zts-20090626	/usr/local/php/lib/php/extensions/no-debug-non-zts-20090626
file_uploads	On	On
highlight.bg	#FFFFFF	#FFFFFF
highlight.comment	#FF8000	#FF8000
highlight.default	#0000BB	#0000BB
highlight.html	#000000	#000000
highlight.keyword	#007700	#007700
highlight.string	#DD0000	#DD0000
html_errors	Off	Off
ignore_repeated_errors	Off	Off
ignore_repeated_source	Off	Off
ignore_user_abort	Off	Off
implicit_flush	Off	Off
include_path	.:/usr/local/php/lib/php	.:/usr/local/php/lib/php
log_errors	On	On
log_errors_max_len	1024	1024
magic_quotes_gpc	Off	Off
magic_quotes_runtime	Off	Off
magic_quotes_sybase	Off	Off
mail.add_x_header	On	On
mail.force_extra_parameters	no value	no value
mail.log	no value	no value
max_execution_time	300	300
max_file_uploads	20	20
max_input_nesting_level	64	64
max_input_time	60	60
max_input_vars	1000	1000
memory_limit	128M	128M
open_basedir	no value	no value
output_buffering	4096	4096
output_handler	no value	no value
post_max_size	50M	50M
precision	14	14
realpath_cache_size	16K	16K
realpath_cache_ttl	120	120
register_argc_argv	Off	Off
register_globals	Off	Off
register_long_arrays	Off	Off
report_memleaks	On	On
report_zend_debug	On	On
request_order	GP	GP
safe_mode	Off	Off
safe_mode_exec_dir	no value	no value
safe_mode_gid	Off	Off
safe_mode_include_dir	no value	no value
sendmail_from	no value	no value
sendmail_path	/usr/sbin/sendmail -t -i 	/usr/sbin/sendmail -t -i 
serialize_precision	17	17
short_open_tag	On	On
SMTP	localhost	localhost
smtp_port	25	25
sql.safe_mode	Off	Off
track_errors	Off	Off
unserialize_callback_func	no value	no value
upload_max_filesize	50M	50M
upload_tmp_dir	no value	no value
user_dir	no value	no value
user_ini.cache_ttl	300	300
user_ini.filename	.user.ini	.user.ini
variables_order	GPCS	GPCS
xmlrpc_error_number	0	0
xmlrpc_errors	Off	Off
y2k_compliance	On	On
zend.enable_gc	On	On

ctype

ctype functions	enabled

curl

cURL support	enabled
cURL Information	7.19.7
Age	3
Features
AsynchDNS	No
Debug	No
GSS-Negotiate	Yes
IDN	Yes
IPv6	Yes
Largefile	Yes
NTLM	Yes
SPNEGO	No
SSL	Yes
SSPI	No
krb4	No
libz	Yes
CharConv	No
Protocols	tftp, ftp, telnet, dict, ldap, ldaps, http, file, https, ftps, scp, sftp
Host	i386-redhat-linux-gnu
SSL Version	NSS/3.19.1 Basic ECC
ZLib Version	1.2.3
libSSH Version	libssh2/1.4.2

date

date/time support	enabled
"Olson" Timezone Database Version	2013.3
Timezone Database	internal
Default timezone	CET

Directive	Local Value	Master Value
date.default_latitude	31.7667	31.7667
date.default_longitude	35.2333	35.2333
date.sunrise_zenith	90.583333	90.583333
date.sunset_zenith	90.583333	90.583333
date.timezone	CET	CET

dom

DOM/XML	enabled
DOM/XML API Version	20031129
libxml Version	2.7.6
HTML Support	enabled
XPath Support	enabled
XPointer Support	enabled
Schema Support	enabled
RelaxNG Support	enabled

eAccelerator

eAccelerator support	enabled
Version	0.9.6.1
Caching Enabled	true
Optimizer Enabled	true
Check mtime Enabled	true
Memory Size	33,554,392 Bytes
Memory Available	13,869,240 Bytes
Memory Allocated	19,685,152 Bytes
Cached Scripts	646
Removed Scripts	0

Directive	Local Value	Master Value
eaccelerator.allowed_admin_path	no value	no value
eaccelerator.cache_dir	/usr/local/eaccelerator_cache	/usr/local/eaccelerator_cache
eaccelerator.check_mtime	1	1
eaccelerator.debug	0	0
eaccelerator.enable	1	1
eaccelerator.filter	no value	no value
eaccelerator.log_file	no value	no value
eaccelerator.optimizer	1	1
eaccelerator.shm_max	0	0
eaccelerator.shm_only	0	0
eaccelerator.shm_prune_period	3600	3600
eaccelerator.shm_size	32	32
eaccelerator.shm_ttl	3600	3600

ereg

Regex Library	Bundled library enabled

filter

Input Validation and Filtering	enabled
Revision	$Id: 209a1c3c98c04a5474846e7bbe8ca72054ccfd4f $

Directive	Local Value	Master Value
filter.default	unsafe_raw	unsafe_raw
filter.default_flags	no value	no value

ftp

FTP support	enabled

gd

GD Support	enabled
GD Version	bundled (2.1.0 compatible)
FreeType Support	enabled
FreeType Linkage	with freetype
FreeType Version	2.4.12
GIF Read Support	enabled
GIF Create Support	enabled
JPEG Support	enabled
libJPEG Version	6b
PNG Support	enabled
libPNG Version	1.2.49
WBMP Support	enabled
XBM Support	enabled

Directive	Local Value	Master Value
gd.jpeg_ignore_warning	0	0

gettext

GetText Support	enabled

hash

hash support	enabled
Hashing Engines	md2 md4 md5 sha1 sha224 sha256 sha384 sha512 ripemd128 ripemd160 ripemd256 ripemd320 whirlpool tiger128,3 tiger160,3 tiger192,3 tiger128,4 tiger160,4 tiger192,4 snefru snefru256 gost adler32 crc32 crc32b salsa10 salsa20 haval128,3 haval160,3 haval192,3 haval224,3 haval256,3 haval128,4 haval160,4 haval192,4 haval224,4 haval256,4 haval128,5 haval160,5 haval192,5 haval224,5 haval256,5

iconv

iconv support	enabled
iconv implementation	glibc
iconv library version	2.12

Directive	Local Value	Master Value
iconv.input_encoding	ISO-8859-1	ISO-8859-1
iconv.internal_encoding	ISO-8859-1	ISO-8859-1
iconv.output_encoding	ISO-8859-1	ISO-8859-1

json

json support	enabled
json version	1.2.1

libxml

libXML support	active
libXML Compiled Version	2.7.6
libXML Loaded Version	20706
libXML streams	enabled

mbstring

Multibyte Support	enabled
Multibyte string engine	libmbfl
HTTP input encoding translation	disabled

mbstring extension makes use of "streamable kanji code filter and converter", which is distributed under the GNU Lesser General Public License version 2.1.

Multibyte (japanese) regex support	enabled
Multibyte regex (oniguruma) backtrack check	On
Multibyte regex (oniguruma) version	4.7.1

Directive	Local Value	Master Value
mbstring.detect_order	no value	no value
mbstring.encoding_translation	Off	Off
mbstring.func_overload	0	0
mbstring.http_input	pass	pass
mbstring.http_output	pass	pass
mbstring.http_output_conv_mimetypes	^(text/|application/xhtml\+xml)	^(text/|application/xhtml\+xml)
mbstring.internal_encoding	no value	no value
mbstring.language	neutral	neutral
mbstring.strict_detection	Off	Off
mbstring.substitute_character	no value	no value

mcrypt

mcrypt support	enabled
mcrypt_filter support	enabled
Version	2.5.8
Api No	20021217
Supported ciphers	cast-128 gost rijndael-128 twofish arcfour cast-256 loki97 rijndael-192 saferplus wake blowfish-compat des rijndael-256 serpent xtea blowfish enigma rc2 tripledes
Supported modes	cbc cfb ctr ecb ncfb nofb ofb stream

Directive	Local Value	Master Value
mcrypt.algorithms_dir	no value	no value
mcrypt.modes_dir	no value	no value

mhash

MHASH support	Enabled
MHASH API Version	Emulated Support

mysql

MySQL Support	enabled
Active Persistent Links	0
Active Links	0
Client API version	mysqlnd 5.0.8-dev - 20102224 - $Id: 731e5b87ba42146a687c29995d2dfd8b4e40b325 $

Directive	Local Value	Master Value
mysql.allow_local_infile	On	On
mysql.allow_persistent	On	On
mysql.connect_timeout	60	60
mysql.default_host	no value	no value
mysql.default_password	no value	no value
mysql.default_port	no value	no value
mysql.default_socket	no value	no value
mysql.default_user	no value	no value
mysql.max_links	Unlimited	Unlimited
mysql.max_persistent	Unlimited	Unlimited
mysql.trace_mode	Off	Off

mysqli

MysqlI Support	enabled
Client API library version	mysqlnd 5.0.8-dev - 20102224 - $Id: 731e5b87ba42146a687c29995d2dfd8b4e40b325 $
Active Persistent Links	0
Inactive Persistent Links	0
Active Links	0

Directive	Local Value	Master Value
mysqli.allow_local_infile	On	On
mysqli.allow_persistent	On	On
mysqli.default_host	no value	no value
mysqli.default_port	3306	3306
mysqli.default_pw	no value	no value
mysqli.default_socket	no value	no value
mysqli.default_user	no value	no value
mysqli.max_links	Unlimited	Unlimited
mysqli.max_persistent	Unlimited	Unlimited
mysqli.reconnect	Off	Off

mysqlnd

mysqlnd	enabled
Version	mysqlnd 5.0.8-dev - 20102224 - $Id: 731e5b87ba42146a687c29995d2dfd8b4e40b325 $
Compression	supported
SSL	supported
Command buffer size	4096
Read buffer size	32768
Read timeout	31536000
Collecting statistics	Yes
Collecting memory statistics	No
Tracing	n/a

Client statistics	
bytes_sent	53648284
bytes_received	1474471615
packets_sent	628258
packets_received	7008695
protocol_overhead_in	28034780
protocol_overhead_out	2513032
bytes_received_ok_packet	19877
bytes_received_eof_packet	2752785
bytes_received_rset_header_packet	1638839
bytes_received_rset_field_meta_packet	60694385
bytes_received_rset_row_packet	1407762276
bytes_received_prepare_response_packet	0
bytes_received_change_user_packet	0
packets_sent_command	313225
packets_received_ok	1807
packets_received_eof	305865
packets_received_rset_header	311418
packets_received_rset_field_meta	642635
packets_received_rset_row	5746066
packets_received_prepare_response	0
packets_received_change_user	0
result_set_queries	305865
non_result_set_queries	5553
no_index_used	11845
bad_index_used	0
slow_queries	0
buffered_sets	305865
unbuffered_sets	0
ps_buffered_sets	0
ps_unbuffered_sets	0
flushed_normal_sets	0
flushed_ps_sets	0
ps_prepared_never_executed	0
ps_prepared_once_executed	0
rows_fetched_from_server_normal	5440201
rows_fetched_from_server_ps	0
rows_buffered_from_client_normal	5440201
rows_buffered_from_client_ps	0
rows_fetched_from_client_normal_buffered	4145892
rows_fetched_from_client_normal_unbuffered	0
rows_fetched_from_client_ps_buffered	0
rows_fetched_from_client_ps_unbuffered	0
rows_fetched_from_client_ps_cursor	0
rows_affected_normal	1346
rows_affected_ps	0
rows_skipped_normal	5440201
rows_skipped_ps	0
copy_on_write_saved	10340915
copy_on_write_performed	1993484
command_buffer_too_small	93
connect_success	904
connect_failure	0
connection_reused	0
reconnect	0
pconnect_success	2
active_connections	0
active_persistent_connections	0
explicit_close	904
implicit_close	0
disconnect_close	0
in_middle_of_command_close	0
explicit_free_result	305865
implicit_free_result	0
explicit_stmt_close	0
implicit_stmt_close	0
mem_emalloc_count	0
mem_emalloc_amount	0
mem_ecalloc_count	0
mem_ecalloc_amount	0
mem_erealloc_count	0
mem_erealloc_amount	0
mem_efree_count	0
mem_efree_amount	0
mem_malloc_count	0
mem_malloc_amount	0
mem_calloc_count	0
mem_calloc_amount	0
mem_realloc_count	0
mem_realloc_amount	0
mem_free_count	0
mem_free_amount	0
mem_estrndup_count	0
mem_strndup_count	0
mem_estndup_count	0
mem_strdup_count	0
proto_text_fetched_null	0
proto_text_fetched_bit	0
proto_text_fetched_tinyint	96299
proto_text_fetched_short	2490
proto_text_fetched_int24	0
proto_text_fetched_int	4644210
proto_text_fetched_bigint	57126
proto_text_fetched_decimal	1964564
proto_text_fetched_float	28777
proto_text_fetched_double	3104
proto_text_fetched_date	975
proto_text_fetched_year	0
proto_text_fetched_time	0
proto_text_fetched_datetime	11597
proto_text_fetched_timestamp	0
proto_text_fetched_string	4766730
proto_text_fetched_blob	748985
proto_text_fetched_enum	0
proto_text_fetched_set	0
proto_text_fetched_geometry	0
proto_text_fetched_other	0
proto_binary_fetched_null	0
proto_binary_fetched_bit	0
proto_binary_fetched_tinyint	0
proto_binary_fetched_short	0
proto_binary_fetched_int24	0
proto_binary_fetched_int	0
proto_binary_fetched_bigint	0
proto_binary_fetched_decimal	0
proto_binary_fetched_float	0
proto_binary_fetched_double	0
proto_binary_fetched_date	0
proto_binary_fetched_year	0
proto_binary_fetched_time	0
proto_binary_fetched_datetime	0
proto_binary_fetched_timestamp	0
proto_binary_fetched_string	0
proto_binary_fetched_blob	0
proto_binary_fetched_enum	0
proto_binary_fetched_set	0
proto_binary_fetched_geometry	0
proto_binary_fetched_other	0
init_command_executed_count	0
init_command_failed_count	0
com_quit	904
com_init_db	903
com_query	311418
com_field_list	0
com_create_db	0
com_drop_db	0
com_refresh	0
com_shutdown	0
com_statistics	0
com_process_info	0
com_connect	0
com_process_kill	0
com_debug	0
com_ping	0
com_time	0
com_delayed_insert	0
com_change_user	0
com_binlog_dump	0
com_table_dump	0
com_connect_out	0
com_register_slave	0
com_stmt_prepare	0
com_stmt_execute	0
com_stmt_send_long_data	0
com_stmt_close	0
com_stmt_reset	0
com_stmt_set_option	0
com_stmt_fetch	0
com_deamon	0
bytes_received_real_data_normal	1264909434
bytes_received_real_data_ps	0

openssl

OpenSSL support	enabled
OpenSSL Library Version	OpenSSL 1.0.1e-fips 11 Feb 2013
OpenSSL Header Version	OpenSSL 1.0.1e-fips 11 Feb 2013

pcre

PCRE (Perl Compatible Regular Expressions) Support	enabled
PCRE Library Version	8.32 2012-11-30

Directive	Local Value	Master Value
pcre.backtrack_limit	1000000	1000000
pcre.recursion_limit	100000	100000

PDO

PDO support	enabled
PDO drivers	mysql, sqlite, sqlite2

pdo_mysql

PDO Driver for MySQL	enabled
Client API version	mysqlnd 5.0.8-dev - 20102224 - $Id: 731e5b87ba42146a687c29995d2dfd8b4e40b325 $

Directive	Local Value	Master Value
pdo_mysql.default_socket	/tmp/mysql.sock	/tmp/mysql.sock

pdo_sqlite

PDO Driver for SQLite 3.x	enabled
SQLite Library	3.7.7.1

Phar

Phar: PHP Archive support	enabled
Phar EXT version	2.0.1
Phar API version	1.1.1
SVN revision	$Id: 21d763042eb5769ae0a09dc1118df2b5aae6fb33 $
Phar-based phar archives	enabled
Tar-based phar archives	enabled
ZIP-based phar archives	enabled
gzip compression	enabled
bzip2 compression	disabled (install pecl/bz2)
Native OpenSSL support	enabled

Phar based on pear/PHP_Archive, original concept by Davey Shafik.
Phar fully realized by Gregory Beaver and Marcus Boerger.
Portions of tar implementation Copyright (c) 2003-2009 Tim Kientzle.

Directive	Local Value	Master Value
phar.cache_list	no value	no value
phar.readonly	On	On
phar.require_hash	On	On

posix

Revision	$Id: 5a2da3946b96c5afbf3aff8db8a8681f8bedee85 $

Reflection

Reflection	enabled
Version	$Id: 4af6c4c676864b1c0bfa693845af0688645c37cf $

session

Session Support	enabled
Registered save handlers	files user sqlite
Registered serializer handlers	php php_binary

Directive	Local Value	Master Value
session.auto_start	Off	Off
session.bug_compat_42	Off	Off
session.bug_compat_warn	Off	Off
session.cache_expire	180	180
session.cache_limiter	nocache	nocache
session.cookie_domain	no value	no value
session.cookie_httponly	Off	Off
session.cookie_lifetime	0	0
session.cookie_path	/	/
session.cookie_secure	Off	Off
session.entropy_file	no value	no value
session.entropy_length	0	0
session.gc_divisor	1000	1000
session.gc_maxlifetime	1440	1440
session.gc_probability	1	1
session.hash_bits_per_character	5	5
session.hash_function	0	0
session.name	PHPSESSID	PHPSESSID
session.referer_check	no value	no value
session.save_handler	files	files
session.save_path	no value	no value
session.serialize_handler	php	php
session.use_cookies	On	On
session.use_only_cookies	On	On
session.use_trans_sid	0	0

shmop

shmop support	enabled

SimpleXML

Simplexml support	enabled
Revision	$Id: 02ab7893b36d51e9c59da77d7e287eb3b35e1e32 $
Schema support	enabled

soap

Soap Client	enabled
Soap Server	enabled

Directive	Local Value	Master Value
soap.wsdl_cache	1	1
soap.wsdl_cache_dir	/tmp	/tmp
soap.wsdl_cache_enabled	1	1
soap.wsdl_cache_limit	5	5
soap.wsdl_cache_ttl	86400	86400

sockets

Sockets Support	enabled

SPL

SPL support	enabled
Interfaces	Countable, OuterIterator, RecursiveIterator, SeekableIterator, SplObserver, SplSubject
Classes	AppendIterator, ArrayIterator, ArrayObject, BadFunctionCallException, BadMethodCallException, CachingIterator, DirectoryIterator, DomainException, EmptyIterator, FilesystemIterator, FilterIterator, GlobIterator, InfiniteIterator, InvalidArgumentException, IteratorIterator, LengthException, LimitIterator, LogicException, MultipleIterator, NoRewindIterator, OutOfBoundsException, OutOfRangeException, OverflowException, ParentIterator, RangeException, RecursiveArrayIterator, RecursiveCachingIterator, RecursiveDirectoryIterator, RecursiveFilterIterator, RecursiveIteratorIterator, RecursiveRegexIterator, RecursiveTreeIterator, RegexIterator, RuntimeException, SplDoublyLinkedList, SplFileInfo, SplFileObject, SplFixedArray, SplHeap, SplMinHeap, SplMaxHeap, SplObjectStorage, SplPriorityQueue, SplQueue, SplStack, SplTempFileObject, UnderflowException, UnexpectedValueException

SQLite

SQLite support	enabled
PECL Module version	2.0-dev $Id$
SQLite Library	2.8.17
SQLite Encoding	iso8859

Directive	Local Value	Master Value
sqlite.assoc_case	0	0

sqlite3

SQLite3 support	enabled
SQLite3 module version	0.7-dev
SQLite Library	3.7.7.1

Directive	Local Value	Master Value
sqlite3.extension_dir	no value	no value

standard

Dynamic Library Support	enabled
Path to sendmail	/usr/sbin/sendmail -t -i

Directive	Local Value	Master Value
assert.active	1	1
assert.bail	0	0
assert.callback	no value	no value
assert.quiet_eval	0	0
assert.warning	1	1
auto_detect_line_endings	0	0
default_socket_timeout	60	60
from	no value	no value
safe_mode_allowed_env_vars	PHP_	PHP_
safe_mode_protected_env_vars	LD_LIBRARY_PATH	LD_LIBRARY_PATH
url_rewriter.tags	a=href,area=href,frame=src,input=src,form=fakeentry	a=href,area=href,frame=src,input=src,form=fakeentry
user_agent	no value	no value

tokenizer

Tokenizer Support	enabled

xml

XML Support	active
XML Namespace Support	active
libxml2 Version	2.7.6

xmlreader

XMLReader	enabled

xmlrpc

core library version	xmlrpc-epi v. 0.51
php extension version	0.51
author	Dan Libby
homepage	http://xmlrpc-epi.sourceforge.net
open sourced by	Epinions.com

xmlwriter

XMLWriter	enabled

Zend Guard Loader

Zend Guard Loader	enabled
License Path	no value
Obfuscation level	3

zip

Zip	enabled
Extension Version	$Id: b1a1a3628c4ed0ad78fb0cc4a99b06a56aa281c4 $
Zip version	1.11.0
Libzip version	0.10.1

zlib

ZLib Support	enabled
Stream Wrapper support	compress.zlib://
Stream Filter support	zlib.inflate, zlib.deflate
Compiled Version	1.2.3
Linked Version	1.2.3

Directive	Local Value	Master Value
zlib.output_compression	Off	Off
zlib.output_compression_level	-1	-1
zlib.output_handler	no value	no value

Additional Modules

Module Name
sysvsem

Environment

Variable	Value
TERM	xterm
LD_LIBRARY_PATH	/usr/local/apache/lib
PATH	/sbin:/usr/sbin:/bin:/usr/bin
PWD	/
SHLVL	1
_	/usr/local/apache/bin/httpd

PHP Variables

Variable	Value
_SERVER["HTTP_HOST"]	84.200.230.171
_SERVER["HTTP_X_REAL_IP"]	120.36.190.230
_SERVER["HTTP_CONNECTION"]	close
_SERVER["HTTP_ACCEPT"]	text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
_SERVER["HTTP_UPGRADE_INSECURE_REQUESTS"]	1
_SERVER["HTTP_USER_AGENT"]	Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
_SERVER["HTTP_ACCEPT_LANGUAGE"]	zh-CN,zh;q=0.8,en;q=0.6,id;q=0.4
_SERVER["PATH"]	/sbin:/usr/sbin:/bin:/usr/bin
_SERVER["SERVER_SIGNATURE"]	<address>Apache Server at 84.200.230.171 Port 80</address>
_SERVER["SERVER_SOFTWARE"]	Apache
_SERVER["SERVER_NAME"]	84.200.230.171
_SERVER["SERVER_ADDR"]	127.0.0.1
_SERVER["SERVER_PORT"]	80
_SERVER["REMOTE_ADDR"]	120.36.190.230
_SERVER["DOCUMENT_ROOT"]	/home/wwwroot/default
_SERVER["SERVER_ADMIN"]	lizipan99@qq.com
_SERVER["SCRIPT_FILENAME"]	/home/wwwroot/default/phpinfo.php
_SERVER["REMOTE_PORT"]	35333
_SERVER["GATEWAY_INTERFACE"]	CGI/1.1
_SERVER["SERVER_PROTOCOL"]	HTTP/1.0
_SERVER["REQUEST_METHOD"]	GET
_SERVER["QUERY_STRING"]	no value
_SERVER["REQUEST_URI"]	/phpinfo.php
_SERVER["SCRIPT_NAME"]	/phpinfo.php
_SERVER["PHP_SELF"]	/phpinfo.php
_SERVER["REQUEST_TIME"]	1462520473

PHP License

This program is free software; you can redistribute it and/or modify it under the terms of the PHP License as published by the PHP Group and included in the distribution in the file: LICENSE

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

If you did not receive a copy of the PHP license, or have any questions about PHP licensing, please contact license@php.net.

`

**Comment by jaypatel512** [comment]
Related thread: https://github.com/paypal/PayPal-PHP-SDK/issues/596.
