### ISSUE TITLE
Sandbox Billing Agreements not generating scheduled transactions 

### ISSUE THREAD

**Issue by malik-umair** [paypal/PayPal-PHP-SDK#572]
How can I implement refund functionality in Paypal php SDK? I\ve implemented paypal direct payments with credit cards and recurring payment with credit card and I'm storing transaction ID after payments are made successfully and I need add a functionality to refund that some/complete amount back.

**Comment by pp-randy** [comment]
You can refund a sale or a capture the general documentation is here: https://developer.paypal.com/docs/integration/direct/refund-payment/

This link should be helpful regarding the amount values, for a full refund leave amount blank. 
https://developer.paypal.com/docs/rest/api/payments/#sale.refund


A sample can be found here for a sale: https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/sale/RefundSale.php

For recurring payment refund, currently the functionality to be added is being tracked here: 
https://github.com/paypal/PayPal-Python-SDK/issues/115

**Comment by malik-umair** [comment]
Thanks @pp-randy  for your response, I'll look through these links and find out if they help me, but before going to refund I'm facing another problem in recurring method. I've setup a recurring method with initial payment, It's taking initial payment from me but the remaining amount never executed which I set in recurring method. My code is below:

    $amount = new Currency();
        $amount->setCurrency('USD')
                ->setValue($dataPaypal['secondTransactionAmount']);

        $definition = new PaymentDefinition();
        $definition->setName("Regular Payments")
                ->setType("REGULAR")
                ->setFrequencyInterval($dataPaypal['paypalBillingFrequency'])
                ->setFrequency($dataPaypal['paypalBillingPeriod'])
                ->setCycles($dataPaypal['paypalBillingCycle'])
                ->setAmount($amount);

        $preferences = new MerchantPreferences();
        $preferences->setCancelUrl(URL::route('payment.status'))
                ->setReturnUrl(URL::route('payment.status'))
                ->setInitialFailAmountAction('CANCEL')
                ->setMaxFailAttempts(5)
                ->setAutoBillAmount('YES')
                ->setSetupFee(array('value' => $dataPaypal['transactionAmount'], 'currency' => 'USD'));

        $plan = new Plan();
        $plan->setName('5 star Resorts')
                ->setDescription('Testing payment by creating plans')
                ->setType('FIXED')
                ->setPaymentDefinitions(array($definition))
                ->setMerchantPreferences($preferences);
        $createdPlan = $plan->create($this->_api_context);

        $patch = new Patch();

        $value = new PayPalModel('{
	       "state":"ACTIVE"
	     }');

        $patch->setOp('replace')
                ->setPath('/')
                ->setValue($value);
        $patchRequest = new PatchRequest();
        $patchRequest->addPatch($patch);

        $createdPlan->update($patchRequest, $this->_api_context);

        $plan = Plan::get($createdPlan->getId(), $this->_api_context);

        $agreement = new Agreement();
        $currentTime = time() + 500;
        $createdDate = date("Y-m-d") . ' ' . date("H:i:s", $currentTime);
        $datetime = new DateTime($createdDate);
        $startDate = $datetime->format(DateTime::ISO8601);

        $agreement->setName('5 Star Resorts')
                ->setDescription('Resort Booking')
                ->setStartDate($startDate);

        //Add Plan ID Please note that the plan Id should be only set in this case.
        $plan = new Plan();
        $plan->setId($createdPlan->getId());
        $agreement->setPlan($plan);
        //Add Payer
        $payer = new Payer();
        $payer->setPaymentMethod('credit_card')
                ->setPayerInfo(new PayerInfo(array('email' => $dataPaypal['ppEmail'])));
        //Add Credit Card to Funding Instruments
        $creditCard = new CreditCard();
        $creditCard->setType($dataPaypal['ccType'])
                ->setNumber($dataPaypal['ccNumber'])
                ->setExpireMonth($dataPaypal['ccExpMonth'])
                ->setExpireYear($dataPaypal['ccExpYear'])
                ->setCvv2($dataPaypal['ccCode'])
                ->setFirstName($dataPaypal['firstName'])
                ->setLastName($dataPaypal['lastName']);

        $fundingInstrument = new FundingInstrument();
        $fundingInstrument->setCreditCard($creditCard);
        $payer->setFundingInstruments(array($fundingInstrument));
        //Add Payer to Agreement
        $agreement->setPayer($payer);
        //Add Shipping Address
        $shippingAddress = new ShippingAddress();
        $shippingAddress->setLine1($dataPaypal['addressLineOne'])
                ->setCity($dataPaypal['city'])
                ->setState($dataPaypal['state_'])
                ->setPostalCode($dataPaypal['postalCode'])
                ->setCountryCode('US');
        $agreement->setShippingAddress($shippingAddress);
        $request = clone $agreement;
        //Create Agreement
        try {
            $agreement = $agreement->create($this->_api_context);
            if ($agreement->getId() != '') {
                $dataPayment = array(
                    'paymentMethodId' => $paymentMethodId,
                    'paypalProfileId' => $agreement->getId()
                );
                $id = Payments::UpdatePaymentRecurringPaypal($dataPayment);
                $id = PaymentMethod::UpdatePaymentMethodRecurringPaypal($dataPayment);
                return true;
            }
        } catch (Exception $ex) {
            echo 'error' . $agreement->getId();
            exit(1);
        }


can you please guide me how can I achieve following goals:
1- On form submit, take initial payment immediately from user credit card.(I'm taking this amount by setSetupFee() method)
2- Take remaining amount at mentioned date.(I've been working on it from many days but I didn't received any remaining payment from the user profile, when I checked it in my sandbox account it's putting all remaining payments in OUT STANDING amount, I don't know why is that happening)

Please help me to fix this as I've spent a lot of days on implementing it but it's working as required. Thanks!

**Comment by pp-randy** [comment]
An outstanding happens when the buyer account was unable to pay.  Maybe this is a blessing in disguise, this could happen in Live at times.  

If you provide the email address of the buyer account in sandbox and the Billing Agreement ID, I should be able to look further into this.  My immediate suggestion is to also test against a new buyer account.  

You don't have to provide your sandbox information in this public Github issue either, you can file a ticket with Merchant Technical Support here, and they could also take a look: https://www.paypal-techsupport.com/app/ask/

**Comment by malik-umair** [comment]
Following are some Billing Agreement Ids in which initial payment is successfully paid but recurring payment is not occurring.

1. I-014XVMATJVYG
2. 	I-X2K1PUY1761K
3. I-M1JWCAEL59FU
4. I-SLJ41L9L44AT

I've used two different testing sandbox accounts for this:

1. um31716-facilitator@gmail.com
2- 	jawad.saleem@purelogics.net

Thanks for your suggestion to file ticket on Technical Support, I'll take care of it in future.

**Comment by malik-umair** [comment]
Hi, Did you found any thing regarding this??

**Comment by pp-randy** [comment]
I reviewed yesterday and these to me looked like they should have billed.  This should not be a problem on live. 

For internal tracking: SDS-1101

**Comment by malik-umair** [comment]
But how can I assure that it'll not happen on live? as I can't go on live without confirmation that it'll not occur there otherwise it can create a lot of mess... can you guide me what to do as I'm very new in using Paypal and it's my first attempt to integrate it... Thanks!

**Comment by pp-randy** [comment]
I understand and apologize for the inconvenience. There is an issue in sandbox causing the payments not to be made, and I will update you when it is resolved. It appears sandbox wide as it also impacts my profiles.  I apologize again because I do not have an ETA, but will update you when I see progress on our end.

**Comment by malik-umair** [comment]
that's ok... I'll be waiting for your response... Thanks for guiding.

**Comment by pp-randy** [comment]
I am editing this issue subject to track the billing agreement payments not working in sandbox.

For tracking of refunding billing agreements we will use: https://github.com/paypal/PayPal-Python-SDK/issues/115

**Comment by malik-umair** [comment]
ok, any update regarding this fix yet?

**Comment by pp-randy** [comment]
Hi @malik-umair we are still working to resolve this issue and I apologize for the delay.

New Internal Tracking: PPPLMER-12667, SDS-1101

**Comment by pp-randy** [comment]
@malik-umair some of the delays could be related to the credit card number being used for your profiles; especially, if it is a common testing card number. Can you try with a new card numbers?  You can generate them on Step 4 of this FAQ https://www.paypal-knowledge.com/infocenter/index?page=content&id=FAQ1413&expand=true&locale=en_US

**Comment by pp-randy** [comment]
Closing this out as it should be resolved, as using newly credit cards as suggested above will help.
