### ISSUE TITLE
Getting ERROR: Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/billing-agreements/. {"name":"VALIDATION_ERROR","details":[{"field":"agreement_details","issue":"Not valid to specify this field in a request"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#VALIDATION_ERROR","debug_id":"1a227f6b3b24"}

### ISSUE THREAD

**Issue by malik-umair** [paypal/PayPal-PHP-SDK#573]
I'm getting above mentioned error while setting Agreement Details object in Agreement. I want to set next payment date on which recurring should occur but it's giving error. If I remove to add Detail's object in agreement then it work but then initial payment is made successfully but recurring payment was never made.

    $agreementDetail = new AgreementDetails();
        $toDate = date("Y-m-d");
        $currentTime = time();
        $createdDate = date("Y-m-d", strtotime($toDate . ' +1 day')) . ' ' . date("H:i:s", $currentTime);
        $datetime = new DateTime($createdDate);
        $startDate = $datetime->format(DateTime::ISO8601);
        $startDate = explode('+', $startDate);
        $next_billing_date = $startDate[0] . 'Z';
        $agreementDetail->setNextBillingDate($next_billing_date);

    $agreement = new Agreement();
    $agreement->setAgreementDetails($agreementDetail);

I've a lot of other issues as well and has created many other tickets but no one is responding on them from many days!

**Comment by jaypatel512** [comment]
As mentioned, you are not supposed to fill the agreement details yourself. This is something that gets returned back from the server. 

Please refer to [developer docs](https://developer.paypal.com/webapps/developer/docs/api/#create-an-agreement) for more details.

**Comment by malik-umair** [comment]
But if I do not set it then how will my next payment occur? I'm facing a problem in recurring payments in which initial payment is made successfully but remaining amount never executed. That's why I thought that it might be due to I'm not setting next payment date. If I don't have to set it then why recurring is not working. I'm on sandbox mode. Please help me to fix it as I've spend a lot of time in searching it's solution but nothing is working due to lack of sample code and examples. :(

**Comment by malik-umair** [comment]
You can check my issue from here and guide me if you have any idea of this issue. #572 

Thanks!
