### ISSUE TITLE
Guest checkout not working in php sdk

### ISSUE THREAD

**Issue by faraz110** [paypal/PayPal-PHP-SDK#574]
I've been working on php sdk, and all seems to be working for both sandbox and live, the only issue is that, when we are live, guest checkout with credit card is not work tough it is working ok with sandbox, Paypal Account Optional is enabled and country is UK, and account it Business, please help me

**Comment by pp-randy** [comment]
@faraz110 this doesn't appear to be an SDK issue if sandbox was working as you intended.  Please reach out to PayPal Technical Support for assistance here: https://www.paypal-techsupport.com/app/ask/

**Comment by faraz110** [comment]
thanks bro i'll do :)
