### ISSUE TITLE
Empty array in CURLOPT_HTTPHEADERS could cause Segfaults

### ISSUE THREAD

**Issue by shockgonewild** [paypal/PayPal-PHP-SDK#575]
A possible bug in PHP could crash the application while executing curl_setopt_array().
This is not directly a bug in the PayPal-PHP-SDK package itself, but it makes the SDK useless
in my production environment.

In **\PayPal\Core\PayPalHttpConfig**  the $defaultCurlOptions  include:

` CURLOPT_HTTPHEADER => array(),`

Which could cause Segfaults:
See: [https://bugs.php.net/bug.php?id=72042&edit=3](url)
AND: [https://bugs.php.net/bug.php?id=71703](url)

I experienced this issue on Plesk 12.5.30 with PHP Version 7.05 and Debian 7.10 

Simple workaround could be to replace :

`$ch = curl_init($this->httpConfig->getUrl());`

With: 

```
        $options = $this->httpConfig->getCurlOptions();
        if(empty($options[CURLOPT_HTTPHEADER])) {
            unset ($options[CURLOPT_HTTPHEADER]);
        }
        curl_setopt_array($ch, $options);
``` 

in **\PayPal\Core\PayPalHttpConnection**   function execute.

**Comment by jaypatel512** [comment]
Thanks @shockgonewild for detailed bug.
