### ISSUE TITLE
Get each transaction associated with a Recurring Payment Profile

### ISSUE THREAD

**Issue by sarathvsgit** [paypal/PayPal-PHP-SDK#576]
Hi ,
     How can get each transaction detail associated with reccuring payment profile. I want to log all the 
 details of  each transaction in recurring payment of each profile . Is it possible to get the details of each transaction and status  (success,failed,transaction Id)  ?

**Comment by pp-randy** [comment]
@sarathvsgit this sample and documentation should help.  Transaction id and status are provided.

https://developer.paypal.com/docs/rest/api/payments.billing-agreements/#agreement.transactions
http://paypal.github.io/PayPal-PHP-SDK/sample/doc/billing/SearchBillingTransactions.html
https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/billing/SearchBillingTransactions.php
