### ISSUE TITLE
Warning: Ambiguous class resolution, "PayPal\Auth\OAuthTokenCredential" was found in both 

### ISSUE THREAD

**Issue by googlle** [paypal/PayPal-PHP-SDK#578]
Warning: Ambiguous class resolution, "PayPal\Auth\OAuthTokenCredential" was found in both "../vendor/paypal/rest-api-sdk-php/lib/PayPal/Auth/OAuthTokenCredential.php" and "../vendor/paypal/sdk-core-php/lib/PayPal/Auth/OAuthTokenCredential.php", the first will be used.

I use in composer.json
```php
"paypal/adaptivepayments-sdk-php": "*",
"paypal/rest-api-sdk-php": "*"
```

**Comment by jaypatel512** [comment]
I think the dependency comes from [sdk-core-php](https://github.com/paypal/sdk-core-php) package. I think we no longer need that package to have the OAuthTokenCredential. I will go ahead and remove that from the package. 

That should fix the issue. Moving this issue to [sdk-core-php](https://github.com/paypal/sdk-core-php)

**Comment by googlle** [comment]
Thanks
