### ISSUE TITLE
error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure

### ISSUE THREAD

**Issue by antonioreyna** [paypal/PayPal-PHP-SDK#582]
### Required Information

- PHP Version: PHP 5.6.19-1~dotdeb+7.1
- PayPal-PHP-SDK Version: v1.2.1
- Debug ID(s):

### Issue Description

I am getting this message when trying to connect using my sandbox credentials.

error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure

**Comment by antonioreyna** [comment]
Now I am getting this:

error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure

**Comment by jaypatel512** [comment]
Have you reviewed the PHP section here? 
https://github.com/paypal/tls-update#php

**Comment by antonioreyna** [comment]
yes, I get this:

$ php -r '$ch = curl_init(); curl_setopt($ch, CURLOPT_URL, "https://tlstest.paypal.com/"); var_dump(curl_exec($ch));'
PayPal_Connection_OKbool(true)

**Comment by jaypatel512** [comment]
Oh ! I realized you are using v1.2.1 of PHP SDK. Can you please update to latest, as we made some SSL POODLE fixes that disabled communicating over SSLv3. Please update to [latest release](https://github.com/paypal/PayPal-PHP-SDK/releases) and see if that resolves that issue.

Please re-open if that does not fix that.
