### ISSUE TITLE
Internal Service Error in Sandbox since days (debug ID 40d0e22ee2478)

### ISSUE THREAD

**Issue by jamecs** [paypal/PayPal-PHP-SDK#583]
Since days I'm trying to use the PayPal Sandbox with my shopsystem. 

Processing ends with "http 1.1 500 Internal Service Error"

Sandbox is configured properly. Doesn't matter if I use Creditcard or Paypal money. Always internal service error.

2016-06-02 16:46:32 USER NOTICE: "API response:
HTTP/1.1 500 Internal Server Error
Date: Thu, 02 Jun 2016 14:46:33 GMT
Server: Apache
PROXY_SERVER_INFO: host=slcsbplatformapiserv3001.slc.paypal.com;threadId=343
Paypal-Debug-Id: 40d0e22ee2478
CORRELATION-ID: 40d0e22ee2478
Content-Language: en_us
Connection: close
Connection: close
Paypal-Debug-Id: 40d0e22ee2478
Set-Cookie: X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Dplatformapiserv%26TIME%3D3376828503%26HTTP_X_PP_AZ_LOCATOR%3D; Expires=Thu, 02 Jun 2016 15:16:34 GMT; domain=.paypal.com; path=/; Secure; HttpOnly
Set-Cookie: X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT
Vary: Authorization
Content-Length: 194
Content-Type: application/json

{"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"40d0e22ee2478"}
"

I don't want to test it on a live system because of the sandbox errors.

**Comment by pp-randy** [comment]
The API call appears to be a patch request for a payment. Are you able to provide the full API request so I can see what you are sending in for the patch?

**Comment by jamecs** [comment]
here you go :)

---snip---
2016-06-02 16:45:34 USER NOTICE: "API request:
POST https://api.sandbox.paypal.com/v1/oauth2/token
Accept: application/json
Accept-Language: en_US
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
"


================================================================================

2016-06-02 16:45:34 USER NOTICE: "API response:
HTTP/1.1 200 OK
Date: Thu, 02 Jun 2016 14:45:35 GMT
Server: Apache
PROXY_SERVER_INFO: host=slcsbplatformapiserv3002.slc.paypal.com;threadId=1237
Paypal-Debug-Id: 79d98acf1fffc
CORRELATION-ID: 79d98acf1fffc
X-PAYPAL-TOKEN-SERVICE: IAAS
Paypal-Debug-Id: 79d98acf1fffc
Set-Cookie: X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Dplatformapiserv%26TIME%3D2403749975%26HTTP_X_PP_AZ_LOCATOR%3D; Expires=Thu, 02 Jun 2016 15:15:37 GMT; domain=.paypal.com; path=/; Secure; HttpOnly
Set-Cookie: X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT
Vary: Authorization
Content-Length: 550
Connection: close
Content-Type: application/json

{"scope":"https://uri.paypal.com/services/subscriptions https://api.paypal.com/v1/payments/.* https://api.paypal.com/v1/vault/credit-card https://uri.paypal.com/services/applications/webhooks openid https://uri.paypal.com/payments/payouts https://api.paypal.com/v1/vault/credit-card/.*","nonce":"2016-06-02T14:45:37ZSS2eV7p3ULSz7UT6HyX2E4wKxj5EcLn2eppbUlk2QGw","access_token":"A101.8eCh86j5olMPYXzROLPaL5XZl6r97eVisN8XnGwAlzQb2b4E_9v1rjEwG-OWXiIb.gElSvx1bMS1aGWJPmbA86E6r7a8","token_type":"Bearer","app_id":"APP-80W284485P519543T","expires_in":32400}
"


================================================================================

2016-06-02 16:45:34 USER NOTICE: "API response decoded:
stdClass Object
(
    [scope] => https://uri.paypal.com/services/subscriptions https://api.paypal.com/v1/payments/.* https://api.paypal.com/v1/vault/credit-card https://uri.paypal.com/services/applications/webhooks openid https://uri.paypal.com/payments/payouts https://api.paypal.com/v1/vault/credit-card/.*
    [nonce] => 2016-06-02T14:45:37ZSS2eV7p3ULSz7UT6HyX2E4wKxj5EcLn2eppbUlk2QGw
    [access_token] => A101.8eCh86j5olMPYXzROLPaL5XZl6r97eVisN8XnGwAlzQb2b4E_9v1rjEwG-OWXiIb.gElSvx1bMS1aGWJPmbA86E6r7a8
    [token_type] => Bearer
    [app_id] => APP-80W284485P519543T
    [expires_in] => 32400
)
"


================================================================================

2016-06-02 16:45:34 USER NOTICE: "API request:
POST https://api.sandbox.paypal.com/v1/payments/payment
Authorization: Bearer A101.8eCh86j5olMPYXzROLPaL5XZl6r97eVisN8XnGwAlzQb2b4E_9v1rjEwG-OWXiIb.gElSvx1bMS1aGWJPmbA86E6r7a8
Accept: application/json
Accept-Language: en_US
Content-Type: application/json
PayPal-Partner-Attribution-Id: Gambio_Cart_REST_EC
Expect:

{"intent":"sale","payer":{"payment_method":"paypal"},"transactions":[{"amount":{"currency":"EUR","total":"64.88","details":{"subtotal":"59.98","tax":"0.00","shipping":"4.90"}},"description":"Jannis Metzidakis Clothing","item_list":{"items":[{"quantity":1,"name":"Herren T-Shirt \"Jannis Metzidakis\"","price":"29.99","currency":"EUR","sku":"JM-TS-001"},{"quantity":1,"name":"Herren T-Shirt \"Jannis Metzidakis\"","price":"29.99","currency":"EUR","sku":"JM-TS-007"}],"shipping_address":{"recipient_name":"John Doe","line1":"Kleistra\u00dfe 57","city":"Gotham City","postal_code":"11111","country_code":"DE","state":"Sunshine State"}}}],"redirect_urls":{"return_url":"http:\/\/www.jannis-metzidakis.de\/checkout_confirmation.php","cancel_url":"http:\/\/www.jannis-metzidakis.de\/checkout_payment.php?paypal=cancel"},"experience_profile_id":"XP-T87F-SZZV-XFMB-CLXV"}
"


================================================================================

2016-06-02 16:45:34 USER NOTICE: "API response:
HTTP/1.1 201 Created
Date: Thu, 02 Jun 2016 14:45:38 GMT
Server: Apache
PROXY_SERVER_INFO: host=slcsbplatformapiserv3002.slc.paypal.com;threadId=450
Paypal-Debug-Id: b062131170206
CORRELATION-ID: b062131170206
Content-Language: en_us
Paypal-Debug-Id: b062131170206
Set-Cookie: X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Dplatformapiserv%26TIME%3D2454081623%26HTTP_X_PP_AZ_LOCATOR%3D; Expires=Thu, 02 Jun 2016 15:15:38 GMT; domain=.paypal.com; path=/; Secure; HttpOnly
Set-Cookie: X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT
Vary: Authorization
Content-Length: 1199
Connection: close
Content-Type: application/json

{"id":"PAY-9GK47887SA921632BK5IENEQ","intent":"sale","state":"created","payer":{"payment_method":"paypal"},"transactions":[{"amount":{"total":"64.88","currency":"EUR","details":{"subtotal":"59.98","tax":"0.00","shipping":"4.90"}},"description":"Jannis Metzidakis Clothing","item_list":{"items":[{"name":"Herren T-Shirt \"Jannis Metzidakis\"","sku":"JM-TS-001","price":"29.99","currency":"EUR","quantity":1},{"name":"Herren T-Shirt \"Jannis Metzidakis\"","sku":"JM-TS-007","price":"29.99","currency":"EUR","quantity":1}],"shipping_address":{"recipient_name":"John Doe","line1":"1111 Hollywood Blvd","city":"Gotham City","state":"Sunshine State","postal_code":"11111","country_code":"DE"}},"related_resources":[]}],"experience_profile_id":"XP-T87F-SZZV-XFMB-CLXV","create_time":"2016-06-02T14:45:38Z","links":[{"href":"https://api.sandbox.paypal.com/v1/payments/payment/PAY-9GK47887SA921632BK5IENEQ","rel":"self","method":"GET"},{"href":"https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-96N54809U8717384H","rel":"approval_url","method":"REDIRECT"},{"href":"https://api.sandbox.paypal.com/v1/payments/payment/PAY-9GK47887SA921632BK5IENEQ/execute","rel":"execute","method":"POST"}]}
"


================================================================================

2016-06-02 16:45:34 USER NOTICE: "API response decoded:
stdClass Object
(
    [id] => PAY-9GK47887SA921632BK5IENEQ
    [intent] => sale
    [state] => created
    [payer] => stdClass Object
        (
            [payment_method] => paypal
        )

    [transactions] => Array
        (
            [0] => stdClass Object
                (
                    [amount] => stdClass Object
                        (
                            [total] => 64.88
                            [currency] => EUR
                            [details] => stdClass Object
                                (
                                    [subtotal] => 59.98
                                    [tax] => 0.00
                                    [shipping] => 4.90
                                )

                        )

                    [description] => Jannis Metzidakis Clothing
                    [item_list] => stdClass Object
                        (
                            [items] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [name] => Herren T-Shirt "Jannis Metzidakis"
                                            [sku] => JM-TS-001
                                            [price] => 29.99
                                            [currency] => EUR
                                            [quantity] => 1
                                        )

                                    [1] => stdClass Object
                                        (
                                            [name] => Herren T-Shirt "Jannis Metzidakis"
                                            [sku] => JM-TS-007
                                            [price] => 29.99
                                            [currency] => EUR
                                            [quantity] => 1
                                        )

                                )

                            [shipping_address] => stdClass Object
                                (
                                    [recipient_name] => John Doe
                                    [line1] => 1111 Hollywood Blvd
                                    [city] => Gotham City
                                    [state] => Sunshine State
                                    [postal_code] => 11111
                                    [country_code] => DE
                                )

                        )

                    [related_resources] => Array
                        (
                        )

                )

        )

    [experience_profile_id] => XP-T87F-SZZV-XFMB-CLXV
    [create_time] => 2016-06-02T14:45:38Z
    [links] => Array
        (
            [0] => stdClass Object
                (
                    [href] => https://api.sandbox.paypal.com/v1/payments/payment/PAY-9GK47887SA921632BK5IENEQ
                    [rel] => self
                    [method] => GET
                )

            [1] => stdClass Object
                (
                    [href] => https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-96N54809U8717384H
                    [rel] => approval_url
                    [method] => REDIRECT
                )

            [2] => stdClass Object
                (
                    [href] => https://api.sandbox.paypal.com/v1/payments/payment/PAY-9GK47887SA921632BK5IENEQ/execute
                    [rel] => execute
                    [method] => POST
                )

        )

)
"


================================================================================

2016-06-02 16:46:10 USER NOTICE: "API request:
GET https://api.sandbox.paypal.com/v1/payments/payment/PAY-9GK47887SA921632BK5IENEQ
Authorization: Bearer A101.8eCh86j5olMPYXzROLPaL5XZl6r97eVisN8XnGwAlzQb2b4E_9v1rjEwG-OWXiIb.gElSvx1bMS1aGWJPmbA86E6r7a8
Accept: application/json
Accept-Language: en_US
Content-Type: application/json
PayPal-Partner-Attribution-Id: Gambio_Cart_REST_EC
Expect:
"


================================================================================

2016-06-02 16:46:10 USER NOTICE: "API response:
HTTP/1.1 200 OK
Date: Thu, 02 Jun 2016 14:46:11 GMT
Server: Apache
PROXY_SERVER_INFO: host=slcsbplatformapiserv3002.slc.paypal.com;threadId=1339
Paypal-Debug-Id: e54defa495b69
CORRELATION-ID: e54defa495b69
Content-Language: en_us
Paypal-Debug-Id: e54defa495b69
Set-Cookie: X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Dplatformapiserv%26TIME%3D3007729751%26HTTP_X_PP_AZ_LOCATOR%3D; Expires=Thu, 02 Jun 2016 15:16:11 GMT; domain=.paypal.com; path=/; Secure; HttpOnly
Set-Cookie: X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT
Vary: Authorization
Content-Length: 1886
Connection: close
Content-Type: application/json

{"id":"PAY-9GK47887SA921632BK5IENEQ","intent":"sale","state":"created","cart":"96N54809U8717384H","payer":{"payment_method":"paypal","status":"VERIFIED","payer_info":{"email":"sandbox@jannis-metzidakis.de","first_name":"Jan","last_name":"Metz","payer_id":"A7L4PETJFL6YU","shipping_address":{"recipient_name":"John Doe","line1":"1111 Hollywood Blvd","city":"Gotham City","state":"Sunshine State","postal_code":"11111","country_code":"DE"},"country_code":"DE","billing_address":{"line1":"ESpachstr. 1","line2":"","city":"Freiburg","state":"Empty","postal_code":"79111","country_code":"DE"}}},"transactions":[{"amount":{"total":"64.88","currency":"EUR","details":{"subtotal":"59.98","tax":"0.00","shipping":"4.90"}},"payee":{},"description":"Jannis Metzidakis Clothing","item_list":{"items":[{"name":"Herren T-Shirt \"Jannis Metzidakis\"","sku":"JM-TS-001","price":"29.99","currency":"EUR","quantity":1},{"name":"Herren T-Shirt \"Jannis Metzidakis\"","sku":"JM-TS-007","price":"29.99","currency":"EUR","quantity":1}],"shipping_address":{"recipient_name":"John Doe","line1":"1111 Hollywood Blvd","city":"Gotham City","state":"Sunshine State","postal_code":"11111","country_code":"DE"}},"related_resources":[]}],"redirect_urls":{"return_url":"http://www.jannis-metzidakis.de/checkout_confirmation.php?paymentId=PAY-9GK47887SA921632BK5IENEQ","cancel_url":"http://www.jannis-metzidakis.de/checkout_payment.php?paypal=cancel"},"create_time":"2016-06-02T14:45:38Z","update_time":"2016-06-02T14:46:11Z","links":[{"href":"https://api.sandbox.paypal.com/v1/payments/payment/PAY-9GK47887SA921632BK5IENEQ","rel":"self","method":"GET"},{"href":"https://api.sandbox.paypal.com/v1/payments/payment/PAY-9GK47887SA921632BK5IENEQ/execute","rel":"execute","method":"POST"},{"href":"https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-96N54809U8717384H","rel":"approval_url","method":"REDIRECT"}]}
"


================================================================================

2016-06-02 16:46:10 USER NOTICE: "API response decoded:
stdClass Object
(
    [id] => PAY-9GK47887SA921632BK5IENEQ
    [intent] => sale
    [state] => created
    [cart] => 96N54809U8717384H
    [payer] => stdClass Object
        (
            [payment_method] => paypal
            [status] => VERIFIED
            [payer_info] => stdClass Object
                (
                    [email] => sandbox@jannis-metzidakis.de
                    [first_name] => Jan
                    [last_name] => Metz
                    [payer_id] => A7L4PETJFL6YU
                    [shipping_address] => stdClass Object
                        (
                            [recipient_name] => John Doe
                            [line1] => 1111 Hollywood Blvd
                            [city] => Gotham City
                            [state] => Sunshine State
                            [postal_code] => 11111
                            [country_code] => DE
                        )

                    [country_code] => DE
                    [billing_address] => stdClass Object
                        (
                            [line1] => ESpachstr. 1
                            [line2] => 
                            [city] => Freiburg
                            [state] => Empty
                            [postal_code] => 79111
                            [country_code] => DE
                        )

                )

        )

    [transactions] => Array
        (
            [0] => stdClass Object
                (
                    [amount] => stdClass Object
                        (
                            [total] => 64.88
                            [currency] => EUR
                            [details] => stdClass Object
                                (
                                    [subtotal] => 59.98
                                    [tax] => 0.00
                                    [shipping] => 4.90
                                )

                        )

                    [payee] => stdClass Object
                        (
                        )

                    [description] => Jannis Metzidakis Clothing
                    [item_list] => stdClass Object
                        (
                            [items] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [name] => Herren T-Shirt "Jannis Metzidakis"
                                            [sku] => JM-TS-001
                                            [price] => 29.99
                                            [currency] => EUR
                                            [quantity] => 1
                                        )

                                    [1] => stdClass Object
                                        (
                                            [name] => Herren T-Shirt "Jannis Metzidakis"
                                            [sku] => JM-TS-007
                                            [price] => 29.99
                                            [currency] => EUR
                                            [quantity] => 1
                                        )

                                )

                            [shipping_address] => stdClass Object
                                (
                                    [recipient_name] => John Doe
                                    [line1] => 1111 Hollywood Blvd
                                    [city] => Gotham City
                                    [state] => Sunshine State
                                    [postal_code] => 11111
                                    [country_code] => DE
                                )

                        )

                    [related_resources] => Array
                        (
                        )

                )

        )

    [redirect_urls] => stdClass Object
        (
            [return_url] => http://www.jannis-metzidakis.de/checkout_confirmation.php?paymentId=PAY-9GK47887SA921632BK5IENEQ
            [cancel_url] => http://www.jannis-metzidakis.de/checkout_payment.php?paypal=cancel
        )

    [create_time] => 2016-06-02T14:45:38Z
    [update_time] => 2016-06-02T14:46:11Z
    [links] => Array
        (
            [0] => stdClass Object
                (
                    [href] => https://api.sandbox.paypal.com/v1/payments/payment/PAY-9GK47887SA921632BK5IENEQ
                    [rel] => self
                    [method] => GET
                )

            [1] => stdClass Object
                (
                    [href] => https://api.sandbox.paypal.com/v1/payments/payment/PAY-9GK47887SA921632BK5IENEQ/execute
                    [rel] => execute
                    [method] => POST
                )

            [2] => stdClass Object
                (
                    [href] => https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-96N54809U8717384H
                    [rel] => approval_url
                    [method] => REDIRECT
                )

        )

)
"


================================================================================

2016-06-02 16:46:32 USER NOTICE: "API request:
GET https://api.sandbox.paypal.com/v1/payments/payment/PAY-9GK47887SA921632BK5IENEQ
Authorization: Bearer A101.8eCh86j5olMPYXzROLPaL5XZl6r97eVisN8XnGwAlzQb2b4E_9v1rjEwG-OWXiIb.gElSvx1bMS1aGWJPmbA86E6r7a8
Accept: application/json
Accept-Language: en_US
Content-Type: application/json
PayPal-Partner-Attribution-Id: Gambio_Cart_REST_EC
Expect:
"


================================================================================

2016-06-02 16:46:32 USER NOTICE: "API response:
HTTP/1.1 200 OK
Date: Thu, 02 Jun 2016 14:46:33 GMT
Server: Apache
PROXY_SERVER_INFO: host=slcsbplatformapiserv3001.slc.paypal.com;threadId=533
Paypal-Debug-Id: a48a90c431163
CORRELATION-ID: a48a90c431163
Content-Language: en_us
Paypal-Debug-Id: a48a90c431163
Set-Cookie: X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Dplatformapiserv%26TIME%3D3376828503%26HTTP_X_PP_AZ_LOCATOR%3D; Expires=Thu, 02 Jun 2016 15:16:33 GMT; domain=.paypal.com; path=/; Secure; HttpOnly
Set-Cookie: X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT
Vary: Authorization
Content-Length: 1886
Connection: close
Content-Type: application/json

{"id":"PAY-9GK47887SA921632BK5IENEQ","intent":"sale","state":"created","cart":"96N54809U8717384H","payer":{"payment_method":"paypal","status":"VERIFIED","payer_info":{"email":"sandbox@jannis-metzidakis.de","first_name":"Jan","last_name":"Metz","payer_id":"A7L4PETJFL6YU","shipping_address":{"recipient_name":"John Doe","line1":"1111 Hollywood Blvd","city":"Gotham City","state":"Sunshine State","postal_code":"11111","country_code":"DE"},"country_code":"DE","billing_address":{"line1":"ESpachstr. 1","line2":"","city":"Freiburg","state":"Empty","postal_code":"79111","country_code":"DE"}}},"transactions":[{"amount":{"total":"64.88","currency":"EUR","details":{"subtotal":"59.98","tax":"0.00","shipping":"4.90"}},"payee":{},"description":"Jannis Metzidakis Clothing","item_list":{"items":[{"name":"Herren T-Shirt \"Jannis Metzidakis\"","sku":"JM-TS-001","price":"29.99","currency":"EUR","quantity":1},{"name":"Herren T-Shirt \"Jannis Metzidakis\"","sku":"JM-TS-007","price":"29.99","currency":"EUR","quantity":1}],"shipping_address":{"recipient_name":"John Doe","line1":"1111 Hollywood Blvd","city":"Gotham City","state":"Sunshine State","postal_code":"11111","country_code":"DE"}},"related_resources":[]}],"redirect_urls":{"return_url":"http://www.jannis-metzidakis.de/checkout_confirmation.php?paymentId=PAY-9GK47887SA921632BK5IENEQ","cancel_url":"http://www.jannis-metzidakis.de/checkout_payment.php?paypal=cancel"},"create_time":"2016-06-02T14:45:38Z","update_time":"2016-06-02T14:46:33Z","links":[{"href":"https://api.sandbox.paypal.com/v1/payments/payment/PAY-9GK47887SA921632BK5IENEQ","rel":"self","method":"GET"},{"href":"https://api.sandbox.paypal.com/v1/payments/payment/PAY-9GK47887SA921632BK5IENEQ/execute","rel":"execute","method":"POST"},{"href":"https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-96N54809U8717384H","rel":"approval_url","method":"REDIRECT"}]}
"


================================================================================

2016-06-02 16:46:32 USER NOTICE: "API response decoded:
stdClass Object
(
    [id] => PAY-9GK47887SA921632BK5IENEQ
    [intent] => sale
    [state] => created
    [cart] => 96N54809U8717384H
    [payer] => stdClass Object
        (
            [payment_method] => paypal
            [status] => VERIFIED
            [payer_info] => stdClass Object
                (
                    [email] => sandbox@jannis-metzidakis.de
                    [first_name] => Jan
                    [last_name] => Metz
                    [payer_id] => A7L4PETJFL6YU
                    [shipping_address] => stdClass Object
                        (
                            [recipient_name] => John Doe
                            [line1] => 1111 Hollywood Blvd
                            [city] => Gotham City
                            [state] => Sunshine State
                            [postal_code] => 11111
                            [country_code] => DE
                        )

                    [country_code] => DE
                    [billing_address] => stdClass Object
                        (
                            [line1] => ESpachstr. 1
                            [line2] => 
                            [city] => Freiburg
                            [state] => Empty
                            [postal_code] => 79111
                            [country_code] => DE
                        )

                )

        )

    [transactions] => Array
        (
            [0] => stdClass Object
                (
                    [amount] => stdClass Object
                        (
                            [total] => 64.88
                            [currency] => EUR
                            [details] => stdClass Object
                                (
                                    [subtotal] => 59.98
                                    [tax] => 0.00
                                    [shipping] => 4.90
                                )

                        )

                    [payee] => stdClass Object
                        (
                        )

                    [description] => Jannis Metzidakis Clothing
                    [item_list] => stdClass Object
                        (
                            [items] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [name] => Herren T-Shirt "Jannis Metzidakis"
                                            [sku] => JM-TS-001
                                            [price] => 29.99
                                            [currency] => EUR
                                            [quantity] => 1
                                        )

                                    [1] => stdClass Object
                                        (
                                            [name] => Herren T-Shirt "Jannis Metzidakis"
                                            [sku] => JM-TS-007
                                            [price] => 29.99
                                            [currency] => EUR
                                            [quantity] => 1
                                        )

                                )

                            [shipping_address] => stdClass Object
                                (
                                    [recipient_name] => John Doe
                                    [line1] => 1111 Hollywood Blvd
                                    [city] => Gotham City
                                    [state] => Sunshine State
                                    [postal_code] => 11111
                                    [country_code] => DE
                                )

                        )

                    [related_resources] => Array
                        (
                        )

                )

        )

    [redirect_urls] => stdClass Object
        (
            [return_url] => http://www.jannis-metzidakis.de/checkout_confirmation.php?paymentId=PAY-9GK47887SA921632BK5IENEQ
            [cancel_url] => http://www.jannis-metzidakis.de/checkout_payment.php?paypal=cancel
        )

    [create_time] => 2016-06-02T14:45:38Z
    [update_time] => 2016-06-02T14:46:33Z
    [links] => Array
        (
            [0] => stdClass Object
                (
                    [href] => https://api.sandbox.paypal.com/v1/payments/payment/PAY-9GK47887SA921632BK5IENEQ
                    [rel] => self
                    [method] => GET
                )

            [1] => stdClass Object
                (
                    [href] => https://api.sandbox.paypal.com/v1/payments/payment/PAY-9GK47887SA921632BK5IENEQ/execute
                    [rel] => execute
                    [method] => POST
                )

            [2] => stdClass Object
                (
                    [href] => https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-96N54809U8717384H
                    [rel] => approval_url
                    [method] => REDIRECT
                )

        )

)
"


================================================================================

2016-06-02 16:46:32 USER NOTICE: "API request:
PATCH https://api.sandbox.paypal.com/v1/payments/payment/PAY-9GK47887SA921632BK5IENEQ
Authorization: Bearer A101.8eCh86j5olMPYXzROLPaL5XZl6r97eVisN8XnGwAlzQb2b4E_9v1rjEwG-OWXiIb.gElSvx1bMS1aGWJPmbA86E6r7a8
Accept: application/json
Accept-Language: en_US
Content-Type: application/json
PayPal-Partner-Attribution-Id: Gambio_Cart_REST_EC
Expect:

[{"op":"add","path":"\/transactions\/0\/invoice_number","value":"400223"}]
"


================================================================================

2016-06-02 16:46:32 USER NOTICE: "API response:
HTTP/1.1 500 Internal Server Error
Date: Thu, 02 Jun 2016 14:46:33 GMT
Server: Apache
PROXY_SERVER_INFO: host=slcsbplatformapiserv3001.slc.paypal.com;threadId=343
Paypal-Debug-Id: 40d0e22ee2478
CORRELATION-ID: 40d0e22ee2478
Content-Language: en_us
Connection: close
Connection: close
Paypal-Debug-Id: 40d0e22ee2478
Set-Cookie: X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Dplatformapiserv%26TIME%3D3376828503%26HTTP_X_PP_AZ_LOCATOR%3D; Expires=Thu, 02 Jun 2016 15:16:34 GMT; domain=.paypal.com; path=/; Secure; HttpOnly
Set-Cookie: X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT
Vary: Authorization
Content-Length: 194
Content-Type: application/json

{"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"40d0e22ee2478"}
"


================================================================================

2016-06-02 16:46:32 USER NOTICE: "API response decoded:
stdClass Object
(
    [name] => INTERNAL_SERVICE_ERROR
    [message] => An internal service error has occurred
    [information_link] => https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR
    [debug_id] => 40d0e22ee2478
)
"
---snap---

**Comment by pp-randy** [comment]
I can't reproduce this directly, with your JSON string I got a 400.  Can you format the JSON to look like this for the patch?  
`[{"op":"add","path":"/transactions/0/invoice_number","value":""}]`

**Comment by jamecs** [comment]
unfortunately I'm not a PHP crack. I simply copied the debug messages from the gambio shopsystem.

**Comment by pp-randy** [comment]
@jamecs would you please run another test and provide the patch failure log again?  I want to check the error is the same.

**Comment by jamecs** [comment]
sure....i'll be back....

**Comment by jamecs** [comment]
================================================================================

2016-06-03 16:58:50 USER NOTICE: "API request:
PATCH https://api.sandbox.paypal.com/v1/payments/payment/PAY-4NA002091A098941RK5IZWCQ
Authorization: Bearer A101.fQraLmfpP6pYjL1nZPEdJAs3u_P8bRclUuY7oW9kxn7NBPTrsJBd-QqyrS7NoRvY.A96ibEhulz9-c3jNfDBQCs-SFw4
Accept: application/json
Accept-Language: en_US
Content-Type: application/json
PayPal-Partner-Attribution-Id: Gambio_Cart_REST_EC
Expect:

[{"op":"add","path":"\/transactions\/0\/invoice_number","value":"400225"}]
"


================================================================================

2016-06-03 16:58:50 USER NOTICE: "API response:
HTTP/1.1 500 Internal Server Error
Date: Fri, 03 Jun 2016 14:58:52 GMT
Server: Apache
PROXY_SERVER_INFO: host=slcsbplatformapiserv3001.slc.paypal.com;threadId=489
Paypal-Debug-Id: e969bd3798640
CORRELATION-ID: e969bd3798640
Content-Language: en_us
Connection: close
Connection: close
Paypal-Debug-Id: e969bd3798640
Set-Cookie: X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Dplatformapiserv%26TIME%3D748376407%26HTTP_X_PP_AZ_LOCATOR%3D; Expires=Fri, 03 Jun 2016 15:28:52 GMT; domain=.paypal.com; path=/; Secure; HttpOnly
Set-Cookie: X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT
Vary: Authorization
Content-Length: 194
Content-Type: application/json

{"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"e969bd3798640"}
"


================================================================================

2016-06-03 16:58:50 USER NOTICE: "API response decoded:
stdClass Object
(
    [name] => INTERNAL_SERVICE_ERROR
    [message] => An internal service error has occurred
    [information_link] => https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR
    [debug_id] => e969bd3798640
)
"

**Comment by jamecs** [comment]
maybe that would help too

http://server1.jamecs.net/paypal/

all logs from the gambio shopsystem related to paypal

**Comment by pp-randy** [comment]
I am escalating this internally for additional investigation: PPPLPAYPT-9619; unfortunately, I am not able to replicate. 

If your cart could support adding the invoice_number during the initial payment request this might help move forward as a workaround.  Or if you have an option to disable invoice number for now in your cart settings to see if it continues.

**Comment by jamecs** [comment]
afaik the invoice number will be generated automatically by the shop software.
I will check if there is any possibility to assign a number manually. i will report here.

**Comment by pp-randy** [comment]
If it could be added to the initial payment request, you could reduce an API call per each transaction.

**Comment by pp-randy** [comment]
@jamecs I apologize would you be able to generate a new error again? We are trying to rule out an intermittent sandbox issue.

**Comment by jamecs** [comment]
Here you go 

---snip---

2016-06-06 17:41:01 (e6fcf999ce5f487caec122d9726eb0ae) USER NOTICE: "API request:
PATCH https://api.sandbox.paypal.com/v1/payments/payment/PAY-84R80323563530212K5KZS3A
Authorization: Bearer A101.HReo7rfwn6dNQTvfOhHj7C-oOPSPr0BsCjZF3GNA6Yb3NUZLzk5zud7HabmPEw7X.1NSmA8gOJip6-WZDHZv4D1Zp-zm
Accept: application/json
Accept-Language: en_US
Content-Type: application/json
PayPal-Partner-Attribution-Id: Gambio_Cart_REST_EC
Expect:

[{"op":"add","path":"\/transactions\/0\/invoice_number","value":"400203"}]
" in /var/www/hosting/kenpo/jannis-metzidakis.de/html/gambio-2.7.4.1/system/classes/external/paypal3/PayPalLogger.inc.php:125 (Details)

2016-06-06 17:41:01 (e6fcf999ce5f487caec122d9726eb0ae) USER NOTICE: "API response:
HTTP/1.1 500 Internal Server Error
Date: Mon, 06 Jun 2016 15:41:03 GMT
Server: Apache
PROXY_SERVER_INFO: host=slcsbplatformapiserv3002.slc.paypal.com;threadId=231
Paypal-Debug-Id: 5904220a9b47c
CORRELATION-ID: 5904220a9b47c
Content-Language: en_us
Connection: close
Connection: close
Paypal-Debug-Id: 5904220a9b47c
Set-Cookie: X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Dplatformapiserv%26TIME%3D2409190743%26HTTP_X_PP_AZ_LOCATOR%3D; Expires=Mon, 06 Jun 2016 16:11:03 GMT; domain=.paypal.com; path=/; Secure; HttpOnly
Set-Cookie: X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT
Vary: Authorization
Content-Length: 194
Content-Type: application/json

{"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"5904220a9b47c"}
" in /var/www/hosting/kenpo/jannis-metzidakis.de/html/gambio-2.7.4.1/system/classes/external/paypal3/PayPalLogger.inc.php:125 (Details)

2016-06-06 17:41:01 (e6fcf999ce5f487caec122d9726eb0ae) USER NOTICE: "API response decoded:
stdClass Object
(
    [name] => INTERNAL_SERVICE_ERROR
    [message] => An internal service error has occurred
    [information_link] => https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR
    [debug_id] => 5904220a9b47c
)

---snap---

**Comment by pp-randy** [comment]
@jamecs I apologize I haven't been able to get you any insight into this failure.  Since this does not appear to be an SDK issue at this time would you be able to contact PayPal Technical Support?  You can create a ticket here: https://www.paypal-techsupport.com/app/ask

**Comment by pp-randy** [comment]
Closing this issue. PayPal Technical Support will be better able to move forward with resolution.
