### ISSUE TITLE
Fail when creating credit card payment

### ISSUE THREAD

**Issue by kilip** [paypal/PayPal-PHP-SDK#584]
### Required Information

- PHP Version: 5.6.21
- PayPal-PHP-SDK Version: 1.7.1
- Debug ID(s): 842439ba773ab

### Issue Description
Always fail when I tried to make a credit card payment. The same code actually worked before, but since 25 May this same code is not working anymore (I know from my test log that the last working code is in 19 May).

**Comment by jaypatel512** [comment]
This may be caused because of the overused credit card number. This is a known issue in sandbox. Can you please try different credit card number, and see if you are getting the same error or not. Specially `4111111111111..1` will not work at all. 

Let me know if that resolves the issue.

**Comment by jaypatel512** [comment]
Try using this `4669424246660779` credit card for sandbox. You can generate more similar sandbox credit card by following step 4 at https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1413&viewlocale=en_US&direct=en

**Comment by kilip** [comment]
I still have this UNKNOWN-ERROR, Debug ID: e6d6d7c860000

I have tried follow step 4, but there are no "Generate CC Number" in that add credit card form.

**Comment by kilip** [comment]
It's working now! Thanks for help

**Comment by pp-randy** [comment]
For internal tracking: PPPLMER-14753
