### ISSUE TITLE
Getting error ACCOUNT_UNCONFIRMED_EMAIL even if it is confirmed

### ISSUE THREAD

**Issue by copongcopong** [paypal/PayPal-PHP-SDK#586]
### Required Information

- PHP Version: 5.6
- PayPal-PHP-SDK Version: "version": "1.7.2",
- Debug ID(s): 836c0994c8dfc

### Issue Description

This via the Payouts API endpoint; 

Under PayPal\Api\PayoutItemDetails Object

```
[errors] => PayPal\Api\Error Object
                                                (
                                                    [_propMap:PayPal\Common\PayPalModel:private] => Array
                                                        (
                                                            [name] => ACCOUNT_UNCONFIRMED_EMAIL 
                                                            [message] => Sender's email is not confirmed
                                                            [information_link] => https://developer.paypal.com/webapps/developer/docs/api/#ACCOUNT_UNCONFIRMED_EMAIL 
                                                        )

                                                )
```
the url under "information_link" is no help.

Appears to be same issue with http://stackoverflow.com/questions/36805772/paypal-api-error-senders-email-is-not-confirmed

**Comment by ppmtscory** [comment]
@copongcopong is this still an issue?  I see that you've had successful Payouts between the same accounts after you filed this issue.  What I'm seeing as an issue at the timeframe of this error has to do with funding so, before I file an issue for the error mapping, I wanted to see if you were still experiencing this or not.

**Comment by copongcopong** [comment]
It appears to be something to be set in Paypal's backend. We've contact their support directly and have it fixed. Thanks

**Comment by ppmtscory** [comment]
@copongcopong can you let me know when it was that you called in to have support correct the issue?  I'd like to look in the account and see what the issue was exactly.

**Comment by copongcopong** [comment]
@ppmtscory It got resolved by the support (we called them); Here is an excerpt from the email I got from them too: 

> Thanks for contacting PayPal MTS!

> I see that your email is confirmed, and you have permissions for Payouts in REST, so it may be a glitch in the system which happens from time to time. I suggest you add another email to your account, confirm it, and make it default / primary and then remove the original email and re-add it, confirm it and set it to primary. If you want, you should be able to remove the extra email that you added. This should fix the issue but if it persists, just respond to this ticket and I will continue to help.
.

**Comment by Beagle25** [comment]
@ppmtscory I'm actually running into this same exact issue.

Unfortunately, MTS has not responded to my ticket in almost a week, the business specialists I've talked to on the phone have not been able to diagnose the problem, and the suggested solution listed above didn't have any effect.

I've verified that both PayPal accounts have confirmed email addresses and sufficient funds each time I've attempted a payout. I'm also still receiving mass payment receipt emails saying that the payment was denied.

**My Environment**
PHP Version: 5.5.11
PayPal-PHP-SDK Version: "version": "1.6.4",
Debug ID(s): NULL (The denied payout item always returns a NULL debug ID)

**Code Snippet**
This is a snippet of the PHP code that's triggering the failures with hard coded values from real attempted payments included.

```
$payouts = new \PayPal\Api\Payout();

$senderBatchHeader = new \PayPal\Api\PayoutSenderBatchHeader();
$senderBatchHeader->setSenderBatchId('18')
->setEmailSubject('Monthly Payment');

$senderItem = new \PayPal\Api\PayoutItem();
$senderItem->setRecipientType('EMAIL')
->setNote('Monthly Payment')
->setReceiver('<RECIPIENT EMAIL>')
->setSenderItemId('18')
->setAmount(new \PayPal\Api\Currency('{
"value":"0.06",
"currency":"USD"
}'));

$payouts->setSenderBatchHeader($senderBatchHeader)->addItem($senderItem);
$payoutBatch = $payouts->createSynchronous($apiContext);

$payoutItems = $payoutBatch->getItems();
$payoutItem = $payoutItems[0];
$payoutItemId = $payoutItem->getPayoutItemId();

$payoutItemDetails = \PayPal\Api\PayoutItem::get($payoutItemId, $apiContext);
$payoutItemFee = $payoutItemDetails->getPayoutItemFee();

var_dump($payoutItems);
```

**API Response**
This is the output of the above code.

```
array(1) {
	[0]=> object(PayPal\Api\PayoutItemDetails)#38 (1) {
		["_propMap":"PayPal\Common\PayPalModel":private]=> array(8) {
			["payout_item_id"]=> string(13) "B7GK8KPJVVE4N"
			["transaction_status"]=> string(6) "FAILED"
			["payout_item_fee"]=> object(PayPal\Api\Currency)#40 (1) {
				["_propMap":"PayPal\Common\PayPalModel":private]=> array(2) {
					["currency"]=> string(3) "USD"
					["value"]=> string(4) "0.00"
				}
			}
			["payout_batch_id"]=> string(13) "H36EBZ7FZYHJC"
			["payout_item"]=> object(PayPal\Api\PayoutItem)#42 (1) {
				["_propMap":"PayPal\Common\PayPalModel":private]=> array(5) {
					["amount"]=> object(PayPal\Api\Currency)#44 (1) {
						["_propMap":"PayPal\Common\PayPalModel":private]=> array(2) {
							["currency"]=> string(3) "USD"
							["value"]=> string(4) "0.06"
						}
					}
					["note"]=> string(23) "Monthly payment"
					["receiver"]=> string(21) "<RECIPIENT EMAIL>"
					["recipient_type"]=> string(5) "EMAIL"
					["sender_item_id"]=> string(2) "21"
				}
			}
			["time_processed"]=> string(20) "2016-06-22T03:04:05Z"
			["errors"]=> object(PayPal\Api\Error)#46 (1) {
				["_propMap":"PayPal\Common\PayPalModel":private]=> array(3) {
					["name"]=> string(26) "ACCOUNT_UNCONFIRMED_EMAIL "
					["message"]=> string(31) "Sender's email is not confirmed"
					["information_link"]=> string(83) "https://developer.paypal.com/webapps/developer/docs/api/#ACCOUNT_UNCONFIRMED_EMAIL "
				}
			}
			["links"]=> array(1) {
				[0]=> object(PayPal\Api\Links)#48 (1) {
					["_propMap":"PayPal\Common\PayPalModel":private]=> array(3) {
						["href"]=> string(61) "https://api.paypal.com/v1/payments/payouts-item/B7GK8KPJVVE4N"
						["rel"]=> string(4) "item"
						["method"]=> string(3) "GET"
					}
				}
			}
		}
	}
}
```

I've been banging my head against a wall trying to get past this issue so any help would be greatly appreciated!

**Comment by ppmtscory** [comment]
@Beagle25 can you let me know your ticket number and I can see if I can get somebody to have a look at it?

**Comment by Beagle25** [comment]
@ppmtscory Sure, the id I received is 1268175 and my incident number is 160616-000389.

For some reason I'm not able to use my PayPal credentials to login to the page and view my ticket at the link that was provided in my MTS confirmation email: https://www.paypal-techsupport.com/app/account/questions/detail/i_id/1268175

Thanks for your help.

**Comment by pp-randy** [comment]
@Beagle25 the credentials are separate for paypal-techsupport.com, you will want to follow the reset password flow.  

This is most likely a bug with the error being thrown since your email is confirmed.  I tested with an unverified account in the sandbox and also get the same email address error, which is not the correct error for this issue since the email is confirmed.  This could explain the error you are seeing. 

When you log into PayPal.com do you see anything about Get Verified?

**Comment by Beagle25** [comment]
@pp-randy Thanks for clearing that up. I'll reset my paypal-techsupport.com password to get access to my ticket.

Unfortunately no, PayPal.com is showing that my email address has been confirmed. I tried associating a new email with my account, confirming it, switching it to be my primary address, then deleting my original email and I still received the same error. I then tried switching back to my original email in the same manor and experienced the same result.

I've also tried payouts to several different PayPal accounts with sufficient funds and confirmed email addresses and they've all failed the same way.

**Comment by pp-randy** [comment]
@Beagle25 The issue is most likely related to if your account is Verified, and not the email (since its already confirmed).

**Comment by Beagle25** [comment]
@pp-randy Sounds good. It looks like the only thing left on my To-Do list is adding a bank account. I'll finish that step and let you know whether or not this has an effect.

**Comment by pp-randy** [comment]
@Beagle25 please let me know if this resolves the issue for you.  There is still a bug, so in the mean time I have created a bug to follow up further internally since the wrong error is being returned when an account is unverified.

Internal Tracking: PPPLPAYPT-10298

**Comment by Beagle25** [comment]
@pp-randy Good news! I was able to get payouts working by adding a confirmed bank account, swapping out my emails again, and using a new API client secret. The only quirk I'm still running into is the payout item fee always returning $0.00 but I can work around that.

Thank you very much for your help.
