### ISSUE TITLE
No way to remove charge model using override_charge_models object when creating new Billing Agreement.

### ISSUE THREAD

**Issue by lsimeonov** [paypal/PayPal-PHP-SDK#588]
### Required Information

- PHP Version: 7.0.2
- PayPal-PHP-SDK Version: 1.7.2
- Debug ID(s): 1ae803a92ebc5  (request tries to set the charge model amount to 0)

### Issue Description
There is no way to remove a charge model when creating a billing agreement using override_charge_models. Neither you can set the amount to 0.

So if I collect VAT for one customers and none for others there is no way to remove the charge. 
Of course this can be tackled by using different plan but the solution is dirty and adds significant overhead where you can use only one plan for the task.

**Comment by ppmtscory** [comment]
@lsimeonov when I sent a $0 value it works just fine for me.  Below is the code I use with the SDK...
```
$ovChgModel = new OverrideChargeModel();
$ovChgModel->setChargeId('CHM-6EG851821V256282PG3BKDNI')
    ->setAmount(new Currency(array('value' => '0', 'currency' => 'USD')));
$agreement->setOverrideChargeModels(array($ovChgModel));
```

**Comment by lsimeonov** [comment]
@ppmtscory 

Just made second test and it works. Obviously I was doing something wrong with the request as I was working late.
Everything is working now.
Thanks!
