### ISSUE TITLE
Notification when reoccurring payment is made

### ISSUE THREAD

**Issue by blazerunner44** [paypal/PayPal-PHP-SDK#593]
I was able to setup a billing agreement using the sdk. Now I am wondering how to have a notification sent to my app when the monthly subscription payment goes through. I tried setting a notify_url on the merchant preferences object, but that caused the API to return something to the effect of "this field is not allowed".

```
$merchantPreferences = new MerchantPreferences();
$merchantPreferences>setReturnUrl("return url") ->setCancelUrl("cancel url")->setNotifyUrl("ipn url")
```

My next idea was to take a look at webhooks. The two that I thought might be what I'm looking for were 

- BILLING.PLAN.UPDATED: This event is triggered when a billing plan is updated.
- BILLING.SUBSCRIPTION.UPDATED: This event is triggered when a billing subscription is updated.

( I love the in-depth documentation on when each hook is called) :)

So I'm not quite sure which webhook, if any, to use. Neither of those sound like they notify when a payment is processed but instead notify when a change is made to the agreement terms, price, etc.

Could someone point me in the right direction?

**Comment by ppmtscory** [comment]
@blazerunner44 unfortunately there is no webhook that's fired when you receive a payment during the normal course of the subscription.  This enhancement is being tracked [here](https://github.com/paypal/PayPal-Python-SDK/issues/132).  This is a general request and is not specific to a certain SDK so please follow along over there for any updates.  In the meantime, you can use IPN via your account profile to be notified of such payments.
