### ISSUE TITLE
accessToken:PayPal returning empty

### ISSUE THREAD

**Issue by JeffersonFilho** [paypal/PayPal-PHP-SDK#595]
### Required Information

- PHP Version: 5.6.22
- PayPal-PHP-SDK Version: 1.7.3
- Debug ID(s):

### Issue Description

Hello guys,

For some strange reason the **accessToken:PayPal\Auth\OAuthTokenCredential:private]**  is retuning empty.

This is my code: 

```
use PayPal\Rest\ApiContext;
use PayPal\Auth\OAuthTokenCredential;

$clientId = 'myID';
$clientSecret = 'mySecret';


    $apiContext = new ApiContext(
        new OAuthTokenCredential(
            $clientId,
            $clientSecret
        )
    );

    $apiContext->setConfig(
        array(
            'mode' => 'sandbox',
            'log.LogEnabled' => true,
            'log.FileName' => '../PayPal.log',
            'log.LogLevel' => 'DEBUG',
            'cache.enabled' => true,
	    'validation.level' => 'log'

        )
    );

print_r($apiContext);

PayPal\Rest\ApiContext Object
(
    [requestId:PayPal\Rest\ApiContext:private] => 
    [credential:PayPal\Rest\ApiContext:private] => PayPal\Auth\OAuthTokenCredential Object
        (
            [clientId:PayPal\Auth\OAuthTokenCredential:private] => myID
            [clientSecret:PayPal\Auth\OAuthTokenCredential:private] => mySecret
            [accessToken:PayPal\Auth\OAuthTokenCredential:private] => 
            [tokenExpiresIn:PayPal\Auth\OAuthTokenCredential:private] => 
            [tokenCreateTime:PayPal\Auth\OAuthTokenCredential:private] => 
            [cipher:PayPal\Auth\OAuthTokenCredential:private] => PayPal\Security\Cipher Object
                (
                    [secretKey:PayPal\Security\Cipher:private] => I get a value here
                )

            [_propMap:PayPal\Common\PayPalModel:private] => Array
                (
                )

        )

)

```
Any ideas why the token field is empty?

Many thanks!

**Comment by jaypatel512** [comment]
It will be empty for the first call. We do a lazy call where we only retrieve access token if it is required by underlying API operation. 

You can read more on how to get started in PHP SDK in our [wiki section](https://github.com/paypal/PayPal-PHP-SDK/wiki/Making-First-Call).

**Comment by JeffersonFilho** [comment]
Hello jaypatel512,

I know but this is the problem, is not retrieving the token at all if I try to do ```$payment->create($apiContext);``` or ```  $payment = Payment::get($paymentId, $apiContext);``` I get 500 error which I believe is because I haven't got the access token on my ```$apiContext```. Any suggestion why?
