### ISSUE TITLE
ISSUE:FAILURE: SECURITY WARNING: TLSv1.2 is not supported on this system

### ISSUE THREAD

**Issue by shikaids** [paypal/PayPal-PHP-SDK#596]
Hello,
I run paypal-sampl of PHP on ubuntu+apache+mysql+nginx+php5.6.22, CHECK TLS: {myurl}/payment/paypal-sample/sample/tls/TlsCheck.php,I got  this:

```
1. FAILURE: SECURITY WARNING: TLSv1.2 is not supported on this system. Please upgrade your curl to atleast 7.34.0.
- Current Curl Version: 7.35.0
- Current OpenSSL Version:OpenSSL/1.0.1f (Failed)

```

So,  I upgraded openssl to 1.0.1t , recomplied PHP, and success.

> openssl version -a
```
OpenSSL 1.0.1t  3 May 2016
built on: Fri Jun 24 03:04:34 2016
platform: linux-x86_64
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) idea(int) blowfish(idx) 
compiler: gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -m64 -DL_ENDIAN -O3 -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM
OPENSSLDIR: "/usr/local/ssl"
```

I checked PHP, in a shell on your production system, run:

> $ php -r '$ch = curl_init(); curl_setopt($ch, CURLOPT_URL, "https://tlstest.paypal.com/"); var_dump(curl_exec($ch));'

the shell showed, just like this:

> PayPal_Connection_OKbool(true)

BUT the TlsCheck.php was also showed:

```
1. FAILURE: SECURITY WARNING: TLSv1.2 is not supported on this system. Please upgrade your curl to atleast 7.34.0.
- Current Curl Version: 7.35.0
- Current OpenSSL Version:OpenSSL/1.0.1f (Failed)

```

So, I checked php.info, and it show:
```
OpenSSL support	enabled
OpenSSL Library Version	OpenSSL 1.0.1f 6 Jan 2014
OpenSSL Header Version	OpenSSL 1.0.1t 3 May 2016
Openssl default config	/usr/lib/ssl/openssl.cnf
```
**PLEASE ATEEN, The openssl library version is different of Header Version.**

THE PAYPAL-SAMPLE PYAMENT IS STILL NOT WORKING!

What problem about this?

on the link https://github.com/paypal/tls-update#php
it say "OpenSSL used by CURL library is required to be 1.0.1c or higher. "
BUT IT NOT WORK.

Someone can tell, what is going on, why is it, and how can I do.

THANKS!!!

**Comment by jaypatel512** [comment]
Can you please make sure that the version of php that is used in your command line is the same used for your web server ?

**Comment by jaypatel512** [comment]
Also, please review the docs mentioned here. https://github.com/paypal/TLS-update/tree/php-improvements#php

I have updated the description to try to differentiate between the OS openssl version (`openssl version`), PHP openssl extension(php.ini - openssl.so), and php_curl openssl version (`php -r 'echo json_encode(curl_version(), JSON_PRETTY_PRINT);'`). 

In your case, you are updating the openssl on your OS and your PHP, but not the php_curl. Try to run `php -r 'echo json_encode(curl_version(), JSON_PRETTY_PRINT);'` and see the ssl version. Please let me know if that is up to date too, and you are still seeing this error.

**Comment by jaypatel512** [comment]
There are many threads including [this](http://stackoverflow.com/questions/35131590/php-curl-set-ssl-version) that can help you find the best way for you to update openssl for your PHP code.

**Comment by shikaids** [comment]
@jaypatel512  Thank you!!!
Yes, the version of PHP that is used in your command line is the same used for web server.
The PHP version is 5.6.22.

I think you are right. I ran the command (php -r 'echo json_encode(curl_version(), JSON_PRETTY_PRINT);'). It shown:

```

{
    "version_number": 467712,
    "age": 3,
    "features": 50877,
    "ssl_version_number": 0,
    "version": "7.35.0",
    "host": "x86_64-pc-linux-gnu",
    "ssl_version": "OpenSSL\/1.0.1f",
    "libz_version": "1.2.8",
    "protocols": [
        "dict",
        "file",
        "ftp",
        "ftps",
        "gopher",
        "http",
        "https",
        "imap",
        "imaps",
        "ldap",
        "ldaps",
        "pop3",
        "pop3s",
        "rtmp",
        "rtsp",
        "smtp",
        "smtps",
        "telnet",
        "tftp"
    ]
}
```
the ssl_version is different from the openssl version of Operating System.

> The article show:( https://github.com/paypal/TLS-update/tree/php-improvements#php)

```
The php_curl version shown here could be different from the openssl version, as they are two different components.
Please keep in mind when updating your openssl libraries, you need to update php_curl openssl version and not the OS openssl version.
```

```
There are three places where you will find openssl
Openssl installed in your Operating System openssl version.
Openssl extension installed in your PHP Found in php.ini.
Openssl used by PHP_CURL. curl_version().
```

I think I need to update php_curl openssl version. 
Now I need goole for updating php_curl openssl version. 
And do you have any suggestion for updating php_curl?

**Comment by jaypatel512** [comment]
Steps on updating php_curl is widely different based on what OS you use, third party tools like (MAMP, XAMMP), web server that enables it (nginx, apache), etc. 

A quick stackoverflow tour should be enough for you to get the details. I was hoping to add more details to the TLS-Update Link, however, I do not have the proper resources to test them myself. 

I would really appreciate if you could help me link to the steps you took for your combination. This way, we could possibly get the whole list that would help other external developers.

**Comment by shikaids** [comment]
@jaypatel512  sorry for replying late.
Hello, THE PROBLEM IS STILL HERE.  Every things seems right, but the PAYPAL-SDK-SAMPLE TlsCheck.php not OK. I think the problem is not about SSL / TLS 1.2, but I can not find any other problems now.

Please see this:
```
> paypal-sample/sample/tls/TlsCheck.php

1. FAILURE: SECURITY WARNING: TLSv1.2 is not supported on this system. Please upgrade your curl to atleast 7.34.0.
- Current Curl Version: 7.35.0
- Current OpenSSL Version:OpenSSL/1.0.1f (Failed)
```

and I do these:

I updated SSL/TLS libraries like below:
```
- OpenSSL installed in your Operating System openssl version.
- OpenSSL extension installed in your PHP. This can be found in your php.ini.
- OpenSSL used by PHP_CURL. curl_version().
```

1, UPDATE OPENSSL VERSION IN Operating System(ubuntu)
```
> openssl version -a
OpenSSL 1.0.1t  3 May 2016
built on: Fri Jun 24 03:04:34 2016
platform: linux-x86_64
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) idea(int) blowfish(idx) 
compiler: gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -m64 -DL_ENDIAN -O3 -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM
OPENSSLDIR: "/usr/local/ssl"
```

2, CHECK PHP  INFO, I have configured --with-openssl, and openssl is enable
```

> PHP INFO
'./configure' '--prefix=/usr/local/php' '--with-config-file-path=/usr/local/php/etc' '--with-apxs2=/usr/local/apache/bin/apxs' '--with-mysql=mysqlnd' '--with-mysqli=mysqlnd' '--with-pdo-mysql=mysqlnd' '--with-iconv-dir' '--with-freetype-dir=/usr/local/freetype' '--with-jpeg-dir' '--with-png-dir' '--with-zlib' '--with-libxml-dir=/usr' '--enable-xml' '--disable-rpath' '--enable-bcmath' '--enable-shmop' '--enable-sysvsem' '--enable-inline-optimization' '--with-curl' '--enable-mbregex' '--enable-mbstring' '--with-mcrypt' '--enable-ftp' '--with-gd' '--enable-gd-native-ttf' '--with-openssl=shared' '--with-mhash' '--enable-pcntl' '--enable-sockets' '--with-xmlrpc' '--enable-zip' '--enable-soap' '--with-gettext' '--disable-fileinfo' '--enable-opcache'

--with-openssl=shared

openssl
OpenSSL support	enabled
OpenSSL Library Version	OpenSSL 1.0.1f 6 Jan 2014
OpenSSL Header Version	OpenSSL 1.0.1t 3 May 2016
Openssl default config	/usr/lib/ssl/openssl.cnf

add extension at the end of php.ini:
extension=openssl.so
```

I download the latest cURL version, 7.49.1, it include  libcurl / 7.35.0, OpenSSL/1.0.1f. 
The latest cURL not include OpenSSL/1.0.1t
```
> curl -V
curl 7.49.1 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP 
```

3,I checked by these command of PHP:

```

> php -r 'echo json_encode(curl_version(), JSON_PRETTY_PRINT);'
{
    "version_number": 467712,
    "age": 3,
    "features": 50877,
    "ssl_version_number": 0,
    "version": "7.35.0",
    "host": "x86_64-pc-linux-gnu",
    "ssl_version": "OpenSSL\/1.0.1f",
    "libz_version": "1.2.8",
    "protocols": [
        "dict",
        "file",
        "ftp",
        "ftps",
        "gopher",
        "http",
        "https",
        "imap",
        "imaps",
        "ldap",
        "ldaps",
        "pop3",
        "pop3s",
        "rtmp",
        "rtsp",
        "smtp",
        "smtps",
        "telnet",
        "tftp"
    ]
}
```

above all, I installed Openssl in Operating System,  Openssl Extension in PHP, and OpenSSL used by PHP_CURL. 

I checked if it work by two way below:

1、use command
```

> php -r '$ch = curl_init(); curl_setopt($ch, CURLOPT_URL, "https://tlstest.paypal.com/"); var_dump(curl_exec($ch)); var_dump(curl_error($ch));'
PayPal_Connection_OKbool(true)
string(0) ""

```
2, usre cacert.pem and TlsCheck.php
The page show:PayPal_Connection_OKbool(true)

But the paypal-sample problem still here.
I think if it the openssl problem? If have any other issue?

**Comment by shikaids** [comment]
I read this https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1913&viewlocale=en_US

```

PayPal is in the process of upgrading the SSL certificates used to secure our web sites and API endpoints. These new certificates will be signed using the SHA-256 algorithm and VeriSign's 2048-bit G5 Root Certificate. You will need to ensure that your environment supports the use of the SHA-256 signing algorithm and discontinue the use of SSL connections that rely on the VeriSign G2 Root Certificate.

```

Should I update SSL certificates? How to do it?
Or if ,  while I update openssl, the SSL certificates is installed default?

**Comment by shikaids** [comment]
@jaypatel512 
Hello, I think I found what happened about the issue. BUT THERE IS NEW ISSUE.

I download latest paypal PayPal-PHP-SDK from https://github.com/paypal/PayPal-PHP-SDK.
And I did not change anything to run it. [of couse composer update first]
There show:

```
Response Object

SUCCESS. Your system supports TLSv1.2
```

Then ,I change the sandbox $clientId and $clientSecret of my app  on bootstrap.php.

```
$clientId ="the sandbox clientId of my app";
$clientSecret ="the sandbox clientSecret of my app";
$apiContext->setConfig(
        array(
            'mode' => 'sandbox',
            'log.LogEnabled' => true,
            'log.FileName' => '../PayPal.log',
            'log.LogLevel' => 'DEBUG', // PLEASE USE `INFO` LEVEL FOR LOGGING IN LIVE ENVIRONMENTS
            'cache.enabled' => true,
            // 'http.CURLOPT_CONNECTTIMEOUT' => 30
            // 'http.headers.PayPal-Partner-Attribution-Id' => '123123123'
            //'log.AdapterFactory' => '\PayPal\Log\DefaultLogFactory' // Factory class implementing \PayPal\Log\PayPalLogFactory
        )
    );
```

It was also working.

BUT, when I changed the live $clientId and $clientSecret of my app  on bootstrap.php.
IT WAS NOT WORKING!!!!


```
$clientId ="the live clientId of my app";
$clientSecret ="the live clientSecret of my app";
$apiContext->setConfig(
        array(
            'mode' => 'live',
            'log.LogEnabled' => true,
            'log.FileName' => '../PayPal.log',
            'log.LogLevel' => 'INFO', // PLEASE USE `INFO` LEVEL FOR LOGGING IN LIVE ENVIRONMENTS
            'cache.enabled' => true,
            // 'http.CURLOPT_CONNECTTIMEOUT' => 30
            // 'http.headers.PayPal-Partner-Attribution-Id' => '123123123'
            //'log.AdapterFactory' => '\PayPal\Log\DefaultLogFactory' // Factory class implementing \PayPal\Log\PayPalLogFactory
        )
    );
```

What happened about the problem?

**Comment by jaypatel512** [comment]
Hey @shikaids !

I think we might know the root cause. Currently Sandbox is restricted to TLSv1.2 however, live currently still accepts any TLS version. The actual TLS Update in live is scheduled later. 

Can you please confirm my theory by making a temporary change and test it for me. I am not able to reproduce this issue on my servers.

Please add the following line just before the clientId secret line as shown below:
```php
\PayPal\Core\PayPalHttpConfig::$defaultCurlOptions[CURLOPT_SSLVERSION] = 1;
$clientId ="the live clientId of my app";
$clientSecret ="the live clientSecret of my app";
$apiContext->setConfig(
        array(
            'mode' => 'live',
            'log.LogEnabled' => true,
            'log.FileName' => '../PayPal.log',
            'log.LogLevel' => 'INFO', // PLEASE USE `INFO` LEVEL FOR LOGGING IN LIVE ENVIRONMENTS
            'cache.enabled' => true,
            // 'http.CURLOPT_CONNECTTIMEOUT' => 30
            // 'http.headers.PayPal-Partner-Attribution-Id' => '123123123'
            //'log.AdapterFactory' => '\PayPal\Log\DefaultLogFactory' // Factory class implementing \PayPal\Log\PayPalLogFactory
        )
    );
```
This should set the SSLVERSION to TLSv1, which includes all TLSv1.0, 1.1 and 1.2 and most likely the future revisions.

**Comment by shikaids** [comment]
Hey @jaypatel512 
I done it as your post.
Ran sample/tls/TlsCheck.php, it still went wrong.
I suposed it is not the adding line problem.

the wrong response is:

```
1. FAILURE: SECURITY WARNING: TLSv1.2 is not supported on this system. Please upgrade your curl to atleast 7.34.0.
- Current Curl Version: 7.35.0
- Current OpenSSL Version:OpenSSL/1.0.1f (Failed)

Response Object
 Got Http response code 401 when accessing https://test-api.sandbox.paypal.com/v1/oauth2/token.
```

I read the php code of  TlsCheck.php of sample. I think the problem is service.EndPoint link problem,
because we use live config, so cannot touch the link of https://test-api.sandbox.paypal.com.

```
$apiContext->setConfig(array('service.EndPoint'=>"https://test-api.sandbox.paypal.com", 'cache.enabled'=>false));
```

So, I think if the sandbox TlsCheck is sucess, now I use live mode, I am not going to do check, I do payment directly on lIVE MODE.

But got error.

Ran CreatePaymentUsingPayPal.php, it is right, and go to paypal site and login to pay it, paying is going on right, but continue,confirm to pay, it response ERROR. THESE CODE BELOW.
```

Request Object

{
    "intent": "sale",
    "payer": {
        "payment_method": "paypal"
    },
    "redirect_urls": {
        "return_url": "http://mydomainname/payment/paypal-sample2/sample/payments/ExecutePayment.php?success=true",
        "cancel_url": "http://mydomainname/payment/paypal-sample2/sample/payments/ExecutePayment.php?success=false"
    },
    "transactions": [
        {
            "amount": {
                "currency": "USD",
                "total": "0.40",
                "details": {
                    "shipping": "0.10",
                    "tax": "0.10",
                    "subtotal": "0.20"
                }
            },
            "item_list": {
                "items": [
                    {
                        "name": "Ground Coffee 40 oz",
                        "currency": "USD",
                        "quantity": 1,
                        "sku": "123123",
                        "price": "0.10"
                    },
                    {
                        "name": "Granola bars",
                        "currency": "USD",
                        "quantity": 1,
                        "sku": "321321",
                        "price": "0.10"
                    }
                ]
            },
            "description": "Payment description",
            "invoice_number": "57700bb59a22d"
        }
    ]
}
 
```

```

Response Object

{
    "intent": "sale",
    "payer": {
        "payment_method": "paypal"
    },
    "redirect_urls": {
        "return_url": "http://mydomainname/payment/paypal-sample2/sample/payments/ExecutePayment.php?success=true",
        "cancel_url": "http://mydomainname/payment/paypal-sample2/sample/payments/ExecutePayment.php?success=false"
    },
    "transactions": [
        {
            "amount": {
                "total": "0.40",
                "currency": "USD",
                "details": {
                    "subtotal": "0.20",
                    "tax": "0.10",
                    "shipping": "0.10"
                }
            },
            "description": "Payment description",
            "invoice_number": "57700bb59a22d",
            "item_list": {
                "items": [
                    {
                        "name": "Ground Coffee 40 oz",
                        "sku": "123123",
                        "price": "0.10",
                        "currency": "USD",
                        "quantity": 1
                    },
                    {
                        "name": "Granola bars",
                        "sku": "321321",
                        "price": "0.10",
                        "currency": "USD",
                        "quantity": 1
                    }
                ]
            },
            "related_resources": []
        }
    ],
    "id": "PAY-5JP75131GX3022801K5YAXNI",
    "state": "created",
    "create_time": "2016-06-26T17:07:01Z",
    "links": [
        {
            "href": "https://api.paypal.com/v1/payments/payment/PAY-5JP75131GX3022801K5YAXNI",
            "rel": "self",
            "method": "GET"
        },
        {
            "href": "https://www.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-8H0966112H7182608",
            "rel": "approval_url",
            "method": "REDIRECT"
        },
        {
            "href": "https://api.paypal.com/v1/payments/payment/PAY-5JP75131GX3022801K5YAXNI/execute",
            "rel": "execute",
            "method": "POST"
        }
    ]
}
```

BUT AFTER PAID RESPOSE:
```

Request Object

No Data
```

```

Response Object

 Got Http response code 400 when accessing https://api.paypal.com/v1/payments/payment/PAY-5JP75131GX3022801K5YAXNI/execute.

{
    "name": "VALIDATION_ERROR",
    "details": [
        {
            "field": "purchase_units[0]",
            "issue": "Item amount must add up to specified amount subtotal (or total if amount details not specified)"
        }
    ],
    "message": "Invalid request - see details",
    "information_link": "https://developer.paypal.com/docs/api/#VALIDATION_ERROR",
    "debug_id": "e47ae30dad2ae"
}
```

**Comment by shikaids** [comment]
Hey @jaypatel512 
I done it as your post.
Ran sample/tls/TlsCheck.php, it still went wrong.
I suposed it is not the adding line problem.

the wrong response is:

1. FAILURE: SECURITY WARNING: TLSv1.2 is not supported on this system. Please upgrade your curl to atleast 7.34.0.
- Current Curl Version: 7.35.0
- Current OpenSSL Version:OpenSSL/1.0.1f (Failed)

Response Object
 Got Http response code 401 when accessing https://test-api.sandbox.paypal.com/v1/oauth2/token.
I read the php code of TlsCheck.php of sample. I think the problem is service.EndPoint link problem,
because we use live config, so cannot touch the link of https://test-api.sandbox.paypal.com.

$apiContext->setConfig(array('service.EndPoint'=>"https://test-api.sandbox.paypal.com", 'cache.enabled'=>false));
So, I think if the sandbox TlsCheck is sucess, now I use live mode, I am not going to do check, I do payment directly on lIVE MODE.

IT WORK FINE.

So sorry for bothering you these days. THANK YOU VERY MUCH!!!!

Now I am going to try and test deeply on my php website, because the sample is working not means the practice work, I need going deeply.

**Comment by jaypatel512** [comment]
Hey @shikaids !

Hope I helped. For future reference, for anyone having similar issue, please review https://github.com/paypal/tls-update#php to test if your system works.

**Comment by ztjuh** [comment]
I'm having this issue too.

> 1. FAILURE: SECURITY WARNING: TLSv1.2 is not supported on this system. Please upgrade your curl to atleast 7.34.0.
> - Current Curl Version: 7.50.1
> - Current OpenSSL Version:OpenSSL/1.0.2h (Failed)

I have followed tls-update#php and tried the files (cacert.pem & TlsCheck.php).

    $ php -f TlsCheck.php
    PayPal_Connection_OK

    $ openssl version
    OpenSSL 1.0.2j  26 Sep 2016

    $ php -r 'echo json_encode(curl_version(), JSON_PRETTY_PRINT);'
    {
        "version_number": 471555,
        "age": 3,
        "features": 968605,
        "ssl_version_number": 0,
        "version": "7.50.3",
        "host": "i686-pc-linux-gnu",
        "ssl_version": "OpenSSL\/1.0.2j",
        "libz_version": "1.2.8",
        "protocols": [
            "dict",
            "file",
            "ftp",
            "ftps",
            "gopher",
            "http",
            "https",
            "imap",
            "imaps",
            "pop3",
            "pop3s",
            "rtsp",
            "scp",
            "sftp",
            "smb",
            "smbs",
            "smtp",
            "smtps",
            "telnet",
            "tftp"
        ]

From phpinfo();
    $_SERVER['SSL_VERSION_LIBRARY']	OpenSSL/1.0.2j

In PayPal.log I found the following
    [01-11-2016 09:08:08] PayPal\Core\PayPalHttpConnection : INFO: POST https://test-api.sandbox.paypal.com/v1/oauth2/token
    [01-11-2016 09:08:08] PayPal\Core\PayPalHttpConnection : INFO: Invalid or no certificate authority found - Retrying using bundled CA certs file

The only thing that occured to me is that phpinfo shows `OpenSSL 1.0.2j` and TlsCheck.php `OpenSSL/1.0.2h`.
