### ISSUE TITLE
Paypal's transactions history example

### ISSUE THREAD

**Issue by andr22** [paypal/PayPal-PHP-SDK#597]
### Required Information

- PHP Version: 5.4.17
- PayPal-PHP-SDK Version: last

### Issue Description

Is there any way to obtain all the transactions history (button, classic APIs, etc)?.

I would appreciate the code example.

**Comment by ppmtscory** [comment]
Unfortunately the REST version of (List Payments)[https://developer.paypal.com/docs/api/payments/#payment_list] will only grab REST transactions.  However, if you wanted, the classic (TransactionSearch)[https://developer.paypal.com/docs/classic/api/merchant/TransactionSearch_API_Operation_NVP/] API should provide all transactions.  I understand this isn't ideal, but at this time, those are the options.
