### ISSUE TITLE
How to make pre-approval payments and captures?!

### ISSUE THREAD

**Issue by kamboP** [paypal/PayPal-PHP-SDK#600]
### Required Information

- PHP Version:5.6
- PayPal-PHP-SDK Version:
- Debug ID(s):

### Issue Description
> Please include as many details (logs, steps to reproduce) as you can to help us reproduce this issue faster.

**Comment by ppmtscory** [comment]
If by pre-approval you mean authorizations, then you can check out the following examples in the payment [samples](https://github.com/paypal/PayPal-PHP-SDK/tree/master/sample/payments) folder of this repo.

AuthorizePayment.php
AuthorizePaymentUsingPayPal.php
AuthorizationCapture.php

**Comment by kamboP** [comment]
Actually I am looking for this one here: 
https://developer.paypal.com/docs/classic/api/adaptive-payments/Preapproval_API_Operation/?mark=pre%20approval

**Comment by ppmtscory** [comment]
@kamboP those are the legacy APIs and all the documentation you should need to use them should be on those pages that you linked to.  Those APIs are not a part of this PHP REST SDK as they are not available via REST API yet.
