### ISSUE TITLE
Guest Payment

### ISSUE THREAD

**Issue by kmohsin** [paypal/PayPal-PHP-SDK#602]
Have few questions with regard to : Guest Payment; As  a reference screen is attached.

![img_1524](https://cloud.githubusercontent.com/assets/18312757/16736338/8ac28e72-475a-11e6-9dc7-42bf972eb7e3.PNG)

1. Can the guest payment through be directed back automatically to ExecutePayment.php ?
  - If yes will the payment id be available in the session after its return from guest (direct) payment through credit card?

2. If its just the services ( non tangible products ) that the payer is buying , can the ship to billing address be made permanently disabled ? If yes how ? 

thank you

### Required Information

- PHP Version:
- PayPal-PHP-SDK Version:
- Debug ID(s):

### Issue Description
> Please include as many details (logs, steps to reproduce) as you can to help us reproduce this issue faster.

**Comment by jaypatel512** [comment]
Answer 1: Yes, irrespective of what flow the user takes, paypal will redirect it back to `redirect_url` set by you (Generally, ExecutePayment.php).

Answer 2: You can use `Payment Experience` APIs to create an experience without a shipping address.
    Step 1: Create a new Payment Experience with `no_shipping` enabled. 
    Step 2: Store the `experienceId` returned back in your permanent record.
    Step 3: Anytime, the buyer is buying non-tangible products, you can add the `experience_id` stored before in your payment as 
```php
$payment->setExperienceProfileId("your profile id");
```
This would remove the need for shipping address.

**Comment by kmohsin** [comment]
thanks , How can the backend know if the user is going with a guest payment or a paypal payment ?

**Comment by jaypatel512** [comment]
Hey @kmohsin !

You can figure out if the user is going with guest payment by checking for [receipt_id](https://developer.paypal.com/docs/api/payments/#sale_get_response) in Sale response. 

However, there shouldnt be a real need for differentiating them.
