### ISSUE TITLE
Got Http response code 400 when accessing https://api.paypal.com/v1/payments/payment

### ISSUE THREAD

**Issue by laics1984** [paypal/PayPal-PHP-SDK#604]
### Required Information

- PHP Version: 5.6
- PayPal-PHP-SDK Version: 1.7.3
- Debug ID(s):

i receive this message  in the process of making payment from paypal account in the success return url:

> Fatal error: Uncaught exception 'PayPal\Exception\PayPalConnectionException' with message 'Got Http response code 400 when accessing https://api.paypal.com/v1/payments/payment/PAY-51W39127C3576120JK6DF54Q/execute.' in /home/ximplify/public_html/api/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php:178 Stack trace: #0 /home/ximplify/public_html/api/vendor/paypal/rest-api-sdk-php/lib/PayPal/Transport/PayPalRestCall.php(74): PayPal\Core\PayPalHttpConnection->execute('{"payer_id":"DP...') #1 /home/ximplify/public_html/api/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PayPalResourceModel.php(102): PayPal\Transport\PayPalRestCall->execute(Array, '/v1/payments/pa...', 'POST', '{"payer_id":"DP...', NULL) #2 /home/ximplify/public_html/api/vendor/paypal/rest-api-sdk-php/lib/PayPal/Api/Payment.php(653): PayPal\Common\PayPalResourceModel::executeCall('/v1/payments/pa...', 'POST', '{"payer_id":"DP...', NULL, Object(PayPal\Rest\ApiContext), NULL) #3 /home/ximplify/public_html/api/pay.php(33): PayPal\Api\Payment in /home/ximplify/public_html/api/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php on line 178

The below is my code: 

```
> $paymentId = $_GET['paymentId'];
> 	$payerId = $_GET['PayerID'];
> 
> 	try{
> 		$payment = Payment::get($paymentId, $paypal);
> 
> 		$execute = new PaymentExecution();
> 		$execute->setPayerId($payerId);
> 
> 		$result = $payment->execute($execute, $paypal);
> 
> 
> 		$transactions = $payment->getTransactions();
> 		$resources = $transactions[0]->getRelatedResources();
> 
> 		$sale = $resources[0]->getSale();
> 		$saleID = $sale->getId();
> 	}catch(PayPalConnectionException $e){
> 		echo $e->getCode(); // Prints the Error Code
>     	echo $e->getData();
>     	die($e);
> 	}catch (Exception $ex) {
> 	    die($ex);
> 	}
```

I have no issue on sandbox, only receive this 400 error message after switching to live. 
In live, it has no issue when i pay via credit card and debit card option on paypal, this error only appear when i pay using paypal account.

Can someone please help? Thanks.

**Comment by jaypatel512** [comment]
From the log trace, it looks like it did not threw proper information on `$e->getData();`. Can you please make sure you are getting that information correctly ? It should be similar to what is [shown here](https://github.com/paypal/PayPal-PHP-SDK/wiki/exception-%27PayPal%5CException%5CPayPalConnectionException%27-with-message-%27Got-Http-response-code-400-when-accessing).

**Comment by laics1984** [comment]
hi @jaypatel512 , the above error is what was being produced with the code above, with

```
echo $e->getCode(); 
echo $e->getData();
die($e);
```

I refer to the same doc too.

**Comment by jaypatel512** [comment]
Generally, the error should contain something like this:

```
{
    "name": "VALIDATION_ERROR",
    "details": [
        {
            "field": "transactions[0].amount",
            "issue": "Transaction amount details (subtotal, tax, shipping) must add up to specified amount total"
        }
    ],
    "message": "Invalid request - see details",
    "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#VALIDATION_ERROR",
    "debug_id": "0faff23b719d8"
}
```

which I do not see in your trace log. That got me thinking about it.

**Comment by jaypatel512** [comment]
Try using full path for Exception as shown below: 
```
} catch (PayPal\Exception\PayPalConnectionException $ex) {
```

**Comment by laics1984** [comment]
yes @jaypatel512 got it. 

`

> 400{"name":"INSTRUMENT_DECLINED","details":[],"message":"The instrument presented was either declined by the processor or bank, or it can't be used for this payment.","information_link":"https://developer.paypal.com/docs/api/#INSTRUMENT_DECLINED","debug_id":"f56553bc7a577"}

`

**Comment by laics1984** [comment]
@jaypatel512 may i know what causes the error above? it happens to both my account and my clients'. Thanks.

**Comment by ppmtscory** [comment]
@laics1984 when we reached out to your funding instrument to see if the payment could be processed, they responded with a decline response.  This is the reason for that error by looking up the debug ID you provided.  For payment decline messages, such as this, it's best to reach out to our [Merchant Tech Support](https://www.paypal-techsupport.com/app/ask) team so they can look up the attempt as this isn't an SDK issue.

**Comment by SteaveAshmore** [comment]
Facing same and unable to handle exeption
CRITICAL - Uncaught PHP Exception PayPal\Exception\PayPalConnectionException: "Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payment." at C:\wamp\www\taxi\vendor\paypal\rest-api-sdk-php\lib\PayPal\Core\PayPalHttpConnection.php line 154

**Comment by ppmtscory** [comment]
@SteaveAshmore this issue has been closed since July.  Please file a new issue with the extended logs (Jay outlined above how to retrieve them) so that we can take a look.

**Comment by nikkojoson** [comment]
![error](https://user-images.githubusercontent.com/10240947/37819378-3faa60e4-2eb8-11e8-8511-ddda6ce35473.png)

Experiencing same problem same as @SteaveAshmore

**Comment by xiaoleih41** [comment]
Did you get the detail error message by following the instruction provided by Jay? Please provide the `debugId` as well.

**Comment by efusionsoft** [comment]
if you check the error log, it says:

```
PayPal\Core\PayPalHttpConnection : ERROR: Got Http response code 400 when accessing https://api.paypal.com/v1/payments/payment/PAY-96M71322C3889580NLLO74MQ/execute. {"name":"INSTRUMENT_DECLINED","details":[],"message":"The instrument presented  was either declined by the processor or bank, or it can't be used for this payment.","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"4b1c022962b20"}
```
That happens when the payer ( customer ) tries to pay using a card that is expired or declined by the bank.

**Comment by xiaoleih41** [comment]
So the card was not good.  I believe you have got reason for the decline.

**Comment by ankitabhatti05** [comment]
https://github.com/paypal/PayPal-PHP-SDK/issues/604#issuecomment-232406453

@jaypatel512 i got same error what you define here

**Comment by luisfernandogp** [comment]
To solve this. I had to add the exception full path \PayPal\Exception\PayPalConnectionException $ex
