### ISSUE TITLE
Item Title - CSV Export

### ISSUE THREAD

**Issue by mersed** [paypal/PayPal-PHP-SDK#615]
### Required Information

- PHP Version:PHP 5.6.23-0+deb8u1 (cli) (built: Jul 12 2016 07:33:16)
- PayPal-PHP-SDK Version:1.7.4
- Debug ID(s):

### Issue Description
Currently I am using Paypal PHP SDK in order to process credit cards. And everything works properly without any kind of issues, credit cards are processed and everything works fine.

One of the requirements though is to have populated "Item Title" column within csv export with specific value during rest api request. 
> It is a standard export:
> 1. Login to your merchant/business account
> 2. Click on "View all of my transactions"
> 3. Click on "Download: CSV"
> 4. Within CSV "Item Title" column is not populated.

What i need to setup on my side prior the request in order for this field to be populated? I tried with quite a few fields but all of the requests i sent resulted with the empty column within that export.

> I was not able to find any kind of documentation which value corresponds to this specific field within an export.

Only thing I was able to find regarding this subject is this [guide](https://www.paypalobjects.com/webstatic/en_US/developer/docs/pdf/pp_merchantsetupadministrationguide.pdfl)

As per description within that document ti says:
---------------------------------------------------------------------------

Specified by buyer in the website field:
- Auction/Item Title

Or by seller in any of the following button-creation fields:
- PayPal Shopping Cart ItemName
- Buy Now Item Name
- Donations Item Name
- Subscriptions Name

But i was not able to find any of these fields within the Paypal PhP SDK

**Comment by mersed** [comment]
Ticket is created on the paypal side asking regarding this feature as well (before 10 days ago). I also tried with the ruby sdk as well (did not work as well). At the end it does not matter which language is used for rest api communication - it is mostly question "**Is there a field which corresponds to Item Title column within paypal export?**" 

FYI [ticket](http://stackoverflow.com/questions/38508987/paypal-rest-api-description-item-name-missing) is created on stackoverflow as well.

**Comment by pp-randy** [comment]
Hi @mersed,

Sorry for the delay in response.  This sample should have what you are looking for in regards to items https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/CreatePayment.php#L53

**Comment by mersed** [comment]
Hi @pp-randy 

That is the first thing I tried. It is not working (I checked documentation quite detailed so simple thing as that one is something I did not miss).

For example, report on Merchant Pro account which can be find as:
Home -> Reports -> Transaction Finder will have Item Name column even you provide it.

Same example for Merchant account 
Home -> History -> Download CSV

**Comment by pp-randy** [comment]
What is being populated appears to be the transaction description
https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/CreatePayment.php#L95

**Comment by mersed** [comment]
Hi @pp-randy 

Not sure that I understand "**What is being populated appears to be the transaction description**" because I tried to use transaction description as well and "Item Name" column within the report I mentioned is still empty.

However, it seems more complicated then i though. I had several call sessions with Paypal Support and few tickets opened on paypal side. I am waiting an update from their side and will provide update here as well.

Bottom point is that, for the report which is needed on my side:
Home -> Reports -> Transaction Finder 
it seems that there is no field on the paypal side which will populate "Item Name" column using REST API.

The ticket on paypal side is escalated into the "Researching" phase and they are working on it. As per my discussion with them there is indication that this is "bug" or "not completed api" functionality on their side and there is nothing to do with specific SDK.

**Comment by pp-randy** [comment]
I stand corrected @mersed when it was PayPal payment it was showing.

**Comment by mersed** [comment]
I see. Thank you for the update @pp-randy .
I will follow up regarding this as soon as I have update from their side.

**Comment by pp-randy** [comment]
Since you are working with Technical Support I will resolve this issue as it is not directly related to the SDK at this time.  Let me know if you need further assistance so I can escalate appropriately.

**Comment by mersed** [comment]
As promised, following up with an update regarding this issue. It seems that REST API will not cover everything (especially when we are talking about reporting system - which is quite important feature for larger customers).

Everything is resolved with usage of DoDirect Payment Api (seems like much more stable for credit card processing).

Posted an answer on [stackoverflow](http://stackoverflow.com/questions/38508987/paypal-rest-api-description-item-name-missing/38837721#38837721) as well in case someone is struggling with the same issue and wants more details.
