### ISSUE TITLE
Prerequisites must be updated from PHP 5.3 to 5.4 due to new logger class

### ISSUE THREAD

**Issue by Tomcraft1980** [paypal/PayPal-PHP-SDK#618]
### Required Information

- PHP Version: 5.3
- PayPal-PHP-SDK Version: 1.7.3
- Debug ID(s):

### Issue Description
Due to the new logger class that came with sdk version 1.7.0 and which uses traits, you need to change the prerequisites to use PHP 5.4 instead of PHP 5.3

**Comment by modGTB** [comment]
See here: http://php.net/manual/en/language.oop5.traits.php

**Comment by jaypatel512** [comment]
Huh ! Weird, I checked the `psr/log` [composer.json](https://github.com/php-fig/log/blob/master/composer.json#L14) and saw that it supports `php >= 5.3.0`

```
"require": {
        "php": ">=5.3.0"
    }
```

**Comment by modGTB** [comment]
but traits are only supported PHP >= 5.4

have a look at \Psr\Log\LoggerTrait.php

**Comment by jaypatel512** [comment]
I agree @modGTB ! I think the same bug exists in psr/log library, and that basically caused us to assume that PHP 5.3 should work. I will create a PR in Psr/log and get that fixed. I will update the dependency in our SDK too.

**Comment by jaypatel512** [comment]
Related PR in PSR/Log repository: https://github.com/php-fig/log/pull/48

**Comment by GrahamCampbell** [comment]
👎

**Comment by jaypatel512** [comment]
As expected ! Thanks @GrahamCampbell !
