### ISSUE TITLE
New function to set expiryBufferTime for OAuthTokenCredential

### ISSUE THREAD

**Issue by modGTB** [paypal/PayPal-PHP-SDK#619]
New function to set expiryBufferTime for OAuthTokenCredential to set the buffer time independent to session lifetime.

Therefore a new function in class OAuthTokenCredential like this:

>     /**
     * Helper method to set expiryBufferTime
     *
     * @param $time
     */
    public function setExpiryBufferTime($time)
    {
        self::$expiryBufferTime = (int)$time;
    }

**Comment by jaypatel512** [comment]
Hey @modGTB !

Can you please elaborate on why would you want to set the expireyBufferTime ? Any example, or use case would help a lot.

**Comment by modGTB** [comment]
Hi,
one customer reported, that a payment will fail, when the customer comes back to the shop and the cachefile has expired in the meanwhile.

My solution is to set it to the session expiry time (1440) in my case.

I have not checked how long a cachefile ist vaild in the live enviroment. In sandbox it is 12 hours.

**Comment by jaypatel512** [comment]
Generally, if it fails, it will automatically generate a new access token and try again. This feature might still enter log entry of failed try, but it will still continue to work for the user. However, I agree, that we can may be modify the expiryTime checker to have a fixed buffer of few seconds or so. 

Do you wish to send us a PR, and help us out here. I think creating a new method is too much. We can just create a constant, and add that to the expiration checker code. Thanks for bringing this up.

**Comment by jaypatel512** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Cs1hGhKa&#x2F;233-invalidate-access-token-cache-few-seconds-before-it-expires"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Invalidate access token cache few seconds before it expires</a>

**Comment by modGTB** [comment]
a very simple method would be to change the property from private to public.

> private static $expiryBufferTime = 120;

to 

> public static $expiryBufferTime = 120;

then you can change it like this:

> OAuthTokenCredential::$expiryBufferTime = 1440;

**Comment by modGTB** [comment]
PR is done
