### ISSUE TITLE
I am getting: {"name":"UNKNOWN_ERROR","message":"An unknown error occurred.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR","debug_id":"8125f4da8778d"}

### ISSUE THREAD

**Issue by krasho** [paypal/PayPal-PHP-SDK#624]
### Required Information

- PHP Version: 7
- PayPal-PHP-SDK Version: 1.7.4
- Debug ID(s): 8125f4da8778d

### Issue Description
Hello I am adding PayPal-PHP-SDK in my project and I wanted to register a payment in mode sandbox, but I am getting this message:

[06-08-2016 05:27:45] PayPal\Core\PayPalHttpConnection : ERROR: Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payment. {"name":"UNKNOWN_ERROR","message":"An unknown error occurred.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR","debug_id":"8125f4da8778d"}

I am using this data:
        $billing_address = new Address();
        $billing_address->setLine1("My Address");
        $billing_address->setCity("My City");
        $billing_address->setState("My State");
        $billing_address->setPostalCode("00000");
        $billing_address->setCountryCode("MX");

        $card = new CreditCard();
        $card->setType(strtolower("visa"))
            ->setNumber("4242424242424242")
            ->setExpireMonth("01")
            ->setExpireYear("2017")
            ->setCvv2("123")
            ->setFirstName("My First Name")
            ->setLastName("My Last Name");

        $fi = new FundingInstrument();
        $fi->setCreditCard($card);

        $payer = new Payer();
        $payer->setPaymentMethod("credit_card")
            ->setFundingInstruments(array($fi));

        $total = new Amount();
        $total->setCurrency("USD")
            ->setTotal(5.00);

//shipping Address
        $shipping_address = new ShippingAddress();
        $shipping_address->setCity("My City");
        $shipping_address->setCountryCode("MX");
        $shipping_address->setPostalCode("00000");
        $shipping_address->setLine1("My Address");
        $shipping_address->setState("My State");
        $shipping_address->setRecipientName("My RecipientName");

        $itemList = new ItemList();
        $itemList->setShippingAddress($shipping_address);

        $transaction = new Transaction();

        $transaction->setAmount($total)
            ->setDescription("Payment description")
            ->setInvoiceNumber(uniqid())
            ->setItemList($itemList);

        $payment = new Payment();
        $payment->setIntent("sale")
            ->setPayer($payer)
            ->setTransactions(array($transaction));

        try {
            $payment->create($this->_api_context);
        } catch (PayPal\Exception\PayPalConnectionException $ex) {
            $payPalerrors = $ex->getData();

        } catch (Exception $ex) {
            //echo "<br>error 3<br>";
            $errors    = $ex->getMessage();
        }
    }

What am I doing wrong?

Thanks
> Please include as many details (logs, steps to reproduce) as you can to help us reproduce this issue faster.

**Comment by jaypatel512** [comment]
Please use any other random credit card using many of freely available random credit card generation. These credit cards `4242...`, `4111`, etc are overused like crazy by all in sandbox, and causes these corner cases.

Here are few links to these free credit card numbers:
- http://www.getcreditcardnumbers.com/
- http://credit-card-generator.2-ee.com/
