### ISSUE TITLE
Payment Complete but no transaction recorded no deduction occured

### ISSUE THREAD

**Issue by naviciroel** [paypal/PayPal-PHP-SDK#625]
### Required Information

- PHP Version: 5.5+
- PayPal-PHP-SDK Version: latest

### Issue Description
> We currently having an issue regarding transaction not recorded in paypal using Live.
> We have tested the payment process on sandbox and it works smoothly. But on the live account we tested it and was also processing smoothly but when we check the account there was not transaction recorded and on the account that done the payment the amount was not deducted and no notification such as on hold or denied. we also recorded the the payment ID like [ PAY-1TU083178A750331EK6UYMSA ]. So any idea about this matter? Please help we really need to make this work cause our clients are currently wanting to pay online.

![pscreen](https://cloud.githubusercontent.com/assets/6640515/17509492/bd0feb28-5e4c-11e6-89ca-91f6c9325e71.png)

Code:

```
$clientId = 'XXXXXX';
$clientSecret = 'XXXXX';
$apiContext = $this->getApiContext($clientId, $clientSecret);
$payer = new Payer();
$payer->setPaymentMethod("paypal");

$item1 = new Item();
$item1->setName('Comapany Name')
->setCurrency('PHP')
->setQuantity(1)
->setPrice($payment_to_pay);

$redirectUrls = new RedirectUrls();
$redirectUrls->setReturnUrl('http:' . make_url('step', 'finish') . "?rf=" . $ID)
->setCancelUrl('http:' . make_url('step', 'finish') . "?cancel=1&rf=" . $ID);

$itemList = new ItemList();
$itemList->setItems([$item1]);


$details = new Details();
$details->setSubtotal($payment_to_pay);

$amount = new Amount();
$amount->setCurrency('PHP')
->setTotal($payment_to_pay)
->setDetails($details);

$transaction = new Transaction();
$transaction->setAmount($amount)
->setItemList($itemList)
->setDescription("{$prop_name} - {$room->rm_title} - {$days_of_stay}")
->setInvoiceNumber(uniqid());

$setBankTxnPendingUrl = 'http:' . make_url('step', 'finish') . "?rf=" . $ID;

$payment = new Payment();
$payment->setIntent("sale")
->setPayer($payer)
->setRedirectUrls($redirectUrls)
->setTransactions([$transaction])
->setExperienceProfileId($this->paypalCreateWebProfile($apiContext, $setBankTxnPendingUrl)->getId());
$request = clone $payment;
try {
$payment->create($apiContext);
} catch (\Exception $ex) {
redirect(make_url('step'));
exit(1);
}
$approvalUrl = $payment->getApprovalLink();
redirect($approvalUrl);
```

> 
> [04-08-2016 11:10:34] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payment-experience/web-profiles/
> [04-08-2016 11:10:35] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [04-08-2016 11:10:35] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payments/payment
> [04-08-2016 11:10:36] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [04-08-2016 05:17:59] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payment-experience/web-profiles/
> [04-08-2016 05:18:00] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [04-08-2016 05:18:00] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payments/payment
> [04-08-2016 05:18:02] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [05-08-2016 10:49:35] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/oauth2/token
> [05-08-2016 10:49:37] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 200
> [05-08-2016 10:49:37] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payment-experience/web-profiles/
> [05-08-2016 10:49:38] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [05-08-2016 10:49:38] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payments/payment
> [05-08-2016 10:49:39] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [05-08-2016 10:59:29] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payment-experience/web-profiles/
> [05-08-2016 10:59:30] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [05-08-2016 10:59:30] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payments/payment
> [05-08-2016 10:59:32] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [05-08-2016 11:03:29] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payment-experience/web-profiles/
> [05-08-2016 11:03:30] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [05-08-2016 11:03:30] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payments/payment
> [05-08-2016 11:03:32] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [05-08-2016 11:07:41] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payment-experience/web-profiles/
> [05-08-2016 11:07:42] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [05-08-2016 11:07:42] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payments/payment
> [05-08-2016 11:07:44] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [05-08-2016 11:26:53] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/oauth2/token
> [05-08-2016 11:26:54] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 200
> [05-08-2016 11:26:54] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payment-experience/web-profiles/
> [05-08-2016 11:26:55] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [05-08-2016 11:26:56] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payments/payment
> [05-08-2016 11:26:57] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [05-08-2016 11:30:15] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payment-experience/web-profiles/
> [05-08-2016 11:30:16] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [05-08-2016 11:30:16] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payments/payment
> [05-08-2016 11:30:18] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [08-08-2016 05:05:34] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/oauth2/token
> [08-08-2016 05:05:36] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 200
> [08-08-2016 05:05:36] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payment-experience/web-profiles/
> [08-08-2016 05:05:37] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [08-08-2016 05:05:37] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payments/payment
> [08-08-2016 05:05:38] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [08-08-2016 05:09:55] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payment-experience/web-profiles/
> [08-08-2016 05:09:56] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [08-08-2016 05:09:56] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payments/payment
> [08-08-2016 05:09:57] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [08-08-2016 05:09:58] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payment-experience/web-profiles/
> [08-08-2016 05:09:59] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [08-08-2016 05:09:59] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payments/payment
> [08-08-2016 05:10:00] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [09-08-2016 12:04:06] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payment-experience/web-profiles/
> [09-08-2016 12:04:07] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [09-08-2016 12:04:07] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payments/payment
> [09-08-2016 12:04:09] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [09-08-2016 02:19:38] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/oauth2/token
> [09-08-2016 02:19:40] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 200
> [09-08-2016 02:19:40] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payment-experience/web-profiles/
> [09-08-2016 02:19:41] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [09-08-2016 02:19:41] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payments/payment
> [09-08-2016 02:19:42] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [09-08-2016 02:23:14] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payment-experience/web-profiles/
> [09-08-2016 02:23:16] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [09-08-2016 02:23:16] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payments/payment
> [09-08-2016 02:23:17] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [09-08-2016 02:59:46] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payment-experience/web-profiles/
> [09-08-2016 02:59:47] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [09-08-2016 02:59:47] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payments/payment
> [09-08-2016 02:59:52] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 400
> [09-08-2016 02:59:52] PayPal\Core\PayPalHttpConnection : ERROR: Got Http response code 400 when accessing https://api.paypal.com/v1/payments/payment. {"name":"VALIDATION_ERROR","details":[{"field":"transactions[0]","issue":"Item amount must add up to specified amount subtotal (or total if amount details not specified)"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/docs/api/#VALIDATION_ERROR","debug_id":"3e8f60b781db4"}
> [09-08-2016 03:00:16] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payment-experience/web-profiles/
> [09-08-2016 03:00:17] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [09-08-2016 03:00:17] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payments/payment
> [09-08-2016 03:00:18] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 400
> [09-08-2016 03:00:18] PayPal\Core\PayPalHttpConnection : ERROR: Got Http response code 400 when accessing https://api.paypal.com/v1/payments/payment. {"name":"VALIDATION_ERROR","details":[{"field":"transactions[0]","issue":"Item amount must add up to specified amount subtotal (or total if amount details not specified)"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/docs/api/#VALIDATION_ERROR","debug_id":"4e9345f48f55"}
> [09-08-2016 03:03:39] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payment-experience/web-profiles/
> [09-08-2016 03:03:40] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [09-08-2016 03:03:40] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payments/payment
> [09-08-2016 03:03:41] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [09-08-2016 03:29:09] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payment-experience/web-profiles/
> [09-08-2016 03:29:11] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
> [09-08-2016 03:29:11] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.paypal.com/v1/payments/payment
> [09-08-2016 03:29:12] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201

**Comment by sankarbhavanib** [comment]
@naviciroel  I don't see any payment execution step on the log. Are you performing that step ? 

Please refer to https://developer.paypal.com/docs/api/payments/?mark=payment%20execution#payment_execute for more details

**Comment by naviciroel** [comment]
@sankarbhavanib 

Yes. Upon using sandbox their were execution but upon live, all I get is what is posted above and also I followed the docs of the api. Its really confusing cause every time we test it, its always successful and complete but no record no amount and no deduction. We need to make this work, we already had disabled the online payment and it has really affected our transactions.

**Comment by sankarbhavanib** [comment]
Step1 : Merchant creates payment token using payment call 
Step2: Customer Logs in and approve payment 
Step3: Merchant execute the approved payment  

you can see the payment transactions only when you complete all 3 steps

**Comment by sankarbhavanib** [comment]
Closing this ticket. Please reach out to us if you need further help
