### ISSUE TITLE
#Paypal REST# An internal service error has occurred # DebugId = ee77937c51914

### ISSUE THREAD

**Issue by etandon13** [paypal/PayPal-PHP-SDK#628]
**Required Information**

PHP Version: 5.6.14
PayPal-PHP-SDK Version: 1.0.0 (REST API)
Debug ID(s): "ee77937c51914"

**Issue Description**

We are trying to capture the payment using REST Paypal SDK on Live environment and giving the error as 
Got Http response code 500 when accessing https://api.paypal.com/v1/payments/authorization/#redacted text#/capture. {"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error occurred.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"ee77937c51914"}

We are tried multiple time for this capture request and giving same error.
This is a very generic error which doesn't help us understand what action should be taken to resolve this.
Can you please let us know the root cause for same?

**Comment by nazarel** [comment]
Also facing the same problem.

The frustrating part is that everything works fine in sandbox but not live.
Saving/Deleting credit cards from the vault works but it's almost impossible to debug what the problem is when using these stored cards to create payments.

**Comment by pp-randy** [comment]
@etandon13 I apologize for the delay. 
@nazarel 

Can both of you reach out to PayPal Technical Support since this is impacting your payments on production.  You can reach them here: https://www.paypal-techsupport.com/app/ask
