### ISSUE TITLE
CreditCardToken is not working 

### ISSUE THREAD

**Issue by mgw2007** [paypal/PayPal-PHP-SDK#630]
- PHP Version: 5.5.6
- PayPal-PHP-SDK Version: 1.7.4
- Debug ID(s): fdc3471037ed9

When I try to make payment using new credit card its working fine but If I save credit cards then I try to us it again depend on creditCardToken I got error UNKNOWN_ERROR

this is my code

        $apiContext  = new \PayPal\Rest\ApiContext(
                new \PayPal\Auth\OAuthTokenCredential(ClientID,ClientSecret)
        );

        $fi          = new FundingInstrument();
        $creditCardToken = new \PayPal\Api\CreditCardToken($apiContext);
        $creditCardToken->setCreditCardId(THE_CARD_ID);
        $fi->setCreditCardToken($creditCardToken);

        $payer       = new Payer();
        $payer->setPaymentMethod("credit_card")
                ->setFundingInstruments(array($fi));

        $amount      = new Amount();
        $amount->setCurrency("USD")
                ->setTotal('50');

        $transaction = new Transaction();
        $transaction->setAmount($amount)
                ->setDescription("Payment description")
                ->setInvoiceNumber(uniqid());
        $payment     = new Payment();
        $payment->setIntent("sale")
                ->setPayer($payer)
                ->setTransactions(array($transaction));

this is the response
{"name":"UNKNOWN_ERROR","message":"An unknown error occurred.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR","debug_id":"fdc3471037ed9"}

**Note:**my needs need is to allow users to add credit card information then I add the card on paypal and I save the credit card token so I can use this token to make schedules payments every month

Thanks

**Comment by pp-randy** [comment]
@mgw2007 can you try using the steps provided here? https://github.com/paypal/PayPal-NET-SDK/issues/165#issuecomment-222212829

This card appears to be tied to several sandbox accounts.  Can you attempt to generate a new test card number and vault it?  Then let me know if it is still occurring?

**Comment by mgw2007** [comment]
Hi @pp-randy 
I used the credit cards generated form https://www.paypal-knowledge.com/infocenter/index?page=content&id=FAQ1413&expand=true&locale=en_US
and its working fine now

Thanks

**Comment by pp-randy** [comment]
@mgw2007 thank you for the follow up.
