### ISSUE TITLE
FlowConfig doesn't have userAction

### ISSUE THREAD

**Issue by Anorionil** [paypal/PayPal-PHP-SDK#631]
### Required Information

- PayPal-PHP-SDK Version: Latest

### Issue Description
The SDK doesn't support the **user_action** field which is part of **flow_config**. See https://developer.paypal.com/docs/api/payment-experience/#definition-flow_config

**Comment by bluk** [comment]
Should be fixed with #682 so will close this. It should roll out in the next release.
