### ISSUE TITLE
Will credit cards in the vault remain valid until their expiration dates?

### ISSUE THREAD

**Issue by lway** [paypal/PayPal-PHP-SDK#632]
### Required Information
- PHP Version: 7.0.9
- PayPal-PHP-SDK Version: 1.7.4
- Debug ID(s): N/A
### Issue Description

I am storing credit cards in the vault and need to charge them at a later time, perhaps months in the future.  I noticed that each card has a valid_until property, but it doesn't seem to have any effect in sandbox mode.  I can't find any documentation describing exactly what the valid_until property does.  Does it have any effect on the validity of a stored credit card?

**Comment by bluk** [comment]
The `valid_until` property is not the same as the expiration date. I believe it is the date until the vaulted card is guaranteed to work as you suspected. The card's expiration date could be later than the valid_until date (e.g. the card expires in November 2019 but the vault_until date is until October 17th, 2019).

I've opened DEVDOC-518 to track this internally.

**Comment by bluk** [comment]
The documentation was updated to help clarify `valid_until`. Please see the [API reference](https://developer.paypal.com/docs/api/vault/#credit-card_create_response). If this isn't clear, you can directly contact the doc writers via the `Give us some feedback on this page` link at the bottom of the page or leave a comment and we can reopen. Thanks.
