### ISSUE TITLE
#Paypal REST# To get Capture-Id from Authorization-Id

### ISSUE THREAD

**Issue by kafuwale** [paypal/PayPal-PHP-SDK#633]
PHP Version: 5.6.14
PayPal-PHP-SDK Version: 1.0.0 (REST API)
Debug ID(s): ""

### Issue Description
In paypal SOAP API ,we can do a TransactionSearch() from the TransactionID (Authorization-Id) and Capture-Id can be gotten for already captured orders.

In REST API ,is there is any direct way to get the Capture-Id from the Authorization-Id?

We found following transaction search API
/v1/payments/payment/payment_id , but here payment_id is the parent payment-id of the transaction and is of no use because for Old paypal orders (placed via SOAP method) we are not getting the parent payment-id.

Please suggest the way to get Capture-Id from Authorization-Id.

**Comment by kafuwale** [comment]
@ppmtscory ,can you please help me out in this?

**Comment by ppmtscory** [comment]
At this time, you'd need to use the Classic APIs to look up the transactions that were processed that way.
