### ISSUE TITLE
Broken links at CreatePayment.php and CreatePayment.html

### ISSUE THREAD

**Issue by enav** [paypal/PayPal-PHP-SDK#634]
CreatePayment.php :
https://github.com/enav/PayPal-PHP-SDK/blob/master/sample/payments/CreatePayment.php#L117

CreatePayment.html :
https://github.com/enav/PayPal-PHP-SDK/blob/master/sample/doc/payments/CreatePayment.html#L80

**Comment by rbur0425** [comment]
i do not have any problems going to https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1413
