### ISSUE TITLE
Payments using credit card information - 500 error

### ISSUE THREAD

**Issue by djtetsu** [paypal/PayPal-PHP-SDK#636]
### Required Information

- PHP Version: 7.0.8
- PayPal-PHP-SDK Version: 1.7.4
- Debug ID(s):

### Issue Description
> Please include as many details (logs, steps to reproduce) as you can to help us reproduce this issue faster.

Trying out the sample code, 'Payments using credit card information' and I get the 500 error:
http://beta.cuddlecompanions.org/paypal/paypal/rest-api-sdk-php/sample/payments/CreatePayment.php

The link is borken, and tried creating a credit card with a 'first.php' (using my client id and key) and that seemed to work fine:
http://beta.cuddlecompanions.org/paypal/first.php

Any help in getting past this would be appreciated!

Thankyou!

**Comment by moazam1** [comment]
Getting same error.

**Comment by pp-randy** [comment]
Can you both try generating a new test card number using STEP 4 of this FAQ? https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1413

**Comment by moazam1** [comment]
Tried but didn't work:

`(
    [name] => INTERNAL_SERVICE_ERROR
    [message] => An internal service error has occurred
    [information_link] => https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR
    [debug_id] => c922fb564ca3c
)`

**Comment by djtetsu** [comment]
Solved!  I went into the sample folder, updated bootstrap.php with the client id and client secret.

**Comment by pp-randy** [comment]
@djtetsu thank you for following up.

@moazam1 if you are still having an issue please let me know.

**Comment by moazam1** [comment]
@pp-randy I still have trouble. Part of the API is working fine for me i.e. I used Payout and it worked but credit card is not working. See below the error:

`(
    [name] => INTERNAL_SERVICE_ERROR
    [message] => An internal service error has occurred
    [information_link] => https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR
    [debug_id] => 3761e63e4e746
)`

**Comment by pp-randy** [comment]
@moazam1 I will look further into this here: https://github.com/paypal/PayPal-PHP-SDK/issues/639
