### ISSUE TITLE
INTERNAL_SERVICE_ERROR

### ISSUE THREAD

**Issue by alritz05** [paypal/PayPal-PHP-SDK#637]
### Required Information

- PHP Version:
- PayPal-PHP-SDK Version: 
- Debug ID(s): 246e24f82616

### Issue Description
I have issue here, i created a billing plan before it was working and now not working in creating a billing plan.. any help?
screenshot:
http://screencast.com/t/Yor8St2vitIa

**Comment by eduknopfler** [comment]
Iḿ having exactly the same problem for the last 24 hours more or less, but I can create billing plans. My problem is I can't get any. Got response 500 all the time in a code that has been working fine for more than a week

**Comment by pp-randy** [comment]
Is this for PayPal funded Billing Plans in the sandbox? 

I am aware of a PayPal funded payment issue in sandbox (Internal Tracking PPPLMER-19298).

**Comment by eduknopfler** [comment]
Yesterday it started to work again. I guess it really was a Paypal problem and they solved it.

**Comment by pp-randy** [comment]
Thank you for the follow up @eduknopfler.  I apologize for the inconvenience.
