### ISSUE TITLE
Sandbox - 500 - credit_card as funding instrument

### ISSUE THREAD

**Issue by pp-randy** [paypal/PayPal-PHP-SDK#639]
Created from https://github.com/paypal/PayPal-PHP-SDK/issues/636#issuecomment-244954260
@pp-randy I still have trouble. Part of the API is working fine for me i.e. I used Payout and it worked but credit card is not working. See below the error:

( [name] => INTERNAL_SERVICE_ERROR [message] => An internal service error has occurred [information_link] => https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR [debug_id] => 3761e63e4e746 )

@moazam1 creating a new issue for tracking.

**Comment by moazam1** [comment]
Randy, do you need any more information?

**Comment by pp-randy** [comment]
Can you provide your request JSON?  I am getting an 500 error as well, but want to ensure I am reproducing your issue.

**Comment by moazam1** [comment]
`{"intent":"sale","payer":{"payment_method":"credit_card","funding_instruments":[{"credit_card":{"type":"visa","number":"4618912173232879","expire_month":"01","expire_year":"2021","cvv2":"123","first_name":"Joe","last_name":"Shopper"}}]},"transactions":[{"amount":{"currency":"USD","total":"20","details":{"shipping":"1.20","tax":"1.30","subtotal":"17.50"}},"item_list":{"items":[{"name":"Ground Coffee 40 oz","description":"Ground Coffee 40 oz","currency":"USD","quantity":1,"tax":"0.30","price":"7.50"},{"name":"Granola bars","description":"Granola Bars with Peanuts","currency":"USD","quantity":5,"tax":"0.20","price":"2"}]},"description":"Payment description","invoice_number":"57ced93c34dd0"}]}`

**Comment by pp-randy** [comment]
I am following up internally for further investigation (Internal Tracking: PPPLPAYPT-12463). 

In my testing the same card will work if using the payment_card object instead of credit_card object as the funding_instrument. 
```
{
	"intent" : "sale",
	"payer" : {
		"payment_method" : "credit_card",
		"funding_instruments" : [{
				"payment_card" : {
					"type" : "visa",
					"number" : "4618912173232879",
					"expire_month" : "01",
					"expire_year" : "2021",
					"cvv2" : "123",
					"first_name" : "Joe",
					"last_name" : "Shopper",
					"billing_country" : "US"
				}
			}
		]
	},
	"transactions" : [{
			"amount" : {
				"currency" : "USD",
				"total" : "20",
				"details" : {
					"shipping" : "1.20",
					"tax" : "1.30",
					"subtotal" : "17.50"
				}
			},
			"item_list" : {
				"items" : [{
						"name" : "Ground Coffee 40 oz",
						"description" : "Ground Coffee 40 oz",
						"currency" : "USD",
						"quantity" : 1,
						"tax" : "0.30",
						"price" : "7.50"
					}, {
						"name" : "Granola bars",
						"description" : "Granola Bars with Peanuts",
						"currency" : "USD",
						"quantity" : 5,
						"tax" : "0.20",
						"price" : "2"
					}
				]
			},
			"description" : "Payment description",
			"invoice_number" : "57ced93c34dd0"
		}
	]
}
```

**Comment by pp-randy** [comment]
I guess the question is now @moazam1 does the above request work for you?

**Comment by moazam1** [comment]
That worked but now I am using a deprecated method setPaymentCard: 

```
/**
     * Payment Card information.
     *
     * @deprecated Not publicly available
     * @param \PayPal\Api\PaymentCard $payment_card
     *
     * @return $this
     */
```

**Comment by pp-randy** [comment]
@moazam1 thank you for confirming.  I am working to get more clarity since there is some conflicting information here. 

https://developer.paypal.com/docs/api/payments/#definition-funding_instrument
![image](https://cloud.githubusercontent.com/assets/6819909/18280342/5d399518-741e-11e6-8bc5-ab424ccf2ded.png)

**Comment by moazam1** [comment]
Strange, I am using latest version of Paypal API. Randy, that's why I recommend not listening music loud. Seems like developer did opposite. Hope you guys will fix this information.

**Comment by pp-randy** [comment]
New Internal Tracking: PPPLPAYPT-12535

**Comment by rbur0425** [comment]
#640

**Comment by pp-randy** [comment]
Credit Card object is supported in Sandbox again and the 500 error caused by it appears to be resolved.
