### ISSUE TITLE
Parameter ’Custom‘ can not be found in REST PHP SDK

### ISSUE THREAD

**Issue by tony0121** [paypal/PayPal-PHP-SDK#641]
### Required Information

- PHP Version: 5.5.9
- PayPal-PHP-SDK Version: ALL
- Debug ID(s):

### Issue Description
> How to use parameter 'Custom' under 'Transation' object,? I could not find the function to set this parameter in SDK.

**Comment by jaypatel512** [comment]
Please make sure you are using the latest release:

```php
$transaction = new Transaction();
$transaction->setAmount($amount)
    ->setItemList($itemList)
    ->setCustom("Custom")
    ->setDescription("Payment description")
```
