### ISSUE TITLE
Create a single payout without using mass payments

### ISSUE THREAD

**Issue by avramovic** [paypal/PayPal-PHP-SDK#642]
### Required Information

- PHP Version: 5.6
- PayPal-PHP-SDK Version: 1.7.4
- Debug ID(s): none

### Issue Description

I'm trying to programmatically make a payment from my PayPal account to certain user of my website so I have installed the SDK and set it up using client ID and secret and it all works fine. I have used this example as a reference: https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payouts/CreateSinglePayout.php

It all works fine in my sandbox, the payment is processed, but it creates "mass payment" even for a single-user payments, and when I log in into my PayPal sandbox merchant account I see only mass payment and can't see who is the recipient of the payment unless I do a manual search for the recipient e-mail address - then I can see the payment and their account details.

You can see some screenshots here: http://imgur.com/a/D6Nxe

By comparing *sample/payouts/CreateSinglePayout.php* and *sample/payouts/CreateBatchPayout.php* I see that both of them are creating batch payment (**\PayPal\Api\PayoutSenderBatchHeader**) and for single payout it adds only one **\PayPal\Api\PayoutItem** while for the batch payout it adds three payout items (in your example).

So my question is - is it possible to make a "regular" payment using your SDK, without using mass (batch) payments? Am I looking at the correct examples?

**Comment by pp-randy** [comment]
@avramovic Payouts use Mass Payments, this is described a bit more here: 
https://developer.paypal.com/docs/integration/direct/payouts/
> Note: Payouts are available everywhere that Mass Payments are available. Any payouts that you send through the Payouts API appear as Mass Payments in your PayPal account and in Mass Payment reports.

If its about wanting the Payout Status you can try the Synchronous payout mode:
![image](https://cloud.githubusercontent.com/assets/6819909/18478987/e21b882a-7998-11e6-9ffb-e770c5836529.png)

Adaptive Payments would support this but I would not encourage them for a new integration at this time. 
https://github.com/paypal/adaptivepayments-sdk-php

**Comment by avramovic** [comment]
@pp-randy Thank you for you answer, that clears things a little bit. So basically we have to use mass payments. That's ok.
