### ISSUE TITLE
No webhook event fired when invoice paid/cancelled

### ISSUE THREAD

**Issue by cariboufute** [paypal/PayPal-PHP-SDK#645]
### Required Information

- PHP Version: 7.0.3-5+deb.sury.org~trusty+1
- PayPal-PHP-SDK Version: 1.7.4
- Debug ID(s): none

### Issue Description

I created a webhook for all invoices so whenever an invoice is paid or cancelled, it fires an event to  a URL with POST method, as described in the docs. However, I receive no event at all when I cancel an invoice by the API, nor by the PayPal invoice URL itself.

I tested the webhook URL on my API with the webhook simulator and it works. it looks like the problem is that there is no event fired at all.

I first create a webhook for all invoices paid or cancelled
```
$apiContext = new ApiContext(
    new OAuthTokenCredential(
        'PAYPAL_CLIENT_ID',       //replaced by real ID in code
        'PAYPAL_CLIENT_SECRET'    //replaced by real ID in code
    )
);

$apiContext->setConfig(['mode' => env('PAYPAL_MODE', 'sandbox')]);

$webhook = new \PayPal\Api\Webhook;
$url = 'https://XXX.XXX/api/license/mix-add-on/invoice/webhook';  //re

$webhook->setUrl($url);
$webhook->setEventTypes([
    $this->makeInvoicePaidWebhookEvent(),
    $this->makeInvoiceCancelledWebhookEvent(),
]);

$webhook->create($apiContext);
```

Then I create the invoice with the PayPal PHP SDK.

Now, I cancelled it following the URL from the PayPal email, or I cancel it using the PayPal API (PHP SDK).

In both cases, I don't receive any event in my API.

Here is the code of the endpoint in my API. It includes the 503 error workaround described in the SDK Wiki. (It is a Laravel/Dingo API app, I include the subclass method code in it).

```
public function invoiceWebhook(Request $request)
{
    try {
        $event = \PayPal\Api\WebhookEvent::validateAndGetReceivedEvent($request->getContent(), $apiContext);    //$request->getContent() returns the whole JSON content of request in Laravel.

        //code to treat event...

    } catch (InvalidArgumentException $ex) {
        return $this->response->error('Service unavailable', 503)->withHeader('Retry-After', 15); //returns an HTTP response with code 503 and "Retry-After: 15" header
    } catch (Exception $e) {
        Log::error("Error in " . $e->getFile() . ", line " . $e->getLine() . ": " . $e->getMessage() . "\n" . $e->getTrace());
    }

    return $this->response->noContent();   //returns an HTTP response with code 204 (No Content)
}
```

**Comment by cariboufute** [comment]
I tried also for INVOICING.INVOICE.PAID event by doing the whole process of invoice payment. I am using the sandbox environment.

- My app creates an invoice and sends it to the client.
- The client checks the invoice and pays it.
- Once the PayPal API sends the API event, my app validates it and marks the invoice as paid in our databases.

The same problem still occurs : no event is fired when invoice is paid or cancelled.

**Comment by cariboufute** [comment]
P.S. : Now I am using PayPal-PHP-SDK Version: 1.8.0

**Comment by cariboufute** [comment]
Also, I tested a webhook reacting to all events. It receives PAYMENT.SALE.COMPLETED events when payment is completed. It receives none of invoice events when invoice is paid.

**Comment by bluk** [comment]
Hi, thanks for reporting the issue. I've opened PPPLMER-21843 to track this internally.

**Comment by bluk** [comment]
Invoicing web hooks should now be sent. If you still encounter an issue with this, please leave a comment or open a new issue. Thanks.

**Comment by cariboufute** [comment]
Thanks, now I receive invoice webhook events, but can't verify their signature, so the events are sent again and again. Please check the new issue : https://github.com/paypal/PayPal-PHP-SDK/issues/704
