### ISSUE TITLE
paypal return wrong approval url

### ISSUE THREAD

**Issue by playwolf719** [paypal/PayPal-PHP-SDK#650]
### Required Information

- PHP Version: 5.4
- PayPal-PHP-SDK Version: 1.7.3
- Debug ID(s):

### Issue Description
> paypal return wrong approval url (I'm from China)

![image](https://cloud.githubusercontent.com/assets/6240382/18659586/1cebc91a-7f3e-11e6-9e3f-66444fedfa7a.png)

**Yesterday the url is ok with "sandbox", but today it's not. Please help me.**

**Comment by ashishdots** [comment]
Same here....frustrated...
Please, anybody have solution regarding that...
It was working fine yesterday..

**Comment by thusitha92** [comment]
I'm also getting this error.
Yesterday it was work fine and today I'm getting a PayPal URL instead of a sandbox URL.
This needs to be fixed ASAP.

**Comment by playwolf719** [comment]
@jaypatel512 Anyone here to solve the problem? Our website is in a hurry!

**Comment by ashishdots** [comment]
All the developers are facing same issue out there :
http://stackoverflow.com/questions/39583509/this-transaction-is-invalid-paypal-php-sdk

Issue is still there...:(

**Comment by petrogad** [comment]
Same here. If someone sees this working could they update it?

I tried placing sandbox in front of my url, however that did not seem to be working either.

Thanks!

**Comment by drummingdemon** [comment]
Same here, sandbox stopped working a few hours ago...any update on a fix or workaround?

**Comment by playwolf719** [comment]
@petrogad The change does't work, the only way is to wait? OMG

**Comment by petrogad** [comment]
agreed :)

**Comment by Verokster** [comment]
Same thing )))

**Comment by bluk** [comment]
Thank you all for reporting this sandbox issue. We have an internal ticket PPPLMER-20280 to track this, and teams are working on a solution. We will report back when this issue is fixed.

**Comment by lyhoanglong** [comment]
me too, still waiting :(

**Comment by lyhoanglong** [comment]
paypal is back 💃

**Comment by ashishdots** [comment]
:) its working fine again...

**Comment by amilabasnayakafree** [comment]
Its working fine.

**Comment by pp-randy** [comment]
Thank you for your patience and to those of you able to confirm it is resolved now.

**Comment by tseval** [comment]
I got this problem again now. I have made no code changes in my end, but all of a sudden it redirects to the live site instead of the sandbox.

**Comment by saschanos** [comment]
Same for me. Can you please fix this?

**Comment by bluk** [comment]
SRE-43159 has been opened to track this re-occurance. Thank you for the report.

**Comment by bluk** [comment]
This issue should be resolved again. Apologizes for the issue.

**Comment by Styopchik** [comment]
still having problems

**Comment by jaypatel512** [comment]
Hey @Styopchik !

We are not able to reproduce this anymore. We are successfully getting sandbox approval urls.

**Comment by Styopchik** [comment]
"links": [
        {
            "href": "https://api.sandbox.paypal.com/v1/payments/payment/PAY-8B948234AP549115FK7UT3YQ",
            "rel": "self",
            "method": "GET"
        },
        {
            "href": "https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-5B012565SP4283102",
            "rel": "approval_url",
            "method": "REDIRECT"
        },
        {
            "href": "https://api.sandbox.paypal.com/v1/payments/payment/PAY-8B948234AP549115FK7UT3YQ/execute",
            "rel": "execute",
            "method": "POST"
        }
    ]

**Comment by jaypatel512** [comment]
The above link looks correct. It is pointing to sandbox correctly.
