### ISSUE TITLE
We hook billing agreement cancel dates

### ISSUE THREAD

**Issue by mbuk** [paypal/PayPal-PHP-SDK#651]
### Required Information

- PHP Version: 7
- PayPal-PHP-SDK Version: latest

### Issue Description
I contacted PayPal merchant integration for support but they were useless (as expected). I was asking about webhooks and I get and answer about the IPN.....

I want to understand if the webhook system can be used when a billing agreement is cancelled to determine when an entitlement expires.

For example:

John has an annual subscription.
He signed up on January the 1st 2016
He cancels on January 2nd 2016

Because he's on an annual plan he has effectively prepaid for 12 months of service.
Does the webhook have any information I can use to work out when the account would have been billed again - ie the last last day of an entitlement.

**Comment by bluk** [comment]
Sorry for the late response. The `agreement_details` is probably the most relevant info:

```
		"agreement_details": {
			"outstanding_balance": {
				"value": "0.00"
			},
			"num_cycles_remaining": "5",
			"num_cycles_completed": "0",
			"last_payment_date": "2016-04-28T11:29:54Z",
			"last_payment_amount": {
				"value": "1.00"
			},
			"final_payment_due_date": "2017-11-30T10:00:00Z",
			"failed_payment_count": "0"
		},
```

While you could use PayPal as the system of record, most integrators have their own subscription records in their data store. You can use the [webhook simulator](https://developer.paypal.com/developer/webhooksSimulator/) to see what data you could get.

If that doesn't answer your question, please leave a comment or open a new issue. Thanks.
