### ISSUE TITLE
UTF8 encoding in result response from sandbox, corrupts json response

### ISSUE THREAD

**Issue by bhoehl** [paypal/PayPal-PHP-SDK#656]
https://github.com/paypal/PayPal-PHP-SDK/pull/655

**Comment by jaypatel512** [comment]
Hey @bhoehl !

Thank for the PR and detailed explanation. I will add this to my tasks, as finish reviewing and testing your PR as soon as possible. 

I will close this issue as a duplicate, as we could directly review the PR. Thanks again @bhoehl for your help.
