### ISSUE TITLE
Large number of INVALID_BILLING_ADDRESS on Vault API repeat transactions

### ISSUE THREAD

**Issue by paultarr** [paypal/PayPal-PHP-SDK#658]
### Required Information

- PHP Version: 5.4.16
- PayPal-PHP-SDK Version: 1.6.4
- Debug ID(s):

Large number of transactions billed via Vault API repeat card transactions have been returning INVALID_BILLING_ADDRESS from this morning.

Example debug_ids:

31107994c026
97593b9a45c18
22237fd26dbd9
ce676fcb620ac
870e0b9f6b9fd
be7544c3261b8
7851216b2fefe
ec940876cc1f4
147a116ebba22

**Comment by bluk** [comment]
@paultarr Since these are live transactions, please contact [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/app/ask).
