### ISSUE TITLE
Fatal error in running a sample script

### ISSUE THREAD

**Issue by Richard2012** [paypal/PayPal-PHP-SDK#666]
### Required Information

- PHP Version:  5.3.29
- PayPal-PHP-SDK Version: 1.8.0
- Debug ID(s): ?

### Issue Description
Whern running a sample script 
/PayPal-PHP-SDK/paypal/rest-api-sdk-php/sample/payments/CreatePaymentUsingPayPal.php

I am getting this output (first garbage and then):
(€½ù¹ZÉº 
Warning: Invalid argument supplied for foreach() in /PayPal-PHP-SDK/composer/autoload_real.php
Fatal error: Class 'Psr\Log\AbstractLogger' not found in /PayPal-PHP-SDK/paypal/rest-api-sdk-php/lib/PayPal/Log/PayPalLogger.php on line 10

I digged into the code in the script
/PayPal-PHP-SDK/composer/autoload_psr4.php
and have changed the line 
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
into
    'Psr\\Log\\' => $vendorDir . '/psr/log/Psr/Log',

and the error does not pop up any more, but I don't think I should be doing this.

**Comment by jaypatel512** [comment]
You need to follow the instructions to either use Composer, or Direct download provided in each release. Please follow [instructions here](https://github.com/paypal/PayPal-PHP-SDK/wiki/Installation). We do recommend using `composer`.
