### ISSUE TITLE
Class 'PayPal\Api\JsonValidator' not found  in PayPal/Api/WebhookEvent.php:212

### ISSUE THREAD

**Issue by mdrost** [paypal/PayPal-PHP-SDK#667]
### Required Information

- PHP Version: PHP 7.0.8-0ubuntu0.16.04.2 (cli) ( NTS )
- PayPal-PHP-SDK Version: 1.8.0
- Debug ID(s):

### Issue Description
> Commit af4648bdfdd85b1b2bd2be576bcf757077c3aa59 removed `use PayPal/Validation/JsonValidator;` from `PayPal/Api/WebhookEvent.php`, but it is still in use.

**Comment by jaypatel512** [comment]
Thanks for pointing that out. Fixed it. Should be available in next release.
