### ISSUE TITLE
The same script returns token in console but throws exception in browser

### ISSUE THREAD

**Issue by Richard2012** [paypal/PayPal-PHP-SDK#671]
### Required Information

- PHP Version: 5.4
- PayPal-PHP-SDK Version: 1.8.0
- cURL Version: 7.19.7
- Debug ID(s): ?

### Issue Description
The same script (shown below with ids blurred) returns a valid token in console, but generates PayPalConnectionException "Could not generate new Access token. Invalid response from server" when run in browser.

Yes we did run the https://tlstest.paypal.com/ tests with cacert.pem file and the result was OK  both in the console and in browser. 

```
<?php // real IDs and paths replaced here. They were not the problem
require  $myServerPath .'/vendor/autoload.php';

$apiContext = new \PayPal\Rest\ApiContext( new \PayPal\Auth\OAuthTokenCredential(
        $clientID, $clientSecret)
);

use PayPal\Api\Amount;
use PayPal\Api\Payer;
use PayPal\Api\Payment;
use PayPal\Api\RedirectUrls;
use PayPal\Api\Transaction;

$payer = new Payer();
$payer->setPaymentMethod("paypal");

$amount = new Amount();
$amount->setCurrency("EUR")->setTotal(31.10);

$transaction = new Transaction();
$transaction->setAmount($amount)->setDescription("Payment for advice");

$baseUrl = $myServerURL;
$redirectUrls = new RedirectUrls();
$redirectUrls->setReturnUrl($baseUrl . "fourth.php?ppok=true")
    ->setCancelUrl($baseUrl . "fourth?ppok=false");

$payment = new Payment();
$payment->setIntent("sale")
    ->setPayer($payer)
    ->setRedirectUrls($redirectUrls)
    ->setTransactions(array($transaction));

try {
    $payment->create($apiContext);
} catch (Exception $ex) {
    var_dump( $ex) ;
    exit(1);
}

$approvalUrl = $payment->getApprovalLink();
echo $approvalUrl;
```

**Comment by bluk** [comment]
Hi, can you please enable logging and see if you can get the response from the server? Please see the [logging configuration wiki page](https://github.com/paypal/PayPal-PHP-SDK/wiki/Logging).

**Comment by Richard2012** [comment]
Thank you Bryant

 

Here is the complete exception object:


 

 

PayPal\Exception\PayPalConnectionException Object
(
    [url:PayPal\Exception\PayPalConnectionException:private] => 
    [data:PayPal\Exception\PayPalConnectionException:private] => 
    [message:protected] => Could not generate new Access token. Invalid response from server: 
    [string:Exception:private] => 
    [code:protected] => 0
    [file:protected] => /classes/vendor/paypal/rest-api-sdk-php/lib/PayPal/Auth/OAuthTokenCredential.php
    [line:protected] => 272
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /classes/vendor/paypal/rest-api-sdk-php/lib/PayPal/Auth/OAuthTokenCredential.php
                    [line] => 210
                    [function] => generateAccessToken
                    [class] => PayPal\Auth\OAuthTokenCredential
                    [type] => ->
                    [args] => Array
                        (
                            [0] => Array
                                (
                                    [log.LogEnabled] => 1
                                    [log.FileName] => PayPal.log
                                    [log.LogLevel] => DEBUG
                                )

                            [1] => 
                        )

                )

            [1] => Array
                (
                    [file] => /classes/vendor/paypal/rest-api-sdk-php/lib/PayPal/Auth/OAuthTokenCredential.php
                    [line] => 160
                    [function] => updateAccessToken
                    [class] => PayPal\Auth\OAuthTokenCredential
                    [type] => ->
                    [args] => Array
                        (
                            [0] => Array
                                (
                                    [log.LogEnabled] => 1
                                    [log.FileName] => PayPal.log
                                    [log.LogLevel] => DEBUG
                                )

                        )

                )

            [2] => Array
                (
                    [file] => /classes/vendor/paypal/rest-api-sdk-php/lib/PayPal/Handler/RestHandler.php
                    [line] => 82
                    [function] => getAccessToken
                    [class] => PayPal\Auth\OAuthTokenCredential
                    [type] => ->
                    [args] => Array
                        (
                            [0] => Array
                                (
                                    [log.LogEnabled] => 1
                                    [log.FileName] => PayPal.log
                                    [log.LogLevel] => DEBUG
                                )

                        )

                )

            [3] => Array
                (
                    [file] => /classes/vendor/paypal/rest-api-sdk-php/lib/PayPal/Transport/PayPalRestCall.php
                    [line] => 70
                    [function] => handle
                    [class] => PayPal\Handler\RestHandler
                    [type] => ->
                    [args] => Array
                        (
                            [0] => PayPal\Core\PayPalHttpConfig Object
                                (
                                    [headers:PayPal\Core\PayPalHttpConfig:private] => Array
                                        (
                                            [Content-Type] => application/json
                                            [Expect] => 
                                            [User-Agent] => PayPalSDK/PayPal-PHP-SDK 1.8.0 (platform-ver=5.3.29; bit=64; os=Linux_3.12.41-77.ELK6.x86_64; machine=x86_64; crypto-lib-ver=1.0.1e-fips; curl=7.19.7)
                                        )

                                    [curlOptions:PayPal\Core\PayPalHttpConfig:private] => Array
                                        (
                                            [32] => 6
                                            [78] => 10
                                            [19913] => 1
                                            [13] => 60
                                            [10018] => PayPal-PHP-SDK
                                            [10023] => Array
                                                (
                                                )

                                            [81] => 2
                                            [64] => 1
                                        )

                                    [url:PayPal\Core\PayPalHttpConfig:private] => https://api.sandbox.paypal.com/v1/payments/payment
                                    [method:PayPal\Core\PayPalHttpConfig:private] => POST
                                    [retryCount:PayPal\Core\PayPalHttpConfig:private] => 0
                                )

                            [1] => {"intent":"sale","payer":{"payment_method":"paypal"},"redirect_urls":{"return_url":"http://www.caribation.com/classes/third.php?ppok=true","cancel_url":"http://www.caribation.com/classes/third.php?ppok=false"},"transactions":[{"amount":{"currency":"EUR","total":"31.10"},"description":"Anzahlung fuer Casa Reservierung"}]}
                            [2] => Array
                                (
                                    [path] => /v1/payments/payment
                                    [apiContext] => PayPal\Rest\ApiContext Object
                                        (
                                            [requestId:PayPal\Rest\ApiContext:private] => 
                                            [credential:PayPal\Rest\ApiContext:private] => PayPal\Auth\OAuthTokenCredential Object
                                                (
                                                    [clientId:PayPal\Auth\OAuthTokenCredential:private] => AYZd-OQhc7PEm6sG3tSiW4QlHLno7gh15xIfHrNSZ-XgpOxnzrG7YYYSP6gDIawoUOZxFRXp8Wa2SRZF
                                                    [clientSecret:PayPal\Auth\OAuthTokenCredential:private] => EHefg1gAogFPvn92xxxxxxxxxxxAr5grJD127lOa63806RR22wqaswxUqZ36EkhhHF_S04G9YPHYno3
                                                    [accessToken:PayPal\Auth\OAuthTokenCredential:private] => 
                                                    [tokenExpiresIn:PayPal\Auth\OAuthTokenCredential:private] => 
                                                    [tokenCreateTime:PayPal\Auth\OAuthTokenCredential:private] => 
                                                    [cipher:PayPal\Auth\OAuthTokenCredential:private] => PayPal\Security\Cipher Object
                                                        (
                                                            [secretKey:PayPal\Security\Cipher:private] => EHefg1gAogFPvn92eeeeeeeeeeeeeer5grJD127lOa63806RR22wqaswxUqZ36EkhhHF_S04G9YPHYno3
                                                        )

                                                    [_propMap:PayPal\Common\PayPalModel:private] => Array
                                                        (
                                                        )

                                                )

                                        )

                                )

                        )

                )

            [4] => Array
                (
                    [file] => /classes/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PayPalResourceModel.php
                    [line] => 102
                    [function] => execute
                    [class] => PayPal\Transport\PayPalRestCall
                    [type] => ->
                    [args] => Array
                        (
                            [0] => Array
                                (
                                    [0] => PayPal\Handler\RestHandler
                                )

                            [1] => /v1/payments/payment
                            [2] => POST
                            [3] => {"intent":"sale","payer":{"payment_method":"paypal"},"redirect_urls":{"return_url":"http://www.caribation.com/classes/third.php?ppok=true","cancel_url":"http://www.caribation.com/classes/third.php?ppok=false"},"transactions":[{"amount":{"currency":"EUR","total":"31.10"},"description":"Anzahlung fuer Casa Reservierung"}]}
                            [4] => 
                        )

                )

            [5] => Array
                (
                    [file] => /classes/vendor/paypal/rest-api-sdk-php/lib/PayPal/Api/Payment.php
                    [line] => 579
                    [function] => executeCall
                    [class] => PayPal\Common\PayPalResourceModel
                    [type] => ::
                    [args] => Array
                        (
                            [0] => /v1/payments/payment
                            [1] => POST
                            [2] => {"intent":"sale","payer":{"payment_method":"paypal"},"redirect_urls":{"return_url":"http://www.caribation.com/classes/third.php?ppok=true","cancel_url":"http://www.caribation.com/classes/third.php?ppok=false"},"transactions":[{"amount":{"currency":"EUR","total":"31.10"},"description":"Anzahlung fuer Casa Reservierung"}]}
                            [3] => 
                            [4] => PayPal\Rest\ApiContext Object
                                (
                                    [requestId:PayPal\Rest\ApiContext:private] => 
                                    [credential:PayPal\Rest\ApiContext:private] => PayPal\Auth\OAuthTokenCredential Object
                                        (
                                            [clientId:PayPal\Auth\OAuthTokenCredential:private] => AYZd-OQhc7PEm6sG3tSiW4QlHLno7gh15xIfHrNSZ-XgpOxnzrG7YYYSP6gDIawoUOZxFRXp8Wa2SRZF
                                            [clientSecret:PayPal\Auth\OAuthTokenCredential:private] => EHefg1gAogFPvn92ZtttttttttxVAr5grJD127lOa63806RR22wqaswxUqZ36EkhhHF_S04G9YPHYno3
                                            [accessToken:PayPal\Auth\OAuthTokenCredential:private] => 
                                            [tokenExpiresIn:PayPal\Auth\OAuthTokenCredential:private] => 
                                            [tokenCreateTime:PayPal\Auth\OAuthTokenCredential:private] => 
                                            [cipher:PayPal\Auth\OAuthTokenCredential:private] => PayPal\Security\Cipher Object
                                                (
                                                    [secretKey:PayPal\Security\Cipher:private] => EHefg1gAogFPvn92hhhhhhhhhh5grJD127lOa63806RR22wqaswxUqZ36EkhhHF_S04G9YPHYno3
                                                )

                                            [_propMap:PayPal\Common\PayPalModel:private] => Array
                                                (
                                                )

                                        )

                                )

                            [5] => 
                        )

                )

            [6] => Array
                (
                    [file] => /caribation.com/general/third.php
                    [line] => 100
                    [function] => create
                    [class] => PayPal\Api\Payment
                    [type] => ->
                    [args] => Array
                        (
                            [0] => PayPal\Rest\ApiContext Object
                                (
                                    [requestId:PayPal\Rest\ApiContext:private] => 
                                    [credential:PayPal\Rest\ApiContext:private] => PayPal\Auth\OAuthTokenCredential Object
                                        (
                                            [clientId:PayPal\Auth\OAuthTokenCredential:private] => AYZd-OQhc7PEm6sG3tSiW4QlHLno7gh15xIfHrNSZ-XgpOxnzrG7YYYSP6gDIawoUOZxFRXp8Wa2SRZF
                                            [clientSecret:PayPal\Auth\OAuthTokenCredential:private] => EHefg1gAogFPvn92qqqqqqqqqAr5grJD127lOa63806RR22wqaswxUqZ36EkhhHF_S04G9YPHYno3
                                            [accessToken:PayPal\Auth\OAuthTokenCredential:private] => 
                                            [tokenExpiresIn:PayPal\Auth\OAuthTokenCredential:private] => 
                                            [tokenCreateTime:PayPal\Auth\OAuthTokenCredential:private] => 
                                            [cipher:PayPal\Auth\OAuthTokenCredential:private] => PayPal\Security\Cipher Object
                                                (
                                                    [secretKey:PayPal\Security\Cipher:private] => EHefg1gAogFPvn92Zcccccccccc5grJD127lOa63806RR22wqaswxUqZ36EkhhHF_S04G9YPHYno3
                                                )

                                            [_propMap:PayPal\Common\PayPalModel:private] => Array
                                                (
                                                )

                                        )

                                )

                        )

                )

        )

    [previous:Exception:private] => 
)


 

Gesendet: Freitag, 07. Oktober 2016 um 11:30 Uhr
Von: "Bryant Luk" <notifications@github.com>
An: paypal/PayPal-PHP-SDK <PayPal-PHP-SDK@noreply.github.com>
Cc: "Caribation Labs" <iteam@gmx.com>, Author <author@noreply.github.com>
Betreff: Re: [paypal/PayPal-PHP-SDK] The same script returns token in console but throws exception in browser (#671)


Hi, can you please enable logging and see if you can get the response from the server? Please see the logging configuration wiki page.

**Comment by bluk** [comment]
@Richard2012 I edited your response to remove some information. The client ID / secret you were using is not correct, so I would double-check that credentials match in the Developer Dashboard or if you are using different credentials in the console. I suggest disabling your old client secret in the [PayPal Developer Dashboard](https://developer.paypal.com/developer/applications/) and generating a new one.

**Comment by Richard2012** [comment]
Thanks again Bryant,
my credentials are correct and I can prove it on curl, which returns me the access_token:

```
$ch = curl_init("https://api.sandbox.paypal.com/v1/oauth2/token");
curl_setopt($ch, CURLOPT_HEADER, "Accept: application/json");
curl_setopt($ch, CURLOPT_USERPWD, "$clientId:$clientSecret");
curl_setopt($ch, CURLOPT_POSTFIELDS, "grant_type=client_credentials");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
$result = curl_exec($ch);
curl_close($ch);
```
Also, my script returns the correct payment object, if I run it in the console.
It only fails in browser (any browser). Any ideas?

**Comment by bluk** [comment]
https://github.com/paypal/PayPal-PHP-SDK/issues/673 seems to be related but I did try your pasted client ID and secret earlier in a HTTP client and got a 401 back. Can you try that patch out and see if it works?

**Comment by Richard2012** [comment]
OK, will try

The keys I have posted were blurred by me on purpose.

Thanks

 

 

Gesendet: Freitag, 07. Oktober 2016 um 21:01 Uhr
Von: "Bryant Luk" <notifications@github.com>
An: paypal/PayPal-PHP-SDK <PayPal-PHP-SDK@noreply.github.com>
Cc: "Caribation Labs" <iteam@gmx.com>, Mention <mention@noreply.github.com>
Betreff: Re: [paypal/PayPal-PHP-SDK] The same script returns token in console but throws exception in browser (#671)


#673 seems to be related but I did try your pasted client ID and secret earlier in a HTTP client and got a 401 back. Can you try that patch out and see if it works?

**Comment by bluk** [comment]
I'll close this for now since #673 seems to have ideas for a fix. If you still have issues after trying the fixes, please leave a comment, and we'll reopen. Thanks.

**Comment by Richard2012** [comment]
Thank you for your time

I have also closed the SDK and work with curl directly now

 

 

 

 

Gesendet: Montag, 10. Oktober 2016 um 12:15 Uhr
Von: "Bryant Luk" <notifications@github.com>
An: paypal/PayPal-PHP-SDK <PayPal-PHP-SDK@noreply.github.com>
Cc: "Caribation Labs" <iteam@gmx.com>, Mention <mention@noreply.github.com>
Betreff: Re: [paypal/PayPal-PHP-SDK] The same script returns token in console but throws exception in browser (#671)


I'll close this for now since #673 seems to have ideas for a fix. If you still have issues after trying the fixes, please leave a comment, and we'll reopen. Thanks.
