### ISSUE TITLE
Billing Agreeements cannot override the amount of the payment definition

### ISSUE THREAD

**Issue by benjaminpick** [paypal/PayPal-PHP-SDK#672]
After some investigation, I realized that `override_charge_models` actually does what is says: it can only override the *charges* (shipping or taxes) of the corresponding Billing Plan. 

What I want is to override the actual amount of the subscription. The use case being: users can decide to donate a regular amount of money of their choice. So all the other details remain the same (hence the billing Plan) but the amount varies from user to user.

So does this mean I have to create a new billing plan for each user? Is there a maximum limit of Plans that I can create?

**Comment by bluk** [comment]
I believe you would have to create a new billing plan for each user. As far as a maximum limit of billing plans, I am not sure there is one (there may be some limits to stop abuse). Your best bet is to contact [PayPal Technical Support](https://www.paypal-techsupport.com) at the bottom of the page with the Contact Us link.

**Comment by puremana** [comment]
For future reference, Paypal has confirmed there is no limit to billing plans you can create. If possible, I would urge you to reconsider this though as at least in my case it was taking 10+ seconds per plan to be created.

For this reason we have resorted to do manual refunds.
