### ISSUE TITLE
Paypal 500 code error. URGENT .......

### ISSUE THREAD

**Issue by chinwei3889** [paypal/PayPal-PHP-SDK#676]
### Required Information

- PHP Version:7.0.6
- PayPal-PHP-SDK Version:1.8.0
- Debug ID(s):7e15b171e63de

### Issue Description
[07-10-2016 05:39:07] PayPal\Core\PayPalHttpConnection : ERROR: Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment/PAY-1GJ223100J952125MK734DDQ/execute. {"name":"INTERNAL_SERVICE_ERROR","details":[],"message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"7e15b171e63de"}

today 3pm still can get success payment but after 6pm direct become code 500 error.
what id the problem?
![z](https://cloud.githubusercontent.com/assets/10541134/19196735/45d5ca52-8ce9-11e6-95bc-2aef9148aea5.png)

**Comment by bluk** [comment]
Internal issue PPPLMER-21356 is being used to track this. Sorry for the inconvenience.

**Comment by chinwei3889** [comment]
so we need wait for maintenance is it?

**Comment by bluk** [comment]
@chinwei3889 Yes, there are teams currently working and fixing the issue. I don't have an ETA unfortunately.

**Comment by chinwei3889** [comment]
ok, thanks Bluk  :D

**Comment by mcastroascencio** [comment]
any update? :(

**Comment by bluk** [comment]
@mcastroascencio Teams are still working towards a resolution. Either I or someone from PayPal will update this issue when this is resolved. Thanks for your patience.

**Comment by bldmadrid** [comment]
Also happening from Android Mobile SDK.
{"name":"INTERNAL_SERVICE_ERROR","debug_id":"be87c248c0ded","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR"}

**Comment by kdubious** [comment]
.NET SDK, too.

**Comment by bluk** [comment]
This should be fixed now. I was able to execute a payment earlier. If you're still encountering an issue, please open a new issue with a `PayPal-Debug-ID` if possible. Thanks for your patience and our apologies for the issue.

**Comment by niteshsirohi1** [comment]
I am facing the same issue, please help
request failure with http statusCode:500,exception:Internal Server Error
request failed with server response:{"name":"INTERNAL_SERVICE_ERROR","debug_id":"e4566ebdc0a80","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR"}

**Comment by bluk** [comment]
@niteshsirohi1 Looking at your debug-id, this is the same issue as https://github.com/paypal/PayPal-PHP-SDK/issues/678 . Product development teams are actively working towards a resolution. Please check that issue for status updates.
