### ISSUE TITLE
Response 500 on creating WebProfile

### ISSUE THREAD

**Issue by stvveb** [paypal/PayPal-PHP-SDK#678]
### Required Information

- PHP Version: 7.0.6
- PayPal-PHP-SDK Version: 1.8.0
- Debug ID(s): c6d80d6e1ffc8

### Issue Description

I'am trying to create WebProfile. The code bellow worked for me for the last 8 days, and since today it returns response 500.

code:
`      

      $flowConfig = new \PayPal\Api\FlowConfig();       
      $flowConfig->setLandingPageType("Billing");       
      $flowConfig->setBankTxnPendingUrl($this->referer);
      $presentation = new \PayPal\Api\Presentation();
      $inputFields = new \PayPal\Api\InputFields();    
      $inputFields->setAllowNote(false)
            ->setNoShipping(1)
            ->setAddressOverride(0);
      $webProfile = new \PayPal\Api\WebProfile();
      $webProfile->setName(uniqid())
                    ->setFlowConfig($flowConfig)
                    ->setPresentation($presentation)
                    ->setInputFields($inputFields);
        try {
             $createProfileResponse = $webProfile->create($this->apiContext);
             $createProfileResponse = json_decode($createProfileResponse);
             $web_profile_id = $createProfileResponse->id;                
             return $web_profile_id;         
        } catch (\PayPal\Exception\PayPalConnectionException $ex) {
            return FALSE;
        }     
  `
 I've tryed [this](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payment-experience/CreateWebProfile.php) example and got same error. Creating end executing payments works perfectly, so the problem is only with the web profiles.

**Comment by stvveb** [comment]
log attached:
[log.txt](https://github.com/paypal/PayPal-PHP-SDK/files/517773/log.txt)

**Comment by ahmad-saad** [comment]
I have the same Problem and I think it is a problem in Paypal server side.

and it started yestarday, and I report a bug in Paypal support system.

**Comment by cyclux** [comment]
Same here. Also reported on paypal MTS.

**Comment by carmelocatalfamo** [comment]
Same problem.. Today worked 5/6 times.
Now it returns response 500.

**Comment by ahmad-saad** [comment]
for me it works now.

I hope it continue to work.

Regard's

**Comment by pp-randy** [comment]
I'm aware of an issue during this time that appears related but should now be resolved.  Is anyone still seeing 500 errors if so can I get a PayPal debug-id from your API response?

Internal Tracking: SRE-43433

**Comment by stvveb** [comment]
Now it works.

**Comment by Flippsus** [comment]
I am still getting the 500 Error from as API response, when POSTing to 
https://api.sandbox.paypal.com/v1/payments/payment/.../execute
I am getting this in Sandbox Mode.
debug_id: 56b6cfe4ab32

**Comment by pp-randy** [comment]
@Flippsus, I'm taking a look.  Thank you for the debug_id.

**Comment by pp-randy** [comment]
@Flippsus since your issue is separate from this one I have started a new issue here: https://github.com/paypal/PayPal-PHP-SDK/issues/687

**Comment by Nicbyte** [comment]
I'm not sure if my issue I have is related, I'm testing the express checkout at the moment. I'm using Ajax as a test before tucking it the code server side. I can get an access token fine with my first request, second request to get the web experience profile id gives me Internal Server error 500.

**Comment by pp-randy** [comment]
I apologize the issue with web experience profiles has been reoccurring.  I am reopening the issue until a long term solution has been put in place.

Internal Tracking: PPPLPAYPT-13586

**Comment by bluk** [comment]
This issue was resolved, and we have not encountered this error for a while. If you encounter this issue, please open a new issue or leave a comment. Thanks for your patience.
