### ISSUE TITLE
Authorize Payment Sandbox Stopped Responding Issue

### ISSUE THREAD

**Issue by ashutosh-finelogics** [paypal/PayPal-PHP-SDK#679]
### Required Information

- PHP Version: > 5.5
- PayPal-PHP-SDK Version: Latest
- Debug ID(s):

### Issue Description
> Please include as many details (logs, steps to reproduce) as you can to help us reproduce this issue faster.

I am creating php server side to authorize payment using the sdk. I wrote the code on two testing servers (https://whealsformeal.com/paypal/testing  and http://lokhittrust.in/wfm/paypal/testing and  localhost/wfm/paypal/testing)... All were working fine since afternoon. But suddenly the https://www.sandbox.paypal.com/cgi-bin/webscr stopped responding and Iam getting a browser response wherein some misconfiguration or connection closed by host is coming up. Even if i try opening the https://sandbox.paypal.com , it isn't opening. Is the site down or I am doing some mistake.

**Comment by bluk** [comment]
Hello, I moved your title to the issue body to make it more readable.

You should try https://www.sandbox.paypal.com to browse the PayPal Sandbox Website. We have had a few sandbox issues recently, so can you please try again? If the issue persists, can you get a PayPal-Debug-ID for the API calls you are making with the SDK? Thanks!

**Comment by ashutosh-finelogics** [comment]
Thanks bluk... In sandbox seller account I changed the settings for accepting payment and it got to work.
Appreciate your zeal to help. Will get back in case some problem comes up.
Thanks once again
