### ISSUE TITLE
Pay with Paypal through Paypal REST API does not show up payment  amount on Paypal Sandbox or live sites

### ISSUE THREAD

**Issue by ghost** [paypal/PayPal-PHP-SDK#68]
In Order summery amount is not showing but description is showing

I am using below code to pass amount and description

require **DIR** . '/../bootstrap.php';
use PayPal\Api\Address;
use PayPal\Api\Amount;
use PayPal\Api\Payer;
use PayPal\Api\Payment;
use PayPal\Api\FundingInstrument;
use PayPal\Api\RedirectUrls;
use PayPal\Api\Transaction;

$charge = trim($_POST['amount']);
$currency = trim($_POST['currency']);
$desc = trim($_POST['desc']);
$get_url=trim($_SESSION['get_url']);

$payer = new Payer();
$payer->setPayment_method("paypal");

$amount = new Amount();
$amount->setCurrency($currency);
$amount->setTotal($charge);

$transaction = new Transaction();
$transaction->setAmount($amount);
$transaction->setDescription($desc);

$baseUrl = getBaseUrl();
$redirectUrls = new RedirectUrls();
$redirectUrls->setReturn_url("http://$get_url/includes/rest-api-sdk-php-master/sample/payments/ExecutePayment.php?success=true");
$redirectUrls->setCancel_url("http://$get_url/includes/rest-api-sdk-php-master/sample/payments/ExecutePayment.php?success=false");

$payment = new Payment();
$payment->setIntent("sale");
$payment->setPayer($payer);
$payment->setRedirect_urls($redirectUrls);
$payment->setTransactions(array($transaction));

try {
    $payment->create($apiContext);
} catch (\PPConnectionException $ex) {
    echo "Exception: " . $ex->getMessage() . PHP_EOL;
    var_dump($ex->getData());  
    exit(1);
}

foreach($payment->getLinks() as $link) {
    if($link->getRel() == 'approval_url') {
        $redirectUrl = $link->getHref();
    }
}

$_SESSION['paymentId'] = $payment->getId();
if(isset($redirectUrl)) {

```
header("Location: $redirectUrl");
exit;
```

}

In order summery its showing description but amount is not showing.
Please help me to sort out this problem
Thank for you help.

Sunil

**Comment by saadamin** [comment]
found the solution here https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/CreatePayment.php
