### ISSUE TITLE
INTERNAL_SERVICE_ERROR: CreatePaymentUsingSavedCard

### ISSUE THREAD

**Issue by mukundindianic** [paypal/PayPal-PHP-SDK#680]
### Required Information

- PHP Version: 5.6
- PayPal-PHP-SDK Version: Latest
- Debug ID(s): 5c2aa2ded8e4

When I tried to create payment using saved card, received following error:
```
{
    "name": "INTERNAL_SERVICE_ERROR",
    "message": "An internal service error occurred.",
    "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR",
    "debug_id": "5c2aa2ded8e4"
}

```

**Comment by mukundindianic** [comment]
Another debug code:
```
{
    "name": "INTERNAL_SERVICE_ERROR",
    "message": "An internal service error occurred.",
    "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR",
    "debug_id": "f688b6748f00"
}
```

**Comment by bluk** [comment]
There have been sandbox issues over the last 24 hours which should be fixed now. Looking at the debug ID, I also didn't see a `payer_id` associated with the credit card ID. The `payer_id` should be the same `payer_id` field with the vaulted credit card resource. A sample message request that worked for me this morning:

```
{
  "intent": "sale",
  "payer": {
    "payment_method": "credit_card",
    "funding_instruments": [
      {
        "credit_card_token": {
          "credit_card_id": "CARD-9GW41790D72344021K734KSM",
          "payer_id": "Y6SCG5MPEH9CD"
        }
      }
    ]
  },
  "transactions": [
    {
      "amount": {
        "total": "4.01",
        "currency": "USD"
      }
    }
  ]
}
```

**Comment by mukundindianic** [comment]
It is still not working for me, same error:
```
{
    "name": "INTERNAL_SERVICE_ERROR",
    "message": "An internal service error occurred.",
    "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR",
    "debug_id": "6b192eb89b521"
}
```

**Comment by mukundindianic** [comment]
I think it is service error as I always receive 
```
{
    "name": "INTERNAL_SERVICE_ERROR",
    "message": "An internal service error occurred.",
    "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR",
    "debug_id": "c197cc8c90a"
}
```
@bluk, earlier you mentioned, was issue of service and service was down, but I always receive internal service error.

More over I never see any transaction log in neither developer dashboard (sandbox transaction in either app/merchant) nor in sandbox merchant account.

**Comment by bluk** [comment]
@mukundindianic The last 2 errors seems to show that you are trying to process transactions with an account in an unsupported country. Please ensure that [direct credit cards are supported](https://developer.paypal.com/docs/integration/direct/rest-api-payment-country-currency-support/) for your country. For instance, if you created a Sandbox Test Merchant account in India, then processing direct credit cards is not supported with your merchant/seller account.

**Comment by mukundindianic** [comment]
Thats little disappointing.
You mean to say that if I have merchant account in USA or any of above listed country I can accept credit card payments from buyer belongs to any country including India with supported cards like(MasterCard, Visa, Amerian Express etc.)

**Comment by mukundindianic** [comment]
I tried with create payment using: payments/CreatePayment.php (credit card). It worked well and received success and following response with same sets of credentials:

```
"id": "PAY-6UW0033042867362RLAAIWRI",
    "create_time": "2016-10-14T07:37:41Z",
    "update_time": "2016-10-14T07:37:41Z",
    "state": "created",
    "links": [
        {
            "href": "https://api.sandbox.paypal.com/v1/payments/payment/PAY-6UW0033042867362RLAAIWRI",
            "rel": "self",
            "method": "GET"
        }
    ]
```
Then why is it not working for another similar method called: payments/CreatePaymentUsingSavedCard.php?

**Comment by bluk** [comment]
@mukundindianic I'm not entirely sure why the credit payments work using the `CreatePayment.php`. The previous `CreatePaymentUsingSavedCard.php` did seem to indicate that the domestic transactions were not supported using that sandbox merchant account.

Technically today, only the PayPal Pro UK merchant accounts are fully supported for the credit card use case using the REST API. PayPal US can work but it does not fully support all of the features for instance. The Classic/SOAP APIs are fully supported in both countries.

You can [Contact PayPal Support](https://www.paypal.com/us/selfhelp/home) for more clarification on the supported use cases.

If you require different country support, you may want to look at [Braintree Payments](https://www.braintreepayments.com/), a PayPal owned company for credit card and other payment method support if it fits your needs.

**Comment by dineshkumarchauhan** [comment]
Hi bulk and mukundindianic

**_Same error in payments/CreatePaymentUsingSavedCard.php?_**
{
    "name": "INTERNAL_SERVICE_ERROR",
    "message": "An internal service error occurred.",
    "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR",
    "debug_id": "49ebdca3ef25e"
}

_**mukundindianic, have you resolved your problem?**_

Please reply me, ASAP

Thank You

**Comment by pp-randy** [comment]
@dineshkumarchauhan you are being impacted by https://github.com/paypal/PayPal-REST-API-issues/issues/22

You need to use a randomly generated card to resolve.  At the bottom of https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1413 you will find a Generate CC Number button, which will create a credit card that you can use for testing.

**Comment by pp-randy** [comment]
Locking the thread, please create a new issue if the 500 error continues after using the above suggestion.
