### ISSUE TITLE
next_billing_date always returns 10:00:00Z

### ISSUE THREAD

**Issue by m-aarouf** [paypal/PayPal-PHP-SDK#681]
### Issue Description

In the agreement details, I am getting the next_billing_date = 2016-11-07T10:00:00Z.  However, the merchant sandbox website shows that the payment was executed at 2016-11-07 13:11:25 UTC

Note that I am always getting the next billing date at 10:00:00.

Also note that the last_payment_date is returning the correct date and time in UTC. So, I assume that this is not a time zone issue.

So, I am confused. Is it the case that PayPal needs 3-4 hours to execute payments? Or is it a bug that the next_billing_date will always be at 10:00:00 no matter when the payment is going to be executed?

Link to my stackoverflow question: http://stackoverflow.com/questions/39917167/paypal-billing-agreements-time-zone-and-returned-time

**Comment by pp-randy** [comment]
The Billing Agreements are done in a batch and will most likely not bill exactly at 10, but it should bill on that date and should be fairly consistent from billing to billing.   

Are you seeing this behavior in Sandbox or Production?  Production has more resources processing the billing agreements and is more likely be more consistent between the payments.

**Comment by m-aarouf** [comment]
@pp-randy Thanks for replying. I am seeing this behavior on sandbox.
One more question, Is the `next_billing_date`  returned in `AgreementDetails.getNextBillingDate()` uses  `UTC`  time zone? since there are some comments that mention that PayPal uses PDT. [example](https://github.com/paypal/PayPal-Java-SDK/issues/207)

**Comment by pp-randy** [comment]
Sorry for the delay @m-aarouf.  

next_billing_date is coming back as UTC.

My REST API Details returned next_billing_date:2016-10-31T10:00:00Z
My IPN returned next_payment_date: 03:00:00 Oct 31, 2016 PDT

These are the same time just different time zones.

**Comment by m-aarouf** [comment]
Thanks for the reply @pp-randy :)
I will repost here once I test on live.

**Comment by pp-randy** [comment]
@m-aarouf I also have some updated information on start_date you might find helpful https://github.com/paypal/PayPal-Java-SDK/issues/207#issuecomment-255794267

**Comment by pp-randy** [comment]
Closing the issue for now. Please let me know if you need further assistance
