### ISSUE TITLE
getBillingAddress() is null

### ISSUE THREAD

**Issue by OnnoGeorg** [paypal/PayPal-PHP-SDK#684]
### Required Information

- PHP Version: 5-6.26
- PayPal-PHP-SDK Version: 1.7.0
- Debug ID(s):

### Issue Description

Since about a week, no billing address is returned to PayerInfo. If I try e.g. to get the street via
`$payment->getPayer()->getPayerInfo()->getBillingAddress()->getLine1()` 
it results in an error:
`PHP Fatal error:  Call to a member function getLine1() on null in ...`

PayerInfo's member functions `getEmail()`, `getFirstName()` and  `getLastName()` are ok and returning the expected values.

Was there a change in the API?

**Comment by bluk** [comment]
Can you please contact [PayPal Support](https://www.paypal.com/us/selfhelp/home) regarding this issue? It seems to be an account specific issue. You may also want to mention internal issue PPPLPAYPT-13584 which seems to be related. Thanks.
