### ISSUE TITLE
Error 500 & 503 | Sandbox API: All down

### ISSUE THREAD

**Issue by cyclux** [paypal/PayPal-PHP-SDK#691]
### Required Information

- PHP Version: 7.0.11
- PayPal-PHP-SDK Version:  1.8.0

Down again. This time also with Error 503. Here some logs..

/#INTERNAL_SERVICE_ERROR","debug_id":"1d05812cf02e7"}
/#INTERNAL_SERVICE_ERROR","debug_id":"5173e68ae9e6d"}/#INTERNAL_SERVICE_ERROR","debug_id":"869f2b4a1ee13"}
/#INTERNAL_SERVICE_ERROR","debug_id":"e5739b16af8f3"}

**Comment by bluk** [comment]
Thanks for providing the Debug-IDs. The root cause is the same as https://github.com/paypal/PayPal-PHP-SDK/issues/678 so will close as a duplicate. My apologies for the service interruptions. The product development team is actively working towards a resolution.
