### ISSUE TITLE
[question] Is it possible to reserve a payment?

### ISSUE THREAD

**Issue by JCarlosR** [paypal/PayPal-PHP-SDK#695]
Hi. I have to make the next flow in my site:
1. A user A reserve one slot in a service offered by the user B.
2. My site asks the user A for paypal or credit card data (to verify that really have the amount to pay, and avoid to spend that amount).
3. User B see the user A profile and accept or cancel.
4. If user B accepts, the payment is performed. If cancel, user A is able to use the reserved amount in other transactions.
Can I achive this using Paypal?
Thanks in advance. Please help me with some ideas.

**Comment by pp-randy** [comment]
The answer is yes; however, not knowing if and how your website would make money on this transaction limits the response.   

It seems you could use an authorization for your purpose.  More here:  https://developer.paypal.com/docs/integration/direct/capture-payment/#authorize-the-payment 
For an accept you capture the authorization. For the cancel you would want to void the authorization.  Voiding the authorization should free any reserved amount.  

In step 2, is the authorization between user A and your site?  If so, you could collect the payment and then send it out to user B using a Payout.  This does make your site liable for chargebacks though.

On the other hand you could use make the transaction between user A and B then send B and invoice for your services.   

Depending on your business model and if you are in the United States the Braintree Marketplace offering might interest you https://developer.paypal.com/docs/marketplace/

**Comment by JCarlosR** [comment]
Thanks for your help.

My site will work primarily with countries in LATAM.
I will read more about it, but can I use this repository to perform the authorization and capture the payment?

**Comment by pp-randy** [comment]
Yes https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/AuthorizePaymentUsingPayPal.php

PayPal has sales teams that support LATAM that should be able to help you with finding the best solution. Example for Brazil the sales team is here: https://www.paypal-brasil.com.br/contatocomercial/?bus=mp

Go to https://www.paypal.com/webapps/mpp/country-worldwide.  If you do not find any phone numbers for the business areas then the general customer support team should be able to assist you.

**Comment by JCarlosR** [comment]
@pp-randy Thank you.
Using the sample code I have implemented the following:
- Authorize a payment using paypal.
- Capture an authorized payment.
- Void an authorized payment.

My question is, where I can see the information of these transactions?
- When I go to ```Sandbox -> Transactions``` I get the next message: ```You don't have any transactions```
- But I think that the capture is executed correctly, because in ```Sandbox -> Accounts``` the profile of the buyer shows a balance of ```9973.00 USD``` instead of ```9999``` (I saw this default value initially).

**Comment by pp-randy** [comment]
You can log into the sandbox account like you would a live account, but you do that here. https://www.sandbox.paypal.com.  You use your sandbox business account to log in.  Let me know if your transactions are not showing up there and I will look further into it.

**Comment by JCarlosR** [comment]
@pp-randy Thank you. I can see the transactions in the test accounts, but not in ```Sandbox -> Transactions``` in the dev dashboard. Is it normal?

I have the next questions, should I create a new issue?
- How I can add a ```note to the buyer``` when an authorization is voided?
- I never set a shipping address but this information appears when the buyer is approving the authorization.

**Comment by pp-randy** [comment]
Did you end up integrating with this SDK?  They should show up if you did.  Only the REST API transactions show up in that space.

I don't see a note for voiding https://developer.paypal.com/docs/api/payments/#authorization_void
I can create a feature request for one, seems it exists in the Classic API https://developer.paypal.com/docs/classic/api/merchant/DoVoid_API_Operation_NVP/

For shipping address look at https://developer.paypal.com/docs/api/payment-experience/#definition-input_fields.  You will need to create a web experience profile with no_shipping set to 1.  You supply that id in the payment for those payments you don't want shipping addresses on.

**Comment by JCarlosR** [comment]
@pp-randy Yes. I am using this SDK.

I want to add a note to explain to the "buyer" why the other user has rejected his/her request (if it possible, please create the feature request).

Is it not possible to set the no_shipping to 1 for one of the objects used in ```https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/AuthorizePaymentUsingPayPal.php```?

**Comment by pp-randy** [comment]
Moving the note field to https://github.com/paypal/PayPal-REST-API-issues/issues/48 for further tracking.

**Comment by pp-randy** [comment]
I apologize for the delay in update and missing your last comment. 
For no_shipping the web experience profile must currently be used.
