### ISSUE TITLE
FAILURE: SECURITY WARNING: TLSv1.2 is not supported on this system. Please upgrade your curl to atleast 7.34.0.

### ISSUE THREAD

**Issue by ztjuh** [paypal/PayPal-PHP-SDK#705]
### Required Information

- PHP Version: 7.0.12
- PayPal-PHP-SDK Version: 1.10.0
- Debug ID(s): ?

### Issue Description
> When running https://website/vendor/paypal/rest-api-sdk-php/sample/tls/TlsCheck.php I get the following warning: 
> 
> 1. FAILURE: SECURITY WARNING: TLSv1.2 is not supported on this system. Please upgrade your curl to atleast 7.34.0.
> - Current Curl Version: 7.50.1
> - Current OpenSSL Version:OpenSSL/1.0.2h (Failed)
> 
> Possible duplicate of: https://github.com/paypal/PayPal-PHP-SDK/issues/596

I have followed tls-update#php and tried the files (cacert.pem & TlsCheck.php).

    $ php -f TlsCheck.php
    PayPal_Connection_OK

    $ openssl version
    OpenSSL 1.0.2j  26 Sep 2016

    $ php -r 'echo json_encode(curl_version(), JSON_PRETTY_PRINT);'
    {
        "version_number": 471555,
        "age": 3,
        "features": 968605,
        "ssl_version_number": 0,
        "version": "7.50.3",
        "host": "i686-pc-linux-gnu",
        "ssl_version": "OpenSSL\/1.0.2j",
        "libz_version": "1.2.8",
        "protocols": [
            "dict",
            "file",
            "ftp",
            "ftps",
            "gopher",
            "http",
            "https",
            "imap",
            "imaps",
            "pop3",
            "pop3s",
            "rtsp",
            "scp",
            "sftp",
            "smb",
            "smbs",
            "smtp",
            "smtps",
            "telnet",
            "tftp"
        ]

From phpinfo();:

    $_SERVER['SSL_VERSION_LIBRARY']	OpenSSL/1.0.2j

In PayPal.log I found the following:

    [01-11-2016 09:08:08] PayPal\Core\PayPalHttpConnection : INFO: POST https://test-api.sandbox.paypal.com/v1/oauth2/token
    [01-11-2016 09:08:08] PayPal\Core\PayPalHttpConnection : INFO: Invalid or no certificate authority found - Retrying using bundled CA certs file

The only thing that occured to me is that phpinfo shows `OpenSSL 1.0.2j` and TlsCheck.php `OpenSSL/1.0.2h`.

**Comment by jaypatel512** [comment]
Can you please make sure that you are getting proper curl_version as mentioned at https://github.com/paypal/TLS-update#php.

**Comment by ztjuh** [comment]
$ php_curl
    -bash: php_curl: command not found

I'm on Arch Linux there is no package for `php_curl`.

**Comment by ztjuh** [comment]
Any solution, or should I switch distibutions?

**Comment by ztjuh** [comment]
I have rebooted the server, now it says:

> 1. FAILURE: SECURITY WARNING: TLSv1.2 is not supported on this system. Please upgrade your curl to atleast 7.34.0.
> - Current Curl Version: 7.50.3
> - Current OpenSSL Version:OpenSSL/1.0.2j (Failed)

So versions are the same...

**Comment by aldimol** [comment]
In file **sample/tls/TlsCheck.php** - line 24, replace the address service.EndPoint:
$apiContext->setConfig(array('service.EndPoint'=>"https://**# test-**api.sandbox.paypal.com", 'cache.enabled'=>false));

$apiContext->setConfig(array('service.EndPoint'=>"https://api.sandbox.paypal.com", 'cache.enabled'=>false));

Sorry for bad english ...

**Comment by ztjuh** [comment]
This works, thank you very much!
