### ISSUE TITLE
PayPal Plus: Payments are not processed (infinit activity) or canceled without any hint

### ISSUE THREAD

**Issue by SDPrio** [paypal/PayPal-PHP-SDK#708]
- PHP Version: 5.5.6
- PayPal-PHP-SDK Version: 1.10.0
- Debug ID(s): 32fb5810e4e64

I am using the PHP Rest API SDK within my Symfony 2.8 project. Currently I am trying to integrate PayPal Plus after using the "normal" PayPal Checkout before.

While creating a new payment using the SDK I receive an error 500 from time to time as described in issue #707 (e.g. debug ID 32fb5810e4e64). 

However, in most cases the creation of the payment works without any problem and I can use the approval link in `JS` with `PAYPAL.apps.PPP` to select the payment method. I can choose between PayPal, Credit Card and Debit payment. While using PayPal as payment method works without any problem, using other payment methods is not possible.

When I select Credit Card or Debit payment, I am redirected to the corresponding PayPal checkout page. After specifying all payment details, a click on the "Purchase" button brings up an activity indicator. After about a minute of "activity", the indicator is dismissed and nothing else happens. I am stuck on the PayPal page. 

In very rare cases, the Payment seems to be processed, and I am redirected to my page. However the redirection is always done using the `Cancel URL` instead of the `Confirmation URL`, e.g.:

`example.com/shop/cancel-order?token=EC-4RC22852A8020311C&ppp_msg=1`

So, there are two problems:

1. In most cases submitting the payment does not has any effect at all
2. In the rare other cases, the payment is canceled without any hint what went wrong

Is this a know issue? How to solve this?

**Comment by jaypatel512** [comment]
We have seen similar effect on few extremely overused credit cards. Can you please see if you are randomly generating a credit card for your testing. Few common numbers such as `41111...` are extremely overused, and causes issues with these flows. 

Can you please try and reproduce this with a random credit card generated from many available websites ?

**Comment by SDPrio** [comment]
The issue occurs no matter if one of the test credit card numbers from the PayPal docs or a real credit card number is used.

**Comment by pp-randy** [comment]
@SDPrio PayPal Technical Support should be better able to better assist you with integrating PayPal Plus in the sandbox environment.  
English: https://www.paypal-techsupport.com/app/ask
German: https://de.paypal-techsupport.com/app/ask

**Comment by pp-randy** [comment]
Closing the issue, since Technical Support seems the way to go for this one.
