### ISSUE TITLE
REST API : payouts error 500 INTERNAL_ERROR

### ISSUE THREAD

**Issue by kruggs** [paypal/PayPal-PHP-SDK#711]
Hi,
i'm struggling with an error 500 with sandbox paypal "payouts", i manage to make works payment, but i always get error 500 with payouts
`{"name":"INTERNAL_ERROR","message":"An internal service error has occurred.","debug_id":"1add4a9923341","information_link":"https://developer.paypal.com/docs/api/payments.payouts-batch/#errors"}`

the code i use to test (replace *** with your token): 
`curl -v https://api.sandbox.paypal.com/v1/payments/payouts?sync_mode=true \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer ***" \
  -d '{
  "sender_batch_header":{
    "email_subject":"You have a payment"
  },
  "items":[
    {
      "recipient_type":"EMAIL",
      "amount":{
        "value":12.34,
        "currency":"USD"
      },
      "receiver":"shirt-supplier-one@mail.com",
      "note":"Payment for recent T-Shirt delivery",
      "sender_item_id":"A123"
    }
  ]
}'
`

I tried with default apikey we got with the sdk, i also test with my apikey (sandbox account, app etc etc).
I tried with master branch, and tags\1.10.0

I think i try almost everything, so guys if you have idea or if it's coming from their side ? (i saw some old issue on ruby sdk about it)
if you need more detail let me know.

ps : do we need to change/update the ssl certificat (pem file) from the sdk or not ?

Thanks

**Comment by bluk** [comment]
Thank you for the error report. I've opened PPPLPAYPT-14603 internally to track this error. This error should only occur in sandbox and is a PayPal service error.

I don't believe you need to change/update the SSL PEM file.

**Comment by kruggs** [comment]
Thanks a lot,
seems fixed now (10.33 am Paris time)

By the way not sure if it's related, for the check tls1.2 front he sandbox i always get  : "SSL certificate problem: certificate has expired", my curl version is ok  7.38.* and openssl 1.0.1t

**Comment by bluk** [comment]
@kruggs Thanks for reporting the certificate issue. The test-api.sandbox.paypal.com endpoint should now be unnecessary to use. TLS 1.2 should be required for sandbox connections so if you can connect to sandbox, you should pass that test. I've opened PR #714 to remove the TLS sample.
