### ISSUE TITLE
Debug_id dbbda5c0dab41 for payments/payouts

### ISSUE THREAD

**Issue by semionk-jomedia** [paypal/PayPal-PHP-SDK#712]
We received this error recently, and have been struggling to understand or find who to ask for this type of issues.

php5.6
happens when sending payout request.

Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payouts?sync_mode=false. {"name":"INTERNAL_ERROR","message":"An internal service error has occurred.","debug_id":"dbbda5c0dab41","information_link":"https://developer.paypal.com/docs/api/payments.payouts-batch/#errors"}

**Comment by bluk** [comment]
Can you please try again? If it fails, can you please provide the debug_id again as well?

This appears to be the same issue as #711 , but the issue should be resolved. I have also been able to make a simple request to create a payout.

**Comment by semionk-jomedia** [comment]
yes it works now. Its been happening  for couple days prior which lead to a concern.

we were wondering what is the root of the problem.

But definitely works now.

**Comment by bluk** [comment]
It was a sandbox internal service issue which should now be resolved. If you encounter the issue again, please open a new issue. Thanks.
