### ISSUE TITLE
Questions about deprecated methods

### ISSUE THREAD

**Issue by azngeek** [paypal/PayPal-PHP-SDK#713]
### Required Information

- PHP Version: 7
- PayPal-PHP-SDK Version:
- Debug ID(s):

### Issue Description
> Why is the method getPaymentInstruction() deprecated and what is the replacement?

```
 /**
     * Instructions for the payer to complete this payment.
     * @deprecated Not publicly available
     * @return \PayPal\Api\PaymentInstruction
     */
    public function getPaymentInstruction()
    {
        return $this->payment_instruction;
    }
```

**Comment by bluk** [comment]
As documented, this field is not publicly available. What are you trying to use it for?

If you are trying to have a free form field to send to the payer, you may want to see [`getNoteToPayer`](https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Api/Payment.php#L429).

**Comment by azngeek** [comment]
I am not using it for anything but debugging a Magento module and saw that it is using this method. I think that it is currently used to check if the payment object contains information about a PUI payment. 

The logic of the code i am debugging is like that one.

```
 if($paymentInstructions = $ppPayment->getPaymentInstruction()) {
            $payment->setData('ppp_pui_reference_number', $paymentInstructions->getReferenceNumber());
            $payment->setData('ppp_pui_instruction_type', $paymentInstructions->getInstructionType());
            $payment->setData(
                'ppp_pui_payment_due_date',
                Mage::helper('iways_paypalplus')->convertDueDate($paymentInstructions->getPaymentDueDate())
            );
            $payment->setData('ppp_pui_note', $paymentInstructions->getNote());

            $bankInsctructions = $paymentInstructions->getRecipientBankingInstruction();
            $payment->setData('ppp_pui_bank_name', $bankInsctructions->getBankName());
            $payment->setData('ppp_pui_account_holder_name', $bankInsctructions->getAccountHolderName());
            $payment->setData(
                'ppp_pui_international_bank_account_number',
                $bankInsctructions->getInternationalBankAccountNumber()
            );
            $payment->setData('ppp_pui_bank_identifier_code', $bankInsctructions->getBankIdentifierCode());
            $payment->setData('ppp_pui_routing_number', $bankInsctructions->getRoutingNumber());

            $ppAmount = $paymentInstructions->getAmount();
            $payment->setData('ppp_pui_amount', $ppAmount->getValue());
            $payment->setData('ppp_pui_currency', $ppAmount->getCurrency());
        }
```

So is there any other possibility? I could use ```toArray``` instead to fix the code. Just want to ensure that i will not break the existing code in a few months when updating the lib.

**Comment by bluk** [comment]
While the field is deprecated, it should not be removed until a major version bump (e.g. 2.x). I don't know of a replacement field for this (especially if you are GETting the data and trying to store it into Magento payment object), but you can probably use the `toArray` if you feel the need to just get the response and parse it yourself.
