### ISSUE TITLE
Invalid price if setLocale() has a different decimal seperator

### ISSUE THREAD

**Issue by Visualq** [paypal/PayPal-PHP-SDK#717]
### Required Information

- PHP Version: All
- PayPal-PHP-SDK Version: Latest
- Debug ID(s):

### Issue Description
Currently using setLocale('nl_NL') which has  a comma as decimal seperator. This is causing problems in FormatConverter as it can't find the '.' it will round the value. (0.20 double value cast to string which happends in strpos, will result in 0,20).

`
        } elseif (strpos($value, ".") === false) {
            $decimals = 0;
        }`

**Comment by jaypatel512** [comment]
Hey @Visualq !

You are correct. It would be more advisable, if we let the developer decide the format there, instead of SDK jumping in, and automatically overriding it. We were able to reproduce the issue, and will work on the fix as soon as possible.

**Comment by jaypatel512** [comment]
On further review by @bluk ! We realized that paypal APIs requires `.` as a decimal separator. Read more detailed log inside the PR #755.

To solve your issues, you may have to manually convert the currency values to use `.` separator before passing it in to the SDK.
