### ISSUE TITLE
question : Vault creditcard vs creditcard from Paypal

### ISSUE THREAD

**Issue by kruggs** [paypal/PayPal-PHP-SDK#718]
### Required Information

- PHP Version: 5.6.24
- PayPal-PHP-SDK Version:1.10.0
- Debug ID(s):

### Issue Description
Hi, i'm testing payment via already saved creditcard on sandbox and it's working.
I try to get list of all creditcard on sandbox and i get the one created on sandbox.
On live i try to get the list all all creditcard : 
`$cards = CreditCard::all($params, $this->getApiContext());`

I got 0, it's a bit strange because i have already a creditcard in our account and we are using it for year now.

Is it mandatory to add a credit card with Vault api to be allow to use payment api  ? Or it's a bug ? Does it will mean i will have 2 creditcard (2 times the same) saved in Paypal ?
Stored creditcard via vault doesn't appear in paypal interface ?
Sorry i can't find any help/doc about this :(

**Comment by jaypatel512** [comment]
The saved credit card as specific to your merchant account. The saved card are not the customer's saved cards. 

Vaulting (Saving credit card) in PayPal is mostly used in cases where the merchant does not want to store the credit card in their database. 

For most common flows, we recommend using "Pay with PayPal". The UI that the user will log in, and select the payment will show properly stored credit cards to the user.
