### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by techpulse** [paypal/PayPal-PHP-SDK#719]
Hello.

Would PayPal SDK, have option to split payments using Express Checkout?

If so, could anyone guide me how?
And if so, what happens when someone disputes/chargebacks/unauthorized? Would it be disputed / taken from all accounts or only the main one?

Thanks!

**Comment by jaypatel512** [comment]
Hey @techpulse !

We currently do not have that support in PayPal REST SDKs. We however, have classic (legacy) APIs that supported [split payments](https://developer.paypal.com/docs/classic/adaptive-payments/integration-guide/APIntro/). We have [adaptive-payments-php-sdk](https://github.com/paypal/adaptivepayments-sdk-php), that supports those legacy APIs. However, keep in mind that the SDKs are not actively maintained for these `classic` APIs.
