### ISSUE TITLE
500 - Internal Server Error when trying to execute payment.

### ISSUE THREAD

**Issue by scbritton** [paypal/PayPal-PHP-SDK#722]
### Required Information

- PHP Version: 5.6
- PayPal-PHP-SDK Version: 1.0.0
- Debug ID(s): Paypal-Debug-Id: 493dde766acfd

### Issue Description
> Please include as many details (logs, steps to reproduce) as you can to help us reproduce this issue faster.

Payment was created fine, using Postman and the sample requests from the "First API Call" found in the REST api information on the developer.paypal.com website.

Payment was approved and first, I tried to use Postman to execute the payment.  I kept getting 401 Unauthorized errors.  

So, because I was using the SDK earlier and kept getting 500 Internal Server errors earlier today (yet was not getting them yesterday) I decided to drop the SDK and use CURL to text.  

The output from CURL:
```
$ curl -v -X POST https://api.sandbox.paypal.com/v1/payments/payment/PAY-28D42433WW256043MLAYOG3Q/execute -H "Content-Type:application/json" -H "Authorization: Bearer <Access-Token-Redacted>" -d '{ "payer_id":"CPHLG4W8PPXXC" }'
* Hostname was NOT found in DNS cache
*   Trying 173.0.82.78...
* Connected to api.sandbox.paypal.com (173.0.82.78) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Request CERT (13):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using AES256-SHA256
* Server certificate:
*        subject: C=US; ST=California; L=San Jose; O=PayPal, Inc.; OU=PayPal Production; CN=api.sandbox.paypal.com
*        start date: 2016-01-13 00:00:00 GMT
*        expire date: 2018-01-13 23:59:59 GMT
*        subjectAltName: api.sandbox.paypal.com matched
*        issuer: C=US; O=Symantec Corporation; OU=Symantec Trust Network; CN=Symantec Class 3 Secure Server CA - G4
*        SSL certificate verify ok.
> POST /v1/payments/payment/PAY-28D42433WW256043MLAYOG3Q/execute HTTP/1.1
> User-Agent: curl/7.35.0
> Host: api.sandbox.paypal.com
> Accept: */*
> Content-Type:application/json
> Authorization: Bearer <Access token redacted>
> Content-Length: 30
>
* upload completely sent off: 30 out of 30 bytes
< HTTP/1.1 500 Internal Server Error
< Date: Sun, 20 Nov 2016 00:16:31 GMT
* Server Apache is not blacklisted
< Server: Apache
< PROXY_SERVER_INFO: host=slcsbplatformapiserv3002.slc.paypal.com;threadId=463
< Paypal-Debug-Id: 493dde766acfd
< CORRELATION-ID: 493dde766acfd
< Content-Language: *
< Connection: close
< Connection: close
< Paypal-Debug-Id: 493dde766acfd
< Set-Cookie: X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Dplatformapiserv%26TIME%3D1609248856%26HTTP_X_PP_AZ_LOCATOR%3D; Expires=Sun, 20 Nov 2016 00:46:31 GMT; domain=.paypal.com; path=/; Secure; HttpOnly
< Set-Cookie: X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT
< Vary: Authorization
< Content-Length: 207
< Content-Type: application/json
<
* Closing connection 0
* SSLv3, TLS alert, Client hello (1):
{"name":"INTERNAL_SERVICE_ERROR","details":[],"message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"493dde766acfd"}
```

**Comment by BenWoodford** [comment]
Sounds like #707 again, I've got the same and am glad it's not just me. Frankly I'm appalled at how often the sandbox goes down. Paypal isn't exactly a cheap service to use compared to literally every other card processor out there, so to have things held up because their sandbox keeps throwing up errors is ridiculous.

Unfortunately I don't choose what gateway to use, the client does. Otherwise we'd be using Stripe.

**Comment by scbritton** [comment]
It seems to have resolved itself as of Sunday afternoon (my time)...
		_____________________________

**Comment by pp-randy** [comment]
Thank you @scbritton for reporting that the issue is resolved. 

I apologize for the recent sandbox issues that have come up the past couple weekends.

**Comment by Luthfifs** [comment]
@pp-randy i get this issue today

[2017-03-17 14:19:07] local.INFO: {"name":"INTERNAL_SERVICE_ERROR","details":[],"message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/payments#INTERNAL_SERVICE_ERROR","debug_id":"3bcc86abafadf"}  

[2017-03-17 14:19:07] local.INFO: Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment/PAY-6GR22327NR782741ULDFYZHA/execute.  

can you help me guys ?

**Comment by tituscrow82** [comment]
I was receiving the same error from 6pm ET yesterday until I gave up at 11pm ET.     Just tried it now and it is working again.  Not sure what is going on.

**Comment by pp-randy** [comment]
@Luthfifs please create a new issue if you are still experiencing a problem.  Sorry for the delay.
