### ISSUE TITLE
Getting System error popup while creating payment in Sandbox envirmont

### ISSUE THREAD

**Issue by sucharuhasija** [paypal/PayPal-PHP-SDK#723]
Hi , I am getting the following issue in iOS 

PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR
![screen shot 2016-11-20 at 10 04 37 am](https://cloud.githubusercontent.com/assets/15157454/20460471/8ccfd8b6-af09-11e6-831a-c6e19bd25c5f.png)
 - System error. Please try again later. (500) | PayPal Debug-ID: 871341487b44b, 871341487b44b [sandbox, PayPal iOS SDK 2.14.7]

also a similar issue is coming in android tooo

**Comment by pp-randy** [comment]
Hi @sucharuhasija can you let me know if you are still having an issue?  We've had some recent system issues that caused 500 errors that are now resolved.

**Comment by sucharuhasija** [comment]
Thanks, The issue has been resolved now
