### ISSUE TITLE
Unsupported SSL protocol version

### ISSUE THREAD

**Issue by ak868308** [paypal/PayPal-PHP-SDK#724]
![tt](https://cloud.githubusercontent.com/assets/7982249/20461956/69fe8956-af34-11e6-8b7c-7c22a28f3307.PNG)
### Required Information

- PHP Version:
- PayPal-PHP-SDK Version:
- Debug ID(s):

### Issue Description
PayPal\Exception\PayPalConnectionException

Unsupported SSL protocol version

show issue here 
//Throw Exception if Retries and Certificates doenst work
        if (curl_errno($ch)) {
            **$ex = new PayPalConnectionException(**
                $this->httpConfig->getUrl(),
                curl_error($ch),
                curl_errno($ch)
            );
            curl_close($ch);
            throw $ex;
        }

**Comment by pp-randy** [comment]
Indicated here https://github.com/paypal/tls-update,  your OpenSSL needs to be a higher version, such as 1.0.1c or above. Your output shows OpenSSL 1.0.0.

**Comment by jaypatel512** [comment]
Please follow the instructions mentioned in tls-update site provided by @pp-randy ! We have made all sandbox API calls to only use TLSv1.2 which is supported in PHP by OpenSSL 1.0.1c or higher.

**Comment by landguy423** [comment]
![screen shot 2017-11-28 at 7 55 24 am](https://user-images.githubusercontent.com/20238035/33329493-8cbcf0ba-d411-11e7-8355-a688c9f20e28.png)

Hello.
OpenSSL is 1.0.2 but still showed me `Unsupported SSL protocol version` .

**Comment by xiaoleih41** [comment]
will this https://github.com/paypal/PayPal-PHP-SDK/issues/474 help you?
