### ISSUE TITLE
Creating a webhook with wildcard event types

### ISSUE THREAD

**Issue by jurgenhaas** [paypal/PayPal-PHP-SDK#727]
### Required Information

- PHP Version: 7
- PayPal-PHP-SDK Version: latest
- Debug ID(s): None

### Issue Description

Creating a webhook requires a liust of event types that this webhook is bound to. Through the UI you can create a webhook that listens to "all" events and that is displayed as a wildcard event type with "*". I wonder what's the syntax through the API to achieve exactly that.

**Comment by pp-randy** [comment]
@jurgenhaas you pass in * as the value of name in the API as well.
```
"event_types": [
    {
      "name": "*"
    }
]
```
