### ISSUE TITLE
Payment is completed and success but the send account is not lost money, also the receive account is not received money

### ISSUE THREAD

**Issue by anhnq2806** [paypal/PayPal-PHP-SDK#728]
### Required Information

- PHP Version:
- PayPal-PHP-SDK Version:
- Debug ID(s):

### Issue Description
> Please include as many details (logs, steps to reproduce) as you can to help us reproduce this issue faster.

**Comment by jaypatel512** [comment]
Can you please add a bit more details, with what you are trying to achieve. My best guess from the issue description is, you are trying to do a Payment with PayPal, but forgetting to execute the payment at the end.

**Comment by pp-randy** [comment]
Closing the issue, please update us if you need further assistance.
