### ISSUE TITLE
Getting INVALID_RESOURCE_ID error in live mode

### ISSUE THREAD

**Issue by SDPrio** [paypal/PayPal-PHP-SDK#731]
### Required Information

- PHP Version: 5.6
- PayPal-PHP-SDK Version: 1.10.0
- Debug ID(s): 73c779d11d5dc, 3996e2b1511e2, 1f77d4f0a8ff7, 88fc250fb5cc3, 95bbfd89166b1, b76de424ae8da

### Issue Description
Since yesterday I receive INVALID_RESOURCE_ID errors on several different payments, while other payments still work without any problem. The error is returned as response on `https://api.paypal.com/v1/payments/payment/PAY-xyz..` requests.

What is the problem with these requests?

**Comment by pp-randy** [comment]
Hi @SDPrio,

Since this is a production impacting issue can you please reach out to PayPal Technical Support for assistance at https://www.paypal-techsupport.com/app/ask.
