### ISSUE TITLE
Still accessing sandbox endpoint when trying to go live regardless of configuring.

### ISSUE THREAD

**Issue by The-Perfect-Username** [paypal/PayPal-PHP-SDK#739]
### Required Information

- PHP Version: 5.5.9
- PayPal-PHP-SDK Version: >= 1.6.2

### Issue Description
No matter what I do I cannot access the Live endpoint without changing the constants in PayPalConstants.php for sandbox to REST_SANDBOX_ENDPOINT = "https://api.paypal.com/" and OPENID_REDIRECT_SANDBOX_URL = "https://www.paypal.com". 

Before I did that I would get this error response "Got Http response code 401 when accessing https://api.sandbox.paypal.com/v1/oauth2/token." This would happen even if I changed the apiContext mode to 'mode' = 'live' in /sample/bootstrap.php as well as changing my Api credentials to my live credentials. I even tried the sdk_config method but still no luck.

When I tried to change the constants I did manage to go around that problem, however I came across another error. For some reason, even when it takes me to the right endpoint with the right credentials and with a verified business account, it gives me an unauthorized payment error. What I'm trying to do is pay with a credit card and according to customer support I should be able to do it, even though I'm in Australia.

```
[url:PayPal\Exception\PayPalConnectionException:private] => https://api.paypal.com/v1/payments/payment

[data:PayPal\Exception\PayPalConnectionException:private] => {"name":"UNAUTHORIZED_PAYMENT","message":"Unauthorized payment.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#UNAUTHORIZED_PAYMENT","debug_id":"e78b10d23def4"}

[message:protected] => Got Http response code 401 when accessing https://api.paypal.com/v1/payments/payment.
```
I genuinely have no idea why this is an issue and urgently need it resolved.

**Comment by pp-randy** [comment]
Please reach out to PayPal Technical Support in regards to the Unauthorized Payment issue on Production https://www.paypal-techsupport.com/app/ask/

I will keep this open to further look into the endpoint issue you are facing.

**Comment by pp-randy** [comment]
@The-Perfect-Username how is it going. Are you able reproduce the endpoint issue with an updated release of the SDK? https://github.com/paypal/PayPal-PHP-SDK/releases

**Comment by The-Perfect-Username** [comment]
Thanks for the reply but it turns out we did require the website payments pro account which seemed to fix the payment issue. Basically nothing more than a situation of vague information and confusion. However the endpoint issue still stands and I needed to change the Sandbox Endpoint URLs to the same as the Live Endpoint URLs.
