### ISSUE TITLE
Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment/PAY-93671206LR172291LLBDSYDQ/execute

### ISSUE THREAD

**Issue by shoosah** [paypal/PayPal-PHP-SDK#741]
### Required Information

- PHP Version: 5.5.38
- PayPal-PHP-SDK Version:1.10.0
- Debug ID(s):9759d3a8c02d4

### Issue Description
The environment is sandbox. 
In the following section an approval link is generated without any problem:

		$clientId = AppConfig::get( 'paypal.client_id' );
		$clientSecret = AppConfig::get( 'paypal.client_secret' );
		$sdkConfig = array(
			"mode" => AppConfig::get( 'paypal.environment' )
		);

		$apiContext = new ApiContext(
			new OAuthTokenCredential(
				$clientId,
				$clientSecret
			)
		);
		$apiContext->setConfig( $sdkConfig );

		$payer = new Payer();
		$payer->setPaymentMethod( "paypal" );

		$amount = new Amount();
		$amount->setCurrency( "USD" )
			->setTotal( $AppUserProduct['Price'] );

		$item = new Item();
		$item->setName( $AppUserProduct['web_name_short'] )
			->setCurrency( "USD" )
			->setQuantity( 1 )
			->setPrice( $AppUserProduct['Price'] );

		$itemList = new ItemList();
		$itemList->setItems( array( $item ) );

		$transaction = new Transaction();
		$transaction->setAmount( $amount )
			->setItemList( $itemList )
			->setDescription( "Payment description" )
			->setInvoiceNumber( uniqid() );

		$redirectUrls = new RedirectUrls();
		$redirectUrls->setReturnUrl( "http://192.168.4.2:8080/paypal/success" )
			->setCancelUrl( "http://192.168.4.2:8080" );

		$payment = new Payment();
		$payment->setIntent( "sale" )
			->setPayer( $payer )
			->setRedirectUrls( $redirectUrls )
			->setTransactions( array($transaction) );

		try{
			$payment->create( $apiContext );
			// Get PayPal redirect URL and redirect user
			$approvalUrl = $payment->getApprovalLink();

		} catch (PayPal\Exception\PayPalConnectionException $ex) {
		} catch( Exception $ex ){
		}

Following the approval link will return me to "http://192.168.4.2:8080/paypal/success" where the following codes are processed. Please note that the ip address of the following section is different than the ip address of the first section however the client secret, client ID and environment is the same. So the apiContext object which is created should be the same.  I could see there is a unique token returned in the url ($token = $_GET['token'];) which is not really used anywhere (based on the code samples)! I receive 500 response error most of the times but this code could execute the payments few times!

		$clientId = AppConfig::get( 'paypal.client_id' );
		$clientSecret = AppConfig::get( 'paypal.client_secret' );
		$token = $_GET['token'];
		$sdkConfig = array(
			"mode" => AppConfig::get( 'paypal.environment' )
		);

		$apiContext = new ApiContext(
			new OAuthTokenCredential(
				$clientId,
				$clientSecret
			)
		);

		$apiContext->setConfig( $sdkConfig );

		// Get payment object by passing paymentId
		$paymentId = $_GET['paymentId'];
		$payment = Payment::get( $paymentId, $apiContext );
		$payerId = $_GET['PayerID'];

		// Execute payment with payer id
		$execution = new PaymentExecution();
		$execution->setPayerId( $payerId );

		try{
			// Execute payment
			$result = $payment->execute( $execution, $apiContext );
			var_dump($result);

		} catch (PayPal\Exception\PayPalConnectionException $ex) {
		} catch (Exception $ex) {
		}

**Comment by bluk** [comment]
@shoosah Can you please try a different [sandbox test account](https://developer.paypal.com/developer/accounts/)? If you still encounter an error, please contact [PayPal Merchant Technical Support](https://www.paypal-techsupport.com) since it seems to be test account specific.

**Comment by shoosah** [comment]
@bluk Thank you for your reply. Using different sandbox test account resolved the issue. I have a question not an issue tho: I could see there is a unique token returned in the url ($token = $_GET['token'];). I noticed the substring with length 10 of this token is the same token in $approvalUrl($approvalUrl = $payment->getApprovalLink();). I was wondering if this is the correct assumption and it is true in production as well.

**Comment by bluk** [comment]
@shoosah If you mean on the return URL after approving, then the token should be the same. I don't think you need to directly use it for executing the payment though.

**Comment by shoosah** [comment]
@bluk Thanks for your prompt response. Sorry it was an error from my side. You are right, the token is the same. I need the token for other stuff than executing the payment.
