### ISSUE TITLE
get error FeesPayer

### ISSUE THREAD

**Issue by a-iron** [paypal/PayPal-PHP-SDK#745]
Hello. I get error when want to setup FeesPayer

```php
$payouts = new \PayPal\Api\Payout();

$senderBatchHeader = new \PayPal\Api\PayoutSenderBatchHeader();
$senderBatchHeader->setSenderBatchId(uniqid())
    ->setEmailSubject("You have a Payout!");

$senderItem = new \PayPal\Api\PayoutItem();
$senderItem->setRecipientType('Email')
    ->setNote('Thanks for your patronage!')
    ->setReceiver($data['email'])
    ->setSenderItemId("2014031400023")
    ->setAmount(new \PayPal\Api\Currency([
        "value"    => $entityUserPointWithdraw->getTotal(),
        "currency" => "USD"
    ]))
   ->setFeesPayer("PRIMARYRECEIVER");//error
```

**Comment by bluk** [comment]
The field does not exist in the [Payouts API](https://developer.paypal.com/docs/api/payments.payouts-batch) but does exist in the adaptive payments [Pay operation](https://developer.paypal.com/docs/classic/api/adaptive-payments/Pay_API_Operation/). You can either use an Adaptive Payments SDK (which is in limited release) or use the REST [Payouts API](https://developer.paypal.com/docs/integration/direct/payouts/).

If you have questions about using the API, please reach out to [PayPal Merchant Technical Support](https://www.paypal-techsupport.com).

**Comment by googlle** [comment]
hi. Payouts API will support this feature in the future ?

**Comment by pp-randy** [comment]
I am not aware of plans to add who pays the fee to payouts; however, if you are interested in this please create an issue on this repo https://github.com/paypal/PayPal-REST-API-issues and we will follow up further.
