### ISSUE TITLE
Paypal vault creditcart

### ISSUE THREAD

**Issue by parthustad** [paypal/PayPal-PHP-SDK#749]
$card->setType("visa")

I have seen this code in paypal vault credit card example

There several other types of cards as well

for exmaple master card , american express etc

Can you please let me know all list of card types with accurate speeling values?

**Comment by jaypatel512** [comment]
Please refer to the developer docs for details on acceptable values. https://developer.paypal.com/docs/api/vault/#credit-card_create_request
