### ISSUE TITLE
There is issue in delete card code

### ISSUE THREAD

**Issue by parthustad** [paypal/PayPal-PHP-SDK#752]
if we want to delete perticular than we must pass card for that

but in your code on below link
https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/vault/DeleteCreditCard.php
there is no option for specific card id

Please add updated version of code

**Comment by jaypatel512** [comment]
You can just initialize a new `$card` and set just the `id`. 

And follow the remaining code.
