### ISSUE TITLE
Paypal Recurring payments profile with express checkout do not renew payment process.

### ISSUE THREAD

**Issue by ManishLSN** [paypal/PayPal-PHP-SDK#756]
### Issue Description

I was waiting for for my recurrent deposit subscription renewal period and the period goes expire but the payment did not deducted from customer account. any resolution or information ?

I have applied 
t3=Y
a3=xx(Amount)
p3=1
srt = 5

that means my customer get recurrent payment subscription each year till 5 year.

but after a year do not seen any actions.

**Comment by pp-randy** [comment]
Hi @ManishLSN,

This appears to be a question regarding a Payments Standard subscription.  You should contact PayPal Customer Support, or you could try reaching out to the technical support forum here https://www.paypal-community.com/t5/Merchant-Integration-Technical/ct-p/mts
