### ISSUE TITLE
Terrible documentation cut-off

### ISSUE THREAD

**Issue by 8balloon** [paypal/PayPal-PHP-SDK#757]
### Required Information

- PHP Version: 5.7
- PayPal-PHP-SDK Version: 1.10.0
- Debug ID(s): n/a (not a bug -- this is a documentation problem)

### Issue Description
The documentation in `sample/invoice/CreateThirdPartyInvoice.php` cuts off at a CRUCIAL point. The documentation on line 93 reads like this:

`    // ### Use Refresh Token. MAKE SURE TO update `MerchantInfo.Email` based on`

...and then it cuts off!!! I need to know how to use `MerchantInfo.Email` to specify the third-party I want to read invoices from. Without doing this, it appears that I can only read invoices from my own account.

Thank you!!

**Comment by 8balloon** [comment]
@jaypatel512 it looks like you authored this documentation. Could you illuminate us as to what you were trying to write?

**Comment by jaypatel512** [comment]
You are absolutely right ! My bad ! Thanks for pointing this out. Fixing it right away 👍

**Comment by 8balloon** [comment]
@jaypatel512 Thank you so much for your quick response. Your PR looks good. Unfortunately it doesn't help me :( 

Would it be possible for you to update this example to demonstrate how to perform a search on third-party invoices?

I can provide an example of what I'm trying to do if that would be helpful!

**Comment by jaypatel512** [comment]
Let me know what are you trying to accomplish, and maybe we can add a new sample or I could help you a bit here in this issue.

**Comment by 8balloon** [comment]
I would like an example of performing a search on third-party invoices.

Something like `\PayPal\Api\Invoice::search($search, $apiContext);` on third party invoices. Does that make sense?

**Comment by jaypatel512** [comment]
Re-opening this issue. Accidentally closed by automatic PR merge.

**Comment by jaypatel512** [comment]
Hey @8balloon !

I think I have an answer for you. To do a search, you basically would have to update your `apiContext` to update its access token with refresh token used to create that third party invoice. It is shown at https://github.com/paypal/PayPal-PHP-SDK/blob/third-party/sample/invoice/GetThirdPartyInvoice.php#L22

Once apiContext is updated with this new access token, you should be able to use that `apiContext` instance for all operations related to that third party merchant, whose `refreshToken` you used.

**Comment by 8balloon** [comment]
That works for me. Thanks a bunch @jaypatel512
