### ISSUE TITLE
Print/Debug SDK objects

### ISSUE THREAD

**Issue by thejacer87** [paypal/PayPal-PHP-SDK#762]
Perhaps I missed something in the documentation somewhere. Or maybe it's just a PHP thing. But when trying to debug responses from API calls, the objects seem almost impossible to view any info.

Example: I just created a payment `$payment->create($apiContext);`. After executing I would like to seem some details on the object. With xDebug on it looks like this: 
![image](https://cloud.githubusercontent.com/assets/6412919/21904451/8ad0e752-d8b8-11e6-9980-77122451bf80.png)

To get something like the auth_id I must do : `  $auth_id = $payment->getTransactions()[0]->getRelatedResources()[0]->getAuthorization()->getId();`. That seems extremely unreasonable to chain through so many object's methods to extract info... and I would have to do it for all properties I need. 

Is there no way to convert the `$payment` response to an array or something so I can access things a little easier? At the very least a way to pretty print the object so I don't have to hunt as much to get some info?

**Comment by jaypatel512** [comment]
Hey @thejacer87 !

You can easily do `$payment->toArray();` and that should do the trick. 
Also, if you look into the `_propMap` array, you should be able to see the same array that you are looking for. 

Please reopen the issue if you still cannot access things the way you wished.

**Comment by thejacer87** [comment]
thanks @jaypatel512 `->toArray()` worked. I had tried casting it `(array)` but that didn't work. That image I pasted was me clicking into the propMap. So either I have something wrong in my config, or there's a bug with phpStorm or xdebug that won't show me the propMap

**Comment by jaypatel512** [comment]
Seems something wrong with your setup. We also use PHPStorm and xDebug for PHP development here.
