### ISSUE TITLE
Class 'PayPal\Rest\ApiContext' not found in laravel while included

### ISSUE THREAD

**Issue by thomasmoors** [paypal/PayPal-PHP-SDK#763]
My code:

```
?php

namespace App\Helpers;

use PayPal\Rest\ApiContext;
use PayPal\Auth\OAuthTokenCredential;
use PayPal\Api\Agreement;
use PayPal\Api\Payer;
use PayPal\Api\Plan;
use PayPal\Api\PaymentDefinition;
use PayPal\Api\PayerInfo;
use Carbon\Carbon;


class PayPalHelper {
    private $apiContext;

    function __construct($test = false) {
        // https://developer.paypal.com/developer/applications

        if ($test) {
            // Sandbox account
            $this->apiContext = new ApiContext(
                new OAuthTokenCredential(
                    'secret',     // ClientID
                    'secret'      // ClientSecret
                    )
                );
}
```
Yes I ran composer, it just can't load the class, saw someone else with the same problem: http://laravel.io/forum/04-01-2015-paypal-sdk

**Comment by thomasmoors** [comment]
SO question: http://stackoverflow.com/questions/41632504/class-paypal-rest-apicontext-not-found-while-it-really-is-present-in-the-exact

**Comment by brajeshsipl** [comment]
I have installed  PayPal-PHP-SDK package in laravel 5.5 using composer command below
 composer require "paypal/rest-api-sdk-php:*"

Now i gone through sample code process but getting same error

Class 'PayPal\Rest\ApiContext' not found.

**Comment by xiaoleih41** [comment]
This is normally caused by incorrect installation of the SDK. Please refer to [this issue](https://github.com/paypal/PayPal-PHP-SDK/issues/885) for the possible solution.

**Comment by samolabams** [comment]
The solution is that the Class name is not well capitalized. Its supposed to be '**PayPal**\Rest\ApiContext' instead of '**Paypal**\Rest\ApiContext'

**Comment by Nomia** [comment]
Saved my time, thx @samolabams
