### ISSUE TITLE
Unable to receive subscription notification from PayPal Rest API Webhooks.

### ISSUE THREAD

**Issue by mfuzailzubari** [paypal/PayPal-PHP-SDK#768]
### Required Information

- PHP Version: 7.0
- PayPal-PHP-SDK Version: 1.11.0
- Debug ID(s):

### Issue Description
> I have implemented recurring payments using PayPal Rest API. I have subscribed to some events of webhooks. When the subscription is created, I got a notification from paypal. But when the recurring payment created I have not get any notification, even on the events console of developer account.

**Comment by luvgodnorcal420** [comment]
Wpw

**Comment by pp-randy** [comment]
@mfuzailzubari you should get a type of `BILLING.SUBSCRIPTION.CREATED`.  Are you still an issue?  Is this Live or Sandbox?  I have seen some delay in sandbox recently. 

Also when you subscribe your listener you can use `"name" = "*"` to get all events.

**Comment by pp-randy** [comment]
Closing the issue, please let me know if further assistance is needed.
