### ISSUE TITLE
Cannot select sandbox developer account?

### ISSUE THREAD

**Issue by shigawaka** [paypal/PayPal-PHP-SDK#769]
### Required Information

- PHP Version:
- PayPal-PHP-SDK Version:
- Debug ID(s):

### Issue Description
> Please include as many details (logs, steps to reproduce) as you can to help us reproduce this issue faster.
![aw](https://cloud.githubusercontent.com/assets/12228888/22182879/4883dc84-e0eb-11e6-98c7-a8bb550fdd54.png)

When i'm creating an application I can't select a sandbox account. I can't get my Client ID and Secret Key. Please enlighten me what I did wrong.

**Comment by pp-randy** [comment]
On the left Sandbox -> Accounts.  Do you have a business account?  If not, can you create one and see if this resolves the issue for you? 

I did look over it and the drop down is working for me currently.

**Comment by pp-randy** [comment]
Closing the issue, please let me know if it is still not working for you.

**Comment by shigawaka** [comment]
I'm sorry for the late reply. Was busy for the past week. Anyway I found a solution online that involves in manually putting the business account in the selected option.

**Comment by joshleitzel** [comment]
Here's the method @shigawaka was probably referring to for anyone else that lands here: http://stackoverflow.com/questions/25504445/cant-create-app-for-paypal-rest-api

Truly, truly horrible on PayPal's part.

**Comment by pp-randy** [comment]
@josephting I'm aware of an issue with Brazil Accounts not being created correctly in Sandbox which is related to those not showing on the account list https://github.com/paypal/PayPal-REST-API-issues/issues/23

What country is your sandbox business account for?

**Comment by josephting** [comment]
@pp-randy Don't remember exactly but they are either US or Malaysian account. Probably used the US one for active development since the main account used on production environment was an account based in US.

**Comment by szatti1489** [comment]
Hey, I have excatly the same problem. When I try to create an app, the sandbox developer account dropdown is empty, even I have both a BUSINESS and a PERSONAL developer account.
What should I do now? I am from Hungary (HU, HUN), if it is important.
thx

**Comment by pp-randy** [comment]
@szatti1489 try creating a new sandbox business account and see if that shows up in your App account drop down.  If the problem still persists please create a new issue here [PayPal-REST-API-issues](https://github.com/paypal/PayPal-REST-API-issues).
