### ISSUE TITLE
Paypal payment 

### ISSUE THREAD

**Issue by 22wpexpert** [paypal/PayPal-PHP-SDK#770]
### Required Information

- PHP Version:
- PayPal-PHP-SDK Version:
- Debug ID(s):

### Issue Description
when a user checkout from my site , I want to store there payment details and after 10 days I want to make payment.

Is there any way to do this ?

**Comment by bluk** [comment]
You can try authorizing the payment first, and then later capturing the funds. Please see the [`Capture payments later` documentation](https://developer.paypal.com/docs/integration/direct/payments/capture-payment/) for an example.
