### ISSUE TITLE
Incoming JSON data does not match API request

### ISSUE THREAD

**Issue by ace411** [paypal/PayPal-PHP-SDK#773]
### Required Information

- PHP Version: 7.1
- PayPal-PHP-SDK Version: 1.11.0
- Debug ID(s): ac76a89ef3ae2

### Issue Description
> Please include as many details (logs, steps to reproduce) as you can to help us reproduce this issue faster.

I get a "Incoming JSON request does not map to API request" error whenever I attempt to make a payment. Below is the code I typed:

        (int)$total = 0;
        (int)$counter = 0;
        $items = [];
        foreach ($specifics as $values) {
            $total += $values['price'] * $values['quantity'];
            $counter++;
            $items[$counter] = new Item();
            $items[$counter]->setName($values['name'])
                ->setCurrency($currency)
                ->setPrice($values['price'])
                ->setQuantity($values['quantity']);
        }        
        
        $itemList = new ItemList();
        $itemList->setItems($items);
        
        $ppDetails = new Details;
        $ppDetails->setShipping(isset($details['shipping']) ? $details['shipping'] : 0)
            ->setTax(isset($details['tax']) ? $details['tax'] : 0)
            ->setSubTotal($total);
        
        $amount = new Amount();
        $amount->setCurrency($currency)
            ->setTotal($total + $details['tax'] + $details['shipping'])
            ->setDetails($ppDetails);
        
        $transaction = new Transaction();
        $transaction->setAmount($amount)
            ->setItemList($itemList)
            ->setDescription(isset($desc) ? $desc : 'Payment made with Paypal')
            ->setInvoiceNumber(uniqid());
            
        $baseUrl = $this->getBaseUrl('result.php');
        $redirectUrls = new RedirectUrls();
        $redirectUrls->setReturnUrl("{$baseUrl}?success=true")
            ->setCancelUrl("{$baseUrl}?success=false");
        
        $payment = new Payment();
        $payment->setIntent('sale')
            ->setPayer($payer)
            ->setRedirectUrls($redirectUrls)
            ->setTransactions([$transaction]);
        
        try {
            $payment->create($this->initiator);
        } catch (\PayPal\Exception\PayPalConnectionException $ex) {
            echo "<br /> Error: {$ex->getCode()} <br/> {$ex->getData()}";
        }
        
        $approvalUrl = $payment->getApprovalLink();
        echo "<a href='{$approvalUrl}'>Pay</a>";
        return $payment;

This error is really annoying and I hope that I can get some help soon.

**Comment by jaypatel512** [comment]
The best way to debug something like this would be to do `$payment->toJson()`before calling `create`, and compare that with developer docs. 

If you can pass that, it would be easier for us to debug too.

**Comment by ace411** [comment]
Thanks. I'll do that and then post my findings.

**Comment by ace411** [comment]
object(stdClass)#17 (4) {
  ["intent"]=>
  string(4) "sale"
  ["payer"]=>
  object(stdClass)#18 (1) {
    ["payment_method"]=>
    string(6) "paypal"
  }
  ["redirect_urls"]=>
  object(stdClass)#19 (2) {
    ["return_url"]=>
    string(45) "http://localhost:8050/result.php?success=true"
    ["cancel_url"]=>
    string(46) "http://localhost:8050/result.php?success=false"
  }
  ["transactions"]=>
  array(1) {
    [0]=>
    object(stdClass)#22 (4) {
      ["amount"]=>
      object(stdClass)#20 (3) {
        ["currency"]=>
        string(3) "USD"
        ["total"]=>
        string(6) "251.25"
        ["details"]=>
        object(stdClass)#21 (3) {
          ["shipping"]=>
          string(4) "1.25"
          ["tax"]=>
          string(1) "5"
          ["subtotal"]=>
          string(3) "245"
        }
      }
      ["item_list"]=>
      object(stdClass)#27 (1) {
        ["items"]=>
        object(stdClass)#24 (3) {
          ["1"]=>
          object(stdClass)#23 (4) {
            ["name"]=>
            string(5) "sugar"
            ["currency"]=>
            string(3) "USD"
            ["price"]=>
            string(2) "30"
            ["quantity"]=>
            int(2)
          }
          ["2"]=>
          object(stdClass)#25 (4) {
            ["name"]=>
            string(9) "chocolate"
            ["currency"]=>
            string(3) "USD"
            ["price"]=>
            string(2) "40"
            ["quantity"]=>
            int(4)
          }
          ["3"]=>
          object(stdClass)#26 (4) {
            ["name"]=>
            string(4) "milk"
            ["currency"]=>
            string(3) "USD"
            ["price"]=>
            string(2) "25"
            ["quantity"]=>
            int(1)
          }
        }
      }
      ["description"]=>
      string(14) "Sample Payment"
      ["invoice_number"]=>
      string(13) "589220f467352"
    }
  }
}

**Comment by jaypatel512** [comment]
From the looks of it, the items you are passing in should be an array of item. In your case, it is showing as objects. Please follow the sample code provided at http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/CreatePaymentUsingPayPal.html

This block of code seems to be the culprit.
```php
$items[$counter] = new Item();
        $items[$counter]->setName($values['name'])
            ->setCurrency($currency)
            ->setPrice($values['price'])
```
The request should look something like this:
```php
{
    "intent": "sale",
    "payer": {
        "payment_method": "paypal"
    },
    "redirect_urls": {
        "return_url": "http://localhost:5000/payments/ExecutePayment.php?success=true",
        "cancel_url": "http://localhost:5000/payments/ExecutePayment.php?success=false"
    },
    "transactions": [
        {
            "amount": {
                "currency": "USD",
                "total": "20",
                "details": {
                    "shipping": "1.20",
                    "tax": "1.30",
                    "subtotal": "17.50"
                }
            },
            "item_list": {
                "items": [
                    {
                        "name": "Ground Coffee 40 oz",
                        "currency": "USD",
                        "quantity": 1,
                        "sku": "123123",
                        "price": "7.50"
                    },
                    {
                        "name": "Granola bars",
                        "currency": "USD",
                        "quantity": 5,
                        "sku": "321321",
                        "price": "2"
                    }
                ]
            },
            "description": "Payment description",
            "invoice_number": "589222cc5b58d"
        }
    ]
}
```

Please re-open the issue if the problem still exists. 👍
