### ISSUE TITLE
How can I get payer_id?

### ISSUE THREAD

**Issue by dmorsoleto** [paypal/PayPal-PHP-SDK#774]
I am using this sdk with the javascript box that paypal load an iframe.

I am stuck on this issue. I can't discover how I can get this payer_id...

Can anyone help me, please?

Thanks

**Comment by pp-randy** [comment]
I followed this guide, and the fields were posted to me as `paymentID` and `payerID`.

https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/advanced-integration/#set-up-your-server

Because of this code
```
        onAuthorize: function(data) {
        
            // Note: you can display a confirmation page before executing
            
            var EXECUTE_PAYMENT_URL = 'ExecutePayment.cfm';
            
            paypal.request.post(EXECUTE_PAYMENT_URL,
                    { paymentID: data.paymentID, payerID: data.payerID })
                    
                .then(function(data) { 
                    console.log(data);      
                })
                .catch(function(err) { console.log(err) });
        }
```

**Comment by dmorsoleto** [comment]
Thank you. But I am trying with this sdk and I think I am missing some middle function.

In my app I create the payment with the parameter below after config all needed parameters:
$payment = new Payment();
$payment->setIntent("sale")
    ->setPayer($payer)
    ->setRedirectUrls($redirectUrls)
    ->setTransactions(array($transaction));
try {
    $payment->create($apiContext);
} catch (Exception $ex) {
    echo "error";
}

Then paypal returns me a JSON that I can get the paymentID and the approvalURL, I get this:
$approvalUrl = $payment->getApprovalLink();
$payment_id = $payment->getId();

But in this response not gives me the payerID. And to execute de payment I need this payerID. Which function I need to run that I am missing here?

**Comment by pp-randy** [comment]
You are using the checkout.js version 4 shown here with this SDK? https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/other-integrations/

If so, can you show me the code for your onAuthorize function?

**Comment by pp-randy** [comment]
@dmorsoleto did you get this figured out?  If not please let me know.

**Comment by pp-randy** [comment]
Closing for now, please let me know if you need further assistance.

**Comment by dmorsoleto** [comment]
Sorry, I was in a work travel.

I am working with paypal plus. I am not sure that I need this checkout.js.

I use the code in my other post to generate de approval URL and I complete on this function of paypal plus:

$(".pplus-loading").show(), ppp = PAYPAL.apps.PPP({
		        approvalUrl: $("#approval_url").val(),
		        placeholder: "ppplus",
		        payerFirstName: getFirstName(),
		        payerLastName: getLastName(),
		        payerEmail: getPayerEmail(),
		        payerTaxId: getPayerTaxId(),
		        payerTaxIdType: "BR_CPF",
		        country: "BR",
		        language: "pt_BR",
		        mode: "sandbox",
		        buttonLocation: "outside",
		        enableContinue: "continueButton"
		    });

![screen shot 2017-02-20 at 16 32 52](https://cloud.githubusercontent.com/assets/4205270/23139259/4173b490-f78a-11e6-8bef-917456e2eeb9.png)

After load the widget and send the information filled, I received this result:
{"error":"MISSING_EXPERIENCE_PROFILE_ID","resolution":"MISSING_EXPERIENCE_PROFILE_ID"...

This error is about payer_id, isn't it?

thanks for help

**Comment by vijayvvm** [comment]
Hi, Was checking this through and remembered a similar one we faced. This is from the Integration Guide : 

 "PayPal Plus requires that you create an experience profile.  The steps to follow to create a profile can be found on the PayPal Developer Portal under Payment Experience Web Profiles.  The profile must include the parameters no_shipping and address_override set to 1 in the property input_fields."
 
Apparently, PayPal Plus checks this Profile ID to accept the payments.

**Comment by pp-randy** [comment]
Thank you @vijayvvm.

@dmorsoleto the sample is here https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payment-experience/CreateWebProfile.php#L38-L42, try setting both as 1 as @vijayvvm suggests.

**Comment by dmorsoleto** [comment]
Thank you @vijayvvm and @pp-randy.

I do this before create payment or after?

**Comment by pp-randy** [comment]
You Create the Web Profile and supply the profile id in payment calls.  Supply it with the payment using  `setExperienceProfileId` method of payment https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Api/Payment.php#L400-L411

The good news is you should only need to create the web profile once and reuse its id if no_shipping and address_override are the only values you are setting.
