### ISSUE TITLE
Paypal Login Session

### ISSUE THREAD

**Issue by shigawaka** [paypal/PayPal-PHP-SDK#777]
### Required Information

- PHP Version:
- PayPal-PHP-SDK Version:
- Debug ID(s):

### Issue Description
> Please include as many details (logs, steps to reproduce) as you can to help us reproduce this issue faster.

Well, I was wondering if it is possible to automatically logins the user in paypal everytime they checks out?

_Given the scenario a new user registers in my site._

`New User->Logins to paypal->get permissions(etc..)->approve->gets back to my site`

So, everytime the user checks-out it automatically logins in paypal.

I saw the documents but it is just too much for me to comprehend.

**Comment by bluk** [comment]
The user/customer must choose to automatically login (usually by checking the `Stay logged in for faster checkout` option). Depending on their security settings, they may not need to login for some time.

**Comment by shigawaka** [comment]
Well, I was thinking that if the customer logs out then the paypal session would be gone by then?

**Comment by shigawaka** [comment]
I would like to link his paypal account to his profile in my site thus easier check out

**Comment by bluk** [comment]
I would recommend that you look into [Braintree Payments's PayPal Vault flow](https://developers.braintreepayments.com/guides/paypal/vault/javascript/v3) which allows you to charge in the future without having the customer re-authenticate. Braintree is a PayPal owned company, and you will need to setup an account with Braintree.

If these are regular payments / subscriptions, you can look into either Braintree's subscription service or PayPal's [billing agreements](https://developer.paypal.com/docs/integration/direct/billing-agreements/) as well.
