### ISSUE TITLE
DPRP DISABLED

### ISSUE THREAD

**Issue by dhavalbera9898** [paypal/PayPal-PHP-SDK#780]
### Issue Description
> I am getting error in billing recurring profile in paypal using credit card with sandbox account 
Billing agreement plan created successfully but for billing agreement i get following response.

How can i enable DPRP ?

{
    "name": "DPRP_DISABLED",
    "message": "DPRP is disabled for this merchant.",
    "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#DPRP_DISABLED",
    "debug_id": "b2696e4c2cc91"
}

**Comment by xiaoleih41** [comment]
Thank you for your questions. Unfortunately, it appears to me that this function is not available to UK sandbox account at this time. Please consider to open a US pro account instead to testing this feature. In the mean time I will follow up further internally. 

internal tracking: PPPLMER-26782

**Comment by dhavalbera9898** [comment]
Thank you for your quick response. 
As per your instruction, I created new US pro account, still i am facing same issue.
What information would you like to have to check it?

Waiting for your response.

**Comment by pp-randy** [comment]
We should be able enable it on the US account.  What is the email address? 

Updated internal tracking: PPPLMER-26632

**Comment by dhavalbera9898** [comment]
email:-  dhavalbera9898@gmail.com
 
"debug_id": "9f5b89a4764f8"

**Comment by pp-randy** [comment]
@dhavalbera9898 can you create a US Business Account in sandbox and put pro on it?  You can do this at https://developer.paypal.com/developer/accounts/ after logging in. 

We have an issue with UK accounts and enabling DPRP in sandbox currently.

**Comment by dhavalbera9898** [comment]
I was create a  US Business Account in sandbox and put pro on it see the attachment .

Request Object

{
    "name": "DPRP",
    "description": "Payment with credit Card",
    "start_date": "2019-06-17T9:45:04Z",
    "plan": {
        "id": "P-6AC21829U3194605GMRPOHNA"
    },
    "payer": {
        "payment_method": "credit_card",
        "payer_info": {
            "email": "niravpatel.root@gmail.com"
        },
        "funding_instruments": [
            {
                "credit_card": {
                    "type": "visa",
                    "number": "4032031950038975",
                    "expire_month": "03",
                    "expire_year": "2022",
                    "cvv2": "159"
                }
            }
        ]
    },
    "shipping_address": {
        "line1": "111 First Street",
        "city": "Saratoga",
        "state": "CA",
        "postal_code": "95070",
        "country_code": "US"
    }


and I get 

Response Object

 Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/billing-agreements/.

{
    "name": "DPRP_DISABLED",
    "message": "DPRP is disabled for this merchant.",
    "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#DPRP_DISABLED",
    "debug_id": "ab095d0358ea3"
}
![test_account](https://cloud.githubusercontent.com/assets/25740532/23198971/1aac674a-f8f1-11e6-9ca6-a6273e45e48a.png)

**Comment by pp-randy** [comment]
@dhavalbera9898 I have added Recurring Payments, please try again and let me know if things are working for you.  Also you might want to use a different payer email other than `"email": "niravpatel.root@gmail.com"`, being the same as your merchant account has the potential to throw an error especially if you attempt a PayPal funded payment.

**Comment by umeshadroit** [comment]
@pp-randy We are facing the same issue "DPRP is disabled for this merchant.". We have created a US Business Pro Account in sandbox, can you please enable it for the merchant account 'umesh_1333032404_biz@adroitcoders.com'.

Thanks.

**Comment by pp-randy** [comment]
@umeshadroit you should be good.  I need to followup and have this be automatic...

**Comment by umeshadroit** [comment]
@pp-randy Thank you for your quick response, Things are working as expected now.

Thanks.

**Comment by t1gerr** [comment]
@pp-randy We have a US pro account and everything works when we in sandbox mode, but have the same issue on live mode:

{
	"status": 400,
	"duration_time": 312,
	"body": {
		"message": "DPRP is disabled for this merchant.",
		"debug_id": "d36230d74074a",
		"information_link": "https://developer.paypal.com/webapps/developer/docs/api/#DPRP_DISABLED",
		"name": "DPRP_DISABLED"
	},
	"additional_properties": {},
	"header": {
		"Date": "Tue, 11 Apr 2017 15:25:37 GMT",
		"paypal-debug-id": "d36230d74074a",
		"Content-Language": "*"
	}
}

Please help!

**Comment by pp-randy** [comment]
@t1gerr since you are seeing this issue in Production you should contact [PayPal Customer Support](https://www.paypal.com/help) in regards to getting the Recurring Payments product added to the account.

**Comment by t1gerr** [comment]
@pp-randy Thank you for your quick reply! Our account is 	PayPal Payflow Pro and Recurring billing is also enabled in PayPal Manager. Everything works fine in sandbox mode, just got this issue in live mode.

**Comment by pp-randy** [comment]
PayPal Manager Recurring Billing is part of the Payflow Pro product line and is a different product.  

The error indicates your PayPal account is not enabled to support Direct Payment Recurring Payments.

Do you have both Subscriptions and Direct credit cards enabled for live in your Account Status?  https://developer.paypal.com/developer/accountStatus

**Comment by t1gerr** [comment]
@pp-randy looks like all options are checked on our account. Is there any way I can know the sdk is using 'PayPal Manager Recurring Billing' or 'Direct Payment Recurring Payments'? Can I config it? I just refer the sample code from [PayPal PHP SDK](https://paypal.github.io/PayPal-PHP-SDK/sample/#billing). And again, I don't have this issue on sandbox mode. Thanks for you kind help!
![account_status](https://cloud.githubusercontent.com/assets/2357992/24937098/67c69754-1efc-11e7-8eac-d7611eb74c88.JPG)

**Comment by pp-randy** [comment]
Its a Production account setting, you will need Customer Service help.  I can only help with the setting for Sandbox accounts.  https://www.paypal.com/help

**Comment by chandraumc** [comment]
Hi I am trying the same and I am getting error for Paypal Sandbox for Cananda. DPRP is disabled.
debug_id":"283b2e0d4e870"
I have already upgraded to business pro account but getting this error for recurring payment agreement.

**Comment by pp-randy** [comment]
@chandraumc can you try with a new account and adding Pro again, or see if it still give you the Pro option for this account?  I'm not seeing Pro being enabled and I am having issues adding it.

Also I think US accounts will have DPRP enabled for them out of the box.

**Comment by chandraumc** [comment]
thanks randy for your reply, but do tell me is there any restriction in Canada to create the Pro account with dprp enabled.

**Comment by pp-randy** [comment]
There shouldn't be, but with any integration that requires vetting on live you should ensure you get it before dedicating a lot of development time.  Have you discussed your needs with a PayPal sales team?

**Comment by psavard** [comment]
Hello @pp-randy,

I need my DPRP to be enable for my sandbox account. Can you help me with this please?

My account email is billing-facilitator@totalcoaching.com

Let me know if you need anything else.

Thank you very much!

**Comment by pp-randy** [comment]
@psavard are you approved for this feature on your live account?  If so, I will help you get this enabled in the sandbox.  Otherwise, I would suggest our Braintree offering to see if it will meet your needs https://www.braintreepayments.com/en-my/features/recurring-billing.

**Comment by psavard** [comment]
We are already live with this feature with our live account. We have already to switch to Braintree but it turns out that there's some missing feature with canadian bank account so we have choose to stick with paypal api.

**Comment by pp-randy** [comment]
@psavard due to a sandbox issue I'm not able to enable this feature for any other country but US.  Would you be able to test with a United States account?

**Comment by psavard** [comment]
@pp-randy , I've configured a US sandbox account associated to this e-mail : billing-facilitator-us@totalcoaching.com

Thanks for your help!

**Comment by psavard** [comment]
Hello @pp-randy , did you have time to look at my request?

Thanks!

**Comment by pp-randy** [comment]
@psavard unfortunately, I have needed to escalate this issue internally as I am facing an issue with this US account as well.  I apologize for the inconvenience. 

Since this is a bug not related to the SDK I have created https://github.com/paypal/PayPal-REST-API-issues/issues/167, so please track this issue for further updates.

**Comment by pp-randy** [comment]
Locking the thread, please follow https://github.com/paypal/PayPal-REST-API-issues/issues/167 for further updates.
