### ISSUE TITLE
Reference Transaction not available in this SDK?

### ISSUE THREAD

**Issue by shigawaka** [paypal/PayPal-PHP-SDK#781]
### Required Information

- PHP Version:
- PayPal-PHP-SDK Version:
- Debug ID(s):

### Issue Description
>It seems I cannot find documentation for Reference Transaction in this SDK. I was wondering if it's not available?

Supposedly, I was to use Reference Transaction together with Billing agreement. I intended to use it in order to make the users checks-out faster and linked their paypal to my site.

**Comment by xiaoleih41** [comment]
Reference Transaction is not available in REST API. If you want to use reference transaction, please use classic API instead. PayPal's merchant SDK supports reference transactions. https://github.com/paypal/merchant-sdk-php  thanks, Xiaolei
