### ISSUE TITLE
CreditCard::all() gets only 10 cards, NOT all

### ISSUE THREAD

**Issue by thejacer87** [paypal/PayPal-PHP-SDK#782]
The Cards array:

![image](https://cloud.githubusercontent.com/assets/6412919/22993277/4b81a332-f377-11e6-8e6e-95b00f6080b6.png)

The array shows that there are 41 items. But only puts 10 in the array. How can I access the rest?

**Comment by jaypatel512** [comment]
You can use the `page_size` and `page` as mentioned in the developer docs: https://developer.paypal.com/docs/api/vault/#credit-card_list

Look at the [sample code](http://paypal.github.io/PayPal-PHP-SDK/sample/doc/vault/ListCreditCards.html) to see how to pass params into the call.
