### ISSUE TITLE
Wiki INI File

### ISSUE THREAD

**Issue by RumbleFrog** [paypal/PayPal-PHP-SDK#783]
Not sure if this is mentioned, but from what I read, it says that that the INI configuration file is in the relative directory as the script. 

Wouldn't it helpful to mention to disable public access to the INI file or move it above web root directory, it may seem obvious to some, but many left it exposed, and people can access it and get the public & secret key.

**Comment by bluk** [comment]
@RumbleFrog Can you please tell us which documentation you are referring to so we can ensure it is updated? I agree with the suggestion, and you should be able to use the [`PP_CONFIG_PATH` to define a non-public directory](https://github.com/paypal/PayPal-PHP-SDK/wiki/File-based-Configurations).

**Comment by RumbleFrog** [comment]
@bluk Looks like the article has been updated: https://github.com/paypal/PayPal-PHP-SDK/wiki/File-based-Configurations

But also within the composer package, the INI is also publicly accessible.

**Comment by jaypatel512** [comment]
We should not have any `ini` files downloaded during composer, except in `Samples` code. We have updated the wiki with instructions to make sure to use more secure location to store .ini files. Closing this issue now. Thanks for your input.
