### ISSUE TITLE
How can I go live Payout from sandbox with certificate?

### ISSUE THREAD

**Issue by longlysavvycom** [paypal/PayPal-PHP-SDK#784]
### Required Information

- PHP Version: 5.6
- PayPal-PHP-SDK Version: 1.11.0

**Comment by xiaoleih41** [comment]
Payout API is an Advanced RESTful API.  You will have to pass REST APP credentials to go live. Please check into this articles on the steps of enabling Live credentials of Payout API. https://developer.paypal.com/docs/integration/direct/payouts/
Please let me know if you have any further questions.

**Comment by lyhoanglong** [comment]
Hi @xiaoleih41 Paypal send me v.zero SDK Credentials. How can I setup this token into Php SDK? maybe a key in this config?

```
<?php

return array(
  'client_id' => env('PAYPAL_CLIENT', ''),
  'secret' => env('PAYPAL_SECRET', ''),

  'settings' => array(
    // TYPE: sandbox or live
    'mode' => env('PAYPAL_MODE', 'sandbox'),
    'http.ConnectionTimeOut' => 30,
    'log.LogEnabled' => true,
    'log.FileName' => storage_path() . '/logs/paypal.log',

    // Type: 'FINE', 'INFO', 'WARN' or 'ERROR'
    'log.LogLevel' => env('PAYPAL_LOG_LEVEL', 'ERROR'),
  )
);
```

**Comment by codetay** [comment]
Go to https://developer.paypal.com/ then create an app, get your credentials and go live if you are ready

**Comment by lyhoanglong** [comment]
@codetay my app already live except payout, Paypal send me said that: 'Paypal need us to implement the v.zero SDK Credentials to our website before i can enable the payout functions in the paypal. Credentials like this: developeraccess_token$production$...'. How can I setup Api username, Api password and this token to PHP-SDK?

**Comment by xiaoleih41** [comment]
Can you confirm if you have a REST app created at developer.paypal.com? You will need client ID and secret for your PHP SDK. https://developer.paypal.com/docs/integration/direct/make-your-first-call/#get-an-access-token

**Comment by lyhoanglong** [comment]
@xiaoleih41 Yes, I have client Id and client secret and its work for all api except payout. I asked paypal technical support and he said that payout api not support in Singapore and I have to implement MASS PAY API.

**Comment by xiaoleih41** [comment]
@lyhoanglong  sorry for the late response. You may have to contact your local CS teams to enable masspay setting on your account as payout API is only available to US at this time. Once mass pay setting is enabled, your Payout REST may work afterwards. As it's more of business feature limitation. I am closing this ticket. Thanks, Xiaolei
