### ISSUE TITLE
Paypal sdk Get payment by id

### ISSUE THREAD

**Issue by maniJoe** [paypal/PayPal-PHP-SDK#786]
I am getting this error using java

ERROR HttpConnection - Response code: 404	Error response: {"name":"INVALID_RESOURCE_ID","message":"Requested resource ID was not found.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INVALID_RESOURCE_ID","debug_id":"7d567f0d5fee2"}

**Comment by pp-randy** [comment]
What is the URL you are attempting to get?

**Comment by pp-randy** [comment]
Closing due to lack of response.
