### ISSUE TITLE
Is it possible to receive payments in debit/credit card?

### ISSUE THREAD

**Issue by shigawaka** [paypal/PayPal-PHP-SDK#789]
### Required Information

- PHP Version:
- PayPal-PHP-SDK Version:
- Debug ID(s):

### Issue Description
Hi, I tried this method in a payment when the facilitator is not the receiver. [Here](http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/CreateThirdPartyPayment.html)

I was wondering if the receiver instead of the paypal email can put his Debit/Credit Card?

**Comment by pp-randy** [comment]
@shigawaka are you asking if the payment can be sent directly to credit card?  If so, then the answer is no as the payment needs to be sent to a PayPal Account.
