### ISSUE TITLE
Get related transactions to get the converted amount in paypal

### ISSUE THREAD

**Issue by mcordoba** [paypal/PayPal-PHP-SDK#790]
### Required Information

- PHP Version: 7.0.15
- PayPal-PHP-SDK Version: 1.10.0
- Debug ID(s):

### Issue Description

Hi, is it possible to get the related transactions? I have my account in EUR and I am receiving payments in USD and the amount is automatically converted to EUR.

I need to get through the API the amount converted to EUR. I can't see anywhere how to do it. The only thing I have seen in the documentation is the property receivable_amount but I dont get this info in the response.

I have attached a photo where I need to get the value underlined in green.
![paypal](https://cloud.githubusercontent.com/assets/1489586/23373665/4cbfd896-fd21-11e6-82c3-4e526eb70058.jpg)

Any ideas?

Thank you so much

**Comment by xiaoleih41** [comment]
You’ll need to look at the `related_resources` object in the response.  This will have a `sale` object in it, and this will have a `receivable_amount` object that will have the details of what was deposited into your PayPal account."
To retrieve it, the code should be like below. 

```PHP
$transactions = $payment->getTransactions();
$relatedResources = $transactions[0]->getRelatedResources();
$sale = $relatedResources[0]->getSale();
$finalAmount = $sale->getReceivableAmount();
```

**Comment by xiaoleih41** [comment]
Please let me know if you have any additional questions.

**Comment by mcordoba** [comment]
Hi,

Thank you for your response. The thing is that my sale object doesnt have the receivable amount field.

I have choose to automatically convert other currencies into EUR when I receive a payment so it always has the amount in EUR that I need to get but is I cant find this field.

Sorry, maybe I am doing something wrong...

**Comment by pp-randy** [comment]
@mcordoba try looking up the sale directly https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/sale/GetSale.php#L25, put in the transaction id here instead of doing an additional Sale creation and see if it gives back what is needed.

**Comment by mcordoba** [comment]
@pp-randy yep I did that too but no luck. Any related transaction nor receivable_amount.

Im just doing:

		var_dump(PayPalSale::get('XXXXXXXXXXXX', $apiContext));

I have attached the response.
[response.txt](https://github.com/paypal/PayPal-PHP-SDK/files/814142/response.txt)

Any idea?

**Comment by pp-randy** [comment]
Can you toss me the transaction id?  I will see if I can replicate.

**Comment by mcordoba** [comment]
I thought it should be private and for that I hid it.

Here you have: 0SW05404NW447233T

If not, I will edit the comment to hide it.

**Comment by pp-randy** [comment]
Not sandbox... OK I have removed it, sorry I usually assume people are in sandbox.

**Comment by mcordoba** [comment]
Yes, I was trying with a real transaction that I know there is related transactions with the currency conversion. In that transaction I only see the amount in USD but not the EUR I have received which is 37,66 EUR.

I really appreciate your help.

**Comment by pp-randy** [comment]
I apologize @mcordoba I did further testing and the currency receivable_amount appears to only be on the actual execute response, and was not available with a direct payment or sale lookup.  I will submit a feature request for the receivable_amount added to the payment lookup.

**Comment by pp-randy** [comment]
I have submitted https://github.com/paypal/PayPal-REST-API-issues/issues/21 to track this further.

**Comment by mcordoba** [comment]
Thank you so much. I'll be aware :)
