### ISSUE TITLE
The recipient is unable to accept payment

### ISSUE THREAD

**Issue by Ruchitapuri** [paypal/PayPal-PHP-SDK#791]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description

Hi,

Payout api is working fine with sandbox account, but with live it shows mass payment status as denied(The recipient is unable to accept payment), using USD currency.
For app have enabled payouts for both sandbox and live, see image attached.

![paypalerror](https://cloud.githubusercontent.com/assets/26251285/23658248/bebbccc4-0367-11e7-9fa7-e631074acf13.png)

**Comment by ndoctor13** [comment]
I have the same issue. Anyone know the reason?

**Comment by ppmtscory** [comment]
Please file a ticket with our [Merchant Tech Support team](https://www.paypal-techsupport.com/app/ask) with the account number information (email addresses are fine) for both the sender and the receiver so they can look up the specific denial.  They'll be able to tell you why it was denied.
