### ISSUE TITLE
Same user, one purchase - approve multiple Billing Agreements possible?

### ISSUE THREAD

**Issue by dnsnx** [paypal/PayPal-PHP-SDK#792]
Hi there, 

Sorry, if this is the wrong place to ask my question, but actually I did not know where else.
My question is,, if it is possible to execute / approve multiple billing agreements from one user at the same purchase? 

We created a shop where the user can buy different modules for different periods. If a user buys 2 or more modules we want to create for each module a billing agreement (i.e. 12 months). If I understand the API correctly, every module or every billing agreement has to be approved independently. 
Is there a way to let the user approve the billing agreement once for all modules at all? Or can we create a billing plan with multiple modules in it?

Thanks for your help in advance.

**Comment by xiaoleih41** [comment]
There's no way to approve multiple billing agreement in one process. Thanks, Xiaolei. Your customer will have to approve them individually. thanks, Xiaolei
