### ISSUE TITLE
Unable to use Sandbox, getting 'Internal Error' (10002)

### ISSUE THREAD

**Issue by umeshadroit** [paypal/PayPal-PHP-SDK#795]
We are getting 'Internal Error' (10002) from last 3 days for merchant account 'umesh_1333032404_biz@adroitcoders.com'.

[{"L_ERRORCODE":"10002","L_SHORTMESSAGE":"Internal Error","L_LONGMESSAGE":"Oops! We have encountered an unexpected error, please try again.","L_SEVERITYCODE":"Error"}]

Can you please look into this issue.

Thanks.

**Comment by pp-randy** [comment]
There is a sandbox  issue is being tracked here: https://www.paypal-notify.com//eventnotification/event_details?eventId=7782 appears to still be on going.

**Comment by umeshadroit** [comment]
It's currently showing resolved status, but still not working on our end, showing same error.

"Resolved: This issue has been resolved as of Mar 10, 2017 05:30 AM IST. "

Thanks.

**Comment by pp-randy** [comment]
@umeshadroit can you get me a correlation id from the error?  I will look further.

**Comment by umeshadroit** [comment]
Getting following response from the 'SetExpressCheckout' call:

    [ACK] => Failure
    [TIMESTAMP] => 2017-03-13T05:01:24+00:00
    [CORRELATIONID] => 0
    [L_ERRORCODE0] => 10002
    [L_SHORTMESSAGE0] => Internal Error
    [L_LONGMESSAGE0] => Oops! We have encountered an unexpected error, please try again.
    [L_SEVERITYCODE0] => Error

Thanks.

**Comment by umeshadroit** [comment]
Can I get a feedback on the above please?

**Comment by umeshadroit** [comment]
I am still unable to use Sandbox, can you please look into this.

Thanks.

**Comment by pp-randy** [comment]
@umeshadroit I apologize for the delay.  I do not see logs for your account in sandbox either.  Do any of your responses have a correlationid with a value other than 0?
`[CORRELATIONID] => 0`

Would you able to test with a different account as well to rule out account issues?  What type of API call are you making?  I will try to reproduce this as well.

**Comment by pp-randy** [comment]
I added an edit, the error code doesn't match the short message.  If this is a 10002, which is authentication error it could explain why I didn't see logs under your account.  You would need to pass authentication for the logs to show up on your account.  Without a correlation id value it is hard to diagnose this issue.  Do you have the full response?  It is possible something isn't' being parsed in the response correctly.

**Comment by pp-randy** [comment]
@umeshadroit were you able to resolve this?

**Comment by umeshadroit** [comment]
Yes, its working now.

Thanks.
