### ISSUE TITLE
Unknown Error (Direct Credit Card Payments)

### ISSUE THREAD

**Issue by varunp5814** [paypal/PayPal-PHP-SDK#796]
### General information

* SDK/Library version: PayPal-Php-sdk
* Environment: Laravel 5.2
* `PayPal-Debug-ID` values: "debug_id":"a9d0c9cb7d5e", "debug_id":"ac21e7b4d8b47"
* Language, language version, and OS: PHP 7.0 on Ubuntu 16.10 

### Issue description

Getting Error : Unknown Error when i try to use Direct Card Payments (Using sandbox account credit cards)

**Comment by jaypatel512** [comment]
What test credit card are you using ? Please refrain from using `411111...`, or similar popular credit card numbers for testing in sandbox. The cards are extremely overused in our sandbox, and causes corner case issues. Please use any random credit card number, that you can generate from tools available online over the internet. Please re-open if that does not fix the issue.
