### ISSUE TITLE
Could someone help me how to start the paypal api step by step.

### ISSUE THREAD

**Issue by engharb** [paypal/PayPal-PHP-SDK#799]
Dears,
I'm a beginner in using the paypal_api_plus. I want to learn step by step how is the configuration and integration of PayPal-PHP-SDK in my project?

Best regards,

**Comment by jaypatel512** [comment]
You can follow the instructions to use and integrate `PayPal-PHP-SDK` here : https://github.com/paypal/PayPal-PHP-SDK/wiki

You will find all interesting information at http://paypal.github.io/PayPal-PHP-SDK/
