### ISSUE TITLE
How to use setTax()?

### ISSUE THREAD

**Issue by suntrop** [paypal/PayPal-PHP-SDK#801]
I can't see how/what is setTax() meant for. Is it the absolute value of the VAT included or will it come on top? Or perhaps it is the tax rate?

I can't see the tax anywhere on the PayPal website/sandbox

```
$items[$count]->setName($cart_item->product_title)
				->setDescription('#: ' . $cart_item->product_number)
				->setCurrency('EUR')
				->setQuantity($cart_item->quantity)
				->setPrice($cart_item_price)
				->setTax('11.22')
				->setUrl($cart_item->product_original_page->httpUrl);

```
Nothing helpful there 
http://paypal.github.io/PayPal-PHP-SDK/docs/class-PayPal.Api.Item.html#_setTax

**Comment by xiaoleih41** [comment]
Thank you for your question. It's the absolute amount of the tax for that specific item. It's not a tax rate. 
The definition is listed [here] (https://developer.paypal.com/docs/api/payments/#definition-json_patch)
Please let me know if you have any further questions.  Thanks, Xiaolei

**Comment by pp-randy** [comment]
@xiaoleih41 is correct that tax is at the item level.  You can set the overall tax amount in the details using setTax shown here https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/CreatePayment.php#L71-L78.  You would use setTax for VAT as well.
