### ISSUE TITLE
Getting Internal Server Error While Executing Agreement SandBox

### ISSUE THREAD

**Issue by sufyan297** [paypal/PayPal-PHP-SDK#802]
paypal-debug-id →283bda0bee7bd, 283bda0bee7bd
Mode: Sandbox
URI: https://api.sandbox.paypal.com/v1/payments/billing-agreements/EC-xxx/agreement-execute

Error:
`<ns1:XMLFault xmlns:ns1="http://cxf.apache.org/bindings/xformat">
    <ns1:faultstring xmlns:ns1="http://cxf.apache.org/bindings/xformat">java.lang.NullPointerException</ns1:faultstring>
</ns1:XMLFault>`

it was working fine 2 hours ago now getting this error... Please fixed this... i tried with Postman after getting this error on my code.

**Comment by alxanthony** [comment]
@sufyan297 Did you ever figured this out? Im having the same problem.
