### ISSUE TITLE
Wrong total label

### ISSUE THREAD

**Issue by suntrop** [paypal/PayPal-PHP-SDK#803]
The PayPal website is missing my $total and just shows "Subtotal" … but with the correct total amount.

The part from the $transaction object:
```
[amount] => PayPal\Api\Amount Object
(
	[_propMap:PayPal\Common\PayPalModel:private] => Array
		(
			[currency] => EUR
			[total] => 490.80
			[details] => PayPal\Api\Details Object
				(
					[_propMap:PayPal\Common\PayPalModel:private] => Array
						(
							[shipping] => 45
							[subtotal] => 445.80
						)

				)

		)

)
```

![paypal_checkout_-_log_in](https://cloud.githubusercontent.com/assets/1328092/23890369/e0b4615e-0891-11e7-9257-011579aaccc2.png)

**Comment by jaypatel512** [comment]
Hey @suntrop !

I think the PayPal UI is misrepresenting `Total` with `SubTotal` here. I have moved this issue to our API issue tracker, as this is not an SDK bug.
