### ISSUE TITLE
Presentation setLogoImage doesn't change logo

### ISSUE THREAD

**Issue by javray** [paypal/PayPal-PHP-SDK#804]
### General information

* SDK/Library version: 1.11.0
* Environment:  Production
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: PHP

### Issue description

Using method setLogoImage to define de company logo doesn't do anything. setBrandName works fine but setLogoImage doesn't.

I see the page with old logo and can't change it.

This is my code:

require_once __DIR__ . '/bootstrap.php';

  use PayPal\Api\FlowConfig;
  use PayPal\Api\Presentation;
  use PayPal\Api\InputFields;
  use PayPal\Api\WebProfile;
  use PayPal\Api\PayPalConnectionException;

  $flowConfig = new FlowConfig();
  $presentation = new Presentation();

  $presentation
    ->setLogoImage('https://www.XXXX.com/img/logo.png')
    ->setBrandName('XXXXX')
    ->setLocaleCode('ES')
    ->setReturnUrlLabel('Volver')
    ->setNoteToSellerLabel('!Gracias!');

  $inputFields = new InputFields();

  $inputFields
    ->setAllowNote(true)
    ->setNoShipping(1)
    ->setAddressOverride(0);

  $webProfile = new WebProfile();

  $webProfile
    ->setName('XXXXX' . uniqid())
    ->setFlowConfig($flowConfig)
    ->setPresentation($presentation)
    ->setInputFields($inputFields)
    ->setTemporary(true);

  try {
    $createProfileResponse = $webProfile->create($apiContext);
  }
  catch (PayPalConnectionException $ex) {
    header('HTTP/1.1 412 Error al crear perfil');
    exit(1);
  }

**Comment by jaypatel512** [comment]
Hey @javray !

We were able to see the logo working properly as expected.

Make sure you use the `id` returned in `$createProfileResponse` and set it in each payment request you wish to see that logo.

```php
... Your normal payment object...

$payment->setPaymentExperienceId("12312312312312");

$payment->create(...);
```

This should make this request use all your settings in the payment experience. You can re-use the same experience Id across all your calls.
![screen shot 2017-03-24 at 1 18 38 pm](https://cloud.githubusercontent.com/assets/1309895/24308040/6f34f524-1094-11e7-9129-ca9e076df7da.png)
