### ISSUE TITLE
override_charge_models bugs in SDK

### ISSUE THREAD

**Issue by knifesk** [paypal/PayPal-PHP-SDK#805]
There is an error in the `override_charge_models` part of the `Agreement` class.. If I setup an `addOverrideChargeModel()` I get the following error:
``` 
{
    "name": "MALFORMED_REQUEST",
    "message": "Incoming JSON request does not map to API request",
    "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#MALFORMED_REQUEST",
    "debug_id": "7c89a87f6397f"
}
```

When I check what the SDK is posting I get 
``` 
{
    "name": "Mensual TAX",
    "description": "Mensual TAX",
    "start_date": "2017-03-17T14:12:03-0300",
    "plan": {
        "id": "P-7TP27165HE453514F3U4GP5Y"
    },
    "payer": {
        "payment_method": "paypal"
    },
    "override_charge_models": [
        {
            "id": "CHM-7E797779SS542894F3U4GP5Y",
            "amount": {
                "value": "10.08",
                "currency": "EUR"
            }
        }
    ],
    "override_merchant_preferences": {
        "cancel_url": "https://MY DOMAIN REPLACED/suscripciones/54/cancel",
        "return_url": "https://MY DOMAIN REPLACED/suscripciones/54/confirm"
    }
}
```

Notice the `override_charge_models` objects `id` attribute should be `charge_id` acording to the [REST Docs](https://developer.paypal.com/docs/api/payments.billing-agreements#agreement_create)

**Comment by knifesk** [comment]
Though I still think this is a bug, here's a little work around:

I solved it by just setting the `charge_id` attribute directly without the `setId()` setter method... 
```php
$chargeModel = new ChargeModel();
$chargeModel->setAmount(new Currency(['value' => $amount * $tax, 'currency' => $currency]));
$chargeModel->charge_id = $chm_id; //<- set the charge_id directly instead using the setId() setter

$agreement->addOverrideChargeModel($chargeModel);
```

**Comment by xiaoleih41** [comment]
Thank you for your question. I noticed that you are using **ChargeModel()** instead of **OverrideChargeModel()** class. I would recommend you to use **OverrideChargeModel()** instead as it fits your usecase.  Also, to set charge_id, you should use setChargeId() mentioned [ here ](https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Api/OverrideChargeModel.php#L26). Please let me know if you have any further questions. Thanks, Xiaolei

**Comment by jaypatel512** [comment]
@xiaoleih41 is correct. You need to use `OverrideChargeModel` object, as shown in https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Api/Agreement.php#L26.

**Comment by knifesk** [comment]
Ohhh!!! I see! Thank you guys.. There's so much classes inside the lib that I didn't saw that one.... I'm going to change it right away! thanks!
