### ISSUE TITLE
Could not resolve host: api.paypal.com

### ISSUE THREAD

**Issue by pettazz** [paypal/PayPal-PHP-SDK#806]
### General information

* SDK/Library version: 1.3.2
* Environment: Both!
* Language, language version, and OS: lang=PHP;v=5.5.9-1ubuntu4.21;bit=64;os=Linux_3.13.0-24-generic;machine=x86_64;openssl=1.0.1f;curl=7.35.0

### Issue description

Trying to create a new payment, starting yesterday (with no code changes on our end for months at least) I'm consistently getting an exception with curl errno 6, could not resolve host:

    [url:PayPal\Exception\PayPalConnectionException:private] => https://api.paypal.com/v1/oauth2/token
    [data:PayPal\Exception\PayPalConnectionException:private] => 
    [message:protected] => Could not resolve host: api.paypal.com
    [string:Exception:private] => 
    [code:protected] => 6
    [file:protected] => /var/www/steempb/JACKED/JACKED/lib/paypal-vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php
    [line:protected] => 140

Same error occurs in sandbox mode. Has something just changed that requires an update to the SDK? I'm able to curl the same url from the command line and get a 401.

**Comment by pp-randy** [comment]
That looks like a possible DNS issue to me.  Its odd though if your curl request worked on the same server.  Have you tried restarting the processes this is using to see if it clears up?

**Comment by pettazz** [comment]
That is super weird. I restarted Apache and it seems to be okay now.
