### ISSUE TITLE
Sample List Payments error INTERNAL_SERVICE_ERROR

### ISSUE THREAD

**Issue by gruzintsev** [paypal/PayPal-PHP-SDK#809]
Error when execute /vendor/paypal/rest-api-sdk-php/sample/payments/ListPayments.php

Response

`
-------------------------------------------------------------
        REQUEST:
Array
(
    [count] => 10
    [start_index] => 5
)

        RESPONSE:
ERROR:Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment?count=10&start_index=5.{
    "name": "INTERNAL_SERVICE_ERROR",
    "message": "An internal service error occurred.",
    "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR",
    "debug_id": "27d3c87487540"
}
`

**Comment by eXist73** [comment]
I am also having this exact issue. The other routes on the sand box appear to be ok.  I've made test payments using the **CreatePayment.php** example perfectly fine.

When I attempt to use the **ListPayments.php** example to retrieve these payments, I get the exact same error as you from api.sandbox.paypal.com:

**500 Internal server error.**

Here is my code for access the List Payments route:
```
 public function testListPayment()
    {
        try {
            $params = array('count' => 10, 'start_index' => 5);
            $context = new ApiContext(new OAuthTokenCredential($this->_client_id, $this->_client_secret));
            $context->setConfig(self::testApiConfig());
            $payments = Payment::all($params, $context);
        } catch (\Exception $ex) {
            return $ex;
        }

        return $payments;
    }
```

The error exception object looks something like this:
```
object(PayPal\Exception\PayPalConnectionException)[261]
  private 'url' => string 'https://api.sandbox.paypal.com/v1/payments/payment?count=10&start_index=5' (length=73)
  private 'data' => null
  protected 'message' => string 'Could not resolve host: api.sandbox.paypal.com' (length=46)
  private 'string' (Exception) => string '' (length=0)
  protected 'code' => int 6
  protected 'file' => string '/var/www/web/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php' (length=84)
  protected 'line' => int 122
  ... (more below) ...
```

**Comment by xiaoleih41** [comment]
I am looking into it. I will follow up with detail shortly. Thanks, Xiaolei

**Comment by xiaoleih41** [comment]
Please track this issue at https://github.com/paypal/PayPal-REST-API-issues/issues/54
