### ISSUE TITLE
getTransactions() - further details needed

### ISSUE THREAD

**Issue by AlexKbaum** [paypal/PayPal-PHP-SDK#812]
### General information

* SDK/Library version:
* Environment: live
* Language, language version, and OS: tdb

### Issue description

What transactions are returned 

$transactions = $_payment->getTransactions();
$transaction = $transactions[0];

Will transaction[0] give always the latest? What if multiple transactions are within this array?

**Comment by pp-randy** [comment]
@AlexKbaum I have not seen multiple transactions in the transactions array.  I think it was designed to support parallel payments; however, that is not implemented at this time.  You should expect only one transaction in the array in my experience. 

The related_resources in the transaction on the other hand is usually oldest to newest.  This will probably have the additional transactions you are looking for.  You can get more on on related_resources described in the [transaction definition](https://developer.paypal.com/docs/api/payments/#definition-transaction). 

Let me know if you have further questions.
