### ISSUE TITLE
Third Party with multiple payees

### ISSUE THREAD

**Issue by RobertoDonPedro** [paypal/PayPal-PHP-SDK#813]
### Issue description
Hi, I am checking out the third party payments and could make some calls like in the sample
http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/CreateThirdPartyPayment.html

But unlike the sample I do not have just one but multiple payees. I tried to add transactions with different payees but this did now work.

Is third party not the correct approach for multiple payees? If not, which is the correct REST approach which is available right now?

Thx, Robert

**Comment by pp-randy** [comment]
Unfortunately, the REST API does not support parallel payments.  This is being tracked here: https://github.com/paypal/PayPal-REST-API-issues/issues/2

The Braintree Marketplace offering might work for you https://www.braintreepayments.com/en-au/products/braintree-marketplace

The Merchant API does have parallel payments, the `PAYMENTREQUEST_n_SELLERPAYPALACCOUNTID` field is a key piece to that https://developer.paypal.com/docs/classic/api/merchant/SetExpressCheckout_API_Operation_NVP/

**Comment by RobertoDonPedro** [comment]
Unfortunately Braintree marketplace is not available in the EU and will not be soon.

With EC Parallel Payment the buyer sees the commission the marketplace gets, which I hoped is possible to avoid.


Am 28.03.2017 um 16:36 schrieb Randy <notifications@github.com<mailto:notifications@github.com>>:


Unfortunately, the REST API does not support parallel payments. This is being tracked here: paypal/PayPal-REST-API-issues#2<https://github.com/paypal/PayPal-REST-API-issues/issues/2>

The Braintree Marketplace offering might work for you https://www.braintreepayments.com/en-au/products/braintree-marketplace

The Merchant API does have parallel payments, the PAYMENTREQUEST_n_SELLERPAYPALACCOUNTID field is a key piece to that https://developer.paypal.com/docs/classic/api/merchant/SetExpressCheckout_API_Operation_NVP/

**Comment by pp-randy** [comment]
REST Option: 
Your Marketplace accepts the initial payment then uses payouts.  

NVP / SOAP (Classic} API Options:
Express Checkout Parallel payments to your receivers.  Have billing agreements in place with your receivers then charge them with [DoReferenceTransaction](https://developer.paypal.com/docs/classic/api/merchant/DoReferenceTransaction_API_Operation_NVP/)  for your marketplace service or you could send them an invoice charging for services.

**Comment by RobertoDonPedro** [comment]
Ad 1) Then the marketplace is liable which is not appreciated

Ad 2) reference transactions are not approved by PayPal below a monthly turnover of € 10.000 in many countries. I experienced this with retries of failed billing agreements. If you mean this kind of reference transactions..?

And this approach would not be reflected in the commissions reporting,..,



Am 28.03.2017 um 18:03 schrieb Randy <notifications@github.com<mailto:notifications@github.com>>:


REST Option:
Your Marketplace accepts the initial payment then uses payouts.

NVP / SOAP (Classic} API Options:
Express Checkout Parallel payments to your receivers. Have billing agreements in place with your receivers then charge them with DoReferenceTransaction<https://developer.paypal.com/docs/classic/api/merchant/DoReferenceTransaction_API_Operation_NVP/> for your marketplace service or you could send them an invoice charging for services.

**Comment by xiaoleih41** [comment]
If you can't get approved for reference transaction, you can try www.paypal-apps.com for adaptive payment preapproval payment. The API is scheduled to be deprecated but it won't be sunset. The approval process should be easier if you explain  your business case well in the description. For more detail, please check [ here](https://developer.paypal.com/docs/classic/adaptive-payments/ht_ap-basicPreapproval-curl-etc/)
Thanks, 
Xiaolei

**Comment by RobertoDonPedro** [comment]
Well, adaptive payments is the method where I came from. A customer told me that he does not get it approved, that's why I looked for new possibilities. But obviously there are non available, so I do not quite understand why this was depreciated.

I myself explained well what I want to to do (I think..:-), now it's "approved conditionally"  (not sure what it means but I think it means it does not work in production... yet ).

However the drawback with adaptive parallel is the same like with EC parallel - the customer sees the commission the marketplace gets. I wanted to solve this, too with a regular payment for the buyer and split like parallel just behind the scenes.

Thx, Robert

Sent from my iPhone

Am 28.03.2017 um 19:21 schrieb Xiaolei Wheelock <notifications@github.com<mailto:notifications@github.com>>:


If you can't get approved for reference transaction, you can try www.paypal-apps.com<http://www.paypal-apps.com> for adaptive payment preapproval payment. The API is scheduled to be deprecated but it won't be sunset. The approval process should be easier if you explain your business case well in the description. For more detail, please check here<https://developer.paypal.com/docs/classic/adaptive-payments/ht_ap-basicPreapproval-curl-etc/>
Thanks,
Xiaolei

**Comment by xiaoleih41** [comment]
Hi Robert, I hope you have found the solution.  To avoid letting customer to see the commission. you can do parallel on all merchant payments but preapproval payment with each merchants. So that when a merchant receives payments, the system can auto calculate the commission amount and charge your merchant the commission through preapproval payment token that you acquired from the merchant when you have onboarded them. In this case, the customer will not be able to see the commission part as it was done by a seperate transaction but both the merchant and you will pay for the PayPal fee of the commission part.

**Comment by RobertoDonPedro** [comment]
Hi Xiaolei,  thanks for checking in. Yes, I am aware that I could do it this way. However, I then would need to develop a completely new commissioning system, too. That would not be an issue and I would do it, but I'd rather not develop a new solution based on an technology that's depreciated yet... That's my concern.
As I said, I do not understand, why you depreciate functionality if you do not have alternatives available broadly.  Personally I believe that your REST API very urgently would need a solution like this. 
Thx, Robert

**Comment by xiaoleih41** [comment]
I totally agree with you that we need a compatible solution for our marketplace partners soon. Hopefully in the next a couple of months.
