### ISSUE TITLE
Paypal REST problem with AdBlock plus

### ISSUE THREAD

**Issue by engharb** [paypal/PayPal-PHP-SDK#815]
Dears,
  I have integrated Paypal_plus in my system. But I still face a problem that the AdBlock plus block the payment request via paypal and give me the following message 'net::ERR_BLOCKED_BY_CLIENT'.

How can I enable the payment via paypal in AdBlock (how to get rid of this problem)?

It's kind of you to help me.

Best regards,

**Comment by pp-randy** [comment]
Please reach out to PayPal Technical Support here:  https://www.paypal-techsupport.com/app/ask.

They should be better able to assist you since this appears to be a browser issue and not directly related to the SDK.
