### ISSUE TITLE
http.ConnectionTimeOut does not work

### ISSUE THREAD

**Issue by max-mathieu** [paypal/PayPal-PHP-SDK#816]
### General information

* SDK/Library version: 1.6.4 - but code is same in current version
* Environment: Both
* `PayPal-Debug-ID` values: N/A
* Language, language version, and OS: PHP 5.5/5.6

### Issue description

The configuration option `http.ConnectionTimeOut` does not change the behavior of the SDK. Requests still timeout after 10s which is the default

Looking at https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Core/PayPalHttpConfig.php, it seems that `http.ConnectionTimeOut` ends up being stored in `$curlOptions['ConnectionTimeOut']` which has no impact on the curl object. Overall, I am not sure when `getHttpConstantsFromConfigs` can be useful, as `curl_setopt_array` expects specific keys.

The tests cover that parameters passed in config are stored in `$curlOptions` but the problem is that they are not being used.

I'll try to propose a PR

**Comment by jaypatel512** [comment]
There is a difference between `CURLOPT_CONNECTTIMEOUT` and `CURLOPT_TIMEOUT`. 

PayPal sets these as defaults:
```
CURLOPT_CONNECTTIMEOUT => 10,
CURLOPT_TIMEOUT => 60
```

If you want to override any of the curl options, you can add that as a config when initializing `apiContext`.

```php
    $apiContext->setConfig(
        array(
            'mode' => 'sandbox',
             ...

            'http.CURLOPT_TIMEOUT' => 1
        )
     );
```

Here is what a quick change in our sample showed:
<img width="1087" alt="screen shot 2017-03-29 at 11 41 29 am" src="https://cloud.githubusercontent.com/assets/1309895/24465958/b3389580-1474-11e7-8297-22512d3059ab.png">


Please re-open this issue if you are still facing this issue. 👍

**Comment by max-mathieu** [comment]
@jaypatel512 Thanks, I guess this was taken from the sample folder pre version 1.x. Fwiw, the tests files still refer to it, so I assumed this was possibly still valid, but the fix is easy on our end. Thanks again

**Comment by jaypatel512** [comment]
We made a lot of improvements, and did a lot of bug fixes on 1.x. I would strongly recommend you use that. I think we may have accidently referred tests to `master`, and so, it incidently, pointed you here. 👍

**Comment by max-mathieu** [comment]
We're on 1.6.4 at the moment, I think the config was not updated accordingly. Thanks for pointing me out that it was effectively deprecated so quickly, much appreciated!
