### ISSUE TITLE
[Question]  reason code of failed payment in recursive payments    

### ISSUE THREAD

**Issue by sarathvsgit** [paypal/PayPal-PHP-SDK#818]
Hi,
      Is there is any method to get the reason code of a failed payment  which is in recursive manner.
 ie if a payment failed in a subscription (recursive billing) , is there any method to track the reason of that failed payment.

**Comment by xiaoleih41** [comment]
Thank you for your question. Currently, we don't have a way to track this type of situation for REST billing agreement API. A feature request was filed recently and please refer to https://github.com/paypal/PayPal-REST-API-issues/issues/15 for the issue status as well as possible alternative product recommendation. Thanks, Xiaolei
