### ISSUE TITLE
Paypal Sandbox Transaction Dates - Changing Timezone

### ISSUE THREAD

**Issue by mistaq** [paypal/PayPal-PHP-SDK#820]
When testing my transactions, although they are now recorded in the Sandbox, the transaction date/time does not match my timezone - is there a way to change this?

Alternatively, what timezone does PayPal Developer use?

**Comment by pp-randy** [comment]
If its a US account it will be Pacific Time.  You can test logging in then trying this link in sandbox: https://www.sandbox.paypal.com/businessprofile/mysettings
or https://www.sandbox.paypal.com/us/cgi-bin/webscr?cmd=_profile-time-zone

You should be able to select some other options relative to the country. 
![image](https://cloud.githubusercontent.com/assets/6819909/24612806/e2e2b40c-184b-11e7-82ce-9de089f40661.png)

**Comment by pp-randy** [comment]
Closing this issue, but let me know if you need further assistance.
