### ISSUE TITLE
cant create payment from saved credit card

### ISSUE THREAD

**Issue by afrakhan123** [paypal/PayPal-PHP-SDK#822]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS:

**Comment by afrakhan123** [comment]
get this response :

{
    "name": "UNKNOWN_ERROR",
    "message": "An unknown error occurred.",
    "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR",
    "debug_id": "67b85d29adfe7"
}

**Comment by afrakhan123** [comment]
Solved this myself. Do not use the default credit card details in the vaulting. get the ones from your sandbox account. Please leave this issue here as I wasted 4 hours messing about when this could have easily been written on the documentation. sort yourself out paypal!

**Comment by pp-randy** [comment]
I apologize you experienced an issue.  By default do you mean the card number in the SDK?  If so, we are tracking that issue here: https://github.com/paypal/PayPal-REST-API-issues/issues/22

**Comment by pp-randy** [comment]
Closing the issue for now since we are tracking the issue already, more details in my previous comment.
