### ISSUE TITLE
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

### ISSUE THREAD

**Issue by veerasarma** [paypal/PayPal-PHP-SDK#824]
When i install the package using composer i got this error 
"Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead."
How can i install and use it please give brief explanation

**Comment by xiaoleih41** [comment]
Please click the [ PayPal-PHP-SDK ](https://github.com/paypal/PayPal-PHP-SDK) link on the top this page, and then click **clone or download" blue button. download, and expand the file. The SDK should be installed correctly.

**Comment by veerasarma** [comment]
We try like this way but we can't run the sample files it says something like "The 'vendor' folder is missing. You must run 'composer update' to resolve application dependencies. Please see the README for more information. "

**Comment by xiaoleih41** [comment]
Please make sure the path to the **vendor** folder is correct. Where do you store your php file? If it's not saved in the sample folder, you may change the path accordingly.

**Comment by xiaoleih41** [comment]
@veerasarma Was the issue resolved? When you use [ Direct Download method 
 ](https://github.com/paypal/PayPal-PHP-SDK/wiki/Installation-Direct-Download), Please click [ releases section ](https://github.com/paypal/PayPal-PHP-SDK/releases) link and download the package from there. You should be able to install it correctly without using composer.
