### ISSUE TITLE
Item amount must add up to specified amount subtotal (or total if amount details not specified)

### ISSUE THREAD

**Issue by c4media** [paypal/PayPal-PHP-SDK#826]
### General information

* SDK/Library version: 1.11.0 
* Environment: Sandbox
* `PayPal-Debug-ID` values: b240850d39bdb
* Language, language version, and OS: PHP 7.1

### Issue description

Hello,
I have searched everywhere and can not find any solution.
When i try to update a payment i got the error. I have no problems creating payments with the same logic. 

Here is the post:

```dump
object(PayPal\Api\PatchRequest)#1086 (1) {
  ["_propMap":"PayPal\Common\PayPalModel":private]=>
  array(1) {
    ["patches"]=>
    array(1) {
      [0]=>
      object(PayPal\Api\Patch)#1083 (1) {
        ["_propMap":"PayPal\Common\PayPalModel":private]=>
        array(3) {
          ["op"]=>
          string(7) "replace"
          ["path"]=>
          string(22) "/transactions/0/amount"
          ["value"]=>
          object(stdClass)#1087 (3) {
            ["total"]=>
            string(8) "1,872.00"
            ["currency"]=>
            string(3) "SEK"
            ["details"]=>
            object(stdClass)#1081 (4) {
              ["subtotal"]=>
              string(8) "1,419.20"
              ["shipping"]=>
              string(5) "63.20"
              ["handling_fee"]=>
              string(5) "15.20"
              ["tax"]=>
              string(6) "374.40"
            }
          }
        }
      }
    }
  }
}
```

Here is the code: 
```php
$patchReplace = new Patch();
            $patchReplace->setOp('replace')
                ->setPath('/transactions/0/amount')
                ->setValue(json_decode('{
                    "total": "'.number_format($order->getTotal(true),2).'",
                    "currency": "'.$paypalOrder->currency.'",
                    "details": {
                        "subtotal": "'.number_format($order->getTotal(false, true, false),2).'",
                        "shipping": "'.number_format($order->deliveryMethodPrice,2).'",
                        "handling_fee": "'.number_format($order->paymentMethodPrice,2).'",
                        "tax": "'.number_format($order->getTotalVat(),2).'"
                    }
                }'));

            $patchRequest = new PatchRequest();
            $patchRequest->addPatch($patchReplace);
try {
                $result = $payment->update($patchRequest, $paypal->getApiContext());

            } catch (\PayPal\Exception\PayPalConnectionException $ex) {
                dd($patchRequest, $payment,  $ex->getCode(),$ex->getData());
                echo $ex->getCode();
                echo $ex->getData();
                dd($ex);
            } catch (Exception $ex) {
                dd($ex);

            }
```

**Comment by pp-randy** [comment]
Did you change the subtotal value?  Are you passing line items details?

**Comment by c4media** [comment]
@pp-randy yes, i have change the subtotal value. And i can`t find any documentation how to change the items?

**Comment by pp-randy** [comment]
Can you explain more about why you are trying to modify the price of your line items?  

[Update payment / patch](https://developer.paypal.com/docs/api/payments/#payment_update) indicates that `You can update the amount, shipping address, invoice ID, and custom data.`  In my understanding a patch for a payment is more along the lines of changing the shipping amount if needed based on the buyers' location.  I was not able to modify line items using a patch.

**Comment by c4media** [comment]
@pp-randy I must be able to change the prices of the items. The price may change after the customer has paid. Or if a change is made or a return.

**Comment by pp-randy** [comment]
You can't patch a payment after it executes.  If a return is made you need to create a refund. 
[payments/#sale_refund](https://developer.paypal.com/docs/api/payments/#sale_refund).

Have you looked into using orders? If the price is variable this may be an option for you since you get some flexibility. 
https://developer.paypal.com/docs/integration/direct/payments/orders/
> The sum of the amounts in any open authorizations for an order cannot exceed 115% or $75, whichever is less, of the amount that you requested when you created the order.

**Comment by xiaoleih41** [comment]
Close this issue as the root of the issue has been identified.
