### ISSUE TITLE
CreatePaymentUsingSavedCard 

### ISSUE THREAD

**Issue by prakher1992** [paypal/PayPal-PHP-SDK#827]
I got this error:
#Response Object
Got 
Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payment.
Plz tell me solution

**Comment by xiaoleih41** [comment]
It  could be caused by an over used sandbox credit card number. Please generate or use your sandbox credit card number for ```CreateCreditCard.php```.  That should take care of the issue. If not, please provide the debug_Id associated with this API call.

**Comment by prakher1992** [comment]
{
    "name": "UNKNOWN_ERROR",
    "message": "An unknown error occurred.",
    "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR",
    "debug_id": "7c25e0cdec977"
}

**Comment by prakher1992** [comment]
Thank you
