### ISSUE TITLE
MALFORMED_REQUEST when using $transaction->setReferenceId()

### ISSUE THREAD

**Issue by PhoneixS** [paypal/PayPal-PHP-SDK#828]
### General information

* SDK/Library version: 1.11.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: 6835f984b6735
* Language, language version, and OS: PHP 5.4 on Ubuntu 16.04

### Issue description

I'm trying to include a identifier in the transaction so I know which transaction is when it returns from Paypal. I've tried to use the reference_id as it's like the better option (because is a temporal identifier that I assign to the transaction).

The problem is that when I set it to the transaction, Paypal refuse to accept the json, it returns:

    {
       "name":"MALFORMED_REQUEST",
       "message":"Incoming JSON request does not map to API request",
       "information_link":"https://developer.paypal.com/webapps/developer/docs/api/#MALFORMED_REQUEST",
       "debug_id":"6835f984b6735"
    }

More or less I use the example code:

    // Create new payer and method
    $payer = new Payer();
    $payer->setPaymentMethod("paypal");

    // Set redirect urls
    $redirectUrls = new RedirectUrls();
    $redirectUrls->setReturnUrl($urlRetorno)
        ->setCancelUrl($urlCancelar);

    // Set payment amount
    $amount = new Amount();
    $amount->setCurrency($moneda)
        ->setTotal($total);

    // Set transaction object
    $transaction = new Transaction();
    $transaction->setAmount($amount)
        ->setDescription($descripcion);

    // If I comment this line it runs ok.
    $transaction->setReferenceId($referenceId);

    // Create the full payment object
    $payment = new Payment();
    $payment->setIntent('sale')
        ->setPayer($payer)
        ->setRedirectUrls($redirectUrls)
        ->setTransactions(array($transaction));

    echo $payment->toJSON();

    // Create payment with valid API context
    try {

        $payment->create($apiContext);

        // Get PayPal redirect URL and redirect user
        $approvalUrl = $payment->getApprovalLink();

        // Finalmente le redirigimos a PayPal para que apruebe el pago
        //redirige($approvalUrl, 'Intentando redirigir a PayPal.');

    } catch (PayPal\Exception\PayPalConnectionException $ex) {
        echo $ex->getCode();
        echo $ex->getData();
        die($ex);
    } catch (Exception $ex) {
        die($ex);
    }

And this is the result (calling toJSON()):

    {
       "intent":"sale",
       "payer":{
          "payment_method":"paypal"
       },
       "redirect_urls":{
          "return_url":"https://example.com/return.php",
          "cancel_url":"https://example.com/cancel.php"
       },
       "transactions":[
          {
             "amount":{
                "currency":"MXN",
                "total":"1515"
             },
             "description":"Suscripci\u00f3n c\u00f3digo PP-19119",
             "reference_id":"304171757041"
          }
       ]
    }

I have found the [reference_id in the API documentation][1] so I supposed I could use it. Maybe this isn't an PHP SDK problem and is more an API problem but I don't really know it.

  [1]: https://developer.paypal.com/docs/api/payments/#definition-transaction

**Comment by jaypatel512** [comment]
The reason why you are getting a malformed request is because, that is a read-only field, and you are trying to set it :)

![screen shot 2017-04-18 at 11 54 28 am](https://cloud.githubusercontent.com/assets/1309895/25142796/cc3ba2a2-242d-11e7-98d7-cdd4bdbd7cd8.png)

**Comment by PhoneixS** [comment]
Where is that documentation? In the reference I have found it said:

![Optional. The merchant-provided ID for the purchase unit](https://cloud.githubusercontent.com/assets/1279539/25142943/f545bc60-2468-11e7-97ab-85dcdf07bd9a.png)

Particularly the "merchant-provided" part.

**Comment by pp-randy** [comment]
Use invoice_number [payments/#definition-transaction](https://developer.paypal.com/docs/api/payments/#definition-transaction)
![image](https://cloud.githubusercontent.com/assets/6819909/25288275/6c62b104-268a-11e7-82a0-5452f40a89de.png)

**Comment by pp-randy** [comment]
We will follow up further on the usage of reference_id in the documentation.

**Comment by pp-randy** [comment]
I have created https://github.com/paypal/PayPal-REST-API-issues/issues/69 to follow up on this issue further.
