### ISSUE TITLE
Paypal get userinfo from refresh token FuturePayment 

### ISSUE THREAD

**Issue by esprajwol** [paypal/PayPal-PHP-SDK#834]
I have paypal refresh token stored on my server. and i want to get the user basic info like profile email using that refresh token. but while trying to the get userinfo there are no such profile info.

```
   $refreshToken = 'R23AAGKvPzMhDzJ....LtWIho91Q5tpwqhRAJZJS4pYoOa9Psh4eYTIwdiIjcFVIMcDaaQPq1Ilb1R60w';
    $tokenInfo = new OpenIdTokeninfo();
    $tokenInfo = $tokenInfo->createFromRefreshToken(array('refresh_token'=> 
$refreshToken), $this->apiContext);
$params = array('access_token' => $tokenInfo->getAccessToken() );
$userInfo  = OpenIdUserinfo::getUserinfo($params, $this->apiContext);
dd($userInfo);

```

the resulted output is this

```
OpenIdUserinfo {#319
 -_propMap: array:1 [
 "user_id" => "https://www.paypal.com/webapps/auth/identity/user/Lo-
 Qp2vr2KOQrIz4OOhWaj6XLEOj2TumkUfAArGKvwM"
 ]
```

I have generated the refreshtoken from the authetication code generated from MOBILE SDK The transaction has to be done for Paypal Future Payment

The reference code used was https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/lipp/GetUserInfo.php

**Comment by pp-randy** [comment]
You need to also request the [email and profile scopes](https://developer.paypal.com/docs/integration/direct/identity/attributes/) in the initial request for user consent.  Then using the refresh_token should return you the information you are requesting. 

Examples: 
https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/lipp/ObtainUserConsent.php#L15

https://github.com/paypal/PayPal-Android-SDK/blob/master/SampleApp/src/main/java/com/paypal/example/paypalandroidsdkexample/SampleActivity.java#L166-L185

**Comment by pp-randy** [comment]
Closing the issue since adding the scopes should resolve this.  Please let me know if you need further help.
