### ISSUE TITLE
Payout Sync Mode - Internal Server Error

### ISSUE THREAD

**Issue by DanielOlarte** [paypal/PayPal-PHP-SDK#835]
### General information

* SDK/Library version: 1.11.0
* Environment: Production
* `PayPal-Debug-ID` values: 99ac5079bcbf
* Language, language version, and OS: Ubuntu 14.04, PHP 7.1

### Issue description

We have two ways to perform payments in our platform:
1. Using payouts in sync mode
2. Using payouts in async mode

If we execute the payments in Sandbox, they work perfectly. But, when we want to execute payouts in sync mode on Production, it gives the following error:

`PayPal\Core\PayPalHttpConnection : ERROR: Got Http response code 500 when accessing https://api.paypal.com/v1/payments/payouts?sync_mode=true. {"name":"INTERNAL_ERROR","message":"An internal service error has occurred.","debug_id":"99ac5079bcbf","information_link":"https://developer.paypal.com/docs/api/payments.payouts-batch/#errors"}
`

We read that the sync mode it's going to be deprecated, but also says that the current integrations will be supported, then, I want to make sure that it's still available for us (we been using this mode since July 2015).

Please, let me know if you need more information.

Thank you

**Comment by xiaoleih41** [comment]
Please submit a ticket at [PayPal technical support](https://www.paypal-techsupport.com/app/ask) on production related questions.

**Comment by pp-randy** [comment]
Were you able to follow up with PayPal Technical Support?  

If not, are you still getting 500s?  If so, can you drop me a new debug_id I was not able to find logs for this failure.   

Since your integration is existing I would not be too concerned since it says you will be supported.

**Comment by DanielOlarte** [comment]
@xiaoleih41 Thank you, I already did

@pp-randy I did it, and we tested it again today, and it's working correctly.

Thank you for your help!
