### ISSUE TITLE
Demo report errors

### ISSUE THREAD

**Issue by lujianzhao** [paypal/PayPal-PHP-SDK#839]
run demo,
but Report errors；
The 'vendor' folder is missing. You must run 'composer update' to resolve application dependencies.\nPlease see the README for more information..

I can't find the "php -f PayPal-PHP-SDK/paypal/rest-api-sdk-php/sample/index.php".

**Comment by xiaoleih41** [comment]
Please refer to https://github.com/paypal/PayPal-PHP-SDK/issues/824 for the correct way of downloading and installing of the SDK.
