### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Octolus** [paypal/PayPal-PHP-SDK#842]
Any way to customize the store name, or other features of the store?

**Comment by pp-randy** [comment]
I think you are looking for [Payment Experience](https://developer.paypal.com/docs/api/payment-experience/) and in particularly the [`presentation`](https://developer.paypal.com/docs/api/payment-experience/#definition-presentation) object. 

Also see the sample for [creating a web experience profile](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payment-experience/CreateWebProfile.php#L25-L33).

**Comment by pp-randy** [comment]
Closing the issue for now, please let me know if further assistance is needed or if you have any other questions.
