### ISSUE TITLE
can i store bankaccount detail in vault ?  vault api support to store bank account detail of user and use in future for payment in php laravel api ?

### ISSUE THREAD

**Issue by axay-ordex** [paypal/PayPal-PHP-SDK#843]
Hello,
I tried to impliment store bankaccount in paypal using vault api using php rest api sdk in laravel. but it throw me error ""Call to undefined method PayPal\Api\BankAccount::create() ". 
i refer below sample code for store bank account detail in vault.

http://paypal.github.io/PayPal-PHP-SDK/sample/doc/vault/CreateBankAccount.html

Please let me know paypal vault support store bank account detail or not ?

**Comment by xiaoleih41** [comment]
I am checking internally on this feature now.

**Comment by xiaoleih41** [comment]
This feature is not available to external developer. It is for internal developers only. You will not be able to store bank info in vault. The content will be removed to avoid future confusion.

**Comment by avwalshaikh** [comment]
@xiaoleih41  Thanks for information. can we use paypal pay flow in php and store client bank account detail ?

**Comment by xiaoleih41** [comment]
Payflow ACH recurring billing is reserved for government agency and school type of entities. Please contact the customer service phone number listed on your account and request to talk to the sales department, the sales representative should be able to help you find the best solution for your specific business needs.
