### ISSUE TITLE
can we use paypal pay flow in laravel ?

### ISSUE THREAD

**Issue by avwalshaikh** [paypal/PayPal-PHP-SDK#847]
i am new in paypal integration in laravel(php). i want to store client bank account detail in my paypal account using ach and i want to cut payment on particular date. is this possible ?

**Comment by xiaoleih41** [comment]
It is not possible to store client bank information in the vault for any future payments. It's a feature only available to PayPal internal development. However you can store credit card information in vault. To get to know more on PayPal *vault feature please check it out [here]( https://developer.paypal.com/docs/integration/direct/vault/?mark=rest%20vault). If you have downloaded PayPal SDK, you can refer to the sample files inside of the [sample folder](https://github.com/paypal/PayPal-PHP-SDK/tree/master/sample/vault). Please note that the ones about vaulting bank account info will be removed soon to avoid any future confusion.

**Comment by avwalshaikh** [comment]
@xiaoleih41 Thanks for your response. one more question can we use payflow pro to store bank account detail of client and deduct a amount on specific date from client bank account ? is there any api  to store bank account detail of client and deduct amount from that on specific date ?

**Comment by xiaoleih41** [comment]
I know there may be a way to do that but it is reserved to certain industry types such as school or government agency. I would recommend you to contact PayPal sales team to get to know about the feature and if you are qualified for it.
