### ISSUE TITLE
Missing Autoload.php

### ISSUE THREAD

**Issue by djeraseit** [paypal/PayPal-PHP-SDK#848]
Missing autoload.php in latest  version for manual installation.

**Comment by jaypatel512** [comment]
Please make sure you download "PayPal-PHP-SDK-1.11.0.zip" file. It includes autoload.php

![screen shot 2017-05-09 at 1 02 53 pm](https://cloud.githubusercontent.com/assets/1309895/25865227/dff22966-34b7-11e7-96a0-1422578568b3.png)

![screen shot 2017-05-09 at 1 04 01 pm](https://cloud.githubusercontent.com/assets/1309895/25865264/fd1724b0-34b7-11e7-8b53-4c389dc7fa91.png)

**Comment by getSwiftly** [comment]
1.13.0 is missing the autoload.php

**Comment by xiaoleih41** [comment]
I cannot reproduce your error. Did you follow the instruction listed exact [here]9https://github.com/paypal/PayPal-PHP-SDK/wiki/Installation-Direct-Download)?

**Comment by SheikMain** [comment]
I still don't see any autoload.php ... Is there a repo out there that contains it?
