### ISSUE TITLE
apicontext mode not working

### ISSUE THREAD

**Issue by cmorsucci** [paypal/PayPal-PHP-SDK#851]
```
$apiContext = new ApiContext(new OAuthTokenCredential($paypalClientID, $paypalSecret));
        $apiContext->setConfig([
            'mode' => 'sandbox',
        ]);
```
If i set the config of api context like in the example above.. the sdk always go in production.. it's a bug?

**Comment by pp-randy** [comment]
Are you using the sdk_config.ini and setting this to live otherwise? 

Does it work if you don't use the short syntax `[ ]` but use `array('mode' => 'sandbox')`?

**Comment by cmorsucci** [comment]
mmm i install the sdk through composer and only set the config like example in my first post..
I tried with array('mode' => 'sandbox') but It does not work equally

**Comment by pp-randy** [comment]
You are using this same context when you create a transaction? What URL are you redirecting the buyer too?  Can you provide the PayPal Debug ID returned in the headers from the API call prior to redirecting the buyer to PayPal?

**Comment by xiaoleih41** [comment]
Closing this thread due to inactivity
