### ISSUE TITLE
Paypal return "400 Unable to refresh access token" after call refresh token

### ISSUE THREAD

**Issue by bob1701** [paypal/PayPal-PHP-SDK#852]
Hello, I use the Paypal SDK to authorize clients on my site, but when I try to get access_token, Paypal returns 400 errors with the description "Unable to refresh access token".

The default example is working.

Please help as I am unable to move forward.

The list of my code:
```
use PayPal\Api\OpenIdTokeninfo;
use PayPal\Api\OpenIdUserinfo;

$refreshToken = 'C21AAHGeO4Ah7vrYzFNmvCxn9wplulKX-TIe17wfWDRIXMPH4MBIRkMN5OCuFUk-QcKBsTD3MWRX3j3tQ4xVcMHLh5pmIl42A';
$clientId = 'AZGKPdDCkeDGNgkje2b__yIWZBUWiDfEifiGJwoiD4ksmCDD4FieN_oW2a82yjcKCyeubAfO2uQZsUwP';
$clientSecret = 'EGwnYPLfXB8NSXCIeJho23kPw9hXxWiP22LaP8gmFjPDL5XX3TGFpEUn1m4ascle7727pX5fWEHAy5V9';
$apiContext = new \PayPal\Rest\ApiContext(
    new \PayPal\Auth\OAuthTokenCredential(
        $clientId,
        $clientSecret
    )
);

$apiContext->setConfig(
    array(
        'mode' => 'sandbox',
        'log.LogEnabled' => true,
        'log.FileName' => 'PayPal.log',
        'log.LogLevel' => 'DEBUG', // PLEASE USE `INFO` LEVEL FOR LOGGING IN LIVE ENVIRONMENTS
        'cache.enabled' => true,
        // 'http.CURLOPT_CONNECTTIMEOUT' => 30
        // 'http.headers.PayPal-Partner-Attribution-Id' => '123123123'
        //'log.AdapterFactory' => '\PayPal\Log\DefaultLogFactory' // Factory class implementing \PayPal\Log\PayPalLogFactory
    )
);
try {
    $tokenInfo = new OpenIdTokeninfo();
    $tokenInfo = $tokenInfo->createFromRefreshToken(array('refresh_token' => $refreshToken), $apiContext);

    $params = array('access_token' => $tokenInfo->getAccessToken());
    $userInfo = OpenIdUserinfo::getUserinfo($params, $apiContext);
} catch (Exception $ex) {
    // NOTE: PLEASE DO NOT USE RESULTPRINTER CLASS IN YOUR ORIGINAL CODE. FOR SAMPLE ONLY
    var_dump("User Information", "User Info", null, $params, $ex);
    exit(1);
}

// NOTE: PLEASE DO NOT USE RESULTPRINTER CLASS IN YOUR ORIGINAL CODE. FOR SAMPLE ONLY
var_dump("User Information", "User Info", $userInfo->getUserId(), $params, $userInfo);
```

The result of the code execution:
> string(16) "User Information"
string(9) "User Info"
NULL
NULL
object(PayPal\Exception\PayPalConnectionException)#23 (9) {
  ["url":"PayPal\Exception\PayPalConnectionException":private]=>
  string(69) "https://api.sandbox.paypal.com/v1/identity/openidconnect/tokenservice"
  ["data":"PayPal\Exception\PayPalConnectionException":private]=>
  string(180) "{"error_description":"Unable to refresh access token","error":"invalid_request","correlation_id":"c4532fe46a761","information_link":"https://developer.paypal.com/docs/api/#errors"}"
  ["message":protected]=>
  string(112) "Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/identity/openidconnect/tokenservice."
  ["string":"Exception":private]=>
  string(0) ""
  ["code":protected]=>
  int(400)
  ["file":protected]=>
  string(91) "/var/www/melony/app/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php"
  ["line":protected]=>
  int(154)
  ["trace":"Exception":private]=>
  array(4) {
    [0]=>
    array(6) {
      ["file"]=>
      string(90) "/var/www/melony/app/vendor/paypal/rest-api-sdk-php/lib/PayPal/Transport/PayPalRestCall.php"
      ["line"]=>
      int(73)
      ["function"]=>
      string(7) "execute"
      ["class"]=>
      string(32) "PayPal\Core\PayPalHttpConnection"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(1) {
        [0]=>
        string(136) "refresh_token=C21AAHGeO4Ah7vrYzFNmvCxn9wplulKX-TIe17wfWDRIXMPH4MBIRkMN5OCuFUk-QcKBsTD3MWRX3j3tQ4xVcMHLh5pmIl42A&grant_type=refresh_token"
      }
    }
    [1]=>
    array(6) {
      ["file"]=>
      string(92) "/var/www/melony/app/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PayPalResourceModel.php"
      ["line"]=>
      int(102)
      ["function"]=>
      string(7) "execute"
      ["class"]=>
      string(31) "PayPal\Transport\PayPalRestCall"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(5) {
        [0]=>
        array(1) {
          [0]=>
          string(26) "PayPal\Handler\RestHandler"
        }
        [1]=>
        string(39) "/v1/identity/openidconnect/tokenservice"
        [2]=>
        string(4) "POST"
        [3]=>
        string(136) "refresh_token=C21AAHGeO4Ah7vrYzFNmvCxn9wplulKX-TIe17wfWDRIXMPH4MBIRkMN5OCuFUk-QcKBsTD3MWRX3j3tQ4xVcMHLh5pmIl42A&grant_type=refresh_token"
        [4]=>
        array(2) {
          ["Content-Type"]=>
          string(33) "application/x-www-form-urlencoded"
          ["Authorization"]=>
          string(222) "Basic QVpHS1BkRENrZURHTmdramUyYl9feUlXWkJVV2lEZkVpZmlHSndvaUQ0a3NtQ0RENEZpZU5fb1cyYTgyeWpjS0N5ZXViQWZPMnVRWnNVd1A6RUd3bllQTGZYQjhOU1hDSWVKaG8yM2tQdzloWHhXaVAyMkxhUDhnbUZqUERMNVhYM1RHRnBFVW4xbTRhc2NsZTc3MjdwWDVmV0VIQXk1Vjk="
        }
      }
    }
    [2]=>
    array(6) {
      ["file"]=>
      string(85) "/var/www/melony/app/vendor/paypal/rest-api-sdk-php/lib/PayPal/Api/OpenIdTokeninfo.php"
      ["line"]=>
      int(248)
      ["function"]=>
      string(11) "executeCall"
      ["class"]=>
      string(33) "PayPal\Common\PayPalResourceModel"
      ["type"]=>
      string(2) "::"
      ["args"]=>
      array(5) {
        [0]=>
        string(39) "/v1/identity/openidconnect/tokenservice"
        [1]=>
        string(4) "POST"
        [2]=>
        string(136) "refresh_token=C21AAHGeO4Ah7vrYzFNmvCxn9wplulKX-TIe17wfWDRIXMPH4MBIRkMN5OCuFUk-QcKBsTD3MWRX3j3tQ4xVcMHLh5pmIl42A&grant_type=refresh_token"
        [3]=>
        array(2) {
          ["Content-Type"]=>
          string(33) "application/x-www-form-urlencoded"
          ["Authorization"]=>
          string(222) "Basic QVpHS1BkRENrZURHTmdramUyYl9feUlXWkJVV2lEZkVpZmlHSndvaUQ0a3NtQ0RENEZpZU5fb1cyYTgyeWpjS0N5ZXViQWZPMnVRWnNVd1A6RUd3bllQTGZYQjhOU1hDSWVKaG8yM2tQdzloWHhXaVAyMkxhUDhnbUZqUERMNVhYM1RHRnBFVW4xbTRhc2NsZTc3MjdwWDVmV0VIQXk1Vjk="
        }
        [4]=>
        object(PayPal\Rest\ApiContext)#11 (2) {
          ["requestId":"PayPal\Rest\ApiContext":private]=>
          NULL
          ["credential":"PayPal\Rest\ApiContext":private]=>
          object(PayPal\Auth\OAuthTokenCredential)#12 (7) {
            ["clientId":"PayPal\Auth\OAuthTokenCredential":private]=>
            string(80) "AZGKPdDCkeDGNgkje2b__yIWZBUWiDfEifiGJwoiD4ksmCDD4FieN_oW2a82yjcKCyeubAfO2uQZsUwP"
            ["clientSecret":"PayPal\Auth\OAuthTokenCredential":private]=>
            string(80) "EGwnYPLfXB8NSXCIeJho23kPw9hXxWiP22LaP8gmFjPDL5XX3TGFpEUn1m4ascle7727pX5fWEHAy5V9"
            ["accessToken":"PayPal\Auth\OAuthTokenCredential":private]=>
            NULL
            ["tokenExpiresIn":"PayPal\Auth\OAuthTokenCredential":private]=>
            NULL
            ["tokenCreateTime":"PayPal\Auth\OAuthTokenCredential":private]=>
            NULL
            ["cipher":"PayPal\Auth\OAuthTokenCredential":private]=>
            object(PayPal\Security\Cipher)#13 (1) {
              ["secretKey":"PayPal\Security\Cipher":private]=>
              string(80) "EGwnYPLfXB8NSXCIeJho23kPw9hXxWiP22LaP8gmFjPDL5XX3TGFpEUn1m4ascle7727pX5fWEHAy5V9"
            }
            ["_propMap":"PayPal\Common\PayPalModel":private]=>
            array(0) {
            }
          }
        }
      }
    }
    [3]=>
    array(6) {
      ["file"]=>
      string(35) "/var/www/melony/app/test/paypal.php"
      ["line"]=>
      int(146)
      ["function"]=>
      string(22) "createFromRefreshToken"
      ["class"]=>
      string(26) "PayPal\Api\OpenIdTokeninfo"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(2) {
        [0]=>
        array(1) {
          ["refresh_token"]=>
          string(97) "C21AAHGeO4Ah7vrYzFNmvCxn9wplulKX-TIe17wfWDRIXMPH4MBIRkMN5OCuFUk-QcKBsTD3MWRX3j3tQ4xVcMHLh5pmIl42A"
        }
        [1]=>
        object(PayPal\Rest\ApiContext)#11 (2) {
          ["requestId":"PayPal\Rest\ApiContext":private]=>
          NULL
          ["credential":"PayPal\Rest\ApiContext":private]=>
          object(PayPal\Auth\OAuthTokenCredential)#12 (7) {
            ["clientId":"PayPal\Auth\OAuthTokenCredential":private]=>
            string(80) "AZGKPdDCkeDGNgkje2b__yIWZBUWiDfEifiGJwoiD4ksmCDD4FieN_oW2a82yjcKCyeubAfO2uQZsUwP"
            ["clientSecret":"PayPal\Auth\OAuthTokenCredential":private]=>
            string(80) "EGwnYPLfXB8NSXCIeJho23kPw9hXxWiP22LaP8gmFjPDL5XX3TGFpEUn1m4ascle7727pX5fWEHAy5V9"
            ["accessToken":"PayPal\Auth\OAuthTokenCredential":private]=>
            NULL
            ["tokenExpiresIn":"PayPal\Auth\OAuthTokenCredential":private]=>
            NULL
            ["tokenCreateTime":"PayPal\Auth\OAuthTokenCredential":private]=>
            NULL
            ["cipher":"PayPal\Auth\OAuthTokenCredential":private]=>
            object(PayPal\Security\Cipher)#13 (1) {
              ["secretKey":"PayPal\Security\Cipher":private]=>
              string(80) "EGwnYPLfXB8NSXCIeJho23kPw9hXxWiP22LaP8gmFjPDL5XX3TGFpEUn1m4ascle7727pX5fWEHAy5V9"
            }
            ["_propMap":"PayPal\Common\PayPalModel":private]=>
            array(0) {
            }
          }
        }
      }
    }
  }
  ["previous":"Exception":private]=>
  NULL
}

**Comment by pp-randy** [comment]
Can you provide your initial parameters you provided for the Log in with PayPal request?  

If you can also include the request for the authorization_code that would be helpful.

**Comment by bob1701** [comment]
I used test account:

> test@testmoney.pro

 It was created in sandbox. 
API returned  authorization_code:

> C21AAGCUpqoi2MaNAP9zeG4Rf9Qpn3nH-3AlToUqi24uo6jNxV8_arcieq3R1jdnjHzz6ewXVKDXpTd2Xplt_PNOlArICByEQ

**Comment by pp-randy** [comment]
What scopes did you use?  Can you provide a PayPal-Debug-Id from the API response of the authorization_code?

**Comment by bob1701** [comment]
I used these scopes : openid profile email address phone

I tried to use only "openid", but the result was the same.

My Debug info:

```
[16-05-2017 09:43:22] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.sandbox.paypal.com/v1/identity/openidconnect/tokenservice
[16-05-2017 09:43:23] PayPal\Core\PayPalHttpConnection : DEBUG: Request Headers         : POST /v1/identity/openidconnect/tokenservice HTTP/1.1, Host: api.sandbox.paypal.com, Accept: */*, Content-Type: application/x-www-form-urlencoded, Authorization: Basic QVpHS1BkRENrZURHTmdramUyYl9feUlXWkJVV2lEZkVpZmlHSndvaUQ0a3NtQ0RENEZpZU5fb1cyYTgyeWpjS0N5ZXViQWZPMnVRWnNVd1A6RUd3bllQTGZYQjhOU1hDSWVKaG8yM2tQdzloWHhXaVAyMkxhUDhnbUZqUERMNVhYM1RHRnBFVW4xbTRhc2NsZTc3MjdwWDVmV0VIQXk1Vjk=, User-Agent: PayPalSDK/PayPal-PHP-SDK 1.11.0 (platform-ver=5.6.30-0+deb8u1; bit=64; os=Linux_2.6.32-042stab120.20; machine=x86_64; crypto-lib-ver=1.0.1t; curl=7.38.0), Content-Length: 136, ,
[16-05-2017 09:43:23] PayPal\Core\PayPalHttpConnection : DEBUG: Request Data            : refresh_token=C21AAFMJG_gkn-T6j5-xZs9vVfT43SHpc0YdVcDnZeBZ19Morh_Idhe64yewaH2jsW2hcGaGVNOFajGOB5Gz05E0o3M_ha-QA&grant_type=refresh_token
--------------------------------------------------------------------------------------------------------------------------------

[16-05-2017 09:43:23] PayPal\Core\PayPalHttpConnection : INFO: Response Status  : 400
[16-05-2017 09:43:23] PayPal\Core\PayPalHttpConnection : DEBUG: Response Headers        : HTTP/1.1 400 Bad Request, Date: Tue, 16 May 2017 21:43:23 GMT, Server: Apache, Cache-Control: no-store, Pragma: no-cache, Paypal-Debug-Id: 3844fae473603, Set-Cookie: Apache=10.72.108.11.1494971003620862; path=/; expires=Thu, 09-May-47 21:43:23 GMT, Vary: Accept-Encoding,Authorization, Connection: close, HTTP_X_PP_AZ_LOCATOR: sandbox.slc, Paypal-Debug-Id: 7147d4d393b59, Set-Cookie: X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Didentityspartaweb_api%26TIME%3D2071075673%26HTTP_X_PP_AZ_LOCATOR%3Dsandbox.slc; Expires=Tue, 16 May 2017 22:13:23 GMT; domain=.paypal.com; path=/; Secure; HttpOnly, Set-Cookie: X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT, Content-Length: 180, Content-Type: application/json, ,
[16-05-2017 09:43:23] PayPal\Core\PayPalHttpConnection : ERROR: Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/identity/openidconnect/tokenservice. {"error_description":"Unable to refresh access token","error":"invalid_request","correlation_id":"3844fae473603","information_link":"https://developer.paypal.com/docs/api/#errors"}
[16-05-2017 09:43:23] PayPal\Core\PayPalHttpConnection : DEBUG:

================================================================================================================================

```

**Comment by pp-randy** [comment]
@bob1701 sorry for any confusion.  I want the debug output for the call before the refresh that is erroring when you request the authorization_code, this is the call that returns you the refresh_token.

**Comment by bob1701** [comment]
Thanks for help. I understood that mistake was in confusing authorization_code and refresh_token.

**Comment by pp-randy** [comment]
I'm glad you were able to resolve.
