### ISSUE TITLE
Mass Payments PHP Not Processed - Denied

### ISSUE THREAD

**Issue by venomshot** [paypal/PayPal-PHP-SDK#853]
* SDK/Library version: 1.11.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: FRB959AH99C6U
* Language, language version, and OS: PHP, Windows 10

Hello,

I am trying to setup Mass Payouts for my site. What I am trying to do is split payments, so when a shopper buys an item, a percentage of the funds go to me, and the rest/majority go to the PayPal user who is selling the item. While it does show that the payouts were sent, both return as denied. 

What I am noticing is that the Sandbox buyer has no record of the transaction, however my main it shows that my main Sandbox Account associated with the app is making the "Payment To / Mass Payment" in the Sandbox Activity, and in the payment log, both amounts, recipients and notes are correct.

In the IPN History, it appears to be making two IPN Records per time I attempt to process the payment. 

Regular, non-Mass Payments work as expected.

Please let me know what I need to provide, so that I dont provide too much info or account secrets - thank you!

**Comment by pp-randy** [comment]
Do you have enough funds in your account balance to cover the transaction fees?  
The debug_id was not correct, did you get it from an API response header?  If you don't have this, give me a transaction id for now and I will look into it and ask additional questions if needed.

**Comment by venomshot** [comment]
Hello, thank you for the response. Yes there are enough funds; the Unique transaction ID is 8958851, and payout_batch_id is ECQRXRL8KZRLJ.

**Comment by pp-randy** [comment]
Try now, I have verified your sandbox account by adding a bank account.  I think that is probably the cause.

**Comment by venomshot** [comment]
Okay, I do see that it went through now (UID 8958866 + Batch SKFMBUAHW5DCU) ; A few last questions regarding this to make sure I am doing this properly.

1. Can I have myself be one of the two recipients of the payout? Or would that be considered as 'Paying myself' money that technically I already have and am distributing at the moment? For example, a total of $200, can I send $190 to the target, and the other $10 to me?

2. Will a payout of this scope of two persons always result in a flat fee of $0.50?

3. Will (or can) both recipients receive all order details by default, including price and Item ID, etc, or do I need to include them when configuring the PayoutItem? If I need to manually include them, what is the code with which I can pull them from what the buyer has confirmed?

**Comment by venomshot** [comment]
Also, via PHP how can I retrieve the payout_batch_id and verify that the payment is Pending? I see it in the var_dump from `$output = $payouts->create(null, $api);` but cannot traverse the JSON to pull the variable.

**Comment by venomshot** [comment]
Payments are failing now, latest batch ID is IDBUP9MZZSPY84S. I feel like it is because there is not enough money in the payments@clique.life account, but why is that draining? Shouldnt that just be redistributing the payments from the buyer? I tried to add money to that sandbox account but being prompted for SSN.

**Comment by venomshot** [comment]
It appears that upon the sandbox buyer committing to pay, my current redirect has my main sandbox account paying out the mass payments to the seller, but actually receiving money from the buyer, which is draining the main account.

What do I need to change so when the buyer commits to pay, the money splits to myself and the seller, rather than comes straight from my sandbox account? 

Latest batch ID is IDYKS8D6ABD5MS8

**Comment by xiaoleih41** [comment]
What you are looking for is a marketplace function or parallel/chained payment feature which is not available in REST API. Payout API is the closest API to mimic this type of function.  You will have to ensure that you have received the buyer's funds before you initiate the payment as the payment cannot be split between two receivers in REST. 
1. You will keep $10 and send $190 to the seller. You don't have to send the $10.00 to another account but you can. 
2. Yes, it will be $.50 per payout transaction. To receive the buyer's payment, you will pay a PayPal transaction rate too. 
3.  As your account will be the only receive the entire amount from the buyer, you will get all the detail. You can [retrieve the transaction detail](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/sale/GetSale.php) and send it to the payout recipient separately. 
4.  As long as it's a US verified PayPal account without any account issue, it should be able to receive payouts.

**Comment by venomshot** [comment]
@xiaoleih41 Thank you for the detailed response. I think that mass payouts in this case would be a bit messy in the long run and hard to manage. It seems like the way to go is parallel payments.

1. Lastly before closing the issue, it seems the parallel payments is using JSON, whereas I am using PHP --- is there some sort of "getting started" guide to JSON / Paypal? 

2. Do I need to delete all of my previous Paypal PHP framework + integration, or can I keep it for future single payouts?

That should get my on the way --- thanks again!

- Chris

**Comment by xiaoleih41** [comment]
REST API doesn't support parallel payment API. You probably looked into adaptive payment API. I would suggest to use [Express Checkout parallel payment API](https://developer.paypal.com/docs/classic/express-checkout/ht_ec-parallelPayments/?mark=parallel) instead. It's mobile optimized.
