### ISSUE TITLE
400{"name":"VALIDATION_ERROR","details":[{"field":"transactions[0]","issue":"Item amount must add up to specified amount subtotal

### ISSUE THREAD

**Issue by JohnCarlo29** [paypal/PayPal-PHP-SDK#855]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description

i got this error.. i try to use paypal sdk to checkout my items from my cart

here is my checkout.php

`<?php
	require __DIR__  . '/vendor/autoload.php';

	use PayPal\Api\Payer;
	use PayPal\Api\Item;
	use PayPal\Api\ItemList;
	use PayPal\Api\Details;
	use PayPal\Api\Amount;
	use PayPal\Api\Transaction;
	use PayPal\Api\RedirectUrls;
	use PayPal\Api\Payment;

	define('SITE_URL', 'https://localhost/prince2');
	$paypal = new \PayPal\Rest\ApiContext(
        new \PayPal\Auth\OAuthTokenCredential(
            'Ae4_0KrtBmc1HEGEAeN6YDkChhV165r9GeFJwMM3ZIwUlxnKJXe-BN9Y-TNHRh4CTCsdx2MdsPOpi8RM',     // ClientID
            'EE2cQufq0iX9-XBeDU6LP0zvMAJvNu9_xRIGerKETolGBzVffWli3WuiTFNKeEp9lKDtPPIb1yXvasxd'      // ClientSecret
        )
	);

	if(!isset($_POST['product'],$_POST['price'])){
		die();
	}

	$products = $_POST['product'];
	$prices = $_POST['price'];
	$quantities = $_POST['quantity'];
	$shipping = 100;

	$initialTotal = 0.0;
	$total = 0.0 + $shipping;

	for($i=0;$i<=count($prices)-1;$i++){
		$total += $prices[$i];
		$initialTotal += $prices[$i];
	}

	$payer = new Payer();
	$payer->setPaymentMethod('paypal');

	$item = new Item();

	$list=[];
	for($i=0;$i<=count($products)-1;$i++){
		$item->setName($products[$i])
		->setCurrency('PHP')
		->setQuantity($quantities[$i])
		->setPrice($prices[$i]);
		
		array_push($list,$item);
	}

	$itemList = new ItemList();
	$itemList->setItems($list);

	$details = new Details();
	$details->setShipping($shipping)
			->setSubtotal($initialTotal);

	$amount = new Amount();
	$amount->setCurrency('PHP')
				->setTotal($total)
				->setDetails($details);

	$transaction = new Transaction();
	$transaction->setAmount($amount)
				->setItemList($itemList)
				->setDescription('PrinceCLothing Payment')
				->setInvoiceNumber(uniqid());

	$redirectUrls = new RedirectUrls();
	$redirectUrls->setReturnUrl(SITE_URL.'/pay.php?success=true')
				 ->setCancelUrl(SITE_URL.'/pay.php?success=false');

	$payment = new Payment();
	$payment->setIntent('sale')
			->setPayer($payer)
			->setRedirectUrls($redirectUrls)
			->setTransactions([$transaction]);

	try {
	    $payment->create($paypal);
	} catch (PayPal\Exception\PayPalConnectionException $ex) {
	    echo $ex->getCode(); // Prints the Error Code
	    echo $ex->getData(); // Prints the detailed error message 
	    die($ex);
	} catch (Exception $ex) {
	    die($ex);
	}

	echo $approvalUrl = $payment->getApprovalLink();
?>`

----------------------error--------------------------

400{"name":"VALIDATION_ERROR","details":[{"field":"transactions[0]","issue":"Item amount must add up to specified amount subtotal (or total if amount details not specified)"}]

please help me to fix this im only just a student who want to explore. BTW $products, $prices and $quantites are all in array form

**Comment by xiaoleih41** [comment]
The calculation of your code may have some issues. Please refer to SDK sample 
[CreatePaymentUsingPayPal.php](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/CreatePaymentUsingPayPal.php). and understand that the `Subtotal` property of `$details` should equal to the sum of each **item price**  times its **quantity**. You may have to echo the numbers of each item's `sub_total` and add them together to see if the numbers are match or not.

**Comment by JohnCarlo29** [comment]
thank you so much @xiaoleih41  your my saviour. I did'nt noticed the value of initialTotal. Case Solve.. Once again Thank You
