### ISSUE TITLE
How to update payer information using PayPal rest api?

### ISSUE THREAD

**Issue by kcppdevelopers** [paypal/PayPal-PHP-SDK#856]
### General information

* SDK/Library version: Latest version
* Environment: SandBox
* `PayPal-Debug-ID` values: 2165de79b633
* Language, language version, and OS: Window Wamp

### Issue description

I am working PayPal Plus development, but I am little bit confused how to  update payer information using PayPal rest api?

{"name":"MALFORMED_REQUEST","details":[{"field":"payer_info","issue":"Unrecognized field/Invalid Value"}],"message":"MALFORMED_REQUEST","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"2165de79b633"}

**Comment by kcppdevelopers** [comment]
@jaypatel512 Can you please help me on this?

**Comment by pp-randy** [comment]
It looks like you are trying to patch payer_info for a payment.  Is this the case?  If so you, can only change a few things. 


> [Update Payment](https://developer.paypal.com/docs/api/payments/#payment_update) - You can update the amount, shipping address, invoice ID, and custom data.

**Comment by pp-randy** [comment]
Can you provide your API request JSON?

**Comment by xiaoleih41** [comment]
Close this issue due to inactivity. Please resubmit the ticket if you have any additional questionis
