### ISSUE TITLE
Need API to pay money to my customer?

### ISSUE THREAD

**Issue by Govind13100** [paypal/PayPal-PHP-SDK#857]
I want to pay to my customers who want to sell their products, 

Can you please guide me about it, what kind of api paypal provide for this and how to implement it,

I am tired of googling and the result is negative

Any help would be great full !!!

**Comment by xiaoleih41** [comment]
Are you taking full payments from a buyer then pay it out to a seller?  This is considered as high risk in PayPal unless you are fully confident in your sellers' services and products.  Your PayPal account will be legally and financially responsible for every single payment you received to your PayPal account as you will be the sole receiver of the payment from the buyer and PayPal's perspective.  It may be considered as a [PayPal AUP policy](https://www.paypal.com/us/webapps/mpp/ua/acceptableuse-full) violation based on the description of item 3(e).

Technically, you can consider to use PayPal's payout API to pay your merchants.  Please note that there's no refund for payout payments but there will be chargeback risk for the payment sent by the buyer as it can be funded by a credit card. 

The recommended way to run a marketplace in PayPal is to facilitate the payment directly from the buyer to the seller. You can send an invoice or set up a billing agreement with the seller to charge your platform fee. 

You can also looking into our Braintree products. It has a [marketplace module](https://www.braintreepayments.com/products/braintree-marketplace) that will fit your credit card processing needs. 

I know it's not perfect. PayPal is working on a new marketplace product this year and hopefully it will launch within this year.

**Comment by Govind13100** [comment]
Hie there,Thank you for your reply.
 
No, I am not taking any payment from a buyer/customer, allow me to explain my whole scenario.

There is a steam.com website which allow to play game to user around the world(may be you know that).One of the most popular game is CSGO (Counter strike). I am developing a website with steam login functionality, user can login through steam and i will show the inventory(items/skins) of the logged in user in order to sell. The particular user can then select any inventory(items/skins) to sell and we will offer him a suitable price, if user agree with our price , then we will pay him the money and buy his/her inventory(items/skins).After this we will sell his/her inventory(items/skins) to other user. So i need both to pay the user at once and also to taking money at once. 
My English is not good, pardon !!

Hope you understood the scenario.

Any help will help me a lot. Thank you.

**Comment by xiaoleih41** [comment]
Thank you for your explanation. You can using PHP to do single payout. Please check the SDK sample file [here](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payouts/CreateSinglePayout.php). Hopefully it will solve your issue.

**Comment by xiaoleih41** [comment]
Close this thread due to inactivity. Please resubmit if you have any further questions.
