### ISSUE TITLE
UNKNOWN_ERROR sandbox 

### ISSUE THREAD

**Issue by reydajp** [paypal/PayPal-PHP-SDK#858]
### General information
- Mode (Sandbox/Live): Sandbox
- PayPal-Debug-ID: 9f452a4842c8d
- Version of PHP: 5.6.22
- SDK Version: latest

### Issue description
Tried the default `Payments using credit card information`  [example](https://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/CreatePayment.html) within my application and it return the next error:
`object(stdClass) {
	name => 'UNKNOWN_ERROR'
	message => 'An unknown error occurred.'
	information_link => 'https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR'
	debug_id => '9f452a4842c8d'
}`

**Comment by xiaoleih41** [comment]
This could be caused by the credit card number in the sample was over used. Please try to use the credit card come with your sandbox account or generate a new one. It should solve the issue.

**Comment by reydajp** [comment]
@xiaoleih41 
Thank for you answer. I'm not using the credit card number in the sample but a generated one.

It 's perfectly working when I'm using the payment by iframe ([Website Payments Pro Hosted Solutions](https://developer.paypal.com/docs/classic/products/website-payments-pro-hosted-solution/)) 
but getting this `UNKNOWN_ERROR` when I'm using the REST API.

**Comment by xiaoleih41** [comment]
@reydajp 
I cannot reproduce your error. I have tried the sample with a newly generated card. The transaction was successful. Can you check your credentials or may try a new card to see if it will solve the issue?

**Comment by reydajp** [comment]
@xiaoleih41 
It seems the REST API is not available for my country. That 's maybe why I'm getting this error message. 
Anyway I suggest a more explicit message in this case.
Thank you for you support

**Comment by reydajp** [comment]
not available in Japan
