### ISSUE TITLE
How to implement it on live server?

### ISSUE THREAD

**Issue by Govind13100** [paypal/PayPal-PHP-SDK#860]
hie there,

Greeting of the day!!!

I have used the composer method to download the SDK, I followed your composer command and all things working fine, i am using Single Payout method to pay money to my customer, I have test this with my sandbox account ,Money deducted from my business account and transferred to my personal account.

using http://localhost:5000/   link as you have mentioned in your documentation.

But when i try to implement the same on my live server(i.e my live site). The thing is not working , can you please tell me , do m I missing anything in order to work on live server, or anything that is mandatory to implement this on live sever.

Any help would be great-full !!!!
Thanks in advance.

**Comment by xiaoleih41** [comment]
Do you have a debug_Id for us to take a look at? Have you enabled payout live credentials on your live APP? What kind of error have you received? This issue may provide the information that you were looking for. https://github.com/paypal/PayPal-PHP-SDK/issues/784

**Comment by Govind13100** [comment]
Hie, thanks for replying.

It worked, and sorry to bother you!
The issue was different then what you understood from my issue How to implement it on live server? #860. I don't want to be it on live paypal , i want it to run with sandbox details on my live server, It was running great on my localhost , but was creating problem on live server.

Now everything working fine, i have implemented this on my live server.

Thank you for your response.

**Comment by xiaoleih41** [comment]
I am glad the issue has been solved. I am closing this thread.
