### ISSUE TITLE
How to apply installment option in the transaction ?

### ISSUE THREAD

**Issue by DeeSouza** [paypal/PayPal-PHP-SDK#861]
### General information

* SDK/Library version: last version
* Environment: Sandbox | Production
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: PHP 

### Issue description

```
$installment  = new InstallmentOption;
$installment->setTerm = 1;

$payment      = new Payment();
$payment->setIntent("sale")
->setPayer($payer)
->setTransactions(array($transaction));
```
How to implement installment option in method `Payment `?

Thanks!

**Comment by xiaoleih41** [comment]
Can you ask what type of business function you are trying to accomplish? Will [create billing plan and billing agreement](https://github.com/paypal/PayPal-PHP-SDK/tree/master/sample/billing) help with your case?

**Comment by DeeSouza** [comment]
It is a simple purchase with credit card only, but has installment option. No plan.
![image](https://cloud.githubusercontent.com/assets/12430887/26317979/ca705120-3eef-11e7-8d55-d2bdc91b02a7.png)

**Comment by xiaoleih41** [comment]
As it's a region specific feature. I am reaching out to Brazilian integration group for possible information on this feature.

**Comment by xiaoleih41** [comment]
Installments is actually setup at your PayPal account. You do not send the Installments option through the API call…
You should access your account > Profile > Profile and Settings > My selling tools > Installments Plan, PayPal will automatically present the installment plan based on the buyer’s options.

**Comment by xiaoleih41** [comment]
Close this ticket due to inactivity. Please resubmit if you have any further questions.
