### ISSUE TITLE
Chained Payments Secondary Receiver not Receiving

### ISSUE THREAD

**Issue by venomshot** [paypal/PayPal-PHP-SDK#862]
I am using the cUrl initiated Adaptive Payments structure in which I create a class, construct headers, and send requests via cUrl to process data.

Right now I have my payment array including:
```
"actionType" => "PAY_PRIMARY",		
"currencyCode" => "USD",
"feesPayer" => "PRIMARYRECEIVER",		
"receiverList" => array(
"receiver" => array(
array(	
"primary"=>"true",																"amount"=>$total_transaction_price,	
"email"=>$business_recipient_email,	
"invoiceId"=>$order_vsid,		
"paymentType"=>"GOODS"
),
array(			
"amount"=>$my_portion,		
"email"=>$secondary receiver email
"invoiceId"=>$order_vsid,				
"paymentType"=>"SERVICE"	
																),
														)
												),
```

Which returns in success and with a paykey, however I am not clear on how to continue on in this format to process the payment to the secondary receiver. Can someone please provide an example? Ive seen the documents at https://developer.paypal.com/docs/classic/adaptive-payments/integration-guide/APIntro/ and all throughout, but nothing there specifically explains how to pass the funds from the primary receiver to the secondary receiver, only that the option exists.

**Comment by venomshot** [comment]
It seems I need to make an ExecutePayment request, but I am unsure how to format it. I have the payKey and recipient. 

My payment execution code looks like this:
```
function _paypalSend($data,$call){
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL, $this->apiUrl.$call);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);
		curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, FALSE);
		curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
		curl_setopt($ch, CURLOPT_HTTPHEADER, $this->headers);
		//
		return json_decode(curl_exec($ch), TRUE);
		curl_close($ch);
}
```

**Comment by xiaoleih41** [comment]
Locking this conversation. Please use [adpativepayments-sdk-PHP](https://github.com/paypal/adaptivepayments-sdk-php) for this issue. Please refer to this [guide](https://developer.paypal.com/docs/classic/adaptive-payments/ht_ap-basicChainedPayment-curl-etc/) on setting up a basic chained payment.

**Comment by xiaoleih41** [comment]
Close this thread as it's in the wrong repository.
