### ISSUE TITLE
Error in  PayPal-PHP-SDK sample - Create Billing Agreement With Credit Card

### ISSUE THREAD

**Issue by manian-kumaran** [paypal/PayPal-PHP-SDK#863]
* SDK/Library version: PayPal-PHP-SDK-1.11.0
* Environment: Sandbox (running php -f paypal/rest-api-sdk-php/sample/index.php)
* `PayPal-Debug-ID` values: 
{
    "name": "INTERNAL_SERVICE_ERROR",
    "message": "An internal service error occurred.",
    "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR",
    "debug_id": "c68942fb3fd24"
}
* Language, language version, and OS: php 7 on Ubuntu 16.04

### Issue description

1. Download https://github.com/paypal/PayPal-PHP-SDK/releases/download/1.11.0/PayPal-PHP-SDK-1.11.0.zip
2. Unzip it
3. Run the sample per instruction:
php -f paypal/rest-api-sdk-php/sample/index.php
4. Choose 'Create Billing Agreement With Credit Card' and click 'Try it'
5. It executes: 
(1) Created Plan (Ok)
(2) Updated the Plan to Active State (Ok)
(3) Created Billing Agreement (Failed)
Response Object

 Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/billing-agreements/.

{
    "name": "INTERNAL_SERVICE_ERROR",
    "message": "An internal service error occurred.",
    "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR",
    "debug_id": "970f21a69b303"
}

In addition to this issue, I'd like to know if I can 'Create Billing Agreement with Credit Card' for third party merchant using Third Party Permission. There is very limited documentation on the third party permission to execute REST API. 

Inspired by sample of creating third party invoice: https://developer.paypal.com/docs/classic/invoicing/ht_invoicing-3p/, I tried the following but it fails with Unauthorized error message:

curl -v POST https://api.sandbox.paypal.com/v1/payments/billing-agreements \
-H "Content-Type:application/json"  \
-H "X-PAYPAL-SECURITY-USERID: <App username>"  \
-H "X-PAYPAL-SECURITY-PASSWORD: <App password>" \
-H "X-PAYPAL-SECURITY-SIGNATURE: <App signature>" \
-H "X-PAYPAL-REQUEST-DATA-FORMAT: JSON" \
-H "X-PAYPAL-RESPONSE-DATA-FORMAT: JSON" \
-H "X-PAYPAL-APPLICATION-ID: <App ID>" \
-H "X-PAYPAL-SECURITY-SUBJECT: <merchant email address>"  \
-H "X-PAYPAL-AUTHENTICATION: <oauth signature computed using merchant permission accessToken and tokenSecret and request URI above>" \
...
payload

**Comment by xiaoleih41** [comment]
Please try to use a new sandbox credit card for the testing. This error might have been caused by overused sandbox credit card number. REST API currently doesn't support 3rd party permission for billing agreement creation. I can put in a feature request to the product team.

**Comment by manian-kumaran** [comment]
Thanks. That's exactly correct, credit card number is overused.
