### ISSUE TITLE
Calling API for Third Party Merchant using Permission - Lack of support in REST-API

### ISSUE THREAD

**Issue by manian-kumaran** [paypal/PayPal-PHP-SDK#864]
There seems to be lack of support for calling rest-API for third party merchant using Permission. 
I can only find documentation about third party rest-API for:

- How to Send an Invoice on Behalf of a Third-Party Merchant
https://developer.paypal.com/docs/classic/invoicing/ht_invoicing-3p/

- How to get Third-Party Permissions
https://developer.paypal.com/docs/classic/permissions-service/ht_permissions-invoice/

- Permission Service Integration Guide (that only applies to NVP/SOAP and not REST-API)
https://developer.paypal.com/docs/classic/permissions-service/integration-guide/PermissionsAbout/

Where can I find sample/documentation on how to call REST API for third party merchant?
Is there support or not at all for calling REST API for third party merchant?

**Comment by xiaoleih41** [comment]
Third party permission is not supported in REST at this time.  I have submitted a feature request. Please use NVP/SOAP instead for now.  Please track the status at https://github.com/paypal/PayPal-REST-API-issues/issues/80

**Comment by pp-randy** [comment]
Here is a sample that has details of how to use Log in with PayPal for this with the REST API https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/invoice/CreateThirdPartyInvoice.php

**Comment by manian-kumaran** [comment]
Hi,
Any progress in Calling API for Third Party Merchant using Permission using REST-API?

**Comment by xiaoleih41** [comment]
Log in with PayPal is the way to access 3rd party permission. Other than that, you will need to consider to integration PayPal marketplace solution which is a partner program that you should apply.
