### ISSUE TITLE
INTERNAL_SERVICE_ERROR on RefundSale

### ISSUE THREAD

**Issue by EdanSmith** [paypal/PayPal-PHP-SDK#865]
- SDK Version = 1.11
- Sandbox
- Paypal Debug Id = f41cc529add3c
- PHP 5.5 on Windows

Full error: {"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error occurred.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"f41cc529add3c"}

```
use PayPal\Api\Amount;
use PayPal\Api\Details;
use PayPal\Api\RefundRequest;
use PayPal\Api\Sale;

$amount = new Amount();
$details = new Details();

$details->setSubtotal(30);

$amount->setCurrency('BRL');
$amount->setTotal($details->getSubtotal());

$refundRequest = new RefundRequest();
$refundRequest->setAmount($amount);

$sale = new Sale();
$sale->setId($transactionId);
try {
    $apiContext = getApiContext($clientId, $clientSecret);
    $refundedSale = $sale->refundSale($refundRequest, $apiContext);
    echo 'Refunded!';
} catch (Exception $ex) {
    echo $ex->getData();
    exit(1);
}
```

For some reason i'm getting this error, the clientId and clientSecret are coming from the bootstrap file and it's all ok, also the $transactionId is coming from another class and is Ok too.

I'm trying to refund a payment which the totalValue was 30.00 .

**Comment by xiaoleih41** [comment]
I don't see you retrieve and pass on the transaction ID.  Please check into this [sample file](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/sale/RefundSale.php#L10-L11). Also, you don't need new detail or subtotal to do refund. All you need is the **saleId** and the **Total** amount.

**Comment by EdanSmith** [comment]
The saleId is the transaction ID? like "PAY-38324802329048 ......." ? Because if it is that, i'm sending it already... it's just not explicit in there.

**Comment by xiaoleih41** [comment]
No, That's payment Id. that's not `sale_id`. `sale_id` is under [Sales](https://developer.paypal.com/docs/api/payments/#sale).

**Comment by EdanSmith** [comment]
I fixed it!, the problem was that I was sending the TransactionId instead of the saleId, Thank you.
