### ISSUE TITLE
Card stored in app's owner's instead of merchant that gives consent in ObtainUserConsent.php

### ISSUE THREAD

**Issue by manian-kumaran** [paypal/PayPal-PHP-SDK#866]
SDK/Library version: PayPal-PHP-SDK-1.11.0
Environment: Sandbox (running php -f paypal/rest-api-sdk-php/sample/index.php)

ObtainUserConsent succesfully returns accessToken.
And use the accessToken above to save credit card into vault and use it to:
Payments using saved credit card (using Vault APIs)

but the payment goes to the app owner (sandbox) paypal account instead of the merchant that has given consent during ObtainUserConsent.

Testing it using cUrl:
Storing card to vault using third party merchant accessToken
curl -v POST https://api.sandbox.paypal.com/v1/vault/credit-cards/ \
-H "Content-Type:application/json" \
-H "Authorization: Bearer <merchant's accessToken from ObtainUserConsent>" \
-d '{
  "number": "4532507516709022",
  "type": "visa",
  "expire_month": 11,
  "expire_year": 2022,
  "cvv2": "874",
  "first_name": "Joe",
  "last_name": "Shopper Shopper",
  "billing_address": {
  "line1": "52 N Main ST",
  "city": "Johnstown",
  "country_code": "US",
  "postal_code": "43210",
  "state": "OH",
  "phone": "408-334-8890"
  }
}'

Response:
Success HTTP/1.1 201 Created
{"id":"CARD-15P925155D148....."
....

curl -v https://api.sandbox.paypal.com/v1/payments/payment \
-H "Content-Type:application/json" \
-H "Authorization: Bearer <merchant's accessToken from ObtainUserConsent>" \
-d '{
  "intent": "sale",
  "payer": {
    "payment_method": "credit_card",
    "funding_instruments": [{
      "credit_card_token": {
        "credit_card_id": "CARD-15P925155D148.....",
        "external_customer_id": "joe_shopper408-389778978934-8890"
      }
    }]
  },
  "transactions": [{
    "amount": {
      "total": "60.70",
      "currency": "USD"
    },
    "description": "Payment by vaulted credit card."
  }]
}'

Success, HTTP/1.1 201 Created
{"id":"PAY-6S614497SK016814TLETZVDY", ....

But the payment goes to the App owner paypal account instead to merchant who have already given consent.

Is it because storing credit vault is only for owner of the app and not for third party merchant?

According to this Paypal owned blog, it says that third party merchant is supported to any REST api calls:
https://devblog.paypal.com/authenticating-with-oauth-2-in-the-new-restful-apis/
And in ObtainUserConsent.php it clearly shows that the consent scope 
https://api.paypal.com/v1/vault/credit-card

Why the credit card ends up into app owner paypal account instead of to the merchant's account where its access-token is used to store the card to vault.

Am I missing something?

Please advise.

**Comment by xiaoleih41** [comment]
Vault doesn't work with LIPP to provide third party access functionality. Please look into [Braintree Auth](https://www.braintreepayments.com/products/braintree-auth). It's a beta product but it supports storing and vaulting credit cards for merchants.

**Comment by manian-kumaran** [comment]
Hi Xiaoleih
Thanks.

What is the consent scope 
https://api.paypal.com/v1/vault/credit-card
for in ObtainUserScope.php?

My understanding is that the ObtainUserConsent.php is used to get authorization code from third party merchant and use the authorization code to get refresh-token/access-token to do transactions in the requested scope on behalf of the third party merchant.

Is there documentation about how to use the refresh-token/access-token as a result of ObtainUserConsent.php? I spend significant amount to read/find documentation/information regarding transaction on behalf of third party merchant using REST api. I look all samples code in PayPal-PHP-SDK-1.11.0 and paypal developer documentation/api reference and the only clue about third party merchant transaction is User Consent section. Unfortunately, there is no follow up on how to use the access-token as a result of ObtainUserScope to make transaction on behalf of third party merchant.

**Comment by xiaoleih41** [comment]
Have you requested `https://api.paypal.com/v1/vault/credit-card` in your list of scopes when the merchant granted consent to you?

**Comment by xiaoleih41** [comment]
I tested it and got the same result.  Vault doesn't support 3rd party API caller to store the card on the merchant's behalf. I would suggest you to look into [Braintree Auth](https://www.braintreepayments.com/products/braintree-auth) product as I have suggested before. It should allow you to vault PayPal method as well.
