### ISSUE TITLE
Paypal-plus integration using PayPal-REST-API-PHP

### ISSUE THREAD

**Issue by masudewucse** [paypal/PayPal-PHP-SDK#868]
### General information

For normal paypal (PayPal-REST-API-PHP) we know the credit card credentials in our website and this is how the REST is developed.<br>
But in Paypal plus options load in an iframe and redirect to paypal website in order to get payment credentials from buyer. 
Does $payer->setPaymentMethod("paypal");  Works for all 1. Paypal 2. Credit Card 3. Direct debit 4. Invoice.. for paypal plus?

**Comment by xiaoleih41** [comment]
Yes. you are correct. **Payment method** for **PayPal Plus**  is `paypal`.
