### ISSUE TITLE
PayPal\Api\Payment::all not working correctly

### ISSUE THREAD

**Issue by EdanSmith** [paypal/PayPal-PHP-SDK#869]
- SDK Version = 1.11
- Sandbox
- PHP 5.5 on Windows

I have been trying to use ```PayPal\Api\Payment::all``` It says it does the same thing as ```PayPal\Api\Payment::get``` but it returns all the payments based on the parameters... The thing is, it's not the same return, sounds like it's missing information on the "all" or i'm not doing it right.

For example, it doesn't return the Sale State (Which could be Completed, Pending, Refunded.... etc).

That's the code that I have:
```
$payments = PayPal\Api\Payment::all(array('count' => 150, 'start_index' => 0), $apiContext);
foreach ($payments->getPayments() as $payment)
.....
```
That's what i'm trying to retrieve from ```PayPal\Api\Payment::all``` --> ```$payment->transactions[0]->related_resources[0]->sale->state;```

Also, is it better (performance wise) to use the Payment::all instead of a foreach on Payment::get ? The difference is huge when we are talking about 500 ~ 1000 records to read?

**Comment by xiaoleih41** [comment]
Both responses include **related resources** content which includes the `state` of **sale**.  If the transaction is funded by credit card, the responses are almost identical. For 500-1000 records, I would suggest you to use [PayPal reporting](https://developer.paypal.com/docs/classic/products/reporting/) instead.

**Comment by EdanSmith** [comment]
But for some reason i'm not receiving the **Related Resources** content on ```PayPal\Api\Payment::all```... the way that I called it was correct? Am I missing anything?

**Comment by xiaoleih41** [comment]
Please refer to the sample code for [listPayments.php](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/ListPayments.php) and [GetPayments.php](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/GetPayment.php). Hope this will help you retrieve **related resources** info. Again, for the amount of records you are pulling, I would suggest you to look into [PayPal reporting](https://developer.paypal.com/docs/classic/products/reporting/) instead.

**Comment by EdanSmith** [comment]
Thanks.
