### ISSUE TITLE
problem in paypal on server 

### ISSUE THREAD

**Issue by MhmudHsham** [paypal/PayPal-PHP-SDK#871]
Hi,
i have a problem in paypal on server ... it works in localhost but doesn't work on the server
error message :
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'

**Comment by xiaoleih41** [comment]
Please provide your API request minus the API credentials/password. Please make sure you are pointing at the correct endpoint.

**Comment by xiaoleih41** [comment]
Close this thread due to inactivity. Please resubmit if you still have the same issue.
