### ISSUE TITLE
Latest SDK Version

### ISSUE THREAD

**Issue by axelf** [paypal/PayPal-PHP-SDK#874]
Is Version 1.11.0 the latest version? If not, where can i download the latest version? I wanted to use the `getToken()` method from the Payment class, but in my download i cant find the method. Here on github i see this method.

**Comment by xiaoleih41** [comment]
Version 1.11.0 is the latest version. If you are using [direct download](https://github.com/paypal/PayPal-PHP-SDK/wiki/Installation-Direct-Download), please download the SDK from [here](https://github.com/paypal/PayPal-PHP-SDK/releases).

**Comment by axelf** [comment]
I used this link, but in the download package i can't see the getToken() method

**Comment by xiaoleih41** [comment]
I am providing feedback internally. In the meantime, you can replace the file with [the one](https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Api/Payment.php#L553) listed on the site.

**Comment by axelf** [comment]
Ok, thank you. Would be nice to see the changes in the latest sdk version download

**Comment by xiaoleih41** [comment]
I have requested it. It will be included in the next release.  Hopefully it will be soon.

**Comment by jaypatel512** [comment]
Hey @axelf !

We have just released [v1.12.0](https://github.com/paypal/PayPal-PHP-SDK/releases/tag/1.12.0). Please update to latest version to get the method you are looking for. Cheers 🎆

**Comment by axelf** [comment]
Nice...thank you for this information.
