### ISSUE TITLE
Can I use SDK for Donation

### ISSUE THREAD

**Issue by wowthemes** [paypal/PayPal-PHP-SDK#876]
Can I use this SDK for Donation purpose. I try to search in the sample code but can't find any reference to donation. Please guide.

**Comment by xiaoleih41** [comment]
Technically, you can use any PayPal API for donation but if you may want to check with compliance@paypal.com to see if your PayPal account is qualified to be a fundraising account and maybe special rate for donation payments.

**Comment by wowthemes** [comment]
I didn't find any option in documentation to set the payment as donation. So Payer can see it as donation. Can you please guide me how to set payment as donation. Thanks

**Comment by xiaoleih41** [comment]
There's no payment type called donation. Donation is a type of use case in PayPal. You can customize the look of your PayPal checkout button. Please take a look at [this](https://github.com/paypal/paypal-checkout/blob/master/src/components/button/templates/component/config.js).

**Comment by wowthemes** [comment]
Thanks a lot for your response.  Actually I am developing a WordPress Donation Plugin but instead of normal donation form with hidden input field `name="cmd"` and `value="donation"`, plugin need to redirect user to PayPal after collecting address info. Plugin will hook up other payment methods in this way as well.

I am looking a method like `$Payment->setCMD('donation')` and then redirect donor to PayPal. Is it possible. Really appreciate your help.

**Comment by trainerbill** [comment]
@wowthemes Since this is a donation, amount can be changed, then I would suggest just using our JS library so you don't have to do anything on the server side.

https://github.com/paypal/paypal-checkout/blob/master/docs/button.md

Use the basic Integration.

in the onAuthorize callback you can run actions.payment.get() to return the persons paypal account and shipping information.

**Comment by wowthemes** [comment]
I think JS will not help because I have custom donation button like [here](http://wow-themes.com/wordpress/attyia/index.php/donations/join-our-campaign-donation-so-far/) so when user click on donate button then I build PayPal API Request and redirect the user to PayPal to make donation. The current PHP API is works fine but I am not able to set cmd to donation. Any solution please

**Comment by xiaoleih41** [comment]
@wowthemes We don't have **donation** as **transaction/payment type** in PayPal. `cmd` is not a property of `payment` in our SDK. This maybe is your plugin specific requirement. I am sorry that we cannot be of help on this.

**Comment by xiaoleih41** [comment]
Close this thread as we do not support the parameter mentioned in this thread.
