### ISSUE TITLE
Paypal Plus, How to decide which payment system has been used

### ISSUE THREAD

**Issue by masudewucse** [paypal/PayPal-PHP-SDK#877]
I am using Paypal plus payment options (iframe) which redirects me to `Paypal` website for the credentials.
I have done a transaction using `Creditcard` and found the response below . No where in the array it says that the `Credit card` has been used for this transaction. I see almost same response when i used `Paypal`. 
By the way, not matter what i used `Creditcard` or `Paypal` the response always says `paypal`.
How can i decide from the response which payment method has been used? Please help! 

Credit Card payement, Paypal response: 
<pre>
{
    "id": "PAY-01Y41728PS359693FLFAT3VQ",
    "intent": "sale",
    "state": "approved",
    "cart": "4EL590323E815271G",
    "payer": {
        "payment_method": "paypal",
        "status": "UNVERIFIED",
        "payer_info": {
            "email": "StefanBergmann@teleworm.us",
            "first_name": "Stefan",
            "last_name": "Bergmann",
            "payer_id": "8DAFS5B5T6ZRJ",
            "shipping_address": {
                "recipient_name": "Stefan Bergmann",
                "line1": "M\u00fchlenstrasse 59",
                "city": "W\u00fcrzburg",
                "state": "",
                "postal_code": "97014",
                "country_code": "DE"
            },
            "phone": "0931536531",
            "country_code": "DE"
        }
    },
    "transactions": [
        {
            "amount": {
                "total": "15.00",
                "currency": "EUR",
                "details": {
                    "subtotal": "15.00"
                }
            },
            "payee": {
                "merchant_id": "8KR2DFU4JQ682"
            },
            "description": "Payment description",
            "invoice_number": "59413dd5588a6",
            "soft_descriptor": "PAYPAL *MRSTESTSTOR",
            "item_list": {
                "items": [
                    {
                        "name": "Ground Coffee 40 oz",
                        "description": "Ground Coffee 40 oz",
                        "price": "5.00",
                        "currency": "EUR",
                        "tax": "0.00",
                        "quantity": 1
                    },
                    {
                        "name": "Ground Coffee 40 oz 5555",
                        "description": "Ground Coffee 40 oz",
                        "price": "10.00",
                        "currency": "EUR",
                        "tax": "0.00",
                        "quantity": 1
                    }
                ],
                "shipping_address": {
                    "recipient_name": "Stefan Bergmann",
                    "line1": "M\u00fchlenstrasse 59",
                    "city": "W\u00fcrzburg",
                    "state": "",
                    "postal_code": "97014",
                    "country_code": "DE"
                }
            },
            "related_resources": [
                {
                    "sale": {
                        "id": "8K183812C20626822",
                        "state": "completed",
                        "amount": {
                            "total": "15.00",
                            "currency": "EUR",
                            "details": {
                                "subtotal": "15.00"
                            }
                        },
                        "payment_mode": "INSTANT_TRANSFER",
                        "protection_eligibility": "ELIGIBLE",
                        "protection_eligibility_type": "ITEM_NOT_RECEIVED_ELIGIBLE,UNAUTHORIZED_PAYMENT_ELIGIBLE",
                        "transaction_fee": {
                            "value": "0.64",
                            "currency": "EUR"
                        },
                        "receipt_id": "280163013842171",
                        "parent_payment": "PAY-01Y41728PS359693FLFAT3VQ",
                        "create_time": "2017-06-14T13:46:55Z",
                        "update_time": "2017-06-14T13:46:55Z",
                        "links": [
                            {
                                "href": "https://api.sandbox.paypal.com/v1/payments/sale/8K183812C20626822",
                                "rel": "self",
                                "method": "GET"
                            },
                            {
                                "href": "https://api.sandbox.paypal.com/v1/payments/sale/8K183812C20626822/refund",
                                "rel": "refund",
                                "method": "POST"
                            },
                            {
                                "href": "https://api.sandbox.paypal.com/v1/payments/payment/PAY-01Y41728PS359693FLFAT3VQ",
                                "rel": "parent_payment",
                                "method": "GET"
                            }
                        ],
                        "soft_descriptor": "PAYPAL *MRSTESTSTOR"
                    }
                }
            ]
        }
    ],
    "create_time": "2017-06-14T13:46:55Z",
    "links": [
        {
            "href": "https://api.sandbox.paypal.com/v1/payments/payment/PAY-01Y41728PS359693FLFAT3VQ",
            "rel": "self",
            "method": "GET"
        }
    ]
}</pre>
<br>
PayPal payment, response:
<pre>
{
    "id": "PAY-01F49332GG461303XLFAT6OA",
    "intent": "sale",
    "state": "approved",
    "cart": "23J80365Y16775935",
    "payer": {
        "payment_method": "paypal",
        "status": "VERIFIED",
        "payer_info": {
            "email": "sandbox@akademie-sport-gesundheit.de",
            "first_name": "Masud",
            "last_name": "Rana",
            "payer_id": "M4ZW2WSWTGNY2",
            "shipping_address": {
                "recipient_name": "Masud Rana",
                "line1": "ESpachstr. 1",
                "city": "Freiburg",
                "state": "Empty",
                "postal_code": "79111",
                "country_code": "DE"
            },
            "phone": "7888140719",
            "country_code": "DE"
        }
    },
    "transactions": [
        {
            "amount": {
                "total": "15.00",
                "currency": "EUR",
                "details": {
                    "subtotal": "15.00"
                }
            },
            "payee": {
                "merchant_id": "8KR2DFU4JQ682"
            },
            "description": "Payment description",
            "invoice_number": "59413f37dd72e",
            "item_list": {
                "items": [
                    {
                        "name": "Ground Coffee 40 oz",
                        "description": "Ground Coffee 40 oz",
                        "price": "5.00",
                        "currency": "EUR",
                        "tax": "0.00",
                        "quantity": 1
                    },
                    {
                        "name": "Ground Coffee 40 oz 5555",
                        "description": "Ground Coffee 40 oz",
                        "price": "10.00",
                        "currency": "EUR",
                        "tax": "0.00",
                        "quantity": 1
                    }
                ],
                "shipping_address": {
                    "recipient_name": "Masud Rana",
                    "line1": "ESpachstr. 1",
                    "city": "Freiburg",
                    "state": "Empty",
                    "postal_code": "79111",
                    "country_code": "DE"
                }
            },
            "related_resources": [
                {
                    "sale": {
                        "id": "21A95372AL539953M",
                        "state": "completed",
                        "amount": {
                            "total": "15.00",
                            "currency": "EUR",
                            "details": {
                                "subtotal": "15.00"
                            }
                        },
                        "payment_mode": "INSTANT_TRANSFER",
                        "protection_eligibility": "ELIGIBLE",
                        "protection_eligibility_type": "ITEM_NOT_RECEIVED_ELIGIBLE,UNAUTHORIZED_PAYMENT_ELIGIBLE",
                        "transaction_fee": {
                            "value": "0.64",
                            "currency": "EUR"
                        },
                        "parent_payment": "PAY-01F49332GG461303XLFAT6OA",
                        "create_time": "2017-06-14T13:51:12Z",
                        "update_time": "2017-06-14T13:51:12Z",
                        "links": [
                            {
                                "href": "https://api.sandbox.paypal.com/v1/payments/sale/21A95372AL539953M",
                                "rel": "self",
                                "method": "GET"
                            },
                            {
                                "href": "https://api.sandbox.paypal.com/v1/payments/sale/21A95372AL539953M/refund",
                                "rel": "refund",
                                "method": "POST"
                            },
                            {
                                "href": "https://api.sandbox.paypal.com/v1/payments/payment/PAY-01F49332GG461303XLFAT6OA",
                                "rel": "parent_payment",
                                "method": "GET"
                            }
                        ]
                    }
                }
            ]
        }
    ],
    "create_time": "2017-06-14T13:51:12Z",
    "links": [
        {
            "href": "https://api.sandbox.paypal.com/v1/payments/payment/PAY-01F49332GG461303XLFAT6OA",
            "rel": "self",
            "method": "GET"
        }
    ]
}
</pre>

**Comment by xiaoleih41** [comment]
By reading the [integration guide](https://www.paypalobjects.com/webstatic/de_DE/downloads/PayPal-PLUS-IntegrationGuide.pdf), the only valid payment resource is PayPal account payments (p8). Therefore I suspect the response will always show it as a PayPal transaction regardless the payment method was chosen.

**Comment by masudewucse** [comment]
As Paypal payment required one extra step (Execute after success: issues#873) which does not include in Credit card. 
How do i decide that step in my coding if i see all (paypal/Creditcard) are PayPal transaction?

**Comment by xiaoleih41** [comment]
Based on the integration guide I have referred earlier, it appears to me that execute after success is a necessary for all payment method types. I am closing this ticket as it's a duplicated ticket.
