### ISSUE TITLE
Cannot use "authorize" or "order" intent on JS Express Checkout

### ISSUE THREAD

**Issue by adam-laraqui** [paypal/PayPal-PHP-SDK#880]
### General information

* SDK/Library version: Latest
* Environment: Sandbox
* `PayPal-Debug-ID` values: No errors thrown

### Issue description

Hi there. I wanted to ask if there are known issues with the "authorize" and "order" intent options using Server-side REST. I have "sale" working fine with the JS Express Checkout, but with "authorize", I am getting this below screenshot with just a Log In button (even though I'm already in a session) and clicking the button just dismisses the PayPal overflow instantly. No errors are thrown though. I am guessing it is not intended to work with JS Express Checkout?

![image](https://user-images.githubusercontent.com/25623217/27265349-eec97c8e-548b-11e7-8cc7-f796ef95243f.png)

Any info would be appreciated.

**Comment by trainerbill** [comment]
@adam-laraqui This SDK will work with authorize and order as will the JS SDK.  This seems like an issue with the integration or possibly an issue in the sandbox environment.  Lets move this over to gitter so I can provide some realtime assistance.

https://gitter.im/paypal/paypal-checkout
