### ISSUE TITLE
 can't access sandbox and client Authentication failed 

### ISSUE THREAD

**Issue by vivekmore89** [paypal/PayPal-PHP-SDK#881]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS:

**Comment by xiaoleih41** [comment]
This was an issue resolved last night. Do you still have the issue? Please clean the cache and cookie and try again. Please make sure to add some balance  when you create the PayPal account. If it doesn't work, please provide some detail for us to do research.

**Comment by xiaoleih41** [comment]
Close the thread as the issue should have been solved.

**Comment by woopz27** [comment]
@xiaoleih41 can you send me a link of resolved issue?
