### ISSUE TITLE
Can't create aggreement when I'am using setExternalRememberMeId

### ISSUE THREAD

**Issue by chrisAFSanalytics** [paypal/PayPal-PHP-SDK#882]
When I'm using "setExternalRememberMeId", I get an error when the agreement create function is called.

//code
 $payerinfo = new PayerInfo();
 $payerinfo->setEmail($email)
              ->setExternalRememberMeId("$uid");
 $payer = new Payer();
 $payer->setPaymentMethod('paypal')
      ->setPayerInfo($payerinfo);
      $agreement->setPayer($payer); 
 $agreement = $agreement->create($apiContext);

//error
"error":"400{\"name\":\"MALFORMED_REQUEST\",\"message\":\"Incoming JSON request does not map to API request\",
\"information_link\":\"https:\/\/developer.paypal.com\/webapps\/developer\/docs\/api\/#MALFORMED_REQUEST\",\"debug_id\":\"3ec1cf8a54235\"}","state":1}

**Without setExternalRememberMeId, it works fine**

$payerinfo = new PayerInfo();
 $payerinfo->setEmail($email);
             
 $payer = new Payer();
 $payer->setPaymentMethod('paypal')
      ->setPayerInfo($payerinfo);
      $agreement->setPayer($payer); 
 $agreement = $agreement->create($apiContext);

**Comment by xiaoleih41** [comment]
This looks like a property that is nolonger included in [`Payer_Info ` object](https://developer.paypal.com/docs/api/payments.billing-agreements#definition-payer_information). Please use `payer_id` or `email` when you execute the agreement as the customer reference.

**Comment by chrisAFSanalytics** [comment]
Hi,
Thank for your answer.

however, payer_id is  The PayPal-assigned ID for the customer  and email is the paypal email 

This is bad, setExternalRememberMeId  allowed us to define our own customer id.
