### ISSUE TITLE
Access payer_id with LIPP

### ISSUE THREAD

**Issue by QuantumLlama** [paypal/PayPal-PHP-SDK#884]
Hello, is there a reason why we can't access payer_id attribute in the identity API?
getPayerId() returns as null.

Is it possible to just give everyone access to this by default? I don't see the harm, especially since it is also given when a payment is made.

I've looked it up and it seems we need to request access to it via tech support.
I created a ticket but it has been a week without a response.

I've called customer support and they could not help either.
My ticket reference # is 170615-000771

**Comment by xiaoleih41** [comment]
I have forwarded this request to our technical support team who is handling your ticket. They will respond to you.

**Comment by xiaoleih41** [comment]
Close this ticket as the MTS team has taken it over.
