### ISSUE TITLE
Uncaught Error: Class 'Paypal\Rest\ApiContext'

### ISSUE THREAD

**Issue by Kalilufr** [paypal/PayPal-PHP-SDK#885]
Good morning,
I am having this message:

Fatal error: Uncaught Error: Class 'Paypal\Rest\ApiContext' not found

 and I keep searching how to fix it but nothing is working.

Here is my code

<?php 

require 'vendor/autoload.php';

define('SITE_URL', 'https://mysite.com/products.php');

$paypal = new Paypal\Rest\ApiContext(
	new \Paypal\Auth\OAuthTokenCredential(
		'CLIENT_ID,
		'SECRET_ID'
		)
);

Can you help me? Thank you so much

**Comment by xiaoleih41** [comment]
I am not sure if you have installed the SDK correctly. Please check [the instruction](https://github.com/paypal/PayPal-PHP-SDK/wiki/Installation) and confirm the file directory after the installation to make sure that you have everything needed in place.

**Comment by Kalilufr** [comment]
I had installed the SDK the right way but I did it again, in case.
Everything looks in the right place except that in vendor I find a "psr"
file that is not in the doc you send me to.
The error I asked help for got solved (not sure why) but I know get this
one :

*Fatal error*: Uncaught Error: Class 'Paypal\Api\Payer' not found

I really appreciate your quick answer and any help you can offer me. Thank
you

2017-06-26 21:27 GMT+02:00 Xiaolei Wheelock <notifications@github.com>:

**Comment by xiaoleih41** [comment]
Did you follow the wiki page step by step and configure the bootstrap.php page as [indicated](https://github.com/paypal/PayPal-PHP-SDK/wiki/Samples)? Have you run any of the samples? Were those successful?

**Comment by Kalilufr** [comment]
I now have followed every step and it is working.
I am very grateful for your time and much appreciated help.

2017-06-26 22:55 GMT+02:00 Xiaolei Wheelock <notifications@github.com>:

**Comment by xiaoleih41** [comment]
I am glad it has solved the issue. close this thread.

**Comment by samolabams** [comment]
The solution is that the Class name is not well capitalized. Its supposed to be '**PayPal**\Rest\ApiContext' instead of '**Paypal**\Rest\ApiContext'
