### ISSUE TITLE
Paypal Recurring Payment Rest api question

### ISSUE THREAD

**Issue by usamamashkoor** [paypal/PayPal-PHP-SDK#886]
Hi i am trying to create a monthly subscription using PayPal rest API php 
here are the steps which i have followed 
1)Create a Plan
2)Activate that Plan
3)Create a Billing Agreement
4)then got a approval link from PayPal when customer login and click agree then i execute the billing agreement using the token 

but when i print the agreement response object which is returned after execution 
```
echo "<pre>";
    print_r($result);
echo "</pre>";
```

then i am not getting the transaction fee in the response i have initial setup fee 10 i can see the fee in response but not the transaction fee on setup initial fee.

can some one let me know how can i get it.?

and i also want to know about the PayPal web hook which are important for the monthly subscription functionality.
for example
1)user cancel the subscription notification 
2)user monthly payment payment success notification 
and any other web hook which is necessary for this.

i am following this guide for this 
https://developer.paypal.com/docs/api/quickstart/create-billing-plan/

kindly help me on this issue please.

Thanks and Regard
M.Usama

**Comment by xiaoleih41** [comment]
The fee you saw in the response should be the fee for the `setup_fee` as that should be the only transaction completed when you execute the billing agreement. 
Please refer to https://github.com/paypal/PayPal-REST-API-issues/issues/105 for the questions about webhooks.

**Comment by xiaoleih41** [comment]
Please follow https://github.com/paypal/PayPal-REST-API-issues/issues/112 for including transaction fee to the API response associated with billing agreement execution.

**Comment by usamamashkoor** [comment]
Thanks @xiaoleih41 let me check the webhook questions and also Thanks  for the transaction fee issue.
i am also facing one more issue hope you can help me out on this one.
i can now create the subscription using php paypal rest api but when i logged into the businesses sandbox account i can see the subscription their but the subscription payments status  are shown as Unclaimed and the amount is not adding into the balance of sandbox business account.
Can you please help me on this...
Thanks

**Comment by xiaoleih41** [comment]
What's the `DebugId` in your API response or your sandbox account email address?

**Comment by usamamashkoor** [comment]
Email address of sandbox account is  usama-bussiness@gmail.com

**Comment by usamamashkoor** [comment]
the customer has agree to the agreement and i have got the token back from paypal and i executed the agreement using the token but i did not get any DebugId in the response after agreement execution.

**Comment by xiaoleih41** [comment]
The payment is in AUD which is not a currency held on your account. Under your account **profile>payment receiving preferences**, you can choose to accept payments in a currency that you don't currently hold or you can open the AUD balance inside of your PayPal account.

**Comment by usamamashkoor** [comment]
Hi but i can not see the payment receiving preferences, in my account 
![paypal profile](https://user-images.githubusercontent.com/8676339/27880111-43dad818-61dd-11e7-8bba-b660d61bebaf.png)

**Comment by xiaoleih41** [comment]
Click on **profile**, you will get to the profile page. Under **Security and risk settings**, you should see **Payment receiving preferences**.

**Comment by usamamashkoor** [comment]
sorry could not find the  Security and risk settings i have checked all the tabs.
![paypal info](https://user-images.githubusercontent.com/8676339/27880561-d6ddf694-61de-11e7-942b-d4688597f4b3.png)

**Comment by xiaoleih41** [comment]
You may look into **My selling tools**. If you still cannot see, please use **contact us** tab to contact our customer service department as your account layout may be different from mine.

**Comment by usamamashkoor** [comment]
in the selling tools i clicked on Block payments then it shows me
Payment Receiving Preferences	 page 
then i see this option with radio box
Allow payments sent to me in a currency I do not hold:
 Yes, accept and convert them to U.S. Dollars. Additional charges apply.
 No, deny the payments 
 Ask Me, decide accepting or denying each individual payment 

and i check this option 
 Yes, accept and convert them to U.S. Dollars. Additional charges apply.

let me know if this is right.

**Comment by usamamashkoor** [comment]
Thanks after doing the above setting now the Payment status	shows complete. Thanks again now will look into the subscription hooks.

**Comment by xiaoleih41** [comment]
Close this issue as the issue has been solved.
