### ISSUE TITLE
PayPal Guest Checkout Will Not Show Shipping Address Fields (PayPal Payments Standard)

### ISSUE THREAD

**Issue by skyready** [paypal/PayPal-PHP-SDK#887]
Hello,

I saw the closed issue at https://github.com/paypal/PayPal-PHP-SDK/issues/57 about HIDING the Shipping Address fields on the PayPal payment screen. But I am having the opposite problem:

Using OpenCart 2.3.0.2, and PayPal Payments Standard. When a customer chooses the option to "Pay with Debit or Credit Cart" (PayPal Guest Checkout I think they call it), when they are taken to that screen, there are fields for the Billing Address, but no Shipping Address. The transactions go thru fine, but when I log into my PayPal business account to check the orders, none of the orders have a Shipping Address. I am using ShipStation (a PayPal product, I think), to import the PayPal transactions so I can print USPS Shipping Labels. But, since PayPal doesn't have Shipping Addresses for these orders, I have to MANUALLY type in every customer Shipping Address for EVERY order, if I want to print Shipping Labels.

I found some forum posts (and even some PayPal documentation) that says you can force the PayPal Payment screen to display Shipping Address fields by having the following line in the OpenCart code that is used to send the data to PayPal (I have ommitted the html tags, as they cause the code not to show up in this post:

input type="hidden" name="no_shipping" value="2"

A "no_shipping" value of "2" means "Prompt for an address, and require one", which is what I need. I need the customer to fill out the Shipping Address fields on the Guest Checkout screen (even better if I could send the Shipping Address to PayPal and have them pre-populate the Shipping Address fields, like they do for the Billing Address). But setting the "no_shipping" value to "2" does NOT make the Shipping Address fields appear on the Guest Checkout screen.

There is also the following line of code that can be added, according to PayPal docs:

input type="hidden" name="address_override" value="1"

... which is SUPPOSED to allow OpenCart to override the PayPal shipping address (but this is Guest Checkout, remember? There is no PayPal shipping address in this case). In any event, this setting also does nothing.

I don't know what happens if my customers choose to pay with their PayPal account ... haven't tested this yet. But I need the Shipping Address to be stored in the PayPal transaction, so ShipStation will work properly. ShippingEasy, (similar to ShipStation) will not even import PayPal transactions that don't contain a Shipping Address.

I think I saw some docs on how to pass the Shipping Address to PayPal if using PayPal Express Checkout, but I am using PayPal Payments Standard, and I could find no such documentation.

At my wits end on this problem. Hoping SOMEONE from PayPal will answer this post (I have filed a ticket with PayPal, but as usual, they are notoriously slow to act on these types of critical issues). 

Help!

Larry Sanford
![paypal_guest_checkout](https://user-images.githubusercontent.com/29945130/27905372-8f27c5d0-61f4-11e7-89be-b3fd7b8eaf30.jpg)

**Comment by xiaoleih41** [comment]
@skyready Please reach out to OpenCart and [ShipStation](https://help.shipstation.com/hc/en-us) directly regarding your shipping label issue.  As this is not a PayPal SDK issue, I am closing this issue.

**Comment by skyready** [comment]
Xiaolei,

 

Can you please provide a little more clarification, other than just “This is not a PayPal SKD issue”?

 

At least let me know if my assumptions about the html settings I mention in the post are correct. At least answer the question: What do I have to do on my end to ensure that PayPal will show the Shipping Address fields on the PayPal Guest Checkout screen?

 

Thank you,

 

Lucas Sanford

 

Sky Ready RC

(858) 500-2306

www.skyreadyrc.com

 

logo

**Comment by xiaoleih41** [comment]
@skyready  You can parse the following [HTML Variables](https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/Appx_websitestandard_htmlvariables/) to PayPal for PayPal to display the shipping address.

**Comment by skyready** [comment]
Xiaolei,

 

I really appreciate the prompt response, as I am trying to fix this issue so I can start earning money for me, and for PayPal!

 

Yes, I have seen the documentation you pointed me to, in fact, I used it to determine how to get the PayPal Guest Payment screen to display Shipping Address, but it does not work. Below is how I am parsing the data to send to PayPal. All of the Billing Address fields are being pre-populated on the PayPal Guest Payment screen (except State and Phone Number, but I am not passing the Phone Number to PayPal). What am I doing wrong here? I am following the PayPal documentation. Are there additional values I need to pass in for Shipping Address? If so, that is not in the PayPal documentation you pointed me to. 

 

Note, I am setting “no_shipping” = “2”, which is supposed to “'Prompt for an address, and require one”, according to the PayPal documentation. Is this not supposed to make the PayPal Guest Payment screen display Shipping Address fields?

 

Note also that I tried setting “address_override” to “0” and “1”, but neither setting has any effect.

 









<input type="hidden" name="no_shipping" value="2" />

 



<input type="hidden" name="address_override" value="1" />

 



<input type="hidden" name="state" value="<?php echo $state; ?>" />

 

<input type="hidden" name="first_name" value="<?php echo $first_name; ?>" />

<input type="hidden" name="last_name" value="<?php echo $last_name; ?>" />

<input type="hidden" name="address1" value="<?php echo $address1; ?>" />

<input type="hidden" name="address2" value="<?php echo $address2; ?>" />

<input type="hidden" name="city" value="<?php echo $city; ?>" />

<input type="hidden" name="email" value="<?php echo $email; ?>" />

<input type="hidden" name="zip" value="<?php echo $zip; ?>" />

<input type="hidden" name="country" value="<?php echo $country; ?>" />

<input type="hidden" name="bn" value="OpenCart_2.0_WPS" />

 

I have attached a screen capture of the PayPal Guest Checkout screen, so you can see the result.

 

Thanks again for helping me on this. I want nothing more than to start using PayPal for my online store!

 

Regards,

 

Larry Sanford

 

Sky Ready RC

(858) 500-2306

www.skyreadyrc.com

 

logo

**Comment by fedoranna** [comment]
Hello!

I can see that this is an old post, but I still have a very similar problem. 
I use PayPal buttons on my Wordpress website and no_address=2 does not work. I tried with subscription buttons and buy now buttons, does not work with either. I don't get ANY shipping or billing info from my cusctomers.
Does anyone know how to solve this problem?

Thanks,
Anna
