### ISSUE TITLE
Item with negative price causes error 500 on payment execute

### ISSUE THREAD

**Issue by shoguniphicus** [paypal/PayPal-PHP-SDK#888]
* SDK/Library version: 1.7.2
* Environment: Sandbox
* `PayPal-Debug-ID` values: 27f354b028bf7
* Language, language version, and OS: Ubuntu 16.04

### Issue description
I can perform payment that all item has positive price, and it's still working in both Sandbox and Production.

But when I add an item with negative price, something like "-20.00", then when I land on Paypal's site, the subtotal, grandtotals are displayed correctly. The problem only occurs when Paypal tried to execute the payment.

It sort of hangs for almost a minute, then gives error 500.

**Comment by xiaoleih41** [comment]
I could not reproduce the error. I was able to process payments with negative priced items.  Please send me your request JSON and response for us do further testing.

**Comment by shoguniphicus** [comment]
This is the request json

```json
{"intent":"sale","payer":{"payment_method":"paypal"},"redirect_urls":{"return_url":"http://my.stoned.app/checkout/payment/execute/paypal?success=true","cancel_url":"http://my.stoned.app/checkout/payment/execute/paypal?success=false"},"transactions":[{"amount":{"currency":"MYR","total":"200","details":{"shipping":"20","subtotal":"180"}},"item_list":{"items":[{"name":"New Taiwan Product","currency":"MYR","quantity":1,"sku":"WTF","price":"200"},{"name":"NEWYEAR2016","description":"PROMO CODE","currency":"MYR","quantity":1,"sku":"NEWYEAR2016","price":"-20"}]},"description":"Payment description","invoice_number":"1.100017.292"}]}
```

This is during execute
```json
'{"payer_id":"EHUP8DSUZDKJA","transactions":[{"amount":{"currency":"MYR","total":"200","details":{"shipping":"20","subtotal":"180"}}}]}'
```

Do note that I am however, able to do normal purchase if I just dont put any reduction to the price of the item. I am well aware of the logic that Paypal will use to calculate all the items to get the grandtotal. So I am pretty confused what's missing here.

**Comment by xiaoleih41** [comment]
Are you using credit card for payment? Are you using random generated credit card? Can you make sure to generate a new random one? Sometimes, if the card was overused in sandbox environment, you may get this error.

**Comment by pp-randy** [comment]
4242 is the ending of a common test card which probably explains the issue.  

Please follow this FAQ to add a new credit card to your buyer account https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1413.

**Comment by shoguniphicus** [comment]
pp-randy, No I just did a transaction using the same card. But this time, without the negative-priced item. And Paypal process the payment just fine.

This is the response from the successful payment just now.
id	paypalpaymentid	state	payer_id	payment_id	created_at	updated_at
13	PAY-84856104UF532292VLFUOJXY	approved	EHUP8DSUZDKJA	37	2017-07-14 23:36:28	2017-07-14 23:36:28

I actually read about the stuff on the Paypal site, and I change the credit card to new ones. Doesnt seem to solve the problem.

**Comment by pp-randy** [comment]
I apologize for the inconvenience. Can you provide the response JSON for the failure with the newer generated credit card being used?

**Comment by shoguniphicus** [comment]
This is from the new card, with the same error
```json
{"name":"INTERNAL_SERVICE_ERROR","details":[],"message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"77451a6d50aa0"}
```
Funnily enough, the response from Paypal's redirection is always successful.
http://my.stoned.app/checkout/payment/execute/paypal?success=true&paymentId=PAY-3D8618685C945144PLFUONKQ&token=EC-6VS39135H36246808&PayerID=EHUP8DSUZDKJA

The request JSON is
```json
{"intent":"sale","payer":{"payment_method":"paypal"},"redirect_urls":{"return_url":"http://my.stoned.app/checkout/payment/execute/paypal?success=true","cancel_url":"http://my.stoned.app/checkout/payment/execute/paypal?success=false"},"transactions":[{"amount":{"currency":"MYR","total":"200","details":{"shipping":"20","subtotal":"180"}},"item_list":{"items":[{"name":"New Taiwan Product","currency":"MYR","quantity":1,"sku":"WTF","price":"200"},{"name":"NEWYEAR2016","description":"PROMO CODE","currency":"MYR","quantity":1,"sku":"NEWYEAR2016","price":"-20"}]},"description":"Payment description","invoice_number":"1.100017.293"}]}
```

**Comment by pp-randy** [comment]
Thank you @shoguniphicus I'm regularly able to reproduce this. 

I was able to complete payments using some lower and higher amount totals.  300 it seems was working fine. 

```
{
	"transactions": [{
			"amount": {
				"total": 300,
				"currency": "MYR",
				"details": {
					"subtotal": 285,
					"shipping": 15
				}
			},
			"description": "Testing",
			"item_list": {
				"items": [{
						"currency": "MYR",
						"price": 300,
						"quantity": 1,
						"name": "Test Item"
					}, {
						"currency": "MYR",
						"price": -15,
						"quantity": 1,
						"name": "Discount"
					}
				]
			}
		}
	]
}
```

**Comment by pp-randy** [comment]
Since this is API issue please follow here https://github.com/paypal/PayPal-REST-API-issues/issues/116 for further updates on the resolution.

If you have any further questions please let me know.
