### ISSUE TITLE
Billing address for Credit card payment

### ISSUE THREAD

**Issue by masudewucse** [paypal/PayPal-PHP-SDK#889]
I am using Paypal Plus (iframe). 
Is there any Class in Paypal-PHP-SDK which serves the Billing address for Credit card payment?
I did not find any right Class for Billing information. 
I used the following : 
<pre>

        $payer = new \PayPal\Api\Payer();
        $payer->setPaymentMethod('paypal');

        $addr = new \PayPal\Api\Address();
        $addr->setLine1("3909 Witmer Road")
            ->setLine2("Niagara Falls")
            ->setCity("Niagara Falls")
            ->setState("NY")
            ->setPostalCode("14305")
            ->setCountryCode("US")
            ->setPhone("716-298-1822");
        $payer_info = new \PayPal\Api\PayerInfo();
        $payer_info->setBillingAddress($addr);
</pre>
But it did not work!
I do not want my customers to write the billing info again in the paypal creditcard form because they already provided these info in my website. Please help!

**Comment by xiaoleih41** [comment]
PayPal plus integration may have different way in handling billing agreement related info based on the country you have registered your account under . Please submit a ticket at https://www.paypal-techsupport.com/, the tech team from your region should be able to help with your specific questions.

**Comment by xiaoleih41** [comment]
Close this issue as the correct contact channel has been provided.
