### ISSUE TITLE
Including the SDK without Composer

### ISSUE THREAD

**Issue by guy123123** [paypal/PayPal-PHP-SDK#89]
How would I go about utilizing the SDK without composer? 

This is all I've found on the issue and it doesn't work:

"In case you cannot install composer on your machine, you can fetch the SDK download bundle from https://github.com/paypal/sdk-packages/raw/gh-pages/rest-api-sdk/php/rest-api-sdk-php-0.7.1.zip and unzip the contents to the samples folder."

Any help would be greatly appreciated. Thanks.

**Comment by yurtesen** [comment]
This doesn't seem to be working. The updated documentation has same code for both composer and non-composer systems. (in next page where it says make your first call). and at least in my system, php is not able to find the classes.

```
<?php
// 1. Autoload the SDK Package. This will include all the files and classes to your autoloader
// Used for composer based installation
require __DIR__  . '/vendor/autoload.php';
// Use below for direct download installation
// require __DIR__  . '/vendor/autoload.php';
```

**Comment by jaypatel512** [comment]
Thanks for pointing this out. I have updated the wiki with correct info: 

```php
<?php
// 1. Autoload the SDK Package. This will include all the files and classes to your autoloader
// Used for composer based installation
require __DIR__  . '/vendor/autoload.php';
// Use below for direct download installation
// require __DIR__  . '/PayPal-PHP-SDK/autoload.php';
```

**Comment by yurtesen** [comment]
Hi jaypatel512,
Thats all good but it doesnt work
I have 2 lines in my php file. I am trying to use
https://devtools-paypal.com/guide/recurring_payment_ec/php?env=sandbox
```
require './PayPal-PHP-SDK/autoload.php';
$paypalService = new PayPalAPIInterfaceServiceService($config);
```
It ends up with error

>  Fatal error: Class 'PayPalAPIInterfaceServiceService' not found in /var/www/html/test/test.php on line 3

**Comment by shatner** [comment]
Not sure if I'm the only one, but I can't find a version of the SDK which includes the autoload.php file referenced in the documentation. Specifically, this page https://github.com/paypal/PayPal-PHP-SDK/wiki/Installation-Direct-Download indicates what the file structure should be, but neither version 1.6.4 nor version 1.0.0 seem to reflect that file structure. (Here's what I see after downloading and unzipping those versions: http://imgur.com/a/EuVQY ).

[This guy](https://www.igorkromin.net/index.php/2015/06/08/a-quick-start-with-the-paypal-php-sdk-for-the-rest-api/) has some code that is intended to resolve the missing autoload.php but doesn't seem to do the trick (I still get the error "Class 'PayPal\Rest\ApiContext' not found")

Is the documentation inaccurate, or is support for using this SDK without composer incomplete, or am I just missing something obvious? Many thanks!

**Comment by jaypatel512** [comment]
Hey @shatner, the issue is, you are installing the wrong zip. For every release provided here: https://github.com/paypal/PayPal-PHP-SDK/releases, there is a zip file that we specifically package. (Not the ones that github auto generates). 

E.g. : PayPal-PHP-SDK-1.6.4.zip for the latest. Please download that, and unzip, and follow the instructions. You should be able to get the proper file structure after that.

**Comment by shatner** [comment]
Thanks for the quick reply. I was indeed missing something obvious. The instructions mention the .zip file, I just didn't realize the content would be different from the others. Glad I asked -- thank you again!

**Comment by velryphon** [comment]
Hi,

I've been struggling with integrating the Paypal Checkout SDK (without composer) for days, and I've finally make it work.

I have coded a loader that construct dependencies needed for the SDK to work, here it is :

`<?php

function autoload($classes, $deps_file)
{
		$deps	=array();	//Stores the classes that have been scanned
		$stack	=array();	//Stores the classes about to be scanned, needed to avoid scanning twice the same class

	foreach($classes as $class)
				load_class_file($class, $deps, $stack);

		$stream	="<?php".PHP_EOL;

	foreach($deps as $dep)
	{
		$stream	.=str_replace("\\", "/", "require(\"".$dep.".php\");".PHP_EOL);
		$stream	.="use ".$dep.";".PHP_EOL;
	}

		$stream	.="?>".PHP_EOL;

				file_put_contents($deps_file, $stream);
}

//==================================================

function load_class_file($class_path, &$deps, &$stack)
{
	if(!in_array($class_path, $stack))
	{
						$stack[]	=$class_path;
						$file		=$class_path.".php";

		if(file_exists($file))
		{
						$content	=file_get_contents($file);
						$lines		=explode("\n", $content);
						$namespace;
						$uses		=array();

			foreach($lines as $line)
			{
				if(substr($line, 0, strlen("namespace ")) == "namespace ")
				{
						$namespace	=str_replace(";", "", str_replace("namespace ", "", $line));
				}
				if(substr($line, 0, strlen("use ")) == "use ")
				{
						$uses[]		=substr($line, strlen("use "), strlen($line) - strlen("use ") - 1);

									load_class_file(end($uses), $deps, $stack);
				}
				else if(strpos($line, "extends") > 0)
				{
						$line		=str_replace("class ", "", $line);
						$line		=str_replace(" extends ", ";", $line);
						$fields		=explode(";", $line);
						
						$child		=$fields[0];
						$mother		=$fields[1];

						$found		=false;

					if(file_exists($namespace."\\".$mother.".php"))
								load_class_file($namespace."\\".$mother, $deps, $stack);
				}
				else if(strpos($line, "new ") > 0)
				{
						$data		=explode("new ", $line)[1];
						$class		=trim(explode("(", $data)[0]);

						$found		=false;

					foreach($uses as $use)
					if(strpos($use, $class))
					{
						$found		=true;
									break;
					}

					if(!$found)
					if(file_exists($namespace."\\".$class.".php"))
									load_class_file($namespace."\\".$class, $deps, $stack);
				}
				else if(strpos($line, "::") > 0)
				{
						$data		=explode("::", $line)[0];
						$data		=explode(" ", $data);
						$class		=trim(end($data));

						$found		=false;

					foreach($uses as $use)
					if(strpos($use, $class))
					{
						$found		=true;
									break;
					}

					if(!$found)
					if(file_exists($namespace."\\".$class.".php"))
									load_class_file($namespace."\\".$class, $deps, $stack);
				}
			}

						$deps[]		=$class_path;
		}
	}
}

?>`

Then simply execute once the main function to build dependencies :

```
include("autoload.php");

$classes	=array();
$classes[]	="BraintreeHttp\Encoder";
$classes[]	="PayPalCheckoutSdk\Core\PayPalHttpClient";
$classes[]	="PayPalCheckoutSdk\Core\SandboxEnvironment";
$classes[]	="PayPalCheckoutSdk\Orders\OrdersGetRequest";

			autoload($classes, "deps.php");
```
This code scans for the 4 main classes (Encoded, PaypalHttpClient, SandboxEnvironment and OrdersGetRequest) called by the sample code from SDK (PaypalClient class) :+1: 

```
class PayPalClient
{
    public static function client()
    {
        return new PayPalHttpClient(self::environment());
    }

    public static function environment()
    {
        $clientId = YOUR_SB_CLIENT_ID;
        $clientSecret = YOUR_SB_CLIENT_SECRET;
        return new SandboxEnvironment($clientId, $clientSecret);
    }
}

class PaypalOrder
{
  public static function getOrder($orderId)
  {
    $client = PayPalClient::client();
    $response = $client->execute(new OrdersGetRequest($orderId));
    print "Status Code: {$response->statusCode}\n";
    print "Status: {$response->result->status}\n";
    print "Order ID: {$response->result->id}\n";
    print "Intent: {$response->result->intent}\n";
    print "Links:\n";
    foreach($response->result->links as $link)
    {
      print "\t{$link->rel}: {$link->href}\tCall Type: {$link->method}\n";
    }
    print "Gross Amount: {$response->result->purchase_units[0]->amount->currency_code} {$response->result->purchase_units[0]->amount->value}\n";
  }
}
if (!count(debug_backtrace()))
{
  PaypalOrder::getOrder($_POST["orderID"], true);
}
```

Here are the depencencies generated from this autoloader, needed for the PayPalClient to work : 

```
require("BraintreeHttp/HttpRequest.php");
use BraintreeHttp\HttpRequest;
require("BraintreeHttp/Serializer.php");
use BraintreeHttp\Serializer;
require("BraintreeHttp/Serializer/Form.php");
use BraintreeHttp\Serializer\Form;
require("BraintreeHttp/Serializer/Json.php");
use BraintreeHttp\Serializer\Json;
require("BraintreeHttp/Serializer/FormPart.php");
use BraintreeHttp\Serializer\FormPart;
require("BraintreeHttp/Serializer/Multipart.php");
use BraintreeHttp\Serializer\Multipart;
require("BraintreeHttp/Serializer/Text.php");
use BraintreeHttp\Serializer\Text;
require("BraintreeHttp/Encoder.php");
use BraintreeHttp\Encoder;
require("BraintreeHttp/Curl.php");
use BraintreeHttp\Curl;
require("BraintreeHttp/IOException.php");
use BraintreeHttp\IOException;
require("BraintreeHttp/HttpResponse.php");
use BraintreeHttp\HttpResponse;
require("BraintreeHttp/HttpException.php");
use BraintreeHttp\HttpException;
require("BraintreeHttp/HttpClient.php");
use BraintreeHttp\HttpClient;
require("BraintreeHttp/Injector.php");
use BraintreeHttp\Injector;
require("PayPalCheckoutSdk/Core/AccessTokenRequest.php");
use PayPalCheckoutSdk\Core\AccessTokenRequest;
require("PayPalCheckoutSdk/Core/AccessToken.php");
use PayPalCheckoutSdk\Core\AccessToken;
require("PayPalCheckoutSdk/Core/AuthorizationInjector.php");
use PayPalCheckoutSdk\Core\AuthorizationInjector;
require("PayPalCheckoutSdk/Core/GzipInjector.php");
use PayPalCheckoutSdk\Core\GzipInjector;
require("PayPalCheckoutSdk/Core/FPTIInstrumentationInjector.php");
use PayPalCheckoutSdk\Core\FPTIInstrumentationInjector;
require("PayPalCheckoutSdk/Core/Version.php");
use PayPalCheckoutSdk\Core\Version;
require("PayPalCheckoutSdk/Core/UserAgent.php");
use PayPalCheckoutSdk\Core\UserAgent;
require("PayPalCheckoutSdk/Core/PayPalHttpClient.php");
use PayPalCheckoutSdk\Core\PayPalHttpClient;
require("BraintreeHttp/Environment.php");
use BraintreeHttp\Environment;
require("PayPalCheckoutSdk/Core/PayPalEnvironment.php");
use PayPalCheckoutSdk\Core\PayPalEnvironment;
require("PayPalCheckoutSdk/Core/SandboxEnvironment.php");
use PayPalCheckoutSdk\Core\SandboxEnvironment;
require("PayPalCheckoutSdk/Orders/OrdersGetRequest.php");
use PayPalCheckoutSdk\Orders\OrdersGetRequest;
```

I'm not a PHP expert so I did'nt want to use composer which I didn't know. Moreover, I did'nt know how to use it on my host server.

I'm still in testing mode, so the ProductionEnvironment class has not yet been scanned to build its dependencies.

I hope it will be usefull for anyone wanting to integrate simple paypal transaction to simple website, without using Composer or any CMS that could already includes Paypal Checkout System.

**Comment by Rolf1952** [comment]
No we have mid 2019 and still the "PHP SDK without composer"-outoloader does not provide any classes. Does anybody know, where the bug is located?

I'm using PayPal-PHP-SDK-1.14.0.zip (download link: https://github.com/paypal/PayPal-PHP-SDK/releases/download/1.14.0/PayPal-PHP-SDK-1.14.0.zip)
