### ISSUE TITLE
400{"name":"MALFORMED_REQUEST","message":"Incoming JSON request does not map to API request"

### ISSUE THREAD

**Issue by shamim96** [paypal/PayPal-PHP-SDK#890]

**Comment by pp-randy** [comment]
@shamim96 can you provide any details or is this resolved now?

**Comment by shamim96** [comment]
it is resolve randy. Thank you for your response. i am new at github. i cannot find the option where from delete the post.

**Comment by AlexisWilke** [comment]
@shamim96 when you write a comment on your own issue you should have two butons: `Close Issue` or `Comment`. If you're all good, click the `Close Issue` button.
