### ISSUE TITLE
Paypal sandbox test transaction not working correctly 

### ISSUE THREAD

**Issue by shamim96** [paypal/PayPal-PHP-SDK#892]
I have created a sandbox checkout page with paypal sandbox app. I can go to checkout page and can complete the checkout transaction with another buyer sandbox account. Now the problem is when i go into the buyer sendbox account in the transaction history there are no transaction history about that checkout, and my balance is same as before. Also when  i go into my app sandbox account i see in the history i did not get any balance against that checkout. 
What is the problem i can not understand what is the problem. Anyone please give me solution. 
This is the link i have created for test checkout with paypal- http://briannamdix.website/paypal/checkout.php

**Comment by xiaoleih41** [comment]
I can see the redirect URL with EC token and payerID but I don't see you executing the payment. Please make sure to execute the payment once the user approves the payment. You can use sample code [here](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/ExecutePayment.php).

**Comment by shamim96** [comment]
Do you need to add the execution code into the success redirect success page? 
My return url/ success page have no code yet. Is the the reason.

**Comment by xiaoleih41** [comment]
Yes, you need to take the EC token and payer ID from the return URL to execute the payment.

**Comment by xiaoleih41** [comment]
Close this issue as it should have been solved.
