### ISSUE TITLE
$plans = \PayPal\Api\Plan::all(array(), $apiContext); only creates CREATED plans

### ISSUE THREAD

**Issue by AlexisWilke** [paypal/PayPal-PHP-SDK#893]
### General information

* SDK/Library version:  1.12.0
* Environment:  Sandbox
* `PayPal-Debug-ID` values:  n.a.
* Language, language version, and OS:  PHP 7.0.18-0ubuntu0.16.04.1 (cli) (NTS) Ubuntu 16.04

### Issue description

The `all()` function only returns plans that are `CREATED`.

I know I have `DELETED` and `ACTIVE` plans, those disappear from that list. `DELETED` I could understand, but I don't see why the `all()` function would not return `ACTIVE` plans?! (I did not try with `INACTIVE` plans, so maybe those are shown and maybe not.)

**Comment by pp-randy** [comment]
The status value default is CREATED, you need to adjust the status to retrieve your other plans. This default is not documented at this time, so we have an issue tracking the needed documentation changes here: https://github.com/paypal/PayPal-REST-API-issues/issues/117

We also have an issue for tracking the DELETED plans not being accessible here: https://github.com/paypal/PayPal-REST-API-issues/issues/28. Currently, passing DELETED status will fail validation. 

Please let me know if you have further questions.
