### ISSUE TITLE
Error when going to User Consent page

### ISSUE THREAD

**Issue by re1naldo** [paypal/PayPal-PHP-SDK#894]
I tried to generate User Consent URL by following the example [here](http://paypal.github.io/PayPal-PHP-SDK/sample/doc/lipp/ObtainUserConsent.html). The URL was generated but I got this error when accessing that URL:

> We're sorry. Looks like this action is not supported. Please return and report this error so that we can support it in the future. (invalid client_id or redirect_uri) 

The generated URL: [https://www.sandbox.paypal.com/signin/authorize?client_id=AQq19_B9TrZZMxkSlrrTeSR4pBwl5cX7g6VpgKAE1I07OKOSpn9qJLhplGewb3gqzfvZXaaSoqneIvA0&response_type=code&scope=openid+profile+address+email+phone+https%3A%2F%2Furi.paypal.com%2Fservices%2Finvoicing&redirect_uri=http%3A%2F%2Fwww.xxxxxxxxx.com%2Findex.php%3Fr%3Duser%252Fview%26id%3D1](https://www.sandbox.paypal.com/signin/authorize?client_id=AQq19_B9TrZZMxkSlrrTeSR4pBwl5cX7g6VpgKAE1I07OKOSpn9qJLhplGewb3gqzfvZXaaSoqneIvA0&response_type=code&scope=openid+profile+address+email+phone+https%3A%2F%2Furi.paypal.com%2Fservices%2Finvoicing&redirect_uri=http%3A%2F%2Fwww.xxx.com%2Findex.php%3Fr%3Duser%252Fview%26id%3D1)

Is the generated URL wrong?

**Comment by xiaoleih41** [comment]
I don't think PayPal support the **return URL** you have provided. Please refer to [PayPal Accept User Policy 2(i)](https://www.paypal.com/us/webapps/mpp/ua/acceptableuse-full) for detail.

**Comment by re1naldo** [comment]
@xiaoleih41 The URL that I provided before is not the actual one. The original site does not violate Paypal policy as far as I can see.

**Comment by re1naldo** [comment]
I have just tried to generate URL in Live mode but still got the same result. Why does it always give this error?

**Comment by xiaoleih41** [comment]
Your return URL doesn't match exact the one you put in your app. Also by looking at this generated URL the **+** sign has not been encoded as expected.

**Comment by re1naldo** [comment]
Actually, I have tried changing the return URL and set the application to Live. The generated URL now:

[https://www.paypal.com/signin/authorize?client_id=AZ3yYOmKUbJ74xuoYa_nn0A9NCeYcpRhx4ylZnSOu37XVzzNafzE0I-aONS9C4-92ZcHhMYkxP6fK4X3&response_type=code&scope=openid+profile+address+email+phone+https%3A%2F%2Furi.paypal.com%2Fservices%2Fpaypalattributes+https%3A%2F%2Furi.paypal.com%2Fservices%2Fexpresscheckout+https%3A%2F%2Furi.paypal.com%2Fservices%2Finvoicing&redirect_uri=https%3A%2F%2Fapp.sockoflorist.com%2Findex.php%3Fr%3Duser%252FgetToken%26id%3D3](https://www.paypal.com/signin/authorize?client_id=AZ3yYOmKUbJ74xuoYa_nn0A9NCeYcpRhx4ylZnSOu37XVzzNafzE0I-aONS9C4-92ZcHhMYkxP6fK4X3&response_type=code&scope=openid+profile+address+email+phone+https%3A%2F%2Furi.paypal.com%2Fservices%2Fpaypalattributes+https%3A%2F%2Furi.paypal.com%2Fservices%2Fexpresscheckout+https%3A%2F%2Furi.paypal.com%2Fservices%2Finvoicing&redirect_uri=https%3A%2F%2Fapp.sockoflorist.com%2Findex.php%3Fr%3Duser%252FgetToken%26id%3D3)

However, the error still appeared. How should the + sign be encoded?

**Comment by xiaoleih41** [comment]
I tried to decode your return uri. Here is what I got. https://app.sockoflorist.com/index.php?r=user%2FgetToken&id=3. Please fix it so that it is same as the one you put in the app. Also, please use [state](https://developer.paypal.com/docs/api/auth-headers/#obtain-users-consent) parameter in the return URL.

**Comment by re1naldo** [comment]
Thanks for the info on state parameter. The initial error was gone and now I see an Invalid Scope error:

> Looks like this action is not supported. Please return and report this error so that we can support it in the future. (invalid scope)

I use email and invoicing scopes:
```
OpenIdSession::getAuthorizationUrl(
      $baseUrl,
      array('email', 'https://uri.paypal.com/services/invoicing'),
      self::PAYPAL_CLIENT_ID,
      null,
      $this->id,
      UserPayment::getApiContext()
)
```
Under Sandbox App Settings, Invoicing and Address Information fields have been checked. Why do I still get this error?

**Comment by re1naldo** [comment]
The URL suddenly works when I tested it again today. It is strange since I didn't change any code or settings.
