### ISSUE TITLE
SSL peer handshake failed

### ISSUE THREAD

**Issue by aronzillo** [paypal/PayPal-PHP-SDK#897]
### General information

* SDK/Library version: paypal/rest-api-sdk-php v1.11.0, library anouar/paypalpayment v2.0
* Environment: Sandbox
* Language, language version, and OS: PHP 7.0.20 on macOS Sierra 10.12.6

### Issue description

I am trying to implement PayPal on my site, but when trying to ask for approval of the purchase I get the following error:

`PayPalConnectionException {#221 ▼
  -url: "https://api.sandbox.paypal.com/v1/oauth2/token"
  -data: null
  #message: "SSL peer handshake failed, the server most likely requires a client certificate to connect"
  #code: 35
  #file: "/Users/Aronzillo/Laravel/ecommerce/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php"
  #line: 122`

What happen here?

**Comment by pp-randy** [comment]
Can you try with v1.12.0? https://github.com/paypal/PayPal-PHP-SDK/releases
I see a pull request with some TLS changes that might help: https://github.com/paypal/PayPal-PHP-SDK/pull/844

**Comment by marcoraddatz** [comment]
Got the same error with v1.12 and cURL v7.54.1 / OpenSSL v1.0.2l.

**Comment by pp-randy** [comment]
@aronzillo does removing the SSL version in the request correct the issue for you?

**Comment by davidbehler** [comment]
`	    $apiContext->setConfig(
	        array(
	            'http.CURLOPT_SSLVERSION' => CURL_SSLVERSION_TLSv1
	        )
	    );`

Fixed it for me.

**Comment by pp-randy** [comment]
TLS 1.2 is currently what should be used.  I would see if `CURL_SSLVERSION_TLSV1_2` works.

**Comment by xiaoleih41** [comment]
Close this issue due to inactivity.

**Comment by cdtweb** [comment]
@pp-randy I tried with `CURL_SSLVERSION_TLSv1_2` and I got the exact same error. Using `CURL_SSLVERSION_TLSv1` works just fine though.

**Comment by bionicmaster** [comment]
+1, I have the same error, this is only happening in sandbox

**Comment by JasonStainton** [comment]
+1 - Having the same error come back too in sandbox. Working on production.

**Comment by rosswintle** [comment]
+1 - Having the same issue here. Actually, I'm getting this response in local dev on my MacBook, but using Sandbox on my staging server is fine. So could be to do with the server environment, not the fact that you're using Sandbox. Using 1.12.0

**Comment by tempelmann** [comment]
I opened #943 because this one seems not to get noticed any more since it's gotten closed

**Comment by xiaoleih41** [comment]
Please refer to https://github.com/paypal/PayPal-PHP-SDK/issues/943 for the answers.
