### ISSUE TITLE
Payment all not showing all transactions

### ISSUE THREAD

**Issue by lesterjanpearson** [paypal/PayPal-PHP-SDK#898]
$total = 200;
$array = array();
for($x=0;$x<$total;$x+=20){
    $params = array('count' => 20,'start_index'=>$x);
    try {
        $response = Payment::all($params, $apiContext);
        //$result=json_decode($result, true, 512);
        $response = json_decode($response->toJSON(),true);
        $array = array_merge($array,$response['payments']);
    } catch (Exception $ex) {
        $array[] = $ex;
    }
}
$response = Payment::all($params, $apiContext);

when searching 1 email on the paypal summary I see 4 transactions of the email only minutes part.
but when I run this code. I only see 3. not sure why. they are succesfull payments.

**Comment by lesterjanpearson** [comment]
$payee_id = "xxxx";
$params = array('payee_id'=>$payee_id);

also wont filter the payee. it will display all.

**Comment by xiaoleih41** [comment]
Can you provide the **transactionIDs** of the transactions you can see?

**Comment by xiaoleih41** [comment]
Close the issue due to inactivity.
