### ISSUE TITLE
We are unable to validate your information. Please try again. -- At this time, we are unable to process your request. Please return to test account's Test Store and try another option.

### ISSUE THREAD

**Issue by AlexisWilke** [paypal/PayPal-PHP-SDK#899]
### General information

* SDK/Library version:  1.12.0
* Environment:  Sandbox
* `PayPal-Debug-ID` values:  n.a.
* Language, language version, and OS:  PHP 7.0.18-0ubuntu0.16.04.1 (cli) (NTS) Ubuntu 16.04

### Issue description

The creation of a plan and an agreement work as expected, but when I try to redirect the user to the agreement to accept it, I can log in but then I get that error:

> At this time, we are unable to process your request. Please return to test account's Test Store and try another option.

There is also another error message in a box at the top that looks like this:

> We are unable to validate your information. Please try again.

I don't know whether that can be useful to you, but one of the links to approve the agreement is:

https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-7X6121331J365924K

Is that message saying that there is a problem with the App, the user, my plan/agreement? It's really not clear at all and don't see what to do next.

FYI, this is AFTER I log in with the test user, so I would imagine the user in itself is fine. The Recurring Billing feature is turned on in the App. I am using the PHP SDK so you would think that this should work first time as is?!?

![paypal-test-store-failure](https://user-images.githubusercontent.com/1028617/28561741-5f0704a8-70d4-11e7-9def-977c4f4effdf.png)

**Comment by xiaoleih41** [comment]
do you have `debugId` of your API calls? what are the sandbox accounts you are trying to use?

**Comment by AlexisWilke** [comment]
The redirect itself does not generate a `debugId`...

The last time it created a new plan, a new agreement, and then tried to get the user to agree have the following `debugId`:

* 7a9511da7e2 -- create plan
* 9ce3db593671d -- activate plan
* a7dd31a711a03 -- create agreement

All 3 are successful.

Our test account is paypal@m2osw.com and I'm trying to make the payment with paypal-buyer@m2osw.com which has worked just fine in the past.

**Comment by xiaoleih41** [comment]
The buyer account's status is **closed**. Please create a new active account and try again.

**Comment by AlexisWilke** [comment]
Why would it be closed and how can I know? I don't recall ever closing on of my sandbox account?!

**Comment by xiaoleih41** [comment]
I don't know but try to open a new one should solve the issue.

**Comment by AlexisWilke** [comment]
Yeah! That worked. Now I have to write the code to execute the agreement and I should be there. It would have been great to get an error saying "Your account is closed" though, instead of "We are unable to validate your info."...

**Comment by xiaoleih41** [comment]
I don't think that much account specific info will be disclosed. It will only tell you there's some difficulty to access your account info regardless it was closed or get limited due to some other issue. I am glad the issue has solved. I am closing this issue now.
