### ISSUE TITLE
getBaseUrl(),  ExecutePayment.php

### ISSUE THREAD

**Issue by ldavis02** [paypal/PayPal-PHP-SDK#900]
### General information
* SDK/Library version: 1.12.0
* Environment: Sandbox
  Debug-IDs: NA
  Language:  PHP

### Issue description
In  CreatePaymentUsingPayPal.php there is a reference to a getBaseUrl function--

$baseUrl = getBaseUrl();
$redirectUrls = new RedirectUrls();
$redirectUrls->setReturnUrl("$baseUrl/ExecutePayment.php?success=true")
    ->setCancelUrl("$baseUrl/ExecutePayment.php?success=false");

However, the function doesn't seem to exist. This causes a Fatal error: call to undefined function.
The only other references to getBaseUrl seem to be in the sample/lipp directory of the 1.11.0 version of the SDK., but the function itself doesn't  seem to exist there either.

**Comment by bluk** [comment]
I believe the function is defined in [sample/common.php](https://github.com/paypal/PayPal-PHP-SDK/blob/b2c244199bfffa5f99178acdd1b463a14c398d63/sample/common.php#L176). It should be included via the required [bootstrap.php](https://github.com/paypal/PayPal-PHP-SDK/blob/b2c244199bfffa5f99178acdd1b463a14c398d63/sample/bootstrap.php#L20)

**Comment by ldavis02** [comment]
All set, thanks.
