### ISSUE TITLE
Samples are not in zip file

### ISSUE THREAD

**Issue by techpaul702** [paypal/PayPal-PHP-SDK#903]
Samples don't seem to be in downloaded zip file

**Comment by bluk** [comment]
This is an intentional change due to a few developers unintentionally copying the entire contents of the ZIP file into their website. In order to get a copy of the samples, you should clone this repository.

**Comment by weinraum** [comment]
I've cloned the repository and still no sample files are downloadable.

**Comment by bluk** [comment]
@weinraum Hmm. The samples should be located under the [`sample`](https://github.com/paypal/PayPal-PHP-SDK/tree/master/sample) directory in your `git clone`ed repository. Are they not present there?

**Comment by weinraum** [comment]
thank you @bluk , I've cloned it in github and the files are not downloaded neither. 

I've installed the githubdesktop.exe and got it via that prog.

thanks
