### ISSUE TITLE
UNKNOWN_ERROR with Vault Card

### ISSUE THREAD

**Issue by castillo8811** [paypal/PayPal-PHP-SDK#905]
### General information

* Environment: Sandbox
* `PayPal-Debug-ID` values: 7b6339d1f0df1, e3a3ad42a971d
* Language, language version, and OS: PHP 5.6, Fedora 25

### Issue description
```javascript

{"name":"UNKNOWN_ERROR","message":"An unknown error occurred.","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"e3a3ad42a971d"}
```
I am trying to create a Payment from a Vault Card like your example: https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/CreatePaymentUsingSavedCard.php  and Always I get a Unknow Error, I tried to change the PaymentCard  instead CredicardtToken and I always got the same error.

I verified my Account and the direct credicard payments is enable in my sandbox mode.

My JSON data:
```javascript
{
	"intent": "sale",
	"payer": {
		"payment_method": "credit_card",
		"funding_instruments": [{
			"credit_card_token": {
				"credit_card_id": "CARD-471328143C832022GLF7YLPY"
			}
		}]
	},
	"transactions": [{
		"amount": 3387120,
		"item_list": {
			"items": [{
				"name": "Socialme Booking Charge - 2017-09-05 04:30",
				"currency": "Mx",
				"quantity": 1,
				"price": "3387120"
			}]
		},
		"description": "Socialme Booking Charge - 2017-09-05 04:30",
		"invoice_number": "59810a0110265"
	}]
}
```

**Comment by pp-randy** [comment]
This is due to an overused credit card, we are tracking that issue here: https://github.com/paypal/PayPal-REST-API-issues/issues/22

I would also encourage using our [Braintree offering](https://www.braintreepayments.com/) if you are eligible as I have a pull request to remove credit card samples in this SDK https://github.com/paypal/PayPal-PHP-SDK/pull/896.
