### ISSUE TITLE
Adding a discount in Payments API?

### ISSUE THREAD

**Issue by WaldoTH** [paypal/PayPal-PHP-SDK#908]
Hello guys, I'm having a bit of trouble when validating my payment JSON (therefore I'm not getting the appropiate approval_url) when using a giftcard in my store:
I'll provide an example: 

My order has a subtotal = $100
Shipping is $50
I have a GIFTCARD = $-20
So, my total is = $130

However here's a sample of the JSON sent: 

**transactions":[{"amount":{"currency":"MXN","total":"130.00","details":{"shipping":"50.00","subtotal":"100"}},"payment_options":{"allowed_payment_method":"IMMEDIATE_PAY"},"item_list":{"items":[{"name":"BOOK-TEST","currency":"MXN","quantity":1,"price":"100.00"}]**

So, when I send this JSON, I get the following from the curl:

{"name":"VALIDATION_ERROR","details":[{"field":"transactions[0].amount","issue":"Transaction amount details (subtotal, tax, shipping) must add up to specified amount total"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"5bf80ae79750b"}

So, I guess Paypal is rejecting this payment because the subtotal (100) + shipping (50) should be $150 instead of $130, because it doesn't know that I'm using a giftcard to subtract from the total.

I checked in the [Payments API](https://developer.paypal.com/docs/api/payments/) (/v1/payments/payment) but I didn't found where should I put the GIFTCARD/DISCOUNT amount in the JSON in order to get the approval.

So, how can I make Paypal understand I'm applying a discount to my total? How can I add a discount field to the details section of the JSON? or is it even possible? 

Any help would be greatly appreciated! Thank you for your help and time!

**Comment by pp-randy** [comment]
Add a line item with a negative amount.

**Comment by WaldoTH** [comment]
Thank you, I'll do that as it seems there's no field for the discount on the JSON. But the negative item idea is great, thank you!

**Comment by theyuv** [comment]
Is this the recommended way to add withholding tax to a payment as well?
I want to subtract withholding tax from a Payment I'm creating. 
Should I just add a line item for this (with quantity = 1)?
Or is there a more appropriate field where this should be entered?

Some background:
Withholding tax is usually a percentage of the total of the payment. 
So if the payment is $100 and there is 20% withholding tax, the payment should be for $80 and I would like the details of this to be accurately presented in the payment details.
