### ISSUE TITLE
Single payout not working on live !!!

### ISSUE THREAD

**Issue by Govind13100** [paypal/PayPal-PHP-SDK#909]
I have enable the payout service on live and tried to do one payment but it's say's insufficient fund error. I have 80 dollar in my account even though error is for insufficient fund. 
here is a screenshot of my error 

Can any one tell or suggest something on this????

Thanks in advance 

Edit: Removed Imaged
Debug ID 5bd2ad60a3718

**Comment by pp-randy** [comment]
You need to have a balance in the currency you are trying to send. Payouts does not do the conversion for you. 

Please see https://www.paypal.com/us/selfhelp/article/how-do-i-transfer-my-balance-to-another-currency-faq1025

**Comment by Govind13100** [comment]
@pp-randy Thanks , that worked!!!!
