### ISSUE TITLE
Payment Wall problem

### ISSUE THREAD

**Issue by engharb** [paypal/PayPal-PHP-SDK#910]
### Issue description
Hello,
I have integrated the payment wall, the problem when I open two tabs for two different payments/order the changes done in one of the payment wall (iframe) affect the payment type in the other tabs.

I found the problem is that the ppp stores (paypalplus_session_v2, paypalplus_store) once in the cookie and when any changes happened in one of the browser tab will be stored globally and affect the other payments.

Do you have suggestion how to solve that problem?

best regards,

**Comment by xiaoleih41** [comment]
PayPal doesn't need you to cache session cookies. PayPal process payment through payment token. It might be PaymentWall specific issue. Have you reached out to them on this?

**Comment by engharb** [comment]
Thanks a lot for your responding could you please give me info to whom should I contact. I did not find a support portal to drop my problem.

best regards,

**Comment by xiaoleih41** [comment]
If you have integrated the product from www.paymentwall.com. The site lists its contact info as devsupport@paymentwall.com
