### ISSUE TITLE
[Error] Unable to refresh access token

### ISSUE THREAD

**Issue by vladyslavstartsev** [paypal/PayPal-PHP-SDK#913]
### General information

* SDK/Library version: 1.12.0 
* Environment: sandbox
* `PayPal-Debug-ID` values: Where can I find it? the only thing that I found is `"correlation_id":"495f824cff420"`
* Language, language version, and OS: Ubuntu 16.04 (on Vagrant), PHP 7.1

### Issue description

I want to get user info so I followed the samples
https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/lipp/GetUserInfo.php
also https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/lipp/GenerateAccessTokenFromRefreshToken.php and https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/lipp/ObtainUserConsent.php
but when I user click on a button (on the page), he calls the method that has this code
```
$apiContext = new ApiContext(
            new OAuthTokenCredential(
                'ATEySpLmk9EZ7m0ZVIYkdXt7Yt5wan_29il94F7KxtlxbhNbAh2wz3qKLJEZeujEPlatjjSqqImESHv9',     // ClientID
                '<secret>'      // ClientSecret
            )
        );
        $apiContext->setConfig(['mode' => 'SANDBOX']);


        $baseUrl = secure_url(route('paypal.loginSuccess'));

        $redirectUrl = OpenIdSession::getAuthorizationUrl(
            $baseUrl,
            [],
            null,
            null,
            null,
            $apiContext
        );

        return redirect($redirectUrl);
```
Then he logs in with his PayPal account and the PayPal redirects him to the  `$baseUrl` which has this code (I know that code looks ugly, but that's not the point)

```
public function successfulLogin(Request $request)
    {

        $apiContext = new ApiContext(
            new OAuthTokenCredential(
                'ATEySpLmk9EZ7m0ZVIYkdXt7Yt5wan_29il94F7KxtlxbhNbAh2wz3qKLJEZeujEPlatjjSqqImESHv9',     // ClientID
                '<secret>'      // ClientSecret
            )
        );
        $apiContext->setConfig(['mode' => 'SANDBOX']);

        $permanentCode = $request->input('code');

        $tokenInfo = new OpenIdTokeninfo();
        $tokenInfo = $tokenInfo->createFromRefreshToken(['refresh_token' => $permanentCode], $apiContext);

        $params = ['access_token' => $tokenInfo->getAccessToken()];
        $userInfo = OpenIdUserinfo::getUserinfo($params, $apiContext);
        dd($userInfo);
    }
```

In the `successfulLogin` I can get array of this 
```
array:2 [▼
  "code" => "C21AAFrc5OukhN1tJQjReBo2YR5BVNXdCsLgZtjq3qNkhXrxCpSW9DxEuhVtWINgMS7KzXMK55sqvpHscYfDoJ0O8k8omUCRA"
  "scope" => "phone address email https://uri.paypal.com/services/expresscheckout openid https://uri.paypal.com/services/paypalattributes profile"
]
```

When I try to pass the `code` param as a `refresh_token` to `createFromRefreshToken`  method.

But if fails with this 
`
{"error_description":"Unable to refresh access token","error":"invalid_request","correlation_id":"c8e8cc07a14b0","information_link":"https://developer.paypal.com/docs/api/#errors"}
`
It looks like #852 but it haven't helped me

**Comment by ApacheEx** [comment]
You get authorization code not refresh_token, so to create an access token based on code you should use:

```php
$accessToken = OpenIdTokeninfo::createFromAuthorizationCode(
  array("code" => $permanentCode), 
  null, 
  null, 
  $apiContext
);
```

**Comment by vladyslavstartsev** [comment]
@ApacheEx yeah! You're right! I was trying to do it as you mention it yesterday. 
but I was reloading the page with `F5` and not going again to login screen, and this thing, the `access token` doesn't work on the second request, so I was getting error like 
`{"error_description":"Invalid authorization code","error":"access_denied","correlation_id":"5d9a5ab32be4f","information_link":"https://developer.paypal.com/docs/api/#errors"}`
I should rebroduce all the steps, not only the last one.
Writing this since I think it may help others to fix similar problem.

**Comment by pp-randy** [comment]
@vladyslavstartsev Did you need any additional help?

**Comment by vladyslavstartsev** [comment]
No, already done with it.
