### ISSUE TITLE
Refund request refused after updating currency.

### ISSUE THREAD

**Issue by 34tm4n** [paypal/PayPal-PHP-SDK#914]
Hello
I am trying to refund a transaction with EUR currency in sandbox.
It was working fine when I was using USD as currency but i switchted to EUR i am getting this error on refund request:

{ Error: Response Status : 400
at IncomingMessage.<anonymous(/node_modules/paypal-restsdk/lib/client.js:136:23)
at emitNone (events.js:91:20)
at IncomingMessage.emit (events.js:185:7)
at endReadableNT (_stream_readable.js:974:12)
at _combinedTickCallback (internal/process/next_tick.js:80:11)
at process._tickDomainCallback (internal/process/next_tick.js:128:9)
response: 
{ name: 'TRANSACTION_REFUSED',
message: 'Request was refused.You can not refund this type of transaction',
information_link: 'https://developer.paypal.com/docs/api/payments/#errors',
debug_id: 'c677afb9c1a96',
httpStatusCode: 400 },
httpStatusCode: 400 }

I am getting this error from Paypal Node SDK and also from rest APIs.

Thanks

**Comment by xiaoleih41** [comment]
You cannot refund unclaimed transaction. You can accept or deny the payments but not refund them.

**Comment by 34tm4n** [comment]
What do you mean by unclaimed transactions?
This was working fine by $ currency. What suddenly happened with the Euro currency ?

**Comment by xiaoleih41** [comment]
Please take a look at your transaction history. It appears to me that you don't have EUR as an open currency so all EUR transaction status are unclaimed. They are waiting for you to accept or deny them. So far, there's no EUR payment deposited in your PayPal account.

**Comment by 34tm4n** [comment]
I am using Sandbox account. Where I can find the menu to view transaction history of sandbox account.

**Comment by xiaoleih41** [comment]
Please use your sandbox account info to login https://www.sandbox.paypal.com.

**Comment by 34tm4n** [comment]
Thanks for quick response, I add the Euro currency and it solved my problem. 
Do I need to update any thing when I move from sandbox to live version of the application?

**Comment by xiaoleih41** [comment]
Please make sure that you have all the currencies you want to accept open in your live business account too.

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been provided.
