### ISSUE TITLE
500 Internal Error on payment execution in Sandbox

### ISSUE THREAD

**Issue by jeffberube** [paypal/PayPal-PHP-SDK#915]
### General information

* SDK/Library version: 1.12
* Environment: Sandbox
* `PayPal-Debug-ID` values: 47b56ff259e1d
* Language, language version, and OS: PHP 5.6 on 

### Issue description

Have been getting intermittent bouts of '500 internal errors' in the last few days. Happens when trying to execute a payment. Sample error message:

`ERROR: Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment/PAY-2XN98534RF542114CLGO7XQY/execute.`

**Comment by emorell96** [comment]
Same issue here. I've having intermittent issues with the execution of the payment.

**Comment by papipons** [comment]
Same issue here on creating a FuturePayment

{
"name":"INTERNAL_SERVICE_ERROR",
"details":[],
"message":"An internal service error has occurred",
"information_link":"https://developer.paypal.com/docs/api/payments/#errors",
"debug_id":"6d04d81da163"
}`

**Comment by xiaoleih41** [comment]
I was told the issue has been solved. Please check again.

**Comment by chris-trotter** [comment]
@xiaoleih41 Still getting 500 errors on the sandbox.

**Comment by papipons** [comment]
Same here, still getting 500 errors on the sandbox

**Comment by pp-randy** [comment]
If you are getting a 500 for payouts please track https://github.com/paypal/PayPal-REST-API-issues/issues/130.

**Comment by papipons** [comment]
Okay, thank you.

**Comment by pp-randy** [comment]
Anyone still getting this for Payment execution?  If so, please provide a new paypal-debug-id, so we can follow up.

**Comment by chris-trotter** [comment]
@pp-randy 

```
{
    "name": "INTERNAL_ERROR",
    "message": "An internal service error has occurred.",
    "debug_id": "99b9aacac8da6",
    "information_link": "https://developer.paypal.com/docs/api/payments.payouts-batch/#errors"
}
```

**Comment by pp-randy** [comment]
@chris-trotter that is a payouts error, please follow here https://github.com/paypal/PayPal-REST-API-issues/issues/130.

**Comment by pp-randy** [comment]
Closing this issue to reduce confusion with the payouts issue https://github.com/paypal/PayPal-REST-API-issues/issues/130.

**Comment by pp-randy** [comment]
If you get a 500 error for Payment execute please file new issue in https://github.com/paypal/PayPal-REST-API-issues/
