### ISSUE TITLE
Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payouts?.

### ISSUE THREAD

**Issue by NikitaMelikhov** [paypal/PayPal-PHP-SDK#917]
Suddenly I began to get an error when I applied to payouts api, although I already did several such requests and they worked fine, and there were no changes in the code.

`object(PayPal\Exception\PayPalConnectionException)#24 (9) { ["url":"PayPal\Exception\PayPalConnectionException":private]=> string(51) "https://api.sandbox.paypal.com/v1/payments/payouts?" ["data":"PayPal\Exception\PayPalConnectionException":private]=> string(193) "{"name":"INTERNAL_ERROR","message":"An internal service error has occurred.","debug_id":"491368446dce","information_link":"https://developer.paypal.com/docs/api/payments.payouts-batch/#errors"}" ["message":protected]=> string(94) "Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payouts?." ["string":"Exception":private]=> string(0) "" ["code":protected]=> int(500)`

**Comment by chris-trotter** [comment]
This is a known unresolved issue. See #915.

**Comment by pp-randy** [comment]
This is a separate issue with payouts, I am tracking it here: https://github.com/paypal/PayPal-REST-API-issues/issues/130.
