### ISSUE TITLE
Use of deprecated VerifyWebhookSignature::setWebhookEvent in sample code

### ISSUE THREAD

**Issue by tobiasmuehl** [paypal/PayPal-PHP-SDK#918]
[This sample code](http://paypal.github.io/PayPal-PHP-SDK/sample/doc/notifications/ValidateWebhookEvent.html) should be updated, it's currently using a deprecated method

**Comment by xiaoleih41** [comment]
Thank you for pointing this out. It is noted. Please use the sample code included in the SDK instead.

**Comment by jaypatel512** [comment]
This has been fixed now. Thank you for letting us know. 👍
