### ISSUE TITLE
Wiki Docs, broken link

### ISSUE THREAD

**Issue by shakaran** [paypal/PayPal-PHP-SDK#919]
Check at https://github.com/paypal/PayPal-PHP-SDK/wiki/Samples

Where it links to:

https://github.com/paypal/rest-api-sample-app-php

The "rest-api-sample-app-php" doesn't exist

**Comment by xiaoleih41** [comment]
Thank you for pointing that out.  All the samples are moved to SDKs. Would you mind to submit a pull request?

**Comment by shakaran** [comment]
@xiaoleih41 I never did before a pull request for a wiki page. I think that I just changed the link to https://github.com/paypal/PayPal-PHP-SDK/tree/master/sample (not sure if this is the proper location since it speaks about a pizza app). Probably you can watch or moderate my change, but no idea, since it is my first time changing things in a wiki project at github

**Comment by xiaoleih41** [comment]
That's perfect.

**Comment by xiaoleih41** [comment]
Close this issue as it has been solved.
