### ISSUE TITLE
PaypalPlus: Sandbox test payments work good but once i move to live it does not work!

### ISSUE THREAD

**Issue by masudewucse** [paypal/PayPal-PHP-SDK#920]
When i use sandbox client_id and secret for paypalPlus, things are working fine. Once i change the mode to live and use live credentials i get the following error: 
<pre>
https://api.paypal.com/v1/payments/payment
Fatal error: Uncaught exception PayPal\Exception\PayPalConnectionException with message Got Http response code 400 when accessing https://api.paypal.com/v1/payments/payment. thrown in system/modules/booking/paypal/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php on line 154
#0 system/modules/booking/paypal/vendor/paypal/rest-api-sdk-php/lib/PayPal/Transport/PayPalRestCall.php(73): PayPal\Core\PayPalHttpConnection->execute('{"intent":"sale...')
#1 system/modules/booking/paypal/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PayPalResourceModel.php(102): PayPal\Transport\PayPalRestCall->execute(Array, '/v1/payments/pa...', 'POST', '{"intent":"sale...', Array)
#2 system/modules/booking/paypal/vendor/paypal/rest-api-sdk-php/lib/PayPal/Api/Payment.php(564): PayPal\Common\PayPalResourceModel::executeCall('/v1/payments/pa...', 'POST', '{"intent":"sale...', NULL, Object(PayPal\Rest\ApiContext), Object(PayPal\Transport\PayPalRestCall))
#3 system/modules/booking/paypal/Payments.php(314): PayPal\Api\Payment->create(Object(PayPal\Rest\ApiContext))
#4 system/modules/core/modules/Module.php(287): Payments->compile()
#5 system/modules/booking/paypal/Payments.php(33): Contao\Module->generate()
#6 system/modules/core/library/Contao/Controller.php(321): Payments->generate()
#7 system/modules/core/library/Contao/InsertTags.php(447): Contao\Controller::getFrontendModule('150')
#8 system/modules/core/library/Contao/Controller.php(692): Contao\InsertTags->replace('...', false)
#9 system/modules/core/classes/FrontendTemplate.php(100): Contao\Controller::replaceInsertTags('...', false)
#10 system/modules/core/pages/PageRegular.php(190): Contao\FrontendTemplate->output(true)
#11 system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#12 index.php(20): Contao\FrontendIndex->run()
#13 {main}
</pre>

Please help me on this!

**Comment by xiaoleih41** [comment]
Do you have a **debugId** for us to take a look?  As PayPal plus is a regional product. You may reach out to https://www.paypal-techsupport.com/, the regional technician team should be able to help you.

**Comment by xiaoleih41** [comment]
Close this ticket as answer has been given.
