### ISSUE TITLE
Paypal detect/prevent pending payments from being processed

### ISSUE THREAD

**Issue by updatesvc** [paypal/PayPal-PHP-SDK#923]
### General information
I  am currently using paypal and laravel (PHP frmework) to process payments on my web app to sell digital products (Order is autmatically processed immediately).I have noticed a user on the platform is buying products using paypal but the payments are always pending .He/She is using this to their advantage to buy digital products basically for free, I have to manually revoke access to the products after they buy them.
See [screen shot](http://i.imgur.com/VKVzop6.jpg)
See my code below:
`        $payment_id = Session::get('paypal_payment_id');
        /** clear the session payment ID **/
        
        Session::forget('paypal_payment_id');
        if (empty(request('PayerID')) || empty(request('token'))) {
            //payment failed
        
        }
        $payment = Payment::get($payment_id, $this->apiContext);
        /** PaymentExecution object includes information necessary **/
        /** to execute a PayPal account payment. **/
        /** The payer_id is added to the request query parameters **/
        /** when the user is redirected from paypal back to your site **/
        $execution = new PaymentExecution();
        $execution->setPayerId(request('PayerID'));
        /**Execute the payment **/
        $result = $payment->execute($execution, $this->apiContext);
        /** dd($result);exit; /** DEBUG RESULT, remove it later **/
        //dd($payment_id,$result,$result->transactions[0]->related_resources[0]->sale->state);
        if ($result->getState() == 'approved' && $result->transactions[0]->related_resources[0]->sale->state =="completed") { 
            
            /** it's all right **/
            /** Here Write your database logic like that insert record or value in database if you want **/

		    //  Proccess order

           
            Session::put('success','Payment success');
           
            
        }`
**Is there away I can prevent pending payments from being executed/received (maybe on Paypal website setting like : never accept pending payment)**?

Or **is there away to know if the payment is pending before processing order**?
I already tried the above ....sale->state=="completed"

**Comment by xiaoleih41** [comment]
If you do  [GetPayment](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/GetPayment.php) after a payment is executed. The **sales->state** should be "pending" if the transaction status is pending. 
````
            "related_resources": [
                {
                    "sale": {
                        "id": "4L988308597227045",
                        "state": "pending",
                        "amount": {
                            "total": "11.00",
                            "currency": "EUR",
                            "details": {
                                "subtotal": "7.50",
                                "tax": "1.30",
                                "shipping": "2.20"
                            }
                        },
````

**Comment by updatesvc** [comment]
Thanks.

**Comment by s1728k** [comment]
hi with same code how i can get the amount value after line if ($result->getState() == 'approved')
