### ISSUE TITLE
Call to undefined function App\Http\Controllers\getBaseUrl()

### ISSUE THREAD

**Issue by maulikkanani1** [paypal/PayPal-PHP-SDK#924]
### Issue description

when i call CreatePaymentUsingPayPal.php file it's give me an "Call to undefined function App\Http\Controllers\getBaseUrl()" this erro

**Comment by xiaoleih41** [comment]
Please refer to issue https://github.com/paypal/PayPal-PHP-SDK/issues/900 for the possible cause and make sure you have included the [bootstrap.php](https://github.com/paypal/PayPal-PHP-SDK/blob/b2c244199bfffa5f99178acdd1b463a14c398d63/sample/bootstrap.php#L20).

**Comment by xiaoleih41** [comment]
Close this issue due to inactivity. Please resubmit when you have additional questions.
