### ISSUE TITLE
Missing 'purchase_order' in Transaction

### ISSUE THREAD

**Issue by Lozik** [paypal/PayPal-PHP-SDK#926]
### General information

* SDK/Library version: 1.12.0

### Issue description

Is it possible that the actual SDK version misses the 'purchase_order' field of the actual REST API version? In the API documentation, this field is present but I do not find it anywhere in this SDK's source code: https://developer.paypal.com/docs/api/payments/

I do not know if this is because the SDK is not up to date with the REST API or if it is just something that has been forgotten.

**Comment by xiaoleih41** [comment]
We are looking into this issue.  Thank you for pointing it out.
