### ISSUE TITLE
Guest Checkout Not Showing on Sandbox/Live

### ISSUE THREAD

**Issue by RHaylor** [paypal/PayPal-PHP-SDK#927]
### General information

* SDK/Library version: 1.110
* Environment: Sandbox
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: PHP, Windows Xampp, WordPress

Hi There, 

I hope someone might be able to help me. 

I have put together, a checkout page for a subscription service users get an approval URL which then sends them to the PayPal checkout page.  However, when I go onto the PayPal checkout page there is no option for the users to checkout as a guest, they either have to sign up for a PayPal account or login as a PayPal user. 

I'm a bit of a newbie at this, so there might be something I've done wrong.  The PayPal Option button is is set to On in PayPal and I have tested this on both sandbox and live and in each scenario, it still doesn't give the option for a user to checkout as  a guest. 

Any help would be great. 

Thanks 

Robert

**Comment by xiaoleih41** [comment]
**Subscription** allows a merchant to pull funds from a PayPal account  for a period of time while **PayPal option** only allows one time payment. Therefore, your buyer will have to have a registered PayPal account in order to be subscribed to a subscription.
