### ISSUE TITLE
Paypal here - Cannot login to get access token with live account

### ISSUE THREAD

**Issue by thekingbk90** [paypal/PayPal-PHP-SDK#928]
I have a problem when login to get access token. Anyone can help.

I used sandbox Url and live Url to get access token for paypal here.
After login, the sandbox account worked but live account didn't work.
My paypal account is business in England and I have already configed paypal here available and redirect URLs

<script>
sandboxUrl = 'https://www.sandbox.paypal.com/signin/authorize?scope=openid https://uri.paypal.com/services/paypalattributes/business https://uri.paypal.com/services/paypalhere address email&response_type=code&redirect_uri='+redirectUri+'&client_id='+clientId;

liveUrl ='https://www.paypal.com/signin/authorize?scope=openid https://uri.paypal.com/services/paypalattributes/business https://uri.paypal.com/services/paypalhere address email&response_type=code&redirect_uri='+redirectUri+'&client_id='+clientId;
</script>

Error log:
400{"error_description":"client id or secret is null","error":"invalid_client","correlation_id":"6ef69e2276769","information_link":"https://developer.paypal.com/docs/api/#errors"}Please try again

I got client ID from live Paypal app.
https://prnt.sc/gnadbj
https://prnt.sc/gnadth
https://prnt.sc/gnadnl

**Comment by xiaoleih41** [comment]
It looks like your **clientId** is not valid. I found this `correlation_id` in sandbox environment. So you may check your environment and credentials to make sure they are correct.

**Comment by thekingbk90** [comment]
Thank for your answer but I got client ID from live app.
https://prnt.sc/gnadbj

https://prnt.sc/gnadth

https://prnt.sc/gnadnl

How can I check "correlation_id" ?

**Comment by xiaoleih41** [comment]
I meant to say you might have used your live client ID in sandbox environment. Please make sure you have switched your environment to live as well.

**Comment by thekingbk90** [comment]
But the link I used is live environment.
Paypal.com instead of sanbox.paypal.com

**Comment by xiaoleih41** [comment]
The one you listed above is not... I found the **correlation Id* you gave me in the **sandbox environment** so the **environment** was not set correctly. Also, I don't think you have passed enough **scope** here. Please follow this [guide](https://developer.paypal.com/docs/integration/paypal-here/merchant-onboarding/initiating-the-onboarding-flow/) to configure the paypal here. If you have any further questions, please ask questions under https://github.com/paypal/paypal-here-sdk-android-distribution repository.

**Comment by thekingbk90** [comment]
I'm sorry. I posted sandboxUrl and liveUrl are same. I've changed it.
I used live environment exactly. 
Thank for your interest in.
I will ask in android repository.

**Comment by xiaoleih41** [comment]
You are fine. I hope the guide I sent you earlier will help you with correct scopes as well. I am going to close this issue as your issue will be addressed in the **PayPal here** repository going forward.
