### ISSUE TITLE
How to get billing agreement id after creating a agreement object?

### ISSUE THREAD

**Issue by Gwill** [paypal/PayPal-PHP-SDK#930]
### General information

* SDK/Library version: 1.12.0
* Environment: Sandbox
* Language, language version, and OS: PHP, Ubuntu 16.04

### Issue description

How to get billing agreement id after creating a agreement object?

```
$agreement->getId();  // null
```

**Comment by xiaoleih41** [comment]
**A billing agreement Id** won't get created until it is executed. It is tracked at issue https://github.com/paypal/PayPal-REST-API-issues/issues/19. You can use Payment token as the identifier before the billing agreement is executed.

**Comment by Gwill** [comment]
Thanks!
