### ISSUE TITLE
PayPal Rest API Webhook to notify about Other non-rest api events

### ISSUE THREAD

**Issue by wounded1987** [paypal/PayPal-PHP-SDK#932]
I'm trying to use the PayPal rest webhook notifications for transactions generated using third party marketplace (Etsy.com), I am assuming they use classic way of making this transactions since I'm able to fetch them using TransactionSearch NVP API.

I setup Rest API application and trying to see if any events are occurring in the "Live" dashboard with a webhook that I have created and I see no events there. (I setup a dummy listener just to see if these events were ever sent)

So, is my assumption is correct, I wont be able to use Rest API nor use the Rest API **webhooks** to get any notifications for transactions that occurred via third party marketplace? If I am able to fetch these transactions using NVP, does it mean they were generated using NVP API? (they use notify_url)

Thanks for any help you can give.

**Comment by xiaoleih41** [comment]
Your assumption is correct. REST webhooks will only work transactions made with REST API. For NVP/SOAP transactions,  you will need to use classic [IPN](https://developer.paypal.com/docs/classic/products/instant-payment-notification/) instead.

**Comment by wounded1987** [comment]
Thanks, if they use IPN & notify_url is present + I can see these transactions and fetch them with NVP/SOAP, does it mean they were made with the NVP/SOAP API ?

**Comment by xiaoleih41** [comment]
Yes. They are NVP/SOAP APIs.

**Comment by oscarmolinadev** [comment]
@xiaoleih41 Hi, if I created Agreement with Rest API and I change something in paypal dashboard I'll receive a webhook?

Thanks.

**Comment by xiaoleih41** [comment]
I don't quite understand the question. Changing PayPal dashboard should not trigger any webhooks. If you have created a billing agreement before you enable the webhook. You enable the webhook then the billing agreement status changed, you may receive a webook event.

**Comment by oscarmolinadev** [comment]
@xiaoleih41 For example I create an Agreement (12 cycles) with REST API, 2 days later I go to Paypal Dashboard and change the Agreement to infinite cycles, this change trigger a webhook?

**Comment by xiaoleih41** [comment]
@oscarmolinadev This doesn't apply to REST API recurring payment. You cannot make changes on billing agreement from the dashboard.

**Comment by oscarmolinadev** [comment]
@xiaoleih41 If I cancel/suspend or the user cancel the recurring payment triggers a webhook, why not when change inside dashboard?

![image](https://user-images.githubusercontent.com/6513086/30845749-2971ccf4-a295-11e7-94da-a42ea211b3a3.png)

**Comment by xiaoleih41** [comment]
This is not REST API recurring payment therefore it won't trigger the webhooks built for REST APIs.

**Comment by oscarmolinadev** [comment]
It's created with REST API and then managed through paypal dashboard.

**Comment by xiaoleih41** [comment]
From the screenshot, I can see it is using profile ID which is a type of recurring payment created by classic NVP/SOAP API. Please read  how to handle classic recurring payment profile [here](https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECRecurringPayments/) and the classic recurring payment notification [here](https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECRecurringPayments/#recurring-payments-notifications).  As the original issue of this thread has been solved. I am going to close this issue. If you have any specific case, please provide detail correlation Id and we can troubleshoot from there.
