### ISSUE TITLE
PHP PayPal SDK MALFORMED_REQUEST exception on update redirectUrls

### ISSUE THREAD

**Issue by theburhan** [paypal/PayPal-PHP-SDK#933]
I have a situtation for a PayPal plus integration when, I have to call create Payment to fetch approvalLink and then updatePayment to apply patch. The problem is, when I create a Payment, I do have to pass returnUrl and cancelUrl, but at that time, I do not have an orderId, because it is not yet completed, and I have to pass that orderId in the returnUrl and cancelUrl, therefore, on the updatePayment, I try to apply the patch like.
```
$patchRedirectUrls = new Patch();
$patchRedirectUrls->setOp('replace')
     ->setPath('/redirect_urls')
      ->setValue(json_decode('{"returnURL":"http://test.shop?orderId=123","cancelURL":"http://test.shop?orderId=123"}'));
$patchRequest = new PatchRequest();
        $patchRequest->setPatches([$patchRedirectUrls]);
        $ret = $createdPayment->update($patchRequest, $this->apiContext);
```
error: {"name":"MALFORMED_REQUEST","message":"MALFORMED_REQUEST","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"8a164a227092a"}"

**Comment by xiaoleih41** [comment]
You cannot update **return URL** according to the info provided [here](https://developer.paypal.com/docs/api/payments/#payment_update). You can only update amount, shipping address and custom data.

**Comment by theburhan** [comment]
Thanks for the clarification. I have changed the work flow to create orderId before the order is placed, so that returnUrl may have orderId.
