### ISSUE TITLE
Paypal checkout.js (REST API) and Agreements

### ISSUE THREAD

**Issue by oscarmolinadev** [paypal/PayPal-PHP-SDK#934]
### General information

* SDK/Library version: 1.12.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: 639f36b4621e1

### Issue description
I use checkout.js for create subscriptions with REST API but I have some problems.

1 - For checkout.js I need to send the token agreement and currently I have to parse the URL of the approval_url for get the token, other APIs I think they have a `getToken()` func/param

2 - When the agreement is created the response not return the ID always is `null` but in docs exists:

![image](https://user-images.githubusercontent.com/6513086/30737003-445d6b12-9f85-11e7-99ab-9a64e9e1fc83.png)

3 - If agreement not return ID it would have to be possible to search by token.

4 - If agreement is accepted but not executed correctly I can't restart the process with checkout.js, throws error (return to merchant) I supose that I need update the agreement to `pending` for re-acept the agreement and execute payment again or I need delete the agreement? (I can't delete if I haven't the ID).
**NOTE: This only happens on onAuthorize, the agreement not executed but the result response is OK 200, if the response is 500 then i can re-accept&pay the agreement.**

Thanks.

**Comment by xiaoleih41** [comment]
Billing agreement Id will not be created until you execute the payment. The sample code is wrong. The issue was reported. Please check into this issue https://github.com/paypal/paypal-checkout/issues/234 for more information. Before the payment is executed successful, the **agreement status** will not be `completed`.

**Comment by xiaoleih41** [comment]
Closing this issue as the answer has been provided.
