### ISSUE TITLE
Add and Send Payment to our Vendors by Using PayPal Merchant Account with PayPal-PHP-SDK

### ISSUE THREAD

**Issue by RamizDevBatch** [paypal/PayPal-PHP-SDK#935]
Hy 
I want to add and pay our vendors from PayPal, can you guide me how I can do this by using [PayPal SDK ](https://github.com/paypal/PayPal-PHP-SDK)on Github??
PayPal online support and Call also not helping me to fix it, also Support Email communicatino is very slow, can anyone tell me how i can sovle do this or how i can contact with paypal quickly ???
Thanks in Advance Smiley Happy :)

**Comment by xiaoleih41** [comment]
PayPal REST API doesn't support multi-payees situation.  Therefore you cannot use this SDK to make payments to more than one receiver.  You may look into  [Braintree marketplace](https://www.braintreepayments.com/products/braintree-marketplace) or  [PayPal Marketplace](https://developer.paypal.com/docs/marketplaces/pp4mp/) for possible solution instead.

**Comment by RamizDevBatch** [comment]
hy
thanks for you response , but your response is very slow, for the now i m
using payout APis for sending money , but i need to confirm Email address
is valid or not  like given email address contain Paypal account or not ??
how i can check this ?

**Comment by RamizDevBatch** [comment]
i m checking this link for verification
https://developer.paypal.com/docs/classic/api/adaptive-accounts/GetVerifiedStatus_API_Operation/

but i m fail to integrate it due to PayPal message
"To determine whether you can use this limited-release API, contact your
PayPal integration team."
what is its solution ?? please reply me as soon as possible

and one more thing i want to integrate IPN in PHP, is there any help in PHP
how i can do this ?

**Comment by xiaoleih41** [comment]
We are deprecating `GetVerifiedStatus` API. There will be no more new integration on this API. You may contact the customer service number listed on your account and request to talk to a sales person from PayPal. The sales person should be able to recommend the most suitable API that works for your specific situation. 
To integration ** IPN**, please follow [this guideline](https://developer.paypal.com/docs/classic/ipn/ht_ipn/). You can also use this [SDK](https://github.com/paypal/ipn-code-samples/tree/master/php)

**Comment by RamizDevBatch** [comment]
How to use IPN for payment verification

**Comment by xiaoleih41** [comment]
**IPN** is a type of payment notification. It sends you a string of data including **payment status** information. you can deserialize the data and get the information your want to verify. The detail are explained in this [guide](https://developer.paypal.com/docs/classic/ipn/ht_ipn/).

**Comment by RamizDevBatch** [comment]
ye i have follow above link which you sent me in email. but i m getting
just 200 error
my link is
http://demoapps.devbatch.com/sproglets_b3/api/v2/paypal/ipnverification and
its working fine on simulator, and here is its code



$raw_post_data = file_get_contents('php://input'); $raw_post_array =
explode('&', $raw_post_data); $myPost = array(); foreach($raw_post_array as
$keyval) { $keyval = explode('=', $keyval); if (count($keyval) == 2)
$myPost[$keyval[0]] = urldecode($keyval[1]); } $req =
'cmd=_notify-validate'; if (function_exists('get_magic_quotes_gpc')) {
$get_magic_quotes_exists = true; } foreach($myPost as $key => $value) { if
($get_magic_quotes_exists == true && get_magic_quotes_gpc() == 1) { $value
= urlencode(stripslashes($value)); } else { $value = urlencode($value); }
$req.= "&$key=$value"; } // STEP 2: Post IPN data back to paypal to
validate $ch = curl_init('https://sandbox.paypal/cgi-bin/webscr'); //
change to [...]sandbox.paypal[...] when using sandbox to test
curl_setopt($ch, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);
curl_setopt($ch, CURLOPT_POST, 1); curl_setopt($ch, CURLOPT_RETURNTRANSFER,
1); curl_setopt($ch, CURLOPT_POSTFIELDS, $req); curl_setopt($ch,
CURLOPT_SSL_VERIFYPEER, 1); curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 2);
curl_setopt($ch, CURLOPT_FORBID_REUSE, 1); curl_setopt($ch,
CURLOPT_HTTPHEADER, array( 'Connection: Close' )); // In wamp like
environments that do not come bundled with root authority certificates, //
please download 'cacert.pem' from "http://curl.haxx.se/docs/caextract.html"
and set the directory path // of the certificate as shown below.
curl_setopt($ch, CURLOPT_CAINFO, dirname(__FILE__) . '/cacert.pem'); if
(!($res = curl_exec($ch))) { error_log("Got " . curl_error($ch) . " when
processing IPN data"); curl_close($ch); exit; } curl_close($ch); // STEP 3:
Inspect IPN validation result and act accordingly if (strcmp($res,
"VERIFIED") == 0) { $item_name = $_POST['item_name']; $item_number =
$_POST['item_number']; $payment_status = $_POST['payment_status']; if
($_POST['mc_gross'] != NULL) { $payment_amount = $_POST['mc_gross']; } else
{ $payment_amount = $_POST['mc_gross1']; } $payment_currency =
$_POST['mc_currency']; $txn_id = $_POST['txn_id']; $receiver_email =
$_POST['receiver_email']; $payer_email = $_POST['payer_email']; $custom =
$_POST['custom']; echo "you win"; } elseif (strcmp($res, "INVALID") == 0) {
echo "try again"; }


but its not giving me message in case of success or fail, its just giving
me 200 status and i think code is not running after these line of code

if (!($res = curl_exec($ch))) { error_log("Got " . curl_error($ch) . " when
processing IPN data"); curl_close($ch); exit; }

can you please guide me how i can solve this ??


On Mon, Sep 25, 2017 at 10:39 PM, Xiaolei Wheelock <notifications@github.com

**Comment by xiaoleih41** [comment]
200 response means successful.

**Comment by xiaoleih41** [comment]
Close this issue due to inactivity. Please resubmit when you have additional questions.
