### ISSUE TITLE
Sample code to get payments and refunds by transactionID

### ISSUE THREAD

**Issue by paulyip-c3** [paypal/PayPal-PHP-SDK#936]
### General information

* SDK/Library version: SDK-1.12.0
* Environment: Production
* `PayPal-Debug-ID` values: e36fabb821183
* Language, language version, and OS:  php / CentOS 7

### Issue description

I was able to get the "getting started" examples working. However, I think this is a fairly simple question but I'm unable to get it working.

Basically, I have a (live) transactionID: 8E5266108S778104J received on Sep 23, 2017
A few days later, I process a partial refund which is successful. The transactionID is : 2NP65086Y68773548

The question is, what would code look like for me to:

1) instantiate a payment/transaction object on the original transaction
2) get the related refund(s) to the original payment/transaction.

I looked at this example: http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/GetPayment.html

But it wasn't helpful because I see nowhere in that code example how to get information about my specific transaction (by transaction ID == 8E5266108S778104J)

Please help!

Thanks

Paul

**Comment by xiaoleih41** [comment]
@paulyip-c3  Please use [getSale](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/sale/GetSale.php) instead.

**Comment by jaypatel512** [comment]
Hey @paulyip-c3 !

Generally, you would want to do a GET on payments object. This should return you all the transactions that exists for that payments, which should include the refund/sale. You should be able to do use `getSale` sample to get particular `sale` information.
