### ISSUE TITLE
Error on delete app in my account for create app to 

### ISSUE THREAD

**Issue by fredroo** [paypal/PayPal-PHP-SDK#938]
![image](https://user-images.githubusercontent.com/6863089/30819503-e6b80b24-a1ec-11e7-850b-10fa6e85df08.png)
![image](https://user-images.githubusercontent.com/6863089/30819515-f18f3e64-a1ec-11e7-9fac-609e61a931e4.png)
![image](https://user-images.githubusercontent.com/6863089/30819609-437b4498-a1ed-11e7-8c03-20efa9d91f11.png)

this error in my paypal account in my apps (developer.paypal.com)

**Comment by xiaoleih41** [comment]
@fredroo Does this link to a Braintree app?  I was able to delete my REST App.

**Comment by fredroo** [comment]
@xiaoleih41 REST App

**Comment by fredroo** [comment]
fo Brazilian account

**Comment by fredroo** [comment]
someone help me, i need this now

**Comment by xiaoleih41** [comment]
Can you contact customer service listed on your account. It must have something to do with your specific account. As it's a live App, please contact www.paypal-techsupport.com or customer service number listed on your account to get more account specific assistance.

**Comment by fredroo** [comment]
thanks a lot my friend
