### ISSUE TITLE
Tutorial not working because samples are missing, and more

### ISSUE THREAD

**Issue by tempelmann** [paypal/PayPal-PHP-SDK#942]
I am trying to follow the instructions to get this SDK working.
There are many issues that makes this quite painful:

All following the installer instructions (https://github.com/paypal/PayPal-PHP-SDK/wiki/Installation)

* Downloading the composer on a Mac (10.12.6), it's named composer.phar, not composer, making the instructions using it not work out of the box.
* It should be explained that the downloaded SDK and the first.php file need to go into the same directory. In my understanding of using SDKs in general, they usually get placed in a different location than the user files, hence you should tell us that this works differently here. Mind you, I'm not a PHP pro who might know all this. I am just try to find _some_ SDK that gets me started with Webhooks, and PHP seemed the least painful, as e.g. python explains even less and assumes more general understanding.
* "Making Your First call" runs without an error but without any other output, too. I added some echo lines and found that it runs into the catch part, but then prints nothing there, either. Would be nice if you'd add some text like: "Error: " so that it's clearer something went wrong, even if the err msg is empty like in my case.
* The instructions (and the pic at https://github.com/paypal/PayPal-PHP-SDK/wiki/Installation-Direct-Download) suggest to run some of the examples, located inside the vecdor folder. However, the latest download (1.12.0) does not include this folder, and there seems to be no easy way to download them, either. Even selecting them individually from the samples pages does not work because Selecting the right code also includes the left notes along with it.
* Some later examples refer to "../bootstrap.php". While the initial instructions suggest to create such a file, they should point out that this is _necessary_ to run the examples.

**Comment by tempelmann** [comment]
The empty result apparently comes running into #943 

Also, I now realize that the sample folder comes with its own bootstrap.php - and in there, one needs to edit the $clientId and $clientSecret vars, of course. But that's not obvious, either - it should be mentioned on this page where it suggests to try out the samples: https://github.com/paypal/PayPal-PHP-SDK/wiki/Samples

Yes, I see that it says: "Update the bootstrap.php file with your new client id and secret.", but it should say that this time, it's the one in the samples folder, while on the previous pages (for first.php etc.), there was a separate bootstrap.php file that was talked about, in the root folder. And yes, the link behind the instruction points to the sample folder but that's all too subtle for a smooth learning experience.

**Comment by xiaoleih41** [comment]
Can you submit a pull request for us to review?

**Comment by tempelmann** [comment]
Huh? What should the commit contain? I can inly make a pull req if I can prpose changes. But this is all about documentation that I cannot provide

**Comment by xiaoleih41** [comment]
It has been edited based on your feedback. Thank you.
