### ISSUE TITLE
Error on Create Single Synchronous Payout: VALIDATION_ERROR

### ISSUE THREAD

**Issue by reyadrian** [paypal/PayPal-PHP-SDK#944]
### General information 

* SDK/Library version: 1.12.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: c5e39dca9d8e5
* Language, language version, and OS: PHP Version 5.6.20 on Debian 8 (jessie)

### Issue description

On Create Single Synchronous Payout:

It will always return a validation error even though the JSON format was correct (I just copied the sample code from here [http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payouts/CreateSinglePayout.html](http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payouts/CreateSinglePayout.html:)

Response:
`{
	"name": "VALIDATION_ERROR",
	"message": "Invalid request - see details.",
	"debug_id": "c5e39dca9d8e5",
	"information_link": "https://developer.paypal.com/docs/api/payments.payouts-batch/#errors",
	"details": [{
		"field": "items",
		"issue": "SIZE_LIMIT_EXCEEDED_FOR_SYNC_PAYOUT"
	}]
}`

**Comment by reyadrian** [comment]
does not allowed synchronous payout.

**Comment by xiaoleih41** [comment]
@reyadrian  Synchronous payout has been deprecated.
