### ISSUE TITLE
Lastschrift TRANSACTION_REFUSED

### ISSUE THREAD

**Issue by theburhan** [paypal/PayPal-PHP-SDK#946]
I am using PayPal Plus for German customers, the payment method I select is lastschrift. The payment object looks like below, because of data privacy I am not using actual URL's. The same solution works for Credit Card and Classic PayPal as payment method, but for lastschrift (debit card) it fails on Sandbox account. Below, you sill see the response I get from PayPal Api Gateway, Please advise what is missing in the Payment object?

Payment Object
```
object(PayPal\Api\Payment)#369 (1) {
  ["_propMap":"PayPal\Common\PayPalModel":private]=>
  array(8) {
    ["intent"]=>
    string(4) "sale"
    ["payer"]=>
    object(PayPal\Api\Payer)#335 (1) {
      ["_propMap":"PayPal\Common\PayPalModel":private]=>
      array(1) {
        ["payment_method"]=>
        string(6) "paypal"
      }
    }
    ["redirect_urls"]=>
    object(PayPal\Api\RedirectUrls)#351 (1) {
      ["_propMap":"PayPal\Common\PayPalModel":private]=>
      array(2) {
        ["cancel_url"]=>
        string(199) "http://mysite.com?success=false&payment=paypal&hash=5c70ff48a6b5ccfca7e93f78e9534971895e0fc7f1a3a8f7ebcab00b96b08447a8da0d7179032fe7c0561b0608535cfc1abfded00e164dcfa0f47b312623"
        ["return_url"]=>
        string(198) "http://mysite.com?success=true&payment=paypal&hash=5c70ffca7ea0e893f78e9534971895e0fc7f1a3a8f7ebcab00b96b08447a8da0d7179032fe7c0561b0608535cfc1abfded00e164dcfa0f47b312623"
      }
    }
    ["transactions"]=>
    array(1) {
      [0]=>
      object(PayPal\Api\Transaction)#233 (1) {
        ["_propMap":"PayPal\Common\PayPalModel":private]=>
        array(5) {
          ["amount"]=>
          object(PayPal\Api\Amount)#364 (1) {
            ["_propMap":"PayPal\Common\PayPalModel":private]=>
            array(2) {
              ["total"]=>
              string(5) "20.75"
              ["currency"]=>
              string(3) "EUR"
            }
          }
          ["custom"]=>
          string(36) "98012a-0242ac120019"
          ["invoice_number"]=>
          string(30) "59d4e1b9e5c162.44570022"
          ["item_list"]=>
          object(PayPal\Api\ItemList)#359 (1) {
            ["_propMap":"PayPal\Common\PayPalModel":private]=>
            array(0) {
            }
          }
          ["related_resources"]=>
          array(0) {
          }
        }
      }
    }
    ["id"]=>
    string(28) "PAY-0AP77553K0252044HLHKODQA"
    ["state"]=>
    string(7) "created"
    ["create_time"]=>
    string(20) "2017-10-04T13:27:28Z"
    ["links"]=>
    array(3) {
      [0]=>
      object(PayPal\Api\Links)#356 (1) {
        ["_propMap":"PayPal\Common\PayPalModel":private]=>
        array(3) {
          ["href"]=>
          string(79) "https://api.sandbox.paypal.com/v1/payments/payment/PAY-0AP77553K0252044HLOKODQL"
          ["rel"]=>
          string(4) "self"
          ["method"]=>
          string(3) "GET"
        }
      }
      [1]=>
      object(PayPal\Api\Links)#323 (1) {
        ["_propMap":"PayPal\Common\PayPalModel":private]=>
        array(3) {
          ["href"]=>
          string(94) "https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-9VN88052ZT8571459"
          ["rel"]=>
          string(12) "approval_url"
          ["method"]=>
          string(8) "REDIRECT"
        }
      }
      [2]=>
      object(PayPal\Api\Links)#357 (1) {
        ["_propMap":"PayPal\Common\PayPalModel":private]=>
        array(3) {
          ["href"]=>
          string(87) "https://api.sandbox.paypal.com/v1/payments/payment/PAY-0AP77553K0252044HAAKODQA/execute"
          ["rel"]=>
          string(7) "execute"
          ["method"]=>
          string(4) "POST"
        }
      }
    }
  }
}

```
Response
```
{
   "ack":"contingency",
   "contingency":"TRANSACTION_REFUSED",
   "errorData":{
      "cause":"",
      "step_up_context":{

      }
   },
   "meta":{
      "calc":"5f097e8a2f042",
      "rlog":"JtlEGs2BsDND7FkH8BNleVzKhuZBREylOJqODwc%2FLag9mQarEL5IiPSMixZ6z5gHum0eBi5ndtluDvUvxl0vhNw5RZeLh6Ov_15ee770e538"
   },
   "server":"rr7WLyuONMG99QBtkByC4O92m24iA1L-5-z9fWrJLvJ8jdhiPudpNbiLWl5NPx4OKCvDR6iPArRHAJOuFsOP7AzR7GmiqFbugLlEjKP_GGs13F9NpBvh5gSrdzEgYjEIdXN09u5XAlNgea6-Jte9GGasJuG1Yx0c9jMO8McisVNFygfm4xW_46zs4yTtPpgoRfovhbgr137N30U3wyK_vyfGkI2-8bCy8L4xBtbI_Y2jYe1VNCAc9m0QYC44Gv5jp3wzS0uMCtMn2pjHBKmYZyxzRnvc4vRq"
}
```

**Comment by xiaoleih41** [comment]
Please log into your merchant account, on the **profile** tab, click the **account type: Upgrade to Pro** like. Click the Enable which appears in the window to see if this will fix your issue.

**Comment by theburhan** [comment]
There is no option to change account type to Pro. In my sandbox account, i see only account type 'Business', but Upgrade to Pro is missing.

**Comment by theburhan** [comment]
Further insights, I have a normal PayPal account (not a business account) and therefore PayPal Plus is not activated. I use sandbox account where I have buyer (premier) and facilitator (business) account. Using my sandbox credentials (client/secret id), 

- I call "create" on Payment object to get an approvalLink as mentioned in the question above. 

- Using that approvalLink PayPal plus wall is rendered that shows PayPal, Credit Card and Lastschrif as possible payment methods. 

- Then, i call "update" on Payment object to apply any patches. which is essentially item-list and shipment address. 

- finally I use the approvalLink which redirects me to PayPal Gateway, where I enter sandbox premier account IBAN (I also tried with sandbox business account IBAN) and other information and click on continue button which results in the error mentioned in the question.

- Payment object paymentMethod is set to "paypal" and intent is set to "sale".

Can it be that my account is not PayPal Plus activated? or I should fill in more data to Payment object that may allow debit card (lastschrift) to go through?

**Comment by xiaoleih41** [comment]
Did you try to use credit card to make the payment? I am not sure how you test bank transfer in sandbox environment. Please try using credit card for the payment to see if it works.

**Comment by theburhan** [comment]
Yes, credit card payment works in sandbox environment. I don't know how to test bank transfer now, as the error message is not giving a detailed information, so its hard to debug.

**Comment by xiaoleih41** [comment]
This error normally means the bank refused this transaction due to whatever reason.  Are you using the bank account associated with the sandbox accounts?

**Comment by theburhan** [comment]
Yes, I use IBAN associated with Sandbox account. I assume that sandbox buyer account's (premier account) IBAN should be entered and then funds will be transferred to sandbox business account (facilitator account). So, I have confirmed that facilitator's account has Bank Information added in sandbox.paypal.com and that IBAN is the same as in Sandbox accounts. What else might go wrong? Could you please create an example for PayPal Plus customer with a possibility of lastschrift transaction. Currency, country and locale are all set to "DE".

**Comment by theburhan** [comment]
I have a response from PayPal integration developer that ELV (Elektronisches Lastschriftverfahren) is not possible on sandbox account, but it will have the same response as of PayPal and Credit Card.
