### ISSUE TITLE
Merchant OnBoarding

### ISSUE THREAD

**Issue by theburhan** [paypal/PayPal-PHP-SDK#948]
Is there an equivalent PHP PayPal-Rest-API method calls to this link? I could not find any example in the documentation. 

https://developer.paypal.com/docs/api/merchant-onboarding/#partner-referrals_create

Thanks,
Muhammad

**Comment by xiaoleih41** [comment]
It's a limited release product. We don't have SDK for this. Please contact your account manager to get approved and integration information after that.
