### ISSUE TITLE
.Net REST API, Plans and Agreements, Third Party Payment

### ISSUE THREAD

**Issue by jfranken01** [paypal/PayPal-PHP-SDK#950]
Visual Studio Community 2015 with PayPal NuGet package installed:

I am successfully using .NET REST API for third party payments through single payment definitions by defining an email address as part of the Payee object (as per documentation on the internet).

My application also has a need for regularly billed services (on behalf of subscribed organizations who has customers interfacing with my application).
I have create the Plan, and Agreement code, but can't seem to find an equivalent third party piece that will allow payment to flow between end users and my subscribed companies (third parties).

My Application => Has Subscriber Companies => Has Customers using my Application and paying for services to their company (third party).

Any help is appreciated.

**Comment by xiaoleih41** [comment]
There's no third party permission for billing agreement on REST API at this time. There may be some advanced feature available for certain strategic contracted merchants only. You may contact sales or your account manager for more information on if there's a feature available for you to facilitate 3rd party billing agreement.

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been provided.
