### ISSUE TITLE
Add tracking information via API

### ISSUE THREAD

**Issue by hamzaydia** [paypal/PayPal-PHP-SDK#951]
It's 2017 and PayPal still doesn't allow submitting tracking information via API

# The advantages are:

- [ Receive money from PayPal in days, not weeks ] According to PayPal's official guidelines on making your payment available sooner, "**if you fulfill the order, but don’t provide any shipping information, your payment should be available after 21 days**, as long as your buyer doesn’t report any issues with the transaction".

- [ Lower your fixed or rolling reserve levels ] Once PayPal places a reserve on your account, they will review it periodally. "Ship promptly and **give your customers valid tracking information through PayPal**, so they can keep tabs on their purchases and know when to expect delivery" is listed as the first PayPal Seller Best Practice.

- [ Become eligible for PayPal's Seller Protection ] By adding tracking info, you are protected by PayPal from disputes like **Unauthorized Transaction** (there is a transaction, but the account holder claims that he or she didn’t authorize payment) or **Item Not Received** (a buyer pays for an item, but claims he or she didn’t receive it).

What is the solution?

**Comment by pp-randy** [comment]
@hamzaydia are you using the [Capture API](https://developer.paypal.com/docs/api/payments/#capture)?  I will submit a feature request for the Capture API.  However, let me know if you have other thoughts as well.

**Comment by hamzaydia** [comment]
@pp-randy No, I'm using the [Sale API](https://developer.paypal.com/docs/api/payments/#sale), "Add tracking information" is possible manually in the Transaction details from the dashboard, but it's not possible by the API

**Comment by xiaoleih41** [comment]
Close this case and please track the issue at https://github.com/paypal/PayPal-REST-API-issues/issues/158 going forward.
