### ISSUE TITLE
Adaptive Payments

### ISSUE THREAD

**Issue by avtaylor** [paypal/PayPal-PHP-SDK#952]
Can this library do adaptive payments? Thank you

**Comment by bluk** [comment]
You are probably looking for the [adaptivepayments-sdk-php](https://github.com/paypal/adaptivepayments-sdk-php/) repository. Note that [adaptive payments is on a limited release](https://developer.paypal.com/docs/classic/products/adaptive-payments/?mark=adaptive%20payments) so will require approval to onboard.
