### ISSUE TITLE
Remove Credit Card samples from gh_pages branch

### ISSUE THREAD

**Issue by pp-lecurley** [paypal/PayPal-PHP-SDK#954]
### General information

* Environment: Production

### Issue description

The SDK is set up to accept and process direct credit card payments, however the documentation does not supply a warning or notice that the product has been removed for new sign ups. This feature was disbaled for new applications in the PayPal Developer Guide - https://developer.paypal.com/developer/accountStatus/. 

The document needs to be updated stating the SDK is only supported if the merchant had already been approved for this feature, the "Going Live" page shows old screenshots in the developer website and applying for the product-https://github.com/paypal/PayPal-PHP-SDK/wiki/Going-Live.

Merchants are using the current SDK and testing their configuration in Sandbox, when ready to go live, the checkout returns error- "message": "Unauthorized payment." New merchants will be unable to run live payments using this SDK and will have to find another method of accepting payments using PayPal.

**Comment by xiaoleih41** [comment]
The DCC samples were removed from SDK. We left the vault folder there for people do the guest checkout with a credit card that is stored in the PayPal vault. https://developer.paypal.com/docs/api/payments.billing-agreements#agreement_update

**Comment by pp-randy** [comment]
@xiaoleih41 we need to update this branch https://github.com/paypal/PayPal-PHP-SDK/tree/gh-pages
It is what generates the pages for https://paypal.github.io/PayPal-PHP-SDK/

**Comment by pp-randy** [comment]
We should add to the Credit Card stuff in the readme and move to the top near the TLS stuff

**Comment by jaypatel512** [comment]
Hey @pp-randy @xiaoleih41 @pp-lecurley ! 

We have updated gh-pages with removed vault and other deprecated samples. We will be updating wiki pages soon.

**Comment by xiaoleih41** [comment]
That’s nice!!!! Thank you!
Xiaolei

**Comment by xiaoleih41** [comment]
Close this issue as it's solved.
