### ISSUE TITLE
INVALID_RESOURCE_ID using payment execute.

### ISSUE THREAD

**Issue by kellyburton** [paypal/PayPal-PHP-SDK#957]
Got the following when trying to execute the payment below.  Even though the execute failed the customers payment still went though and we received payment.   I was unable to find in docs but I thought if the execute fails the payment would not come through?  

This problem is sporadic, we had several in Sep and one in Oct.  

Please let me know you need more info.

### General information

* SDK/Library version: paypal/rest-api-sdk-php": "*"
* Environment: Production
* `PayPal-Debug-ID` values: 5fceb96fb350f
* Language, language version, and OS: laravel/framework": "5.1.*

### Issue description
Got Http response code 404 when accessing https://api.paypal.com/v1/payments/payment/PAY-169335047N1253410LHKQ3DI/execute. {"name":"INVALID_RESOURCE_ID","message":"The requested resource ID was not found","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"5fceb96fb350f"}

**Comment by xiaoleih41** [comment]
This issue has been tracked at https://github.com/paypal/PayPal-REST-API-issues/issues/151. I am closing this issue.

**Comment by kellyburton** [comment]
Why would you close it instead of linking it and leaving my issue open so i can track it?

**Comment by xiaoleih41** [comment]
Close it due to duplicate issue. Please track https://github.com/paypal/PayPal-REST-API-issues/issues/151 going forward.
