### ISSUE TITLE
Accepting claim

### ISSUE THREAD

**Issue by SeriousJ55** [paypal/PayPal-PHP-SDK#959]
Is there an SDK function to accept claims?

The rest API has an "accept-claim" fonction that accepts a claim based on a dispute ID:
`/v1/customer/disputes/{dispute_id}/accept-claim`

But I don't find a corresponding function in the PHP SDK.

**Comment by xiaoleih41** [comment]
Dispute API is still under beta testing phase. Once it's open for general public, we will add samples accordingly.

**Comment by SeriousJ55** [comment]
OK, thank you.

When the dispute is not a chargeback, does simply refunding the full amount of the sale automatically settles the dispute? If not, what are additional steps needed?

**Comment by SeriousJ55** [comment]
Up

**Comment by xiaoleih41** [comment]
Yes, once you refund the full amount, the case should be closed automatically.

**Comment by SeriousJ55** [comment]
So what’s the difference between accepting a claim and refunding the sale?

**Comment by xiaoleih41** [comment]
Accepting a  claim is a part of dispute process. Refunding a sale is done in transaction history. you can refund a sale without a dispute. For more detail, please contact the number listed on your account for customer services.

**Comment by xiaoleih41** [comment]
Close this issue as the question has been answered.
