### ISSUE TITLE
Sandbox always return PAYMENT.SALE.COMPLETED

### ISSUE THREAD

**Issue by wiloke** [paypal/PayPal-PHP-SDK#961]
Hi,
I'm confusing with Sandbox account. I created a sandbox account and set Balance to 9$, then I created a product 100$. But I always get PAYMENT.SALE.COMPLETED status from Event Webhook.

One more question, Which event-hook should I use to detect an auto-billing action?
Thanks

**Comment by xiaoleih41** [comment]
It charges your attached funding source such as a sandbox credit card.  I am not sure about which auto-billing you were referring too but you should receive PAYMENT.SALE.COMPLETED when a payment is completed.

**Comment by pp-randy** [comment]
Closing the issue due to inactivity.
