### ISSUE TITLE
Allways VALIDATION_ERROR when 

### ISSUE THREAD

**Issue by romanshul** [paypal/PayPal-PHP-SDK#962]
SDK_VERSION = '1.12.0';
"debug_id":"754e4cd1c7f6"

Hello,
Always VALIDATION_ERROR when I'm trying to create invoice using rest API with PayPal-PHP-SDK library

### Issue description

In account was created an app of invoice type, and was used client_id and secret

function for the invoice creating
`public function createInvoice($params = null)
    {
        if (!$params) {
            return false;
        }

        $invoice = new Invoice();
        // ### Invoice Info
        // Fill in all the information that is
        // required for invoice APIs
        $invoice
            ->setMerchantInfo(new MerchantInfo())
            ->setBillingInfo(array(new BillingInfo()))
            ->setNote("Test invoice, 27 Okt")
            ->setPaymentTerm(new PaymentTerm());

        // ### Merchant Info
        // A resource representing merchant information that can be
        // used to identify merchant
        $owner_email = $this->_credentials['business_owner'];

        $invoice->getMerchantInfo()
                ->setEmail($owner_email)
                ->setFirstName("Name")
                ->setLastName("LastName")
                ->setAddress(new InvoiceAddress());

        // ### Address Information
        // The address used for creating the invoice
        $invoice->getMerchantInfo()->getAddress()
            ->setLine1("1234 Main St.")
            ->setCity("Portland")
            ->setState("OR")
            ->setPostalCode("97217")
            ->setCountryCode("US");

        // ### Billing Information
        // Set the email address for each billing
        $billing = $invoice->getBillingInfo();
        $billing[0]->setEmail($params['email']);

        $billing[0]->setBusinessName("Jay Inc")
            ->setAdditionalInfo("This is the billing Info")
            ->setAddress(new InvoiceAddress());

        $billing[0]->getAddress()
            ->setLine1("1234 Main St.")
            ->setCity("Portland")
            ->setState("OR")
            ->setPostalCode("97217")
            ->setCountryCode("US");

        $items = [];
        foreach ($params['items'] as $key => $item) {
            # code...
            $items[$key] = new InvoiceItem();
            $items[$key]
                ->setName($item['name'])
                ->setQuantity($item['quantity'])
                ->setUnitPrice(new Currency());
            $items[$key]->getUnitPrice()
                ->setCurrency($params['currency'])
                ->setValue((double) $item['price']);
        }

        $invoice->getPaymentTerm()
                    ->setTermType("NET_45");
        // ### Items List
        $invoice->setItems($items);
        $request = clone $invoice;

        $errors = [];
        try {
            $invoice->create($this->config);
        } catch (PayPal\Exception\PayPalConnectionException $ex) {
            $errors = [
                'code'    => $ex->getCode(),
                'data'    => $ex->getData(),
                'message' => $ex->getMessage()
            ];
        } catch (\Exception $ex) {
            $errors = [
                'code'    => $ex->getCode(),
                'message' => $ex->getMessage()
            ];
        }

        return [
            'errors'    => $errors,
            'invoices'  => $invoice
        ];
    }`
It is all response what I see in the logfile:
`Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/invoicing/invoices. {"name":"VALIDATION_ERROR","message":"Invalid request - see details.","information_link":"https://developer.paypal.com/docs/api/invoicing/#errors","debug_id":"754e4cd1c7f6","details":[{"location":"merchantEmail","value":"dima@lukhanin.com"}]}`

**Comment by xiaoleih41** [comment]
What's the merchant's PayPal account email?I don't seem to be able to find it in the sandbox system.

**Comment by romanshul** [comment]
I changed email(dima@lukhanin.com)

**Comment by xiaoleih41** [comment]
It's not a registered sandbox paypal account. Did you create this account inside of developer.paypal.com dashboard?

**Comment by xiaoleih41** [comment]
close due to inactivity. Please resubmit when you have additional info
