### ISSUE TITLE
Paypal rest api pagination not working on production

### ISSUE THREAD

**Issue by maheshsetti** [paypal/PayPal-PHP-SDK#964]
* SDK/Library version: REST API
* Environment: Production

Same query parameters are working with sandbox account but when i use it with production its not working.
### Sandbox api call:
```
https://api.sandbox.paypal.com/v1/payments/payment?start_time=2017-10-01T00:00:00Z&end_time=2017-10-05T23:59:00Z&start_id=PAY-xxxxxxxxxxxxxxxx
```
### Production api call:
```
https://api.paypal.com/v1/payments/payment?start_time=2017-10-19T00:00:00Z&end_time=2017-10-26T23:59:59Z&count=20&start_id=PAY-xxxxxxxxxxxxxxxx
```

**Comment by pp-randy** [comment]
Can you provide a paypal-debug-id from the response headers for your production call?

**Comment by pp-randy** [comment]
Closing due to no response.
