### ISSUE TITLE
Cannot validate city state and zip during payment execute

### ISSUE THREAD

**Issue by mtroyanovsky** [paypal/PayPal-PHP-SDK#969]
### General information

* SDK/Library version:  
* Environment:  Live mode
* `PayPal-Debug-ID` values:  fdb06ea5d7903, f929daebb2629
* Language, language version, and OS:  PHP 7.1, Ubuntu 16.04

### Issue description
When I try to execute payment(step 2 in samples), the paypal returns VALIDATION_ERROR
`{"name":"VALIDATION_ERROR","details":[{"field":"city","issue":"Value is invalid"},{"field":"state","issue":"Value is invalid"},{"field":"zip","issue":"Value is invalid"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"fdb06ea5d7903"}`
In Sandbox mode it's ok, have no ideas why

**Comment by xiaoleih41** [comment]
What city, state and zip did you send in that call?

**Comment by mtroyanovsky** [comment]
```
{
  "shipping_address": {
    "city": "Orenburg",
    "line1": "******",
    "recipient_name": "*****",
    "state": "AL",
    "postal_code": "46000",
    "country_code": "US"
  }
}
```
The problem was solved.
I just comment line with `setTransactions` method and it was help me.
```
public static function executePayment($payment, $payer_id) {
		$execution = new PaymentExecution();
		$execution->setPayerId($payer_id);
		// $execution->setTransactions($payment->getTransactions());
		$payment = $payment->execute($execution, self::_getApiContext());
		return $payment;
	}
```
Issue can be closed. Thanks!

**Comment by xiaoleih41** [comment]
46000 is not a valid zipcode on the USPS website.

**Comment by xiaoleih41** [comment]
Close as the answer has been given
