### ISSUE TITLE
I have not received any message when max_fail_attempts has been reached.

### ISSUE THREAD

**Issue by wiloke** [paypal/PayPal-PHP-SDK#970]
Hi,
I'm using PayPal Rest API for my project, but I'm confusing. When I tested with 0.01$, I got "PAYMENT.SALE.COMPLETED" event, but When I tested with 100000$ and max_fail_attempts has been reached, I got nothing. Could you please explain that?
Thanks

**Comment by xiaoleih41** [comment]
I don't quite understand the exact situation. Are you using payments or billing agreements? Can you provide the steps for me to better understand what you are trying to achieve?

**Comment by wiloke** [comment]
Hi 
Yes, I'm using "billing agreements", and I want to know what event I should get when our customer has been reached max_fail_attempts. 
When I created a subscription, I got "BILLING.SUBSCRIPTION.CREATED" event, on the next billing date, I got "PAYMENT.SALE.COMPLETED" event, but when our customer has been reached  max_fail_attempts, I have not received any event yet. 
Thanks

**Comment by xiaoleih41** [comment]
I don't think there's any webhook specifically linked to `max_fail_attempts` What's the behavior were you expecting after people hit that limit? Will the billing agreement be cancelled or suspended?

**Comment by wiloke** [comment]
I just write a log file like this 
`<?php
if ( isset($_REQUEST['gateway']) && ($_REQUEST['gateway'] == 'paypal') ){
	$raw_post_data = file_get_contents('php://input');

	$content = file_get_contents('live.php');

	if ( $content != '' ){
		$content = $content . "\r\n" . "----------------" . "\r\n" . $raw_post_data;
	}else{
		$content = $raw_post_data;
	}

	file_put_contents('live.php', $content);
}
`
I'm working on Add Listing website, My idea: When user has been reached max_fail_attempts, I will disable Add Listing permission.
Thanks

**Comment by xiaoleih41** [comment]
What's the status of the billing agreement after the user hits the limit?

**Comment by xiaoleih41** [comment]
Close this issue as it has been tracked here https://github.com/paypal/PayPal-REST-API-issues/issues/109.  Please follow that issue going forward
