### ISSUE TITLE
Paypal here merchant login API not work with production account

### ISSUE THREAD

**Issue by thekingbk90** [paypal/PayPal-PHP-SDK#971]
I'm in UK. I have a problem with paypal here API. It work with my sandbox account without my live account.
- With Sandbox account (name Ryan) I used this link => It worked:
https://www.sandbox.paypal.com/signin/authorize?scope=openid https://uri.paypal.com/services/paypalattributes/business https://uri.paypal.com/services/paypalhere address email&response_type=code&redirect_uri=https://devm2.nhubinh.com/webpospaypal/config/paypalsignin/&client_id=AU9fItE20_S6mZNKKyIYGwb0p9k5EFfvVBvXT4yI1tcQokAWWqw9AxEdOA3GLdZHLDW5SMdil9rGdxpq

- With Live account I used this link => Error: invalid scope
https://www.paypal.com/signin/authorize?scope=openid https://uri.paypal.com/services/paypalattributes/business https://uri.paypal.com/services/paypalhere address email&response_type=code&redirect_uri=https://pmvape.co.uk/webpospaypal/config/paypalsignin/&client_id=AaROz0chaNxlK1cwItqOWoEk3A76ABdx3uCVzFTcm4xASwRU07Ro3-HKcE9z01qjUCVBZ2v4jqWsMp1A

I'm sure that my live account is bussiness, my Paypal app has enough paypal here permission, and callback url was filled.
In Addition, My live paypal merchant account can work with Paypal here app (from Apple Store)
Screenshots:
https://prnt.sc/h615la
https://prnt.sc/h615u6
https://prnt.sc/h615y9

Anyone can help me.

Regards,
Johnny

**Comment by pp-randy** [comment]
Please file this issue in the PayPal Here repository: 
[paypal/paypal-here-sdk-ios-distribution](https://github.com/paypal/paypal-here-sdk-ios-distribution)
