### ISSUE TITLE
[QUESTION] Format converter decimal values

### ISSUE THREAD

**Issue by kslimani** [paypal/PayPal-PHP-SDK#973]
### General information

* SDK/Library version: master branch
* Environment: Sandbox
* `PayPal-Debug-ID` values: _not required_
* Language, language version, and OS: PHP 7

### Issue description

In the [Currency Codes](https://developer.paypal.com/docs/integration/direct/rest/currency-codes/#paypal-account-payments) REST APIs documentation, it is stated that _Hungarian forint_ (`HUF`) currency does not support decimals.

In the [format converter](https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Converter/FormatConverter.php#L49) helper class, it seems that only `JPN` and `TWD` currencies are checked.

Does this currency is missing in SDK or it is the documentation which is not up to date ?

Regards,

**Comment by xiaoleih41** [comment]
We are looking into this.

**Comment by pp-randy** [comment]
Closing in favor of this pull request to address the issue https://github.com/paypal/PayPal-PHP-SDK/pull/974.  Thank you for bringing it to our attention.
