### ISSUE TITLE
Paypal recurring payment issue !

### ISSUE THREAD

**Issue by bardascat** [paypal/PayPal-PHP-SDK#975]
I'm trying to setup recurring payments in Paypal for my website using REST API, and I have 2 questions/problems

1.Can't see transaction details in the paypal checkout page:
For one time payment, I know how to display transaction details by providing values for item_list (as in https://developer.paypal.com/docs/api/). 
However I don't know what values we should provide so that recurring payment profile will be shown on checkout page as well. 

In the below picture(left side) you can see that no information is presented to the client regarding the payment amount and setup fees.
https://i.stack.imgur.com/EOPGV.jpg
	
If I switch to production environment when the user tries to make a recurring payment, the user is redirected to the paypal website and he sees this error:
_Sorry, we weren’t able to set up preapproved payments at this time.
Please return to the merchant and choose another way to pay._
	
So what's the issue with the recurring payment:
Why the user does not see any information regarding the payment amount in checkout paypal checkout page.
Why in production env the user get's that error message ?

I'm using this documentation:
http://paypal.github.io/PayPal-PHP-SDK/sample/doc/billing/CreatePlan.html
http://paypal.github.io/PayPal-PHP-SDK/sample/doc/billing/CreateBillingAgreementWithPayPal.html
http://paypal.github.io/PayPal-PHP-SDK/sample/doc/billing/ExecuteAgreement.html

2. How will I be notified when a paypal client cancel the recurring payment ? 
It is important for my web application to know when somebody cancel the recurring payment.
I read something about webhooks, is this the way? Can you give me some documentation  ?
	
My location is Romania, if this matters.

Thanks,
Catalin

**Comment by pp-randy** [comment]
> 1. Can't see transaction details in the paypal checkout page:

Unfortunately, the details are not displayed and this is a known issue https://github.com/paypal/PayPal-REST-API-issues/issues/7.  As a workaround use the description and ensure you display the plan details you need prior to redirecting to PayPal. 

> 2. Why in production env the user get's that error message ?

That looks like a possible payment decline, can you try a different funding source?  If the, issue persists can you provide the PayPal Debug Id from the response headers of the Create Billing Agreement call and I will see if I can find some details.

**Comment by zanderwar** [comment]
> How will I be notified when a paypal client cancel the recurring payment ?
> It is important for my web application to know when somebody cancel the recurring payment.
> I read something about webhooks, is this the way? Can you give me some documentation ?

Webhooks is in fact the right way. You'd be listening for `BILLING.SUBSCRIPTION.CANCELED`

Ref: https://developer.paypal.com/docs/integration/direct/webhooks/event-names/

**Comment by bardascat** [comment]
Thank you for your response !

**Comment by pp-randy** [comment]
Closing as the solution has been provided
