### ISSUE TITLE
I'm here in api paypal

### ISSUE THREAD

**Issue by giicms** [paypal/PayPal-PHP-SDK#976]
PayPal\Exception\PPConnectionException

error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure

File log
PayPal\Core\PPHttpConnection: Connecting to https://api.sandbox.paypal.com/v1/oauth2/token
PayPal\Core\PPHttpConnection: Payload grant_type=client_credentials
PayPal\Core\PPHttpConnection: Adding header User-Agent: PayPalSDK/rest-sdk-php 0.6.0 (lang=PHP;v=7.0.16;bit=32;os=Windows_NT_10.0;machine=i586;openssl=1.0.2k;curl=7.51.0)
PayPal\Core\PPHttpConnection: Adding header Authorization: Basic QWFKSHpqcnlNSGhtb1lqRlRiRFhrQlZDX0NVSzJHejc3TF9IVWpEOXdZWXItbUVTMkFvUGhpbm1sbm9JNnBiNVNYSVFHVnFjOUctNnpHQWI6RUZDSzJ5SWJ5NWtxTEQ4c2JGdi04QWJNdl9SN3ZxcE1mV21hMkdsOWQ4MXc2NWtycnJRNWpxNzhkRDExcTlEYkZWd0hXODFtbkZWbmV5Skw=
PayPal\Core\PPHttpConnection: Adding header Accept: */*

http://www.openscreenshot.com/BycDgflkz

**Comment by pp-randy** [comment]
This is expected behavior as the sandbox environment no longer allows SSLv3.  Please review [paypal/tls-update#php](https://github.com/paypal/tls-update#php) for more information on how to correct this problem.
