### ISSUE TITLE
Non consistent behaviour of create() 

### ISSUE THREAD

**Issue by Sadrak** [paypal/PayPal-PHP-SDK#977]
https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Api/Payment.php#L578
```
        $this->fromJson($json);
        return $this;
```

https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Api/WebProfile.php#L182
```
        $ret = new CreateProfileResponse();
        $ret->fromJson($json);
        return $ret;
```

I don't see why there is a different behaviour. Is there a good explanation or simple a lack of consistent (which could be fixed)?

For payments the samples look like:

```
$payment->create($apiContext);
print $payment->getApprovalLink();
```

and for WebProfiles it is:
```
$return = $webProfile->create($apiContext);
print $return->getId();
```

**Comment by jaypatel512** [comment]
Hey @Sadrak !

We found that the way `Payment` object's `create` is defined, it can cause a lot of confusion for developers, as it was hard to differentiate between `response` data that paypal returned, and `request` data, that you set.

We agreed to use a different approach where each methods should return a new instance back, which we have done for all other classes (including `WebProfile`). However, as you can see, updating `Payment` object at this point would cause a backward in-compatible change, and hence, cannot do that in 1.x release.

We are fixing this in 2.x version of this SDK, along with many other such design changes we learnt from 1.x.
