### ISSUE TITLE
Not getting confirmation page in Production

### ISSUE THREAD

**Issue by danielfrance** [paypal/PayPal-PHP-SDK#978]
### General information

* SDK/Library version: 
* Environment:  Production
* `PayPal-Debug-ID` values: 
* Language, language version, and OS:  php 7.0 Laravel 5.4

### Issue description

I'm using Laravel 5.4
![attachment-4](https://user-images.githubusercontent.com/4622440/32670990-4fc182de-c60b-11e7-9abd-d510ebf11a20.png)
I'm having a production issue.  In my attachment, you can see that a user is sent to a confirmation page to after entering their credit card information.  however in production, I am not redirected to that view.  My paypal.log file is showing successful api calls, and so is my dashboard, but I'm not receiving any errors along the way that can help point me in the right direction. 

My .env file correctly references the live secret and client keys.  I'm at a loss here, any help is appreciated.

**Comment by pp-randy** [comment]
I apologize I am some what confused what the issue is you are seeing.  I see the screenshot for your sandbox integration, that is a legacy checkout flow.   What page are you getting in production?   Is the user not being returned back to your website after approval? 

Can you provide a PayPal Debug Id from the response headers of your Payment API call, or view the source of the production page and find the rlogid value at the time, and I will try to piece some things together?

**Comment by danielfrance** [comment]
Hey Randy. Thanks for being so quick to respond.  

In production, a user gets the following view, but does not get the confirmation view (attachment from previous post).  They are simply redirected back to the website.  
<img width="1190" alt="attachment-3" src="https://user-images.githubusercontent.com/4622440/32673208-d814d0a2-c613-11e7-9a68-f32023e36b6a.png">


I do not have a PayPal Debug ID, and I'm not entirely sure how to find it.  Apologies for not being entirely prepared. I'll review the docs to figure out how to get one.

**Comment by xiaoleih41** [comment]
The debugId should be in the header of the API response. I am not sure which confirmation view you are referring to. Can you please provide step by step of both flows for us to better understand what you are looking for? Are you saying after the user entering the credit card, they gets redirect back to enter the credit card again instead of showing the order summary?

**Comment by danielfrance** [comment]
@xiaoleih41 Thanks for helping me clarify.

Current User Flow in production:
- User go to client website 
- User selects donation level and fills out form
- User is redirected to fill in credit card information on paypal site.  
- User fills out information, hits submit, and is then redirected back to client website
- in dev environment, user is directed to confirmation page which I attached in my first comment.

Client does not receive a successful payment, and money is not withdrawn from user bank account.

When a user is redirected after submitting their payment information, I receive the following GET Parameters with information that I've omitted: 
paymentId=
token= 
PayerID= 

Below is a portion of my controller
`    public function index(Request $request)
    {

        $this->validate($request, [
            'first_name'    =>  'required',
            'last_name'     =>  'required',
            'email'         =>  'required',
            'donation'      =>  'required'
        ]);

        $this->store($request);
        //store the data and send an email
        $this->mailRequest($request);



        $payer = new Payer();
        $payer->setPaymentMethod('paypal');
        $item_1 = new Item();
        $item_1->setName('Oklahoma Academy Donation') /** item name **/
        ->setCurrency('USD')
            ->setQuantity(1)
            ->setPrice($request->donation); /** unit price **/
        $item_list = new ItemList();
        $item_list->setItems(array($item_1));
        $amount = new Amount();
        $amount->setCurrency('USD')
            ->setTotal($request->donation);
        $transaction = new Transaction();
        $transaction->setAmount($amount)
            ->setItemList($item_list)
            ->setDescription('Thank you for your donation');
        $redirect_urls = new RedirectUrls();
        $redirect_urls->setReturnUrl(URL::route('memberships')) /** Specify return URL **/
        ->setCancelUrl(URL::route('memberships'));
        $payment = new Payment();
        $payment->setIntent('Sale')
            ->setPayer($payer)
            ->setRedirectUrls($redirect_urls)
            ->setTransactions(array($transaction));
        /**exit; **/
        try {
            $payment->create($this->_api_context);
        } catch (PPConnectionException $ex) {
            if (Config::get('app.debug')) {
                Session::put('error','Connection timeout');
                return redirect()->to('memberships.submit');
                /** echo "Exception: " . $ex->getMessage() . PHP_EOL; **/
                /** $err_data = json_decode($ex->getData(), true); **/
                /** exit; **/

            } else {
                Session::put('error','Some error occur, sorry for inconvenient');
                return redirect()->to('memberships.submit');
                /** die('Some error occur, sorry for inconvenient'); **/
            }
        }
        foreach($payment->getLinks() as $link) {
            if($link->getRel() == 'approval_url') {
                $redirect_url = $link->getHref();
                break;
            }
        }
        /** add payment ID to session **/
        Session::put('paypal_payment_id', $payment->getId());
        if(isset($redirect_url)) {
            /** redirect to paypal **/
            return redirect()->to($redirect_url);
        }
        Session::put('error','Unknown error occurred');
        return redirect()->to('memberships');

    }

    public function getPaymentStatus()
    {
        /** Get the payment ID before session clear **/
        $payment_id = Session::get('paypal_payment_id');
        /** clear the session payment ID **/
        Session::forget('paypal_payment_id');


        if (empty(Input::get('PayerID')) || empty(Input::get('token'))) {
            Session::put('error','Payment failed');
            return redirect()->to('memberships');
        }


        $payment = Payment::get($payment_id, $this->_api_context);
        /** PaymentExecution object includes information necessary **/
        /** to execute a PayPal account payment. **/
        /** The payer_id is added to the request query parameters **/
        /** when the user is redirected from paypal back to your site **/
        $execution = new PaymentExecution();
        $execution->setPayerId(Input::get('PayerID'));
        /**Execute the payment **/
        $result = $payment->execute($execution, $this->_api_context);
        /** dd($result);exit; /** DEBUG RESULT, remove it later **/
        if ($result->getState() == 'approved') {

            /** it's all right **/
            /** Here Write your database logic like that insert record or value in database if you want **/
            Session::put('success','Payment success');
            return redirect()->to('memberships');
        }
        Session::put('error','Payment failed');
        return redirect()->to('memberships');
    }
`

**Comment by danielfrance** [comment]
@xiaoleih41 I forgot to include my construct method and my env variables.  Since the site works correctly in sandbox mode, I'm assuming this has to be an issue with how I call my `paypal_mode`

`    private $_api_context;
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {

        /** setup PayPal api context **/
        $paypal_conf = Config::get('paypal');
        $this->_api_context = new ApiContext(new OAuthTokenCredential($paypal_conf['client_id'], $paypal_conf['secret']));
        $this->_api_context->setConfig($paypal_conf['settings']);

    }`

`PAYPAL_SECRET=XXXXXX
PAYPAL_CLIENT_ID=XXXXX
PAYPAL_MODE=sandbox`

I use the same format on the production site however on production my PAYPAL_MODE is:

`PAYPAL_MODE=live`

**Comment by xiaoleih41** [comment]
The screenshot you showed us first looks more like a before page, it asks you to log into your PayPal account or pay by credit card.  I am a bit confused why you are expecting this page to pop up after you have already selected PayPal guest checkout flow.  After credit card flow, you should be redirected back to your site showing that payment is successful.

**Comment by pp-randy** [comment]
Do you mean a confirmation page on your website?  Let double check your `return_url` for the payment if that is the case.  We do not see a confirmation page in your first comment, only the checkout page which is the legacy version to this new screenshot you are showing.  @xiaoleih41 and I have discussed internally and do not understand exactly what is wrong as both screenshots look correct to us.

**Comment by alisherazi50** [comment]
how we can change the paypal checkout page language... my paypal account is Spanish and its showing Spanish language i want to change checkout page language to English how can i do that ?
