### ISSUE TITLE
INVALID_RESOURCE_ID - 404 when accessing https://api.sandbox.paypal.com/v1/payments/payment/PAY-52H84142DM845535FLID7ZLA

### ISSUE THREAD

**Issue by winer632** [paypal/PayPal-PHP-SDK#980]
### General information

* SDK/Library version: 1.12.0
* Environment: **Live**
* `PayPal-Debug-ID` values: 49779b28cd160
* Language, language version, and OS: 
PHP 7.1.5 (cli) (built: May 25 2017 17:00:55) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
CentOS Linux release 7.3.1611 (Core) 
### Issue description
@pp-randy 
**"debug_id":"49779b28cd160"**

```
TIME: 2017-11-12_15:48:04    paymentClientJson is {"amount":"0.01","currency_code":"USD","short_description":"XPhone [1m~E~E[1m~@,"intent":"sale"}
TIME: 2017-11-12_15:48:04    paymentId is PAY-52H84142DM845535FLID7ZLA
TIME: 2017-11-12_15:48:04    amount_client is 0.01
TIME: 2017-11-12_15:48:04    currency_client is USD
TIME: 2017-11-12_15:48:21    exc is PayPal\Exception\PayPalConnectionException Object
(
    [url:PayPal\Exception\PayPalConnectionException:private] => https://api.sandbox.paypal.com/v1/payments/payment/PAY-52H84142DM845535FLID7ZLA
    [data:PayPal\Exception\PayPalConnectionException:private] => {"name":"INVALID_RESOURCE_ID","message":"Requested resource ID was not found.","information_link":"https://developer.paypal
.com/docs/api/payments/#errors","debug_id":"49779b28cd160"}
    [message:protected] => Got Http response code 404 when accessing https://api.sandbox.paypal.com/v1/payments/payment/PAY-52H84142DM845535FLID7ZLA.
    [string:Exception:private] =>
    [code:protected] => 404
    [file:protected] => /usr/local/nginx/html/PayPal-PHP-SDK/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php
    [line:protected] => 202
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /usr/local/nginx/html/PayPal-PHP-SDK/paypal/rest-api-sdk-php/lib/PayPal/Transport/PayPalRestCall.php
                    [line] => 73
                    [function] => execute
                    [class] => PayPal\Core\PayPalHttpConnection
                    [type] => ->
                    [args] => Array
                        (
                            [0] =>
                        )

**Comment by pp-randy** [comment]
Can you provide details or the debug id for the create request for this payment?

**Comment by EdanSmith** [comment]
SDK/Library version: 1.11.0
Environment: Live
PayPal-Debug-ID values: "debug_id":"bb171a68e39a1"
PHP 5.6, Windows 10

I'm having a similar problem...
I don't know if I should open a new issue or just use this one since it's almost the same thing. Also, can it be because my lib version is 1.11.0?

Full error message:
Got Http response code 404 when accessing https://api.paypal.com/v1/payments/payment/PAY-7H698759FC185673JLH44LTA.
{"name":"INVALID_RESOURCE_ID","message":"The requested resource ID was not found","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"bb171a68e39a1"}

**Comment by pp-randy** [comment]
@EdanSmith was that payment ever successfully executed?  I see logging from November 2 but don't see an execute, but if it was do you have the transaction id by chance? 

If the payment was never fully completed the payment will not stick around.  Only completed payments will stay.

**Comment by winer632** [comment]
General information

SDK/Library version: 1.12.0
Environment: Sandbox
PayPal-Debug-ID values: 49779b28cd160
Language, language version, and OS:
PHP 7.1.5 (cli) (built: May 25 2017 17:00:55) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
CentOS Linux release 7.3.1611 (Core)

Issue description
`TIME: 2017-11-15_07:19:52    paymentClientJson is {"amount":"0.01","currency_code":"USD","short_description":"XPhone 充值","intent":"sale"}
TIME: 2017-11-15_07:19:52    paymentId is PAY-9S4904117T570954WLIFXUEA
TIME: 2017-11-15_07:19:52    amount_client is 0.01
TIME: 2017-11-15_07:19:52    currency_client is USD
TIME: 2017-11-15_07:19:52    username is arslanpervaiz778@gmail.com
TIME: 2017-11-15_07:19:52    imei is 355311070422417
TIME: 2017-11-15_07:19:52    login_ip is 119.160.119.75
TIME: 2017-11-15_07:19:56    exc is PayPal\Exception\PayPalConnectionException Object
(
    [url:PayPal\Exception\PayPalConnectionException:private] => https://api.sandbox.paypal.com/v1/payments/payment/PAY-9S4904117T570954WLIFXUEA
    [data:PayPal\Exception\PayPalConnectionException:private] => {"name":"INVALID_RESOURCE_ID","message":"Requested resource ID was not found.","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"11737d0118d57"}
    [message:protected] => Got Http response code 404 when accessing https://api.sandbox.paypal.com/v1/payments/payment/PAY-9S4904117T570954WLIFXUEA.
    [string:Exception:private] => 
    [code:protected] => 404
    [file:protected] => /usr/local/nginx/html/PayPal-PHP-SDK/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php
    [line:protected] => 202
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /usr/local/nginx/html/PayPal-PHP-SDK/paypal/rest-api-sdk-php/lib/PayPal/Transport/PayPalRestCall.php
                    [line] => 73
                    [function] => execute
                    [class] => PayPal\Core\PayPalHttpConnection
                    [type] => ->
                    [args] => Array
                        (
                            [0] => 
                        )

                )

            [1] => Array
                (
                    [file] => /usr/local/nginx/html/PayPal-PHP-SDK/paypal/rest-api-sdk-php/lib/PayPal/Common/PayPalResourceModel.php
                    [line] => 104
                    [function] => execute
                    [class] => PayPal\Transport\PayPalRestCall
                    [type] => ->
                    [args] => Array
                        (
                            [0] => Array
                                (
                                    [0] => PayPal\Handler\RestHandler
                                )

                            [1] => /v1/payments/payment/PAY-9S4904117T570954WLIFXUEA
                            [2] => GET
                            [3] => 
                            [4] => Array
                                (
                                )

                        )

                )

            [2] => Array
                (
                    [file] => /usr/local/nginx/html/PayPal-PHP-SDK/paypal/rest-api-sdk-php/lib/PayPal/Api/Payment.php
                    [line] => 600
                    [function] => executeCall
                    [class] => PayPal\Common\PayPalResourceModel
                    [type] => ::
                    [args] => Array
                        (
                            [0] => /v1/payments/payment/PAY-9S4904117T570954WLIFXUEA
                            [1] => GET
                            [2] => 
                            [3] => 
                            [4] => PayPal\Rest\ApiContext Object
                                (
                                    [requestId:PayPal\Rest\ApiContext:private] => 
                                    [credential:PayPal\Rest\ApiContext:private] => PayPal\Auth\OAuthTokenCredential Object
                                        (
                                            [clientId:PayPal\Auth\OAuthTokenCredential:private] => AbCFf8nwj4hydjNzdAZ-rezeC4aUAhCxTz1aRafqIJgEMlIhMIr4gWzF8qun3CSHzJyq6PicGqxSFnW9
                                            [clientSecret:PayPal\Auth\OAuthTokenCredential:private] => EJU_w2L67pCYHjqEwpuRYmkpN4oFHb1wYdQt2r14WWewS3FjmofSvHS7y9B3PX5OoJuvz3Wnrtb7uMqL
                                            [accessToken:PayPal\Auth\OAuthTokenCredential:private] => A21AAHcZY2soDgESXGXk5FKoBM1vgPKtvZai1UErbQgAotZpxmgrC0HFYNlT9M4WISI-Xzoz-hGSeYKA_798iljZFB3AYBVOw
                                            [tokenExpiresIn:PayPal\Auth\OAuthTokenCredential:private] => 32400
                                            [tokenCreateTime:PayPal\Auth\OAuthTokenCredential:private] => 1510701594
                                            [cipher:PayPal\Auth\OAuthTokenCredential:private] => PayPal\Security\Cipher Object
                                                (
                                                    [secretKey:PayPal\Security\Cipher:private] => EJU_w2L67pCYHjqEwpuRYmkpN4oFHb1wYdQt2r14WWewS3FjmofSvHS7y9B3PX5OoJuvz3Wnrtb7uMqL
                                                )

                                            [_propMap:PayPal\Common\PayPalModel:private] => Array
                                                (
                                                )

                                        )

                                )

                            [5] => PayPal\Transport\PayPalRestCall Object
                                (
                                    [logger:PayPal\Transport\PayPalRestCall:private] => PayPal\Core\PayPalLoggingManager Object
                                        (
                                            [logger:PayPal\Core\PayPalLoggingManager:private] => PayPal\Log\PayPalLogger Object
                                                (
                                                    [loggingLevels:PayPal\Log\PayPalLogger:private] => Array
                                                        (
                                                            [0] => emergency
                                                            [1] => alert
                                                            [2] => critical
                                                            [3] => error
                                                            [4] => warning
                                                            [5] => notice
                                                            [6] => info
                                                            [7] => debug
                                                        )

                                                    [loggingLevel:PayPal\Log\PayPalLogger:private] => 
                                                    [loggerFile:PayPal\Log\PayPalLogger:private] => 
                                                    [isLoggingEnabled:PayPal\Log\PayPalLogger:private] => 
                                                    [loggerName:PayPal\Log\PayPalLogger:private] => PayPal\Transport\PayPalRestCall
                                                )

                                            [loggerName:PayPal\Core\PayPalLoggingManager:private] => PayPal\Transport\PayPalRestCall
                                        )

                                    [apiContext:PayPal\Transport\PayPalRestCall:private] => PayPal\Rest\ApiContext Object
                                        (
                                            [requestId:PayPal\Rest\ApiContext:private] => 
                                            [credential:PayPal\Rest\ApiContext:private] => PayPal\Auth\OAuthTokenCredential Object
                                                (
                                                    [clientId:PayPal\Auth\OAuthTokenCredential:private] => AbCFf8nwj4hydjNzdAZ-rezeC4aUAhCxTz1aRafqIJgEMlIhMIr4gWzF8qun3CSHzJyq6PicGqxSFnW9
                                                    [clientSecret:PayPal\Auth\OAuthTokenCredential:private] => EJU_w2L67pCYHjqEwpuRYmkpN4oFHb1wYdQt2r14WWewS3FjmofSvHS7y9B3PX5OoJuvz3Wnrtb7uMqL
                                                    [accessToken:PayPal\Auth\OAuthTokenCredential:private] => A21AAHcZY2soDgESXGXk5FKoBM1vgPKtvZai1UErbQgAotZpxmgrC0HFYNlT9M4WISI-Xzoz-hGSeYKA_798iljZFB3AYBVOw
                                                    [tokenExpiresIn:PayPal\Auth\OAuthTokenCredential:private] => 32400
                                                    [tokenCreateTime:PayPal\Auth\OAuthTokenCredential:private] => 1510701594
                                                    [cipher:PayPal\Auth\OAuthTokenCredential:private] => PayPal\Security\Cipher Object
                                                        (
                                                            [secretKey:PayPal\Security\Cipher:private] => EJU_w2L67pCYHjqEwpuRYmkpN4oFHb1wYdQt2r14WWewS3FjmofSvHS7y9B3PX5OoJuvz3Wnrtb7uMqL
                                                        )

                                                    [_propMap:PayPal\Common\PayPalModel:private] => Array
                                                        (
                                                        )

                                                )

                                        )

                                )

                        )

                )

            [3] => Array
                (
                    [file] => /usr/local/nginx/html/verifyPayment.php
                    [line] => 62
                    [function] => get
                    [class] => PayPal\Api\Payment
                    [type] => ::
                    [args] => Array
                        (
                            [0] => PAY-9S4904117T570954WLIFXUEA
                            [1] => PayPal\Rest\ApiContext Object
                                (
                                    [requestId:PayPal\Rest\ApiContext:private] => 
                                    [credential:PayPal\Rest\ApiContext:private] => PayPal\Auth\OAuthTokenCredential Object
                                        (
                                            [clientId:PayPal\Auth\OAuthTokenCredential:private] => AbCFf8nwj4hydjNzdAZ-rezeC4aUAhCxTz1aRafqIJgEMlIhMIr4gWzF8qun3CSHzJyq6PicGqxSFnW9
                                            [clientSecret:PayPal\Auth\OAuthTokenCredential:private] => EJU_w2L67pCYHjqEwpuRYmkpN4oFHb1wYdQt2r14WWewS3FjmofSvHS7y9B3PX5OoJuvz3Wnrtb7uMqL
                                            [accessToken:PayPal\Auth\OAuthTokenCredential:private] => A21AAHcZY2soDgESXGXk5FKoBM1vgPKtvZai1UErbQgAotZpxmgrC0HFYNlT9M4WISI-Xzoz-hGSeYKA_798iljZFB3AYBVOw
                                            [tokenExpiresIn:PayPal\Auth\OAuthTokenCredential:private] => 32400
                                            [tokenCreateTime:PayPal\Auth\OAuthTokenCredential:private] => 1510701594
                                            [cipher:PayPal\Auth\OAuthTokenCredential:private] => PayPal\Security\Cipher Object
                                                (
                                                    [secretKey:PayPal\Security\Cipher:private] => EJU_w2L67pCYHjqEwpuRYmkpN4oFHb1wYdQt2r14WWewS3FjmofSvHS7y9B3PX5OoJuvz3Wnrtb7uMqL
                                                )

                                            [_propMap:PayPal\Common\PayPalModel:private] => Array
                                                (
                                                )

                                        )

                                )

                        )

                )

        )

    [previous:Exception:private] => 
)`

**Comment by winer632** [comment]
@pp-randy My sandbox account has a same email account winer632@qq.com and 181710174@qq.com with live account. Is this the root cause of this problem?
Because I collect money in a real production environment, but the abnormal url printed in the log is sandbox's. This is strange.

**Comment by winer632** [comment]
@pp-randy One more thing, my sandbox account has a email test2017@qq.com which status is error.
I want to delete this sandbox email address test2017@qq.com, but failed. The hint is "Something went wrong. One or more sandbox accounts could not be deleted. Try again.". Could you please help me delete this sandbox email address test2017@qq.com?
Thank you!

**Comment by winer632** [comment]
@pp-randy I did money transaction in live environment, the api should be https//api.paypal.com/XXXXXX,
why it appears to be sandbox api url  [url:PayPal\Exception\PayPalConnectionException:private] => https://api.sandbox.paypal.com/v1/payments/payment/PAY-XXXXXXXXXXX ?

**Comment by pp-randy** [comment]
@winer632 thank you for the transaction id.  Your payment is for Live or Production but your API lookup is for the sandbox.  

You are using the sandbox endpoint `https://api.sandbox.paypal.com/v1/payments/payment/PAY-XXXXXXXXXXX`
but need to use `https://api.paypal.com/v1/payments/payment/PAY-XXXXXXXXXXX`.

**Comment by pp-randy** [comment]
@winer632 configure your system for live https://github.com/paypal/PayPal-PHP-SDK/wiki/Going-Live that you are using to lookup the payment.  Two separate applications maybe?

**Comment by winer632** [comment]
@pp-randy Thank you! I fixed this after I add this code.
$apiContext->setConfig(
      array(
        ...
        'mode' => 'live',
        ...
      )
);

One more thing which not related to this, my sandbox account has an email address test2017@qq.com which status is error.
I want to delete this sandbox email address test2017@qq.com, but failed. The hint is "Something went wrong. One or more sandbox accounts could not be deleted. Try again.". Could you please help me delete this sandbox email address test2017@qq.com?
Thank you!

**Comment by winer632** [comment]
@pp-randy Yes, I no longer need  the sandbox account test2017@qq.com. And the error  status makes me upset when I see it.

**Comment by EdanSmith** [comment]
@pp-randy Hey, yea, the Json that I have on my database is with the state "Created" only... probably the person didn't pay it, this error may have occurred because we were migrating systems, and instead of updating to "Awaiting User Payment" it got into "Pending", which makes the system expect the payment to be approved.
Thanks.

Also, just a last question, if the payment was approved, it wouldn't be showing 404 for that PAY id, right?

**Comment by pp-randy** [comment]
@EdanSmith yes you shouldn't get a 404 for completed payments, the exception would be a bug or system issue otherwise.

**Comment by pp-randy** [comment]
Closing the issue as resolved now.  Please let me know if either of you have further questions.
