### ISSUE TITLE
Merchant account balance not updating

### ISSUE THREAD

**Issue by kimpoy010** [paypal/PayPal-PHP-SDK#981]
I am able to successfully implement paypal payments on my website but when I check each account, the seller account balance was not updated, but the transaction is shown in the transactions history, buyer account is working and was debited.

this is my code for the payment approval

        $sched = Schedule::find($request['sched_id']);
        $paypal = new \PayPal\Rest\ApiContext(
            new \PayPal\Auth\OAuthTokenCredential(
                'inserted_my_client_id_here',     // ClientID
                inserted_app_secret_key_here'      // ClientSecret
            )
        );

        $payer = new \PayPal\Api\Payer();
        $payer->setPaymentMethod('paypal');

        $amount = new \PayPal\Api\Amount();
        $amount->setCurrency("JPY")
                    ->setTotal($sched->amount);
        

        $transaction = new \PayPal\Api\Transaction();
        $transaction->setAmount($amount)
            ->setDescription("Lesson payment")
            ->setInvoiceNumber(uniqid());

        $redirectUrls = new \PayPal\Api\RedirectUrls();
        $redirectUrls->setReturnUrl(route('paypal.return',$request['sched_id']))
                    ->setCancelUrl(route('pages.profile'));

        $payment = new \PayPal\Api\Payment();
        $payment->setIntent('sale')
            ->setPayer($payer)
            ->setTransactions(array($transaction))
            ->setRedirectUrls($redirectUrls);

        try {
            $payment->create($paypal);
            return redirect($payment->getApprovalLink());
        }
        catch (\PayPal\Exception\PayPalConnectionException $ex) {
            echo $ex->getData();
        }`

and this is my code for the processing of payment

        ` 
        $sched = Schedule::find($id);
        $payID = $_GET['paymentId'];
        $payerID = $_GET['PayerID'];

        $paypal = new \PayPal\Rest\ApiContext(
            new \PayPal\Auth\OAuthTokenCredential(
                'inserted_my_client_id_here',     // ClientID
                inserted_app_secret_key_here'      // ClientSecret
            )
        );

        $payment = \PayPal\Api\Payment::get($payID, $paypal);

        $execution = new \PayPal\Api\PaymentExecution();
        $execution->setPayerId($payerID);

        $transaction = new \PayPal\Api\Transaction();
        $amount = new \PayPal\Api\Amount();

        $amount->setCurrency('JPY');
        $amount->setTotal($sched->amount);
        $transaction->setAmount($amount);

        $execution->addTransaction($transaction);

        try {
            $result = $payment->execute($execution, $paypal);
            try {
                $payment = \PayPal\Api\Payment::get($payID, $paypal);
            } catch (Exception $e) {
                return response($e->getMessage);
                exit(1);
            }
        } catch (Exception $e) {
            return response($e->getMessage);
            exit(1);
        }

        // Session::flash('success','Successfully paid lesson fee!');
        // return redirect()->route('pages.profile');

        return response($payment);`

what am I doing wrong here?
Thanks

### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS:

**Comment by pp-randy** [comment]
Is this happening in the sandbox?  If so, can you provide a transaction id?  If this is a production issue please reach out to PayPal Technical Support so sensitive information is not provided in this public forum.  You can submit an issue to them here: https://www.paypal-techsupport.com/app/ask.

**Comment by xiaoleih41** [comment]
Close due to inactivity. Please resubmit when you have additional info

**Comment by kimpoy010** [comment]
Yes. this happens on sandbox. 

Here's a sample json response from my code.

    ` {
	"id": "PAY-82826359FA7269444LIMCC5Q",
	"intent": "sale",
	"state": "approved",
	"cart": "50T46469MD090505F",
	"payer": {
		"payment_method": "paypal",
		"status": "VERIFIED",
		"payer_info": {
			"email": "student@connect-plus.asia",
			"first_name": "Student",
			"last_name": "Connect",
			"payer_id": "THQBZVUD5UNA6",
			"shipping_address": {
				"recipient_name": "Student Connect",
				"line1": "1 Main St",
				"city": "San Jose",
				"state": "CA",
				"postal_code": "95131",
				"country_code": "US"
			},
			"phone": "4087112414",
			"country_code": "US"
		}
	},
	"transactions": [{
		"amount": {
			"total": "1200",
			"currency": "JPY",
			"details": {
				"subtotal": "1200"
			}
		},
		"payee": {
			"merchant_id": "TN4DUW72FT8DA"
		},
		"description": "Lesson payment",
		"invoice_number": "5a1821908c5ff",
		"item_list": {
			"items": [],
			"shipping_address": {
				"recipient_name": "Student Connect",
				"line1": "1 Main St",
				"city": "San Jose",
				"state": "CA",
				"postal_code": "95131",
				"country_code": "US"
			}
		},
		"related_resources": [{
			"sale": {
				"id": "84P12283VA318733V",
				"state": "completed",
				"amount": {
					"total": "1200",
					"currency": "JPY",
					"details": {
						"subtotal": "1200"
					}
				},
				"payment_mode": "INSTANT_TRANSFER",
				"protection_eligibility": "ELIGIBLE",
				"protection_eligibility_type": "ITEM_NOT_RECEIVED_ELIGIBLE,UNAUTHORIZED_PAYMENT_ELIGIBLE",
				"transaction_fee": {
					"value": "87",
					"currency": "JPY"
				},
				"parent_payment": "PAY-82826359FA7269444LIMCC5Q",
				"create_time": "2017-11-24T13:41:50Z",
				"update_time": "2017-11-24T13:41:50Z",
				"links": [{
					"href": "https://api.sandbox.paypal.com/v1/payments/sale/84P12283VA318733V",
					"rel": "self",
					"method": "GET"
				}, {
					"href": "https://api.sandbox.paypal.com/v1/payments/sale/84P12283VA318733V/refund",
					"rel": "refund",
					"method": "POST"
				}, {
					"href": "https://api.sandbox.paypal.com/v1/payments/payment/PAY-82826359FA7269444LIMCC5Q",
					"rel": "parent_payment",
					"method": "GET"
				}]
			}
		}]
	}],
	"create_time": "2017-11-24T13:41:50Z",
	"links": [{
		"href": "https://api.sandbox.paypal.com/v1/payments/payment/PAY-82826359FA7269444LIMCC5Q",
		"rel": "self",
		"method": "GET"
	}]
    }`

**Comment by xiaoleih41** [comment]
We do have delay in the sandbox environment sometimes. That's sandbox issue only. Can you check if it has been updated or not?

**Comment by kimpoy010** [comment]
the balance is still not updated after more than a week.

**Comment by xiaoleih41** [comment]
I have reported this issue. As it's a sandbox, these are not real money. The display may be off from time to time. please download the history from the activity log, it should reflect the true balance.
