### ISSUE TITLE
Pay with Bank account not possible

### ISSUE THREAD

**Issue by kevinlieser** [paypal/PayPal-PHP-SDK#984]
As seen here (http://paypal.github.io/PayPal-PHP-SDK/docs/class-PayPal.Api.Payer.html) the value "bank" is valid. When setting this payment method the debug log tells me a "credit card funding instrument is needed". I don't understand that. I need to set IBAN and BIC and so on, not a credit card (bank account would need different setter). And the `BankAccount` Class is deprecated (http://paypal.github.io/PayPal-PHP-SDK/docs/class-PayPal.Api.BankAccount.html) – so how should I create a bank card object to pay with?

* SDK/Library version: 1.11.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: 30e99fe529889
* Language, language version, and OS: Linux, PHP

**Comment by xiaoleih41** [comment]
Direct ACH has been deprecated for REST API. The users can add their bank accounts to their PayPal accounts and complete the verification process then make the payment out of their PayPal accounts instead.  You may contact your assigned account manager for more information and potential options.

**Comment by kevinlieser** [comment]
So isn't it a feature of PayPal Plus? Am I right that there is no possibility anymore to pay direct via bank account with Paypal Plus? Adding the Bank account to the Papal account needs – a Paypal account. That's what should be avoid here – like credit card payment without Paypal account.

Paypal, Credit card and Invoice is already included in my project – so it seems that I need to integrate bank account payment with another service provider.

**Comment by xiaoleih41** [comment]
Ah, for German paypal plus, it will be different. You should still be able to use direct bank transfer. However I do not believe you can test it under sandbox environment. Please check with regional MTS team for that. www.paypal-techsupport.com.

**Comment by xiaoleih41** [comment]
Close the issue as the direction has been given.
