### ISSUE TITLE
How to send money to users?

### ISSUE THREAD

**Issue by dht20** [paypal/PayPal-PHP-SDK#985]
I can't understand (if it's possible) how to
Send some dollars to my users.
I see only option for users to buy from me or refund.
I want to send money to my users - in exchange for points(my web-site points)

Is this possible?
Thanks.

**Comment by xiaoleih41** [comment]
Are you looking for payout API with you as the sender? The API reference is [here]( https://developer.paypal.com/docs/api/payments.payouts-batch) You can have samples [here](https://github.com/paypal/PayPal-PHP-SDK/tree/master/sample/payouts)

**Comment by xiaoleih41** [comment]
Close due to inactivity. Please resubmit when you have additional info.
