### ISSUE TITLE
Create Billing Plan for a given payee

### ISSUE THREAD

**Issue by Portekoi** [paypal/PayPal-PHP-SDK#989]
I'm get used to create Payment or Billing Plan with the post method (by using `_xclick` or `_xclick-subscriptions` and hidden fields).

Now, I would like to use the API. 

I've found how to set a `Payee` in the single `Payment` method but not with a subscription / billing plan

How can you do that?

**Comment by xiaoleih41** [comment]
**Payee** is currently supported in **billing agreement** product. Only the API caller account can be the receiver for REST API at this time.

**Comment by Portekoi** [comment]
Ok so only the owner of the App can be the receiver for billing agreement  

Can you confirm, I can't change the payee by another one? Thanks.

**Comment by xiaoleih41** [comment]
You are correct. Only the owner of the app can be the receiver of the billing agreement.

**Comment by PastoriXx** [comment]
Is it planned to add the possibility of changing the payee?

**Comment by xiaoleih41** [comment]
I don't see it in the roadmap. I know we have a product called channel initiated billing not on REST API.. It's reserved for certain contracted partner only.
