### ISSUE TITLE
Third party receiver for invoicing?

### ISSUE THREAD

**Issue by karptonite** [paypal/PayPal-PHP-SDK#99]
Our site facilitates sales between third party buyers and sellers. We'd like to allow the seller to click a button on our site, and send a paypal invoice directly to the buyer, with the seller as the receiver. Is that possible with the REST API? The existing issues page https://github.com/paypal/rest-api-sdk-python/wiki/Existing-Issues-and-Unavailable%5CUpcoming-features 
says that you can't configure receiver for payments, but says nothing about missing features for invoicing. 

It looks like this is possible with the Classic API https://developer.paypal.com/docs/classic/invoicing/ht_invoicing-3p/ 
but I'd prefer to use the REST API if the feature is available.

**Comment by mbopp** [comment]
Checking in to see if there is any movement on allowing third party sellers to send invoices via the REST API?

**Comment by kishinmanglani** [comment]
Also interested in this

**Comment by jaypatel512** [comment]
Hey @mbopp @kishinmanglani ! 

I have pinged the Product Owner again for this feature, and will update the thread accordingly. The API team in constantly adding all the features we had in our classic APIs to REST as fast as possible, correcting mistakes that happened in past along the way.

**Comment by oreonix** [comment]
:+1:  on this.  Any updates on Paypal supporting the REST API for 3rd party invoicing?

**Comment by jaypatel512** [comment]
No updates yet unfortunately. But we are passing all your :+1: 's to our internal team to expedite it :)

**Comment by blakeloverain** [comment]
This is a serious issue preventing third party services (SaaS, ecommerce, etc) from implementing the REST API. It's unreasonable to request that non-technical users create their own "App" in their paypal account and copy/paste their client_id/secret here. There needs to be a way to do this via OAuth, similar to the Permissions Service - but I cannot find any information on an equivalent. If I didn't need to support PayPal, I wouldn't bother, but it seems I have to go back to the classic API. Now I need to figure out how to remain PCI compliant with the credit cards. I'd imagine there's no "vault" equivalent for the classic API's?

**Comment by jaypatel512** [comment]
Hey @blakeloverain !

Unfortunately, the permissions API is no available in REST yet, however, your use case is a perfect example for us to expedite this. I will pass on your request to the product owners down the chain. However, you can also request that by directly reaching out to [Merchant Technical Support](https://www.paypal-techsupport.com/app/ask), as they have more control over the priorities. This Issue tracker is specifically for SDK issues.

Good news is, we do have Vault APIs](http://paypal.github.io/PayPal-PHP-SDK/sample/#vault) in REST API. We have a lot of samples that will show you how exactly to use it, and you can even try it out before touching any kind of code by following steps [here](https://github.com/paypal/PayPal-PHP-SDK/wiki/Samples).

Please let me know if you run into any issues running Vault APIs and I should be able to help you.

**Comment by brandonros** [comment]
Just checking in to see if I am able to use a Permissions-obtained access token to sign a body, then pass  `X-PAYPAL-AUTHORIZATION` to make API calls on behalf of another user, or if this is still not supported?

**Comment by jaypatel512** [comment]
Internal bookkeeping: PE-198

**Comment by jaypatel512** [comment]
Hello All, 

The third party invoicing is now available in release [1.7.3](https://github.com/paypal/PayPal-PHP-SDK/releases/tag/1.7.3). 

We have attached [samples](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/invoice/CreateThirdPartyInvoice.php) to provide you better details.
