### ISSUE TITLE
set and get FailureReason

### ISSUE THREAD

**Issue by JanPet** [paypal/PayPal-PHP-SDK#990]
* SDK/Library version: 1.13.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: PHP 5.6

### Issue description
Hi, in Payment.php start at 476 are setFailureReason/getFailureReason. I have no idea to test this in sandbox . what i have to do to test this nice feature with PaymentMethod 'paypal' and setIntent 'sale'.
we need in our backend some feedback about the state and the reasons of failure.

thanks a lot.
JaPet

**Comment by xiaoleih41** [comment]
Are you looking for the negative testing for rest API? Please look into [this](https://developer.paypal.com/docs/api/nt-rest/) to see if it helps.

**Comment by xiaoleih41** [comment]
Close due to inactivity.
