### ISSUE TITLE
recurring payment with guest checkout

### ISSUE THREAD

**Issue by bardascat** [paypal/PayPal-PHP-SDK#991]
Hello,

I'm a developer and I integrated recurring payment on my website. 
When I switched to live, I noticed that my clients were not able to buy anything if they didn't have a paypal account.

So my need is to enable recurring paymennt on my website but also with the feature "GUEST CHECKOUT".

I was told by some paypal operator that I should buy the package called "ENHANCED recurring payment package" which costs 20$/month.
With this packaged I could have recurring payment with guest checkout.

I bought the package, and when I tried to test the payment again, the issue was still there, the paypal account was MANDATORY.

Now my questions are:
1. Do I need to do some extra configurations on my side to enable GUEST CHECKOUT for recurring payment? 
2. Do I have to a different api for the Enhanced Recurring payment package?

In order to integrate the paypal payment on my website I'm using the rest api:
http://paypal.github.io/PayPal-PHP-SDK/sample/doc/billing/CreatePlan.html
http://paypal.github.io/PayPal-PHP-SDK/sample/doc/billing/UpdatePlan.html
http://paypal.github.io/PayPal-PHP-SDK/sample/doc/billing/CreateBillingAgreementWithPayPal.html
http://paypal.github.io/PayPal-PHP-SDK/sample/doc/billing/ExecuteAgreement.html

I hardly need a response, as currently payment is not functional on my website.
Thanks,
Catalin

**Comment by xiaoleih41** [comment]
That's a different product which doesn't use REST API. Please check [here](https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/auto_bill_step_1/) for detail.

**Comment by bardascat** [comment]
Hello,
Thanks for sharing with me that info.
If I will choose the "subscribe" button (the "non" rest api approach) - In this case will I be able to use webhooks ? 

For example If a client cancel the recurring payment, how will I be notified ? 
With the rest api I would use the webhooks communication.

Thanks

**Comment by xiaoleih41** [comment]
I don't think webhook work with this product. Please look into IPN instead.

**Comment by xiaoleih41** [comment]
Close as the answer has been given.
