### ISSUE TITLE
Paypal Rest API Errors in Sandbox

### ISSUE THREAD

**Issue by xcrap** [paypal/PayPal-PHP-SDK#992]
### General information

* SDK/Library version: 1.13.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: 75191b9ba7473
* Language, language version, and OS: PHP 7.0.22

### Issue description

I'm having some errors when trying my Paypal Rest Api in Sandbox mode after paying.

[19-11-2017 23:30:51] PayPal\Core\PayPalHttpConnection : ERROR: Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment/PAY-4MS83271FG5446309LIJCECY/execute. {"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"75191b9ba7473"}

The very strange thing is that sometimes it works, sometimes don't. 

This is my response code.

```php
if (isset($_GET['success']) && $_GET['success'] == 'true')
   {
    $paymentId = $_GET['paymentId'];
    $payment = Payment::get($paymentId, $apiContext);
    $execution = new PaymentExecution();
    $execution->setPayerId($_GET['PayerID']);
    try {
        $result = $payment->execute($execution, $apiContext);
        try {
            $payment = Payment::get($paymentId, $apiContext);
        } catch (Exception $ex) {
            // echo "Sub Error <br />".$ex->getCode()."<br />".$ex->getData();
            header('Location:'.$path.'results/?success=error_paypal');
            exit(1);
        }
    } catch (Exception $ex) {
        //echo "Main Error <br />".$ex->getCode()."<br />".$ex->getData();
        $error_object = json_decode($ex->getData());
        switch ($error_object->name)
            {
            case 'PAYMENT_ALREADY_DONE':
                header('Location:'.$path.'results/?success=error_paypal_alreadypaid');
                exit(1);
                break;
            }

        header('Location:'.$path.'results/?success=error_paypal');
        exit(1);
    }

    // echo 'Paid '.$payment->getId();
    $transactionID = $payment->getId();
    $query = mysqli_query($db_connect, "UPDATE cms_orders SET cms_date_updated = now(), cms_status = '1' WHERE cms_order_transactionID = '$transactionID' LIMIT 1");
    if (mysqli_affected_rows($db_connect) == 1) header('Location:'.$path.'results/?success=true&transactionID='.$payment->getId());
    return $payment;
    }

else
    {
    header('Location:'.$path.'results/?success=cancel');
    exit();
    }
```

Most of the times it works, I get a successful $transactionID , but sometimes I get those 500 error in the first catch exception. Just a note that my Developers account shows error in all my sandbox accounts, everytime I create a sandbox account it gets processing but they it display error.

It was before It changed to error that I was able to create my App, I can still test and sometimes works but sometimes I get that error, any idea of what's wrong, and also what can be wrong with this sandbox accounts always giving me errors ?

<img width="887" alt="screen shot 2017-11-19 at 23 46 49" src="https://user-images.githubusercontent.com/828596/32997793-18b68ab6-cd84-11e7-8eca-8e41cb02e4b3.png">

**Comment by Razorholt** [comment]
Same thing here!

Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment/PAY-2JC250095N5752841LIJG2WY/execute.

{
    "name": "INTERNAL_SERVICE_ERROR",
    "details": [],
    "message": "An internal service error has occurred",
    "information_link": "https://developer.paypal.com/docs/api/payments/#errors",
    "debug_id": "ee522eed7a3d5"
}

**Comment by xcrap** [comment]
Well this is happening since yesterday. And the sandbox error accounts I have for more than 4 days.. so.. I have no clue.

**Comment by israelbenzaken** [comment]
Same here!

When I'm trying Paypal Sandbox mode after paying.

sometimes it works, sometimes don't.

object(stdClass)#42 (4) {
--
  | ["name"]=>
  | string(22) "INTERNAL_SERVICE_ERROR"
  | ["message"]=>
  | string(38) "An internal service error has occurred"
  | ["information_link"]=>
  | string(54) "https://developer.paypal.com/docs/api/payments/#errors"
  | ["debug_id"]=>
  | string(13) "e7e3cee6d1620"
  | }

Answer?

**Comment by xiaoleih41** [comment]
@xcrap The sandbox environment has some issue recently. I cannot reproduce eithe rof your errors. Can you clean the cache and try to clear all the old sandbox accounts and start from scratch and create a new account? 
@Razorholt  your issue appears to be different and temporary. If it persists, please file a ticket at www.paypal-techsupport.com for them to track the issue. 
@israelbenzaken Your issue is different. I am not sure what exact API call you were trying to make. there's some permission issue involved. You may try to make the call with a US account instead.

**Comment by xcrap** [comment]
I've tried without success.

I've clear all data, cookies, history etc from Chrome, Safari and Firefox.
When i try to remove a Sandbox account I already get this "Something went wrong. One or more sandbox accounts could not be deleted. Try again.".

Even the two sandbox accounts that are created automatically are in Error Status.
I need to use this account because that's my client account to go the Live Mode after.... I really don't understand why  I cannot even remove my sandbox accounts.

I've left a ticket for www.paypal-techsupport.com 3 days ago without  any response.
Help ?

**Comment by xiaoleih41** [comment]
Can you give me your ticket number? I will escalate this for you. As it's account specific issue so it will be better to handled by tech support.

**Comment by xcrap** [comment]
Ref:  171116-000348

**Comment by xiaoleih41** [comment]
I am following up for you. Someone should contact you soon.

**Comment by xiaoleih41** [comment]
Can you try again @xcrap? I was told an issue was solved on Nov 20.

**Comment by xcrap** [comment]
@xiaoleih41 everthing is working fine now, I stop having the errors and I the last two sandbox accounts were created successfully. Unfortunately I cannot still remove the old "error" sandbox accounts and it looks a mess the Developers Account.

**Comment by xiaoleih41** [comment]
I understand. In mid-Dec, we will push out a fix which should address this issue.

**Comment by xcrap** [comment]
Perfect! :D

**Comment by xcrap** [comment]
Now that the sandbox accounts where working and I went today to Live Mode and got this!

{"error":"invalid_client","error_description":"Client Authentication failed"}

I've tried generating a new key but without success!!
Help ?

**Comment by janzheng** [comment]
I'm getting REST API "BAD REQUEST" 400 errors, so some of your fixes must have caused some other problems? Frustrating as even the developers.paypal.com examples don't work.

**Comment by xiaoleih41** [comment]
@janzheng Can you please submit a new issue? You 400 error is different from this issue's 500 error. do you have a debug ID? I just tested the button on the site, it looks fine and the payment was completed.
