### ISSUE TITLE
Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payouts?

### ISSUE THREAD

**Issue by sivabalan02** [paypal/PayPal-PHP-SDK#993]
### General information

* SDK/Library version: paypal/rest-api-sdk-php 1.13.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: 3526557536df0
* Language, language version, and OS: PHP 7.1.7, Windows 7

### Issue description

When i make a payout payment i getting this error Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payouts?

**Comment by xiaoleih41** [comment]
Please Use your own  app credentials to make the call. It may fix the issue.

**Comment by sivabalan02** [comment]
@xiaoleih41 Thank you for the reply. I will check the client id and secret key once again. I have one more doubt. For batch payout also i need call payment approval api?

**Comment by xiaoleih41** [comment]
It doesn't need buyer to approve, if that's what you were referring to. [CreateBatchPayout]( https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payouts/CreateBatchPayout.php) should be sufficient.

**Comment by xiaoleih41** [comment]
close as the answer has been given.
