### ISSUE TITLE
How-to resolve payment conflicts

### ISSUE THREAD

**Issue by Sebi94nbg** [paypal/PayPal-PHP-SDK#994]
Customers can open a conflict for payments.

This usually happens, after the PayPal API has contacted our system, that the payment was successful.

Well... The money was charged successful for the customer, but he is holding back the money, until he marks the conflict as solved.

I would expect, that the API sends a POST request to my defined notification URL, where I can see something like `State: Conflict`. Then my application could remove the customers payment and appear like it was before: Payment did not happen yet.

When the customer marks the conflict as solved, the API would inform me once again about this new state (eg. `conflict_solved`) and I could undo the last payment change for the customer.

Does the API handle conflicts? What's the best practice to handle such payment conflicts? Is there any documentation for? I couldn't find one.

**Comment by xiaoleih41** [comment]
Are you talking about dispute API? PayPal will have dispute API available next year. For the time being, you will have to log into your PayPal account and resolve the issue inside of the resolution center. You can subscribe IPN to get notification. For detail, please check [here](https://developer.paypal.com/docs/classic/products/instant-payment-notification/)

**Comment by xiaoleih41** [comment]
Close as answer has been given
