### ISSUE TITLE
Webhooks not working in sandbox mode

### ISSUE THREAD

**Issue by Schottii** [paypal/PayPal-PHP-SDK#996]
Hey I am currently using this library to implement PayPal-payments and today webhooks stoped working for me.
Do you experience the same? I tried the samples and they are also not woking anymore for me. I tried to trigger a **PAYMENT.SALE.COMPLETED** webhook, but I dont receive any callback from paypal anymore even if I change the url to requestb.in.

As far as I now, there where multiple downtimes of the webhooks in sandbox mode. Is this maybe another one?

Kind regards

**Comment by xiaoleih41** [comment]
Has the issue solved? I cannot reproduce the error but please let me know.

**Comment by Martos** [comment]
I have the same issue with the latest version of sdk

**Comment by pp-randy** [comment]
Do you have a webhook listener registered @Martos? Do they show up on the Developer Dashboard?

**Comment by pp-randy** [comment]
Tagging a possible related issue: https://github.com/paypal/PayPal-REST-API-issues/issues/173

**Comment by Martos** [comment]
I have registrered the webhook on PayPal developer and when i get the list of webhook in code, i get the same webhook registered in the PayPal developer page.

**Comment by pp-randy** [comment]
@Martos is the issue for you the webhooks not being received?

**Comment by Martos** [comment]
When i use the simulator, i receive the webhook correctly

**Comment by pp-randy** [comment]
@Martos is this for a credit card or PayPal payment?  Webhooks for credit card payments were never added to the API. If this is for a PayPal payment, can you grab the paypal-debug-id from the response headers so I can review our logging for the webhook?

**Comment by Martos** [comment]
This is the Paypal-debug-id : 1fa2f69dff9e

**Comment by pp-randy** [comment]
@Martos you need to execute the payment to complete it 
https://developer.paypal.com/docs/api/payments/#payment_execute.  A webhook won't get sent if the payment isn't executed.

**Comment by Martos** [comment]
I have setted the webhook in paypal developer with all events and pay with paypal sample code in the wiki of this sdk. This can't fire an webhook ?

**Comment by pp-randy** [comment]
What was the transaction id that was generated?  Which sample are you using?  For a Payment you would need https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/ExecutePayment.php to complete.  I looked at your accounts I could find using your debug id and see no recent transactions.

**Comment by Martos** [comment]
How i can use Paypal debug id ?

**Comment by pp-randy** [comment]
@Martos are you calling Execute Payment to complete your payments?   Can you provide any JSON response the Paypal-debug-id for the Execute Payment API response?

**Comment by xiaoleih41** [comment]
Close the issue due to inactivity. Please resubmit when you have additional information.
