### ISSUE TITLE
Merchant Account not updated but transaction is showing on history

### ISSUE THREAD

**Issue by kimpoy010** [paypal/PayPal-PHP-SDK#997]
I was able to successfully implement paypal payments on my website, but when I check each account, the seller account balance was not updated, but the transaction is shown in the transactions history, buyer account is working and was debited.

This happens on sandbox. I haven't tried it yet on production.

this is my code for the payment approval

    $sched = Schedule::find($request['sched_id']);
    $paypal = new \PayPal\Rest\ApiContext(
        new \PayPal\Auth\OAuthTokenCredential(
            'inserted_my_client_id_here',     // ClientID
            inserted_app_secret_key_here'      // ClientSecret
        )
    );

    $payer = new \PayPal\Api\Payer();
    $payer->setPaymentMethod('paypal');

    $amount = new \PayPal\Api\Amount();
    $amount->setCurrency("JPY")
                ->setTotal($sched->amount);
    

    $transaction = new \PayPal\Api\Transaction();
    $transaction->setAmount($amount)
        ->setDescription("Lesson payment")
        ->setInvoiceNumber(uniqid());

    $redirectUrls = new \PayPal\Api\RedirectUrls();
    $redirectUrls->setReturnUrl(route('paypal.return',$request['sched_id']))
                ->setCancelUrl(route('pages.profile'));

    $payment = new \PayPal\Api\Payment();
    $payment->setIntent('sale')
        ->setPayer($payer)
        ->setTransactions(array($transaction))
        ->setRedirectUrls($redirectUrls);

    try {
        $payment->create($paypal);
        return redirect($payment->getApprovalLink());
    }
    catch (\PayPal\Exception\PayPalConnectionException $ex) {
        echo $ex->getData();
    }`

and this is my code for the processing of payment

    ` 
    $sched = Schedule::find($id);
    $payID = $_GET['paymentId'];
    $payerID = $_GET['PayerID'];

    $paypal = new \PayPal\Rest\ApiContext(
        new \PayPal\Auth\OAuthTokenCredential(
            'inserted_my_client_id_here',     // ClientID
            inserted_app_secret_key_here'      // ClientSecret
        )
    );

    $payment = \PayPal\Api\Payment::get($payID, $paypal);

    $execution = new \PayPal\Api\PaymentExecution();
    $execution->setPayerId($payerID);

    $transaction = new \PayPal\Api\Transaction();
    $amount = new \PayPal\Api\Amount();

    $amount->setCurrency('JPY');
    $amount->setTotal($sched->amount);
    $transaction->setAmount($amount);

    $execution->addTransaction($transaction);

    try {
        $result = $payment->execute($execution, $paypal);
        try {
            $payment = \PayPal\Api\Payment::get($payID, $paypal);
        } catch (Exception $e) {
            return response($e->getMessage);
            exit(1);
        }
    } catch (Exception $e) {
        return response($e->getMessage);
        exit(1);
    }

    // Session::flash('success','Successfully paid lesson fee!');
    // return redirect()->route('pages.profile');

    return response($payment);`

Here is a sample Transaction ID from  the merchant sandbox account

Transaction ID: 84P12283VA318733V 

what am I doing wrong here?
Thanks

**Comment by xiaoleih41** [comment]
There's some delay sometimes. it should reflect on your site now. Please check.

**Comment by kimpoy010** [comment]
I checked the sandbox account, still now updated, but transactions are shown in transaction history.

A sample transaction ID: 0MM42369RG3380025

This test payment was sent last November 26, 2017 still the same amount is reflecting on merchant account's balance.

**Comment by xiaoleih41** [comment]
I have reported this issue. However as it's a sandbox environment dealing with fake currency, it does have issue in reflecting correct running balance. Please go to activity log and download the activity instead as it should reflect the correct running balance.

**Comment by xiaoleih41** [comment]
I am closing this issue and please track the issue https://github.com/paypal/PayPal-REST-API-issues/issues/169 going forward for the updates.

**Comment by lds-engineers** [comment]
i am not getting response at paypal success page.

**Comment by xiaoleih41** [comment]
@lds-engineers Can you please open a new issue with debugID and detail description of the issue itself.
